### PR TITLE
harfbuzz: reinstate GRAPHITE2_STATIC workaround dropped with meson port

### LINKED ISSUE #6506: Harfbuzz can't find symbols from graphite2
with the latest commit the fix for  #2635 was reverted so the issue arose again

### PR DESCRIPTION
**Pull request by lazka**
Fixes #6506

### CODE REVIEW

**Comment by hessenfarmer** [comment]
if youi would provide me a new built copy of the x64 libharfbuzz.a and the x86 libharfbuzz.a I'll try to integrte them into my environment to test this. Or yopu provide me a link from where to pacman your version.

**Comment by lazka** [comment]
[harfbuzz.zip](https://github.com/msys2/MINGW-packages/files/4669267/harfbuzz.zip)

**Comment by hessenfarmer** [comment]
Have tested a static link as well as a dynamic link build of our project. Everything linked fine and ran so this should work again. Thanks for the fix

**Comment by lazka** [comment]
thanks for testing

**Comment by hessenfarmer** [comment]
Ok thanks when will this be available in the repo?

**Comment by lazka** [comment]
@hessenfarmer it is now

**Comment by hessenfarmer** [comment]
I have seen it many thanks so far. 
However one short question: when I try to do a static link of the package with mingw32 of msys2 running as a 64bit installation I get 2 linking errors for undefined references to some uniscribe functions (provided by Microsoft usp10.dll respectively usp10.h). I don't get them doing a mingw64 static build. Any ideas or explanations? I assume for 64 bit builds Mingw64 takes some library from my system which is 64 bit and it doesn't find the respective 32 bit version on my system. Perhaps you could provide me with a short guide how to build the package without uniscribe, as I think we don't need it. 
here is the error shown by mingw 
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../lib\libharfbuzz.a(hb-uniscribe.cc.obj):(.text+0xe3): undefined reference to `ScriptShape@40'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../lib\libharfbuzz.a(hb-uniscribe.cc.obj):(.text+0x12b): undefined reference to `ScriptItemize@28'

thanks for your help and patience

**Pull request merged**
