### PR TITLE
gcc: backport patch for cpuid.h header guard

### PR DESCRIPTION
**Pull request by 1480c1**
/cc @Biswa96

### CODE REVIEW

**Comment by 1480c1** [comment]
waiting for CI to tell if it actually applies, haven't tested locally, although idk build time of gcc

**Comment by mati865** [comment]
You forgot to attach the patch.

**Comment by 1480c1** [comment]
darn

**Comment by lazka** [comment]
> waiting for CI to tell if it actually applies, haven't tested locally, although idk build time of gcc

around 2h50 all together

**Comment by lazka** [comment]
ok to merge?

**Comment by 1480c1** [comment]
Yeah, CI didn't complain, so it's probably fine

**Comment by jeremyd2019** [comment]
I think this broke in combination with mingw-w64 version of `__cpuidex`:
https://github.com/msys2/MINGW-packages/pull/9082/checks?check_run_id=2981533749#step:9:496

/cc @lhmouse

**Comment by lazka** [comment]
yeah, https://github.com/mirror/mingw-w64/commit/d2374f898457b0f4ea8bd4084a94f2dafc87a99a

So we need to revert this until gcc 11 from what I see.

**Comment by lazka** [comment]
reverted in master

**Comment by jeremyd2019** [comment]
Now it fails with:
```
  In file included from C:/_/mingw-w64-openal/src/openal-soft-openal-soft-1.21.0/alc/cpu_caps.cpp:10:
  D:/a/_temp/msys/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/include/cpuid.h:228:1: error: redefinition of 'unsigned int __get_cpuid_max(unsigned int, unsigned int*)'
    228 | __get_cpuid_max (unsigned int __ext, unsigned int *__sig)
        | ^~~~~~~~~~~~~~~
  In file included from D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/intrin.h:70,
                   from C:/_/mingw-w64-openal/src/openal-soft-openal-soft-1.21.0/alc/cpu_caps.cpp:7:
  D:/a/_temp/msys/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/include/cpuid.h:228:1: note: 'unsigned int __get_cpuid_max(unsigned int, unsigned int*)' previously defined here
    228 | __get_cpuid_max (unsigned int __ext, unsigned int *__sig)
        | ^~~~~~~~~~~~~~~
```

I think this is due to the lack of an include guard, which was added in the patch reverted, but that patch also added a new function that caused a conflict with mingw-w64.  I wonder if it would be possible to "split" that patch and only apply the include guard, not the new function.

**Comment by lazka** [comment]
>  I wonder if it would be possible to "split" that patch and only apply the include guard, not the new function.

worth a try I guess

**Pull request merged**
