### PR TITLE
opencollada: Remove huge pointless patch

### PR DESCRIPTION
**Pull request by orgads**
7.7M patch for indentation?

### CODE REVIEW

**Comment by lazka** [comment]
@Alexpux do you remember why you added that?

**Comment by Alexpux** [comment]
@orgads @lazka this patch solving GCC warnings about identations and guards so I will not allow to drop it

**Comment by elieux** [comment]
Could we instead add something like `-Wno-indentation`?

**Comment by orgads** [comment]
> Could we instead add something like `-Wno-indentation`?

That's exactly what I'm testing now.

**Comment by Alexpux** [comment]
What problem with this patch? Devs write dirty code so you want to fix it by flags?

**Comment by elieux** [comment]
Wow, this build is riddled with warnings; lots of case fallthroughs.

**Comment by Alexpux** [comment]
as i tell i will not drop it

**Comment by elieux** [comment]
@Alexpux, does the patch fix the code or just remove some warnings?

**Comment by Alexpux** [comment]
@elieux it remove warnings, but also can fix some errors becasue of missinterpreting code by compiler

**Comment by orgads** [comment]
I fail to see the value of having a 7M patch which effectively rewrites most of the application.

It's not like the patch actually fixes any behavioral issue. It merely keeps GCC happy. For that, we could either suppress `-Wmisleading-indentation`, or even suppress all compiler warnings.

I successfully built it without the patch without any errors (but there *are* a lot of warnings, regardless of the patch).

**Comment by elieux** [comment]
Assuming it's *only* indentation and no code changes, I don't think the patch helps us in any way. The patch would make sense if gets into upstream, but we are only using the source files to build a package and then the fixed sources are essentially thrown away. *And* it forces more work on us when we upgrade to the next release of opencollada.

**Comment by Alexpux** [comment]
There are no commits to it since 2018

**Comment by orgads** [comment]
I just pushed a revised commit that disables the warnings.

I verified that the 7M patch does nothing but indentation changes (`git diff -w` shows nothing).

Please consider reopening.

**Comment by orgads** [comment]
https://github.com/orgads/MINGW-packages/commit/37b608da83708a2b0fbb0baa965e111295ed7573

**Comment by Alexpux** [comment]
cant reopen

**Comment by orgads** [comment]
Created #6542.

**Pull request closed without merging**
