### PR TITLE
ccache: update to 4.10

### LINKED ISSUE #21032: [ccache] update to 4.10
### Package name

ccache

### New version number

4.10

### Other information that may be useful

_No response_

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by ognevny**
the patch is not required now
fixes #21032

### CODE REVIEW

**Comment by ognevny** [comment]
I didn't have any issue locally...

**Comment by silverqx** [comment]
Failing, the patch is still needed?

**Comment by ognevny** [comment]
> Failing, the patch is still needed?

I guess I need to add fmt as makedepend

**Comment by ognevny** [comment]
> > Failing, the patch is still needed?
> 
> I guess I need to add fmt as makedepend

I also pushed xxhash as dependency

**Comment by silverqx** [comment]
It compiled fine w/o it, why is needed.

**Comment by ognevny** [comment]
> It compiled fine w/o it, why is needed.

msys2 provides a shared library for it, why not?

**Comment by silverqx** [comment]
Ok I see, ccache downloads it and builds if not avail. locally. 👍

**Review by silverqx — APPROVED** [review]
Nice, thx for asap upgrade 👌 LGTM

**Pull request merged**
