### PR TITLE
imath: Add package for openexr

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/10396

Please review @revelator @kmilos

### CODE REVIEW

**Comment by kmilos** [comment]
Thanks for moving forward w/ this!

LGTM, but do we need to handle conflicts w/ legacy `ilmbase` from OpenEXR 2.5 (the Half library etc.)? Any chance we can bump OpenEXR at the same time? Would love to help, but short on time lately 😞

**Comment by kmilos** [comment]
Scratch that, just saw you did it already!!! 👍

**Comment by Biswa96** [comment]
> but do we need to handle conflicts w/ legacy ilmbase from OpenEXR 2.5 (the Half library etc.)?

Yea, I am about to ask that. I can not figure out how to solve the conflicts. The files from ilmbase are scattered between imath and openexr. If I tried to add provides/conflicts/replaces in both packages CI failed with error.

There is another thing that I can not figure out. The clang build fails with a C++ error. Jeremy provided me some information about that same error with kirigami-qt5 package. But the rabbit hole is too dark for me.

**Comment by kmilos** [comment]
I guess we make all packages that were depending on ilmbase depend on OpenEXR on to be safe? Or we start dissecting what exactly they need...

**Comment by Biswa96** [comment]
Yes, dependent packages have to be rebuilt. But replacing the ilmbase with openexr in _depends_ list would not solve the file conflicts at install time, right?

**Comment by jeremyd2019** [comment]
> There is another thing that I can not figure out. The clang build fails with a C++ error. Jeremy provided me some information about that same error with kirigami-qt5 package. But the rabbit hole is too dark for me.

For the record, this was llvm/llvm-project#37457

**Comment by kmilos** [comment]
And I see now you already build all the Python bindings, but might be an idea to package them separately as `pyimath` and conflict/replace `pyilmbase` as well?

**Comment by kmilos** [comment]
Actually, might be ok to start including the Python bindings in the main package like https://packages.msys2.org/base/mingw-w64-openimageio (and have the optional python dependency), but I guess we still need the conflicts/replaces w/ the old separate Python bindings package...

**Comment by kmilos** [comment]
FYI, 3.1.5 is available, can drop some patches...

**Comment by revelator** [comment]
sorry been away  a while due to problems with some screws in my back getting loose :S, changes look ok to me so far but let me see if anything crops up as i notice numerous changes lately.

**Comment by Biswa96** [comment]
Need to fix two things - clang build and provides/replaces/conflicts entries. I have not figured those out yet. Suggestions/fixes are welcomed.

**Comment by kmilos** [comment]
> FYI, 3.1.5 is available, can drop some patches...

OpenEXR is bumped to 3.1.5 now as well.

> provides/replaces/conflicts entries

How about just

`replaces=("${MINGW_PACKAGE_PREFIX}-ilmbase" "${MINGW_PACKAGE_PREFIX}-pyilmbase")`

for `imath`? Should be it, no?

**Pull request closed without merging**
