### PR TITLE
[new-package] tbb 2021.4.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Arch Linux package : https://archlinux.org/packages/testing/x86_64/tbb/

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
I need it to update openimageio to 2.3.10.0 as It fails to link with the intel-tbb.

**Comment by lazka** [comment]
hm, this replaces intel-tbb but doesn't provide the same DLLs so will break all reverse deps. Should we remove the "replaces" for now?

**Comment by MehdiChinoune** [comment]
> hm, this replaces intel-tbb but doesn't provide the same DLLs so will break all reverse deps. Should we remove the "replaces" for now?

I think some of those DLLs could provide the old one, I will try to get a solution in the coming days.

**Comment by MehdiChinoune** [comment]
For now, you could remove 'replaces'.

**Comment by lazka** [comment]
ok

**Pull request merged**
