### PR TITLE
Build full libdazzle

### LINKED ISSUE #7255: Build full libdazzle
Right now libdazzle is half builded to support  some pango utils related to font and css. See all the code discarted:

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libdazzle/0001-windows-Build-pango_font_description_to_css-on-windo.patch#L60

There are some tries to adapt codebase to win32:

- https://gitlab.gnome.org/GNOME/libdazzle/-/merge_requests/37
- https://gitlab.gnome.org/GNOME/libdazzle/-/merge_requests/48

@taozuhong we should open a PR here, removing that patch and adding a win32 one until upstream code is merged.

### PR DESCRIPTION
**Pull request by albfan**
@taozuhong this is an example to track changes and get feedback from win team side.
@lazka, @Alexpux any tip is appreciated

fixes #7255

### CODE REVIEW

**Comment by lazka** [comment]
Any background info on the G_STATIC_ASSERT changes?

**Comment by taozuhong** [comment]
it needs to get the main branch to apply the patch.

**Comment by albfan** [comment]
@lazka looks like they fix build on libdazzle master:

https://gitlab.gnome.org/GNOME/libdazzle/-/commit/3ccef8c092cc33cd6678185a19eda57a85685b9e

Still no tarball I guess.

**Comment by lazka** [comment]
ah, ok. Now someone needs to make it build :)

**Pull request merged**
