### PR TITLE
fix qml plugin from kitemmodels installed to incorrect dir

### PR DESCRIPTION
**Pull request by BLumia**
Resolve https://github.com/msys2/MINGW-packages/issues/13698

### CODE REVIEW

**Comment by Biswa96** [comment]
Please bump the pkgrel variable.

**Comment by Biswa96** [comment]
Is this ready to merge?

**Comment by Biswa96** [comment]
I did not see your merge request in upstream. Should we wait for that patch to be merged? We can import the patch from upstream in PKGBUILD. That may be better than my lazy workaround.

**Comment by BLumia** [comment]
> I did not see your merge request in upstream.

https://invent.kde.org/frameworks/kitemmodels/-/merge_requests/49/diffs

> Should we wait for that patch to be merged? We can import the patch from upstream in PKGBUILD. That may be better than my lazy workaround.

Personally I think your patch is perfect for the current case, since we only care about MSYS2 package build, your patch just done the fix and didn't touch any other part of the project (won't affact existing tests, file generation and resource processing, etc.). If my upstreamed patch get merged then we can drop the current patch when we upgrade the package to that version. My 2cents :)

**Pull request merged**
