### PR TITLE
flatbuffers: Update to 2.0.5

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
I have some doubts about the 0002 patch file. Can anyone provide any info about the "py" command? Without the 0002 patch I get this type of errror:

```
py scripts/generate_code.py --flatc build_dir/flatc.exe
'py' is not recognized as an internal or external command, operable program or batch file.
```

Are the patch files correct? I shall send those to upstream first.

**Comment by naveen521kk** [comment]
> Can anyone provide any info about the "py" command?

https://docs.python.org/3/using/windows.html#from-the-command-line If you run that on CI then MSVC python installed would be used instead of one installed by Pacman.

**Comment by raedrizqie** [comment]
> > Can anyone provide any info about the "py" command?
> 
> https://docs.python.org/3/using/windows.html#from-the-command-line If you run that on CI then MSVC python installed would be used instead of one installed by Pacman.

yes.. it uses the registry to find the default python

**Comment by Biswa96** [comment]
Thanks for the info. I thought that it somehow comes from find_package() call. Any opinion about those new patches?

**Comment by naveen521kk** [comment]
> Any opinion about those new patches?

Lgtm.

**Comment by Biswa96** [comment]
Well then. I have sent those patches to upstream. Then I added the links of those pull request here.

**Pull request merged**
