### PR TITLE
templates: Pass build directory as command line option of build system

### PR DESCRIPTION
**Pull request by Biswa96**
This helps to rule out all the cd commands and jumping between various directories.

### CODE REVIEW

**Comment by ognevny** [comment]
so it's better to apply this change for all packages with cmake/meson?

**Comment by Biswa96** [comment]
> so it's better to apply this change for all packages with cmake/meson? (after merge)

IMO, it is not required to change all the PKGBUILDs but new packages may follow these templates.

**Comment by ognevny** [comment]
> > so it's better to apply this change for all packages with cmake/meson? (after merge)
> 
> IMO, it is not required to change all the PKGBUILDs but new packages may follow these templates.

what about package updates? there is not merged yet update for shaderc

**Comment by Biswa96** [comment]
> what about package updates? there is not merged yet update for shaderc

It can be kept as is. As I said, only new PKGBUILDs which will be added later.

**Pull request merged**
