### PR TITLE
libdazzle: patched 1.0

### PR DESCRIPTION
**Pull request by albfan**
Needed for gitg 3.32.1 #5647

This is a patched version to access to utils avaliable in libdazzle to convert a font description into a css

### CODE REVIEW

**Comment by Alexpux** [comment]
@albfan add gobject-introspection to makedeps

**Comment by Alexpux** [comment]
@albfan why you remove nearly all sources from build?

**Comment by albfan** [comment]
@Alexpux in gtk, pango translates its font description to css, but is not a public function. in libdazzle this is available in: 

https://valadoc.org/libdazzle-1.0/Dazzle.pango_font_description_to_css.html

so gitg uses it.

There're some problems to build libddazzle on windows. 

https://gitlab.gnome.org/GNOME/libdazzle/merge_requests/37

If we can merge this, someone can improve the patch (or we can resolve the MR on libdazzle at some point)

**Comment by albfan** [comment]
@Alexpux, @chergert would accept win32/64 fixes on libdazzle, so if you can show your expertise on https://gitlab.gnome.org/GNOME/libdazzle/merge_requests/37, that would be really appreciated and really useful as example for other win32 ports.

**Comment by taozuhong** [comment]
@albfan 
I have installed the libdazzle-1.0, found its header files missing, could you take a moment to check it?

**Comment by albfan** [comment]
@taozuhong see there're problems to build whole libdazzle. What headers are you missing? Better open a new issue about libdazzle.

We need to review libdazzle for tree features so we can add this too.

**Comment by taozuhong** [comment]
I've submitted a patch to fix all compiler error on msys2, will fix them all at the next version.

**Comment by albfan** [comment]
@taozuhong any link? I can't find any PR or branch in your fork about that

**Comment by taozuhong** [comment]
Here is the PR for libdazzle:
https://gitlab.gnome.org/GNOME/libdazzle/-/merge_requests/48

**Comment by albfan** [comment]
@taozuhong let's drive this in proper way, opening an issue #7255 

Let's comment there, and create a PR any progress on upstream libdazzle gitlab repo. Probably @lazka  and @Alexpux could help doing that.

**Pull request merged**
