### PR TITLE
[mingw-w64-vulkan-validation-layers] Fixes validation layers manifests install folder + shared library exposed functions

### PR DESCRIPTION
**Pull request by Amphaal**
Solves #8030 in its entirety.

### CODE REVIEW

**Comment by lazka** [comment]
ok, so this fixes the exports for 64bit, but breaks the symbol naming for 32bit because it removes the stdcall name mangling. So a step in the right direction, but not ideal. I'll see if I can figure this out.

**Comment by lazka** [comment]
Turns out VK_LAYER_EXPORT was also exported in vulka-headers, making our patch not work as intended... (maybe that got added later). Patched there too now.

**Comment by lazka** [comment]
It exports correctly now, but more than on Linux since they use `-Wl,--version-script` there to filter out symbols and we don't have that. Hopefully not that big of a problem. If not we can have another look.

**Comment by Amphaal** [comment]
Many thanks for your work !

**Pull request merged**
