### PR TITLE
qemu: update to 9.1.0

### PR DESCRIPTION
**Pull request by heljkon**
see https://wiki.qemu.org/ChangeLog/9.1

### CODE REVIEW

**Comment by heljkon** [comment]
For the clang64 build failure: https://gitlab.com/qemu-project/qemu/-/issues/2476

**Comment by heljkon** [comment]
@lazka @Biswa96 @jeremyd2019
Based on ticket [Regression 9.1.0-rc0: Msys2/Clang64 build fails](https://gitlab.com/qemu-project/qemu/-/issues/2476) in QEMU repository a discussion came up about the fitness of CLANG64/CLANGARM64 for QEMU.

[thuth](https://gitlab.com/thuth), a core QEMU developer stated:

> Ok, so Clang does not support gcc_struct yet. You should not use it to build QEMU on MSYS2. While 95% of such a build might work fine, there are likely some emulated devices where this gcc_struct attribute makes a difference and those won't work in such a build.

As I am only contributing to msys2, I ask you the members of msys2 for discussion and decision.

**Comment by lazka** [comment]
If upstream doesn't want to fix their struct packing to not depend on gcc_struct there is not much we can do I guess.

Not sure, your call.

I look at why they added it in the first place: https://lists.gnu.org/archive/html/qemu-devel/2011-08/msg01877.html

**Comment by jeremyd2019** [comment]
> [thuth](https://gitlab.com/thuth), a core QEMU developer stated:
> 
> > Ok, so Clang does not support gcc_struct yet. You should not use it to build QEMU on MSYS2. While 95% of such a build might work fine, there are likely some emulated devices where this gcc_struct attribute makes a difference and those won't work in such a build.

@mstorsjo are you aware of this limitation?  I figured clang has to support both struct packing styles, since it emulates both gcc and msvc frontends, but I guess maybe not both on the same target?

**Comment by mstorsjo** [comment]
> > [thuth](https://gitlab.com/thuth), a core QEMU developer stated:
> > > Ok, so Clang does not support gcc_struct yet. You should not use it to build QEMU on MSYS2. While 95% of such a build might work fine, there are likely some emulated devices where this gcc_struct attribute makes a difference and those won't work in such a build.
> 
> @mstorsjo are you aware of this limitation? I figured clang has to support both struct packing styles, since it emulates both gcc and msvc frontends, but I guess maybe not both on the same target?

Yes, I'm aware of this. It's indeed a case where Clang does support both, it just doesn't support the attribute. It does IIRC support `ms_struct` for opting in to the MS struct layout when building for a target that otherwise uses the default layout, but it doesn't yet support `gcc_struct` for requesting the reverse, when building in a configuration where the MS layout is the default. See https://github.com/llvm/llvm-project/issues/24757 for the general tracking issue, and https://github.com/llvm/llvm-project/pull/71148 for a recent PR that attempts to implement this.

**Comment by heljkon** [comment]
@lazka @Biswa96 @jeremyd2019 @mstorsjo 
Upstream has added a compiler test to make sure, CLANG64 is not build. I don't want to patch this, so I've disabled clang builds.
```
==> Starting build()...
...
../qemu-9.1.0-rc3/meson.build:321:4: ERROR: Problem encountered: Your compiler does not support __attribute__((gcc_struct)) - please use GCC instead of Clang

A full log can be found at .../mingw-w64-qemu/src/build-CLANG64/meson-logs/meson-log.txt

ERROR: meson setup failed

==> ERROR: A failure occurred in build().
    Aborting...
```
 .../mingw-w64-qemu/src/build-CLANG64/meson-logs/meson-log.txt:
```
-----------
Command line: `clang++ -m64 ../tmpud8icv9j/testfile.cpp -o ../tmpud8icv9j/output.obj -c -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument -std=gnu++11` -> 0
Running compile:
Working directory:  ./
Code:
struct x { int y; } __attribute__((gcc_struct));
-----------
Command line: `clang++ -m64 ../tmpoo9iwq6a/testfile.cpp -o ../tmpoo9iwq6a/output.obj -c -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument -std=gnu++11 -Werror` -> 1
stderr:
../tmpoo9iwq6a/testfile.cpp:1:36: error: unknown attribute 'gcc_struct' ignored [-Werror,-Wunknown-attributes]
    1 | struct x { int y; } __attribute__((gcc_struct));
      |                                    ^~~~~~~~~~
1 error generated.
-----------

../qemu-9.1.0-rc3/meson.build:321:4: ERROR: Problem encountered: Your compiler does not support __attribute__((gcc_struct)) - please use GCC instead of Clang
```

**Comment by jeremyd2019** [comment]
That's too bad - my "default" has been using CLANG64 qemu, generally with whpx but sometimes with tcg for arm64 target.  I suppose I'll have to switch to UCRT64 until clang gains support for gcc_struct.

**Comment by heljkon** [comment]
@lazka @jeremyd2019 @Biswa96 
Please review!

As already discussed, QEMU packages for clang weren't build, because upstream has introduced a test which currently results in failing clang builds:

> ERROR: Problem encountered: Your compiler does not support __attribute__((gcc_struct)) - please use GCC instead of Clang

**Comment by heljkon** [comment]
@lazka @jeremyd2019 @Biswa96 @MehdiChinoune 
Just a reminder: still waiting for review.

**Comment by jeremyd2019** [comment]
I miss having qemu-img on arm64 ☹️

**Comment by pbo-linaro** [comment]
I tried recently to push a series fixing clang build on windows. However, maintainers prefer to wait for official clang support for gcc_struct attribute. That said, you can enable it on msys2 side with those two patches: [1](https://patchew.org/QEMU/20241031040426.772604-1-pierrick.bouvier@linaro.org/20241031040426.772604-8-pierrick.bouvier@linaro.org/) [2](https://patchew.org/QEMU/20241031040426.772604-1-pierrick.bouvier@linaro.org/20241031040426.772604-9-pierrick.bouvier@linaro.org/).

IMHO supporting windows-arm64 and clang on windows is worth the risk to introduce any problem with the packing stuff.

**Comment by pbo-linaro** [comment]
@jeremyd2019 You can use mingw64 or ucrt64 msys2 env for that. It will work thanks to x64 emulation (if you're on win11). The overhead should not be a problem for running a simple tool like qemu-img.

**Comment by pbo-linaro** [comment]
I think too it's more a FUD argument than a real problem, QEMU is one of the only big open source projects to use gcc_struct attribute.
That said, MSYS2 is free to apply patches and enable clang for upcoming 9.2 release.

**Comment by bonzini** [comment]
> I think too it's more a FUD argument than a real problem, QEMU is one of the only big open source project to use gcc_struct attribute.

One solution is to add `QEMU_BUILD_BUG_ON(sizeof(...) == ...)` to all structs in QEMU that use bitfields. That will prove very quickly if there are issues or not.

**Comment by jeremyd2019** [comment]
In addition to testing if any struct changes size, each such struct would need to be evaluated to see if it actually matters if it is a different size - not every struct would be exposed to a guest, which is pretty much the only thing I can think of where the layout would matter that much (since this is a Windows host, any struct exposed to the host system would be expected to be laid out with ms bitfields).

**Comment by pbo-linaro** [comment]
Thinking about it today, how about we simply dump dwarf info from qemu-binaries (using llvm-dwarfdump) and simply compare information with following builds configs on windows:
- gcc: using gcc_struct
- gcc: not using gcc_struct
- gcc: using globally option -mno-ms-bitfields
- clang: using globally option -mno-ms-bitfields

It will only cover the types we used, but if we don't, I don't think we should be worried about those.

**Comment by pbo-linaro** [comment]
After a deep investigation, I will propose once again to switch to using `-mno-ms-bitfields` instead of `gcc_struct` attribute. It is, I think, a saner and better default on Windows.
As a consequence, it will allow us to enable clang builds, which supports this option.
 
Details of the investigation are on the [QEMU mailing list](https://lore.kernel.org/qemu-devel/66c346de-7e20-4831-b3eb-1cda83240af9@linaro.org/T/#u).

**Comment by jeremyd2019** [comment]
I would still be concerned about it changing layouts for structs passed to external APIs.  If you can prove that isn't happening, great.

Potential badness: `name:_GIOChannel size:0x70 DW_AT_decl_file:C:/msys64/mingw64/include/glib-2.0/glib/giochannel.h DW_AT_decl_line:100 DW_AT_decl_column:8  ` this would have been built with the default layout in the glib binaries in msys2.

**Comment by pbo-linaro** [comment]
All struct used through QEMU source code are present in debug info, so the listing should be exhaustive. Is there any other potential case that could have been missed?

For `_GIOChannel`, we don't manipulate directly, nor allocate this structure, only glib does. So the size difference has no impact.

Yes, I did this investigation with gcc only for now. There is no point to push further if other devs don't agree in this direction. If we switch to using this option, any difference with clang would be a compiler bug.

**Comment by mstorsjo** [comment]
FWIW, I don't remember if this had been discussed, but I think it probably could be safe to grab the Clang patch for `gcc_struct` support and apply it to the msys2 Clang. The patch iirc requires a little bit more work for upstream (at least adding some tests, maybe something more), but if you'd give it a quick practical test to see that it seems to do what is expected (give structs the same layout as with `-mno-ms-bitfields`) for some cases, I think it's probably quite safe to apply and use.

**Comment by bonzini** [comment]
The conclusion of the discussion is that it *is* safe to drop the usage of `gcc_struct` (and we now have the data to prove it).

**Comment by pbo-linaro** [comment]
Thanks for your help on this Paolo!

**Comment by pbo-linaro** [comment]
Note: This change will not be included officially in 9.2 release, but MSYS2 is free to apply the needed patches (I'll post them here) to enable clang builds.

**Pull request merged**
