### PR TITLE
mesa: Update to 22.2.2

### PR DESCRIPTION
**Pull request by pal1000**

### CODE REVIEW

**Comment by pal1000** [comment]
I don't know what to do for clang32 prefix.

**Comment by ImperatorS79** [comment]
Could you enable `microsoft-experimental` as vulkan driver ? It corresponds to `dozen`, microsoft's Vulkan-to-Direct3D12.

**Comment by pal1000** [comment]
Call @lazka @MehdiChinoune for feedback and assistance.

**Comment by pal1000** [comment]
This discussion from #12306 needs addressing
> Feel free to discuss it in the discussion page of this repository or in discord or gitter. I have been compiling mesa to replace the creepy directx-headers with mingw-w64 headers.

**Comment by lygstate** [comment]
what kind of clang32 failure it is?
Maybe this is related?
https://github.com/llvm/llvm-project/issues/55023

I can building it locally

**Comment by pal1000** [comment]
@lygstate I re-enabled clang32 build in #13961 so you can take a look if it fails.

**Pull request merged**
