### PR TITLE
Add libbacktrace

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by orgads** [comment]
Thank you!

**Comment by mati865** [comment]
FYI libbacktrace is not usable with GCC because of the bug that has been just recent fixed in GCC trunk. More details: https://github.com/ianlancetaylor/libbacktrace/issues/43 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96948

**Comment by lazka** [comment]
Isn't this https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0160-libbacktrace-seh.patch ?

**Comment by mati865** [comment]
Right, I had missed that patch.

**Pull request merged**
