### PR TITLE
update some gnome packages

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
@hmartinez82 Would you like to check if these can be compiled in clangarm64?

**Comment by hmartinez82** [comment]
tepl, gnome-latex, gedit, gedit-plugins? Did I miss anything?

**Comment by Biswa96** [comment]
> tepl, gnome-latex, gedit, gedit-plugins? Did I miss anything?

Nope, but their dependencies may not present in clangarm64 also.

**Comment by hmartinez82** [comment]
Tepl ✅

**Comment by hmartinez82** [comment]
gnome-latex ✅

**Comment by Biswa96** [comment]
Providing the patch which enabled clangarm64 for all these would be sufficient.

**Comment by hmartinez82** [comment]
gedit: ✅ (but requires https://github.com/msys2/MINGW-packages/pull/16690)

**Comment by hmartinez82** [comment]
gedit-plugins: ✅ (but requires https://github.com/msys2/MINGW-packages/pull/16691)

**Comment by hmartinez82** [comment]
Wow, gedit with GTK4 was totally broken before, it's super stable now
image

**Pull request merged**
