### PR TITLE
lcms2: Update to 2.15; port to meson

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by kmilos** [comment]
The psicc man page disappeared in the meson build?

**Comment by Biswa96** [comment]
This diff may help.

```diff
--- a/utils/psicc/meson.build
+++ b/utils/psicc/meson.build
@@ -12,3 +12,5 @@ psicc_exe = executable(
 psicc_man = files(
   'psicc.1',
 )
+
+install_man(psicc_man)
```

I can try to upstream it.

**Comment by Biswa96** [comment]
Patch sent in https://github.com/mm2/Little-CMS/pull/361

**Comment by lazka** [comment]
thanks!

**Comment by Biswa96** [comment]
The patch was accepted in upstream https://github.com/mm2/Little-CMS/commit/ef21b76c33aadfe67f61e378627cd63f21aab4c1 commit.

**Pull request merged**
