### PR TITLE
[new package] zoxide 0.9.4

### LINKED ISSUE #20497: Add [zoxide]
### Package name

zoxide

### Brief description of package

A smarter cd command. Supports all major shells

### URL for package's homepage

https://github.com/ajeetdsouza/zoxide

### Provide a basic test case to validate the package's functionality.

_No response_

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

maybe. if i know how to make a package for msys2 :)

### PR DESCRIPTION
**Pull request by ognevny**
fixes #20497

### CODE REVIEW

**Comment by Biswa96** [comment]
mingw64 can be removed for new packages. Older Windows versions is being dropped.

**Comment by ognevny** [comment]
> mingw64 can be removed for new packages. Older Windows versions is being dropped.

ok, maybe also drop `procs`, which I added yesterday? :) also it's better to update the template

**Comment by mmuetzel** [comment]
> mingw64 can be removed for new packages. Older Windows versions is being dropped.

Where was it decided that contributors should be pushed towards no longer packaging for mingw64?
I'm aware of dropping MINGW32 and clang32. But it is news to me that the same was decided for mingw64.

**Comment by Biswa96** [comment]
> Where was it decided that contributors should be pushed towards no longer packaging for mingw64?

https://www.msys2.org/news/#2024-02-21-note-to-the-remaining-windows-7-80-users

**Comment by mmuetzel** [comment]
> > Where was it decided that contributors should be pushed towards no longer packaging for mingw64?
> 
> https://www.msys2.org/news/#2024-02-21-note-to-the-remaining-windows-7-80-users

I don't see mingw64 mentioned in that note.
Am I missing something?

**Comment by MehdiChinoune** [comment]
There is no decision made about it, just some maintainers decided to not supporting mingw64 in new packages that they review or package themselves.

**Pull request merged**
