### PR TITLE
perl: update to 5.32.1 

### PR DESCRIPTION
**Pull request by naveen521kk**

### CODE REVIEW

**Comment by naveen521kk** [comment]
I am also going to make all the modules here to lowercase.

**Comment by Biswa96** [comment]
> I am also going to make all the modules here to lowercase.

Is there any issue with current naming scheme? I agree it's different. Doesn't that create package conflict? And to mitigate that there'll be more conflicts...replaces...provides... array.

**Comment by naveen521kk** [comment]
> Is there any issue with current naming scheme? I agree it's different. Doesn't that create package conflict? And to mitigate that there'll be more conflicts...replaces...provides... array.

Hmm, either we should make this lower case or revert https://github.com/msys2/MINGW-packages/pull/8430

**Comment by Biswa96** [comment]
OK, seems reasonable. The `provides` list is created by `updpkgprovs` script. It has to be re-run after perl version change. It may need some change also for lowercase.

**Comment by Biswa96** [comment]
Is it possible not to rename patch files? Just to make the diff cleaner and less.

**Comment by naveen521kk** [comment]
Ok https://www.cpan.org/src/5.0/perl-5.32.1.tar.xz is down

**Comment by naveen521kk** [comment]
@Biswa96 does this look good to you?

**Pull request merged**
