### PR TITLE
gnutls: update to 3.7.1

### PR DESCRIPTION
**Pull request by neheb**
Add two patches fixing compilation with clang.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Are you sure this is still needed?  The latest version 12.0.0-3 of clang should have fixed the export issues.

**Comment by neheb** [comment]
I don't see clang 12 in pacman.

**Comment by jeremyd2019** [comment]
It finished building about 1.5 hours ago, it's made it to staging but not to official repos yet

**Comment by jeremyd2019** [comment]
try just bumping to 3.7.1 and not messing with the patches.  CI uses staging packages, it should work now (at least 3.7.0 does)

**Comment by jeremyd2019** [comment]
(this was msys2/CLANG-packages#39)

**Comment by neheb** [comment]
nah.

**Pull request closed without merging**
