### PR TITLE
ccache: update to 4.6

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by lazka** [comment]
For some reason clang32 is failing:

```
   FAILED: doc/ccache.1.tmp C:/_/mingw-w64-ccache/src/build-i686-w64-mingw32/doc/ccache.1.tmp 
  cmd.exe /C "cd /D C:\_\mingw-w64-ccache\src\build-i686-w64-mingw32\doc && D:\M\msys64\clang32\bin\asciidoctor -o ccache.1.tmp -a revnumber="4.6" -a icons=font -a toc=left -a sectanchors -a stylesheet="C:/_/mingw-w64-ccache/src/ccache-4.6/doc/ccache-doc.css" -b manpage C:/_/mingw-w64-ccache/src/ccache-4.6/doc/MANUAL.adoc"
  unexpected ucrtbase.dll
  [88/119] Linking C static library src\third_party\blake3\libblake3.a
  [89/119] Building CXX object unittest/CMakeFiles/unittest.dir/test_Config.cpp.obj
  ninja: build stopped: subcommand failed.
  ==> ERROR: A failure occurred in build().
      Aborting...
  ==> Removing installed dependencies...
  checking dependencies...
```

**Comment by orgads** [comment]
Thanks for spotting this.

Looks like `asciidoctor` package is broken?

Why isn't it reported as failure anyway?

**Comment by lazka** [comment]
We disabled errors for clang when nearly all packages failed one way or another. Maybe it's time we remove that.

**Comment by neheb** [comment]
> We disabled errors for clang when nearly all packages failed one way or another. Maybe it's time we remove that.

Definitely

**Comment by lazka** [comment]
> Looks like `asciidoctor` package is broken?

yes, it fails to build itself: #10893

**Comment by jeremyd2019** [comment]
Looks like a problem with ruby

**Comment by lazka** [comment]
yeah, ruby is broken there, just running ti gives the same error. Downgrading it doesn't help.

**Comment by jeremyd2019** [comment]
clang32 ruby works on my 32-bit Win10 21H1.  I am guessing ucrtbase.dll changed in some newer version that the instruction patterns they are looking for no longer match.

**Pull request merged**
