### PR TITLE
inkscape: update to 1.2.1

### PR DESCRIPTION
**Pull request by Biswa96**
* Remove some upstream patches.
* Add build dependencies for bundled cairo project.
* Extract source tarball manually due to presence of symlinks.

### CODE REVIEW

**Comment by lazka** [comment]
Does it run for you? It doesn't here, without any errors.

**Comment by lazka** [comment]
It's missing symbols in cairo.

**Comment by Biswa96** [comment]
I have used the artifacts from this CI and Inkscape is working without any issue. Do I have to test some specific options?

**Comment by lazka** [comment]
No, just `inkscape.exe`.

**Comment by Biswa96** [comment]
Yup, it's working. I have tested ucrt64, btw.

**Comment by lazka** [comment]
hm, but how I wonder. CI also shows it's linking against system cairo

**Comment by Biswa96** [comment]
The bundled cairo was added in this commit https://gitlab.com/inkscape/inkscape/-/commit/2e3e3d6ab1e0ea7417dced92c0b377a5c76bb19a. It is disabled for unix systems and can be disabled using `WITH_INTERNAL_CAIRO` option explicitly. Should it be disabled to be safe?

**Comment by lazka** [comment]
yes please!

**Pull request merged**
