### PR TITLE
ffmpeg: Enable vf_libplacebo

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by lazka** [comment]
I guess we could build with `-Wno-error=int-conversion`

**Comment by kasper93** [comment]
I've sent the patch upstream, will backport here after it is merged.

**Comment by Biswa96** [comment]
Would you like to share the link please?

**Comment by kasper93** [comment]
> Would you like to share the link please?

https://ffmpeg.org/pipermail/ffmpeg-devel/2023-March/307142.html

**Comment by kasper93** [comment]
I included the patch and removed gcc12 from v4.4. Lynne rewrote a lot of vulkan code in ffmpeg and it will be soon merged (https://github.com/cyanreg/FFmpeg/tree/vulkan), so current code is kinda frozen.

**Comment by lazka** [comment]
I've added the links in ebd8b7fa15272b13a90a1

**Pull request merged**
