### PR TITLE
binutils: Update to 2.37

### PR DESCRIPTION
**Pull request by lazka**
rebased patches; removed the ones in the release; backported one build fix from upstream

### CODE REVIEW

**Comment by Astrum-polaris** [comment]
`0410-windres-handle-spaces.patch` got reverted (partially) again in 2.37, do we still need it?

https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=749c700282097cf679ff019a9674d7c762f48619

https://sourceware.org/bugzilla/show_bug.cgi?id=27594#c7

In msys2 binutils we have another commit reverted to fix mintty build, do mingw binutils need that?

**Comment by lazka** [comment]
From what I remember we needed 0410-windres-handle-spaces.patch for building ffmpeg, but that is inlcluded in the release now (or reverted again, I don't know). I tested building ffmpeg with this and everything seemed to work.

For the msys one, I suspect we can drop the revert then (we will get a conflict anyway)

**Comment by Astrum-polaris** [comment]
> And in case you missed it, this removes 0410-windres-handle-spaces.patch

Yeah. I am talking about the `if defined (_WIN32) && !defined (__CYGWIN__)` part we patched in 2.36.1 got reverted again in 2.37
So I am wondering if we still need it.
If the original problem solved without patching that's fine too.

**Comment by lazka** [comment]
Ah, that got reverted too.. ok, let me check.

**Comment by lazka** [comment]
Now I'm confused why ffmpeg still built fine here with the fix removed.

**Comment by lazka** [comment]
Ah, it was fixed here: https://github.com/FFmpeg/FFmpeg/commit/f9626d1065c43f1d51afe66bdf988b9f33729440 (thanks @mstorsjo !)

I'm wondering if we should just use upstream binutils now or revert like in the msys binutils: https://github.com/msys2/MSYS2-packages/blob/master/binutils/2002-Allow-spaces-in-the-name-of-the-external-preprocesso.patch

**Comment by lazka** [comment]
I think I'll go for the revert for now, and maybe drop it next version.

**Comment by mstorsjo** [comment]
FYI, this is my take of the situation:

https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=21c33bcbe36377abf01614fb1b9be439a3b6de20 - (1) Changed the `--preprocessor` option to treat it as one single path with potential spaces, instead of a string of multiple command line options (as it was documented before). This broke a couple projects that used the `--preprocessor` option as it was documented. In practice, this didn't seem to break things when running on native windows though (due to other details in how shells interpret some quoted paths), only when run in msys/cygwin mode or on actual unix. This issue is what my ffmpeg patch avoids, by just not using this option.

https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=cc3edc52747fd8b184ee48f1b0cc1ac0aca7832e - (2) Fixed handling of options like `-I` that are given paths with spaces and such. This commit is all good afaik, and this one corresponds to something that was patched manually in msys2 before, if I remember correctly.

In response to reports about problems caused by (1), but due to other confusion, (2) was in practice reverted, in https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=749c700282097cf679ff019a9674d7c762f48619.

And the discussion in https://sourceware.org/bugzilla/show_bug.cgi?id=27594 hasn't gotten any consensus regarding what to do, so 2.37 was released in this state, with the seemingly wrong commit reverted and a deadlock in the discussion.

So if you want the quoting fix that you used to have, you should keep patching it in, either in the form of (2) or in the form of what you had before.

**Comment by lazka** [comment]
Thanks for the summary, that helps a lot.

**Pull request merged**
