### PR TITLE
s2geometry: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by Biswa96** [comment]
Patches name should not contain version name. Other than that the package looks good to me 👌

**Comment by podsvirov** [comment]
Please see Patch files section in https://www.msys2.org/wiki/Creating-Packages/

**Comment by Biswa96** [comment]
I mean the version number (here 0.10.0), not the leading patch numbers.

**Comment by podsvirov** [comment]
> Please see Patch files section in https://www.msys2.org/wiki/Creating-Packages/

Please see target description

**Pull request merged**
