### PR TITLE
Add package: ffmpeg-git

### PR DESCRIPTION
**Pull request by lmorand**

### CODE REVIEW

**Comment by Biswa96** [comment]
`-git` packages generally went into [MINGW-packages-dev][1] repository.

[1]: https://github.com/msys2/MINGW-packages-dev.git

**Comment by lmorand** [comment]
Sorry, I didn't know about it. I'll close this one and open another one there.

**Comment by Biswa96** [comment]
I would suggest to wait for maintainer's reply.

**Comment by lazka** [comment]
I've created #7013 to figure out what to do in such cases.

@lmorand just wondering, why do you want such a package in the repo?

**Comment by lmorand** [comment]
I just thought, since building from git is explicitly encoureged in ffmpeg's site, that it would be nice to have that option. Initially, I made this as an alternative to zeranoe's builds which were getting taken down; now I see there are other options, but I still prefer pacman.

**Comment by lazka** [comment]
I'm going to merge this for now, but we might end up moving those -git packages to MINGW-packages-dev in the future.

Thanks!

**Pull request merged**
