### PR TITLE
Remove libcroco, no longer used

### PR DESCRIPTION
**Pull request by lazka**
librsvg no longer uses libcroco since 2.48. Since librsvg was the last user
of libcroco we can remove it.

### CODE REVIEW

**Comment by Biswa96** [comment]
In ArchLinux, gettext uses it.

**Comment by lazka** [comment]
I think gettext includes a copy of libcroco it can use

**Comment by lazka** [comment]
And in Arch it's not actaally used it seems: https://bugs.archlinux.org/task/64416?project=1&string=gettext

**Comment by Ede123** [comment]
FWIW there are some ideas being thrown around in the Inkscape project to take over maintenance of libcroco (we historically include a patched version of it within the source tree), however nothing actionable yet (and I guess we can always bring libcroco back, should Inkscape actually switch to an external dependency).

**Comment by lazka** [comment]
> (and I guess we can always bring libcroco back, should Inkscape actually switch to an external dependency).

Sounds good to me

**Pull request merged**
