### PR TITLE
openvdb: update to 9.0.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
Do we need to rebuild openimageio?

**Comment by MehdiChinoune** [comment]
> Do we need to rebuild openimageio? Does it even link to it... hmm.

Why rebuilding?

**Comment by lazka** [comment]
openimageio depends on openvdb and this is a major version update

**Comment by lazka** [comment]
But it looks like it doesn't actually link against it, so something is wrong in openimageio maybe.

lgtm then

**Comment by MehdiChinoune** [comment]
openimageio will be rebuilt with OpenCV.

**Pull request merged**
