### PR TITLE
qt6: update to 6.5.2 (2/3)

### PR DESCRIPTION
**Pull request by olafmandel**
Part two of three, split out from #17913. Depends on #17916

### CODE REVIEW

**Comment by Biswa96** [comment]
Previous commit was added in this PR.

**Comment by olafmandel** [comment]
I know, but they depend on each other, so once the first one is merged, this one needs to be rebased to master.

**Comment by Biswa96** [comment]
> I know, but they depend on each other, so once the first one is merged, this one needs to be rebased to master.

Hence, I suggested to add the pull request one by one. After one is merged and completed in [queue](https://packages.msys2.org/queue) then the second one and so on. CI would also fail here.

**Comment by lazka** [comment]
To speed things up, and because I can't force push to a organization forked PR I created new PRs with these commits. I hope you don't mind.

**Comment by olafmandel** [comment]
> To speed things up, and because I can't force push to a organization forked PR I created new PRs with these commits. I hope you don't mind.

For reference, this was copied to #17926. And as of now the two changesets are identical.

**Pull request closed without merging**
