### PR TITLE
boost: Replace name-preserving patch with a proper flag

### PR DESCRIPTION
**Pull request by orgads**
This is an upstream convention for quite long.

Reverts fff2fc0d53aa95b85cee0c785e56159b0565ea72.

### CODE REVIEW

**Comment by orgads** [comment]
@Alexpux @lazka

**Comment by orgads** [comment]
I upgraded boost on mxe (with the new names) [3 months ago](https://github.com/mxe/mxe/pull/2698), and nobody complained so far :)

**Comment by orgads** [comment]
hmmm... Now I see that the linked `a` files have the suffix, but the actual dll doesn't. Please wait before approving...

**Comment by lazka** [comment]
How will things find those libraries at build time if their name changes?

**Comment by orgads** [comment]
I'd expect applications that build for Windows to have a proper lookup. How do they work with default upstream boost build?

Anyway, I removed the patch, but found a better way to preserve the old names, by passing the layout version to b2.

**Comment by orgads** [comment]
Actually I think we can consider using `--layout=system`, which is the default on linux. The Windows default (versioned/tagged) seems to target MSVC, when all the DLLs are installed in a single directory. This is not the case for MSYS2/MinGW.

What do you say?

**Comment by lazka** [comment]
Given issues like #4773 and boost not advertising the naming I'd be cautious at least. I'm afraid I don't know enough about this to give any input.

Your current change, replacing the patch with the layout flag, looks good to me.

**Comment by orgads** [comment]
Rebased

**Comment by lazka** [comment]
> Actually I think we can consider using `--layout=system`, which is the default on linux. The Windows default (versioned/tagged) seems to target MSVC, when all the DLLs are installed in a single directory. This is not the case for MSYS2/MinGW.

(In theory this sounds good to me)

**Comment by orgads** [comment]
> > Actually I think we can consider using `--layout=system`, which is the default on linux. The Windows default (versioned/tagged) seems to target MSVC, when all the DLLs are installed in a single directory. This is not the case for MSYS2/MinGW.
> 
> (In theory this sounds good to me)

But then again, we will probably face build issues with dependent applications.

Notice that most applications that use boost, use it as header-only. The runtime libraries are only needed for a small subset of boost modules.

**Pull request merged**
