### PR TITLE
python-findpython: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Seems to fail to build if git is installed (git is installed on the arm64 runner).

**Comment by lazka** [comment]
uh, also the version for other envs is broken. I guess pdm needs patching or some way to override the version

**Comment by lazka** [comment]
see 1ecd1ceb0ec8657280477ea606ab2bdaa103a4ec

**Comment by podsvirov** [comment]
What mean `version for other envs is broken`?. For example, the command `findpython --all` work for me with `MINGW` subsystem.

**Comment by lazka** [comment]
I meant `pip show findpython  | grep Version`

**Comment by podsvirov** [comment]
> I meant `pip show findpython | grep Version`

Ok. Thanks for fix.

My ultimate goal is to port the [python-pdm](https://archlinux.org/packages/extra/any/python-pdm/) package.

**Pull request merged**
