### PR TITLE
jasper: update to 3.0.4

### PR DESCRIPTION
**Pull request by mmuetzel**
This is an update to a new major version. Some dependent package will likely need to be rebuilt. Let's wait for the results of the grokker.

### CODE REVIEW

**Comment by mmuetzel** [comment]
GEGL didn't compile in the CI (at least) for clang. E.g., for CLANG64:
```
  [210/1268] Generating gegl/Gegl-0.4.gir with a custom command (wrapped by meson to set PATH)
  FAILED: gegl/Gegl-0.4.gir 
  "D:/M/msys64/clang64/bin/meson" "--internal" "exe" "--unpickle" "C:/_/mingw-w64-gegl/src/build-CLANG64/meson-private/meson_exe_g-ir-scanner.exe_761709274fd11f03f96ba8cad386805939d38054.dat"
  while executing ['D:/M/msys64/clang64/bin/g-ir-scanner.exe', '--no-libtool', '--namespace=Gegl', '--nsversion=0.4', '--warn-all', '--output', 'gegl/Gegl-0.4.gir', '--c-include=gegl.h', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/.', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/.', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/.', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/.', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/buffer', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/buffer', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/graph', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/graph', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/module', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/module', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/opencl', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/opencl', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/operation', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/operation', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/process', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/process', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/property-types', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/property-types', '--filelist=C:/_/mingw-w64-gegl/src/build-CLANG64/gegl/libgegl-0.4-0.dll.p/Gegl_0.4_gir_filelist', '--include=GLib-2.0', '--include=GObject-2.0', '--include=Babl-0.1', '--symbol-prefix=gegl', '--identifier-prefix=Gegl', '--pkg-export=gegl-0.4', '--cflags-begin', '-DHAVE_CONFIG_H', '-D_FILE_OFFSET_BITS=64', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/.', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/.', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/.', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/.', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/buffer', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/buffer', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/graph', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/graph', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/module', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/module', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/opencl', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/opencl', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/operation', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/operation', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/process', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/process', '-IC:/_/mingw-w64-gegl/src/gegl-0.4.36/gegl/property-types', '-IC:/_/mingw-w64-gegl/src/build-CLANG64/gegl/property-types', '-ID:/M/msys64/clang64/include/babl-0.1', '-ID:/M/msys64/clang64/include', '-ID:/M/msys64/clang64/include/glib-2.0', '-ID:/M/msys64/clang64/lib/glib-2.0/include', '-ID:/M/msys64/clang64/include/gio-win32-2.0', '-ID:/M/msys64/clang64/include/gobject-introspection-1.0', '-D__USE_MINGW_ANSI_STDIO=1', '--cflags-end', '--add-include-path=D:/M/msys64/clang64/share/gir-1.0', '-LC:/_/mingw-w64-gegl/src/build-CLANG64/gegl', '--library', 'gegl-0.4', '-LD:/M/msys64/clang64/lib', '-lbabl-0.1', '-lglib-2.0', '-lintl', '-lgio-2.0', '-lgobject-2.0', '-lgmodule-2.0', '-lm', '-lgirepository-1.0']
  --- stdout ---
  
  --- stderr ---
  Traceback (most recent call last):
  
    File "D:\M\msys64\clang64\bin\g-ir-scanner-script.py", line 99, in <module>
  
      from giscanner.scannermain import scanner_main
  
    File "D:/M/msys64/clang64/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
  
      from giscanner.ast import Include, Namespace
  
  
    File "D:/M/msys64/clang64/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
  
  
      from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  
  
    File "D:/M/msys64/clang64/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
  
  
      from giscanner._giscanner import SourceScanner as CSourceScanner
  
  
  ModuleNotFoundError: No module named 'giscanner._giscanner'
```

It compiles correctly for me locally.
Maybe something broke with Python 3.10? Or something is currently inconsistent in staging?
I'll probably just wait until the Python transition has settled down and attempt again later...

**Comment by mmuetzel** [comment]
The UCRT64 runner has timed out.
Could someone who has the permissions to do it please restart that part of the CI? It might finish in time if it was picked up by a faster runner (at least 2.6 GHz clock).

**Comment by mmuetzel** [comment]
GDAL doesn't seem to pick up Jasper 3.x. And support for it was removed upstream for a newer version (in favor of JPEG-2000 support using OpenJPEG):
https://github.com/OSGeo/gdal/releases/tag/v3.5.0
> * Removed drivers: RDA, JPEG2000 (Jasper-based), [...]

I'll probably try to update GDAL to the newer version first before moving ahead with this PR.

**Comment by mmuetzel** [comment]
Depends on #11855.

**Comment by mmuetzel** [comment]
The "random meson error" #11864 again (for the CLANG64 runner)?
```
2022-06-26T10:25:50.2302960Z [207/1268] Generating symbol file gegl/libgegl-0.4-0.dll.p/libgegl-0.4-0.dll.symbols
2022-06-26T10:25:50.2303627Z FAILED: gegl/libgegl-0.4-0.dll.p/libgegl-0.4-0.dll.symbols 
2022-06-26T10:25:50.2304529Z "D:/M/msys64/clang64/bin/meson" "--internal" "symbolextractor" "C:/_/mingw-w64-gegl/src/build-CLANG64" gegl/libgegl-0.4-0.dll "gegl/libgegl-0.4.dll.a" gegl/libgegl-0.4-0.dll.p/libgegl-0.4-0.dll.symbols 
2022-06-26T10:25:52.1101610Z [208/1268] Compiling C object seamless-clone/libgegl-sc-0.4.dll.p/sc-sample.c.obj
2022-06-26T10:25:52.1102630Z [209/1268] Generating gegl/Gegl-0.4.gir with a custom command (wrapped by meson to set PATH)
2022-06-26T10:25:52.1104354Z ninja: build stopped: subcommand failed.
2022-06-26T10:25:52.2760009Z ==> ERROR: A failure occurred in build().
2022-06-26T10:25:52.4055375Z     Aborting...
```

**Comment by mmuetzel** [comment]
Could someone with the necessary privileges please re-run the CLANG64 job?

**Comment by mmuetzel** [comment]
I think this is ready now.

**Comment by lazka** [comment]
thanks!

**Pull request merged**
