### PR TITLE
Update tepl, gedit and gnome-latex

### PR DESCRIPTION
**Pull request by swilmet**
Another way is to keep tepl4, without touching the gnome-latex package (to apply the patch).

### CODE REVIEW

**Comment by swilmet** [comment]
The error is:
```
Requested 'amtk-5 >= 5.2' but version of Amtk is 5.0.2
```

Amtk was updated recently to version 5.2.0 with commit b4ef17121 , apparently the update is not yet fully propagated.

**Comment by Biswa96** [comment]
As of writing this, Amtk 5.2.0 is in update queue. See https://packages.msys2.org/queue.

**Comment by lazka** [comment]
you can bump the pkgrel of amtk in this PR for now to get it to build first.

**Comment by swilmet** [comment]
Thanks!

**Pull request merged**
