### PR TITLE
enable clangarm64 for more python packages

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
I've not tried others but pywin32 can not be compiled for arm64 as of now. Need some patching. I'm compiling those in RPi.

**Comment by kmilos** [comment]
Ah, thanks, too bad - was going for ipykernel deps... I'll take it out.

**Comment by Biswa96** [comment]
> was going for ipykernel deps... 

Me too, jupyter is my goal 😁

**Comment by Biswa96** [comment]
Just realized pywin32 requires message compiler (mc.exe) from msys2's binutils and Windows 10 does not have the x86_64 emulation and Raspberry Pi 4B can not run Windows 11. @driver1998 may help to port pywin32. So, far, I have done this change

```diff
diff --git a/mingw-w64-python-pywin32/001-compile-and-setup-fixes.patch b/mingw-w64-python-pywin32/001-compile-and-setup-fixes.patch
index 92c8c6295..5849a538a 100644
--- a/mingw-w64-python-pywin32/001-compile-and-setup-fixes.patch
+++ b/mingw-w64-python-pywin32/001-compile-and-setup-fixes.patch
@@ -45,7 +45,7 @@
              if self.pch_header:
                  self.extra_compile_args = self.extra_compile_args or []
  
-@@ -353,6 +364,59 @@
+@@ -353,6 +364,62 @@
                  if found_mfc:
                      break
  
@@ -57,9 +57,12 @@
 +            # MinGW-w64 doesn't define these.
 +            self.extra_compile_args.append("-D__WIN32__")
 +            # Extra compile args
-+            if "64 bit" in sys.version:
++            if "AMD64" in sys.version:
 +                self.extra_compile_args.append("-D_M_X64")  # pythoncom & win32ui
 +                self.extra_compile_args.append("-D_AMD64_")  # mapi
++            elif "ARM64" in sys.version:
++                self.extra_compile_args.append("-D_M_ARM64")  # pythoncom & win32ui
++                self.extra_compile_args.append("-D_ARM64_")  # mapi
 +            else:
 +                self.extra_compile_args.append("-D_M_IX86")  # pythoncom & win32ui
 +                self.extra_compile_args.append("-D_X86_")  # mapi
```

**Comment by Biswa96** [comment]
Thanks. I have the 2GB model and running from microSD card. So, I use a modified WinPE, not a full OS in RPi.

**Pull request merged**
