### PR TITLE
manim: Fix missing package in optdepends

### PR DESCRIPTION
**Pull request by legends2k**
Optional dependency for LaTeX support in manim is provided by `texlive-latex-extra`.  The earlier listed package, `texlive-scheme-medium`, is now absent.  Replace former with latter.

### CODE REVIEW

**Comment by mmuetzel** [comment]
You might need to cherry-pick this upstream commit to avoid the build error:
https://github.com/ManimCommunity/manim/commit/44f78f1dfdd7498542869fc06bb39619f2b2d57b

**Comment by mmuetzel** [comment]
The patch didn't apply on the tarball. Maybe, you just need the following part of it?
``` diff
diff --git a/pyproject.toml b/pyproject.toml
index 8c32dcd03c..4c817cb183 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -27,7 +27,7 @@ packages = [
 
 [tool.poetry.dependencies]
 python = ">=3.7,<3.11"
-click = ">=7.2<=9.0"
+click = ">=7.2,<=9.0"
 click-default-group = "^1.2.2"
 colour = "^0.1.5"
 numpy = "^1.19"
```

**Comment by legends2k** [comment]
@mmuetzel Done!  This can be merged?

**Comment by mmuetzel** [comment]
I'm just a contributor like you that wanted to help getting your PR in shape. You'll have to wait for a maintainer to pick up your PR.

**Pull request merged**
