### PR TITLE
libyuv: update to 1844.r2374.f9fda6e7

### PR DESCRIPTION
**Pull request by kmilos**
In preparation for upcoming libavif 0.11.0

### CODE REVIEW

**Comment by Biswa96** [comment]
Should this be merged now? Or does libavif need to be rebuilt?

**Comment by kmilos** [comment]
Yep, libavif and all of its deps need to be rebuild after libyuv.

**Comment by Biswa96** [comment]
Would you like to rebuild those here or in different PR?

**Comment by kmilos** [comment]
Sure, I can do so here...

**Comment by kmilos** [comment]
Looks like there's a few KDE related components to bump, so I'll probably leave that at 5.98

**Comment by Biswa96** [comment]
Yeah, you can exclude the kimageformats. I shall try to update KDE packages after this PR.

**Comment by novomesk** [comment]
FYI: when you try to upgrade kimageformats to 5.99, it will not build with the new libavif 0.11.0
Patching of kimageformats will be needed.

It is a result of unfortunate situation / timing. I changed to code in kimageformats to reflect changes in libavif git and kimageformats 5.99 was released. Meanwhile libavif reverted the changes and the released kimageformats 5.99 no longer works with that.

It is fixed in kimageformats git but next release will be approximately November 12, 2022.

**Comment by Biswa96** [comment]
> Patching of kimageformats will be needed.

Agree https://github.com/archlinux/svntogit-packages/commit/7b4dbf81760382afaf1b858d6ef568acb1b99f3f

**Comment by kmilos** [comment]
I just bumped kimageformats 5.98 instead so this can be dealt with separately.

**Comment by novomesk** [comment]
> Agree [archlinux/svntogit-packages@7b4dbf8](https://github.com/archlinux/svntogit-packages/commit/7b4dbf81760382afaf1b858d6ef568acb1b99f3f)

Those patches referenced there are focusing on another problem.

**Comment by Biswa96** [comment]
> when you try to upgrade kimageformats to 5.99, it will not build with the new libavif 0.11.0

So, the better choice would be to wait for next KDE updates, right?

**Comment by novomesk** [comment]
For my point of view, it is OK to wait till 5.100

**Comment by kmilos** [comment]
I give up, something weird is up w/  CI now...

**Pull request merged**
