### PR TITLE
qt6: update to 6.2.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
I have seen that ucrt failure occured randomly, There is no way to reproduce it.

**Comment by Biswa96** [comment]
How about merging this then see which one fails in msys2-autobuild?

**Comment by Alexpux** [comment]
@MehdiChinoune qt 6.2.0 have a lot more modules now

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune qt 6.2.0 have a lot more modules now

What do you see missing?

**Comment by Alexpux** [comment]
@MehdiChinoune sorry, seems added modules are included in other modules mostly

**Pull request merged**
