### PR TITLE
flameshot: Replace workaround with proper patches

### PR DESCRIPTION
**Pull request by Biswa96**
* Remove unknown DISABLE_UPDATE_CHECKER cmake option.
* Remove unused check function.
* Install translation with cmake instead of manually doing so.
* Fix translations install directory in executable.
* Remove unused kguiaddons-qt5 dependency which is used in wayland.

### CODE REVIEW

**Comment by Biswa96** [comment]
@ArchGuyWu would you like to review the changes please?

**Comment by ArchGuyWu** [comment]
> @ArchGuyWu would you like to review the changes please?

The win build version of flameshot doesn't have cli, so many of installed file is unused.
  
```
  +/clang64/
  +/clang64/bin/
  +/clang64/bin/flameshot.exe
  +/clang64/share/
  +/clang64/share/applications/
  +/clang64/share/applications/org.flameshot.Flameshot.desktop
  +/clang64/share/bash-completion/
  +/clang64/share/bash-completion/completions/
  +/clang64/share/bash-completion/completions/flameshot
  +/clang64/share/dbus-1/
  +/clang64/share/dbus-1/interfaces/
  +/clang64/share/dbus-1/interfaces/org.flameshot.Flameshot.xml
  +/clang64/share/dbus-1/services/
  +/clang64/share/dbus-1/services/org.flameshot.Flameshot.service
  +/clang64/share/fish/
  +/clang64/share/fish/vendor_completions.d/
  +/clang64/share/fish/vendor_completions.d/flameshot.fish
  +/clang64/share/flameshot/
  +/clang64/share/flameshot/translations/
  +/clang64/share/flameshot/translations/Internationalization_bg.qm
  +/clang64/share/flameshot/translations/Internationalization_ca.qm
  +/clang64/share/flameshot/translations/Internationalization_cs.qm
  +/clang64/share/flameshot/translations/Internationalization_de_DE.qm
  +/clang64/share/flameshot/translations/Internationalization_el.qm
  +/clang64/share/flameshot/translations/Internationalization_es.qm
  +/clang64/share/flameshot/translations/Internationalization_eu.qm
  +/clang64/share/flameshot/translations/Internationalization_fa.qm
  +/clang64/share/flameshot/translations/Internationalization_fi.qm
  +/clang64/share/flameshot/translations/Internationalization_fr.qm
  +/clang64/share/flameshot/translations/Internationalization_gl.qm
  +/clang64/share/flameshot/translations/Internationalization_grc.qm
  +/clang64/share/flameshot/translations/Internationalization_he.qm
  +/clang64/share/flameshot/translations/Internationalization_hu.qm
  +/clang64/share/flameshot/translations/Internationalization_id.qm
  +/clang64/share/flameshot/translations/Internationalization_it_IT.qm
  +/clang64/share/flameshot/translations/Internationalization_ja.qm
  +/clang64/share/flameshot/translations/Internationalization_ka.qm
  +/clang64/share/flameshot/translations/Internationalization_ko.qm
  +/clang64/share/flameshot/translations/Internationalization_nb_NO.qm
  +/clang64/share/flameshot/translations/Internationalization_nl.qm
  +/clang64/share/flameshot/translations/Internationalization_nl_NL.qm
  +/clang64/share/flameshot/translations/Internationalization_pl.qm
  +/clang64/share/flameshot/translations/Internationalization_pt_BR.qm
  +/clang64/share/flameshot/translations/Internationalization_ru.qm
  +/clang64/share/flameshot/translations/Internationalization_sk.qm
  +/clang64/share/flameshot/translations/Internationalization_sr_SP.qm
  +/clang64/share/flameshot/translations/Internationalization_sv_SE.qm
  +/clang64/share/flameshot/translations/Internationalization_tr.qm
  +/clang64/share/flameshot/translations/Internationalization_uk.qm
  +/clang64/share/flameshot/translations/Internationalization_vi.qm
  +/clang64/share/flameshot/translations/Internationalization_zh_CN.qm
  +/clang64/share/flameshot/translations/Internationalization_zh_HK.qm
  +/clang64/share/flameshot/translations/Internationalization_zh_TW.qm
  +/clang64/share/icons/
  +/clang64/share/icons/hicolor/
  +/clang64/share/icons/hicolor/128x128/
  +/clang64/share/icons/hicolor/128x128/apps/
  +/clang64/share/icons/hicolor/128x128/apps/flameshot.png
  +/clang64/share/icons/hicolor/128x128/apps/org.flameshot.Flameshot.png
  +/clang64/share/icons/hicolor/48x48/
  +/clang64/share/icons/hicolor/48x48/apps/
  +/clang64/share/icons/hicolor/48x48/apps/flameshot.png
  +/clang64/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png
  +/clang64/share/icons/hicolor/scalable/
  +/clang64/share/icons/hicolor/scalable/apps/
  +/clang64/share/icons/hicolor/scalable/apps/flameshot.svg
  +/clang64/share/icons/hicolor/scalable/apps/org.flameshot.Flameshot.svg
  +/clang64/share/licenses/
  +/clang64/share/licenses/flameshot/
  +/clang64/share/licenses/flameshot/LICENSE
  +/clang64/share/man/
  +/clang64/share/man/man1/
  +/clang64/share/man/man1/flameshot.1.gz
  +/clang64/share/metainfo/
  +/clang64/share/metainfo/org.flameshot.Flameshot.metainfo.xml
  +/clang64/share/zsh/
  +/clang64/share/zsh/site-functions/
  +/clang64/share/zsh/site-functions/_flameshot
```

```
user@WIN-SERVER CLANG64 ~
$ flameshot --help

user@WIN-SERVER CLANG64 ~
$
```

**Comment by ArchGuyWu** [comment]
You can comment these lines until cli is implement for windows.

**Comment by Biswa96** [comment]
> Nothing happened when using it by cli.

Try it now - something will happen _when using it by cli_ 🙂

**Comment by ognevny** [comment]
> > Nothing happened when using it by cli.
> 
> Try it now - something will happen _when using it by cli_ 🙂 

I guess that the reaction was an approvement

**Pull request merged**
