### PR TITLE
mingw-w64-mesa: Update to 21.1.4

### PR DESCRIPTION
**Pull request by pal1000**

### CODE REVIEW

**Comment by Biswa96** [comment]
If you would like to wait there is something going on with cpuid being redeclared. @1480c1

**Comment by pal1000** [comment]
With 5fc97ca being quickly [reverted](https://github.com/msys2/MINGW-packages/commit/a075432182c5a0a4cde28b7d34b20723e21a4300#diff-d211bc7ba2b51ca6e8996b94c7718d6589a01aefc091330e2e6a9edcfe4b58fb), I think this should be merged as is.

**Comment by pal1000** [comment]
Removed swr disabling commit. Thanks for heads up regarding the cause, @Biswa96.

**Comment by pal1000** [comment]
Superseded by #9155.

**Pull request closed without merging**
