### PR TITLE
firebird-git: update to v5

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
```
  /mingw64/bin/fbclient.dll:
  	libgcc_s_seh-1.dll => D:\M\msys64\mingw64\bin\libgcc_s_seh-1.dll (0x000001d5be7b0000)
  	 libwinpthread-1.dll => D:\M\msys64\mingw64\bin\libwinpthread-1.dll (0x000001d5be7d0000)
  	libstdc++-6.dll => D:\M\msys64\mingw64\bin\libstdc++-6.dll (0x000001d5bf0a0000)
  	msys-tommath-1.dll => not found
```

**Comment by raedrizqie** [comment]
> ```
>   /mingw64/bin/fbclient.dll:
>   	libgcc_s_seh-1.dll => D:\M\msys64\mingw64\bin\libgcc_s_seh-1.dll (0x000001d5be7b0000)
>   	 libwinpthread-1.dll => D:\M\msys64\mingw64\bin\libwinpthread-1.dll (0x000001d5be7d0000)
>   	libstdc++-6.dll => D:\M\msys64\mingw64\bin\libstdc++-6.dll (0x000001d5bf0a0000)
>   	msys-tommath-1.dll => not found
> ```

yeah.. i dont know why it is linked with msys tommath.. maybe @Biswa96  can share some insight..

if it was linked with supplied tommath, this problem doesnt occurs..

**Comment by Biswa96** [comment]
I am not familiar with the project. I think that Mehdi is suggesting to add libtommath in depends instead of makedepends.

**Comment by raedrizqie** [comment]
> I am not familiar with the project. I think that Mehdi is suggesting to add libtommath in depends instead of makedepends.
i see.. but tommath and tomcrypt are static libs.. so i thought it shouldnt be in in depends?

**Comment by MehdiChinoune** [comment]
For some reason MSYS tommath is picked over MINGW one at configuring/building time, and that should be fixed.

**Comment by Biswa96** [comment]
The dll name has `msys` prefix, for example `/mingw64/bin/msys-tommath-1.dll`.

**Comment by MehdiChinoune** [comment]
mingw-w64-libtommath provides import library (`libtommath.dll.a`) but no runtime one!

**Comment by raedrizqie** [comment]
libtommath triplet is 'x86_64-pc-msys' ..no wonder it is messed up

**Comment by lazka** [comment]
Do you know how this fits together with our existing firebird v2 and its reverse dependencies?

**Comment by raedrizqie** [comment]
by 'fits together', do you mean co-exist?

**Comment by lazka** [comment]
Yes, can we remove the former in the future? Will qt5 work with this? Could they coexist somehow?

**Comment by raedrizqie** [comment]
I didnt fully tested these builds though.. binreloc seems to be working fine (loading of firebird.conf & firebird.msg for example)

I was hoping maybe somebody can test these builds somehow..

I dont think v2 and v5 can coexist.. unless maybe if installed in separate dir? but then fbserver between both cant run simultaneously..

**Comment by lazka** [comment]
ok, thanks!

**Comment by raedrizqie** [comment]
tested this with qt5-base and soci.. all built successfully

https://github.com/raedrizqie/MINGW-packages/actions/runs/3380517255

**Comment by raedrizqie** [comment]
firebird now depends on bundled libcds, which uses cmake.. closing this for now

**Pull request closed without merging**
