### PR TITLE
bat: add completions

### LINKED ISSUE #21462: Include [bash-completion] for [bat] packages
### Package name

mingw-w64-x86_64-bat

### New version number

0.24.0

### Other information that may be useful

`bash-completion` is available for `bat` since [0.18.2](https://github.com/sharkdp/bat/releases/tag/v0.18.2) but is not included in `mingw-w64-x86_64-bat`. I'm not sure about other `bat` packages from MSYS2 such as `mingw-w64-ucrt-x86_64-bat` `mingw-w64-clang-x86_64-bat`. Better check it out.
Please include `bash-completion` for `bat` packages

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by ognevny**
and switch to git source while at it

fixes #21462

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Why switching to git source?
It requires more data to download!

**Comment by ognevny** [comment]
> Why switching to git source?
> It requires more data to download!

to remove `GIT_DIR=/dev/null` workaround. for me bigger data to download is not critical

**Comment by MehdiChinoune** [comment]
> to remove `GIT_DIR=/dev/null` workaround. for me bigger data to download is not critical

because you have a fast internet. you know, Not all people in the world has a fast internet.
I live in a region where the internet is at 512 kb/s (64kB).
I have to wake up early to download big files when the internt is fast 8 Mb/s (2MB)

**Comment by ognevny** [comment]
> > to remove `GIT_DIR=/dev/null` workaround. for me bigger data to download is not critical
> 
> because you have a fast internet. you know, Not all people in the world has a fast internet.
> I live in a region where the internet is at 512 kb/s (64kB).
> I have to wake up early to download big files when the internt is fast 8 Mb/s (2MB)

sad to hear. anyway I'll maintain this package, so you don't have to download repo for it

**Pull request merged**
