### PR TITLE
shiboken6/pyside6: Update to 6.3.0

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Shiboken6 and PySide6 should be updated together, otherwise the 'check' job will fail

**Comment by lazka** [comment]
OK. PySide6 fails to build sadly. Maybe it works in CI.

**Comment by lazka** [comment]
feel free to take over, if you want :)

**Comment by lazka** [comment]
```
  FAILED: PySide6/QtCore.cp39-mingw_x86_64.pyd 
  cmd.exe /C "cd . && D:\M\msys64\mingw64\bin\g++.exe -march=x86-64 -mtune=generic -O2 -pipe -DNOMINMAX -Os -DNDEBUG  -pipe   -Wl,--gc-sections -shared -o PySide6\QtCore.cp39-mingw_x86_64.pyd -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\QtCore.rsp  && cd ."
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x45a): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_1809E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x482): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_1903E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x4aa): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_1909E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x4d2): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_2004E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x4fa): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_20H2E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x522): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_21H1E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x54a): undefined reference to `__imp__ZN23QOperatingSystemVersion14Windows10_21H2E'
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: PySide6/QtCore/CMakeFiles/QtCore.dir/PySide6/QtCore/qoperatingsystemversion_wrapper.cpp.obj:qoperatingsystemversion_wrapper.cpp:(.text$_Z40init_QOperatingSystemVersionStaticFieldsv+0x572): undefined reference to `__imp__ZN23QOperatingSystemVersion9Windows11E'
  collect2.exe: error: ld returned 1 exit status
  ```

**Comment by Biswa96** [comment]
The symbols that are defined as `static constexpr` are failing to link but not those are `static const` only. e.g.

```cpp
const QOperatingSystemVersion QOperatingSystemVersion::Windows7 =
    QOperatingSystemVersion(QOperatingSystemVersion::Windows, 6, 1); // works, exported from libqt6core.dll.a
static constexpr QOperatingSystemVersionBase Windows10_1809 { QOperatingSystemVersionBase::Windows, 10, 0, 17763 }; // RS5 // fails, defined in qoperatingsystemversion.h
```

I assume there was a similar issue with constexpr in qt before but can't remember where.

**Comment by lazka** [comment]
thanks, I guess #10358?

**Comment by jeremyd2019** [comment]
Based on comment from #10358 it sounds like they should be static **inline** constexpr?

**Comment by lazka** [comment]
.pyi files are missing. I'll try porting from invoking things via cmake to setup.py, as recommended upstream.

**Pull request merged**
