### PR TITLE
Cairo fix #15316 / 632

### LINKED ISSUE #15316: [GTK3/GTKMM3] libcairo-2.dll call to DWrite.dll causing Segmentation fault
### Description / Steps to reproduce the issue

I have a crash when printing ( https://github.com/giuspen/cherrytree/issues/2066 ) which as the backtrace below shows is pointing the finger to libcairo-2.dll calling DWrite.dll:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffae80b5714 in ?? () from C:\Windows\SYSTEM32\DWrite.dll
(gdb) bt
#0  0x00007ffae80b5714 in ?? () from C:\Windows\SYSTEM32\DWrite.dll
#1  0x00007ffab8371f4c in ?? () from C:\msys64\mingw64\bin\libcairo-2.dll
```

I suspect this was introduced when re-enabling DWite in https://github.com/msys2/MINGW-packages/commit/853c407a0d62503e7db9c9fd1dc5b6e5fb2cfa71#diff-ec73b1797eaafa14b354022f28487d6a4d8f5e84ca776012c1c7fcdf6088b392
I tried to rebuild the package with the patch reverted ( following https://www.msys2.org/wiki/Creating-Packages/ ) but after installing, my app fails to link, I guess I have to rebuild all the libraries that depend on it. I wonder if there is an easy way or I have to rebuild all libraries manually.

Unfortunately for me gtk3-demo doesn't crash.

In case you would be happy to reproduce the crash via my app see https://github.com/giuspen/cherrytree#building-cherrytree-on-windows

```
PenoneG@KUKMW115 MINGW64 ~/git/cherrytree
# gdb ./build/cherrytree.exe
GNU gdb (GDB) 12.1
...
Reading symbols from ./build/cherrytree.exe...
(gdb) r
Starting program: C:\msys64\home\PenoneG\git\cherrytree\build\cherrytree.exe
[New Thread 9180.0x2540]
...
warning: mincore\com\oleaut32\dispatch\ups.cpp(2122)\OLEAUT32.dll!00007FFAFDD39DD6: (caller: 00007FFAFDD391E9) ReturnHr(1) tid
(477c) 8002801D Library not registered.
[New Thread 9180.0x5c30]
[Thread 9180.0x5c30 exited with code 0]
[New Thread 9180.0x5568]
[New Thread 9180.0x5320]
[Thread 9180.0x5568 exited with code 0]
warning: onecore\com\combase\registrationstore\registrationstore.cpp(7759)\combase.dll!00007FFAFD901F64: (caller: 00007FFAFD99
5B43) ReturnHr(1) tid(a88) 80070002 The system cannot find the file specified.
warning: onecore\com\combase\registrationstore\registrationstore.cpp(7759)\combase.dll!00007FFAFD901F64: (caller: 00007FFAFD99
5B43) ReturnHr(2) tid(a88) 80070002 The system cannot find the file specified.
warning: onecore\com\combase\registrationstore\registrationstore.cpp(7759)\combase.dll!00007FFAFD901F64: (caller: 00007FFAFD99
5B43) ReturnHr(3) tid(a88) 80070002 The system cannot find the file specified.
[Thread 9180.0x5320 exited with code 0]
warning: onecore\com\combase\registrationstore\registrationstore.cpp(7759)\combase.dll!00007FFAFD901F64: (caller: 00007FFAFD99
5B43) ReturnHr(4) tid(a88) 80070002 The system cannot find the file specified.
warning: onecore\com\combase\registrationstore\registrationstore.cpp(7759)\combase.dll!00007FFAFD901F64: (caller: 00007FFAFD99
5B43) ReturnHr(5) tid(a88) 80070002 The system cannot find the file specified.
warning: onecore\com\combase\registrationstore\registrationstore.cpp(7759)\combase.dll!00007FFAFD901F64: (caller: 00007FFAFD99
5B43) ReturnHr(6) tid(a88) 80070002 The system cannot find the file specified.
warning: com\ole32\oleregistrationenumeration\oleregistrationenumeration.cpp(150)\ole32.dll!00007FFAFE0387C3: (caller: 00007FF
AFE01B23E) LogHr(1) tid(a88) 80070057 The parameter is incorrect.
warning: com\ole32\oleregistrationenumeration\oleregistrationenumeration.cpp(150)\ole32.dll!00007FFAFE0387C3: (caller: 00007FF
AFE01B23E) LogHr(2) tid(a88) 80070057 The parameter is incorrect.
warning: com\ole32\oleregistrationenumeration\oleregistrationenumeration.cpp(150)\ole32.dll!00007FFAFE0387C3: (caller: 00007FF
AFE01B23E) LogHr(3) tid(a88) 80070057 The parameter is incorrect.
[New Thread 9180.0x601c]
warning: onecore\com\combase\dcomrem\security.cxx(3071)\combase.dll!00007FFAFD86BF3C: (caller: 00007FFAAE29823E) ReturnHr(7) t
id(601c) 80010117 Call context cannot be accessed after call completed.
warning: com\ole32\oleregistrationenumeration\oleregistrationenumeration.cpp(150)\ole32.dll!00007FFAFE0387C3: (caller: 00007FF
AFE01B23E) LogHr(4) tid(a88) 80070057 The parameter is incorrect.
[New Thread 9180.0x3140]

[Thread 9180.0x59c0 exited with code 0]
[New Thread 9180.0x3a40]
warning: Rejecting native image because native image dependency C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expe
cted
warning:
warning: com\ole32\oleregistrationenumeration\oleregistrationenumeration.cpp(150)\ole32.dll!00007FFAFE0387C3: (caller: 00007FFAFE01B23E) LogHr(5) tid(a88) 80070057 The parameter is incorrect.
warning: com\ole32\oleregistrationenumeration\oleregistrationenumeration.cpp(150)\ole32.dll!00007FFAFE0387C3: (caller: 00007FFAFE01B23E) LogHr(6) tid(a88) 80070057 The parameter is incorrect.
[New Thread 9180.0x1fd4]
[Thread 9180.0x1fd4 exited with code 0]
[Thread 9180.0x4d84 exited with code 0]
warning: Invalid parameter passed to C runtime function.

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffae80b5714 in ?? () from C:\Windows\SYSTEM32\DWrite.dll
(gdb) bt
#0  0x00007ffae80b5714 in ?? () from C:\Windows\SYSTEM32\DWrite.dll
#1  0x00007ffab8371f4c in ?? () from C:\msys64\mingw64\bin\libcairo-2.dll
```

### Expected behavior

No crash

### Actual behavior

warning: Invalid parameter passed to C runtime function.

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffae80b5714 in ?? () from C:\Windows\SYSTEM32\DWrite.dll
(gdb) bt
#0  0x00007ffae80b5714 in ?? () from C:\Windows\SYSTEM32\DWrite.dll
#1  0x00007ffab8371f4c in ?? () from C:\msys64\mingw64\bin\libcairo-2.dll

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by giuspen**
Fixes https://github.com/msys2/MINGW-packages/issues/15316
( Workarounbd discussed on https://gitlab.freedesktop.org/cairo/cairo/-/issues/632 )

### CODE REVIEW

**Comment by lazka** [comment]
Thanks for you debugging work with upstream :)

**Comment by giuspen** [comment]
Thanks to you @lazka msys2 is great!

**Comment by Biswa96** [comment]
A proper commit message would be helpful.

**Comment by giuspen** [comment]
Sure @Biswa96 I renamed the patch file and pushed a commit message more meaningful

**Pull request merged**
