### PR TITLE
fmt: Update to 10.1.0

### PR DESCRIPTION
**Pull request by ccyykkcyk**

### CODE REVIEW

**Comment by lazka** [comment]
Requires rebuilds of:

```
mingw-w64-seacas
mingw-w64-spdlog
mingw-w64-tiledb
mingw-w64-vtk
mingw-w64-paraview
```

**Comment by lazka** [comment]
thanks

**Comment by lazka** [comment]
vtk seems to be incompatible:

```
08-05T16:42:14.9183848Z In file included from C:/_/B/src/VTK-9.2.6/ThirdParty/ioss/vtkioss/Ioss_Field.C:14:
2023-08-05T16:42:14.9184215Z In file included from D:/M/msys64/clang32/include/fmt/ostream.h:20:
2023-08-05T16:42:14.9184597Z In file included from D:/M/msys64/clang32/include/fmt/format.h:49:
2023-08-05T16:42:14.9185368Z D:/M/msys64/clang32/include/fmt/core.h:1690:3: error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
2023-08-05T16:42:14.9186027Z   static_assert(
```

**Comment by MehdiChinoune** [comment]
> vtk seems to be incompatible: https://gitlab.kitware.com/vtk/vtk/-/issues/19012
> 
> ```
> 08-05T16:42:14.9183848Z In file included from C:/_/B/src/VTK-9.2.6/ThirdParty/ioss/vtkioss/Ioss_Field.C:14:
> 2023-08-05T16:42:14.9184215Z In file included from D:/M/msys64/clang32/include/fmt/ostream.h:20:
> 2023-08-05T16:42:14.9184597Z In file included from D:/M/msys64/clang32/include/fmt/format.h:49:
> 2023-08-05T16:42:14.9185368Z D:/M/msys64/clang32/include/fmt/core.h:1690:3: error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
> 2023-08-05T16:42:14.9186027Z   static_assert(
> ```

I tried before to update fmt to 10.0.0 but VTK fails to build, I filed an issue https://gitlab.kitware.com/vtk/vtk/-/issues/19012
So waiting for the next release of VTK!

**Pull request merged**
