### PR TITLE
vulkan-loader: update to 1.3.224

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
for some reason this failed in autobuild

**Comment by MehdiChinoune** [comment]
> for some reason this failed in autobuild

Vulkan-loader 1.3.224 is not compatible with Vulkan-headers 1.3.225

**Comment by lazka** [comment]
I've reverted both for now to unblock autobuild. I hope that's ok.

**Comment by MehdiChinoune** [comment]
> I've reverted both for now to unblock autobuild. I hope that's ok.

Please re-revert vulkan-headers, see #12698

**Comment by lazka** [comment]
ok, done

**Pull request merged**
