### PR TITLE
Update arm-none-eabi-newlib to 3.3.0

### PR DESCRIPTION
**Pull request by fauxpark**

### CODE REVIEW

**Comment by fauxpark** [comment]
I don't know why this is segfaulting. It compiled locally before this latest batch of updates :(

**Comment by lazka** [comment]
```
../../../../../../../../newlib/libc/stdlib/__exp10.c: In function '__exp10':
../../../../../../../../newlib/libc/stdlib/__exp10.c:12:3: internal compiler error: Segmentation fault
   {1.0,
   ^
libbacktrace could not find executable to open
```

related to ASLR maybe? @jeremyd2019

**Comment by fauxpark** [comment]
I rebuilt a fresh arm-none-eabi-binutils and tried compiling newlib against that. No more segfault but I get this instead:
```
arm-none-eabi-ar cru lib.a lib_a-chk_fail.o lib_a-stack_protector.o lib_a-memcpy_chk.o lib_a-memmove_chk.o lib_a-mempcpy_chk.o lib_a-memset_chk.o lib_a-stpcpy_chk.o lib_a-stpncpy_chk.o lib_a-strcat_chk.o lib_a-strcpy_chk.o lib_a-strncat_chk.o lib_a-strncpy_chk.o lib_a-gets_chk.o lib_a-snprintf_chk.o lib_a-sprintf_chk.o lib_a-vsnprintf_chk.o lib_a-vsprintf_chk.o
C:\msys64\mingw64\bin\arm-none-eabi-ar.exe: `u' modifier ignored since `D' is the default (see `U')
arm-none-eabi-ranlib lib.a
make[8]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/arm/v5te/softfp/newlib/libc/ssp'
Making all in .
make[8]: Entering directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/arm/v5te/softfp/newlib/libc'
rm -f libc.a
rm -rf tmp
mkdir tmp
cd tmp; \
 for i in argz/lib.a stdlib/lib.a ctype/lib.a search/lib.a stdio/lib.a   string/lib.a signal/lib.a time/lib.a locale/lib.a reent/lib.a  errno/lib.a misc/lib.a ssp/lib.a   syscalls/lib.a  machine/lib.a sys/lib.a; do \
   arm-none-eabi-ar x ../$i; \
 done; \
arm-none-eabi-ar rc ../libc.a *.o
../stdlib/lib.a: No such file or directory
C:\msys64\mingw64\bin\arm-none-eabi-ar.exe: ../stdio/lib.a: No such file or directory
C:\msys64\mingw64\bin\arm-none-eabi-ar.exe: arm-none-eabi-ranlib libc.a
rm -rf tmp
make[8]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/arm/v5te/softfp/newlib/libc'
make[7]: *** [Makefile:683: all-recursive] Error 1
make[7]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/arm/v5te/softfp/newlib/libc'
make[6]: *** [Makefile:641: all-recursive] Error 1
make[6]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/arm/v5te/softfp/newlib'
make[5]: *** [Makefile:452: all] Error 2
make[5]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/arm/v5te/softfp/newlib'
make[4]: *** [Makefile:1260: multi-do] Error 1
make[4]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/newlib'
make[3]: *** [Makefile:1176: all-multi] Error 2
make[3]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/newlib'
make[2]: *** [Makefile:452: all] Error 2
make[2]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build/arm-none-eabi/newlib'
make[1]: *** [Makefile:8500: all-target-newlib] Error 2
make[1]: Leaving directory '/home/fauxpark/git/mingw-packages/mingw-w64-arm-none-eabi-newlib/src/newlib-3.3.0/newlib-build'
make: *** [Makefile:887: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Fabien-Chouteau** [comment]
Maybe it's question of version of GCC.

I have a `PKGBUILD` for a base/bootstrap GCC that can be used to build newlib, and then build the full GCC with this newlib.

**Comment by Fabien-Chouteau** [comment]
Here it is: https://github.com/Fabien-Chouteau/MINGW-packages/blob/arm-none-eabi-toolchain/mingw-w64-arm-none-eabi-gcc-base/PKGBUILD

**Comment by fauxpark** [comment]
Probably not - as I mentioned I was able to compile it before (presumably) the ASLR stuff went in. I think the segfault is because arm-none-eabi-binutils was compiled without ASLR, but newlib is now being compiled *with* ASLR, and that is incompatible in some way.

The "No such file or directory" above I suspect might be due to path length issues. I'm running another build now closer to the drive root (`/e/mingw-w64-arm-none-eabi`), that seemed to help last time, as did lopping off the MINGW_CHOST suffix from the build and install directories.

**Comment by jeremyd2019** [comment]
> ```
> ../../../../../../../../newlib/libc/stdlib/__exp10.c: In function '__exp10':
> ../../../../../../../../newlib/libc/stdlib/__exp10.c:12:3: internal compiler error: Segmentation fault
>    {1.0,
>    ^
> libbacktrace could not find executable to open
> ```
> 
> related to ASLR maybe? @jeremyd2019

Oh dear.  Yeah, probably.  I bet that issue (1c41e8e) applies to any mingw-hosted gcc.  Hopefully easier to deal with on a cross-compiler, as you don't have to deal with multiple stages or LDFLAGS_FOR_TARGET.

**Comment by jeremyd2019** [comment]
I'm trying ce77dbb6 in CI now, see if that's enough.  I expect so, since lto is disabled in this gcc.

**Comment by jeremyd2019** [comment]
That succeeded building on both x86_64 and i686.  I don't know the best way to get it to you.  I created a pull request in your fork to add the commit.  Here's the diff in case that's easier:
```diff
diff --git a/mingw-w64-arm-none-eabi-newlib/PKGBUILD b/mingw-w64-arm-none-eabi-newlib/PKGBUILD
index 185ad24a8..9587c9936 100644
--- a/mingw-w64-arm-none-eabi-newlib/PKGBUILD
+++ b/mingw-w64-arm-none-eabi-newlib/PKGBUILD
@@ -47,6 +47,10 @@ _build_gcc() {

     cp -a ${MINGW_PREFIX}/${_target} ${srcdir}/gcc-${_gccver}/gcc-install-${MINGW_CHOST}

+    local _GCC_LDFLAGS="${LDFLAGS} -Wl,--disable-dynamicbase"
+    if [ "${CARCH}" = 'x86_64' ]; then
+        _GCC_LDFLAGS+=",--image-base=0x400000"
+    fi
     ../configure \
         --build=${MINGW_CHOST} \
         --host=${MINGW_CHOST} \
@@ -76,7 +80,8 @@ _build_gcc() {
         --with-host-libstdcxx="-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm" \
         --with-sysroot=${MINGW_PREFIX} \
         --with-build-sysroot=${srcdir}/gcc-${_gccver}/gcc-install-${MINGW_CHOST} \
-        --with-build-time-tools=${MINGW_PREFIX}/${_target}/bin
+        --with-build-time-tools=${MINGW_PREFIX}/${_target}/bin \
+        LDFLAGS="${_GCC_LDFLAGS}"

     make all-gcc
     make DESTDIR=${srcdir}/gcc-${_gccver}/gcc-install-${MINGW_CHOST} install-gcc
```

**Comment by fauxpark** [comment]
@jeremyd2019 excellent, thanks! Looks like the x64 build encountered a 502 though, any way I can restart it?

**Comment by jeremyd2019** [comment]
The only way I know of as a non-project-member is to push the branch.  I have done git commit --amend --no-edit followed by git push -f, even making no changes but the commit timestamp is enough.

**Pull request merged**
