### PR TITLE
rav1e: enable for clangarm64

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
@jeremyd2019 mentioned something about arm64 & nasm.

**Comment by kmilos** [comment]
Ah yes, will probably need to exclude that one, thanks.

Seems to build for aarch64 on Arch though...

Also @MehdiChinoune any reason `cargo-c` was reverted, any problems?

**Comment by MehdiChinoune** [comment]
See #14077

**Comment by kmilos** [comment]
Thanks, converting to draft until crates are available then. [Though the readme gives the impression it should work w/ Clang and aarch64...](https://github.com/xiph/rav1e#features-1)

**Comment by MehdiChinoune** [comment]
cargo-c is now available for clangarm64.

**Comment by MehdiChinoune** [comment]
cargo-c refuse to build for aarch64 https://github.com/lu-zero/cargo-c/blob/v0.9.15/src/build.rs#L223
Should we patch it?

**Comment by kmilos** [comment]
@MehdiChinoune See https://github.com/lu-zero/cargo-c/issues/245#issuecomment-1366495718 ;)

**Comment by kmilos** [comment]
Just rebased for now, but won't be able to merge until cargo-c is patched obviously.

**Comment by MehdiChinoune** [comment]
done in #14892

**Pull request closed without merging**
