### PR TITLE
starship: update to 1.17.0

### PR DESCRIPTION
**Pull request by ognevnydemon**
patches are not needed now

### CODE REVIEW

**Comment by ognevnydemon** [comment]
clangarm64 fails with
```
C:/Users/Administrator/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-ng-sys-1.1.12/src/zlib-ng/arch/arm/neon_intrins.h:5:12: fatal error: 'arm64_neon.h' file not found
        5 | #  include <arm64_neon.h>
          |            ^~~~~~~~~~~~~~
    1 warning and 1 error generated.
    make[2]: *** [CMakeFiles/zlib.dir/build.make:524: CMakeFiles/zlib.dir/arch/arm/compare256_neon.c.obj] Error 1
    make[2]: *** Waiting for unfinished jobs....
    warning: unknown warning option '-Wno-pedantic-ms-format'; did you mean '-Wno-pedantic-macros'? [-Wunknown-warning-option]
    1 warning generated.
    make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/zlib.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2
    thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:
```

**Comment by Biswa96** [comment]
This condition needs to be modified somehow https://github.com/zlib-ng/zlib-ng/blob/fd5b20f4ce5f0e8d4eafaad190dca5bc74a320fe/arch/arm/neon_intrins.h#L4

**Comment by ognevnydemon** [comment]
> This condition needs to be modified somehow

`#if !defined(__MINGW32__)...`?

**Comment by Biswa96** [comment]
Maybe `|| defined(__aarch64__)`

**Comment by lazka** [comment]
(reverted for now)

**Comment by ognevnydemon** [comment]
> (reverted for now)

oh, maybe it would better to just disable clangarm64... but ok

**Comment by lazka** [comment]
Also fine with me. Let's ask @naveen521kk who added the package in the first place.

**Comment by naveen521kk** [comment]
> Let's ask @naveen521kk who added the package in the first place.

Fine with me :)

**Comment by ognevnydemon** [comment]
in crate's repository I found [this](https://github.com/rust-lang/libz-sys/issues/153) (maybe someone could help with it) and [this](https://github.com/rust-lang/libz-sys/issues/83) (zlib-ng source is always vendored)

**Comment by mati865** [comment]
It should be fixed upstream by https://github.com/zlib-ng/zlib-ng/commit/f9228d8475100d280f416d4ce606d3d56d2a8708
We can wait for a new release with https://github.com/rust-lang/libz-sys/pull/162 or patch the vendored sources.

**Comment by ognevnydemon** [comment]
opened a suggestion to bump crate's version
https://github.com/rust-lang/libz-sys/issues/166

**Pull request merged**
