### PR TITLE
Attempt to plug dependency hole.

### PR DESCRIPTION
**Pull request by JPeterMugaas**
mingw-w64-manim - add mingw-w64-python-isosurfaces as dependency, minor bug fixes.
mingw-w64-python-isosurfaces - new package

### CODE REVIEW

**Comment by lazka** [comment]
thanks.

those upper dependency bounds are starting to get annoying..

**Comment by hartwork** [comment]
@JPeterMugaas sending e-mail to the address you're using in patches bounces back with error…

```
  ......@suddenlink.net
    host mx.suddenlink.net [208.180.40.132]
    SMTP error from remote mail server after initial connection:
    421 Connection limit reached. Please try again later:
    retry timeout exceeded
```

…and profile URL http://www.jpetermugaas.com/ does not resolve to an IP with me. It seems virtually impossible to contact you today other than through this post on GitHub. Are you aware? Sorry for the off-topic post, I didn't see any other option.

**Comment by JPeterMugaas** [comment]
Thanks for making me aware.  I don't know what to do about the SMTP issue at my end because it sounds like server reached copacity.

**Comment by JPeterMugaas** [comment]
I am on facebook ( https://www.facebook.com/profile.php?id=100010213332565 ).

**Comment by hartwork** [comment]
> Thanks for making me aware. I don't know what to do about the SMTP issue at my end because it sounds like server reached copacity.

I just tried again, still unreachable. Either complain to suddenlink.net admins or move to a different mail provider or both.


> I am on facebook ( https://www.facebook.com/profile.php?id=100010213332565 ).

Thanks, but I am not on Facebook.

**Comment by hartwork** [comment]
> or move to a different mail provider

@JPeterMugaas sorry if that was too much, I meant no disrespect.

**Comment by JPeterMugaas** [comment]
May I ask what you wish to contact me about.

**Comment by hartwork** [comment]
> May I ask what you wish to contact me about.

@JPeterMugaas it's about your patch at https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-expat/002-fix-tests.patch . I have CC'ed you on a pull request in libexpat upstream now. Your review/feedback/testing would be greatly appreciated. The goal is to be able to drop the patch from MSYS2 with the next release in a few days.

**Comment by JPeterMugaas** [comment]
My reply is here:  https://github.com/msys2/MINGW-packages/pull/10521

**Pull request merged**
