### PR TITLE
xmake: add new package

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/6169

### CODE REVIEW

**Comment by Biswa96** [comment]
CI output:

> package mingw-w64-i686-xmake-2.3.1-1-i686 does not have a valid architecture

@lazka @Alexpux any hint. I have installed the new package in my system without any issue.

**Comment by Alexpux** [comment]
@Biswa96 for MINGW packages you always must write
````
arch=('any')
````
in PKGBUILD

**Comment by Biswa96** [comment]
Now appveyor failed.

**Comment by waruqi** [comment]
> Now appveyor failed.

please update sha256 to b2e46d9b4dd48fb70d32a314ca4ba12d42b0b294f5e2179c5c09c56f9c52933b

**Comment by Biswa96** [comment]
`updpkgsums` does not show any change.

**Comment by waruqi** [comment]
> `updpkgsums` does not show any change.

You can remove the local cached xmake-2.3.1.tar.gz and run `updpkgsums` again. 

I have checked the remove archive package. It's sha256 is  b2e46d9b4dd48fb70d32a314ca4ba12d42b0b294f5e2179c5c09c56f9c52933b

**Comment by waruqi** [comment]
@Biswa96 

> Also shouldn't the xmake shell script and xmake.exe name be different to remove any confusion while invoking from a shell?

I have renamed them, update shasum (e6e2d3b6679ae6fa2663125d3b0d927ffe811e9d8da88b97209bc508f35df6d7)

**Comment by Biswa96** [comment]
Again Appveyor failed.

**Comment by Biswa96** [comment]
Again Appveyor failed. But I can build it in my system.

**Comment by waruqi** [comment]
> Again Appveyor failed. But I can build it in my system.

That's because it is mingw64 environment on ci, even if mingw-i686-gcc compiler is used. And `make build` script will detect arch as x86_64 using $MSYSTEM_CARCH in makefile.

You can try to modify PKGBUILD and pass the package arch to build it.

```
build() {
    cd "$srcdir"
    make build ARCH=${arch}
}
```

**Comment by waruqi** [comment]
@Biswa96   You can try `make build MSYSTEM_CARCH=${arch}`

**Comment by Biswa96** [comment]
@waruqi Please fix the repository first, I will check this tomorrow.

**Comment by Biswa96** [comment]
@waruqi Please fix the repository first. You may do this PR yourself.

**Comment by waruqi** [comment]
@Biswa96 @Alexpux All checks have passed https://github.com/msys2/MINGW-packages/pull/6224

**Pull request closed without merging**
