### PR TITLE
octave: update to version 7.3.0

### PR DESCRIPTION
**Pull request by mmuetzel**
PCRE isn't actually a new dependency. But it looks like it was pulled in implicitly before. But that no longer seems to be happening.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Is there a way to use pcre2 instead of pcre?

**Comment by mmuetzel** [comment]
> Is there a way to use pcre2 instead of pcre?

There probably is. But it hasn't been implemented yet.
See this upstream bug report:
https://savannah.gnu.org/bugs/index.php?61542

**Comment by MehdiChinoune** [comment]
Fedora is going to drop pcre soon.
https://fedoraproject.org/wiki/PcreDeprecation
https://fedoraproject.org/wiki/PcreRetirement

**Comment by mmuetzel** [comment]
> Fedora is going to drop pcre soon.
> https://fedoraproject.org/wiki/PcreDeprecation
> https://fedoraproject.org/wiki/PcreRetirement

Yeah. I know. 😓
Transitioning would probably not be that hard. We'd just need someone to actually implement it...

**Comment by mmuetzel** [comment]
Fwiw, support for PCRE2 has been added recently in Octave:
https://hg.savannah.gnu.org/hgweb/octave/rev/d1165473e4b0

It will be part of Octave 8 when it will be released probably at some point early next year.

**Comment by MehdiChinoune** [comment]
> Fwiw, support for PCRE2 has been added recently in Octave: https://hg.savannah.gnu.org/hgweb/octave/rev/d1165473e4b0
> 
> It will be part of Octave 8 when it will be released probably at some point early next year.

Could it backported?

**Comment by mmuetzel** [comment]
> Could it backported?

Maybe. I'd rather not without the necessary testing.
Is it important?

**Comment by MehdiChinoune** [comment]
> Is it important?

Just to know if we could drop pcre earlier.

**Pull request merged**
