### PR TITLE
flang: build shared libs and split package

### PR DESCRIPTION
**Pull request by MehdiChinoune**
It segfaults, needs some investigation.

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you provide any backtrace of that segmentation fault, please?

**Comment by MehdiChinoune** [comment]
> Could you provide any backtrace of that segmentation fault, please?

Take any fortran file and try to compile it `flang -c file.f90`
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: D:/Programs/msys64_test/clang64/bin/flang -fc1 -triple x86_64-w64-windows-gnu -emit-obj -fcolor-diagnostics
-mrelocation-model pic -pic-level 2 -target-cpu x86-64 -o constants.o -x f95-cpp-input ../../src/constants.F90
Exception Code: 0xC0000005
 #0 0x00007ffc8f93b1c8 mlir::detail::StorageUniquerImpl::getOrCreate(mlir::TypeID, unsigned int, llvm::function_ref<bool (mlir::Storage
Uniquer::BaseStorage const*)>, llvm::function_ref<mlir::StorageUniquer::BaseStorage* (mlir::StorageUniquer::StorageAllocator&)>) (D:\Pr
ograms\msys64_test\clang64\bin\libFIRDialect.dll+0x13b1c8)
 #1 0x00007ffc8f93b174 mlir::StorageUniquer::getParametricStorageTypeImpl(mlir::TypeID, unsigned int, llvm::function_ref<bool (mlir::St
orageUniquer::BaseStorage const*)>, llvm::function_ref<mlir::StorageUniquer::BaseStorage* (mlir::StorageUniquer::StorageAllocator&)>) (
D:\Programs\msys64_test\clang64\bin\libFIRDialect.dll+0x13b174)
 #2 0x00007ffc8f91c600 mlir::StringAttr::get(mlir::MLIRContext*, llvm::Twine const&) (D:\Programs\msys64_test\clang64\bin\libFIRDialect
.dll+0x11c600)
 #3 0x00007ffc8f92c3ec mlir::OperationName::Impl::Impl(llvm::StringRef, mlir::Dialect*, mlir::TypeID, mlir::detail::InterfaceMap) (D:\P
rograms\msys64_test\clang64\bin\libFIRDialect.dll+0x12c3ec)
 #4 0x00007ffc8f809535 void mlir::RegisteredOperationName::insert<fir::AbsentOp>(mlir::Dialect&) (D:\Programs\msys64_test\clang64\bin\l
ibFIRDialect.dll+0x9535)
 #5 0x00007ffc8f808e43 void mlir::Dialect::addOperations<fir::AbsentOp, fir::AddcOp, fir::AddrOfOp, fir::AllocMemOp, fir::AllocaOp, fir
::ArrayAccessOp, fir::ArrayAmendOp, fir::ArrayCoorOp, fir::ArrayFetchOp, fir::ArrayLoadOp, fir::ArrayMergeStoreOp, fir::ArrayModifyOp,
fir::ArrayUpdateOp, fir::BoxAddrOp, fir::BoxCharLenOp, fir::BoxDimsOp, fir::BoxEleSizeOp, fir::BoxIsAllocOp, fir::BoxIsArrayOp, fir::Bo
xIsPtrOp, fir::BoxProcHostOp, fir::BoxRankOp, fir::BoxTypeCodeOp, fir::BoxTypeDescOp, fir::CallOp, fir::CharConvertOp, fir::CmpcOp, fir
::ConstcOp, fir::ConvertOp, fir::CoordinateOp, fir::DTEntryOp, fir::DeclareOp, fir::DispatchOp, fir::DispatchTableOp, fir::DivcOp, fir:
:DoLoopOp, fir::EmboxCharOp, fir::EmboxOp, fir::EmboxProcOp, fir::ExtractValueOp, fir::FieldIndexOp, fir::FirEndOp, fir::FreeMemOp, fir
::GlobalLenOp, fir::GlobalOp, fir::HasValueOp, fir::IfOp, fir::InsertOnRangeOp, fir::InsertValueOp, fir::IsPresentOp, fir::IterWhileOp,
 fir::LenParamIndexOp, fir::LoadOp, fir::MulcOp, fir::NegcOp, fir::NoReassocOp, fir::ReboxOp, fir::ResultOp, fir::SaveResultOp, fir::Se
lectCaseOp, fir::SelectOp, fir::SelectRankOp, fir::SelectTypeOp, fir::ShapeOp, fir::ShapeShiftOp, fir::ShiftOp, fir::SliceOp, fir::Stor
eOp, fir::StringLitOp, fir::SubcOp, fir::TypeDescOp, fir::UnboxCharOp, fir::UnboxProcOp, fir::UndefOp, fir::UnreachableOp, fir::ZeroOp>
() (D:\Programs\msys64_test\clang64\bin\libFIRDialect.dll+0x8e43)
 #6 0x00007ffc8f808c59 fir::FIROpsDialect::FIROpsDialect(mlir::MLIRContext*) (D:\Programs\msys64_test\clang64\bin\libFIRDialect.dll+0x8
c59)
 #7 0x00007ffc8534b745 std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> llvm::function_ref<std::__1::unique
_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> ()>::callback_fn<fir::FIROpsDialect* mlir::MLIRContext::getOrLoadDialect<f
ir::FIROpsDialect>()::'lambda'()>(long long) (D:\Programs\msys64_test\clang64\bin\libflangFrontend.dll+0x1b745)
 #8 0x00007ffc859b087a mlir::MLIRContext::getOrLoadDialect(llvm::StringRef, mlir::TypeID, llvm::function_ref<std::__1::unique_ptr<mlir:
:Dialect, std::__1::default_delete<mlir::Dialect>> ()>) (D:\Programs\msys64_test\clang64\bin\libflangFrontend.dll+0x68087a)
 #9 0x00007ffc8534b66c fir::FIROpsDialect* mlir::MLIRContext::getOrLoadDialect<fir::FIROpsDialect>() (D:\Programs\msys64_test\clang64\b
in\libflangFrontend.dll+0x1b66c)
#10 0x00007ffc8534ca8c void mlir::MLIRContext::loadDialect<mlir::affine::AffineDialect, fir::FIROpsDialect, hlfir::hlfirDialect, mlir::
acc::OpenACCDialect, mlir::omp::OpenMPDialect, mlir::scf::SCFDialect, mlir::arith::ArithDialect, mlir::cf::ControlFlowDialect, mlir::fu
nc::FuncDialect, mlir::vector::VectorDialect, mlir::math::MathDialect, mlir::complex::ComplexDialect, mlir::DLTIDialect>() (D:\Programs
\msys64_test\clang64\bin\libflangFrontend.dll+0x1ca8c)
#11 0x00007ffc85341f2b fir::support::loadNonCodegenDialects(mlir::MLIRContext&) (D:\Programs\msys64_test\clang64\bin\libflangFrontend.d
ll+0x11f2b)
#12 0x00007ffc85340cbc Fortran::frontend::CodeGenAction::beginSourceFileAction() (D:\Programs\msys64_test\clang64\bin\libflangFrontend.
dll+0x10cbc)
#13 0x00007ffc8533f15c Fortran::frontend::FrontendAction::beginSourceFile(Fortran::frontend::CompilerInstance&, Fortran::frontend::Fron
tendInputFile const&) (D:\Programs\msys64_test\clang64\bin\libflangFrontend.dll+0xf15c)
#14 0x00007ffc8533239f Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (D:\Programs\msys64_test\
clang64\bin\libflangFrontend.dll+0x239f)
#15 0x00007ffcc9f31fc4 Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (D:\Programs\msys64_test\clan
g64\bin\libflangFrontendTool.dll+0x1fc4)
#16 0x00007ff64f8d2d35 fc1_main(llvm::ArrayRef<char const*>, char const*) (D:\Programs\msys64_test\clang64\bin\flang.exe+0x2d35)
#17 0x00007ff64f8d21c7 main (D:\Programs\msys64_test\clang64\bin\flang.exe+0x21c7)
#18 0x00007ff64f8d1315 WinMainCRTStartup (D:\Programs\msys64_test\clang64\bin\flang.exe+0x1315)
#19 0x00007ff64f8d1366 mainCRTStartup (D:\Programs\msys64_test\clang64\bin\flang.exe+0x1366)
#20 0x00007ffcd54c7344 (C:\WINDOWS\System32\KERNEL32.DLL+0x17344)
#21 0x00007ffcd65e26b1 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x526b1)
flang: error: flang frontend command failed due to signal (use -v to see invocation)
flang version 17.0.4
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/Programs/msys64_test/clang64/bin
flang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
flang: note: diagnostic msg: D:/Programs/msys64_test/tmp/constants-8da683
flang: note: diagnostic msg: D:/Programs/msys64_test/tmp/constants-8da683.sh
flang: note: diagnostic msg:

********************
Segmentation fault
```

**Comment by mmuetzel** [comment]
IIUC, the LLVM project is working on a way to separate their Flang runtime from the rest of the compiler. See, e.g.:
https://reviews.llvm.org/D154869
https://discourse.llvm.org/t/rfc-support-cmake-option-to-control-link-type-built-for-flang-runtime-libraries/71602/27

I don't know if we should spend energy into inventing a solution for that ourselves before they do...

**Comment by MehdiChinoune** [comment]
> IIUC, the LLVM project is working on a way to separate their Flang runtime from the rest of the compiler. See, e.g.: https://reviews.llvm.org/D154869 https://discourse.llvm.org/t/rfc-support-cmake-option-to-control-link-type-built-for-flang-runtime-libraries/71602/27
> 
> I don't know if we should spend energy into inventing a solution for that ourselves before they do...

I know about it, At least we should fix building shared libraries, It decreases the size of the package a lot.

**Pull request closed without merging**
