### PR TITLE
CMake: Build cmake-gui for clang64 and ucrt

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Enable Qt GUI on clang64 and ucrt

### CODE REVIEW

**Comment by jeremyd2019** [comment]
We still have clang32 and clangarm64 which have not gotten qt5

**Comment by MehdiChinoune** [comment]
> We still have clang32 and clangarm64 which have not gotten qt5

You can update it later.

**Comment by MehdiChinoune** [comment]
- Fix default generator
cmake will default to "Unix Makefiles"

**Comment by lazka** [comment]
> > We still have clang32 and clangarm64 which have not gotten qt5
> 
> You can update it later.

Ideally this PR wouldn't break it in the first place.

**Comment by jeremyd2019** [comment]
>   cmake will default to "Unix Makefiles"

Is this the most sensible default?  It seems like if any makefiles would be default, "MSYS Makefiles" would be the one to use.

**Comment by 1480c1** [comment]
> > cmake will default to "Unix Makefiles"
> 
> Is this the most sensible default? It seems like if any makefiles would be default, "MSYS Makefiles" would be the one to use.

`MSYS Makefiles` is supposed to be for msys provided from MinGW and `MinGW Makefiles` is supposed to be for `mingw32-make` provided by MinGW, `Unix Makefiles` works fine for `make`, `Ninja` is a bit preferable though.

As a personal note for when actually building with cmake, I prefer to use just `cmake --build $builddir` as the user can set `CMAKE_GENERATOR` to their own and that will override the default (in the case of no `-G`) and assuming one way or the other without explicit `-G` can break `PKGBUILD`s, as it does for me on manjaro

**Comment by MehdiChinoune** [comment]
> >   cmake will default to "Unix Makefiles"
> 
> Is this the most sensible default?  It seems like if any makefiles would be default, "MSYS Makefiles" would be the one to use.

That needs more work.

**Comment by lazka** [comment]
>  cmake will default to "Unix Makefiles"

What did it use before? We don't use "Unix Makefiles"

**Comment by 1480c1** [comment]
> > cmake will default to "Unix Makefiles"
> 
> What did it use before? We don't use "Unix Makefiles"

cmake defaults to checking visual studio installs, then NMake if vs isn't there for windows

**Comment by lazka** [comment]
I would either leave it as is or switch to ninja.

**Pull request closed without merging**
