### PR TITLE
nss: update to 3.73.1

### PR DESCRIPTION
**Pull request by lb90**

### CODE REVIEW

**Comment by lb90** [comment]
This version should contain fixes for the BigSig vulnerability, as reported in https://googleprojectzero.blogspot.com/2021/12/this-shouldnt-have-happened.html

**Comment by lb90** [comment]
This is now ready!

**Comment by lazka** [comment]
Thanks! I remember trying to update it once and failing miserably :)

**Comment by lazka** [comment]
@Jehan in the repo now

**Comment by Jehan** [comment]
Thanks @lazka and @lb90 ! 👍

**Comment by lazka** [comment]
btw, if you are interested in dependencies of a set of packages you can filter the "outdated" page based on that: https://packages.msys2.org/outofdate?related=mingw-w64-gimp%2Cmingw-w64-gtk3 (See input box at the bottom)

**Pull request merged**
