### PR TITLE
python-click: Add documentation

### PR DESCRIPTION
**Pull request by podsvirov**
Depends:
- [x] #14064
- [x] #14065
- [x] #14075

### CODE REVIEW

**Comment by Biswa96** [comment]
Just curious. Does anyone read HTML documentation from packages? Most of the python modules have readthedocs website.

**Comment by podsvirov** [comment]
I am reading. :smile: 📖

**Comment by brisingraerowing** [comment]
Offline docs are useful (I use them sometimes), but putting them in a separate package (like is done with SQLite) might be preferable (some people might not want them cluttering up their filesystem).

**Comment by podsvirov** [comment]
> Offline docs are useful (I use them sometimes), but putting them in a separate package (like is done with SQLite) might be preferable (some people might not want them cluttering up their filesystem).

Please see https://github.com/msys2/MINGW-packages/pull/6336#issuecomment-607908235.

**Comment by lazka** [comment]
> Please see [#6336 (comment)](https://github.com/msys2/MINGW-packages/pull/6336#issuecomment-607908235).

We are less strict nowadays, with having more automation in place. It's still easier for everyone involved to not split though.

**Pull request merged**
