### PR TITLE
Modular Qt5

### PR DESCRIPTION
**Pull request by MehdiChinoune**
This the best solution I can come with.

I tried to build each submodule individually but qtdeclarative fails to build and I didn't find a solution. So I decided to build qtbase and qtdeclarative only from the single module and then build the other submodules individually.
Hope that works.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Libraries built from submodule files:
    - 3d
    - activeqt
    - connectivity
    - datavis3d
    - imageformats
    - gamepad
    - graphicaleffects
    - lottie
    - multimedia
    - networkauth
    - purchasing
    - quickcontrols
    - quicktimeline
    - remoteobjects
    - scxml
    - sensors
    - serialbus
    - serialport
    - speech
    - svg
    - tools
    - translations
    - webglplugin
    - websockets
    - winextras
    - xmlpatterns
    - webchannel
    - webview
  
Libraries fails to:
    - declarative
    - location
    - quick3d
    - quickcontrols2
    - charts
    - script

**Comment by MehdiChinoune** [comment]
It should be ready now.

**Comment by jeremyd2019** [comment]
what's the plan with the existing monolithic qt5 package?  I expected it would have been removed in this pull request but apparently not...  Do I still need to update it too like #9357 ?

**Comment by lazka** [comment]
We need to move all reverse deps away (like #9361) and then tell people to uninstall it, because it will conflict on upgrades :(

**Comment by MehdiChinoune** [comment]
> what's the plan with the existing monolithic qt5 package? I expected it would have been removed in this pull request but apparently not... Do I still need to update it too like #9357 ?

My plan is:
1- Mark qt5 as a provider of all its components, so we the existing users can still use until we rebuild all the qt5-dependent packages.
2- Rebuild qt5-dependent packages one by one until we got no dependency on monolithic qt5
3- Remove monolithic qt5

**Comment by lazka** [comment]
>  3- Remove monolithic qt5

can we make it a dummy package depending on all components instead?

**Comment by jeremyd2019** [comment]
> 1- Mark qt5 as a provider of all its components, so we the existing users can still use until we rebuild all the qt5-dependent packages.

OK, then I won't worry about rebuilding it, as this will cause a rebuild (and it takes some time to build, so no reason to do it twice)

**Comment by MehdiChinoune** [comment]
> > 3- Remove monolithic qt5
> 
> can we make it a dummy package depending on all components instead as step 3?

I think this is better.

**Comment by jeremyd2019** [comment]
Question though... where did `fad2dc11.diff.zip::https://codereview.qt-project.org/changes/qt%2Fqtbase~333051/revisions/1/patch?zip` go in the new modular packages?  Is it still necessary?

**Comment by Alexpux** [comment]
Probably better create Qt5-meta package and add to it conflicts and replaces for Qt5 package

**Pull request merged**
