### PR TITLE
Add 0016-Ensure-lmsvcrt-precede-lkernel32.patch

### PR DESCRIPTION
**Pull request by lhmouse**

### CODE REVIEW

**Comment by Alexpux** [comment]
@lhmouse I’m already building new GCC with this patch, so add only to git

**Comment by lhmouse** [comment]
ok. force-pushed.

**Comment by lazka** [comment]
```
error: patch failed: gcc/config/i386/mingw32.h:165
error: gcc/config/i386/mingw32.h: patch does not apply
```

**Comment by lhmouse** [comment]
Strange. I'll update it tommorrow.

**Comment by mati865** [comment]
That was fast: https://github.com/gcc-mirror/gcc/commit/850533ab160ef40eccfd039e1e3b138cf26e76b8

**Comment by lhmouse** [comment]
@mati865 what? The patch in this PR is against the GCC 10 branch, not the master branch.

**Comment by mati865** [comment]
@lhmouse oops. No clue then, that code hasn't changed at all since 5 years.

**Pull request merged**
