### PR TITLE
mlir: update to 15.0.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
MINGW64:
```
  [1397/1397] Linking CXX shared library bin\libMLIR.dll
  FAILED: bin/libMLIR.dll tools/mlir-shlib/libMLIR.dll.a 
  cmd.exe /C "cd . && D:\M\msys64\mingw64\bin\clang++.exe -march=x86-64 -mtune=generic -O2 -pipe -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -Werror=mismatched-tags -O3 -DNDEBUG  -pipe   -Wl,--gc-sections -shared -o bin\libMLIR.dll -Wl,--out-implib,tools\mlir-shlib\libMLIR.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\MLIR.rsp  && cd ."
  D:/M/msys64/mingw64/bin/ld: error: export ordinal too large: 98873
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
CLANG64:
```
  [1389/1397] Linking CXX shared library bin\libMLIR.dll
  FAILED: bin/libMLIR.dll tools/mlir-shlib/libMLIR.dll.a 
  cmd.exe /C "cd . && D:\M\msys64\clang64\bin\clang++.exe -march=x86-64 -mtune=generic -O2 -pipe -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -Werror=mismatched-tags -O3 -DNDEBUG  -pipe   -Wl,--gc-sections -shared -o bin\libMLIR.dll -Wl,--out-implib,tools\mlir-shlib\libMLIR.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\MLIR.rsp  && cd ."
  ld.lld: error: too many exported symbols (got 77100, max 65535)
  
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Should we disable building `libMLIR.dll`?
@mati865 
@mstorsjo

### CODE REVIEW

**Comment by mati865** [comment]
How did you manage to build it without crashing Clang?
Just checked out your branch, ran `MINGW_ARCH=clang64 makepkg-mingw -C` and Clang crashed shortly after building started.

The error may indicate that symbol visibility is not enabled which I suppose is caused by split PKGBUILD from main LLVM package

**Comment by MehdiChinoune** [comment]
> How did you manage to build it without crashing Clang? Just checked out your branch, ran `MINGW_ARCH=clang64 makepkg-mingw -C` and Clang crashed shortly after building started.

I haven't see any crash!

> 0009-Use-hidden-visibility-when-building-for-MinGW-with-Clang.patch

Yes, That was missing.

**Comment by MehdiChinoune** [comment]
Applying the patch didn't help!

**Comment by MehdiChinoune** [comment]
passing `-DCMAKE_C_VISIBILITY_PRESET=hidden -DCMAKE_CXX_VISIBILITY_PRESET=hidden` has fixed the building. Hopefully It won't break anything.

**Comment by MehdiChinoune** [comment]
Building flang 15.0.0 has succeeded with it, so I assume It's OK.

**Comment by MehdiChinoune** [comment]
Is it OK to merge this?

**Comment by mati865** [comment]
Since Flang is our only user of MLIR this is probably fine,Martin said some time ago that the real fix is more complicated but we don't need to bother right now.

**Pull request merged**
