### PR TITLE
Add oatpp library

### PR DESCRIPTION
**Pull request by Samega7Cattac**

### CODE REVIEW

**Comment by Biswa96** [comment]
The source should point to the specified tag.

**Comment by Samega7Cattac** [comment]
can't find on the docs how to do that

**Comment by Biswa96** [comment]
Here it is https://wiki.archlinux.org/title/Arch_package_guidelines#Package_sources

**Comment by Biswa96** [comment]
O! my bad. The link already points to pkgver. Need to add Ninja in makedepends.

**Pull request merged**
