### PR TITLE
curl: Fix static library

### LINKED ISSUE #21006: -DNGHTTP3_STATICLIB CFLAGS option has to be specified when building static curl to link against libnghttp3.a
### Description / Steps to reproduce the issue

I tried compiling my library using `msys2/setup-msys2@v2` in GitHub Actions with `CURL_STATICLIB` enabled. This issue is similar to  #5440

### Expected behavior

It was supposed to compile successfully, like the previous `mingw-w64-x86_64-curl` build.

### Actual behavior

undefined reference to `__imp_nghttp3_*'

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Fix #21006

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
@sammycage Could you please download the artifacts and test if they fix your issue.

**Comment by raedrizqie** [comment]
i think those flags should also be added to `Cflags.private` in libcurl.pc

**Comment by MehdiChinoune** [comment]
> i think those flags should also be added to `Cflags.private` in libcurl.pc

They should be added for libnghttp2.pc and libnghttp3.pc

**Comment by sammycage** [comment]
> @sammycage Could you please download the artifacts and test if they fix your issue.

@MehdiChinoune Thank you for providing the artifacts. Unfortunately, I am unable to use them directly. I can only incorporate them through the `msys2/setup-msys2` in our GitHub Actions workflow. 

For your reference, the GitHub Action is still encountering the same errors, even after clearing the cache.

**Comment by Biswa96** [comment]
It is possible to verify shared library imports in static library. The output of `nm /path/to/libfoo.a | grep __imp | sort | uniq` command should have Windows APIs **only**.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune Thank you for providing the artifacts. Unfortunately, I am unable to use them directly.

If you want the issue to be fixed, then you should test the fix. The package is ready just download it and install it.

> I can only incorporate them through the `msys2/setup-msys2` in our GitHub Actions workflow.

This is not possible until the PR got merged, the package got built and deplyed.

> For your reference, the GitHub Action is still encountering the same errors, even after clearing the cache.

Of course.

**Comment by sammycage** [comment]
> If you want the issue to be fixed, then you should test the fix. The package is ready just download it and install it.

I have tested it, and it works as expected. Thanks for the quick fix!

**Pull request merged**
