### PR TITLE
libb64: new package

### PR DESCRIPTION
**Pull request by fauxpark**

### CODE REVIEW

**Comment by Biswa96** [comment]
The package only has a static library. Is that expected?

**Comment by fauxpark** [comment]
I've switched out the static lib for `bin/libb64-0.dll`. Not sure if the name is correct or if I need a `.dll.a` in lib as well.

**Comment by Biswa96** [comment]
I am not sure if shared library is required, just asking. If yes then an import lib is required for linking.

**Comment by fauxpark** [comment]
I'm not 100% sure how to build the import lib. Do you know if this is correct?
```
gendef libb64.dll
dlltool -d libb64.def -D libb64.dll -l libb64.dll.a
```

**Comment by fauxpark** [comment]
Okay, I think this is good to go now, the two example programs compile and run as expected (took me a while to remember `-lb64` goes at the end...).

**Comment by Biswa96** [comment]
Thanks. I have compiled transmission with this package and compilation went well.

**Pull request merged**
