### PR TITLE
Remove gtef

### PR DESCRIPTION
**Pull request by swilmet**
Gtef has been renamed to Tepl, and Tepl is packaged in this repo.
No other package in this repo depends on Gtef.

See:
https://wiki.gnome.org/Projects/Gtef
https://wiki.gnome.org/Projects/Tepl

### CODE REVIEW

**Comment by Biswa96** [comment]
If Gtef has been renamed to Tepl then Tpel PKGBUILD may need a `replaces=()` and/or `conflicts=()` option.

**Comment by swilmet** [comment]
Gtef and Tepl are libraries, and they don’t conflict because they are parallel-installable.

Not sure about the replaces=().

**Comment by swilmet** [comment]
Applications either depend on Gtef or Tepl explicitly, and in this repo no package depends on Gtef anymore.

**Comment by lazka** [comment]
thanks!

**Comment by swilmet** [comment]
Thanks for the quick review!

**Pull request merged**
