### PR TITLE
Fix nvidia-cg-toolkit package.

### PR DESCRIPTION
**Pull request by ofry**
Fix nvidia-cg-toolkit package. innoextract should be in build dependencies.

Signed-off-by: ofry <tim4job@bmail.ru>

### CODE REVIEW

**Comment by Biswa96** [comment]
As mingww64-innoextract is added to makedepends list, remove it from the comment.

**Comment by Biswa96** [comment]
As mingw-w64-innoextract is added to make depends list, it can be removed from the comment now.

**Comment by ofry** [comment]
@Biswa96 Done.

**Comment by lazka** [comment]
bump pkgrel

**Comment by Biswa96** [comment]
Would it make any difference as this package is not in pacman repo yet?

**Comment by Biswa96** [comment]
> bump pkgrel

Would it make any difference as this package is not in pacman repo yet?

**Comment by lazka** [comment]
It would make the build CI system try to build it again. But I guess I can force it in this case.

**Pull request merged**
