### PR TITLE
winfile: Fix building with Clang after Clang 17 and enable aarch64 builds

### PR DESCRIPTION
**Pull request by hmartinez82**
Windows 3.11 ARM64

image

### CODE REVIEW

**Comment by Biswa96** [comment]
Would it be possible to fix the actual compiler error instead of suppressing it?

**Comment by hmartinez82** [comment]
@Biswa96 I'll give it a try :)

**Comment by lazka** [comment]
(I think that's only worth it if you plan to upstream them)

**Comment by hmartinez82** [comment]
@lazka Correct 😅, but the usage of `register` alone has 100 hits in 19 files 😑

**Pull request merged**
