### PR TITLE
Add extra options for wabt and remove unused BUILD_SHARED_LIBS option

### PR DESCRIPTION
**Pull request by ArchGuyWu**

### CODE REVIEW

**Comment by ognevny** [comment]
please, do this in separate PRs

**Comment by ArchGuyWu** [comment]
> please, do this in separate PRs

Done.

**Comment by ognevny** [comment]
please, bump pkgrel

**Comment by ArchGuyWu** [comment]
> please, bump pkgrel

Sorry, I forgot that.

**Comment by ArchGuyWu** [comment]
Is it ok to merge?

**Comment by ognevny** [comment]
I found that wabt can use system gtest with `-DUSE_SYSTEM_GTEST=ON`. can you add and remove gtest sybmodule, please?

**Comment by ArchGuyWu** [comment]
> I found that wabt can use system gtest with `-DUSE_SYSTEM_GTEST=ON`. can you add and remove gtest sybmodule, please?

OK

**Comment by ognevny** [comment]
also it uses python, add `${MINGW_PACKAGE_PREFIX}-python` to makedepends and `-DPython3_EXECUTABLE=${MINGW_PREFIX}/bin/python.exe` option

**Comment by ArchGuyWu** [comment]
> also it uses python, add `${MINGW_PACKAGE_PREFIX}-python` to makedepends and `-DPython3_EXECUTABLE=${MINGW_PREFIX}/bin/python.exe` option

Ok.

**Comment by ArchGuyWu** [comment]
GoogleTest itself recommend building GoogleTest from the latest commit instead.
https://github.com/google/googletest/releases/tag/v1.15.2

**Comment by ognevny** [comment]
> GoogleTest itself recommend building GoogleTest from the latest commit instead.
> https://github.com/google/googletest/releases/tag/v1.15.2

does it matter? it's only used for tests that autobuild doesn't run

**Comment by ArchGuyWu** [comment]
> > GoogleTest itself recommend building GoogleTest from the latest commit instead.
> > https://github.com/google/googletest/releases/tag/v1.15.2
> 
> does it matter? it's only used for tests that autobuild doesn't run anyway

Don't know, but it's ok to use system one if just for tests.

**Pull request merged**
