### PR TITLE
libimobiledevice: fix clang compilation

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by Biswa96** [comment]
Huge 🌋

**Comment by lazka** [comment]
Did you file this upstream?

**Comment by neheb** [comment]
https://github.com/libimobiledevice/libimobiledevice/pull/1156

Upstream is fairly slow in my experience. In terms of releases at least.

**Comment by neheb** [comment]
https://github.com/libimobiledevice/libirecovery/pull/83

**Comment by Biswa96** [comment]
Instead of storing the huge patches, we could add the raw patch link from those pull request in pkgbuild sources.

**Comment by neheb** [comment]
Not possible with the libirecovery patch. Upstream API changed slightly.

libimobiledevice (the bigger one) is possible I think.

**Pull request merged**
