### PR TITLE
db: update to 6.2.32

### PR DESCRIPTION
**Pull request by Biswa96**
/cc @hgohel @mmuetzel

### CODE REVIEW

**Comment by mmuetzel** [comment]
@jeremyd2019 mentioned in #17871 that there was a license change for this package and that might be the reason that it wasn't updated yet.
Is that no longer an issue?

**Comment by Biswa96** [comment]
There could be, the latest version is 18 according to https://repology.org/project/db/versions. But this is just a minor version update and the version matches with ArchLinux.

**Comment by hgohel** [comment]
Oracle appears to have [moved to AGPL license with db version 6.0](https://docs.oracle.com/cd/E17076_05/html/installation/license_change60.html) and this PR is bumping up from 6.0.19 which was based on the same license. Here's [Oracle's current FAQ on bdb licensing](https://www.oracle.com/database/technologies/berkeleydb-db-faq.html#DoesthemovetotheAGPLopensourcelicenseaffectcustomerswhopurchasedacommerciallicense). Warning this is not my area of expertise - this is just based on documents found via searching.

**Comment by Biswa96** [comment]
> There appears to have been been concerns about bumping up db version previously as well. See [6c041b0](https://github.com/msys2/MINGW-packages/commit/6c041b0d483b8127d9e4e1fdcbe067022ef78c58)

Good catch. openldap does not depend on db now. db was commented out in openldap PKGBUILD file.

**Comment by Biswa96** [comment]
@GitMensch I have fix the gnucobol build issue here. Would you like to review the change please?

**Comment by GitMensch** [comment]
It is good to have Berkeley DB updated, but as it has a different license it seems to be more reasonable to have both bdb (under current license) and bdb-agpl (newest one, under new license), so people can choose.

... not sure how to handle the "conflict" part then...

**Comment by GitMensch** [comment]
@Biswa96: Thanks for checking the GnuCOBOL issue.
The patch tackles the right thing, but that should be done in the templates ([build_aux/pre-inst-env.in](https://github.com/OCamlPro/gnucobol/blob/gnucobol-3.2/build_aux/pre-inst-env.in) and [tests/atlocal.in](https://github.com/OCamlPro/gnucobol/blob/gnucobol-3.2/tests/atlocal.in))

The "real issue" is that those are already in there:

```sh
# options that are also used in atlocal (always add to both)
COB_CFLAGS="-I@abs_top_srcdir@ @COB_CFLAGS@ ${COB_CFLAGS}"
```
https://github.com/OCamlPro/gnucobol/blob/gnucobol-3.2/build_aux/pre-inst-env.in#L41
https://github.com/OCamlPro/gnucobol/blob/gnucobol-3.2/tests/atlocal.in#L231

I therefore think something in MSYS2 must have changed, because these lines were changed 3 years ago (before the previous release, when that worked).

One thing that comes to mind: Does it work better if there's a space after the `-I` (and in this case also the `-L`)?

**Comment by mmuetzel** [comment]
> Oracle appears to have moved to AGPL license with db version 6.0. Here's Oracle's current FAQ on bdb licensing.

According to Wikipedia Oracle moved to the Affero GPL starting with version 6.0.21. The currently packaged version 6.0.19 still uses a less restrictive license.

**Comment by Biswa96** [comment]
So, can this update be merged with the current dependencies? This update is just to fix the python-bsddb3 build.

**Comment by Biswa96** [comment]
I gave up. I am not familiar with license and related stuff.

**Comment by GitMensch** [comment]
@Biswa96 Would you mind to copy the package along with your change as a new mingw-w64-db-agpl package?
If the python-bsddb3 needs the new one (which I'd find strange because that wouldn't be "BSD" as the name implies) then this could be changed to depend on the new package, too.

**Comment by Biswa96** [comment]
> Would you mind to copy the package along with your change as a new mingw-w64-db-agpl package?

I am not sure about that. python-bsddb3 and swi-prolog are both BSD licensed. Feel free to copy my changes and create a separate pull request.

**Pull request closed without merging**
