### PR TITLE
rust: Update to 1.55.0

### PR DESCRIPTION
**Pull request by filnet**

### CODE REVIEW

**Comment by filnet** [comment]
Strange that CI succeeds. On my end, I get an error when building;

```
Philippe@DESKTOP-IIU0C7D MSYS /C/MINGW-packages/mingw-w64-rust
$ makepkg-mingw -sCLf
==> Making package: mingw-w64-rust 1.55.0-1 (Mon Sep 13 16:50:24 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading rustc-1.55.0-src.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  163M  100  163M    0     0  50.3M      0  0:00:03  0:00:03 --:--:-- 50.3M
  -> Found 0001-add-missing-libs.patch
  -> Found 0004-unbundle-gcc.patch
  -> Found 0005-win32-config.patch
  -> Found 0007-clang-subsystem.patch
  -> Found 0008-disable-self-contained.patch
==> Validating source files with sha256sums...
    rustc-1.55.0-src.tar.gz ... Passed
    0001-add-missing-libs.patch ... Passed
    0004-unbundle-gcc.patch ... Passed
    0005-win32-config.patch ... Passed
    0007-clang-subsystem.patch ... Passed
    0008-disable-self-contained.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
rustc-1.55.0-src/src/tools/cargo/crates/cargo-util/LICENSE-APACHE: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\cargo\\crates\\cargo-util\\LICENSE-APACHE'
rustc-1.55.0-src/src/tools/clippy/rustc_tools_util/LICENSE-APACHE: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\clippy\\rustc_tools_util\\LICENSE-APACHE'
rustc-1.55.0-src/src/tools/cargo/crates/cargo-platform/LICENSE-APACHE: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\cargo\\crates\\cargo-platform\\LICENSE-APACHE'
rustc-1.55.0-src/src/tools/cargo/crates/crates-io/LICENSE-APACHE: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\cargo\\crates\\crates-io\\LICENSE-APACHE'
rustc-1.55.0-src/library/backtrace/crates/backtrace-sys/LICENSE-APACHE: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\library\\backtrace\\crates\\backtrace-sys\\LICENSE-APACHE'
rustc-1.55.0-src/src/tools/cargo/crates/cargo-util/LICENSE-MIT: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\cargo\\crates\\cargo-util\\LICENSE-MIT'
rustc-1.55.0-src/src/tools/clippy/rustc_tools_util/LICENSE-MIT: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\clippy\\rustc_tools_util\\LICENSE-MIT'
rustc-1.55.0-src/src/tools/cargo/crates/cargo-platform/LICENSE-MIT: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\cargo\\crates\\cargo-platform\\LICENSE-MIT'
rustc-1.55.0-src/src/tools/cargo/crates/crates-io/LICENSE-MIT: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\tools\\cargo\\crates\\crates-io\\LICENSE-MIT'
rustc-1.55.0-src/library/backtrace/crates/backtrace-sys/LICENSE-MIT: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\library\\backtrace\\crates\\backtrace-sys\\LICENSE-MIT'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/basic_cross_linux_tree/usr/bin/x86_64-unknown-linux-gnu-ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\basic_cross_linux_tree\\usr\\bin\\x86_64-unknown-linux-gnu-ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/basic_cross_linux_tree/usr/bin/i386-unknown-linux-gnu-ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\basic_cross_linux_tree\\usr\\bin\\i386-unknown-linux-gnu-ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_32bit_linux_tree/usr/bin/ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_32bit_linux_tree\\usr\\bin\\ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_64bit_linux_tree/usr/bin/ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_64bit_linux_tree\\usr\\bin\\ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/basic_cross_linux_tree/usr/x86_64-unknown-linux-gnu/bin/ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\basic_cross_linux_tree\\usr\\x86_64-unknown-linux-gnu\\bin\\ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/basic_cross_linux_tree/usr/i386-unknown-linux-gnu/bin/ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\basic_cross_linux_tree\\usr\\i386-unknown-linux-gnu\\bin\\ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_64bit_linux_tree/usr/x86_64-unknown-linux/bin/ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_64bit_linux_tree\\usr\\x86_64-unknown-linux\\bin\\ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_32bit_linux_tree/usr/i386-unknown-linux/bin/ld: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_32bit_linux_tree\\usr\\i386-unknown-linux\\bin\\ld'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_32bit_linux_tree/usr/bin/as: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_32bit_linux_tree\\usr\\bin\\as'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_64bit_linux_tree/usr/bin/as: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_64bit_linux_tree\\usr\\bin\\as'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_64bit_linux_tree/usr/x86_64-unknown-linux/bin/as: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_64bit_linux_tree\\usr\\x86_64-unknown-linux\\bin\\as'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/multilib_32bit_linux_tree/usr/i386-unknown-linux/bin/as: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\multilib_32bit_linux_tree\\usr\\i386-unknown-linux\\bin\\as'
rustc-1.55.0-src/src/llvm-project/clang/test/Driver/Inputs/CUDA-symlinks/usr/bin/ptxas: Can't create '\\\\?\\C:\\MINGW-packages\\mingw-w64-rust\\src\\rustc-1.55.0-src\\src\\llvm-project\\clang\\test\\Driver\\Inputs\\CUDA-symlinks\\usr\\bin\\ptxas'
tar.exe: Error exit delayed from previous errors.
patching file compiler/rustc_llvm/build.rs
Hunk #1 succeeded at 301 (offset 1 line).
patching file src/bootstrap/dist.rs
patching file src/bootstrap/lib.rs
Hunk #1 succeeded at 1407 (offset 129 lines).
patching file src/bootstrap/configure.py
Hunk #1 succeeded at 290 (offset 1 line).
Hunk #2 succeeded at 327 (offset 1 line).
patching file compiler/rustc_codegen_ssa/src/back/link.rs
Hunk #1 succeeded at 1486 (offset 66 lines).
==> Starting build()...
configure: processing command line
configure:
configure: install.prefix       := /mingw64
configure: install.sysconfdir   := /mingw64/etc
configure: install.localstatedir := /mingw64/var/lib
configure: build.build          := x86_64-pc-windows-gnu
configure: build.host           := ['x86_64-pc-windows-gnu']
configure: build.target         := ['x86_64-pc-windows-gnu']
configure: rust.channel         := stable
configure: llvm.ninja           := True
configure: build.extended       := True
configure: rust.codegen-tests   := False
configure: target.x86_64-pc-windows-gnu.llvm-config := C:/msys64/mingw64/bin/llvm ...
configure: build.python         := C:/msys64/mingw64/bin/python
configure: build.configure-args := ['--prefix=/mingw64', '--sysconfdir=/mingw64/e ...
warning: localstatedir will be ignored


[...]

Dist rust-docs-1.55.0-x86_64-pc-windows-gnu
running: "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\x86_64-pc-windows-gnu\\stage0-tools-bin\\fabricate.exe" "generate" "--image-dir" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\tmp\\tarball\\rust-docs\\x86_64-pc-windows-gnu\\image" "--component-name=rust-docs" "--bulk-dirs" "share/doc/rust/html" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust Documentation" "--success-message=rust-docs installed." "--package-name=rust-docs-1.55.0-x86_64-pc-windows-gnu" "--non-installed-overlay" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\tmp\\tarball\\rust-docs\\x86_64-pc-windows-gnu\\overlay" "--output-dir" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\dist" "--work-dir" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\tmp\\tarball\\rust-docs\\x86_64-pc-windows-gnu"
Error: failed to generate installer

Caused by:
    0: failed to copy 'C:\MINGW-packages\mingw-w64-rust\src\x86_64\build\tmp\tarball\rust-docs\x86_64-pc-windows-gnu\image\share\doc\rust\html\edition-guide\rust-2018\cargo-and-crates-io\cargo-rustc-for-passing-arbitrary-flags-to-rustc.html' to 'C:\MINGW-packages\mingw-w64-rust\src\x86_64\build\tmp\tarball\rust-docs\x86_64-pc-windows-gnu\rust-docs-1.55.0-x86_64-pc-windows-gnu\rust-docs\share\doc\rust\html\edition-guide\rust-2018\cargo-and-crates-io\cargo-rustc-for-passing-arbitrary-flags-to-rustc.html'
    1: Le chemin d’accès spécifié est introuvable. (os error 3)


command did not execute successfully: "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\x86_64-pc-windows-gnu\\stage0-tools-bin\\fabricate.exe" "generate" "--image-dir" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\tmp\\tarball\\rust-docs\\x86_64-pc-windows-gnu\\image" "--component-name=rust-docs" "--bulk-dirs" "share/doc/rust/html" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust Documentation" "--success-message=rust-docs installed." "--package-name=rust-docs-1.55.0-x86_64-pc-windows-gnu" "--non-installed-overlay" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\tmp\\tarball\\rust-docs\\x86_64-pc-windows-gnu\\overlay" "--output-dir" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\dist" "--work-dir" "C:\\MINGW-packages\\mingw-w64-rust\\src\\x86_64\\build\\tmp\\tarball\\rust-docs\\x86_64-pc-windows-gnu"
expected success, got: exit code: 1


Traceback (most recent call last):
  File "C:\MINGW-packages\mingw-w64-rust\src\rustc-1.55.0-src\x.py", line 27, in <module>
    bootstrap.main()
  File "C:/MINGW-packages/mingw-w64-rust/src/rustc-1.55.0-src/src/bootstrap/bootstrap.py", line 1209, in main
    bootstrap(help_triggered)
  File "C:/MINGW-packages/mingw-w64-rust/src/rustc-1.55.0-src/src/bootstrap/bootstrap.py", line 1195, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "C:/MINGW-packages/mingw-w64-rust/src/rustc-1.55.0-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: C:/MINGW-packages/mingw-w64-rust/src/x86_64/build/bootstrap/debug/bootstrap install --stage 2 --verbose
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by filnet** [comment]
The error on my side means I can test the new package...

**Comment by mati865** [comment]
`C:\MINGW-packages\mingw-w64-rust\src\x86_64\build\tmp\tarball\rust-docs\x86_64-pc-windows-gnu\rust-docs-1.55.0-x86_64-pc-windows-gnu\rust-docs\share\doc\rust\html\edition-guide\rust-2018\cargo-and-crates-io\cargo-rustc-for-passing-arbitrary-flags-to-rustc.html` is over 260 characters limit, you need to use shorter path to build it.

**Comment by lazka** [comment]
Build some things and seems to work fine.

Just to be sure: this removes "rust-analyzer.exe" and "cargo-miri.exe". Is that ok?

**Comment by filnet** [comment]
> 
> 
> `C:\MINGW-packages\mingw-w64-rust\src\x86_64\build\tmp\tarball\rust-docs\x86_64-pc-windows-gnu\rust-docs-1.55.0-x86_64-pc-windows-gnu\rust-docs\share\doc\rust\html\edition-guide\rust-2018\cargo-and-crates-io\cargo-rustc-for-passing-arbitrary-flags-to-rustc.html` is over 260 characters limit, you need to use shorter path to build it.

Yep, that was it.

**Comment by filnet** [comment]
> 
> 
> Build some things and seems to work fine.
> 
> Just to be sure: this removes "rust-analyzer.exe" and "cargo-miri.exe". Is that ok?

How come they are gone ?

I am using Visual Code + rls.

**Comment by lazka** [comment]
you can see in the diff in CI.. I dont know..

**Comment by filnet** [comment]
Looks like rust-analyzer and miri are now nightly-only tool.
See https://github.com/rust-lang/rust/commit/6aa79a34d87252deaae11e75663e5740a22f14ea

**Comment by lazka** [comment]
ok to merge then?

**Comment by mati865** [comment]
> Just to be sure: this removes "rust-analyzer.exe" and "cargo-miri.exe". Is that ok?

Yep, it's actually a fix since they were not considered stable yet.

**Pull request merged**
