### PR TITLE
gh: update to v1.10.0

### PR DESCRIPTION
**Pull request by dscho**
It was just released: https://github.com/cli/cli/releases/tag/v1.10.0

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

### CODE REVIEW

**Comment by naveen521kk** [comment]
https://github.com/cli/cli/releases/tag/v1.10.1 is release?

**Comment by dscho** [comment]
> https://github.com/cli/cli/releases/tag/v1.10.1 is release?

Oy... true. I'll prepare a new PR in a moment.

**Comment by dscho** [comment]
Oy! `.2` was released in the meantime. I can't keep up.

**Comment by naveen521kk** [comment]
No worries, I have an automatic thing that will do this, https://github.com/naveen521kk/msys2-updator.

**Comment by dscho** [comment]
> 
> 
> No worries, I have an automatic thing that will do this, https://github.com/naveen521kk/msys2-updator.

Looks complicated. I could not really figure out quickly how it works (I _guess_ a `.json` needs to be added to `packages/` and the `handlers/` magically interpret the `source` URL in the `PKGBUILD` file?).

But maybe it is more flexible than [what I do in Git for Windows](https://github.com/git-for-windows/build-extra/blob/7b657a7d585479d0420d4bce946cf8c45678e90d/please.sh#L2453-L3491) for those packages that I maintain in Git for Windows.

**Comment by dscho** [comment]
> I'll prepare a new PR in a moment.

And here it is: https://github.com/msys2/MINGW-packages/pull/8731

**Comment by naveen521kk** [comment]
> (I guess a .json needs to be added to packages/ and the handlers/ magically interpret the source URL in the PKGBUILD file?).

Yup. As in it checks using Github API(or gitlab API as in the .json file says it) if there is a new version and update the pkgver and checksums. If it's a python package though it does things like resolving dependencies...

**Pull request merged**
