### PR TITLE
add liboqs 0.10.0

### PR DESCRIPTION
**Pull request by d0p1s4m4**
liboqs is a C library for prototyping and experimenting with quantum-resistant cryptography

### CODE REVIEW

**Comment by lazka** [comment]
lgtm.

Is it on purpose that this only builds the static lib?

**Comment by ognevny** [comment]
I find a Rust package that depends on this list. I want to have a shared version of lib :)

**Comment by ognevny** [comment]
@d0p1s4m4 ping you to ask what's the progress on this?

**Comment by d0p1s4m4** [comment]
> @d0p1s4m4 ping you to ask what's the progress on this?

I think it's should be fine now.

**Comment by ognevny** [comment]
> > @d0p1s4m4 ping you to ask what's the progress on this?
> 
> I think it's should be fine now.

there is a compile error in CLANG64

**Comment by lazka** [comment]
To get clang to work someone probably needs to fix the duplicate symbols in upstream.

**Comment by lazka** [comment]
I've added oqsprovider in https://github.com/msys2/MINGW-packages/pull/21655

**Pull request merged**
