### PR TITLE
onefetch: update to 2.21.0

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you provide the source of the patch file? Or, is it mingw specific?

**Comment by ognevny** [comment]
> Could you provide the source of the patch file? Or, is it mingw specific?

I wrote this patch myself. I'm planning to create forks with this change and use [patch.crates-io]

**Comment by Biswa96** [comment]
Understood. Although, I would allow onefetch (or any other rust projects) to link statically if it does not support shared linking.

**Comment by ognevny** [comment]
> Understood. Although, I would allow onefetch (or any other rust projects) to link statically if it does not support shared linking.

this is not about upstream projects, but developers who use this bindings. the main idea is fully static linking in rust (which is even documented in homepage), but cargo and rustc have a stable support of shared libraries (e.g. windows system libraries). so why not?

**Comment by Biswa96** [comment]
> so why not?

This kind of patches are harder to maintain.

**Comment by ognevny** [comment]
> > so why not?
> 
> This kind of patches are harder to maintain. KISS

I can :). as I said I have a plans how to make things easier. but it requires some time. will try tomorrow

**Pull request merged**
