### PR TITLE
mingw-w64-cross-clang: prefixed cross-compiling wrappers for clang

### PR DESCRIPTION
**Pull request by jeremyd2019**
Related to discussion #8736.

Based on wrappers from [llvm-mingw](https://github.com/mstorsjo/llvm-mingw).  Also adds a package that provides "foreign" compiler-rt libs.

The clang wrapper could be simplified (have some of the options removed) if the package is only provided for CLANG*.  I haven't tested them under MINGW*.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
This seems to be working quite well.  I can use this to cross-compile python.  The packaging is a bit odd, but it seems to do the job.

**Comment by driver1998** [comment]
Wonder how will this work with things like cmake, meson and ninja? Can I use mingw64 cmake with aarch64-w64-mingw32-clang?

**Comment by jeremyd2019** [comment]
> Wonder how will this work with things like cmake, meson and ninja? Can I use mingw64 cmake with aarch64-w64-mingw32-clang to cross compile ARM64 binaries on x86_64?

Note I haven't bothered tested the GCC-based MSYSTEMs with this, they should work but who knows...

But with clang64, absolutely!  All the major build systems have a mechanism to configure them to cross-compile.  In fact, I had good luck with cmake not even bothering configuring a toolchain file, and instead just specifying options:

```
        -DCMAKE_{ASM,C,CXX}_COMPILER_TARGET="aarch64-w64-mingw32" \
        -DCMAKE_{ASM,C,CXX}_COMPILER_WORKS=ON \
        -DCMAKE_SYSROOT="/clangarm64" \
        -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
        -DCMAKE_FIND_ROOT_PATH_MODE_{LIBRARY,INCLUDE,PACKAGE}=ONLY \
```

**Comment by jeremyd2019** [comment]
The way I'm doing a "standalone" compiler-rt build here is apparently deprecated.  I'll have to investigate how they intend it to be done now, hopefully it doesn't require downloading the `llvm` sources.

**Comment by mati865** [comment]
How about installing all architectures supported by us on every architecture instead of creating new compiler-rt packages?
It's 35 MiB right now so that would add 70 MiB which doesn't seem so bad considering size and price of today's storage.

**Comment by jeremyd2019** [comment]
How difficult would that be?  Is that possible from the existing mingw-w64-headers-git install or would we need to install the 'foreign' -headers-git like I do for the cross-compiler-rt package here? (compiler-rt only seems to need the headers, thankfully, as it is a static library.  Don't know about the sanitizers, haven't tried to do those for this cross compilation thing yet).

**Comment by mati865** [comment]
Right, forgot about mingw-w64. That would make it even harder than current approach...

**Comment by jeremyd2019** [comment]
I set up a github repository with a release to keep binaries of this, and set up a pacman repo for the latest version.

The files are in the release https://github.com/msys2-arm/cross-clang/releases/repo.  To use, add the following in `/etc/pacman.conf`:

```ini
[cross-clang]
Server = https://github.com/msys2-arm/cross-clang/releases/download/repo
SigLevel = Never
```

**Comment by MehdiChinoune** [comment]
> I set up a github repository with a release to keep binaries of this, and set up a pacman repo for the latest version.
> 
> The files are in the release https://github.com/msys2-arm/cross-clang/releases/repo. To use, add the following in `/etc/pacman.conf`:
> 
> ```ini
> [cross-clang]
> Server = https://github.com/msys2-arm/cross-clang/releases/download/repo
> SigLevel = Never
> ```
```
$ pacman -S mingw-w64-clang-x86_64-cross-clang-aarch64
resolving dependencies...
warning: cannot resolve "mingw-w64-clang-aarch64-crt", a dependency of "mingw-w64-clang-x86_64-cross-clang-aarch64"
warning: cannot resolve "mingw-w64-clang-aarch64-headers", a dependency of "mingw-w64-clang-x86_64-cross-clang-aarch64"
warning: cannot resolve "mingw-w64-clang-aarch64-libc++", a dependency of "mingw-w64-clang-x86_64-cross-clang-aarch64"
warning: cannot resolve "mingw-w64-clang-aarch64-libunwind", a dependency of "mingw-w64-clang-x86_64-cross-clang-aarch64"
warning: cannot resolve "mingw-w64-clang-aarch64-winpthreads-git", a dependency of "mingw-w64-clang-x86_64-cross-clang-aarch64"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-clang-x86_64-cross-clang-aarch64
```

**Comment by jeremyd2019** [comment]
Unfortunately, I had to drop i686 targets for this because there are no more clang32 packages to base it on ☹️.  I have extracted past versions from this PR and put them in https://github.com/msys2-arm/cross-clang, and added a CI to build and upload them to the `repo` release.  Thus, I am going to close this PR and all future versions will happen there.

**Pull request closed without merging**
