### PR TITLE
uasm: fix build

### LINKED ISSUE #7893: uasm: should this be a git package?
I just ran into a source file verification error trying to build uasm.  It was downloading a github archive, so I figured that something internally to github changed, but then I couldn't even find the tag.  Turns out that the PKGBUILD is downloading an archive for a branch, not a tag.  It seems like this should really be a git package (not sure on the current best practice for renaming to -git though).

### PR DESCRIPTION
**Pull request by jeremyd2019**
Change sources to git repo, pinned to same commit that the package was last built against.

Fix multiple definition errors linking by adding -fcommon to compiler flags.

Fixes #7893

Probably still needs some pkgver adjustment, not sure how to go about that on something that uses branches for versions instead of tags.

### CODE REVIEW

**Comment by Biswa96** [comment]
Add the `pkgver()` function like in ghdl or mingw-w64-headers,crt etc. Then `makepkg` will handle the rest.

**Comment by jeremyd2019** [comment]
Those use `git describe --long` which require there to be a tag.  `git describe --long --tags` works for this, but goes back to v213, not referring to v2.50.  It looks like H/globals.h has a `_UASM_VERSION_STR_` that might get the first part, but don't know where the revision count would be counted from.

**Comment by jeremyd2019** [comment]
The mingw-w64 packages turned out to be a better example than the ghdl one, was able to put something together.

**Comment by lazka** [comment]
(I hope that change is OK)

**Pull request merged**
