### PR TITLE
gmp asm x86_64 COFF_TYPE

### LINKED ISSUE #6983: gmp shared library consumers segfault when built with image base > 4GB, headers built for static lib
I decided to try to debug the [gcc segfault](https://github.com/msys2/MINGW-packages/issues/6674#issuecomment-686656479) when built with high image base today.  I build gcc with debug symbols, and the stacktrace disappeared into mpfr, which was not built with debug symbols.  I looked at mpfr, saw it depends on gmp, and started out by building those two packages with debug !strip.  GMP build succeeded, but after installing the built package, gcc would segfault on lines as simple as "d=1.0;" (the crash I had seen in gcc was in real_from_string).

So, it appears that this gcc issue is actually a GMP issue.

### PR DESCRIPTION
**Pull request by jeremyd2019**
Fixes #6983, alternate approach to #7024 .

> My current theory is that for some unknown reason, gmp's assembly functions are resulting in symbols that bfd believes are data, not functions. Without dllimport, this is causing it to use the auto-import hack, which has the Windows loader modify addresses in the function itself, rather than using the jmp thunk which references the `__imp_` symbol. This cannot work correctly on x64 with large addresses, because the CALL instruction is taking a 32-bit relative operand. The only way this can work is with a jmp thunk (unless the compiler knew to generate an indirect CALL, which is what dllimport does).

The 'unknown reason' I mentioned is that the functions were lacking `.type 32`.

> gmp's configure script checks for support for .type pseudo-op, but on mingw that is only allowed inside a .def, and must take an integer not `@function`, so gmp suppresses it altogether.

> My nasty hack seems to have done the trick. So now the question is would we prefer breaking/dropping static libgmp support, following upstream's advice, or introducing a nasty hack so that using static headers with the dynamic libgmp works properly with large addresses.
> 
> ```shell
>   # nasty hack to get asm function symbols identified as functions
>   sed -i 's|^define(<TYPE>, <>)$|define(<TYPE>, <.def $1; .scl 2; .type 32; .endef>)|' config.m4
> ```
> 
> This is nasty because a) configure should be taught how to generate that, and b) that .type is hardcoded for function, whereas the configure-generated macro gets $2 as the type of symbol (function or object I think). For all uses of the macro on mingw/x86 it is only ever passed 'function'.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
gnome-calculator failed to link.  This happened before my changes too, but does not happen on #7024.

**Comment by jeremyd2019** [comment]
Was just looking at how to do this in a way that isn't a nasty hack, and apparently gmp already had and fixed this issue, on x86.  They neglected to include the fix on x86_64.  https://gmplib.org/repo/gmp-6.2/file/tip/acinclude.m4#l2128

Non-hackish patch shortly

**Comment by jeremyd2019** [comment]
Assuming the CI checks succeed, I plan to try sending the patch to gmp upstream.

**Comment by lazka** [comment]
@jeremyd2019 CI looks good

**Comment by jeremyd2019** [comment]
> Assuming the CI checks succeed, I plan to try sending the patch to gmp upstream.

https://gmplib.org/list-archives/gmp-bugs/2020-October/004890.html

**Comment by jeremyd2019** [comment]
https://gmplib.org/list-archives/gmp-bugs/2020-October/004894.html

**Comment by jeremyd2019** [comment]
Is this PR waiting on anything more from me?

**Comment by jeremyd2019** [comment]
https://gmplib.org/list-archives/gmp-bugs/2020-November/004929.html

It looks like a fix for this is committed.  There is a question in there that I am not equipped to answer though:
> Do you know if this might be needed also for mingw running on ARM cpus?

Maybe somebody here has enough knowledge of how Windows on ARM works?  It looks like ld still needs to be told whether a symbol is data or not to generate a proper implib, but what I don't know is whether as wants the same syntax to do so.

**Comment by Biswa96** [comment]
> Maybe somebody here has enough knowledge of how Windows on ARM works? 

Guru here https://github.com/mstorsjo/llvm-mingw

**Comment by jeremyd2019** [comment]
> > Maybe somebody here has enough knowledge of how Windows on ARM works?
> 
> Guru here https://github.com/mstorsjo/llvm-mingw

Thanks.  I was able to query that compiler for what I wanted to know ;)

**Comment by mati865** [comment]
GNU toolchain doesn't support ARM/AArch64 as MinGW target so we would have to test it with LLVM toolchain.

**Pull request merged**
