### PR TITLE
ncurses: update to 6.4.20230211

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/10434

### CODE REVIEW

**Comment by lhmouse** [comment]
Is using tarballs from `https://invisible-mirror.net/archives/ncurses/current/` adhoc or permanent? For example, if ncurses 6.5 is released someday, do we still fetch tarballs there?

**Comment by Biswa96** [comment]
> if ncurses 6.5 is released someday, do we still fetch tarballs there?

It depends. If the mirror link is official and provides signed tarball it would not be changed. If I recall correctly, there was some issue with that link in GitHub actions. So, in that situation source link will be changed.

**Comment by Biswa96** [comment]
Would you like to test if this change fixes the GDB TUI issue?

**Comment by lhmouse** [comment]
I built and installed that tarball locally (with the same SHA-256, albeit not with the PKGBUILD that you have proposed in this PR), and it did fix the issue for me: https://lists.gnu.org/archive/html/bug-ncurses/2023-02/msg00006.html

The issue can be reproduced with https://lists.gnu.org/archive/html/bug-ncurses/2023-02/msg00003.html.

**Comment by Biswa96** [comment]
Not sure what happened. The version number was correct though.

```
$ vercmp 6.4.20230211-1 6.4-1
1
```

**Pull request merged**
