### PR TITLE
[WIP] julia: Update to version 1.4.1

### PR DESCRIPTION
**Pull request by stahta01**
I only know how to make a one line hello world Julia program; so, likely wish to wait till someone who knows Julia says this package works well enough before adding to package build list.

Tim S.

### CODE REVIEW

**Comment by stahta01** [comment]
It builds version 1.3.1; but, the local run of julia fails. More work needed!

**Comment by stahta01** [comment]
Ready to merge. I tested the running of julia under 32 and 64 bit and the simple one line program worked. I can not get the check() code run pass on my slow computer not sure why. Tim S.

**Comment by stahta01** [comment]
I think I found out why the check was not working; but, since it takes about 12 hours to run a check will likely take several days to confirm it is working right.

**Comment by stahta01** [comment]
Going to work on getting version 1.4.1 to build and then see if it can runs checks without a lockup.
Tim S.

**Comment by stahta01** [comment]
I have decided to condense my changes into just two commits.
First, to get version 1.1.1 to build.
Second, to upgrade to version 1.4.1.

Tim S.

**Comment by stahta01** [comment]
@lazka I have no idea how to kill the run away 32 bit build; can you kill it?
Or contact someone to kill it.

Tim S.

**Comment by lazka** [comment]
Sorry for not responding initially.

Can you enable the "Allow edits and access to secrets by maintainers" checkbox for this PR so I can rebase it.

**Comment by stahta01** [comment]
> Sorry for not responding initially.
> 
> Can you enable the "Allow edits and access to secrets by maintainers" checkbox for this PR so I can rebase it.

I do not know how to do that, directions?

Tim S.

**Comment by lazka** [comment]
https://docs.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png

**Comment by stahta01** [comment]
It was already checked I removed the checkmark and rechecked it.

Tim S.

**Comment by lazka** [comment]
your repo is protected for some reason.

anyway, I've pushed this to master manually.

Thanks!

**Pull request closed without merging**
