### PR TITLE
pkgconf: update to 2.2.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
@1480c1

### CODE REVIEW

**Review by 1480c1 — APPROVED** [review]
Seems to work for me

**Comment by dg0yt** [comment]
The mingw package works in vcpkg CI. Thanks!
https://github.com/microsoft/vcpkg/pull/37844

FTR the msys package is still at a flawed source version.

**Comment by MehdiChinoune** [comment]
> FTR the msys package is still at a flawed source version.

I don't understand!

**Comment by Biswa96** [comment]
He is talking about this one https://packages.msys2.org/base/pkgconf

**Comment by dg0yt** [comment]
Yes, I was refering to the "MSYS environment".

**Pull request merged**
