### PR TITLE
Add mingw-w64-nsync package

### PR DESCRIPTION
**Pull request by smalltalkman**

### CODE REVIEW

**Comment by Alexpux** [comment]
@smalltalkman see other cmake packages how they handle PREFIX and DESTDIR

**Comment by Alexpux** [comment]
@smalltalkman see how I fix your re2 package - https://github.com/msys2/MINGW-packages/commit/883a123278e328f8e1e0aa1aeb943cda54d61b3b

**Comment by smalltalkman** [comment]
@Alexpux alright, thank you very much. But I want to know why this is needed. I tested it on both 32-bit and 64-bit.

**Comment by Alexpux** [comment]
@smalltalkman this is how we build and package. 
Using MSYS2_ARG_CONV_EXCL prevent converting UNIX path to Windows

**Comment by smalltalkman** [comment]
@Alexpux fixed

**Pull request merged**
