### PR TITLE
sonixflasher: update to 2.0.6

### PR DESCRIPTION
**Pull request by dexter93**

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you please remove the static flags in Makefile? We prefer dynamic linking and it will reduce the binary file size.

**Comment by dexter93** [comment]
> Could you please remove the static flags in Makefile? We prefer dynamic linking and it will reduce the binary file size.

done, thank you!

**Comment by Biswa96** [comment]
My apology for the confusion, I did not mean to remove the static option in upstream. You could patch is here only. Some may want static linking for a standalone program but for packaging purposes shared linking is preferred.

**Comment by dexter93** [comment]
> My apology for the confusion, I did not mean to remove the static option in upstream. You could patch is here only. Some may want static linking for a standalone program but for packaging purposes shared linking is preferred.

No worries, it was actually a leftover from initial bringup. However, worth noting that I didn't see a binary size difference
Anyway, hope it's ok now :)

**Pull request merged**
