### PR TITLE
gcc: Install a missing binary (g++-mapper-server)

### LINKED ISSUE #10093: MinGW GCC package size growth due to unstripped debug info
While packaging MinGW GCC 11.2.0 for build2 toolchain, we have discovered that debug info is not stripped from static libraries in the `lib/gcc/x86_64-w64-mingw32/11.2.0` directory of the `mingw-w64-x86_64-gcc-11.2.0-1-any.pkg.tar.zst` package archive. 

So, for example `libstdc++.a` size is 32,5M in contrast to that for GCC 10.2.0 (`mingw-w64-x86_64-gcc-10.2.0-1-any.pkg.tar.zst`), which is only 6,5M.

Running `strip -d libstdc++.a` brings the size back to normal (6,9M).

I believe that the GCC package size growth from 26M to 38M is largely due to this issue.

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Also Fixes #10093 (rebuild)

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
```make: INTERNAL: Exiting with 1 jobserver tokens available; should be 3!```
this kind of failure has started appearing since the upgrade of msys-runtime to 3.3.2

**Comment by lazka** [comment]
yeah, that's why I left it in staging. 3.3.3 should be out this week.

**Comment by lazka** [comment]
Maybe I'll revert msys2-runtime in the meantime.

**Comment by MehdiChinoune** [comment]
There were some reports in cygwin mailing-lists about some failures . I think that they have fixed all of them.
https://cygwin.com/pipermail/cygwin/2021-November/249814.html
https://cygwin.com/pipermail/cygwin/2021-November/249910.html
https://cygwin.com/pipermail/cygwin/2021-November/249920.html
https://cygwin.com/pipermail/cygwin/2021-November/249777.html
They are all related to "pipe implementation"

**Comment by MehdiChinoune** [comment]
the mingw32 job succeeded, just failed to download clangarm64 db:
```
error: failed retrieving file 'clangarm64.db.tar.zst.sig' from mirror.clarkson.edu : The requested URL returned error: 500
ci downloading...
error: failed to synchronize all databases (unexpected error) 
```

**Pull request merged**
