### PR TITLE
aalib: Add package for gimp

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/11115

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Is there still an active upstream?  I wonder if it would be worth trying to get the first patch changes related to malloc.h in a better state (the whole point of `AC_CHECK_HEADERS` is that the header may not be present on all systems, it defines a preprocessor macro if it is, so really the include of malloc.h should be in an ifdef rather than removed).  If upstream isn't active, probably not worth the effort because the patch works fine.

**Comment by Biswa96** [comment]
> Is there still an active upstream?

Last Update: [2013-05-02](https://sourceforge.net/p/aa-project/activity) 😁

**Comment by jeremyd2019** [comment]
OK then, I guess nobody is left there to complain if we break pre-C89 compatibility.

**Comment by Biswa96** [comment]
For future reference. The patches were removed from GIMP in this commit https://gitlab.gnome.org/GNOME/gimp/-/commit/1349168d7766685433624a050ab7d7ed7a8c35d4

**Pull request merged**
