### PR TITLE
mosquitto: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by Biswa96** [comment]
Hope the patches are in upstream.

**Comment by podsvirov** [comment]
Unfortunately not yet. I created them today. I think that many of them are not in doubt and I will try to promote them as soon as possible.

**Comment by podsvirov** [comment]
Today a 3 of 5 patches applied.

**Comment by Biswa96** [comment]
In the man pages PR, is there a mismatch in if...elseif section? You have removed `if(WIN32)` but `elseif(WIN32)` remains. Shouldn't it be `elseif(XSLTPROC)`?

**Comment by podsvirov** [comment]
All good. Originally it's do nothing on Windows (`WIN32`), just installed nonexistent files... Now will print warning if `xsltproc` not found.

**Comment by podsvirov** [comment]
*HELP WANTED:* Dear Windows multithreading experts, please take part in the related [discussion](https://github.com/eclipse/mosquitto/issues/2371#issuecomment-970692792).

**Pull request merged**
