### PR TITLE
update GEGL version

### PR DESCRIPTION
**Pull request by lillolollo**

### CODE REVIEW

**Comment by lazka** [comment]
check out the `updpkgsums` command in https://packages.msys2.org/package/pacman-contrib?repo=msys&variant=x86_64 to update checksums

**Comment by Alexpux** [comment]
@lazka GEGL doesnt build for me in any case because of : 
````
[282/789] Generating gegl-0.4.vapi with a custom command
FAILED: gegl/gegl-0.4.vapi 
"D:/msys64/mingw64/bin/vapigen.EXE" "--quiet" "--library=gegl-0.4" "--directory=D:/mingwbuild/mingw-w64-gegl/src/build-x86_64-w64-mingw32/gegl" "--metadatadir=D:/mingwbuild/mingw-w64-gegl/src/gegl-0.4.24/gegl" "--metadatadir=D:/mingwbuild/mingw-w64-gegl/src/gegl-0.4.24/gegl" "D:/mingwbuild/mingw-w64-gegl/src/build-x86_64-w64-mingw32/gegl/Gegl-0.4.gir"
Gegl-0.4.gir:7838.7-7838.60: warning: Signal `Gegl.Node.progress' conflicts with method of the same name
Gegl-0.4.gir:1770.59-1770.59: error: The symbol `Babl' could not be found
Gegl-0.4.gir:2810.57-2810.57: error: The symbol `Babl' could not be found
Gegl-0.4.gir:12159.55-12159.55: error: The symbol `Babl' could not be found
Gegl-0.4.gir:12163.57-12163.57: error: The symbol `Babl' could not be found
[283/789] Compiling C object operations/external/a9161d9@@webp-save@sha/webp-save.c.obj
````

**Comment by lazka** [comment]
I'll have a look

**Comment by lillolollo** [comment]
I have close it because this error

**Comment by lillolollo** [comment]
@lazka @Alexpux we can build GEGL with -Dintrospection=false but is like to put the dust under the carpet

**Pull request closed without merging**
