### PR TITLE
exiv2: update to 0.28

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
We stopped this last time because we would lose unicode path support. Has anything changed there?

**Comment by MehdiChinoune** [comment]
> We stopped this last time because we would lose unicode path support with 0.28.0. Has anything changed there?

I think exiv2 did the opposite It defaults to UNICODE.

**Comment by lazka** [comment]
How can it do that?

**Comment by MehdiChinoune** [comment]
> How can it do that?

I don't know, but according to their README they only supports UCRT which supports UTF-8 by default.
And they also add `-municode` flags on MINGW.

**Comment by lazka** [comment]
The utf-8 locale needs to be set by the process: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170#utf-8-support.

So every application directly or indirectly linking to exiv2 will need to call setlocale when using ucrt somewhere.

Assuming upstream doesn't fix this, I think your approach of splitting things up between ucrt and msvcrt looks good though.

**Comment by lazka** [comment]
@kmilos any thoughts on this?

**Comment by kmilos** [comment]
Agree w/ the approach, but I kinda held back on pushing 0.28.0 on purpose - there are a few regressions and I'd rather have upstream release 0.28.1 (w/ or w/o Unicode restored), and I don't feel like porting back so many patches. @Exiv2/exiv2

**Comment by kmilos** [comment]
Might as well wait for qgis 3.34 including the patch, should come in October AFAICT...

**Comment by MehdiChinoune** [comment]
> Might as well wait for qgis 3.34 including the patch, should come in October AFAICT...

I have already backported the patch

What regressions are you talking about?

**Comment by MehdiChinoune** [comment]
I have backported some fixes (copied from ArchLinux).

**Comment by kmilos** [comment]
> I have backported some fixes (copied from ArchLinux).

Thanks. There's a few more I'd like to get in.

Is.there a particular rush to ship 0.28.0?

**Comment by MehdiChinoune** [comment]
> > I have backported some fixes (copied from ArchLinux).
> 
> Thanks. There's a few more I'd like to get in.
> 
> Is.there a particular rush to ship 0.28.0?

Yes, I have spent a lot of time to backport fixes and make sure that all packages rebuild successfully.
I want to update it as soon as possible before we get any new change from other packages that disrupt the update.

**Comment by kmilos** [comment]
Ok, go ahead then w/ the merge, I'll patch more later as it won't require rebuilds.

**Pull request merged**
