### PR TITLE
libplist: Don't include DllMain in static lib

### PR DESCRIPTION
**Pull request by encounter**
This fixes an issue I was getting trying to include this static library. 

(I also noticed that openssl's libcrypto.a includes a DllMain, is this intentional?)

### CODE REVIEW

**Comment by encounter** [comment]
@Alexpux It looks like some patches are missing from the current repo. Can't find `002-dont-include-winmain-in-static.patch` or `003-fix-cython-decode.patch`.

**Comment by Alexpux** [comment]
@encounter I'm push missing patches

**Comment by Alexpux** [comment]
@encounter  ping?

**Comment by lazka** [comment]
No response, so closing. Feel free to resubmit if this is still a problem.

**Pull request closed without merging**
