### PR TITLE
install-depends fix: arv-viewer needs videoflip GStreamer plugin, whi…

### PR DESCRIPTION
**Pull request by eudoxos**
…ch is in -good plugins

(-base is still sufficient for building)

### CODE REVIEW

**Comment by Biswa96** [comment]
Can you provide any code which proves the requirement? From the meson.build, I found that the gstreamer related pkgconfig files belong to gst-plugin-base package.

**Comment by eudoxos** [comment]
Right here: https://github.com/AravisProject/aravis/blob/main/viewer/arvviewer.c#L62 it will fail at runtime.

**Comment by Biswa96** [comment]
Is it like a plugin to the actual main program? Shouldn't gst-plugins-good be mentioned as option dependency?

**Comment by eudoxos** [comment]
No, it is not optional. The `*-aravis-gst` package only contains the arv-viewer* binary (and its resources), and the viewer will not run without the -good plugins set. It is simply broken without the -good plugins.

**Comment by eudoxos** [comment]
(I am the original packager, BTW, so I know this firsthand)

**Comment by Biswa96** [comment]
Thanks for the hint. In the runtime dependencies list, only gst-plugins-base DLLs are present https://github.com/msys2/MINGW-packages/actions/runs/3601668822/jobs/6067735084#step:11:1759. So, I just make sure of the requirement.

BTW, bump the pkgrel variable please.

**Pull request merged**
