### PR TITLE
openblas: build with openmp support

### PR DESCRIPTION
**Pull request by lazka**
To match what Arch does.

### CODE REVIEW

**Comment by lazka** [comment]
@szhorvat

**Comment by szhorvat** [comment]
Yes, this is what I was suggesting. Based on my reading of https://github.com/xianyi/OpenBLAS/wiki/faq#how-can-i-use-openblas-in-multi-threaded-applications, if any other packages that depend on OpenBLAS use OpenMP, then this is necessary.

**Comment by lazka** [comment]
thanks. I've also opened https://github.com/xianyi/OpenBLAS/issues/3798

**Comment by jeremyd2019** [comment]
Openmp is not built for clangarm64.  Last I heard it was unsupported on windows/arm64

**Comment by lazka** [comment]
Ah, missed that, thx

**Comment by carlkl** [comment]
I can't find a reference for it, but AFAIK openblas used by scipy shouldn't be configured with OpenMP support.

**Comment by lazka** [comment]
I get the same `13 failed, 37771 passed` for the scipy test suite with both openblas configs at least.

**Comment by szhorvat** [comment]
I confirm that the hangs with igraph went away after this change.

**Comment by lazka** [comment]
thanks for testing

**Pull request merged**
