### PR TITLE
Mingw w64 riscv64 unknown elf gcc

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
Based on mingw-w64-arm-none-eabi-gcc.

### CODE REVIEW

**Comment by Biswa96** [comment]
Can the target be added in arm pkgbuild files? I mean one pkgbuild file to create multiple target packages.

**Comment by Fabien-Chouteau** [comment]
> Can the target be added in arm pkgbuild files? I mean one pkgbuild file to create multiple target packages.

Actually I don't know. How would this be done?

**Comment by Fabien-Chouteau** [comment]
@Biswa96 I see that gcc recipes makes multiple packages: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/PKGBUILD

I see multiple drawbacks for tool-chains:
 - The compilation times are already pretty big we already compile everything twice (standard and nano version) so 
 - The different build may require different switches, I think this is doable but might make the script harder to maintain
 - We might want to update to new versions of GCC or newlib at a different time

I'd like to have other opinions on these points.

**Comment by lazka** [comment]
Another downside is that a person updating the arm one might not be able (or know how) to test the other arches.

**Comment by Biswa96** [comment]
Ya, valid logic. I understand.

**Pull request closed without merging**
