### PR TITLE
fastfetch: update to 2.17.0

### PR DESCRIPTION
**Pull request by CarterLi**

### CODE REVIEW

**Comment by Biswa96** [comment]
fastfetch got a library, interesting!

**Comment by CarterLi** [comment]
The library is built for calling WinRT apis, which are not available on Windows 7. Therefore on Windows 7 fastfetch still work despite the dll fails to load.

**Comment by ognevny** [comment]
> fastfetch got a library, interesting!

import libraries should be located in ${prefix}/lib, shouldn't it?

**Comment by Biswa96** [comment]
> import libraries should be located in ${prefix}/lib, shouldn't it?

Yeah, missed it 😝

**Comment by CarterLi** [comment]
[Will be fixed in next release](https://github.com/fastfetch-cli/fastfetch/commit/d50ebc86c708060b61fe8c2cc229cfc5d0dc4e22).

**Pull request merged**
