### PR TITLE
gcc-git: Add Ada and object c build guards

### PR DESCRIPTION
**Pull request by stahta01**
Copied the _enable_ada=no and _enable_objc=no changes to gcc-git.

Tim S.

### CODE REVIEW

**Comment by Alexpux** [comment]
@stahta01 ehy you remove ````--enable-plugin```` from configure options?

**Comment by stahta01** [comment]
> @stahta01 ehy you remove `--enable-plugin` from configure options?

I moved it so only GCC 9 version uses it; GCC 7 does not build with it.

Tim S.

**Comment by Alexpux** [comment]
@stahta01 not only gcc9 but later too

**Comment by stahta01** [comment]
Closing to do more testing and editing

**Pull request closed without merging**
