### PR TITLE
poppler: Update to 21.08.0

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
@sunderme Would you like to test this poppler update? pkgconfig file for poppler-qt6 is added also. The dependent packages will also need a rebuild. I would like to merge this after [pending packages][1] are done.

[1]: https://packages.msys2.org/queue

**Comment by sunderme** [comment]
pkgconfig works

**Comment by lazka** [comment]
The following packages need rebuilds for this:

mingw-w64-poppler-qt6
mingw-w64-pdf2djvu
mingw-w64-gdcm
mingw-w64-gdal
mingw-w64-inkscape
mingw-w64-kfilemetadata-qt5

**Comment by Biswa96** [comment]
Feel free to merge anytime.

**Pull request merged**
