### PR TITLE
New package: frameworkintegration

### PR DESCRIPTION
**Pull request by hmartinez82**
https://archlinux.org/packages/extra/x86_64/frameworkintegration5/

### CODE REVIEW

**Comment by lazka** [comment]
@Biswa96 any thoughts on this re the move to kf6?

**Comment by hmartinez82** [comment]
I can create the kf6 version too when all the upstream deps are out
Same for kdenlive

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=aGVybmFuLmMubWFydGluZXpAZ21haWwuY29t>

**Comment by Biswa96** [comment]
kf6 does not have all the packages yet. I am working on it. I think having an older kf5 version of this/kdenlive would help to find any regression in kf6.

**Comment by Biswa96** [comment]
BTW, which program depends on this library?

**Comment by hmartinez82** [comment]
@Biswa96 I guess you are right. I originally went thru this script https://github.com/KDE/kdenlive/blob/master/packaging/kdenlive-msys2.sh looking at what depds Kdenlive required. As you can see, one of the things it does is to manually download frameworkintegration and build it since MSYS2 doesn't have it. 

But then, when I started writing Kdenlive's PKGBUILD looking at Arch's I didn't add this dependency, and now Kdenlive is working without it. Should we close this without merging then?

**Comment by Biswa96** [comment]
If this is not required, I would choose to close this.

**Comment by hmartinez82** [comment]
Closing since there are not downstream deps.

**Pull request closed without merging**
