### PR TITLE
mingw-w64-headers: Update

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
Where do I get the information for the 4th component of the version number? `6218`right now.

### CODE REVIEW

**Comment by HazardyKnusperkeks** [comment]
Really need this, so that
```
E:/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h:1570:52: error: invalid conversion from 'void*' to 'DXVA2FixedToFloat(DXVA2_Fixed32)::<unnamed struct>*' [-fpermissive]
 1570 |   struct { USHORT Fraction; SHORT Value; } *_f32 = (void *)&f32;
      |                                                    ^~~~~~~~~~~~
      |                                                    |
      |                                                    void*
```
does not happen anymore. :)

**Comment by Biswa96** [comment]
The 4th number is the number of commits after actual version 9 release. The `pkgver` variable is automatically updated while building the package by `pkgver()` function.

1. The way one should do: Build the package with `makepkg-mingw` which clones the whole mingw-w64 repo, **no** shallow clone.
2. Cheating: Go to the GitHub Actions build log. Copy the version from there. There is a line like this:

```
  ==> Starting pkgver()...
  ==> Updated version: mingw-w64-headers-git 9.0.0.6144.45def5d7-1
```

Shh... No one can hear about this 🤫

**Comment by HazardyKnusperkeks** [comment]
Okay, but that number is lower? As far as I checked `45def5d7` is newer than `07922837`.

**Comment by Biswa96** [comment]
6144 > 6128

**Comment by HazardyKnusperkeks** [comment]
Okay, I made a typo in my comment, and then looked only at my comment. Thanks!

**Comment by lazka** [comment]
qt5 also fails because of this:

```
2021-03-27T22:29:47.2938391Z                  from player/directshowevrvideowindowcontrol.h:43,
2021-03-27T22:29:47.2951303Z                  from player/directshowplayerservice.cpp:63:
2021-03-27T22:29:47.2953168Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h: In function 'float DXVA2FixedToFloat(DXVA2_Fixed32)':
2021-03-27T22:29:47.2955080Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h:1570:52: error: invalid conversion from 'void*' to 'DXVA2FixedToFloat(DXVA2_Fixed32)::<unnamed struct>*' [-fpermissive]
2021-03-27T22:29:47.2977482Z  1570 |   struct { USHORT Fraction; SHORT Value; } *_f32 = (void *)&f32;
2021-03-27T22:29:47.2979292Z       |                                                    ^~~~~~~~~~~~
2021-03-27T22:29:47.2980134Z       |                                                    |
2021-03-27T22:29:47.2980857Z       |                                                    void*
2021-03-27T22:29:47.5954565Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h: In function 'DXVA2_Fixed32 DXVA2FloatToFixed(float)':
2021-03-27T22:29:47.5983900Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h:1576:52: error: invalid conversion from 'void*' to 'DXVA2FloatToFixed(float)::<unnamed struct>*' [-fpermissive]
2021-03-27T22:29:47.7863777Z  1576 |   struct { USHORT Fraction; SHORT Value; } *_f32 = (void *)&f32;
2021-03-27T22:29:47.7913491Z       |                                                    ^~~~~~~~~~~~
2021-03-27T22:29:47.8702367Z       |                                                    |
2021-03-27T22:29:47.8706434Z       |                                                    void*
2021-03-27T22:29:47.9814477Z In file included from C:/_/M/mingw-w64-qt5/src/x86_64/qtbase/include/QtCore/qloggingcategory.h:1,
2021-03-27T22:29:48.1365172Z                  from common/directshowglobal.h:46,
2021-03-27T22:29:48.1804007Z                  from player/directshowplayerservice.h:51,
2021-03-27T22:29:48.1889037Z                  from player/directshowplayerservice.cpp:48:
2021-03-27T22:29:48.1894750Z player/directshowplayerservice.cpp: In member function 'void DirectShowPlayerService::load(const QMediaContent&, QIODevice*)':
2021-03-27T22:29:48.1899152Z player/directshowplayerservice.cpp:313:43: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'HRESULT' {aka 'long int'} [-Wformat=]
2021-03-27T22:29:48.3737170Z   313 |             qCWarning(qtDirectShowPlugin, "[0x%x] Failed to attach filter to capture graph", hr);
2021-03-27T22:29:48.5213933Z       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~
2021-03-27T22:29:48.5214809Z make[5]: Leaving directory '/c/_/M/mingw-w64-qt5/src/x86_64/qtmultimedia/src/plugins/directshow'
2021-03-27T22:29:48.5794265Z       |                                  
```

**Comment by HazardyKnusperkeks** [comment]
> 
> 
> qt5 also fails because of this:
> 
> ```
> 2021-03-27T22:29:47.2938391Z                  from player/directshowevrvideowindowcontrol.h:43,
> 2021-03-27T22:29:47.2951303Z                  from player/directshowplayerservice.cpp:63:
> 2021-03-27T22:29:47.2953168Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h: In function 'float DXVA2FixedToFloat(DXVA2_Fixed32)':
> 2021-03-27T22:29:47.2955080Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h:1570:52: error: invalid conversion from 'void*' to 'DXVA2FixedToFloat(DXVA2_Fixed32)::<unnamed struct>*' [-fpermissive]
> 2021-03-27T22:29:47.2977482Z  1570 |   struct { USHORT Fraction; SHORT Value; } *_f32 = (void *)&f32;
> 2021-03-27T22:29:47.2979292Z       |                                                    ^~~~~~~~~~~~
> 2021-03-27T22:29:47.2980134Z       |                                                    |
> 2021-03-27T22:29:47.2980857Z       |                                                    void*
> 2021-03-27T22:29:47.5954565Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h: In function 'DXVA2_Fixed32 DXVA2FloatToFixed(float)':
> 2021-03-27T22:29:47.5983900Z D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/include/dxva2api.h:1576:52: error: invalid conversion from 'void*' to 'DXVA2FloatToFixed(float)::<unnamed struct>*' [-fpermissive]
> 2021-03-27T22:29:47.7863777Z  1576 |   struct { USHORT Fraction; SHORT Value; } *_f32 = (void *)&f32;
> 2021-03-27T22:29:47.7913491Z       |                                                    ^~~~~~~~~~~~
> 2021-03-27T22:29:47.8702367Z       |                                                    |
> 2021-03-27T22:29:47.8706434Z       |                                                    void*
> 2021-03-27T22:29:47.9814477Z In file included from C:/_/M/mingw-w64-qt5/src/x86_64/qtbase/include/QtCore/qloggingcategory.h:1,
> 2021-03-27T22:29:48.1365172Z                  from common/directshowglobal.h:46,
> 2021-03-27T22:29:48.1804007Z                  from player/directshowplayerservice.h:51,
> 2021-03-27T22:29:48.1889037Z                  from player/directshowplayerservice.cpp:48:
> 2021-03-27T22:29:48.1894750Z player/directshowplayerservice.cpp: In member function 'void DirectShowPlayerService::load(const QMediaContent&, QIODevice*)':
> 2021-03-27T22:29:48.1899152Z player/directshowplayerservice.cpp:313:43: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'HRESULT' {aka 'long int'} [-Wformat=]
> 2021-03-27T22:29:48.3737170Z   313 |             qCWarning(qtDirectShowPlugin, "[0x%x] Failed to attach filter to capture graph", hr);
> 2021-03-27T22:29:48.5213933Z       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~
> 2021-03-27T22:29:48.5214809Z make[5]: Leaving directory '/c/_/M/mingw-w64-qt5/src/x86_64/qtmultimedia/src/plugins/directshow'
> 2021-03-27T22:29:48.5794265Z       |                                  
> ```

Actually that's what it should fix (and I'm right now compiling it, although not from this repository). What is also needed is an update of the crt.

**Comment by lazka** [comment]
I will update all of `mingw-w64-` later in one go, I hope that's ok.

**Comment by HazardyKnusperkeks** [comment]
> 
> 
> I will update all of `mingw-w64-` later in one go, I hope that's ok.

Sure thing. Should I bother with pull requests in the future, or just open an issue?

**Comment by lazka** [comment]
but this looks fine too, will do the rest later then. PRs or issues are fine.

thanks

**Pull request merged**
