### PR TITLE
vala: update to v0.56.6

### PR DESCRIPTION
**Pull request by wszqkzqk**

### CODE REVIEW

**Comment by hmartinez82** [comment]
LLVM 16 tidbits
```
../../vala-0.56.6/gobject-introspection/grealpath.h:29:19: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
          extern __stdcall GetFullPathNameA(const char*, int, char*, char**);
```

Needs patching or using `-Wno-implicit-int`

**Comment by Biswa96** [comment]
@wszqkzqk Would you like to apply the attached patch file? [0002-vala-fix-function-decl.patch](https://github.com/msys2/MINGW-packages/files/11151458/0002-vala-fix-function-decl.patch)

**Comment by Biswa96** [comment]
The patch was sent to upstream in this merge request https://gitlab.gnome.org/GNOME/vala/-/merge_requests/304

**Comment by wszqkzqk** [comment]
> @wszqkzqk Would you like to apply the attached patch file? [0002-vala-fix-function-decl.patch](https://github.com/msys2/MINGW-packages/files/11151458/0002-vala-fix-function-decl.patch)

OK

**Pull request merged**
