### PR TITLE
wxwidgets3.2: Add package version 3.2.0

### PR DESCRIPTION
**Pull request by stahta01**

### CODE REVIEW

**Comment by stahta01** [comment]
It would be best if PR #12194 was applied before this package; but, either can be applied first.

Tim S.

**Comment by stahta01** [comment]
I am trying to figure out how to get CodeLite IDE to build and run; currently wxCrafter plugin crashes on startup.
So, I am testing various wx3.2.0 builds

**Comment by stahta01** [comment]
Gave up on fixing CodeLite wxCrafter plugin crash see #12271

**Comment by stahta01** [comment]
I am testing the wxGTK split packages and found an error. That is why I added back the WIP

**Comment by stahta01** [comment]
I was able to build the Code::Blocks IDE code CB project linking against wxGTK/Win after a moderate amount of editing.
And, it even ran and displayed without error; did not try use it after it was displayed.

**Comment by stahta01** [comment]
Any new feedback on this package?

**Comment by lazka** [comment]
I'll have a look once I've cleaned up the 3.0 dependencies

**Comment by lazka** [comment]
What about renaming "base-libs" to "common-libs", or "common" to "base", so there is some symmetry?

**Comment by stahta01** [comment]
> What about renaming "base-libs" to "common-libs", or "common" to "base", so there is some symmetry?
> 
> I've pushed a small fix: [92433ff](https://github.com/msys2/MINGW-packages/commit/92433ff74c98dec0279f2315894830f71052c1a1)

wxWidgets uses wxBase; but, Arch Linux use common. I can see common-libs as being more inline with Arch Linux.
So, that will be the way I think the others will most accept; so, I will change it that way if that is what the msys2 team.
Tim S.

**Comment by lazka** [comment]
You don't have to change it, it's just something that came to mind :)

**Comment by asmwarrior** [comment]
Hi, @stahta01 since wxWidgets 3.2.1 has released, can you take time to update msys2's package to wx 3.2.1? Thanks.

**Comment by stahta01** [comment]
Okay, I have already updated the package; but, I have not really tested it.

Tim S.

**Pull request merged**
