### PR TITLE
enable a few more clangarm64 packages

### PR DESCRIPTION
**Pull request by kmilos**
Includes pugixml update to 1.12, lcms2 dependency cleanup, and adding missing licenses.

### CODE REVIEW

**Comment by Biswa96** [comment]
Try to use `${MSYSTEM}` in build folder, it's trending now 😊

**Comment by Crystal013TKFM** [comment]
If you prefer lowercase, you can write `${MSYSTEM,,}`
On the contrary, `${MINGW_ARCH^^}` will convert it to uppercase

**Comment by kmilos** [comment]
> If you prefer lowercase, you can write `${MSYSTEM,,}`
> On the contrary, `${MINGW_ARCH^^}` will convert it to uppercase

This what the `makepkg-mingw` script does already, both ways.

**Comment by jeremyd2019** [comment]
MINGW_ARCH is allowed to be a space-separated list of arches to build.  MSYSTEM is set to each for each individual build.

**Comment by kmilos** [comment]
Ah, thanks for that insight! Will change it then.

**Pull request merged**
