### PR TITLE
yt-dlp: Add package

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/17921

### CODE REVIEW

**Comment by raedrizqie** [comment]
@Biswa96 isn't this a python extension?

**Comment by Biswa96** [comment]
What is python extension?

**Comment by raedrizqie** [comment]
a python module package? i mean, the package name should have a 'python' prefix, maybe?

**Comment by Biswa96** [comment]
Though there are some rules about python package naming https://wiki.archlinux.org/title/Python_package_guidelines, here I just followed ArchLinux's package name. To me, everything is a python module 😄

**Pull request merged**
