### PR TITLE
arm-none-eabi-gcc: update to 10.1.0

### PR DESCRIPTION
**Pull request by umarcor**

### CODE REVIEW

**Comment by lazka** [comment]
@fauxpark ok?

**Comment by fauxpark** [comment]
Apparently there are still issues with LTO - trying to compile QMK causes this warning at linking stage:

```
Linking: .build/planck_rev6_default.elf                                                             [WARNINGS]
 | 
 | lto-wrapper: warning: Options to Xassembler do not match: -adhlns=.build/obj_planck_rev6_default/muse.lst, -adhlns=.build/obj_planck_rev6_default/keyboards/planck/planck.lst, dropping all -Xassembler and -Wa options.
```
and does not reduce file size as expected.

Additionally there is some problem with the change in behaviour of `-fcommon`? I think it was implied before but is not now. This may be something we should fix on our side, though.

**Comment by Fabien-Chouteau** [comment]
There is already #7465 that updates GCC to `10.1.0` and enables Ada support.
The PR is stalled since two months ago because the build takes too long for GH actions runs.

**Comment by umarcor** [comment]
Thanks @Fabien-Chouteau. I overlooked that. Closing this as a dup.

**Comment by lazka** [comment]
> Additionally there is some problem with the change in behaviour of `-fcommon`? I think it was implied before but is not now. This may be something we should fix on our side, though.

yeah, that changed with gcc 10 to be more strict. Maybe fixing it will also help your LTO case.

**Pull request closed without merging**
