### PR TITLE
ncurses: Correctly report Backspace key

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
Recognize and correctly report Backspace key to applications.

### CODE REVIEW

**Comment by Sonic-Amiga** [comment]
Hello! I am working on a ESP8266 project and caught a problem with "make menuconfig": Backspace key in config utility does not work correctly. This patch contains a fix, i hope you find it useful.

I would also love to submit the patch for upstream ncurses, but i can't find an official repository.

**Comment by lazka** [comment]
Thanks. Let's wait a bit to see if upstream responds.

**Comment by Sonic-Amiga** [comment]
@lazka Seems it doesn't. I'm not even sure it's a correct upstream.

**Comment by mmuetzel** [comment]
Iiuc, they are using a mailing list for bug reports and patches:
https://invisible-island.net/ncurses/announce.html

> Contact the current maintainers at
>
> bug-ncurses@gnu.org
> To join the ncurses mailing list, please write email to
>
> bug-ncurses-request@gnu.org
> containing the line:
> subscribe <name>@<host.domain>
>
> This list is open to anyone interested in helping with the development and testing of this package.

**Comment by Sonic-Amiga** [comment]
@mmuetzel Thank you very much for pointing out, i will reach them there.

**Comment by Sonic-Amiga** [comment]
Hello! The upstream has released a new version, ncurses-6.4-20230708 . The bug has been fixed.

**Comment by mmuetzel** [comment]
I opened #17759 to update to that version.

@Sonic-Amiga: Could you please check if the build artifact from that PR fixes the issue reported by you?

**Comment by Sonic-Amiga** [comment]
It does because i built MinGW version of the new archive for testing in absolutely the same way.

**Comment by Sonic-Amiga** [comment]
Superseded by https://github.com/msys2/MINGW-packages/pull/17759

**Pull request closed without merging**
