### PR TITLE
qt-installer-framework: update to 4.7.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Build it against shared Qt6 and external libarchive

@lazka Could you test it with msys2-installer

### CODE REVIEW

**Comment by lazka** [comment]
Will do

**Comment by lazka** [comment]
I don't quite get how that's supposed to work :) It's all linked dynamically, so we can't use it for the installer.

**Comment by MehdiChinoune** [comment]
> I don't quite get how that's supposed to work :) It's all linked dynamically, so we can't use it for the installer.

Isn't a tool to generate installers like NSIS and WiX? (I am seriously asking)

**Comment by podsvirov** [comment]
> Isn't a tool to generate installers like NSIS and WiX? (I am seriously asking)

Yes.

The `installerbase.exe` executable used as base for created installer. It should be linked statically (have no extra dependencies to run on clean system).

**Comment by lazka** [comment]
> Isn't a tool to generate installers like NSIS and WiX? (I am seriously asking)

It is, but from what I understand it does that by just using the executable from the the package and adding some binary stuff at the end.

**Comment by MehdiChinoune** [comment]
> Yes.
> 
> The `installerbase.exe` executable used as base for created installer. It should be linked statically (have no extra dependencies to run on clean system).

We could use windepoyqt to add required dlls

**Comment by podsvirov** [comment]
> We could use windepoyqt to add required dlls

It's bad idea... We should use static linked qt and link with static runtime.

**Comment by MehdiChinoune** [comment]
> It's bad idea

Why?
I see Many apps deploying Qt DLLs with their apps.

**Comment by lazka** [comment]
Note that we need to get one exe in the end, which is the installer. There can't be any DLLs.

**Comment by podsvirov** [comment]
> I see Many apps deploying Qt DLLs with their apps.

This framework can be used to install any application, no qt-based only.
Application himself can use windeployqt to prepare components, that can be packed to installer for late installation.

**Comment by MehdiChinoune** [comment]
> This framework can be used to install any application, no qt-based only.

I know that, It's already used for msys2-installer which is not a Qt App.

> Application himself can use windeployqt to prepare components, that can be packed to installer for late installation.

What does that to do with the installer?

**Comment by podsvirov** [comment]
Just for note: I'm author of the [CPack IFW Generator](https://cmake.org/cmake/help/latest/cpack_gen/ifw.html) and @lazka wrote right thinks.

**Comment by podsvirov** [comment]
> We could use windepoyqt to add required dlls

> What does that to do with the installer?

**Comment by MehdiChinoune** [comment]
qt-installer-framework is build on Linux against shared Qt. Linux users use it.

Could I ask, Have you tried it or just a speculation?

I have tried building msys2-installer
```
Caught exception: Component "com.msys2.root.base" does not contain a package description (meta/package.xml is missing).
```

**Comment by MehdiChinoune** [comment]
I have successfully generate msys2-installer, but It doesn't launch because of missing dlls and there is no way to fix it.

**Comment by MehdiChinoune** [comment]
I tried to build it against qt6-static but It fails because qt6-static is not fully static.

**Comment by lazka** [comment]
> Could I ask, Have you tried it or just a speculation?

I tried it using the script in https://github.com/msys2/msys2-installer (I had to disable the pacman package downgrade in there though)

**Comment by MehdiChinoune** [comment]
Bad news, It fails to build against qt5-static

**Comment by raedrizqie** [comment]
could you please try building it with qt5-static from #19954 ?

**Comment by MehdiChinoune** [comment]
> could you please try building it with qt5-static from #19954 ?

It's not about static linking.
IFW 4.7.0 was developed against Qt6, while they claim support for Qt5>=5.15.2, It looks like It's broken.

**Comment by raedrizqie** [comment]
i see.. ok then

**Comment by MehdiChinoune** [comment]
I have fixed it to build against qt6-static, just waiting for it from https://github.com/msys2/MINGW-packages/commit/354da6ce to finish building

**Pull request closed without merging**
