### PR TITLE
Add libavro version 1.10.0

### PR DESCRIPTION
**Pull request by dsogari**
From https://github.com/apache/avro

### CODE REVIEW

**Comment by Biswa96** [comment]
The patch file too big. Would it be possible to upstream the changes then update the package here?

**Comment by dsogari** [comment]
@Biswa96 Sorry, the patch got some text that was not intended to be there. I'll update it.

BTW, do you know the correct license name for Apache License 2.0?

**Comment by Biswa96** [comment]
I do not know any hard rule about the license name in PKGBUILD. IMHO, if I need to know the license identifier I straight go to [SPDX License List][1] and copy it 🤓 

[1]: https://spdx.org/licenses/

**Comment by dsogari** [comment]
@Biswa96 Thanks for the feedback! Could you give me a hint on making the x86_64 build pass?

It seems that cmake cannot `execute_process(COMMAND bash version.sh ...)`, where `version.sh` is a bash script located in the `lang/c` directory of the tarball. Do you know of any alternative to running a bash script inside cmake? I'm trying to avoid hardcoding the version numbers in the patch file, so it could be reused in new releases.

**Comment by dsogari** [comment]
Everything OK now.

**Pull request merged**
