### PR TITLE
CI: move continue-on-error from steps to job

### PR DESCRIPTION
**Pull request by jeremyd2019**
See
https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#expressions-in-jobcontinue-on-error

https://github.com/msys2/MINGW-packages/commit/4e952a7445daa0fb9df229ea61b69ccee3264d4a#r49357293

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
That means CI will never report a failure, Is that acceptable for you?
What is the purpose of CI then? Isn't it to check if changes pass or not?

**Comment by jeremyd2019** [comment]
Apparently specifying `continue-on-error` on the job results in the job still reporting as failed in the lists, and also (perhaps more importantly) in the icon on the commit and PR being the red x rather than the green check.  So this may not be desired.

**Comment by jeremyd2019** [comment]
It does show the green icon on the Actions page though, for what that's worth.

**Comment by lazka** [comment]
yeah, that's why I removed it for ucrt64 again. Too hard to see if it failed or not.

**Pull request merged**
