### PR TITLE
imagemagick: Update 7.0.10-6

### PR DESCRIPTION
**Pull request by hiroakit**
## Overview

Merging this PR brings these:

- Update to new version imagemagick.
- Fixed missing imagemagick source url.
  - https://imagemagick.org/download/releases/

## Note

Ref #6342

### CODE REVIEW

**Comment by Alexpux** [comment]
@hiroakit for what reason you rebuild dependent packages?

**Comment by Alexpux** [comment]
Also Im not update packages that are releasing very often as i dont have enought time to build everything

**Comment by hiroakit** [comment]
@Alexpux 

Thank you for your response.
[It](https://github.com/msys2/MINGW-packages/pull/6366#issuecomment-611884074) does not have any special meaning. It is implemented according to previous work.

> Also Im not update packages that are releasing very often as i dont have enought time to build everything
I got it. Thank you.

**Comment by Alexpux** [comment]
I’m rebuild dependent packages only if DLLs names are changed in target package

**Comment by hiroakit** [comment]
@Alexpux

Sure.
This PR fixed wrong imagemagick's url.
Thus please maging.

**Comment by Alexpux** [comment]
@hiroakit revert dependent paackages rebuild

**Comment by hiroakit** [comment]
@Alexpux Reverted the commit.

**Comment by hiroakit** [comment]
Thank you.

**Pull request merged**
