### PR TITLE
texlive: use debian patch for a more sensible zlib check

### PR DESCRIPTION
**Pull request by lazka**
See https://github.com/msys2/MINGW-packages/issues/18251#issuecomment-1923348362

### CODE REVIEW

**Comment by lazka** [comment]
I guess this needs more work

**Comment by lazka** [comment]
@naveen521kk do you have any idea/hints what could be wrong here?

**Comment by naveen521kk** [comment]
> @naveen521kk do you have any idea/hints what could be wrong here?

My guess is https://github.com/msys2/msys2-runtime/issues/190. Though I'll have a better look at it later.

**Comment by lazka** [comment]
I was also just think of that. Let me fix that first then before but work into this.

**Comment by reneparis** [comment]
I scanned through the CI-Build errors, and currently see three different issues:

- MINGW64:
  - `tangleboot.exe: fatal: web file 'tangle.web' not found.`   
     [CI-Build Line 8411](https://github.com/msys2/MINGW-packages/actions/runs/7753937970/job/21728217818?pr=19921#step:11:8411)
  - Preceeded by `WEBINPUTS=.:../../../texk/web2c TEXMFCNF=../../../texk/web2c/../kpathsea ./tangleboot tangle tangle`  
    [CI-Build Line 8409](https://github.com/msys2/MINGW-packages/actions/runs/7753937970/job/21728217818?pr=19921#step:11:8409)

- UCRT64:
  - `error: failed retrieving file` ...
    - `mingw-w64-ucrt-x86_64-python-3.11.8-1-any.pkg.tar.zst` [CI-Build Line 149](https://github.com/msys2/MINGW-packages/actions/runs/7753937970/job/21728218375?pr=19921#step:11:149)
    - `mingw-w64-ucrt-x86_64-icu-74.2-1-any.pkg.tar.zst` [CI-Build Line 151](https://github.com/msys2/MINGW-packages/actions/runs/7753937970/job/21728218375?pr=19921#step:11:151)

- CLANG64
  - `error: failed retrieving file 'clangarm64.db' from mirror.msys2.org` [CI-Build Line 55](https://github.com/msys2/MINGW-packages/actions/runs/7753937970/job/21728218626?pr=19921#step:11:55)

**Comment by reneparis** [comment]
Seems for me, as the MinGW64 issue is related to by https://github.com/msys2/msys2-runtime/issues/208, caused by https://github.com/msys2/msys2-runtime/commit/9944652c41fb96f555d221865f4ed5d0c8b33514

**Comment by lazka** [comment]
This has been merged as part of #21290. thanks @mmuetzel !

**Pull request closed without merging**
