### PR TITLE
mingw-w64-duvatlas - update to latest version.

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by ognevny** [comment]
the same as https://github.com/msys2/MINGW-packages/pull/20548#issuecomment-2037798701

**Comment by ognevny** [comment]
this is not optdepend, it's needed to run the binary

**Comment by JPeterMugaas** [comment]
meshconvert is the binary executable.  That's what I thought you meant.

**Comment by JPeterMugaas** [comment]
I have moved "gcc-libs" to make it a run-time dependency.

**Comment by Biswa96** [comment]
> I have moved "gcc-libs" to make it a run-time dependency.

Please move it to depends list.

**Pull request merged**
