### PR TITLE
charls: new package

### PR DESCRIPTION
**Pull request by kmilos**
Lossless JPEG support: https://github.com/team-charls/charls

One of the optional dependencies of python-imagecodecs.

### CODE REVIEW

**Comment by Biswa96** [comment]
> One of the optional dependencies of python-imagecodecs.

FYI, as you are updating python-imagecodecs in another pull request you could add this dependency in that one. charls will build together with python-imagecodecs.

**Comment by kmilos** [comment]
Cool, I don't have to wait until charls gets published first?

**Comment by Biswa96** [comment]
> I don't have to wait until charls gets published first?

Actually you have to wait for python-imagecodecs but you don't have to wait twice.

**Comment by kmilos** [comment]
Thanks, commit moved over to #7656

**Pull request closed without merging**
