### PR TITLE
Python 2 purge - Round 1

### PR DESCRIPTION
**Pull request by lazka**
Some packages which don't have any reverse dependencies.

### CODE REVIEW

**Comment by lazka** [comment]
This should be ready now.

**Comment by lazka** [comment]
@Alexpux Any thoughts on this and Python 2 removal in general?

**Comment by Alexpux** [comment]
@lazka I'm ok with python2 removal. But dont increase pkgrel as removing doesnt need rebuild

**Comment by lazka** [comment]
OK, I'll try to remove the pkgrel bumps as much as possible. In some cases I had to fix URLs and dependencies as well..

**Comment by lazka** [comment]
On a second thought, not bumping pkgrel means the Python 3 package will all makedepend on Python 2 still and I can't track the progress :/

**Comment by Alexpux** [comment]
@lazka ok but i dont have time to rebuild this untill next year

**Comment by lazka** [comment]
ok, no problem

**Pull request merged**
