### PR TITLE
ollama: Update to 0.1.37

### PR DESCRIPTION
**Pull request by hmartinez82**
```
herna@SurfacePro9 CLANGARM64 /c/M_P/mingw-w64-ollama
$ ollama.exe serve
2024/05/12 06:47:18 routes.go:1006: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR:C:\\msys64\\clangarm64\\bin\\ollama_runners OLLAMA_TMPDIR:]"
time=2024-05-12T06:47:18.590-06:00 level=INFO source=images.go:704 msg="total blobs: 11"
time=2024-05-12T06:47:18.600-06:00 level=INFO source=images.go:711 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyModelHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-05-12T06:47:18.600-06:00 level=INFO source=routes.go:1052 msg="Listening on 127.0.0.1:11434 (version 0.1.37)"
time=2024-05-12T06:47:18.600-06:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu]"
time=2024-05-12T06:47:18.623-06:00 level=INFO source=types.go:71 msg="inference compute" id=0 library=cpu compute="" driver=0.0 name="" total="15.4 GiB" available="8.6 GiB"
[GIN] 2024/05/12 - 06:47:31 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/05/12 - 06:47:32 | 200 |      34.227ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/05/12 - 06:47:32 | 200 |       1.573ms |       127.0.0.1 | POST     "/api/show"
time=2024-05-12T06:47:32.644-06:00 level=INFO source=server.go:318 msg="starting llama server" cmd="C:\\msys64\\clangarm64\\bin\\ollama_runners\\cpu\\ollama_llama_server.exe --model C:\\Users\\herna\\.ollama\\models\\blobs\\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 --ctx-size 2048 --batch-size 512 --embedding --log-disable --parallel 1 --port 58532"
time=2024-05-12T06:47:32.661-06:00 level=INFO source=sched.go:333 msg="loaded runners" count=1
time=2024-05-12T06:47:32.661-06:00 level=INFO source=server.go:488 msg="waiting for llama runner to start responding"
time=2024-05-12T06:47:32.662-06:00 level=INFO source=server.go:524 msg="waiting for server to become available" status="llm server error"
INFO [main] build info | build=2770 commit="952d03d" tid="19176" timestamp=1715518052
INFO [main] system info | n_threads=4 n_threads_batch=-1 system_info="AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="19176" timestamp=1715518052 total_threads=8
INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="7" port="58532" tid="19176" timestamp=1715518052
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from C:\Users\herna\.ollama\models\blobs\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,61249]   = ["▁ t", "e r", "i n", "▁ a", "e n...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 4096
llm_load_print_meta: n_embd_v_gqa     = 4096
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.15 MiB
time=2024-05-12T06:47:32.929-06:00 level=INFO source=server.go:524 msg="waiting for server to become available" status="llm server loading model"
llm_load_tensors:        CPU buffer size =  3647.87 MiB
..................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.14 MiB
llama_new_context_with_model:        CPU compute buffer size =   164.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 1
INFO [main] model loaded | tid="19176" timestamp=1715518055
time=2024-05-12T06:47:35.194-06:00 level=INFO source=server.go:529 msg="llama runner started in 2.53 seconds"
[GIN] 2024/05/12 - 06:47:35 | 200 |    3.1648987s |       127.0.0.1 | POST     "/api/chat"
```
^_^
```
herna@SurfacePro9 CLANGARM64 ~
$ ollama run llama2
>>> What is the MSYS2 project?

MSYS2 is a free and open-source environment for Windows, Mac, and Linux that allows you to run Unix-like systems and
tools on your Windows machine. It provides a way to execute Unix commands, scripts, and programs directly from the
Windows command line, without the need to use a virtual machine or a separate Unix system.

MSYS2 is built using the Minimal SYSTEM (MSYS) framework, which allows developers to create their own customized
Unix-like environments. It provides a wide range of tools and utilities for software development, testing, and
deployment, including compilers, debuggers, version control systems, and more.

Some of the key features of MSYS2 include:

1. Cross-platform compatibility: MSYS2 can run on Windows, Mac, and Linux platforms, making it a versatile tool for
developers who work across multiple environments.
2. Unix-like environment: MSYS2 provides a Unix-like environment, complete with a Bash shell, GNU tools, and other
familiar commands and utilities.
3. Customizable: Developers can create their own customized environments using the MSYS2 builder tool, which allows them
to select the tools and utilities they need for their projects.
4. Integrated development environment (IDE): MSYS2 provides an integrated development environment (IDE) that includes
support for popular programming languages such as C, C++, Python, and Ruby.
5. Toolchain management: MSYS2 can manage toolchains, which are sets of tools and utilities required to build, test, and
deploy software projects.
6. Package management: MSYS2 has its own package manager that allows developers to easily install and manage software
packages and dependencies.
7. Cross-compilation: MSYS2 provides support for cross-compilation, which allows developers to compile code for
different architectures and operating systems.
8. Sandboxing: MSYS2 provides a sandbox environment that allows developers to run applications and scripts in isolation,
without affecting the host system.

Overall, MSYS2 is a powerful tool for software development, testing, and deployment, especially for developers who work
across multiple platforms and environments.
```

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you explain the reasons for the new patches? I feel like mingw-w64-ollama/0003-missing-wmain.patch is not required.

**Comment by hmartinez82** [comment]
I tried to build without that patch. llama_sever failed to link with missing `WinMain()` 

I then tried to compile with  `-municode`, but then several other executables failed to link with missing `wWinMain()` 😑

**Comment by ognevny** [comment]
> Could you explain the reasons for the new patches? I feel like mingw-w64-ollama/0003-missing-wmain.patch is not required.

I've faced the same issue when I tried to update the package. I couldn't fix it

**Comment by hmartinez82** [comment]
Ah ok, the name of the patch is misleading, it should be `missing-main` instead of `missing-wmain` :) I'll rename.

**Comment by hmartinez82** [comment]
I hope they eventually fix their game and get rid of those Powershell scripts . It's really brittle. 
A pure CMake based build system would be awesome!

**Comment by hmartinez82** [comment]
@ognevny I don't even know how the previous package was working. Was the other version a monolithic app? I had to add the runners to the package now for it to actually work. 

I only started using Ollama after 0.1.32 so I wouldn't know.

**Comment by ognevny** [comment]
> @ognevny I don't even know how the previous package was working. Was the other version a monolithic app? I had to add the runners to the package now for it to actually work. 
> 
> I only started using Ollama after 0.1.32 so I wouldn't know.

I don't know actually, sorry

**Pull request merged**
