### PR TITLE
new package: python-requests-unixsocket

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by lazka** [comment]
This packages wont work on Windows.

**Comment by Biswa96** [comment]
C:\Windows\System32\drivers\afunix.sys 🤔

**Comment by lazka** [comment]
Python doesn't support it at least.

**Comment by raedrizqie** [comment]
> This packages wont work on Windows. It's for a unix only functionality.

this is required by jupyter_server though :(

**Comment by lazka** [comment]
> this is required by jupyter_server though :(

ok, fair enough

**Comment by lazka** [comment]
I've created https://github.com/jupyter-server/jupyter_server/issues/598

**Comment by lazka** [comment]
upstream removed the dependency now

**Pull request merged**
