### PR TITLE
[libgme] Add static library

### PR DESCRIPTION
**Pull request by drfiemost**
Build and install the static gme library too.
Also added zlib dependency.

### CODE REVIEW

**Comment by Biswa96** [comment]
Should not that static library be automatically install with `make install` command instead of explicit `install` command?

**Comment by drfiemost** [comment]
> Should not that static library be automatically install with `make install` command instead of explicit `install` command?

But this would overwrite the already installed files . Maybe there's a make target to install only the library? Will check...

**Comment by Biswa96** [comment]
Technically yes but there is a trick. Repeat after me "shared after static" :) If `make install` command is run from shared folder after static folder it'll do the trick. See my very previous faudio pull request or any PKGBUILD file which builds both shared and static libraries separately.

**Comment by drfiemost** [comment]
Ok, will rework the change, thanks. Should I switch to Ninja while at it?

**Comment by Biswa96** [comment]
As you wish.

**Pull request merged**
