### PR TITLE
Spectra: new package

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by raedrizqie** [comment]
this package has wrong dir structure

**Comment by ognevnydemon** [comment]
> Could you please elaborate what is wrong with the dir structure of this package?

it's just called "spectra"

**Comment by raedrizqie** [comment]
without 'mingw-w64-' prefix for its dirname?

**Comment by mmuetzel** [comment]
> without 'mingw-w64-' prefix for its dirname?

Sorry. I still don't get the issue. Which file is installed in which directory? And where should it be installed instead?

Or does "dirname" mean something different for you? In that case, could you please explain what you mean?

**Comment by mmuetzel** [comment]
Ah. Now I see what you mean. The `PKGBUILD` is in the wrong directory in the repository.

That is true. 👍

**Comment by MehdiChinoune** [comment]
I think they mean cmake files, but cmake search in both lib and share directories for cmake config files.

**Comment by MehdiChinoune** [comment]
I think they mean cmake files, but cmake search in both lib and share directories for cmake config files.

**Comment by JPeterMugaas** [comment]
I think I see the problem.  It's directory the PKGBUILD was checked into.  It was named "spectra" instead of "mingw-w64-spectra".  Fixed in:  https://github.com/msys2/MINGW-packages/pull/19601

**Pull request merged**
