### PR TITLE
Python deps for Wind Waker Randomizer

### PR DESCRIPTION
**Pull request by Schala**

### CODE REVIEW

**Comment by 1480c1** [comment]
I think pinned git packages are preferred in this repo, but I could be wrong

**Comment by Schala** [comment]
Pinned?

**Comment by Biswa96** [comment]
Git packages are prohibited/discouraged untill there is no alternative way. If you really want git packages, add the sepcific commit, see mingw headers, crt etc. as examples.

**Comment by Schala** [comment]
Ahh alright. I mean I could put them in with the package I'm trying to commit, I guess.... pinned, that is

**Comment by lazka** [comment]
I added `0.r` to the version so we can easily change the version schema if upstream decides to tag a release or something.

**Pull request merged**
