### PR TITLE
groonga: rebuild for updating a dependency package

### PR DESCRIPTION
**Pull request by komainu8**
Currently, this package can install by pacman -S mingw-w64-x86_64-groonga.
However, we fail to load libgroonga-0.dll.
Because the version of libarrow.dll is updated to 1.0.0 from 0.17.1.
libgroonga-0.dll depends on libarrow.dll.

libgroonga-0.dll of current version is built for libarrow.dll version 0.17.1.
So, libgroonga-0.dll can not use libarrow.dll version 1.0.0.
Because there is no ABI compatibility between libarrow.dll version
0.17.1 and libarrow.dll version 1.0.0.

We need to rebuild the groonga package to use libarrow.dll version 1.0.0.

### CODE REVIEW

**Comment by Biswa96** [comment]
Just to follow the trend, would it be possible to add the pgp key to validate the source tarball? Here is the diff:

```diff
diff --git a/mingw-w64-groonga/PKGBUILD b/mingw-w64-groonga/PKGBUILD
index e379d21ed..1e4276158 100644
--- a/mingw-w64-groonga/PKGBUILD
+++ b/mingw-w64-groonga/PKGBUILD
@@ -10,7 +10,7 @@ arch=('any')
 url="http://groonga.org/"
 license=('LGPL2')
 options=('strip' 'staticlibs')
-source=("https://packages.groonga.org/source/${_realname}/${_realname}-${pkgver}.tar.gz")
+source=(https://packages.groonga.org/source/${_realname}/${_realname}-${pkgver}.tar.gz{,.asc})
 depends=("${MINGW_PACKAGE_PREFIX}-arrow"
          #"${MINGW_PACKAGE_PREFIX}-libevent"
          "${MINGW_PACKAGE_PREFIX}-luajit"
@@ -26,7 +26,9 @@ depends=("${MINGW_PACKAGE_PREFIX}-arrow"
          "${MINGW_PACKAGE_PREFIX}-zlib"
          "${MINGW_PACKAGE_PREFIX}-zstd")
 makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
-sha256sums=('e0d60ecbf441f86fe8a7e2448ec2e5b1e0a9f26405a71258abb2940d69c53213')
+sha256sums=('e0d60ecbf441f86fe8a7e2448ec2e5b1e0a9f26405a71258abb2940d69c53213'
+            'SKIP')
+validpgpkeys=('2701F317CFCCCB975CADE9C2624CF77434839225') # Groonga Key <packages@groonga.org>
 
 build() {
   [[ -d ${srcdir}/build-${CARCH} ]] && rm -rf ${srcdir}/build-${CARCH}
```

**Comment by komainu8** [comment]
@Biswa96 
Thank you for your comment.
I’m working on it.

**Comment by komainu8** [comment]
@Biswa96 
I've fixed it.
I added the pgp key to validate the source tarball.

**Comment by komainu8** [comment]
This modify has been committed by #6903.
So, I close this PR.

**Pull request closed without merging**
