### PR TITLE
Update lcov to 1.16

### PR DESCRIPTION
**Pull request by GitMensch**
restoring it, now using MINGW_PREFIX in perl interpreter

### CODE REVIEW

**Comment by GitMensch** [comment]
It is a bit bad that we need one package for each of MINGW64,MINGW32,MSYS2,... - not because there is anything specific in this package (but the perl shebang - but that could be replaced with "just perl"), but because of the port specific perl dependency.

**Comment by GitMensch** [comment]
Sight, rechecked with resulting version - the MinGW perl does not work without a patch:

~~~
lcov --capture --directory . --output-file coverage.info
Capturing coverage data from .
The command "D:/msys64/mingw64/bin/geninfo" is not found.
~~~

So we need to patch lcov to execute either "perl" or "bash" instead of the geninfo "command" (as its shebang is not understood by the Win32 native environment).

**Comment by GitMensch** [comment]
Tests working now, to make this work lcov had to be adjusted, which was published upstream with https://github.com/linux-test-project/lcov/pull/155 and then integrated into this PR.

**Comment by lazka** [comment]
Needs a rebase I guess?

re patch: puh, I'm not very keen on maintaining that patch downstream, but I guess we can always drop it again and fall back to msys lcov.

**Comment by GitMensch** [comment]
No rebase, but a "special merge" on the command line. I wanted to preserve the history so explicit branched the old version before delete.

I actually have hope that this patch will be included in the next lcov version and therefore not necessary then.

**Comment by lazka** [comment]
Does this mean you expect me to merge it manually? :)

**Comment by GitMensch** [comment]
I actually do not know how to tell git "yes, drop this deletion" and somehow I can't do it via browser.
If no one has an idea how this should be solved I can of course also only add the files "as new", but that felt wrong.

**Comment by GitMensch** [comment]
Thank you for taking care of this!

**Comment by lazka** [comment]
just wondering, have you considered https://gcovr.com/en/stable/index.html as an alternative?

**Comment by GitMensch** [comment]
I wasn't aware of gcovr - is there a package for it already?
Note: as lcov is integrated into exiting packages (it looks like the command line options of gcovr are not compatible so just swapping the "the to execute" wouldn't be enough) it would still be reasonable to have a working package in MinGW for lcov :-)

**Comment by lazka** [comment]
ok, makes sense.

**Pull request merged**
