### PR TITLE
fix memcpy-param-overlap in relocatable patch

### PR DESCRIPTION
**Pull request by nehaljwani**
Prefer memmove over memcpy for overlapping memory regions, otherwise it
triggers the address sanitizer with:

```
ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [x,y) and [a,b) overlap
```

cc @mingwandroid

### CODE REVIEW

**Comment by lazka** [comment]
increase pkgrel (and run updpkgsums)

**Comment by mingwandroid** [comment]
Thanks @nehaljwani! Happy New Year, I hope you are well?

We should fix this in other relocation patches too I think.

**Comment by nehaljwani** [comment]
Wish you a very happy new year too @mingwandroid !

I have updated the merge request to target all instances of the patch, but it seems that the CI is failing due to a missing build time dependency? I am not sure how to fix that:
```bash
$  makepkg-mingw --noconfirm --noprogressbar --skippgpcheck --nocheck --syncdeps --rmdeps --cleanbuild
==> Making package: mingw-w64-bison 3.0.4-3 (Sun, Jan 12, 2020  6:56:59 AM)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: mingw-w64-x86_64-m4
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> mingw-w64-x86_64-m4
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

**Comment by lazka** [comment]
mingw-w64-bison isn't in the repo and probably not buildable, so this should be fine.

**Comment by nehaljwani** [comment]
Isn't it the case that mingw-w64-x86_64-m4 is missing from the repos? Should I remove changes from mingw-w64-bison as it is not buildable at the moment?

**Comment by Alexpux** [comment]
@nehaljwani mingw versions of bison and m4 wads never released, so remove them from commit

**Pull request merged**
