### PR TITLE
crt: Remove full path reference

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by lazka** [comment]
What does this fix? (i.e. why is crt special here?)

**Comment by Biswa96** [comment]
When there is any full path reference in a executable I use `grep -air msys64 pkg` to look into binaries. But it also shows the path from crt libraries. With this change, the full paths from crt are removed and the binaries will contain only full path from their code only.

I was using this method in my setup to fix path relocation issues, thought it may help others also. This does not fix any issue directly.

**Comment by lazka** [comment]
ok, I guess.

I wonder if there is something we should do for all packages?

**Review by lazka — COMMENTED** [review]
ok, I guess.

I wonder if there is something we should do for all packages?

**Comment by Biswa96** [comment]
I am not sure if this will be useful for general use cases. Feel free to close.

**Comment by lazka** [comment]
If it helps you find relocation issues, then it's fine with me.

**Comment by lhmouse** [comment]
Do those paths exist only in symbols? Removing them might make debugging CRT code difficult, but it's also not so easy for MSVCRT or UCRT, so maybe it's fine.

**Comment by Biswa96** [comment]
> Do those paths exist only in symbols? 

Full paths exists in .o and .a files and it comes from `__FILE__` macro in crt code. There may be some trick in autotools to resolve that path to current directory only. But I can not recall it right now.

**Comment by Biswa96** [comment]
I am not sure if this will create any issue. So, I shall use this patch for my personal testing. Feel free to use or modify this change.

**Pull request closed without merging**
