### PR TITLE
Qt 5.14.2

### PR DESCRIPTION
**Pull request by Optiligence**
still building, not tested

### CODE REVIEW

**Comment by Alexpux** [comment]
I have my own local build now with more patches changes

**Comment by Optiligence** [comment]
looking forward to seeing it in the repos soon!

**Comment by Optiligence** [comment]
@Alexpux do you have an ETA?

**Comment by Alexpux** [comment]
@Optiligence I finish shared builds and now building static. When it done I will push changes and packages

**Comment by Optiligence** [comment]
ok, thank you very much

**Comment by Alexpux** [comment]
@Optiligence superseded by https://github.com/msys2/MINGW-packages/commit/a216d4577cb3cec820c7a93cf638811df4cbe0dd

**Pull request closed without merging**
