### PR TITLE
helix,ruff,zed: remove lto workarounds

### PR DESCRIPTION
**Pull request by mati865**

### CODE REVIEW

**Comment by ognevny** [comment]
did you test zed? it's broken in UCRT64 when build with ld: #22071

**Comment by ognevny** [comment]
also lto issue is now fixed in windows-gnu? can you share some links, please?

**Comment by ognevny** [comment]
> did you test zed? it's broken in UCRT64 when build with ld: #22071

it now works! thanks

**Comment by ognevny** [comment]
thanks again

**Comment by JakeIsMeh** [comment]
Unfortunately, this breaks Zed again for me. I had to downgrade to 0.164.2-1 for keyboard shortcuts to work again.

**Comment by ognevny** [comment]
sad :( will revert change ASAP

**Comment by ognevny** [comment]
please, wait until version 0.165.4-2 will be available in repo. that will take some time

**Comment by ognevny** [comment]
zed 0.165.4-2 is now available in repo. can you check whether issue is fixed?

**Comment by JakeIsMeh** [comment]
Keyboard shortcuts now work again. Thank you so much, and for the fast response!

**Pull request merged**
