### PR TITLE
luajit: Update to latest version and enable aarch64 builds

### PR DESCRIPTION
**Pull request by hmartinez82**
Lots of recent work gone into LuaJIT for AArch64, and for Windows  on ARM

### CODE REVIEW

**Comment by lazka** [comment]
Could we use the version scheme Arch uses?

**Comment by hmartinez82** [comment]
I just checked. Arch is using the same commit as this PR. So you mean using the same name pattern?

**Comment by hmartinez82** [comment]
@lazka Done 🚀

**Comment by lazka** [comment]
Thanks. It's mainly so our scripts notice new versions when comparing with Arch.

**Pull request merged**
