### PR TITLE
cppwinrt: Add package

### PR DESCRIPTION
**Pull request by Biswa96**
See https://github.com/mstorsjo/llvm-mingw/issues/307

### CODE REVIEW

**Comment by Biswa96** [comment]
This package can not be built with gcc yet. I think it would be better if upstream adds support for gcc toolchain first. Many headers need some modification.

@alvinhochun Please test the packages from clang environment. In my PC, the test fails with the following log

```
cppwinrt-2.0.221117.1/test/test/variadic_delegate.cpp:45: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```

<details><summary>Click here to see the backtrace of test.exe</summary>

```
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x7ff730913710: Access violation reading location 0x00000008
  * frame #0: 0x00007ff730913710 test.exe`(anonymous namespace)::Object::Callback()
    frame #1: 0x00007ff730914360 test.exe`winrt::impl::variadic_delegate<winrt::impl::delegate_base<void>::delegate_base<(anonymous namespace)::Object, void ((anonymous namespace)::Object::*)()>(winrt::weak_ref<(anonymous namespace)::Object>&&, void ((anonymous namespace)::Object::*)())::'lambda'(auto&&...), void>::invoke() + 80
    frame #2: 0x00007ff730911cb9 test.exe`C_A_T_C_H_T_E_S_T_0() + 3657
    frame #3: 0x00007ff7307993a3 test.exe`Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 499
    frame #4: 0x00007ff730798a7a test.exe`Catch::RunContext::runTest(Catch::TestCase const&) + 554
    frame #5: 0x00007ff73079e49c test.exe`Catch::Session::runInternal() + 3564
    frame #6: 0x00007ff73079d5fb test.exe`Catch::Session::run() + 139
    frame #7: 0x00007ff7307b514a test.exe`main + 106
    frame #8: 0x00007ff7307813d6 test.exe`__tmainCRTStartup at crtexe.c:329:15
    frame #9: 0x00007ff730781426 test.exe`mainCRTStartup at crtexe.c:206:9
    frame #10: 0x00007fff3f8474b4 kernel32.dll`BaseThreadInitThunk + 20
    frame #11: 0x00007fff40fe26a1 ntdll.dll`RtlUserThreadStart + 33
```

</details>

**Comment by alvinhochun** [comment]
Thanks, I have tracked down the crash and submitted a fix with https://github.com/microsoft/cppwinrt/pull/1232.

I will try to look at the gcc situation soon.

**Comment by Biswa96** [comment]
Thank you for the help. So, can I merge this?

**Comment by alvinhochun** [comment]
It may be better to wait until the fix has been merged and upstream has made a new release.

**Comment by Biswa96** [comment]
I can update it 😉

**Pull request merged**
