### PR TITLE
devcon-git: update and fix compilation

### PR DESCRIPTION
**Pull request by neheb**
binutils is needed to make.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
This need a specific commit hash. See mingw-w64-headers-git as example.

**Comment by neheb** [comment]
why not just use codeload?

**Comment by Biswa96** [comment]
What is codeload and how it is used here?

**Comment by 1480c1** [comment]
I think codeload was the zip file?

https://stackoverflow.com/questions/60188254/how-is-codeload-github-com-different-to-api-github-com

**Comment by Biswa96** [comment]
> why not just use codeload?

If it downloads latest default/main branch it will create a different binary/executable/package when upstream changes, instead of the specific commit (f0adcda0) in this pull request.

**Comment by neheb** [comment]
URL would be

```
https://codeload.github.com/microsoft/Windows-driver-samples/tar.gz/f0adcda012820b1cd44a8b3a1953baf478029738
```

for current master. replace the last section with any commit id.

**Comment by Biswa96** [comment]
Yeah, something like that. But I have rarely seen that type of URL format 😄

**Comment by Biswa96** [comment]
Generally, these guidelines are followed https://wiki.archlinux.org/title/VCS_package_guidelines

**Comment by neheb** [comment]
done.

**Pull request merged**
