### PR TITLE
ninja: Fix slow cursor update regression

### PR DESCRIPTION
**Pull request by orgads**
Reported in https://github.com/ninja-build/ninja/issues/2435

PR waiting for approval: https://github.com/ninja-build/ninja/pull/2437.

### CODE REVIEW

**Comment by orgads** [comment]
Wait with this, there should be 1.12.1 hotfix with this change.

**Comment by Biswa96** [comment]
ninja 1.12.1 tag has been released https://github.com/ninja-build/ninja/releases/tag/v1.12.1

**Comment by orgads** [comment]
Great! I'm AFK currently. You can update if you want. I'll push a PR tomorrow is you don't.

**Comment by Biswa96** [comment]
I have updated ninja package in 7a1d83e8aab7d3f6b1f102dfe6558a74d6c87609 commit. Thank you for reporting and fixing the issue upstream ❤️

**Pull request closed without merging**
