### PR TITLE
arm-none-eabi-gcc: update to 12.2.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
times out!

### CODE REVIEW

**Comment by lazka** [comment]
ok if I drop clang64 again? It's really annoying to build locally since it takes ages :(

**Comment by MehdiChinoune** [comment]
> ok if I drop clang64 again? It's really annoying to build locally since it takes ages :( so I want to limit the number of builds

Up to you, It's not something I need or someone asked for.

**Comment by MehdiChinoune** [comment]
Why not dropping MINGW32 instead?

**Comment by lazka** [comment]
ok, fine with me

**Comment by pfeerick** [comment]
Is this PR the reason there is no longer a `mingw-w64-i686-arm-none-eabi-gcc` package in the MSYS packages repo? Trying to figure out why our github builds have just started breaking when `pacman` is trying to grab dependencies for a 32bit build.

**Comment by lazka** [comment]
> Is this PR and [52a0f4e](https://github.com/msys2/MINGW-packages/commit/52a0f4e32b3d5f22defaa4b71c8bea90789e7a96) the reason there is no longer a `mingw-w64-i686-arm-none-eabi-gcc` package in the MSYS packages repo? Trying to figure out why our github builds have started breaking when `pacman` is trying to grab dependencies for a 32bit build.

yes. do you need it? I can add it back then.

**Comment by Biswa96** [comment]
Is it required to build a project with 32bit cross compiler? You are already cross compiling for arm-eabi.

**Comment by MehdiChinoune** [comment]
Your project has two workflow files https://github.com/EdgeTX/edgetx/blob/main/.github/workflows/win-cpn-32.yml and https://github.com/EdgeTX/edgetx/blob/main/.github/workflows/win_cpn-64.yml
Why the 32bit installs `arm-none-abi-gcc` while the 64bit doesn't!

**Comment by pfeerick** [comment]
>  Why the 32bit installs `arm-none-abi-gcc` while the 64bit doesn't!

Good question... the person who modified the win64 build to do a win32 build must have thought (incorrectly) that it was needed. 

> yes. do you really need it? I can add it back then.

No, was just looking for confirmation of the assumption before looking deeper after a nights sleep :) Removing this dependency (or rather, non-dependency) will resolve the issue.

Thank you both! :)

**Pull request merged**
