### PR TITLE
libxml2: Include compiled python bindings that ship with package.

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by lazka** [comment]
While correct in theory, this will lead to file conflicts on install since Python creates those files at runtime :/

**Comment by LABPBS** [comment]
That can be corrected with ``pacman -Syu --overwrite /${MINGW_PREFIX}/lib/python3.9/site-packages/__pycache__/\*``
reference: https://archlinux.org/news/libxml22912-6-update-may-require-manual-intervention/

**Comment by lazka** [comment]
Yeah, I'm worried users will still be confused.

As an alternative we could look through the repo for similar missing cases and handle it when we upgrade to Python 3.10, when these file names change anyway.

**Comment by lazka** [comment]
I've noted this here for the 3.10 update: https://github.com/msys2/MINGW-packages/issues/10515

Closing this until then.

**Pull request closed without merging**
