### PR TITLE
benchmark: update to 1.9.0

### PR DESCRIPTION
**Pull request by ikspress**
This PR propose to do

- Rephrase `PKGBUILD` following `mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-tarball.sh`
- Taken helper macros from `mingw-w64-gcc`
- Enable LTO for shared build
- Disable GoogleTest-specific tests

I disabled gtest due to clang would result a failure with some errors. See [My previous PR checks](https://github.com/msys2/MINGW-packages/actions/runs/9993285054/job/27620296484?pr=21446)

### CODE REVIEW

**Comment by ikspress** [comment]
nitpick and suggestion: Could I remove the comma in `pkgdesc`?

**Comment by ognevny** [comment]
> nitpick and suggestion: Could I remove the comma in `pkgdesc`?

why? it's correct

**Comment by ognevny** [comment]
the same thing can be found in `ruff` pkgdesc: "An extremely fast Python linter, written in Rust"

**Comment by ikspress** [comment]
> the same thing can be found in `ruff` pkgdesc: "An extremely fast Python linter, written in Rust"

Thank you, I got it.

**Pull request merged**
