### PR TITLE
python-llvmlite: update to 0.44.0rc2; python-numba: update to 0.61.0rc2

### PR DESCRIPTION
**Pull request by ognevny**
update numba due to ImportError raised because of numpy version. this requires llvmlite update

### CODE REVIEW

**Comment by ognevny** [comment]
https://github.com/numba/numba/issues/9838

**Comment by jeanpaul98728** [comment]
[https://www.mylittlepolynesia.com/](url) thanks

**Comment by ognevny** [comment]
the only way now is revert commit that pins numpy version to 2.1 (like Arch did)

**Comment by jeanpaul98728** [comment]
thanks

**Pull request merged**
