### PR TITLE
opencv: update to 4.5.4

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Before someone complains about AVX* stuff. Those options are enabled by default https://github.com/opencv/opencv/blob/4.5.4/cmake/OpenCVCompilerOptimizations.cmake#L310, I have just added that option to disable AVX512_SKX for CLANG64, As it failed for some reason.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
dll names changed -> Rebuild of many large packages!

**Comment by lazka** [comment]
do we need https://github.com/opencv/opencv/pull/20920 ?

**Comment by MehdiChinoune** [comment]
> do we need [opencv/opencv#20920](https://github.com/opencv/opencv/pull/20920) ?

I don't know, but I will backport it anyway.

**Comment by MehdiChinoune** [comment]
ceres-solver needs a rebuild, opencv is complaining:
```
Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.4.0) does not exactly match the version of Eigen Ceres was compiled with (3.3.9). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details
```

**Pull request closed without merging**
