### PR TITLE
gtk4: Add patch to fix issue #21959

### LINKED ISSUE #21959: mingw-w64-ucrt-x86_64-gtk4 4.16.1-1
### Description / Steps to reproduce the issue

I updated to GTK 4.16.1-1 on Windows 11 on 09/17/2024, and everything is flickering.

### Expected behavior

Que funcione...

### Actual behavior

...

https://github.com/user-attachments/assets/514483f7-6ce0-44bb-8f61-d25264aacac1

https://github.com/user-attachments/assets/4256fba9-27d6-4605-8f0a-83c2c84a9ea0

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by lb90**
Fixes #21959

### CODE REVIEW

**Comment by mmuetzel** [comment]
Not sure if this is a big deal. But usually contributors create branches for PRs in their fork of the repository instead of creating a branch in the main repository...

**Comment by lb90** [comment]
You're absolutely right. Sorry, sometimes I confuse workflows between different projects...

**Comment by lb90** [comment]
Ok, I have now opened another PR where things are done right: https://github.com/msys2/MINGW-packages/pull/22146. If this repo is configured to [delete branches automatically after merging PRs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches), you may prefer to just merge this. Otherwise close this PR and proceed with the new one

Sorry again for the mess! :/

**Comment by lazka** [comment]
No problem

**Pull request closed without merging**
