### PR TITLE
Rust: disable mingw packaging via configuration option

### PR DESCRIPTION
**Pull request by mati865**
One less downstream patch to maintain (once the fix reaches the release....).

Upstream PR: https://github.com/rust-lang/rust/pull/113725

### CODE REVIEW

**Comment by lazka** [comment]
thanks!

**Comment by lazka** [comment]
Looks like this broke things: https://github.com/msys2/msys2-tests/actions/runs/5766194049/job/15633657127

**Comment by lazka** [comment]
Reverted in 1717c9e1f31701 for now

**Comment by mati865** [comment]
Sorry, looks like we cannot get rid of `0008-disable-self-contained.patch`.
I must have tested intermediate version with `rm -f dest-rust/${MINGW_PREFIX}/lib/rustlib/$OSTYPE/lib/self-contained/*` commented out.

**Pull request merged**
