### PR TITLE
python-tldr: new package

### PR DESCRIPTION
**Pull request by ognevnydemon**
also adds python-shtab and python-shpinx-argparse as dependencies.

~~currently I receive an error while building tldr. I have no idea what's wrong~~ fixed

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
requirments.txt file is not included in PyPi tarball, consider using the one from GitHub.

**Comment by ognevnydemon** [comment]
> requirments.txt file is not included in PyPi tarball, consider using the one from GitHub.

thanks! now it can't find man page, but `make -C docs` from arch doesn't work...

**Comment by ognevnydemon** [comment]
> > requirments.txt file is not included in PyPi tarball, consider using the one from GitHub.
> 
> thanks! now it can't find man page, but `make -C docs` from arch doesn't work...

works, but now sphinxarg is now required. is there package in MSYS2 with it?

**Comment by ognevnydemon** [comment]
pushed all things. should work now

**Pull request merged**
