### PR TITLE
spdlog: Update to 1.8.2

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
The changes have been merged a long time ago, but why isn't the package updated in the package repository?

**Comment by lazka** [comment]
spdlog is waiting on cmake, which is waiting on qt5, which needs to be built manually because it takes longer than 6 hours to build.

**Comment by umarcor** [comment]
@lazka, is it a matter of some maintainer allocating 6h of their own workstation for doing it? Or are there any other issues which are preventing it?

**Comment by lazka** [comment]
the former (6 hours is per arch, so double that, but with more cores it's faster)

**Comment by umarcor** [comment]
Is there any chance for me to contribute those packages? I can allocate those 12h. Yet, I don't know how could I ensure that I did not modify the recipe.

**Pull request merged**
