### PR TITLE
qt6-multimedia: split out backend packages

### PR DESCRIPTION
**Pull request by fauxpark**
Per https://github.com/msys2/MINGW-packages/issues/17330#issuecomment-1566413954

### CODE REVIEW

**Comment by lazka** [comment]
I'm not sure if it's defined which of those two packages gets installed then, and we might end up in the old broken case without ffmpeg.

**Comment by fauxpark** [comment]
pacman on Arch appears to prompt the user when there are multiple candidates available for a dependency:
image

It is only single choice but users can still manually install other providers after the fact. A package can also depend on a specific provider (but I don't think this is necessary for MKVToolNix at least).

As I understand it, the "old broken case" is only due to the fact both backends are currently installed but `ffmpeg` was not. #17351 fixed this, but since the FFmpeg backend is what actually references `ffmpeg` the dependency has been moved accordingly. The WMF backend has no other dependencies as the DLLs it wants are obviously part of Windows.

**Comment by lazka** [comment]
Ahhh, ok, thanks

**Comment by fauxpark** [comment]
Sounds much better, updated. Wasn't sure how much you want to diverge from how Arch does things.

**Pull request merged**
