### PR TITLE
clang: Build with PGO

### PR DESCRIPTION
**Pull request by MehdiChinoune**
enabled only for clang64 and clangarm64

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Some other tests:

HarfBuzz (C++):
w/ PGO: 1m10.877s; 1m10.778s; 1m10.356s
w/o PGO: 1m27.521s; 1m27.103s; 1m28.288s
speedup~=-19%

GTK3 (C):
w/  PGO: 2m45.776s; 2m43.960s; 2m43.853s
w/o PGO: 3m7.433s; 3m9.390s; 3m13.088s
speedup~=-13%

**Comment by lazka** [comment]
I even get 20% for gtk and 28% for harfbuzz.

**Comment by MehdiChinoune** [comment]
> The 5h 44m build time is a bit on high end, let's hope future clang versions don't hit the limit :)

Future clang versions will be built by PGO'ed clang, It should take less time.

**Comment by lazka** [comment]
`time ninja`

**Pull request merged**
