### PR TITLE
More clang arm64 builds

### PR DESCRIPTION
**Pull request by hmartinez82**
Towards building GIMP for Windows on ARM

### CODE REVIEW

**Comment by Biswa96** [comment]
Did you make sure that all of the packages build for arm architecture?

**Comment by hmartinez82** [comment]
@Biswa96 yes. I ran the builds locally in a Surface Pro X, even ran the unit tests for packages that provide it :)

**Comment by Biswa96** [comment]
The gpg check of mpfr package works fine here. `"${MINGW_PACKAGE_PREFIX}-cc"` has to be added in makedepends of mpfr package. BTW, as these are small changes all commits can be put into one.

**Comment by hmartinez82** [comment]
Ok, I'll squash the commits

**Comment by hmartinez82** [comment]
I meant PGP , not GPG :)

**Comment by Biswa96** [comment]
Typo. That PGP check succeed in CI. See the output

```
  ==> Verifying source file signatures with gpg...
      mpfr-4.1.0.tar.xz ... Passed
```

**Comment by lazka** [comment]
re pgp, you can run `../.ci/fetch-validpgpkeys.sh` in a package dir to get the right keys. makepkg normally fetches them automatically, but only if the signature contains the full fingerprint.

**Comment by hmartinez82** [comment]
@kmilos  https://github.com/msys2/MINGW-packages/pull/12526 😀

**Comment by kmilos** [comment]
Amazing work, thank you very much!

And `gmic` was only an optional dependency (with a huge chain behind it indeed!), darktable would've worked without it with some minor features disabled...

**Pull request merged**
