### PR TITLE
ruff: update to 0.1.9

### PR DESCRIPTION
**Pull request by ognevnydemon**

### CODE REVIEW

**Comment by ognevnydemon** [comment]
added workaround of `--locked` issue as recommended by https://github.com/astral-sh/ruff/commit/a3e06e5a9d36bcc5708c3a720375594b7f19b2b4

**Comment by ognevnydemon** [comment]
> added workaround of `--locked` issue as recommended by https://github.com/astral-sh/ruff/commit/a3e06e5a9d36bcc5708c3a720375594b7f19b2b4

this didn't help... will try to patch later

**Comment by ognevnydemon** [comment]
done. should work now. also added completions

**Comment by ognevnydemon** [comment]
build issue reported https://github.com/astral-sh/ruff/issues/9245

**Comment by lazka** [comment]
I remember that old versions had similar issues, which prevented me to package it initially.

**Comment by ognevnydemon** [comment]
> I remember that old versions had similar issues, which prevented me to package it initially. No idea though.

okay, just hope this will be fixed in future release

**Comment by ognevnydemon** [comment]
there is new 0.1.11 release. I can't push it now

**Comment by ognevnydemon** [comment]
> build issue reported https://github.com/astral-sh/ruff/issues/9245

update: the issue is caused by build profile. if I understand right, we just need to patch Cargo.toml with
```patch
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -88,7 +88,7 @@
 rest_pat_in_fully_bound_structs = "warn"

 [profile.release]
-lto = "thin"
+lto = "fat"
# Note that we set these explicitly, and these values
# were chosen based on a trade-off between compile times
# and runtime performance[1].
```

**Comment by mati865** [comment]
Yup, but only for GCC based subsystems. Dunno about MINGW32, I cannot think of a reason why it wouldn't be affected but apparently it works.

**Comment by ognevnydemon** [comment]
> Yup, but only for GCC based ~~subsystems~~ envs. Dunno about MINGW32, I cannot think of a reason why it wouldn't be affected but apparently it works.

I disabled 32-bit

**Comment by MehdiChinoune** [comment]
I pushed 0.1.11

**Pull request closed without merging**
