### PR TITLE
python-tifffile: update to 2021.2.1

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
What does this fix for you?

**Comment by kmilos** [comment]
Just following the [Python packaging template](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-PKGBUILD-templates)...

This changes the path of the shebang line from e.g. `#!/mingw64/bin/python.exe` to the absolute path of the local install, I guess to make it work even outside MINGW terminal?

**Comment by Biswa96** [comment]
Can't we just make the shebang only python.exe?

**Comment by kmilos** [comment]
No idea...

I guess the idea for current Python packaging process is:

1. Replace the absolute path of the local build machine [here ](https://github.com/msys2/MINGW-packages/blob/435d06306e2ac65ed8ac028ccb2aabb6200efa65/mingw-w64-PKGBUILD-templates/PKGBUILD.setup-py-python-pkg#L98)with a relative one
2. Replace the relative one with the local install absolute one in the post_install() by including these scripts

There's inconsistencies in some of the python packages I have (relative paths, absolute build machine ptahs, even /usr/bin), here's the grep of my /mingw64/bin/ *-script.py:

```
$ grep "#!" *-script.py
chardetect-script.py:#!/usr/bin/env python.exe
cygdb-script.py:#!C:/msys64/mingw64/bin/python.exe
cython-script.py:#!C:/msys64/mingw64/bin/python.exe
cythonize-script.py:#!C:/msys64/mingw64/bin/python.exe
distro-script.py:#!/mingw64/bin/python.exe
doesitcache-script.py:#!C:/msys64/mingw64/bin/python.exe
easy_install-3.8-script.py:#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe
easy_install-script.py:#!C:/msys64/mingw64/bin/python.exe
f2py-script.py:#!/usr/bin/env python.exe
futurize-script.py:#!C:/msys64/mingw64/bin/python.exe
g-ir-annotation-tool-script.py:#!C:/msys64/mingw64/bin/python3.exe
g-ir-doc-tool-script.py:#!C:/msys64/mingw64/bin/python3.exe
g-ir-scanner-script.py:#!C:/msys64/mingw64/bin/python3.exe
gdbus-codegen-script.py:#!C:/msys64/mingw64/bin/python3.exe
glib-genmarshal-script.py:#!C:/msys64/mingw64/bin/python3.exe
glib-mkenums-script.py:#!C:/msys64/mingw64/bin/python3.exe
gtester-report-script.py:#!C:/msys64/mingw64/bin/python3.exe
imagecodecs-script.py:#!C:/msys64/mingw64/bin/python.exe
jsonschema-script.py:#!C:/msys64/mingw64/bin/python.exe
lsm2bin-script.py:#!/mingw64/bin/python.exe
mako-render-script.py:#!C:/msys64/mingw64/bin/python.exe
nosetests-3.8-script.py:#!C:/msys64/mingw64/bin/python.exe
nosetests-script.py:#!C:/msys64/mingw64/bin/python.exe
pasteurize-script.py:#!C:/msys64/mingw64/bin/python.exe
pip-script.py:#!C:/msys64/mingw64/bin/python.exe
pip3-script.py:#!C:/msys64/mingw64/bin/python.exe
pip3.8-script.py:#!C:/msys64/mingw64/bin/python.exe
tiffcomment-script.py:#!/mingw64/bin/python.exe
tifffile-script.py:#!/mingw64/bin/python.exe
```

**Comment by naveen521kk** [comment]
I noticed this in many places. I think the shebang should be the full path `C:/msys64/mingw64/bin/python.exe` and this PR does it for the required package.
Setuptools launchers were designed to call the scripts with absolute paths (not Cygwin path though). So the best would be to add this post-install script to python packages which scripts.
> Can't we just make the shebang only python.exe?
`#!python.exe` will work but not expected to always. So, it is better to use absolute paths.

**Comment by lazka** [comment]
Ideally we don't use absolute paths anywhere..

**Comment by naveen521kk** [comment]
> Ideally we don't use absolute paths anywhere..

This is how it is in python scripts... Or we should patch setuptools' launcher to support Cygwin paths...

**Comment by naveen521kk** [comment]
@kmilos I think instead of post-install scripts you can do something as done in https://github.com/msys2/MINGW-packages/pull/7843
I and @lazka had discussed this on [*Discord*](https://discord.com/channels/792780131906617355/794220101741838401/804735506323210280) and finally came to an agreement that there needed to be any shebangs at all and we slowly remove them.

**Comment by kmilos** [comment]
Ok, I'll take a look, thanks. Might wait until the next real version update of tifffile, there's no pressing issue.

Would be great if you guys updated the Python packaging templates (and any other guidelines) in the meantime.

**Pull request merged**
