### PR TITLE
update: assimp to 5.2.1, some qt5-* packages and some qt6-* packages to 6.2.3

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I think mingw-w64-magnum-plugins also needs a rebuild for the assimp update, based on my prior checking in https://github.com/msys2/MINGW-packages/pull/10783#issuecomment-1043446522

**Comment by MehdiChinoune** [comment]
qt5-3d:
```
 Qt 3D:
   Assimp ................................. yes
   System Assimp .......................... yes
```
qt5-quick3d
```
 QtQuick3D:
   Assimp ................................. yes
   System Assimp .......................... yes
```
qt6-3d
```
 Qt 3D:
   Assimp ................................. yes
   System Assimp .......................... yes
```
qt6-quick3d
```
 QtQuick3D:
   Assimp ................................. yes
   System Assimp .......................... yes
```

**Comment by MehdiChinoune** [comment]
It succeeds on my side https://github.com/MehdiChinoune/MINGW-packages/actions/runs/1868830668

**Comment by lazka** [comment]
Thanks!

**Comment by MehdiChinoune** [comment]
Thanks, Finally!

**Pull request merged**
