### PR TITLE
New package: sol2

### PR DESCRIPTION
**Pull request by ImperatorS79**

### CODE REVIEW

**Comment by lazka** [comment]
Same issue as with the other package. Why are you using "MinGW Makefiles"?

**Comment by ImperatorS79** [comment]
I just used what I was used to use ^^. I will have a look right now.

**Comment by lazka** [comment]
We use mingw32-make only in a handful of packages, so my guess is it likely not the right thing to use :)

**Comment by ImperatorS79** [comment]
Comments applied.

**Comment by ImperatorS79** [comment]
@lazka I think everything is ready now.

**Pull request merged**
