### PR TITLE
mingw-w64-arm-none-eabi-gcc: update gcc version and enable Ada support

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Ping @fauxpark @nanodude

**Comment by Fabien-Chouteau** [comment]
I don't see any build error in the logs, only:
```
2020-12-17T23:11:56.6041589Z Terminate batch job (Y/N)? 
2020-12-17T23:11:56.6096221Z ^C
2020-12-17T23:11:56.7122188Z ##[error]The operation was canceled.
2020-12-17T23:11:56.8902605Z Post job cleanup.
```
Is it the build taking too long (~5h)?

**Comment by fauxpark** [comment]
Yes, GitHub Actions only gives you 6 hours per job: https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration

Unfortunately, it has to be built manually.

**Comment by Fabien-Chouteau** [comment]
We should find a way to split the builds, for instance libstdc++ in a different package.

**Comment by Fabien-Chouteau** [comment]
So how can we proceed here?

**Comment by lazka** [comment]
If I merge this as is it means you will have to expect some delays with repo updates since it needs to be built manually.

OK to merge?

**Comment by Fabien-Chouteau** [comment]
Ok for me.

**Comment by lazka** [comment]
Sorry for forgetting this, feel free to re-ping me in future PRs etc..

**Comment by umarcor** [comment]
@fauxpark said in #7976:

> Apparently there are still issues with LTO - trying to compile QMK causes this warning at linking stage:

**Review by umarcor — APPROVED** [review]

**Comment by Fabien-Chouteau** [comment]
Thank you @lazka

**Pull request merged**
