### PR TITLE
librsvg: rebuild and fix build with newer rust

### PR DESCRIPTION
**Pull request by lazka**
rust 1.82.0 doesn't like the target temp file being open while writing to it

### CODE REVIEW

**Comment by ognevny** [comment]
can such change be upstreamed?

**Comment by lazka** [comment]
yes, see the linked issue

**Comment by ognevny** [comment]
it isn't reproducible on my arch machine though

**Comment by lazka** [comment]
It's about replacing a file that is opened by another process, so a Windows specific issue.

**Pull request merged**
