### PR TITLE
[WIP] wxpython: Upgrade to 4.1.2 Alpha 1 Dev 5330

### PR DESCRIPTION
**Pull request by stahta01**
And, upgrade wxWidgets to 3.1.6.

See also #11631 which just upgrade wxWidgets

I am not sure that 401-Fix-clang-compiler-problem.patch is correct way to get clang to stop complaining about the sip generated code. It said something about taking address of a local variable.
`return &self->GetDisabledBitmap();`

Tim S

### CODE REVIEW

**Comment by jeremyd2019** [comment]
> I am not sure that 401-Fix-clang-compiler-problem.patch is correct way to get clang to stop complaining about the sip generated code. It said something about taking address of a local variable. `return &self->GetDisabledBitmap();`

I would suggest that upstream should have updated `GetDisabledBitmap` as they did `GetBitmap`:
https://github.com/wxWidgets/Phoenix/commit/aa1ef7bd75412191e7912855abdfdc1af1c70335#diff-99a364fa919505608877ea651dbec9464feb164862533d84a2fb35c0a68bc864

**Comment by stahta01** [comment]
> > I am not sure that 401-Fix-clang-compiler-problem.patch is correct way to get clang to stop complaining about the sip generated code. It said something about taking address of a local variable. `return &self->GetDisabledBitmap();`
> 
> I would suggest that upstream should have updated `GetDisabledBitmap` like they did `GetBitmap`: [wxWidgets/Phoenix@aa1ef7b#diff-99a364fa919505608877ea651dbec9464feb164862533d84a2fb35c0a68bc864](https://github.com/wxWidgets/Phoenix/commit/aa1ef7bd75412191e7912855abdfdc1af1c70335#diff-99a364fa919505608877ea651dbec9464feb164862533d84a2fb35c0a68bc864)

That does seem to be a possible solution; or, at least better than my current patch file.
Looks like I might need to figure out how to test the change.
Or I could just post it as a possible fix upstream. But, not sure whether I should do both or one or the other.

Tim S.

**Comment by stahta01** [comment]
I am working to report the issue clang compiler found to the wxPython git issue; waiting to I get a build build error.

Tim S.

**Comment by stahta01** [comment]
Changed to "Work In Progress" because I found a few wxWidgets 3.1 changes I wish to do.

**Comment by stahta01** [comment]
A new 4.1.2 Alpha snapshot was just released; so, I am closing this PR to do one with today's snapshot.

**Pull request closed without merging**
