### PR TITLE
scour: add package

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
Required for Inkscape project. /cc @Ede123

**Comment by lazka** [comment]
The arch package is just named "scour". Should this be too?

**Comment by Biswa96** [comment]
I know. I first thought about it but can't get to any conclusion.

1. My left brain said to use 'mingw-w64-python-scour' as it makes sense, fits with other packages and it is a python package.
2. My right brain said to use 'mingw-w64-scour' so that it syncs with the package sync/update ritual with ArchLinux.

Let's have a vote 🗳️

**Comment by lazka** [comment]
Or @Ede123 decides :)

**Comment by Ede123** [comment]
What's more common (with or without prefix)?

I see debian splits "python-scour" (module) and "scour" (executables), but as arch doesn't seem do that and I understand we'd like to be on par with Arch (which I think we usually aim for) just "scour" would probably be the way to go.

I'm fine with both, though, if anybody else feels strongly about one or the other option.

**Comment by Ede123** [comment]
What's more common (with or without prefix)?

I see debian splits "python-scour" (module) and "scour" (executables), but as arch doesn't seem do that and I understand we'd like to be on par with Arch (which I think we usually aim for) just "scour" would probably be the way to go.

I'm fine with both, though, if anybody else feels strongly about one or the other option.

**Comment by Ede123** [comment]
What's more common (with or without prefix)?

I see debian splits "python-scour" (module) and "scour" (executables), but as arch doesn't seem do that and I understand we'd like to be on par with Arch (which I think we usually aim for) just "scour" would probably be the way to go.

I'm fine with both, though, if anybody else feels strongly about one or the other option.

**Comment by Ede123** [comment]
What's more common (with or without prefix)?

I see debian splits "python-scour" (module) and "scour" (executables), but as arch doesn't seem do that and I understand we'd like to be on par with Arch (which I think we usually aim for) just "scour" would probably be the way to go.

I'm fine with both, though, if anybody else feels strongly about one or the other option.

**Comment by Ede123** [comment]
What's more common (with or without prefix)?

I see debian splits "python-scour" (module) and "scour" (executables), but as arch doesn't seem do that and I understand we'd like to be on par with Arch (which I think we usually aim for) just "scour" would probably be the way to go.

I'm fine with both, though, if anybody else feels strongly about one or the other option.

**Comment by Ede123** [comment]
What's more common (with or without prefix)?

I see debian splits "python-scour" (module) and "scour" (executables), but as arch doesn't seem do that and I understand we'd like to be on par with Arch (which I think we usually aim for) just "scour" would probably be the way to go.

I'm fine with both, though, if anybody else feels strongly about one or the other option.

**Comment by Biswa96** [comment]
OK, I will change this to mingw-w64-scour.

**Pull request merged**
