### PR TITLE
Update mlpack to 3.4.2

### PR DESCRIPTION
**Pull request by ImperatorS79**
On windows main shared lib builds but linking otther lib fails, so I switched to static lib (as it is recommended by mlpack on windows).

### CODE REVIEW

**Comment by Biswa96** [comment]
> On windows shared lib fails

Any explanation of this issue?

**Comment by ImperatorS79** [comment]
So the main mlpack dll builds, but then after there are linking errors for all ohter librairies.

I came across this in the mlpack repo https://github.com/mlpack/mlpack/issues/1611.

**Comment by ImperatorS79** [comment]
Any idea how to solve this ? @Biswa96 
```
D:/a/_temp/msys/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/mlpack_kfn.dir/kfn_main.cpp.obj: section .rdata$_ZTSSt5tupleIJPN6mlpack8neighbor7NSModelINS1_10FurthestNSEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE: string table overflow at offset 10000014
{standard input}: Assembler messages:
{standard input}: Fatal error: can't close CMakeFiles/mlpack_kfn.dir/kfn_main.cpp.obj: file too big
make[2]: *** [src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_kfn.dir/build.make:82: src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_kfn.dir/kfn_main.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:9835: src/mlpack/methods/neighbor_search/CMakeFiles/mlpack_kfn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by mattn** [comment]
Any update on this?

**Comment by ImperatorS79** [comment]
Waiting for mlpack to merge the necessary updates such that it does compile in x86_64.

**Comment by ImperatorS79** [comment]
Clang builds do not fail despite not founding julia.

**Comment by lazka** [comment]
Closing in favor of #9972

**Pull request closed without merging**
