### PR TITLE
mlpack: update to 3.4.2

### LINKED ISSUE #6715: [mlpack] Build is broken
```
 In file included from D:/a/_temp/msys/msys64/mingw64/include/armadillo:54,
                 from D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/mlpack-mlpack-3.1.1/src/mlpack/core/arma_extend/arma_extend.hpp:49,
                 from D:\a\MINGW-packages\MINGW-packages\mingw-w64-mlpack\src\mlpack-mlpack-3.1.1\src\mlpack\prereqs.hpp:108,
                 from D:\a\MINGW-packages\MINGW-packages\mingw-w64-mlpack\src\build-x86_64\src\mlpack\cotire\mlpack_CXX_prefix.cxx:4,
                 from D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/build-x86_64/src/mlpack/cotire/mlpack_CXX_prefix.hxx:4:
D:/a/_temp/msys/msys64/mingw64/include/armadillo_bits/compiler_setup.hpp:79:30: fatal error: D:/a/_temp/msys/msys64/mingw64/include/hdf5.h: No such file or directory
   79 | #define ARMA_INCFILE_WRAP(x) <x>
      |                              ^
compilation terminated.
CMake Error at D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/mlpack-mlpack-3.1.1/CMake/cotire.cmake:1885 (message):
  cotire: error 1 precompiling
  D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/build-x86_64/src/mlpack/cotire/mlpack_CXX_prefix.hxx.
Call Stack (most recent call first):
  D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/mlpack-mlpack-3.1.1/CMake/cotire.cmake:3558 (cotire_precompile_prefix_header)
```

Maybe just a missing dep?

### PR DESCRIPTION
**Pull request by MehdiChinoune**
~No shared library.~
Fixes #6715

### CODE REVIEW

**Comment by podsvirov** [comment]
@MehdiChinoune, please review #9975

**Comment by MehdiChinoune** [comment]
I was able to restore the shared library by passing `-Wl,--export-all-symbols` to the linker as suggested on https://github.com/msys2/MINGW-packages/issues/6715#issuecomment-668554259

Fixes #6715

**Comment by ImperatorS79** [comment]
That's great !

**Comment by rcurtin** [comment]
@MehdiChinoune nice fix!  Should we upstream your patch to the CMake sources?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune nice fix! Should we upstream your patch to the CMake sources?

If you wish/could.

**Pull request merged**
