### PR TITLE
update to lua-5.4.2

### PR DESCRIPTION
**Pull request by Testsr**
this package is to update lua to the latest version

### CODE REVIEW

**Comment by Testsr** [comment]
I saw a duplicate, so I am closing this pull request

**Comment by Testsr** [comment]
That other pull request is not going anywhere.

**Comment by lazka** [comment]
The other PR did the right thing of rebuilding all dependent packages though ;) Otherwise this update will break all packages linking to lua.

**Comment by lazka** [comment]
Closing in favor of #7984

**Pull request closed without merging**
