### PR TITLE
python-pygame: update to 2.5.2

### PR DESCRIPTION
**Pull request by JojoFR1**
It's a simple bug fixes releases ([official patchnotes](https://github.com/pygame/pygame/releases/tag/2.5.2))

### CODE REVIEW

**Comment by JojoFR1** [comment]
Once again it failed, no idea why (I would fix it if I knew)

**Comment by Biswa96** [comment]
> Once again it failed, no idea why (I would fix it if I knew)

Hint: See the CI log. It says the build process need something, got it?

**Comment by JojoFR1** [comment]
Oh it needs cython, I will see later I can't right now

**Comment by JojoFR1** [comment]
Oh you did it, thanks (I was going to push).

Sorry for the inconvenience

**Pull request merged**
