### PR TITLE
angleproject: update to 2.1.r20724.b26b01a2

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by lazka** [comment]
Failed on arm, sadly:

```
2023-03-25T22:25:01.1804810Z clang++: warning: argument unused during compilation: '-msse3' [-Wunused-command-line-argument]
2023-03-25T22:25:01.1805559Z In file included from ../../src/common/frame_capture_utils_autogen.cpp:11:
2023-03-25T22:25:01.1806243Z In file included from ../../src/common/frame_capture_utils_autogen.h:14:
2023-03-25T22:25:01.1806919Z In file included from ../../src/common/PackedEnums.h:12:
2023-03-25T22:25:01.1807709Z In file included from ../../src/common/PackedEGLEnums_autogen.h:15:
2023-03-25T22:25:01.1808159Z 
2023-03-25T22:25:01.1808478Z In file included from ../../include/EGL/egl.h:20:
2023-03-25T22:25:01.1808812Z 
2023-03-25T22:25:01.1809108Z In file included from ../../include/EGL/eglplatform.h:18:
2023-03-25T22:25:01.1809454Z 
2023-03-25T22:25:01.1809752Z In file included from ../../include/KHR/khrplatform.h:149:
2023-03-25T22:25:01.1810097Z 
2023-03-25T22:25:01.1810418Z In file included from C:/msys64/clangarm64/bin/../include/c++/v1/stdint.h:106:
2023-03-25T22:25:01.1810786Z 
2023-03-25T22:25:01.1811750Z C:/msys64/clangarm64/bin/../include/c++/v1/__config:261:14: fatal error: 'features.h' file not found
2023-03-25T22:25:01.1812297Z 
2023-03-25T22:25:01.1812640Z #    include <features.h>
2023-03-25T22:25:01.1813042Z 
2023-03-25T22:25:01.1813352Z              ^~~~~~~~~~~~
2023-03-25T22:25:01.1813709Z 
2023-03-25T22:25:01.1813972Z 1 error generated.
2023-03-25T22:25:01.1814512Z 
2023-03-25T22:25:01.1814927Z [5/777] CXX obj/angle_capture_common/frame_capture_utils.o
```

which is weird because that part is

```
#  if defined(__linux__)
#    include <features.h>
```

**Comment by lazka** [comment]
ah, it's passing `--target=aarch64-linux-gnu`:

```
clang++ -MMD -MF obj/angle_capture_common/frame_capture_utils_autogen.o.d -DUSE_AURA=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCOMPONENT_BUILD -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_FE -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DANGLE_VMA_VERSION=2003000 -DANGLE_IS_WIN -DANGLE_ENABLE_SHARE_CONTEXT_LOCK=1 -DANGLE_OUTSIDE_WEBKIT -I../../include -I../../src -I../../src/common/base -I../../src/common/third_party/xxhash -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-attributes -Wno-format -Wno-parentheses -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-nonportable-include-path -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing -fstack-protector -funwind-tables -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers -msse3 --target=aarch64-linux-gnu -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -gdwarf-4 -g2 -gdwarf-aranges -Xclang -fuse-ctor-homing -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -Wbad-function-cast -Wconditional-uninitialized -Wextra-semi-stmt -Wfloat-conversion -Winconsistent-missing-destructor-override -Wmissing-field-initializers -Wnewline-eof -Wnon-virtual-dtor -Wredundant-parens -Wreturn-std-move -Wshadow -Wshadow-field -Wtautological-type-limit-compare -Wundefined-reinterpret-cast -Wunneeded-internal-declaration -Wunused-but-set-variable -Wsuggest-destructor-override -Wsuggest-override -Wparentheses -Wrange-loop-analysis -Wstrict-prototypes -Wunreachable-code-aggressive -Wshorten-64-to-32 -std=c++20 -Wno-trigraphs -fno-exceptions -fno-rtti -c ../../src/common/frame_capture_utils_autogen.cpp -o obj/angle_capture_common/frame_capture_utils_autogen.o
```

**Comment by raedrizqie** [comment]
hmm.. maybe we must add `is_win=true` when configuring the build process?

@Biswa96 could you help me test this?

**Comment by lazka** [comment]
I'd guess it's https://chromium.googlesource.com/chromium/src/build.git/+/refs/heads/main/config/compiler/BUILD.gn#1014

**Comment by lazka** [comment]
> -> [e40652d](https://github.com/msys2/MINGW-packages/commit/e40652ddaf92e01c1bbe3d9a51ff6a44e65b4aac)

worked :)

**Pull request merged**
