### PR TITLE
Add package Scintilla 4.4.4(GTK3)

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by taozuhong** [comment]
@lazka could this package can merge into repo?

**Comment by lazka** [comment]
Once CI passes, sure.

**Comment by Biswa96** [comment]
Some queries:
1. Wouldn't the libraries be with .DLL extension instead of .SO?
2. The prefix is hard coded in pkgconfig file. Shouldn't it be `${prefix}`?

**Comment by Biswa96** [comment]
Some queries:
1. Wouldn't the libraries be with .DLL extension instead of .SO?
2. The prefix is hard coded in pkgconfig file. It should be `/mingw32` for i686 packages.
3. `${MINGW_PREFIX}` already has a forwardslash in the value. So, the forwardslashes can be removed from commands.

**Comment by taozuhong** [comment]
@Biswa96 Could you give me some tips about make scintilla.pc more portable?

**Comment by taozuhong** [comment]
@Biswa96 done，thank for your reviewing and advice.

**Comment by fauxpark** [comment]
Just a note that scintilla.pc somehow has Windows line endings and is showing up as modified in git now.

**Pull request merged**
