### PR TITLE
svt-av1: update to 1.3.0

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
Does this require any packages to be rebuilt?

**Comment by kmilos** [comment]
Hm, possibly, I just saw the ABI version bump here: https://gitlab.com/AOMediaCodec/SVT-AV1/-/compare/v1.2.1...v1.3.0?from_project_id=24327400&page=10&straight=false#fea033795c54df35effffa170a7b6e52541bfeea

**Comment by lazka** [comment]
> Edit: Seems to be only one addition to the public struct, so might be safe to ignore?

that seems like an ABI break to me.

**Comment by kmilos** [comment]
Ok, bumping deps...

**Pull request merged**
