### PR TITLE
arrow: Disable --version-script for clang

### PR DESCRIPTION
**Pull request by Biswa96**
@kou

### CODE REVIEW

**Comment by kou** [comment]
Could you share error message without this patch?
I'll use it when I push a fix for this case to upstream.

**Comment by kou** [comment]
https://pipelines.actions.githubusercontent.com/jz302Jp6n2Ls4LxFeVGslDhpd6yjvpcP6IkHkrD1oqOYWum4cl/_apis/pipelines/1/runs/4231/signedlogcontent/16?urlExpires=2021-08-01T01%3A23%3A35.6332210Z&urlSigningMethod=HMACV1&urlSignature=OvQDjf1gxzpYuqf3dWw2o%2BU%2FqEbSDISzR6zxaO1fRQM%3D

```text
2021-07-31T07:34:52.7307964Z FAILED: release/libarrow.dll release/libarrow.dll.a 
2021-07-31T07:34:52.8385417Z cmd.exe /C "cd . && D:\a\_temp\msys\msys64\clang64\bin\c++.exe -Qunused-arguments -fcolor-diagnostics -O3 -DNDEBUG  -Wa,-mbig-obj -Wall -Wno-unknown-warning-option -Wno-pass-failed -mxsave -msse4.2  -O3 -DNDEBUG  -Wl,--version-script=C:/_/M/mingw-w64-arrow/src/apache-arrow-5.0.0/cpp/src/arrow/symbols.map -shared -o release\libarrow.dll -Wl,--out-implib,release\libarrow.dll.a -Wl,--major-image-version,500,--minor-image-version,0 src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_21_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_20_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_19_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_18_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_17_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_16_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_15_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_14_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_13_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_12_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_11_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_10_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_9_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_8_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_7_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_6_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_5_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_4_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_3_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_2_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_1_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_0_cxx.cxx.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_1_c.c.obj src/arrow/CMakeFiles/arrow_shared.dir/Unity/unity_0_c.c.obj src/arrow/CMakeFiles/arrow_shared.dir/util/io_util.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/vendored/datetime/tz.cpp.obj src/arrow/CMakeFiles/arrow_shared.dir/util/bpacking_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/compute/kernels/aggregate_basic_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/compute/exec/key_hash_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/compute/exec/key_map_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/compute/exec/key_compare_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/compute/exec/key_encode_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/compute/exec/util_avx2.cc.obj src/arrow/CMakeFiles/arrow_shared.dir/filesystem/s3fs.cc.obj  D:/a/_temp/msys/msys64/clang64/lib/libcrypto.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libssl.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbrotlienc.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbrotlidec.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbrotlicommon.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libutf8proc.dll.a  -lws2_32  D:/a/_temp/msys/msys64/clang64/lib/libcrypto.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libssl.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbrotlienc.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbrotlidec.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbrotlicommon.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libbz2.dll.a  D:/a/_temp/msys/msys64/clang64/lib/liblz4.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libsnappy.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libz.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libzstd.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-config.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-transfer.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-identity-management.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-cognito-identity.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-sts.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-s3.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-cpp-sdk-core.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libutf8proc.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libre2.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libcrypto.dll.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-c-event-stream.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-c-io.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-c-cal.a  -lSecur32  -lCrypt32  -lShlwapi  D:/a/_temp/msys/msys64/clang64/lib/libaws-checksums.a  D:/a/_temp/msys/msys64/clang64/lib/libaws-c-common.a  -lBCrypt  -lKernel32  -lWs2_32  -pthread  -lunwind  -lunwind  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
2021-07-31T07:34:52.9198909Z lld: error: unknown argument: --version-script=C:/_/M/mingw-w64-arrow/src/apache-arrow-5.0.0/cpp/src/arrow/symbols.map
```

**Comment by kou** [comment]
Does https://github.com/apache/arrow/pull/10848.patch work?

**Comment by Biswa96** [comment]
Yes, it works. It is technically same thing as my hack. I have replaced your patch with mine.

**Review by kou — APPROVED** [review]
Thanks!

**Comment by mati865** [comment]
This patch might have slight negative effect on GNU based Windows toolchains because more symbols would be exported now. It might be better to use `CheckLinkerFlag` from CMake for this purpose.

**Comment by Biswa96** [comment]
> It might be better to use CheckLinkerFlag from CMake for this purpose.

That's what the patch file does.

**Comment by mati865** [comment]
Ah, I looked at this part:
```
+  if(APPLE OR WIN32)
+    set(CXX_LINKER_SUPPORTS_VERSION_SCRIPT FALSE)
+  else()
+    set(CXX_LINKER_SUPPORTS_VERSION_SCRIPT TRUE)
+  endif()
```
and haven't noticed the check below. It's all good then.

**Pull request merged**
