### PR TITLE
mingw-w64-mesa: Update to 20.2.2

### PR DESCRIPTION
**Pull request by pal1000**
Improvements
- Correct deprecation warnings with llvm, shared-glapi, gles1 and gles2 build options during build configuration
- Link LLVM dynamically.

Build fails on CI for now, but it should work as soon as LLVM 11.0.0-4 appears on repo.

### CODE REVIEW

**Comment by lazka** [comment]
ok to merge?

**Comment by pal1000** [comment]
I still need to add fallback code for when llvm-config is busted with dynamically linked LLVM.

**Comment by lazka** [comment]
ok, ping me if I should merge.

**Comment by pal1000** [comment]
@lazka I am done.

**Pull request merged**
