### PR TITLE
mpv: switch to yt-dlp

### PR DESCRIPTION
**Pull request by lazka**
youtube-dl is basically dead

### CODE REVIEW

**Comment by Biswa96** [comment]
> youtube-dl is basically dead

Not dead _yet_ - still in development 😞

**Comment by lazka** [comment]
Would you prefer to keep it?

**Comment by Biswa96** [comment]
>Would you prefer to keep it?

Not sure. Feel free to remove it.

**Comment by lazka** [comment]
My motivation was that Arch dropped it too btw

**Pull request merged**
