### PR TITLE
angle: Enable clangarm64

### PR DESCRIPTION
**Pull request by Biswa96**
* Remove patch for adding D3D11_CLIP_OR_CULL_DISTANCE_COUNT symbol.
* Define ANGLE_PLATFORM_WINDOWS instead of _WIN32.
* Add arm64 target for mingw toolchain gn file.
* Use -msse3 flag for x86 and x86_64 only.

### CODE REVIEW

**Comment by Biswa96** [comment]
@jeremyd2019 Would you like to check if angle and libepoxy build with this change? I have only cross compiled it.

**Comment by jeremyd2019** [comment]
```
==> Starting build()...
[7888:0109/195639.563:FATAL:args.cc(379)] Check failed: false. OS architecture not handled. ()
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Biswa96** [comment]
I have added the arm64 platform in gn. But the ninja command goes in an endless loop. After Ctrl+C, it shows some python message which I am not familiar with.

**Comment by jeremyd2019** [comment]
> I have added the arm64 platform in gn. But the ninja command goes in an endless loop. After Ctrl+C, it shows some python message which I am not familiar with.

Seemed to work for me: https://github.com/msys2-arm/MINGW-packages/actions/runs/3889880322/jobs/6638775933  :shrug:

**Comment by Biswa96** [comment]
Thank you for checking that. Let me rebase the changes.

**Comment by jeremyd2019** [comment]
Note I also removed the special case for clangarm64 not depending on angleproject in libepoxy on that branch, I don't know if you want to do that in this PR too...

**Comment by Biswa96** [comment]
> Note I also removed the special case for clangarm64 not depending on angleproject in libepoxy...

Yeah, I also wanted to do that. Hence I asked previously "if angle and libepoxy build with this change".

**Comment by Biswa96** [comment]
Though it is expected, the `GDK_GL=gles gtk3-demo --run=glarea` command shows no GL implementation in Windows ARM in Rpi4.

**Pull request merged**
