### PR TITLE
Updates wxPython to 4.1.2 Alpha 1 and adds header to wxWidgets 3.1.7 package

### PR DESCRIPTION
**Pull request by stahta01**
Updates wxPython to 4.1.2 Alpha 1 and adds header to wxWidgets 3.1.7 needed to build wxPython.

Tim S.

### CODE REVIEW

**Comment by lazka** [comment]
thanks!

**Comment by MehdiChinoune** [comment]
sip 6.6.2 was released with some specific fixes for wxPython https://www.riverbankcomputing.com/pipermail/pyqt/2022-June/044726.html

**Comment by stahta01** [comment]
> sip 6.6.2 was released with some specific fixes for wxPython https://www.riverbankcomputing.com/pipermail/pyqt/2022-June/044726.html

wxPython still fails to build with sip 6.6.2-2

Tim S.

**Comment by MehdiChinoune** [comment]
> > sip 6.6.2 was released with some specific fixes for wxPython https://www.riverbankcomputing.com/pipermail/pyqt/2022-June/044726.html
> 
> wxPython still fails to build with sip 6.6.2-2
> 
> Tim S.

Could you show error messages, maybe I could help.

**Comment by stahta01** [comment]
> > > sip 6.6.2 was released with some specific fixes for wxPython https://www.riverbankcomputing.com/pipermail/pyqt/2022-June/044726.html
> > 
> > 
> > wxPython still fails to build with sip 6.6.2-2
> > Tim S.
> 
> Could you show error messages, maybe I could help.

I will try without my revert sip change patch and see if the change was to fix the python SIP command.

```
Running command: sip
H:/msys64/mingw64/bin/sip -w -o -g -n wx.siplib -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/src -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/sip/gen -c C:/Users/CONFID~1/AppData/Local/Temp/tmp3n4tuglq -b sip/cpp/_core.sbf -X pycode_core:wx/core.py  sip/gen/_core.sip
Command 'H:/msys64/mingw64/bin/sip -w -o -g -n wx.siplib -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/src -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/sip/gen -c C:/Users/CONFID~1/AppData/Local/Temp/tmp3n4tuglq -b sip/cpp/_core.sbf -X pycode_core:wx/core.py  sip/gen/_core.sip' failed with exit code 1.
Finished command: sip (0.59s)
```

**Comment by MehdiChinoune** [comment]
> > > > sip 6.6.2 was released with some specific fixes for wxPython https://www.riverbankcomputing.com/pipermail/pyqt/2022-June/044726.html
> > > 
> > > 
> > > wxPython still fails to build with sip 6.6.2-2
> > > Tim S.
> > 
> > 
> > Could you show error messages, maybe I could help.
> 
> I will try without my revert sip change patch and see if the change was to fix the python SIP command.
> 
> ```
> Running command: sip
> H:/msys64/mingw64/bin/sip -w -o -g -n wx.siplib -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/src -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/sip/gen -c C:/Users/CONFID~1/AppData/Local/Temp/tmp3n4tuglq -b sip/cpp/_core.sbf -X pycode_core:wx/core.py  sip/gen/_core.sip
> Command 'H:/msys64/mingw64/bin/sip -w -o -g -n wx.siplib -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/src -I H:/PKGs/MINGW-packages/mingw-w64-wxPython/src/wxPython-4.1.2a1.dev5434+7d45ee6a/sip/gen -c C:/Users/CONFID~1/AppData/Local/Temp/tmp3n4tuglq -b sip/cpp/_core.sbf -X pycode_core:wx/core.py  sip/gen/_core.sip' failed with exit code 1.
> Finished command: sip (0.59s)
> ```

sip>6.0 doesn't have any executable named sip, It has sip-build, sip-install and sip-module.
It looks like wxPython have not yet ported to work with SIP>=6

**Comment by MehdiChinoune** [comment]
https://github.com/wxWidgets/Phoenix/pull/2179

**Comment by mmuetzel** [comment]
> building failed because of a missing python package I think it's called attrs*3.

Could that be this package?
https://packages.msys2.org/base/mingw-w64-python-attrs

**Comment by MehdiChinoune** [comment]
> > building failed because of a missing python package I think it's called attrs*3.
> 
> Could that be this package? https://packages.msys2.org/base/mingw-w64-python-attrs

No, It is attrdict3 https://github.com/wxWidgets/Phoenix/blob/master/requirements/devel.txt#L23

**Comment by stahta01** [comment]
> > > [wxWidgets/Phoenix#2179](https://github.com/wxWidgets/Phoenix/pull/2179)
> > 
> > 
> > See also [Phoenix issues 2169](https://github.com/wxWidgets/Phoenix/issues/2169)
> 
> The PR is opened to close that issue! I have tried to apply that patch, but building failed because of a missing python package I think it's called attrdict3. Could you take a look and add that required package.

The PR no longer can be applied to the master branch. I applied part of it and got a weird error.

```
sip_corewxAutoBufferedPaintDC.cpp is changed, copying...
Traceback (most recent call last):
  File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 2353, in <module>
    main(sys.argv[1:])
  File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 201, in main
    function(options, args)
  File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 1371, in cmd_sip
    srcTxt = processSrc(src, options.keep_hash_lines)
  File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 1328, in processSrc
    srcTxt = f.read()
  File "H:/msys64/mingw32/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 73365: invalid continuation byte
Finished command: sip (0m24.981s)
```
So, I plan to watch the issue instead of the PR and I will run the below command from time to time to see if progress is being made.

```
# from mingw32 propmt
rm -fr ~/pytemp && mkdir -p ~/pytemp && \
pip install --upgrade --platform win32 --only-binary=:all: --target ~/pytemp sip==6.6.2
```
I am guessing the PR is waiting for upstream binary to be made.

I am also guess that a new PR might be required.

Tim S.

**Comment by MehdiChinoune** [comment]
> The PR no longer can be applied to the master branch. I applied part of it and got a weird error.
> 
> ```
> sip_corewxAutoBufferedPaintDC.cpp is changed, copying...
> Traceback (most recent call last):
>   File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 2353, in <module>
>     main(sys.argv[1:])
>   File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 201, in main
>     function(options, args)
>   File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 1371, in cmd_sip
>     srcTxt = processSrc(src, options.keep_hash_lines)
>   File "H:\PKGs\MINGW-packages\mingw-w64-wxPython\src\wxPython-4.1.2a1.dev5434+7d45ee6a\build.py", line 1328, in processSrc
>     srcTxt = f.read()
>   File "H:/msys64/mingw32/lib/python3.10/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 73365: invalid continuation byte
> Finished command: sip (0m24.981s)
> ```

It applies cleanly on my side on the same snapshot
https://github.com/MehdiChinoune/MINGW-packages/commit/d1395e726b118d7d2626dd7250e4f66f1ea42527
https://github.com/MehdiChinoune/MINGW-packages/runs/6973331444?check_suite_focus=true

> So, I plan to watch the issue instead of the PR and I will run the below command from time to time to see if progress is being made.
> 
> ```
> # from mingw32 propmt
> rm -fr ~/pytemp && mkdir -p ~/pytemp && \
> pip install --upgrade --platform win32 --only-binary=:all: --target ~/pytemp sip==6.6.2
> ```
> 
> I am guessing the PR is waiting for upstream binary to be made.

sip 6.6.2 was released and it is available as a binary as well https://pypi.org/project/sip/#files
> 
> I am also guess that a new PR might be required.

To be seen after providing attrdict3 python package.

**Comment by stahta01** [comment]
The sip6 branch merged with wxPython master branch this time; I must of done something wrong.

**Pull request merged**
