### PR TITLE
add package python-igraph

### LINKED ISSUE #21316: Add [mingw-w64-python-igraph]
### Package name

python-igraph

### Brief description of package

This is an interface for igraph in python, not so easy to install sometimes.

### URL for package's homepage

https://github.com/igraph/python-igraph

### Provide a basic test case to validate the package's functionality.

import igraph

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by Kreijstal**
This fixes #21316, also thank you for the feedback on texttable
also related
https://github.com/igraph/python-igraph/issues/769
https://github.com/igraph/python-igraph/issues/574

### CODE REVIEW

**Comment by szhorvat** [comment]
Just a heads up that if you decide to make this depend on `igraph`, it is your responsibility to update `python-igraph` and `igraph` concurrently. `python-igraph` is only guaranteed to be compatible with a single patch release of `igraph`. Even though in practice compatibility is not broken frequently, there is no guarantee that a given `python-igraph` will be compatible with an earlier or later `igraph`.

**Comment by Kreijstal** [comment]
> Just a heads up that if you decide to make this depend on `igraph`, it is your responsibility to update `python-igraph` and `igraph` concurrently. `python-igraph` is only guaranteed to be compatible with a single patch release of `igraph`. Even though in practice compatibility is not broken frequently, there is no guarantee that a given `python-igraph` will be compatible with an earlier or later `igraph`.
> 
> You may choose to use the version of `igraph` included in `python-igraph` (instead of setting `IGRAPH_USE_PKG_CONFIG=1`)and then you will not need to be concerned about this.

But you would then have 2 possibly conflicting igraph versions?

**Comment by szhorvat** [comment]
No, you would not. `python-igraph` includes the full source code of the C/igraph library, and this is used by default when you compile `python-igraph` (i.e. when you don't set `IGRAPH_USE_PKG_CONFIG`). This does not mean that the C igraph library will be installed. It won't. It will be statically linked into `python-igraph`.

**Comment by Kreijstal** [comment]
> No, you would not. `python-igraph` includes the full source code of the C/igraph library, and this is used by default when you compile `python-igraph` (i.e. when you don't set `IGRAPH_USE_PKG_CONFIG`). This does not mean that the C igraph library will be installed. It won't. It will be statically linked into `python-igraph`.

It is all good as long as there are always python-igraph releases that match igraph itself

**Comment by szhorvat** [comment]
There aren't (usually for lack of time). If you're in doubt about compatibility, feel free to ping me ... Sorry that I can't offer a better solution at the moment.

**Pull request merged**
