### PR TITLE
portaudio: Don't link with uuid; update; port to cmake (msys2#8805)

### PR DESCRIPTION
**Pull request by mmuetzel**
This change should be fixing #8805.

I don't know if this is the expected process to propose a change. Please, let me know if I should do something different instead.

### CODE REVIEW

**Comment by lazka** [comment]
Ideally this would a separate patch file

**Comment by lazka** [comment]
There is also a new upstream release. If you are bored you can look into updating to it ;)

**Comment by lazka** [comment]
hm, for some reason CI says the dll moved..

```diff
  --- /dev/fd/63	2021-07-19 17:44:35.000000000 +0000
  +++ /dev/fd/62	2021-07-19 17:44:35.000000000 +0000
  @@ -1,10 +1,9 @@
   /mingw32/
  -/mingw32/bin/
  -/mingw32/bin/libportaudio-2.dll
   /mingw32/include/
   /mingw32/include/portaudio.h
   /mingw32/lib/
   /mingw32/lib/libportaudio.a
  -/mingw32/lib/libportaudio.dll.a
  +/mingw32/lib/libportaudio.lib
  +/mingw32/lib/libportaudio-2.dll
   /mingw32/lib/pkgconfig/
   /mingw32/lib/pkgconfig/portaudio-2.0.pc
```

**Comment by mmuetzel** [comment]
I don't know how the new patch could have caused that.
Maybe different build tools since the last time the library was packaged?

**Comment by lazka** [comment]
yeah, likely not related to this change, still needs to be fixed :/

**Comment by mmuetzel** [comment]
I updated the patches for portaudio 19.07 locally.
Should I push that here? Or better in a separate PR?

That version also installs the binary to `lib` currently.

**Comment by lazka** [comment]
pushing here is fine I think

**Comment by mmuetzel** [comment]
Afaict, the library is installed by libtool with the following command:
```
./libtool --mode=install /usr/bin/install -c lib/libportaudio.la /path/to/MINGW-packages/mingw-w64-portaudio/pkg/mingw-w64-x86_64-portaudio/mingw64/lib
```
I was thinking that tools like `libtool` would automagically find the correct paths on many platforms (including mingw). But it installs the `.dll` to the `lib` folder.
If I call the "global" `libtool` manually instead of the one from portaudio, it installs the `.dll` to the `lib` *and* the `bin` folder.

I'm not sure what is going on tbh.

**Comment by lazka** [comment]
Maybe we should try to build with cmake instead

**Comment by lazka** [comment]
I've pushed a commit changing to cmake. Can you give that a try and see if it works for you?

**Comment by mmuetzel** [comment]
Perfect! 👍 

Not only does the cmake rule install the `.dll` into the correct folder. The switches in the package config file also look a lot cleaner. Turns out `-lportaudio` is enough. 💯
Also: It looks like you could remove all local patches. That's probably a good thing, too.

I'm currently re-building Octave in msys2 without manually overriding the portaudio flags. That was when I first noticed #8805.
I'll report back how that turns out.

**Comment by mmuetzel** [comment]
Compilation succeeded. And the test suite showed the same errors that I knew from before.
So, I'd say that your changeset works as expected.

**Comment by lazka** [comment]
Thanks for testing, then I'll try rebuilds later.

**Comment by mmuetzel** [comment]
Is there anything I can do to help with that?

**Comment by mmuetzel** [comment]
I didn't notice before. But iiuc, the clang32 build is failing with the cmake build rule.
The error is:
```
  [16/44] Building C object CMakeFiles/portaudio.dir/src/hostapi/wasapi/pa_win_wasapi.c.obj
  FAILED: CMakeFiles/portaudio.dir/src/hostapi/wasapi/pa_win_wasapi.c.obj 
  D:\a\_temp\msys\msys64\clang32\bin\clang.exe -DPAWIN_USE_WDMKS_DEVICE_INFO -DPA_LITTLE_ENDIAN -DPORTAUDIO_CMAKE_GENERATED -DWINVER=0x0501 -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0501 -Dportaudio_EXPORTS -DUNICODE -D_UNICODE -IC:/_/mingw-w64-portaudio/src/portaudio/src/common -IC:/_/mingw-w64-portaudio/src/build-i686-w64-mingw32 -IC:/_/mingw-w64-portaudio/src/portaudio/src/os/win -IC:/_/mingw-w64-portaudio/src/portaudio/include -march=i686 -mtune=generic -O2 -pipe -O3 -DNDEBUG -MD -MT CMakeFiles/portaudio.dir/src/hostapi/wasapi/pa_win_wasapi.c.obj -MF CMakeFiles\portaudio.dir\src\hostapi\wasapi\pa_win_wasapi.c.obj.d -o CMakeFiles/portaudio.dir/src/hostapi/wasapi/pa_win_wasapi.c.obj -c C:/_/mingw-w64-portaudio/src/portaudio/src/hostapi/wasapi/pa_win_wasapi.c
  C:/_/mingw-w64-portaudio/src/portaudio/src/hostapi/wasapi/pa_win_wasapi.c:175:24: error: redefinition of '_BYTE_BLOB'
          typedef struct _BYTE_BLOB
                         ^
  D:/a/_temp/msys/msys64/clang32/i686-w64-mingw32/include/wtypesbase.h:317:16: note: previous definition is here
  typedef struct _BYTE_BLOB {
                 ^
  C:/_/mingw-w64-portaudio/src/portaudio/src/hostapi/wasapi/pa_win_wasapi.c:179:15: error: typedef redefinition with different types ('struct (anonymous struct at C:/_/mingw-w64-portaudio/src/portaudio/src/hostapi/wasapi/pa_win_wasapi.c:175:24)' vs 'struct _BYTE_BLOB')
          }     BYTE_BLOB;
                ^
  D:/a/_temp/msys/msys64/clang32/i686-w64-mingw32/include/wtypesbase.h:320:3: note: previous definition is here
  } BYTE_BLOB;
    ^
  C:/_/mingw-w64-portaudio/src/portaudio/src/hostapi/wasapi/pa_win_wasapi.c:1759:17: warning: enumeration value 'eStreamOptionNone' not handled in switch [-Wswitch]
          switch (streamInfo->streamOption)
                  ^
  1 warning and 2 errors generated.
```

The wasapi files were heavily patched with the old build rules. Maybe some of those changes are still needed?

**Comment by lazka** [comment]
> I didn't notice before. But iiuc, the clang32 build is failing with the cmake build rule.

thanks, fixed

**Pull request merged**
