### PR TITLE
vulkan: update to v1.3.274

### PR DESCRIPTION
**Pull request by oltolm**
This is necessary for yuzu.

### CODE REVIEW

**Comment by ognevnydemon** [comment]
`updpkgsums`

**Comment by MehdiChinoune** [comment]
We have encountered some issues with Vulkan updates before.
I think we track the latest SDK tags `vulkan-sdk`, which still 1.3.268.0

**Comment by lazka** [comment]
Looking at the release history, they release about every two months, so shouldn't be too far out hopefully.

**Comment by lazka** [comment]
@oltolm update is in the repo now

**Pull request closed without merging**
