### PR TITLE
kde-frameworks: update to 5.97.0 - Part1

### PR DESCRIPTION
**Pull request by MehdiChinoune**
kcore-addons fails on 32bit envs. Something related to `__stdcall`.

### CODE REVIEW

**Comment by Biswa96** [comment]
The issue seems to be in mingw-w64 headers. Let me reproduce the issue in my system. Thanks for updating these KDE packages.

**Comment by Biswa96** [comment]
I have sent a patch to upstream mingw-w64 https://sourceforge.net/p/mingw-w64/mailman/message/37698415/. It may fix the issue in kcoreaddons-qt5 package. But I can not build all the packages using mingw32 in my old rusty box 😢

**Comment by Biswa96** [comment]
ucrt64 build failed with kcompletion-qt5 package. I have built it in my PC without any issue. I think this can be fixed in autobuild by rebuilding.

**Comment by MehdiChinoune** [comment]
> ucrt64 build failed with kcompletion-qt5 package. I have built it in my PC without any issue. I think this can be fixed in autobuild by rebuilding.

The previous time it failed because of the other random `#include "stdlib.h"`.

**Pull request merged**
