### PR TITLE
helics: Update to 2.7.0

### PR DESCRIPTION
**Pull request by nightlark**
Update to the HELICS 2.7.0 release

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Any idea why lgamma_r would be undefined for clang?

**Comment by nightlark** [comment]
No, it works fine on our Linux clang CI builds. Must be something wonky with the clang build environment used by the msys2 CI job.

**Comment by Biswa96** [comment]
> Must be something wonky with the clang build environment

Agreed. Same error with older version of helics.

**Comment by jeremyd2019** [comment]
Well, it's right - lgamma_r is not present in the mingw-w64 libraries, but also not on the mingw64 variant

**Comment by jeremyd2019** [comment]
not in the headers, either, but seems to be referencd from libc++.  Sounds like an upstream bug to me. (either mingw-w64 needs to provide it, or libc++ needs to avoid using it)

**Pull request merged**
