### PR TITLE
Update Rust to 1.48

### PR DESCRIPTION
**Pull request by mati865**
Closes https://github.com/msys2/MINGW-packages/issues/6758

### CODE REVIEW

**Comment by Biswa96** [comment]
Following the trend, I think Python commands are just `python` not `python3`.

**Comment by mati865** [comment]
I can reproduce 64-bit `(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)` locally with latest packages, trying to fix it.

**Comment by abcfy2** [comment]
Hope this build failing would be fixed.

**Comment by mati865** [comment]
I believe I've got the fix (still testing it to be sure).
Before https://github.com/rust-lang/rust/pull/72049 Rust was relying on the linker "to make things work". That means linker to guess dllimport/dllexport and in case it fails the linker was using runtime pseudo relocs as backup.
I haven't full investigated it but I think the recent changes to Binutils (namely increasing base address over 4G for 64-bit binaries) made runtime pseudo relocs that have 32-bit offsets to overflow and hence trigger the DEP.
That would also explain why i686 build had no issues.

@lazka I believe that would explain some of those cases:
> So far all software that also supports building with MSVC works fine (glib,gtk3,pygobject for example) so I'm wondering if this isn't just exposes some latent bugs for things only built with mingw so far. Agreed on the example search..

**Comment by lazka** [comment]
So we should pass `-Wl,--no-dynamicbase,--image-base=0x400000` to revert this for rust for now?

**Comment by mati865** [comment]
@lazka that would be complicated since executables and DLLs use different base addresses.
I'm backporting https://github.com/rust-lang/rust/pull/72049 and it already passed with `export LDFLAGS="-pipe"`. I'm testing default LDFLAGS now but since https://github.com/rust-lang/rust/pull/75406 works for me locally I believe this will also succeed.

**Comment by jeremyd2019** [comment]
> @lazka that would be complicated since executables and DLLs use different base addresses.

Yes!  I was considering sending another patch for binutils to allow selecting whether the default bases should be "high" or "low" via command line option.  But I am not sold on that being a good idea.  It would make hacking around buggy programs a lot easier though.  Thoughts?

**Comment by mati865** [comment]
> It would make hacking around buggy programs a lot easier though. Thoughts?

It would definitely help with the transition.

**Comment by jeremyd2019** [comment]
> It would definitely help with the transition.

I made a patch and am testing it now (simple tests worked as intended, going to attempt building GCC with it).  I don't know if a 'transitional' option warrants upstreaming though.

**Comment by lazka** [comment]
New binutils with `--default-image-base-low` option is now in the repo.

**Comment by mati865** [comment]
I think using https://github.com/rust-lang/rust/pull/72049 instead of `--default-image-base-low` is better but it's up to you.

**Comment by lazka** [comment]
a real upstream fix/backport is obviously better

**Comment by mati865** [comment]
I have no idea why CI fails on x86_64 build, lets try again.

**Comment by lazka** [comment]
Not sure if relevant, but it finds the wrong Python: `-- Found Python3: C:/hostedtoolcache/windows/Python/3.8.6/x86/python.exe (found version "3.8.6") found components: Interpreter `

**Comment by mati865** [comment]
Blocked on https://github.com/msys2/MINGW-packages/pull/7116

**Comment by mati865** [comment]
CI now appears to be failing due to path length but it's kinda hard to tell.

**Comment by jeremyd2019** [comment]
Or command line length limit, by the look of that ar command... I copy/pasted it and saw 36618 characters there!

**Comment by mati865** [comment]
I think it should have used response file but yeah sounds plausible.

**Comment by filnet** [comment]
Hi,

What's holding up the rust upgrade ? A hard to solve technical problem or just lack of time from the maintainers ?
Can I help in any way ?

**Comment by mati865** [comment]
Local build succeeds every time for me.
I haven't got to dive deeply into the issue yet and since the next Rust version will be released this week I just decided to wait.

**Comment by Zapeth** [comment]
Looking at the build log it seems the failed ar command originates from compiling [libgit2-sys](https://github.com/rust-lang/git2-rs/tree/master/libgit2-sys) for cargo.

I haven't heard yet of command line length being an issue when compiling any kind of software, but path length could certainly be an issue (some of those paths get pretty close to the Windows [MAX_PATH](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) length, and i686 config might just fall under that limit), though I'd be curious why this wasn't an issue with earlier package releases.

In any case, 1.48 was released yesterday, so it might be worth trying a new ci build with that.

**Comment by mati865** [comment]
> I haven't heard yet of command line length being an issue when compiling any kind of software, but path length could certainly be an issue

IIRC I have inspected the longest paths and they were under the limit. Command line limit is definitely a thing on Windows but it depends on how you run the executable so I won't even try to guess what is the limit in this case.

**Comment by mati865** [comment]
I have no idea why it fails with `rustc-1.48.0-src.tar.gz ... FAILED (unknown public key 85AB96E6FA1BE5FE)` on CI.
The build passed for me locally before pushing.

**Comment by lazka** [comment]
It means the release was signed with an ancient gnupg which doesn't include the full key in the signature. You can remove the signature to avoid it.

**Comment by Zapeth** [comment]
Looks like the same issue. I did some searching online and found this -> https://github.com/alexcrichton/cc-rs/pull/496

**Comment by lazka** [comment]
nice :) should I merge?

**Comment by mati865** [comment]
I have made basic tests with x86_64 before pushing and it worked so I guess it's good to go.

**Comment by lazka** [comment]
built librsvg with it and all looks good.

**Comment by a8nJ** [comment]
So how do we get the new version?

**Comment by Biswa96** [comment]
Just wait and [watch](https://packages.msys2.org/updates).

**Pull request merged**
