### PR TITLE
angleproject: rebuild

### LINKED ISSUE #16971: [angleproject] linking fails in mingw32 with undefined symbols
### Description / Steps to reproduce the issue

When attempting to link an sdl2/gles2 hello world against ANGLE's GLESv2, I get a bunch of undefined references.

```
$ gcc sdl2gles2tri.c -lmingw32 -mwindows -lSDL2main -lSDL2 -lGLESv2
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x49): undefined reference to `_imp__glCreateShader@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x83): undefined reference to `_imp__glShaderSource@16'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x93): undefined reference to `_imp__glCompileShader@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0xb2): undefined reference to `_imp__glGetShaderiv@12'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0xe3): undefined reference to `_imp__glGetShaderiv@12'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x11f): undefined reference to `_imp__glGetShaderInfoLog@16'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x14d): undefined reference to `_imp__glDeleteShader@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x236): undefined reference to `_imp__glCreateProgram@0'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x25d): undefined reference to `_imp__glAttachShader@8'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x274): undefined reference to `_imp__glAttachShader@8'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x294): undefined reference to `_imp__glBindAttribLocation@12'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x2a4): undefined reference to `_imp__glLinkProgram@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x2c6): undefined reference to `_imp__glGetProgramiv@12'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x300): undefined reference to `_imp__glGetProgramiv@12'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x345): undefined reference to `_imp__glGetProgramInfoLog@16'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x373): undefined reference to `_imp__glDeleteProgram@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x39b): undefined reference to `_imp__glClearColor@16'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x416): undefined reference to `_imp__glViewport@16'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x427): undefined reference to `_imp__glClear@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x437): undefined reference to `_imp__glUseProgram@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x46f): undefined reference to `_imp__glVertexAttribPointer@24'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x480): undefined reference to `_imp__glEnableVertexAttribArray@4'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x4a1): undefined reference to `_imp__glDrawArrays@12'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x5c6): undefined reference to `_imp__glGetError@0'
C:/msys64/mingw32/bin/sdl2gles2tri.c:(.text+0x5e5): undefined reference to `_imp__glGetError@0'
```

### Expected behavior

Proper linkage.

### Actual behavior

As mentioned, failure to resolve ABI.

Other relevant information,  ANGLE's libraries don't seem to export these symbols.
```
$ nm -g libGLESv2.dll.a | grep _imp__glCreateShader@4
(no output)
```

```
$ nm -g libGLESv2.dll.a | grep glCreateShader
00000000 I __imp__glCreateShaderProgramvEXT
00000000 T _glCreateShaderProgramvEXT
00000000 I __imp__glCreateShaderProgramv
00000000 T _glCreateShaderProgramv
00000000 I __imp__glCreateShader
00000000 T _glCreateShader
```

I'm not sure where the source of this `@4` is being introduced, but the number of underscores at the beginning of the function signature seems incorrect too. I've only tried on MINGW32, as SDL seems to require linking against specifically the 32bit mingw library.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

If I can determine the solution, absolutely

### PR DESCRIPTION
**Pull request by lb90**
Rebuild after #17163 to fix #16971

### CODE REVIEW

**Comment by lazka** [comment]
does it need any testing, or OK to merge?

**Comment by raedrizqie** [comment]
@lb90  maybe you could at this
```
diff --git a/src/compiler/translator/Compiler.cpp b/src/compiler/translator/Compiler.cpp
index 37ca80a28..93b542bbb 100644
--- a/src/compiler/translator/Compiler.cpp
+++ b/src/compiler/translator/Compiler.cpp
@@ -1217,7 +1217,7 @@ bool TCompiler::checkAndSimplifyAST(TIntermBlock *root,

 bool TCompiler::resizeClipAndCullDistanceBuiltins(TIntermBlock *root)
 {
-    auto resizeVariable = [=](const ImmutableString &name, uint32_t size, uint32_t maxSize) {
+    auto resizeVariable = [=, this](const ImmutableString &name, uint32_t size, uint32_t maxSize) {
         // Skip if the variable is not used or implicitly has the maximum size
         if (size == 0 || size == maxSize)
             return true;

```
to `003-angle-src-fixes.patch`, to fix the compiler warning

**Comment by lb90** [comment]
Mmh not sure if hosting at https://chromium.googlesource.com has some connectivity issues, or maybe if it's due to a misconfiguration? Otherwise we can point to the official mirror on github: https://github.com/google/angle

**Comment by raedrizqie** [comment]
maybe you need to rebase?

**Comment by mmuetzel** [comment]
I triggered a rebuild. But it still failed checking out the Git repository.
Afaict, `curl` and `wget` have been updated recently. Did one of those break `git`? Or is it just that specific remote repository?

**Comment by raedrizqie** [comment]
```
Did one of those break git? Or is it just that specific remote repository?
```
its the latter, i think

**Comment by lb90** [comment]
Yeah, what's very strange is that it only happens when running makepkg-mingw. If I run `git clone https://chromium.googlesource.com/angle/angle`  from a MSYS2 shell everything works

**Comment by lb90** [comment]
Using process explorer I see two git.exe instances and one git-remote-https.exe instance. git.exe uses a full CPU core for about 10 seconds, then it stops and git-remote-https.exe starts working, but suddenly I get the error. I guess that git-remote-https.exe does its work too late? I guess the server has timed out by then.

The question is: what's git.exe doing with a full CPU core initially?

/cc @dscho

**Comment by lb90** [comment]
makepkg-mingw invokes git with the --mirror command-line argument. I can now reproduce with `git clone --mirror https://chromium.googlesource.com/angle/angle.git`

**Comment by lazka** [comment]
I think it's a curl or curl-related issue. git+http2+curl8.1 fails on Arch Linux while it works when downgrading to 8.0 or forcing http1

**Comment by dscho** [comment]
> I've filed an issue: [curl/curl#11201](https://github.com/curl/curl/issues/11201)

Awesome work @lazka! Looks like cURL v8.1.2 with a fix for this [will be released in four days](https://curl.se/mail/lib-2023-05/0042.html).

**Pull request merged**
