### PR TITLE
llvm: Apply workaround for Failed to evaluate function length in SEH unwind info in aarch64

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by lazka** [comment]
needs a pkgrel bump

**Comment by hmartinez82** [comment]
First time I see these errors:
```
  checking keyring...
  checking package integrity...
  :: File /var/cache/pacman/pkg/mingw-w64-x86_64-llvm-libs-17.0.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
  Do you want to delete it? [Y/n] 
  :: File /var/cache/pacman/pkg/mingw-w64-x86_64-llvm-17.0.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
  error: failed to commit transaction (invalid or corrupted package)
  Do you want to delete it? [Y/n] 
  Errors occurred, no packages were upgraded.
  Error: Process completed with exit code 1.
```

**Comment by hmartinez82** [comment]
Version bumped. I wonder if there's a limit of 6hrs per build and it's reaching that point

**Comment by mmuetzel** [comment]
Did this patch make it into the 17.0.2 release? Or do we still need to backport it in MSYS2 now that Clang 17.0.2 is being built for staging?

**Comment by hmartinez82** [comment]
Humm. I don't know. https://github.com/llvm/llvm-project-release-prs/pull/722 says merged for release 17.x, but I don't know if made into 17.0.2

**Comment by hmartinez82** [comment]
Apparently, it did not https://github.com/llvm/llvm-project/commits/llvmorg-17.0.2

**Comment by mmuetzel** [comment]
Hmm... Looking at the commit history, this might have landed a couple of days after 17.0.2 was tagged...

**Comment by hmartinez82** [comment]
> Hmm... Looking at the commit history, this might have landed a couple of days after 17.0.2 was tagged...

Yes, they stated as much: https://github.com/llvm/llvm-project-release-prs/pull/722#issuecomment-1744292890

**Comment by rimrul** [comment]
> I wonder if there's a limit of 6hrs per build and it's reaching that point

There is a limit of 6hours per job.

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

**Comment by hmartinez82** [comment]
I'll rebase this and let's try again

**Pull request merged**
