### PR TITLE
mold: don't use mimalloc which causes segfault

### LINKED ISSUE #15462: Mold failure to install and segfault when run
### Description / Steps to reproduce the issue

When installing the `mold` linker (at least for mingw-w64-x86_64 and mingw-w64-clang64 MSYS2 environments) the install terminates with the following warning:
```
:: Proceed with installation? [Y/n]
(2/2) checking keys in keyring                                        [#####################################] 100%
(2/2) checking package integrity                                      [#####################################] 100%
(2/2) loading package files                                           [#####################################] 100%
(2/2) checking for file conflicts                                     [#####################################] 100%
(2/2) checking available disk space                                   [#####################################] 100%
:: Processing package changes...
(1/2) installing mingw-w64-x86_64-mimalloc                            [#####################################] 100%
(2/2) installing mingw-w64-x86_64-mold                                [#####################################] 100%
warning: warning given when extracting /mingw64/bin/ld.mold.exe (Can't create '/mingw64/bin/ld.mold.exe')
```
Subsequently attempting to run any mold command (e.g. `mold --version`) results in data being written to stdout as expected, followed by a segfault
```
> mold --version
mold 1.10.1 (compatible with GNU ld)
Segmentation fault
```

Consistent MRE for both (works with anything passed to mold, even no args or `--help`):
```
> pacman -S mingw-w64-x86_64-mold --noconfirm && mold --version
```

I know for sure that using the clang64 version fails with the same error, I'm not sure about the other environments, but I expect them to be no different.

### Expected behavior

`mold` installing without warnings, `/$MINGW_PREFIX/bin/ld.mold.exe` existing, no segfaults when calling `mold`

### Actual behavior

No warnings on installing, `/$MINGW_PREFIX/bin/ld.mold.exe` does not exist, mold segfaults when called

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes, however #2631 is in-progress by @Biswa96

### PR DESCRIPTION
**Pull request by yujincheng08**
Fix #15462

Tested it works (but no lto support).

### CODE REVIEW

**Comment by yujincheng08** [comment]
Hi, you can see #15462. The stacktrace happens on mimalloc so I raised this PR. Still need more tests so it's still a draft.

**Comment by 3rav** [comment]
Update to 2.32.0?

**Comment by yujincheng08** [comment]
@3rav I intentionally avoid upgrading to make this PR simple. I will upgrade when this PR gets merged.

**Comment by yujincheng08** [comment]
@lazka hi, could you please take a look at this PR?

**Comment by lazka** [comment]
I hope mimalloc will work eventually. CPython will hard-depend on it in the future.

**Comment by RivenSkaye** [comment]
Building mimalloc for Rust has kept something we needed in prod at work going for 3 months straight without a hitch. So I _know_ the allocator can work on the exact same toolchain that had the mold crashes. I don't know what mold does differently in its use of mimalloc, or what version it builds on though

**Pull request merged**
