### PR TITLE
[v8] Update to stable version 9.0.257.17

### PR DESCRIPTION
**Pull request by Kwizatz**
This patch includes a change to fetch the v8 source tar
from the github mirror in order to bring build time down.

### CODE REVIEW

**Comment by Biswa96** [comment]
As we are using a specific tarball we don't need git and patch in makedepends.

**Comment by Kwizatz** [comment]
Whats the difference between a MINGW64 and a UCRT64 build? seems like the UCRT64 build is trying to compile with MSVC, which is probably an error on the gn side.

**Comment by 1480c1** [comment]
ucrt64 build is using a mingw-w64 toolchain that uses ucrt instead of msvcrt as the c runtime library, but in this case it seems it might be a problem on gn's side on detecting ucrt64 as still mingw-w64 gcc

**Comment by Kwizatz** [comment]
It shouldn't be too hard to add support for it, I assume there is a compiler and/or linker flag to use it? let me know what is it and I'll see what can I do, I'll also remove patch and git from the makedepends.

Thanks!

**Comment by lazka** [comment]
You don't need to pass any flags to use it. The build seems to default to msvc though, so I'd guess the mingw detection needs to be fixed/improved.

**Comment by Kwizatz** [comment]
No, I have an idea of what the problem might be, the build determines that it is on a msys/mingw system based on the MSYSTEM enviroment variable, so I'll just have to check what ENV vars are set for UCRT64, is it MSYSTEM=UCRT64?.

I also want to remove git and patch from de dependencies so the PKGBUILD is cleaner.

**Comment by lazka** [comment]
`(MSYSTEM != "" && MSYSTEM != "MSYS")` would be more future proof

**Comment by Kwizatz** [comment]
Got it, thanks!

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
