### PR TITLE
python3.9: add windows 7 support

### PR DESCRIPTION
**Pull request by naveen521kk**

### CODE REVIEW

**Comment by Biswa96** [comment]
It may be better to track if a comment is added in the patch file with the link you've provided me tomorrow in Discord.

**Comment by lazka** [comment]
How hard would it be to have all win7 changes in one patch?

**Comment by naveen521kk** [comment]
Hmm, ok I will do those.

**Comment by naveen521kk** [comment]
ping

**Comment by lazka** [comment]
tested on win7, works nicely.

**Pull request merged**
