### PR TITLE
mpfr: Enable building shared libraries

### LINKED ISSUE #10808: Need MPFR shared libraries
I am trying to build an MS Windows binary for Normaliz  (https://github.com/Normaliz/Normaliz) with all optional packages that are available under Linux and MacOS. I have succeeded with one exception, namely e-antic (https://github.com/flatsurf/e-antic). It insists on shared libraries upstream, including MPFR. 

Unfortunately my attempts to build a dll for MPFR have failed because configure thinks that I don't have shared libraries for GMP. They exist, and without them the C compiler would not even work.

It did not help to install MPFR by pacman, since shared libraries are build neither. What can I do?

### PR DESCRIPTION
**Pull request by MehdiChinoune**
fixes #10808

### CODE REVIEW

**Comment by lazka** [comment]
This adds a runtime dep on all reverse dependencies when they get rebuilt, so we would need to add mpfr there.

**Comment by MehdiChinoune** [comment]
You could add it now without bumping pkgrel, just in case

**Comment by MehdiChinoune** [comment]
So, we went from enabling static libraries to favoring them and disabling the shared ones.
Good progress.

**Comment by lazka** [comment]
I'm confused, what are you referring to?

**Comment by MehdiChinoune** [comment]
The only package where mpfr is not in `depends` is `eigen3` which is just headers library.

**Comment by MehdiChinoune** [comment]
Ping!

**Comment by MehdiChinoune** [comment]
> (This adds a runtime dep on all reverse dependencies when they get rebuilt, so we would need to add mpfr there)

It could be detected now with checking-runtime-dependencies step.

**Comment by lazka** [comment]
What about gcc?

**Comment by MehdiChinoune** [comment]
> What about gcc?

About what?
`mpfr` depends only on `gmp` which doesn't depend on any package => No cycle dependency.

**Comment by MehdiChinoune** [comment]
Ping!

**Comment by jeremyd2019** [comment]
If you install the 'shared' headers for GMP, you cannot use the static GMP library (due to apis being defined dllimport).  With the 'static' headers, you *can* still use the shared GMP library (by virtue of the import thunks)

**Comment by jeremyd2019** [comment]
Oh, I see GMP also has exported data.  Those would require runtime pseudo-relocs for using the shared lib with the static headers, and would probably run into 32-bit range issues on 64-bit with a high imagebase.  I don't know what can be done about that though, given:
>    There's no attempt to support GMP built both static and DLL.  Doing so
   would mean applications would have to tell us which of the two is going
   to be used when linking, and that seems very tedious and error prone if
   using GMP by hand, and equally tedious from a package since autoconf and
   automake don't give much help.

**Comment by jeremyd2019** [comment]
> Oh, I see GMP also has exported data. If something used those, it would require runtime pseudo-relocs for using the shared lib with the static headers, and would probably run into 32-bit range issues on 64-bit with a high imagebase.

Nevermind, refptrs are involved in those that allows a full 64-bit relocation to be used.  So static headers should work fine with shared GMP, but not vice-versa

**Comment by MehdiChinoune** [comment]
Either we fix gmp shared library or disable it, It couldn't be linked to if the header files are from the static build (As @jeremyd2019 explained above)

**Comment by jeremyd2019** [comment]
That's the opposite of what I explained above.  You *can* link to the shared gmp library with the headers from the static build.  You *cannot* link to the static gmp library with the headers from the shared build.

As for mpfr, it attempts to decide how *it* is being built based on the gmp headers, rather than from its own configure script.  This is arguably wrong, except for the fact that the upstream developers already disclaimed all support for having one set of headers for both static and shared, so it's "by design".

**Pull request closed without merging**
