### PR TITLE
Update to latest version version including CVE fixes.

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I think this has already been done.  I'm not quite sure why github isn't showing any indication of that though.

**Comment by mati865** [comment]
This branch is out of date but yeah, GitHub should have detected the conflict here,

**Comment by JPeterMugaas** [comment]
What I see from git is expat 2.4.4, not 2.4.5.

**Comment by jeremyd2019** [comment]
f4bdac0e925d9b59851821dd41dbdbbc371a8b59

**Pull request closed without merging**
