### PR TITLE
arrow: Update to 13.0.0

### PR DESCRIPTION
**Pull request by raulcd**
I just released Arrow 13.0.0.

### CODE REVIEW

**Comment by raulcd** [comment]
we usually add the CI-long-timeout and extra memory, I think the error is related to that:
`  cc1plus.exe: out of memory allocating 253088 bytes` but I might be wrong.

**Comment by kou** [comment]
@raulcd Could you try removing `-DCMAKE_UNITY_BUILD=ON` for the following error?

https://github.com/msys2/MINGW-packages/actions/runs/5950387894/job/16148767448?pr=18242#step:11:953

```text
  cc1plus.exe: out of memory allocating 252848 bytes
```

It may reduce memory usage.

**Comment by raulcd** [comment]
I am not entirely sure why `gdal` failed on the `UCRT64`:
```
FAILED: frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5dataset.cpp.obj 
  D:\M\msys64\ucrt64\bin\g++.exe -DDONT_DEPRECATE_SPRINTF -DENABLE_HDF5_GLOBAL_LOCK -DGDAL_COMPILATION -DH5_BUILT_AS_DYNAMIC_LIB -DH5_BUILT_AS_STATIC_LIB -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DUSE_IMPORT_EXPORT -DWIN32 -IC:/_/B/src/gdal-3.7.1/apps -IC:/_/B/src/gdal-3.7.1/alg -IC:/_/B/src/gdal-3.7.1/gcore -IC:/_/B/src/build-UCRT64-shared/gcore -IC:/_/B/src/gdal-3.7.1/port -IC:/_/B/src/build-UCRT64-shared/port -IC:/_/B/src/gdal-3.7.1/ogr -IC:/_/B/src/gdal-3.7.1/ogr/ogrsf_frmts -IC:/_/B/src/gdal-3.7.1/frmts -isystem D:/M/msys64/ucrt64/include -march=nocona -msahf -mtune=generic -O2 -pipe -fvisibility=hidden -O3 -DNDEBUG -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wextra-semi -Wfloat-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wsuggest-override -fno-operator-names -Wzero-as-null-pointer-constant -MD -MT frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5dataset.cpp.obj -MF frmts\hdf5\CMakeFiles\gdal_HDF5.dir\hdf5dataset.cpp.obj.d -o frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5dataset.cpp.obj -c C:/_/B/src/gdal-3.7.1/frmts/hdf5/hdf5dataset.cpp
  In file included from D:/M/msys64/ucrt64/include/c++/13.2.0/ext/string_conversions.h:43,
                   from D:/M/msys64/ucrt64/include/c++/13.2.0/bits/basic_string.h:4097,
                   from D:/M/msys64/ucrt64/include/c++/13.2.0/string:54,
                   from C:/_/B/src/gdal-3.7.1/port/cpl_error.h:247,
                   from C:/_/B/src/gdal-3.7.1/port/cpl_string.h:35,
                   from C:/_/B/src/gdal-3.7.1/port/cpl_json.h:32,
                   from C:/_/B/src/gdal-3.7.1/frmts/hdf5/hdf5eosparser.h:35,
                   from C:/_/B/src/gdal-3.7.1/frmts/hdf5/hdf5dataset.h:35,
                   from C:/_/B/src/gdal-3.7.1/frmts/hdf5/hdf5dataset.cpp:35:
  D:/M/msys64/ucrt64/include/c++/13.2.0/cstdlib:79:15: fatal error: stdlib.h: No such file or directory
     79 | #include_next <stdlib.h>
        |               ^~~~~~~~~~
  compilation terminated.
  
  [546/1211] Building CXX object frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5imagedataset.cpp.obj
  FAILED: frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5imagedataset.cpp.obj 
  D:\M\msys64\ucrt64\bin\g++.exe -DDONT_DEPRECATE_SPRINTF -DENABLE_HDF5_GLOBAL_LOCK -DGDAL_COMPILATION -DH5_BUILT_AS_DYNAMIC_LIB -DH5_BUILT_AS_STATIC_LIB -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DUSE_IMPORT_EXPORT -DWIN32 -IC:/_/B/src/gdal-3.7.1/apps -IC:/_/B/src/gdal-3.7.1/alg -IC:/_/B/src/gdal-3.7.1/gcore -IC:/_/B/src/build-UCRT64-shared/gcore -IC:/_/B/src/gdal-3.7.1/port -IC:/_/B/src/build-UCRT64-shared/port -IC:/_/B/src/gdal-3.7.1/ogr -IC:/_/B/src/gdal-3.7.1/ogr/ogrsf_frmts -IC:/_/B/src/gdal-3.7.1/frmts -isystem D:/M/msys64/ucrt64/include -march=nocona -msahf -mtune=generic -O2 -pipe -fvisibility=hidden -O3 -DNDEBUG -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wextra-semi -Wfloat-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wsuggest-override -fno-operator-names -Wzero-as-null-pointer-constant -MD -MT frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5imagedataset.cpp.obj -MF frmts\hdf5\CMakeFiles\gdal_HDF5.dir\hdf5imagedataset.cpp.obj.d -o frmts/hdf5/CMakeFiles/gdal_HDF5.dir/hdf5imagedataset.cpp.obj -c C:/_/B/src/gdal-3.7.1/frmts/hdf5/hdf5imagedataset.cpp
  In file included from D:/M/msys64/ucrt64/include/c++/13.2.0/ext/string_conversions.h:43,
                   from D:/M/msys64/ucrt64/include/c++/13.2.0/bits/basic_string.h:4097,
                   from D:/M/msys64/ucrt64/include/c++/13.2.0/string:54,
                   from C:/_/B/src/gdal-3.7.1/port/cpl_error.h:247,
                   from C:/_/B/src/gdal-3.7.1/port/cpl_string.h:35,
                   from C:/_/B/src/gdal-3.7.1/frmts/hdf5/hdf5imagedataset.cpp:32:
  D:/M/msys64/ucrt64/include/c++/13.2.0/cstdlib:79:15: fatal error: stdlib.h: No such file or directory
     79 | #include_next <stdlib.h>
        |               ^~~~~~~~~~
  compilation terminated.
  ```

**Comment by raulcd** [comment]
I think we can re-run the `UCRT64` failure then.

**Comment by kou** [comment]
How about always removing `-DCMAKE_UNITY_BUILD=ON` for safety for now?
The current CI is green. Can we merge this?

**Pull request merged**
