### PR TITLE
scotch: Use split package for 32-bit and 64-bit indexing versions.

### PR DESCRIPTION
**Pull request by mmuetzel**
The two versions of the package got out of sync. Use a split package to make it easier to update both versions at the same time.

This also includes the changes from #10780.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Hmmm...
It looks like the CI doesn't like if split packages conflict with themselves.
The rules for `mingw-w64-scotch` and `mingw-w64-scotch-int64` were almost identical. So I figured that would be a prime candidate for a split package.
Feel free to close if this isn't a use case for a split package.

**Comment by MehdiChinoune** [comment]
Just put an empty `.ci-sequential` in mingw-w64-scotch directory.

**Comment by mmuetzel** [comment]
> Just put a file named `.ci-sequential` in mingw-w64-scotch directory.

Thanks! That helped.

**Comment by mmuetzel** [comment]
Oops. Something is wrong with those libraries. They don't export anything...

**Comment by mmuetzel** [comment]
I should have checked without `-D`. But the symbols were indeed not exported. (I guess that's also an issue with #10780.)
Should be fixed with the latest change.

**Pull request merged**
