### PR TITLE
calculix-ccx: add new package

### PR DESCRIPTION
**Pull request by 3rav**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Is MKL dependency hard-coded, I mean Couldn't Calculix-ccx be built against some open-source libraries like openblas,...

**Comment by MehdiChinoune** [comment]
On Debian/Ubuntu they build it against arpack, spooles and lapack packages https://packages.ubuntu.com/source/mantic/calculix-ccx

**Comment by MehdiChinoune** [comment]
I was able to build it locally without MKL/PARADISO.

**Comment by 3rav** [comment]
> I was able to build it locally without MKL/PARADISO.

Yes you can but:

image
from: https://twitter.com/f_langf/status/1488905077402255363

- spooles (quite old, unstable and very slow)
- PARDISO (Intel or Panua-Pardiso)
- PaStiX (currently, not the basic version, but a modified one https://github.com/msys2/MINGW-packages/pull/8018)

**Comment by MehdiChinoune** [comment]
Being fastest or modern doesn't change the fact thet It's proprietary, It's unfortunate but since we have an open-source alternative the It's the only way.

**Comment by MehdiChinoune** [comment]
I have pushed new changes to:
- remove MKL dependency.
- Make it possible to build against flang in the future.
- Dynamic linking.
- Some formatting (replace tabs with spaces, two spaces identitation)

**Comment by 3rav** [comment]
> I have pushed new changes to:
> 
> * remove MKL dependency.
> * Make it possible to build against flang in the future.
> * Dynamic linking.
> * Some formatting (replace tabs with spaces, two spaces identitation)

Thank you for the corrections, but in this version hardly anyone will want to use it

**Comment by 3rav** [comment]
> I have pushed new changes to:
> 
> * remove MKL dependency.
> * Make it possible to build against flang in the future.
> * Dynamic linking.
> * Some formatting (replace tabs with spaces, two spaces identitation)

Its usability would be significantly improved by the pastix4calculix solver, maybe you know how to fix the error related to python3?

https://github.com/msys2/MINGW-packages/pull/8018#issuecomment-785671957

**Comment by MehdiChinoune** [comment]
> Thank you for the corrections, but in this version hardly anyone will want to use it ("Dynamic linking" - makes its distribution and use much more difficult)

You know MSYS2 is not for that, It's like Homebrew, RPM ,Debian, Arch and any other packaging system. Apps and libraries uses and links dynamically against system libraries.
If you want to make it ditributable then this is the place for it. Also you could copy required dlls and package them along executables in an archive and then distribute it.

**Comment by 3rav** [comment]
> > Thank you for the corrections, but in this version hardly anyone will want to use it ("Dynamic linking" - makes its distribution and use much more difficult)
> 
> You know MSYS2 is not for that, It's like Homebrew, RPM ,Debian, Arch and any other packaging system. Apps and libraries uses and links dynamically against system libraries. If you want to make it ditributable then this is the place for it. Also you could copy required dlls and package them along executables in an archive and then distribute it.

This is currently how it is done, but I wanted to make it more automatic and for everyone to have insight into how the executable file is compiled. At least I've polished up PKGBUILD, which will make it easier for me to compile the executable in the future (especially the double precision version)

From main CalculiX page (see README_install):
http://www.dhondt.de/calculix_2.21_4win.zip

**Comment by aptKevin** [comment]
This PKGBUILD failed on latest msys2-mingw64 package. Which has the gcc version 14.1.0. 
From the build.log there are errors as followed :

> filtermain_backward.c:82:11: error: implicit declaration of function 'filtermatrix_'; did you mean 'filtermain'? [-Wimplicit-function-declaration]

> filtermain_backward.c:86:11: error: implicit declaration of function 'filter_backward_'; did you mean 'filtermain_backward'? [-Wimplicit-function-declaration]

> filtermain_forward.c:186:11: error: implicit declaration of function 'filter_forward_'; did you mean 'filter_forwardmt'? [-Wimplicit-function-declaration]

> external.c:138:21: error: initialization of 'lib_handler' {aka 'struct HINSTANCE__ **'} from incompatible pointer type 'HMODULE' {aka 'struct HINSTANCE__ *'} [-Wincompatible-pointer-types]

> external.c:144:22: error: passing argument 1 of 'GetProcAddress' from incompatible pointer type [-Wincompatible-pointer-types]

From the online document of porting to gcc 14([https://gcc.gnu.org/gcc-14/porting_to.html](https://gcc.gnu.org/gcc-14/porting_to.html)) these errors were due to the change in gcc14 which make certain warnings as errors now.

**Pull request merged**
