### PR TITLE
Openai deps

### PR DESCRIPTION
**Pull request by Schala**
Hope this won't break like the last one...

New:

- python-pytest-asyncio: tqdm checkdep

Updated:

- python-tqdm 4.54, check temporarily disabled

### CODE REVIEW

**Comment by Schala** [comment]
Ugh... why does it choke on that??

**Comment by lazka** [comment]
It's always best to create a new branch for each pull request.

**Comment by lazka** [comment]
But for that CI error: it will try to rebuild llvmlite because you changed it. Just don't touch llvmlite is probably the easiest fix :)

**Comment by Schala** [comment]
Alright. Well, consider this the last PR with a recycled branch lol

**Comment by Schala** [comment]
I'm just going to close this and rebranch

**Comment by lazka** [comment]
Thanks!

**Pull request closed without merging**
