### PR TITLE
jsoncpp: correct name of static library

### LINKED ISSUE #22584: jsoncpp pkgconfig file reports wrong libs for static builds since 1.9.6 update
### Description / Steps to reproduce the issue

When building an application which uses jsoncpp statically and linking using the output of `pkgconfig --static --libs jsoncpp`, linking will fail. This started happening since jsoncpp was updated to version 1.9.6. I am running into this issue with my game OceanPop, available [here](https://github.com/sharkwouter/oceanpop). Below is a smaller example that should reproduce it.

main.cpp:
```
#include <string>
#include <json/json.h>
#include <iostream>

int main(void)
{
  Json::Value data;
  Json::Reader reader;
  std::string text = "{\"message\":\"hello json\"}";
  
  reader.parse(text, data);
  std::cout << data.get("message", "Could not load json message") << "\n";
  
  return 0;
}
```
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10)

project(hello_json)

set(CMAKE_CXX_FLAGS "-static ${CMAKE_CXX_FLAGS}")

include(FindPkgConfig)
pkg_search_module(JSONCPP Required jsoncpp)

include_directories(${JSONCPP_INCLUDE_DIRS})
add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} ${JSONCPP_STATIC_LIBRARIES})
```

Put these in a directory, then run the following commands there:
```
mkdir build && cd build
cmake -G "MinGW Makefiles" ..
cmake --build .
```

### Expected behavior

As with jsoncpp version 1.9.5, I was expecting the build to link correctly and result in a working binary.

### Actual behavior

As seen in the failure of [this GitHub workflow](https://github.com/sharkwouter/oceanpop/actions/runs/11912612163/job/33196581768), building with jsoncpp version 1.9.6 results in the following error:
```
 [100%] Linking CXX executable oceanpop.exe
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ljsoncpp: No such file or directory
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ljsoncpp: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\oceanpop.dir\build.make:517: oceanpop.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:86: CMakeFiles/oceanpop.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2
```
This same code build just fine before the update.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### Are you willing to submit a PR?

I have contributed before, but I don't know if I'll have time to fix this myself.

### PR DESCRIPTION
**Pull request by mmuetzel**
Fixes #22584.

### CODE REVIEW

**Review by sharkwouter — APPROVED** [review]
This is the fix I needed, thanks!

**Comment by sharkwouter** [comment]
It seems this change was made in this PR to enable Clang to work: https://github.com/open-source-parsers/jsoncpp/pull/1480

Maybe upstream has an idea on how to make this condition only activate for MSVC and Clang instead of every WIN32 build.

**Comment by mmuetzel** [comment]
A better condition for upstream would probably be `MSVC OR ("${CMAKE_C_SIMULATE_ID}" STREQUAL "MSVC")`. But MSYS2 always targets MinGW (not MSVC). So, the second part of that condition would never be true when packaging for MSYS2.

**Comment by mmuetzel** [comment]
Thank you for testing and for digging up that PR.

I created a PR for upstream with a change that should work with any compiler when targeting MSVC: https://github.com/open-source-parsers/jsoncpp/pull/1579

**Pull request merged**
