### PR TITLE
fix alure 1 build and move alure2 it's own package

### LINKED ISSUE #8738: recent update to the package have appended the number 2 to headers and libraries causing build errors in my other [alure]
### **description : recent update to the package have appended the number 2 to headers and libraries causing build errors in my projects**

```
Files:

    /mingw64/bin/libalure2.dll
    /mingw64/include/AL/alure2-alext.h
    /mingw64/include/AL/alure2-aliases.h
    /mingw64/include/AL/alure2-typeviews.h
    /mingw64/include/AL/alure2.h
    /mingw64/lib/cmake/Alure2/Alure2Config-noconfig.cmake
    /mingw64/lib/cmake/Alure2/Alure2Config.cmake
    /mingw64/lib/libalure2.dll.a
    /mingw64/lib/libalure2_s.a
    /mingw64/share/licenses/alure/LICENSE
```

### PR DESCRIPTION
**Pull request by fundies**
fixes #8738

### CODE REVIEW

**Comment by Biswa96** [comment]
Why is ninja replaced with make?

**Comment by jeremyd2019** [comment]
Does the alure package require an 'epoch' in this case?  Or is the downgrade acceptable

**Comment by Biswa96** [comment]
Do we? The pkgver seems to be same.

**Comment by jeremyd2019** [comment]
Nevermind.  🤦

**Comment by fundies** [comment]
> Why is ninja replaced with make?
I only reverted the pkgbuild to before it was changed to build alure2 it originally called make

**Comment by fundies** [comment]
> Does the alure package require an 'epoch' in this case? Or is the downgrade acceptable

I bumped alure to PKG release 4 but 3 was an invalid release and I just set alure2 pkgbuild to 1 because it'd be the first time the package was named properly

**Comment by lazka** [comment]
perfect, thanks!

**Pull request merged**
