### PR TITLE
poppler: Add arm64 support

### PR DESCRIPTION
**Pull request by hmartinez82**
Depends on #12324

### CODE REVIEW

**Comment by lazka** [comment]
failed:

```
2022-07-31T10:09:14.0716585Z C:\msys64\clangarm64\bin\clang++.exe -DWIN32_LEAN_AND_MEAN -D_WIN32_IE=0x0500 -D__USE_MINGW_ANSI_STDIO=1 -Dpoppler_EXPORTS -IC:/M/mingw-w64-poppler/src/poppler-22.01.0 -IC:/M/mingw-w64-poppler/src/poppler-22.01.0/fofi -IC:/M/mingw-w64-poppler/src/poppler-22.01.0/goo -IC:/M/mingw-w64-poppler/src/poppler-22.01.0/poppler -IC:/M/mingw-w64-poppler/src/build-aarch64-w64-mingw32 -IC:/M/mingw-w64-poppler/src/build-aarch64-w64-mingw32/poppler -isystem C:/msys64/clangarm64/include -isystem C:/msys64/clangarm64/include/freetype2 -isystem C:/msys64/clangarm64/include/openjpeg-2.5 -isystem C:/msys64/clangarm64/include/nss3 -isystem C:/msys64/clangarm64/include/nspr -Wall -Wextra -Wpedantic -Wno-unused-parameter -Wcast-align -Wformat-security -Wframe-larger-than=65536 -Wmissing-format-attribute -Wnon-virtual-dtor -Woverloaded-virtual -Wmissing-declarations -Wundef -Wzero-as-null-pointer-constant -Wshadow -Wweak-vtables -fno-exceptions -fno-check-new -fno-common -D_DEFAULT_SOURCE -O2 -DNDEBUG -O2 -pipe -Wno-deprecated-declarations -Wno-ignored-attributes -fvisibility=hidden -fvisibility-inlines-hidden -std=c++17 -MD -MT CMakeFiles/poppler.dir/fofi/FoFiType1C.cc.obj -MF CMakeFiles\poppler.dir\fofi\FoFiType1C.cc.obj.d -o CMakeFiles/poppler.dir/fofi/FoFiType1C.cc.obj -c C:/M/mingw-w64-poppler/src/poppler-22.01.0/fofi/FoFiType1C.cc
2022-07-31T10:09:14.0832631Z C:/M/mingw-w64-poppler/src/poppler-22.01.0/fofi/FoFiType1C.cc:2649:27: error: expected unqualified-id
2022-07-31T10:09:14.6693337Z         if (unlikely(std::isinf(ops[i].num))) {
2022-07-31T10:09:14.6803222Z 
2022-07-31T10:09:14.6960935Z                           ^
2022-07-31T10:09:14.7116076Z 
2022-07-31T10:09:14.7119387Z C:/msys64/clangarm64/include/math.h:509:18: note: expanded from macro 'isinf'
2022-07-31T10:09:14.7120887Z 
2022-07-31T10:09:14.7121799Z #define isinf(x) (fpclassify(x) == FP_INFINITE)
2022-07-31T10:09:14.7122870Z 
2022-07-31T10:09:14.7123394Z                  ^
2022-07-31T10:09:14.7124169Z 
2022-07-31T10:09:14.7124761Z 1 error generated.
```

**Comment by hmartinez82** [comment]
@lazka What's the `makepkg-mingw` line used in the CI ? Locally I'm able to build with `makepkg-mingw --cleanbuild --syncdeps --force --noconfirm` . I'm already investigating the unit tests that are failing, but the compilation itself only has a few warnings.

**Comment by lazka** [comment]
https://github.com/msys2/msys2-autobuild/blob/5f53dab6de6962e9531dbeb7e52b683d597de64d/autobuild.py#L573

**Comment by hmartinez82** [comment]
@lazka I'll try with those specific build switches. I looked at the failing unit tests: the main issue is that they are asking for a bunch of test data, mainly PDFs that are not there. The same unit tests are failing even in MINGW64 builds. Right now I got it working in my Surface Pro X 
Screenshot 2022-07-31 121530

**Comment by lazka** [comment]
Ok, let's try again then. Maybe it was a unlucky.

Note: Another difference to CI is that it only has the minimal set of packages installed.

**Comment by hmartinez82** [comment]
@lazka We could just do this instead: https://github.com/msys2/MINGW-packages/pull/12376 :)

**Pull request merged**
