### PR TITLE
glib2: Update to 2.66.6

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by lazka** [comment]
re cflags, alternative is to set the buildtype like in gtk3

**Comment by Biswa96** [comment]
Apology Sir, I can not understand that. According to the `meson.build` file, the `G_DISABLE_CAST_CHECKS` cflag is added when optimization option is enable, not the build type 🤔 ALthough that cflag is not so important, should I remove it?

**Comment by lazka** [comment]
optimization is set according to build type. I'd just copy what gtk3 does atm. I think it's a good idea.

**Comment by lazka** [comment]
ah, that buildtype thing was already in place. never mind then.

**Comment by Biswa96** [comment]
> that buildtype thing was already in place.

Though your comment gave me a nudge. I will add thosse buildtype option in the new gtkmm4 PR.

**Comment by lazka** [comment]
Note that gtk and glib are the only projects I know that change the build config according to buildtype. But it can't hurt, so sure.

**Comment by Biswa96** [comment]
Interesting, if I add release build type in glibmm268 (in my other PR) the project is built three times (build, check, install). SO, scratch my previous idea.

**Pull request merged**
