### PR TITLE
libgit2: Update to 1.6.3

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
pygit2 doesn't support libgit2 yet.
I have reported that anou 10 days ago with no response.

**Comment by lazka** [comment]
Ah, thanks

**Comment by lazka** [comment]
let's wait a bit then..

**Comment by lazka** [comment]
Arch solved it this way: https://github.com/archlinux/svntogit-community/commit/3ec9d294178156aba941574a762a641b289e13bd

**Comment by MehdiChinoune** [comment]
Why not taking the opportunity and pass `-DCMAKE_SHARED_LIBRARY_NAME_WITH_VERSION=ON` to cmake.

**Comment by lazka** [comment]
> Why not taking the opportunity and pass `-DCMAKE_SHARED_LIBRARY_NAME_WITH_VERSION=ON` to cmake.

ok, I'll try

**Comment by lazka** [comment]
should be ready now

**Pull request merged**
