### PR TITLE
cmake: default to ninja

### PR DESCRIPTION
**Pull request by lazka**
It defaults to msvc/nmake otherwise which in MSYS2 is never a good default imo.

### CODE REVIEW

**Comment by lazka** [comment]
@orgads @MehdiChinoune any thoughts on this?

**Comment by 1480c1** [comment]
Would be nice

**Comment by orgads** [comment]
+1

**Comment by lazka** [comment]
ok, let's try this then. I'd still advice everyone to explicitly pass a generator for your automated builds.

**Comment by 1480c1** [comment]
Wait, I just realized cmake doesn't have a dependency set for ninja, is that okay?

**Comment by lazka** [comment]
Not sure. You mean for convenience?

**Comment by 1480c1** [comment]
Yeah, I mean, I guess it's the same situation without the patch because msvc isn't guaranteed to be present, so the default would fail in most cases

**Comment by lazka** [comment]
yeah, probably a good idea.

**Pull request merged**
