### PR TITLE
nspr: Add CLANGARM64

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by lazka** [comment]
thanks!

**Comment by hmartinez82** [comment]
@lazka I saw that you tried to build NSS already. That's my next attempt. Right now, nss is failing with a wrong define in ìntrin.h` it's pointing to x86_64 intrin instead of arm64 :-/  I'll investigate

**Comment by Biswa96** [comment]
@hmartinez82 shouldn't `--enable-64bit` option be also enabled for aarch64? Source https://archlinuxarm.org/packages/armv7h/nspr/files/PKGBUILD

**Comment by hmartinez82** [comment]
@Biswa96 I thought so too originally, but it's automatically done internally for aarch64 at https://hg.mozilla.org/projects/nspr/file/tip/configure#l7065

**Pull request merged**
