### PR TITLE
ogre3d: Fix samples plugin not exporting symbols to be loaded by SampleBrowser

### PR DESCRIPTION
**Pull request by hmartinez82**
image

### CODE REVIEW

**Comment by mmuetzel** [comment]
While you are at it, you could also remove `${MINGW_PACKAGE_PREFIX}-pugixml` from `depends`. (See @MehdiChinoune's comment in the other commit.)

**Comment by hmartinez82** [comment]
@mmuetzel Ok, should I keep it in makedepends and optdepends?

**Comment by MehdiChinoune** [comment]
> @mmuetzel Ok, should I keep it in makedepends and optdepends?

Yes, and Please add `XML Converter` in front of `pugixml` in `optdepends`
```
            "${MINGW_PACKAGE_PREFIX}-pugixml: XML converter"
```

**Comment by mmuetzel** [comment]
The libraries are exporting a lot less symbols now. (But I guess that was the point of this change.)
The package grokker suggests to rebuild the following packages:
```
mingw-w64-ogre3d
mingw-w64-ogitor-git
mingw-w64-opencv
```

I downloaded and installed the MINGW64 artifact from this PR. But it doesn't seem to be working for me. If I try to run `SampleBrowser.exe`, I see the following pop up window:
image

Am I doing something wrong?

**Comment by hmartinez82** [comment]
@MehdiChinoune I need your input here. In the last version of Ogre3D, those dlls (the renderers) were in the ${MINGW_PREFIX}/bin folder, correct?

**Comment by hmartinez82** [comment]
Could this line `-DOGRE_PLUGINS_PATH=lib/OGRE \` be the culprit?

**Comment by lazka** [comment]
oh, I guess I merged too early, sry. what should I do?

**Comment by lazka** [comment]
> The package grokker suggests to rebuild the following packages:

that could be because it's comparing to 1.12.6 in the repo

**Comment by mmuetzel** [comment]
I haven't tested with the package in staging before this PR. So, this might have been an issue already before. Merging this PR might not have made anything worse than it was anyway.

**Comment by hmartinez82** [comment]
@mmuetzelI @lazka and @MehdiChinoune I am able to repro , manually copying those Renderer dlls to the bin folder solves the issue.

The screenshot is running the sample browser from the build bin folder, that's why I didn't notice this issue. Should I remove the `-DOGRE_PLUGINS_PATH=lib/OGRE` line and give it a try?

**Comment by mmuetzel** [comment]
> Should I remove the `-DOGRE_PLUGINS_PATH=lib/OGRE` line and give it a try?

Either that, or check why it looks for the plugins in the bin folder even though it was configured with that flag. (Your proposal might be the easier one of those options though.)

**Comment by MehdiChinoune** [comment]
> @mmuetzelI @lazka and @MehdiChinoune I am able to repro , manually copying those Renderer dlls to the bin folder solves the issue.
> 
> The screenshot is running the sample browser from the build bin folder, that's why I didn't notice this issue. Should I remove the `-DOGRE_PLUGINS_PATH=lib/OGRE` line and give it a try?

You will end up with import libraries installed in bin.

I think we should create a patch to install runtime in bin and library/archive in lib.

**Comment by MehdiChinoune** [comment]
see: #12595

**Comment by mmuetzel** [comment]
Still failed to build in staging. This time with:
https://github.com/msys2-arm/msys2-autobuild/runs/7875552919?check_suite_focus=true#step:10:14172
```
  ==> Installing missing dependencies...
  resolving dependencies...
  warning: cannot resolve "mingw-w64-clang-aarch64-openvr", a dependency of "mingw-w64-clang-aarch64-bullet"
  :: The following package cannot be upgraded due to unresolvable dependencies:
        mingw-w64-clang-aarch64-bullet
  
  :: Do you want to skip the above package for this upgrade? [Y/n] 
```

What does that mean? `mingw-w64-clang-aarch64-openvr` *is* in the repos afaict:
https://repo.msys2.org/mingw/clangarm64/mingw-w64-clang-aarch64-opencv-4.5.5-4-any.pkg.tar.zst

Maybe, some kind of dependency cycle that needs to be broken differently?

**Comment by mmuetzel** [comment]
Edit: Maybe fixed by something like https://github.com/msys2/msys2-autobuild/pull/59 ?

**Pull request merged**
