### PR TITLE
wxwidgets3.2: Update to 3.2.2.1

### PR DESCRIPTION
**Pull request by stahta01**

### CODE REVIEW

**Comment by mmuetzel** [comment]
Oops. That might have broken building packages that depend on wxWidgets.
E.g., https://pipelines.actions.githubusercontent.com/serviceHosts/5a6e1531-23a3-444b-906f-2fd260a6a90d/_apis/pipelines/1/runs/10553/signedlogcontent/20?urlExpires=2023-02-19T14%3A35%3A22.8172240Z&urlSigningMethod=HMACV1&urlSignature=uDXkjdjTuxjZWcbUn3jPsnK8zHo9iUXfehcsy1VRRJE%3D: 
```2023-02-19T14:18:57.3790794Z CMake Error at D:/a/msys64/clang32/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
2023-02-19T14:18:57.3791609Z   Could NOT find wxWidgets: Found unsuitable version "3.2.2", but required is
2023-02-19T14:18:57.3792025Z   at least "3.2.2.1" (found
2023-02-19T14:18:57.3793215Z   -LD:/a/msys64/clang32/lib;;;-pipe;-Wl,--no-seh;-Wl,--large-address-aware;-Wl,--subsystem,windows;-mwindows;-lwx_mswu_gl-3.2;-lwx_mswu_aui-3.2;-lwx_mswu_html-3.2;-lwx_mswu_core-3.2;-lwx_baseu_net-3.2;-lwx_baseu-3.2;-lwx_mswu_propgrid-3.2;-lwx_baseu_xml-3.2;-lwx_mswu_stc-3.2;-lwx_mswu_richtext-3.2)
2023-02-19T14:18:57.3793953Z Call Stack (most recent call first):
2023-02-19T14:18:57.3794594Z   D:/a/msys64/clang32/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
2023-02-19T14:18:57.3795149Z -- Configuring incomplete, errors occurred!
2023-02-19T14:18:57.3795751Z   CMakeModules/FindwxWidgets.cmake:951 (find_package_handle_standard_args)
2023-02-19T14:18:57.3796303Z See also "C:/M/mingw-w64-kicad/src/build-CLANG32/CMakeFiles/CMakeOutput.log".
2023-02-19T14:18:57.3796791Z   CMakeLists.txt:891 (find_package)
2023-02-19T14:18:57.3797260Z See also "C:/M/mingw-w64-kicad/src/build-CLANG32/CMakeFiles/CMakeError.log".
2023-02-19T14:18:57.3797602Z 
2023-02-19T14:18:57.3797662Z 
2023-02-19T14:18:57.4438474Z ==> ERROR: A failure occurred in build().
```

There might be some places that don't handle the fourth number in the version string...

**Comment by mmuetzel** [comment]
Nevermind. It's probably just kicad that needs a patch.

**Comment by asmwarrior** [comment]
Hi, @stahta01 since the [wxWidgets 3.2.3 Released - wxWidgets](https://wxwidgets.org/news/2023/10/wxwidgets-3.2.3-released/), can you help to update the msys2 packags for this release? Thanks.

**Comment by stahta01** [comment]
> Hi, @stahta01 since the [wxWidgets 3.2.3 Released - wxWidgets](https://wxwidgets.org/news/2023/10/wxwidgets-3.2.3-released/), can you help to update the msys2 packags for this release? Thanks.

I will see if it builds okay locally on my PC; It likely should.

Tim S.

**Comment by asmwarrior** [comment]
Hi, @stahta01 , thanks for the update for the wx library version 3.2.3. I see the 3.2.4 version arrived yesterday. Can you update it to the latest 3.2.4 version?

[wxWidgets 3.2.4 Released - wxWidgets](https://wxwidgets.org/news/2023/11/wxwidgets-3.2.4-released/)

Thanks.

**Comment by stahta01** [comment]
> Hi, @stahta01 , thanks for the update for the wx library version 3.2.3. I see the 3.2.4 version arrived yesterday. Can you update it to the latest 3.2.4 version?
> 
> [wxWidgets 3.2.4 Released - wxWidgets](https://wxwidgets.org/news/2023/11/wxwidgets-3.2.4-released/)
> 
> Thanks.

I am trying to build wx 3.2.4 locally now. But, I an building KiCad already so it will be several hours before wxWidgets will finish.

Tim S.

**Comment by asmwarrior** [comment]
That's great! Thanks.

**Comment by asmwarrior** [comment]
Hi, Tim, wxWidgets 3.2.5 is released, can you help to update this package in msys2? Thanks.

**Comment by stahta01** [comment]
Trying to build it now; no idea if the GCC changing to 14.1 will make it harder to build.

**Pull request merged**
