### PR TITLE
binutils: Install config.h for bfd

### PR DESCRIPTION
**Pull request by orgads**
bfd.h is useless without it.

### CODE REVIEW

**Comment by lazka** [comment]
hm, config.h should never ever be installed. Can you go into more detail re what is broken for you?

**Comment by orgads** [comment]
I'm using bfd.h for reading symbols on backtrace logging. If I include bfd.h it fails because config.h must be included before it. So either there's no reason to install bfd.h, or config.h should be installed along with it.

**Comment by orgads** [comment]
From bfd.h:

```
/* PR 14072: Ensure that config.h is included first.  */
#if !defined PACKAGE && !defined PACKAGE_VERSION
#error config.h must be included before this header
#endif
```

**Comment by lazka** [comment]
The developer suggests defining PACKAGE: https://sourceware.org/bugzilla/show_bug.cgi?id=14243#c10

(imo this is all super broken..)

**Comment by orgads** [comment]
Accepted. Thanks.

**Comment by lazka** [comment]
Thanks for testing it. I guess if there are still problems we can accept your patch, given the the weird upstream stance on this.

**Pull request closed without merging**
