### PR TITLE
fix qt5-static for CMake 3.17

### PR DESCRIPTION
**Pull request by Optiligence**
CMake 3.17 stops finding dll files for additional libraries trying to be found by Qt
replace expanding the list with the workaround that will be in 5.14.2 anyway

### CODE REVIEW

**Comment by Optiligence** [comment]
@Alexpux something holding up the repo update? 

I’m waiting for this to fix my CI…

**Comment by Alexpux** [comment]
@Optiligence I will wait 5.14.2. Don’t have time to rebuild qt5 often

**Comment by Alexpux** [comment]
Also we now on carantine so maybe package updates will be once in two - three weeks

**Comment by Optiligence** [comment]
Sad to hear. That makes this PR also kinda pointless.

**Comment by Optiligence** [comment]
it’s not even only qt5-static that’s broken, the code runs for dynamic qt too…
i.e. non already configured CMake builds of qt projects are broken atm

**Pull request merged**
