### PR TITLE
new package: mtn

### PR DESCRIPTION
**Pull request by wahibre**
CLI movie thumbnail generator

https://gitlab.com/movie_thumbnailer/mtn/-/wikis/home

### CODE REVIEW

**Comment by lazka** [comment]
you need to install into the right prefix /your packages contains usses /usr/local) and hard coding "/mingw64" is wrong when building a 32 bit package

**Comment by wahibre** [comment]
Trying to find marco which expands to only mingw32/64. Existing packages dont use any except ${pkgdir} and MINGW_PREFIX looks wrong too.

Please, what is the right replacement for "${MINGW_PREFIX}" in build section..?

```
mingw32-make DESTDIR="${pkgdir}/" PREFIX="${MINGW_PREFIX}" install
```

**Comment by wahibre** [comment]
I started from scratch and fixed it.  
Now it works

**Comment by wahibre** [comment]
Package still not in repo. Is there something I need to fix?

**Comment by lazka** [comment]
it failed to build, I've restarted it here: https://github.com/msys2/msys2-autobuild/runs/1569711439?check_suite_focus=true

**Comment by lazka** [comment]
looks like it went through now. thanks for notifying us

**Pull request merged**
