### PR TITLE
[new-package] emscripten 3.1.39

### PR DESCRIPTION
**Pull request by MehdiChinoune**
based on ArchLinux recipe.
Not tested.

### CODE REVIEW

**Comment by podsvirov** [comment]
@MehdiChinoune, thanks for efforts!
Currently I've [checking more ports](https://github.com/podsvirov/MINGW-packages/actions/runs/5036379627) and after building completed will test this package to build something for web.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune, thanks for efforts! Currently I've [checking more ports](https://github.com/podsvirov/MINGW-packages/actions/runs/5036379627) and after building completed will test this package to build something for web.

I don't think we need i686 and mingw64 for new ports, We are trying to push people for UCRT environments.

**Comment by podsvirov** [comment]
> I don't think we need i686 and mingw64 for new ports, We are trying to push people for UCRT environments.

I'll just say the all ports ('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32') were built without errors.

**Comment by MehdiChinoune** [comment]
It's not working properly.
It generates js script from c/c++, but the generated html doesn't show what It's supposed to show.
I am going to merge it, hoping for someone to debug it and see what's wrong.

**Comment by podsvirov** [comment]
Yes, it doesn't work from scratch, but you're right - we need to merge for the next improvements.
How about applying the suggestion I started?

**Comment by MehdiChinoune** [comment]
> How about applying the suggestion I started?

What suggestion?

**Comment by podsvirov** [comment]
emscripten-fix-source-url

> I suggest change source url from `git+https://github.com/kripken/emscripten#tag=$pkgver` to `git+https://github.com/emscripten-core/emscripten.git#tag=$pkgver` because https://github.com/kripken/emscripten is just redirection to https://github.com/emscripten-core/emscripten.

**Comment by MehdiChinoune** [comment]
You know what `pending` means, you haven't submitted your review!

**Comment by podsvirov** [comment]
You use `.git` suffix for `llvm` and `binaryen` repository url, but not for `emscripten`. Please add `.git` suffix for `emscripten` (`emscripten.git`).

**Pull request merged**
