### PR TITLE
libsignal-protocol-c: rebuild

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by Biswa96** [comment]
skr-url may need a simple pkgrel bump to trigger msys2-autobuild.

**Comment by jeremyd2019** [comment]
Any idea what the issue was (that only appeared on autobuild and not in CI checks)?

**Comment by lazka** [comment]
my current guess is cmake tends to find msys libm if it is installed.

**Comment by lazka** [comment]
but that's also installed here.. so no idea.

**Pull request merged**
