### PR TITLE
mingw-w64-mesa: Check driconf feature requirements

### PR DESCRIPTION
**Pull request by pal1000**
Ref: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12158

Also ${MINGW_PACKAGE_PREFIX}-pkg-config is part of ${MINGW_PACKAGE_PREFIX}-toolchain so don't bother installing it.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
> Also ${MINGW_PACKAGE_PREFIX}-pkg-config is part of ${MINGW_PACKAGE_PREFIX}-toolchain so don't bother installing it.

@lazka how does this fit with your plans for makedepends/toolchains?

**Comment by lazka** [comment]
yes, toolchain is going away in CI

**Comment by raedrizqie** [comment]
> yes, toolchain is going away in CI

can we just use msys's pkgconf instead? ..and add pkgconf in msys base?

**Comment by lazka** [comment]
> can we just use msys's pkgconf instead? ..and add pkgconf in msys base?

That's not compatible. We could make meson depend on pkg-config, since one could argue that it's not very useful without it.

**Pull request merged**
