### PR TITLE
octave: Fix build against Qt6 6.7

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Still segfaults
reproducer:
```
$ octave --gui
```
execute:
```
$ figure()
```
@mmuetzel

### CODE REVIEW

**Comment by mmuetzel** [comment]
Thanks for looking into this.
This probably is good enough as a workaround to get Octave to build again. But the actual issue probably needs to be fixed in Qt 6.7.

The segfault is new since the update to Qt 6.7. It still worked with Qt 6.6. 
So, I'd guess that probably also needs to be fixed in Qt.

For the time being, we could probably revert to building Octave with Qt5.

**Comment by MehdiChinoune** [comment]
> The segfault is new since the update to Qt 6.7. It still worked with Qt 6.6. So, I'd guess that probably also needs to be fixed in Qt.

There is no evidence that the segfault comes from Qt6, maybe octave is using a Qt function a wrong way that was exposed only with Qt6 6.7.0. Someone has to build octave in debug mode and investigate the segfault (qt6-base-debug is available).

> For the time being, we could probably revert to building Octave with Qt5.

I agree on that.

**Comment by mmuetzel** [comment]
The following change to the Qt6 header avoids the build issue of Octave for me, too. And it might avoid similar issues with other projects:
``` diff
$ diff -urN qopengl.h.orig qopengl.h
--- qopengl.h.orig      2024-04-05 05:45:51.000000000 +0200
+++ qopengl.h   2024-04-07 11:25:06.979436100 +0200
@@ -8,21 +8,6 @@

 #ifndef QT_NO_OPENGL

-// On Windows we need to ensure that APIENTRY and WINGDIAPI are defined before
-// we can include gl.h. But we do not want to include <windows.h> in this public
-// Qt header, as it pollutes the global namespace with macros.
-#if defined(Q_OS_WIN)
-# ifndef APIENTRY
-#  define APIENTRY __stdcall
-#  define Q_UNDEF_APIENTRY
-# endif // APIENTRY
-# ifndef WINGDIAPI
-#  define WINGDIAPI __declspec(dllimport)
-#  define Q_UNDEF_WINGDIAPI
-# endif // WINGDIAPI
-# define QT_APIENTRY __stdcall
-#endif
-
 // Note: Apple is a "controlled platform" for OpenGL ABI so we
 // use the system provided headers there. Controlled means that the
 // headers always match the actual driver implementation so there
@@ -107,6 +92,21 @@
 #  include <OpenGL/gl3.h>
 #  include <OpenGL/glext.h>
 # else
+// On Windows we need to ensure that APIENTRY and WINGDIAPI are defined before
+// we can include gl.h. But we do not want to include <windows.h> in this public
+// Qt header, as it pollutes the global namespace with macros.
+#  if defined(Q_OS_WIN)
+#   ifndef APIENTRY
+#    define APIENTRY __stdcall
+#    define Q_UNDEF_APIENTRY
+#   endif // APIENTRY
+#   ifndef WINGDIAPI
+#    define WINGDIAPI __declspec(dllimport)
+#    define Q_UNDEF_WINGDIAPI
+#   endif // WINGDIAPI
+#   define QT_APIENTRY __stdcall
+#  endif
+
 #  define GL_GLEXT_LEGACY // Prevents GL/gl.h from #including system glext.h
 // Some Khronos headers use the ext proto guard in the standard headers as well,
 // which is bad. Work it around, but avoid spilling over to the ext header.
@@ -117,6 +117,16 @@
 #  else
 #   include <GL/gl.h>
 #  endif
+
+#  ifdef Q_UNDEF_WINGDIAPI
+#   undef WINGDIAPI
+#   undef Q_UNDEF_WINGDIAPI
+#  endif
+#  ifdef Q_UNDEF_APIENTRY
+#   undef APIENTRY
+#   undef Q_UNDEF_APIENTRY
+#  endif
+
 #  include <QtGui/qopenglext.h>
 # endif
 #endif // !QT_CONFIG(opengles2)
@@ -281,15 +291,6 @@

 QT_END_NAMESPACE

-#ifdef Q_UNDEF_WINGDIAPI
-# undef WINGDIAPI
-# undef Q_UNDEF_WINGDIAPI
-#endif
-#ifdef Q_UNDEF_APIENTRY
-# undef APIENTRY
-# undef Q_UNDEF_APIENTRY
-#endif
-
 #endif // QT_NO_OPENGL

 #endif // QOPENGL_H
```

> There is no evidence that the segfault comes from Qt6, maybe octave is using a Qt function a wrong way that was exposed only with Qt6 6.7.0. Someone has to build octave in debug mode and investigate the segfault (qt6-base-debug is available).

I agree. There is no evidence (yet) for that. But there is also no evidence (yet) for the issue being in Octave's sources.
At the moment, we can only guess. And that is what I wanted to express.

**Comment by mmuetzel** [comment]
Backtrace from the crash at `figure()`:
```
QOpenGLContext::functions (this=0x0) at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/gui/kernel/qopenglcontext.cpp:517
warning: 517    C:/M/B/src/qtbase-everywhere-src-6.7.0/src/gui/kernel/qopenglcontext.cpp: No such file or directory
(gdb) bt
#0  QOpenGLContext::functions (this=0x0) at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/gui/kernel/qopenglcontext.cpp:517
#1  0x00007ff904622126 in QOpenGLWidgetPrivate::invalidateFboAfterPainting (this=this@entry=0x2631717d850)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/openglwidgets/qopenglwidget.cpp:1014
#2  0x00007ff904623478 in QOpenGLWidgetPrivate::render (this=0x2631717d850)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/openglwidgets/qopenglwidget.cpp:977
#3  0x00007ff871f92680 in QWidget::event (this=0x26311218eb0, event=0x62aedfb190)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:9402
#4  0x00007ff871f459c1 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x26311218eb0, e=0x62aedfb190)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:3287
#5  0x00007ff871f4ed65 in QApplication::notify (this=this@entry=0x2628e97e2a0, receiver=<optimized out>, e=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:3049
#6  0x00007ff802a04203 in octave::octave_qapplication::notify (this=0x2628e97e2a0, receiver=<optimized out>, ev=<optimized out>)
    at ../libgui/src/octave-qobject.cc:150
#7  0x00007ff873ab9938 in QCoreApplication::notifyInternal2 (event=0x62aedfb190, receiver=0x26311218eb0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1134
#8  QCoreApplication::sendSpontaneousEvent (receiver=receiver@entry=0x26311218eb0, event=event@entry=0x62aedfb190)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1589
#9  0x00007ff871f899ca in QWidgetPrivate::sendPaintEvent (this=this@entry=0x2631717d850, toBePainted=...)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:5647
#10 0x00007ff904622e8a in QOpenGLWidget::resizeEvent (this=<optimized out>, e=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/openglwidgets/qopenglwidget.cpp:1511
#11 0x00007ff871f92d27 in QWidget::event (this=0x26311218eb0, event=0x62aedfb5e0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:9192
#12 0x00007ff871f459c1 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x26311218eb0, e=0x62aedfb5e0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:3287
#13 0x00007ff871f4ed65 in QApplication::notify (this=this@entry=0x2628e97e2a0, receiver=<optimized out>, e=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:3049
#14 0x00007ff802a04203 in octave::octave_qapplication::notify (this=0x2628e97e2a0, receiver=<optimized out>, ev=<optimized out>)
    at ../libgui/src/octave-qobject.cc:150
#15 0x00007ff873ab97b8 in QCoreApplication::notifyInternal2 (event=0x62aedfb5e0, receiver=0x26311218eb0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1134
#16 QCoreApplication::sendEvent (receiver=receiver@entry=0x26311218eb0, event=event@entry=0x62aedfb5e0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1575
#17 0x00007ff871f898e3 in QWidgetPrivate::sendPendingMoveAndResizeEvents (this=this@entry=0x2631717d850, recursive=recursive@entry=false,
    disableUpdates=<optimized out>, disableUpdates@entry=false) at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8032
#18 0x00007ff871f91c65 in QWidgetPrivate::show_helper (this=0x2631717d850)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8083
#19 0x00007ff871f91f9d in QWidgetPrivate::show_recursive (this=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8013
#20 0x00007ff871f91741 in QWidgetPrivate::showChildren (this=<optimized out>, spontaneous=false)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8521
#21 0x00007ff871f91c82 in QWidgetPrivate::show_helper (this=this@entry=0x26309ca3d60)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8089
#22 0x00007ff871f90ff4 in QWidgetPrivate::setVisible (this=0x26309ca3d60, visible=visible@entry=true)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8440
--Type <RET> for more, q to quit, c to continue without paging--c
#23 0x00007ff871f917b6 in QWidgetPrivate::showChildren (this=<optimized out>, spontaneous=false)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8523
#24 0x00007ff871f91c82 in QWidgetPrivate::show_helper (this=this@entry=0x26310a7e7b0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8089
#25 0x00007ff871f90ff4 in QWidgetPrivate::setVisible (this=0x26310a7e7b0, visible=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:8440
#26 0x00007ff873af22b1 in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=0x26311953de0, this=0x0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qobjectdefs_impl.h:469
#27 QMetaCallEvent::placeMetaCall (this=0x263171473f0, object=0x26311953de0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qobject.cpp:650
#28 0x00007ff873af7b66 in QObject::event (this=this@entry=0x26311953de0, e=e@entry=0x263171473f0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qobject.cpp:1446
#29 0x00007ff871f925f1 in QWidget::event (this=this@entry=0x26311953de0, event=event@entry=0x263171473f0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qwidget.cpp:9461
#30 0x00007ff8720a6734 in QMainWindow::event (this=this@entry=0x26311953de0, event=event@entry=0x263171473f0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/widgets/qmainwindow.cpp:1314
#31 0x00007ff802abeafc in octave::FigureWindowBase::event (this=0x26311953de0, evt=0x263171473f0) at ../libgui/graphics/FigureWindow.h:35
#32 0x00007ff871f459c1 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x26311953de0, e=0x263171473f0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:3287
#33 0x00007ff871f4ed65 in QApplication::notify (this=this@entry=0x2628e97e2a0, receiver=<optimized out>, e=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:3049
#34 0x00007ff802a04203 in octave::octave_qapplication::notify (this=0x2628e97e2a0, receiver=<optimized out>, ev=<optimized out>)
    at ../libgui/src/octave-qobject.cc:150
#35 0x00007ff873ab9288 in QCoreApplication::notifyInternal2 (receiver=0x26311953de0, event=0x263171473f0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1134
#36 0x00007ff873abd7c4 in QCoreApplication::sendEvent (event=0x263171473f0, receiver=<optimized out>)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1575
#37 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x2628e979500)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qcoreapplication.cpp:1932
#38 0x00007ff873c5a9bc in QEventDispatcherWin32::sendPostedEvents (this=this@entry=0x2628e97e0c0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qeventdispatcher_win.cpp:899
#39 0x00007ff873578dde in QWindowsGuiEventDispatcher::sendPostedEvents (this=0x2628e97e0c0)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/gui/platform/windows/qwindowsguieventdispatcher.cpp:43
#40 0x00007ff873c5e245 in QEventDispatcherWin32::processEvents (this=this@entry=0x2628e97e0c0, flags=...)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qeventdispatcher_win.cpp:468
#41 0x00007ff873578dc5 in QWindowsGuiEventDispatcher::processEvents (this=0x2628e97e0c0, flags=...)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/gui/platform/windows/qwindowsguieventdispatcher.cpp:36
#42 0x00007ff873ac51e4 in QEventLoop::processEvents (flags=..., this=0x62aedff410)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qeventloop.cpp:100
#43 QEventLoop::exec (this=this@entry=0x62aedff410, flags=flags@entry=...)
    at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/kernel/qeventloop.cpp:182
#44 0x00007ff873ac34b7 in QCoreApplication::exec () at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/corelib/global/qflags.h:74
#45 0x00007ff87320afef in QGuiApplication::exec () at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/gui/kernel/qguiapplication.cpp:1926
#46 0x00007ff871f45937 in QApplication::exec () at C:/M/B/src/qtbase-everywhere-src-6.7.0/src/widgets/kernel/qapplication.cpp:2555
#47 0x00007ff8029ff65f in octave::base_qobject::exec (this=this@entry=0x62aedff4e0) at ../libgui/src/octave-qobject.cc:432
#48 0x00007ff802a0b735 in octave::qt_application::execute (this=this@entry=0x62aedff9a0) at ../libgui/src/qt-application.cc:104
#49 0x00007ff7565825c0 in wmain (argc=<optimized out>, wargv=<optimized out>) at ../src/main-gui.cc:150
#50 0x00007ff7565812f7 in __tmainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:267
#51 0x00007ff756581406 in mainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:188
(gdb)
```

That was with a build from the current head of the default branch of Octave.

**Pull request closed without merging**
