### PR TITLE
kokkos: add new package

### PR DESCRIPTION
**Pull request by 3rav**

### CODE REVIEW

**Comment by Biswa96** [comment]
Is this package required for that trilinos issue?

**Comment by MehdiChinoune** [comment]
I don't think this package is needed on windows.
kokkos was made as an abstract to work with different parallel APIs (CUDA, OpenMP, OpenACC...) for GPUs/Accelerators.
Giving that those none of those APIs is supported on Windows (No CUDA, No OpenMP Offload, No OpenACC on GPU). It doesn't make sense to add this package.

**Comment by 3rav** [comment]
> Is this package required for that trilinos issue?

I think yes (also kokkos-kernels), but: https://github.com/trilinos/Trilinos/issues/13177

**Comment by Kreijstal** [comment]
I will test this package

**Comment by Kreijstal** [comment]
this package conflicts with the existing trilinos package, you can't install both at the same time, not sure it is a good idea.

**Pull request closed without merging**
