### PR TITLE
libpaper: fix relocation

### PR DESCRIPTION
**Pull request by lazka**
gnulib assumes the path format matches what we pass to configure, so make sure we only pass unix paths to the gnulib relocation functions.

### CODE REVIEW

**Comment by naveen521kk** [comment]
This doesn't seem to fix the texlive issue. Now it returns a slightly different error message
```
xdvipdfmx:fatal: Unrecognized paper format: # Simply write the paper name. See papersize(5) for possible values
```

**Comment by naveen521kk** [comment]
Also, running `xpdf` which also depends on `libpaper` just segfaults after this update (previously it just issued a warning for missing paper sizes).

**Comment by lazka** [comment]
Meh, ok, thanks for testing

**Comment by naveen521kk** [comment]
Thanks! looks like it works.

**Comment by lazka** [comment]
nice :)

sorry for the breakage

**Pull request merged**
