### PR TITLE
Bump file and libmagic to latest version 5.38

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by lazka** [comment]
Did it build for you locally?

**Comment by pombredanne** [comment]
There is a pending bug likely from upstream 
I submitted this https://bugs.astron.com/view.php?id=163

**Comment by pombredanne** [comment]
@lazka I spinned a VM to find the issue and there is a pending bug likely from upstream 
I submitted this https://bugs.astron.com/view.php?id=163

**Comment by lazka** [comment]
Perfect, thanks

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
