### PR TITLE
enable some more clangarm64 packages

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Please rebase your changes on master.

**Comment by jeremyd2019** [comment]
>   error: target not found: mingw-w64-clang-aarch64-spirv-cross

https://github.com/msys2-arm/MINGW-packages/runs/5546626755?check_suite_focus=true

**Comment by kmilos** [comment]
Did globbing behaviour change somehow?!

**Comment by kmilos** [comment]
The shebang was wrong anyway, so worked around the globbing issue for now.

**Comment by jeremyd2019** [comment]
https://github.com/msys2-arm/MINGW-packages/runs/5594133165?check_suite_focus=true

Passed now

**Pull request merged**
