### PR TITLE
fluidsynth: update to 2.2.0

### PR DESCRIPTION
**Pull request by neheb**
Fix compilation with clang.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
Interesting! Those compiler flags are specifically added for clang.

**Comment by neheb** [comment]
They're not even correct. Those are linker flags that should be matched based on the linker, not the compiler.

**Comment by Biswa96** [comment]
Would you like to upstream your changes for this package and from other pull requests?

**Comment by lazka** [comment]
There is an abi version bump, so needs rebuilds:

````
        mingw-w64-alure
        mingw-w644-gst-plugins-bad
        mingw-w64-openal
        mingw-w64-scummvm
        mingw-w644-SDL2_mixer
        mingw-w64-SDL_mixer
        mingw-w64-vlc
````

**Comment by neheb** [comment]
Seems like scummvm is the issue.

**Pull request merged**
