### PR TITLE
Add some Perl modules

### PR DESCRIPTION
**Pull request by naveen521kk**
It is needed for https://github.com/msys2/MINGW-packages/pull/8271
Also, fixes https://github.com/msys2/MINGW-packages/issues/8341

### CODE REVIEW

**Comment by naveen521kk** [comment]
*ucrt* builds fail, they don't have perl

**Comment by Biswa96** [comment]
Instead of copying patchmakefile.py file multiple times, it can go into mingw-w64-PKGBUILD-common folder. Speaking of UCRT, we could wait for perl in UCRT.

**Comment by naveen521kk** [comment]
> Instead of copying patchmakefile.py file multiple times, it can go into mingw-w64-PKGBUILD-common folder.

How can it be added as a source then?

**Comment by Biswa96** [comment]
> How can it be added as a source then?

I have not test this trickery in this packages, just the idea here to avoid the file duplication:

0. It does not need to be in source, git does the file verification.
1. Grab the actual path of PKGBUILD, convert it to `$pkgbuild_path/../mingw-w64-PKGBUILD-common/patchmakefile.py` and store it in a variable.
2. Place the py file in mingw-w64-PKGBUILD-common folder.
3. Run as `python ${_thepyfile}`.

See any mingw-w64 KDE package as example. Though I would like to wait for maintainers' opinion.

**Comment by naveen521kk** [comment]
Rather I will put that in a gist and fetch it as a URL. Your method looks rather complicated to me.

**Comment by Biswa96** [comment]
I changed one PKGBUILD from here and it's just a two line change.

**Comment by naveen521kk** [comment]
> I changed one PKGBUILD

Can you commit that here? Also, that will cause problems if the repository isn't cloned as a whole and only that package's PKGBUILD was build, is that fine?

**Comment by Biswa96** [comment]
> is that fine?

Maintainers' decision.

**Comment by naveen521kk** [comment]
> Maintainers' decision.

In that case I am just leaving it as is.

**Comment by naveen521kk** [comment]
This is ready.

**Comment by naveen521kk** [comment]
ping for review and merge

**Comment by naveen521kk** [comment]
Thanks :)

**Pull request merged**
