### PR TITLE
LLVM 15 RC3 upgrade

### PR DESCRIPTION
**Pull request by mati865**
Not meant for merging yet, exists only for tracking the upgrade.

Currently MLIR doesn't build with Clang 15, ~~I'll wait for another RC which should happen soon~~ RC3 doesn't help.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Why cxxabi was disabled?

**Comment by mati865** [comment]
> Why cxxabi was disabled?

It has no purpose since we have been fusing it into libc++ for years.

**Comment by mmuetzel** [comment]
The clang environments failed with the following error:
https://github.com/msys2/MINGW-packages/runs/8027125424?check_suite_focus=true#step:10:7534
```
  FAILED: lib/Testing/Support/CMakeFiles/LLVMTestingSupport.dir/Error.cpp.obj 
  D:\M\msys64\clang64\bin\clang++.exe -DGTEST_HAS_RTTI=0 -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IC:/_/mingw-w64-clang/src/build-CLANG64/lib/Testing/Support -IC:/_/mingw-w64-clang/src/llvm/lib/Testing/Support -IC:/_/mingw-w64-clang/src/build-CLANG64/include -IC:/_/mingw-w64-clang/src/llvm/include -IC:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include -IC:/_/mingw-w64-clang/src/llvm/utils/unittest/googlemock/include -march=x86-64 -mtune=generic -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -fno-rtti -Wno-suggest-override -std=c++14 -MD -MT lib/Testing/Support/CMakeFiles/LLVMTestingSupport.dir/Error.cpp.obj -MF lib\Testing\Support\CMakeFiles\LLVMTestingSupport.dir\Error.cpp.obj.d -o lib/Testing/Support/CMakeFiles/LLVMTestingSupport.dir/Error.cpp.obj -c C:/_/mingw-w64-clang/src/llvm/lib/Testing/Support/Error.cpp
  In file included from C:/_/mingw-w64-clang/src/llvm/lib/Testing/Support/Error.cpp:9:
  In file included from C:/_/mingw-w64-clang/src/llvm/include/llvm/Testing/Support/Error.h:14:
  In file included from C:/_/mingw-w64-clang/src/llvm/include/llvm/Testing/Support/SupportHelpers.h:18:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h:60:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googlemock/include/gmock/internal/gmock-internal-utils.h:50:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/gtest.h:61:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/gtest-death-test.h:45:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/internal/gtest-death-test-internal.h:43:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/gtest-matchers.h:47:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/gtest-printers.h:114:
  In file included from C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/internal/gtest-internal.h:71:
  C:/_/mingw-w64-clang/src/llvm/utils/unittest/googletest/include/gtest/internal/gtest-type-util.h:56:12: fatal error: 'cxxabi.h' file not found
  
  #  include <cxxabi.h>
  
             ^~~~~~~~~~
  
  1 error generated.
```

Is this because `cxxabi` is no longer being built?

**Comment by mati865** [comment]
We still build libc++abi (and bundle it inside libc++) like we were doing for years. We just won't create package with useless static library.

The header from the error is some kind of internal header but I have not checked it yet.

**Pull request closed without merging**
