### PR TITLE
guile1.8: new package (lightweight guile version, 32 bit only)

### PR DESCRIPTION
**Pull request by h-c-mueller**
A lightweight guile version for MINGW32 and CLANG32. Currently even the only version available for MINGW. Especially useful for linking against libguile. If MSYS2 is also installed, no need to set GUILE_LOAD_PATH, ref. patch 0017. Fixes for localtime() on CLANG32, ref. patch 0018.

### CODE REVIEW

**Comment by lazka** [comment]
Just wondering, what would this be used/useful for?

**Comment by h-c-mueller** [comment]
Simply speaking, because there is a similar open request for it, ref. #3298.

There have been numerous efforts to bring back guile support for `mingw`. But none version after 1.8.8 was able to meet this request. I assume it will still take a while, until we have back guile support with a contemporary version including 64 bit support. Until that, it's appreciated to have at least available what is working with `mingw`. Therefore, I used package name `guile1.8` to not spoil the name `guile` for a later version and related packaging attempts.
Furthermore, guile 1.8 is much more lightweight than e.g. guile 3.0, but sufficient to provide linking to `libguile`.

**Comment by lazka** [comment]
There is someone working on guile mingw support: https://twitter.com/MikeSpike3/status/1673727567080329216

I don't know how promising that is though.

**Comment by Biswa96** [comment]
That Twitter is not shown without logging in.

**Comment by h-c-mueller** [comment]
Is it maybe related to
https://github.com/spk121/guile

Biswapriyo Nath ***@***.***> schrieb am Sa., 1. Juli 2023,
09:14:

**Comment by Kreijstal** [comment]
how hard is this to port to 64bit

**Pull request merged**
