### PR TITLE
libBlocksRuntime: Mark public symbols with dllexport

### PR DESCRIPTION
**Pull request by qmfrederik**
Functions which are marked with `BLOCK_EXPORT`  are supposed to be externally visible, but miss the `__attribute__((dllexport))` attribute.  As a result, they are not exported from a .dll when compiled with clang.

Additionally, methods marked with `__attribute__((dllexport))`  cannot have the `__attribute__((weak))` attribute applied to them, so make that conditional on being compiled for non-Windows platforms.

Together with #19767, this helps compiling Objective C code on MinGW using the clang compiler.

### CODE REVIEW

**Comment by Biswa96** [comment]
Thank you for the contribution. Just curious, should there be any condition for static vs. shared libraries?

**Comment by qmfrederik** [comment]
That's a good question.  It doesn't look like the blocksruntime build setup is set up to really differentiate for this at build time -- it uses the same object files for creating the static and shared library:

```
libtool: link: clang -shared  .libs/libBlocksRuntime_la-runtime.o .libs/libBlocksRuntime_la-data.o    -g -O2 -fuse-ld=lld   -o .libs/libBlocksRuntime-0.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libBlocksRuntime.dll.a
libtool: link: ar cr .libs/libBlocksRuntime.a  libBlocksRuntime_la-runtime.o libBlocksRuntime_la-data.o
```

Additionally, I don't really see a use case where you would want to use this as a static library.  It's part of the (modern) Objective C runtime.  Your application probably uses multiple shared libraries, all of which would reference the blocks runtime as a shared library.

It doesn't look like this package has been maintained very will since it was added 7 years ago (#3123).  It also seems [no other package depends on this](https://github.com/search?q=repo%3Amsys2%2FMINGW-packages%20libblocksruntime%20&type=code).

A option could be to just stop publishing static versions of libblocksruntime?

@Adsun701 any thoughts?

**Comment by Adsun701** [comment]
@qmfrederik I think it would be a good idea to stop using static versions of libblocksruntime.

**Comment by qmfrederik** [comment]
@Biswa96 @Adsun701 I've removed the static build of libblocksruntime.  Let me know if there's anything else you need!

**Comment by Adsun701** [comment]
@qmfrederik @Biswa96 I think that's good!

**Pull request merged**
