### PR TITLE
python-spyder: update to 5.2.0

### PR DESCRIPTION
**Pull request by raedrizqie**
waiting for `spyder-kernels`

@lazka spyder still failed to detect `rtree` .. can you fix it? thx

### CODE REVIEW

**Comment by lazka** [comment]
> @lazka spyder still failed to detect `rtree` .. can you fix it? thx

where did it fail?

**Comment by raedrizqie** [comment]
Untitled 1

**Comment by lazka** [comment]
it works here (mingw64)

image

**Comment by raedrizqie** [comment]
hmm.. something is wrong with my setup then

**Comment by Biswa96** [comment]
@raedrizqie Your screenshot looks like from Windows 7.

**Comment by raedrizqie** [comment]
> @raedrizqie Your screenshot looks like from Windows 7.

yes.. thats where the problem is

**Pull request merged**
