### PR TITLE
python: rebuild without high-entropy-va

### PR DESCRIPTION
**Pull request by lazka**
It crashes the build otherwise

### CODE REVIEW

**Comment by jeremyd2019** [comment]
high-entropy-va is only available on x86_64 target, so i686 is failing due to not knowing the flag.

**Comment by lazka** [comment]
thanks!

**Comment by Biswa96** [comment]
Though I'm interested in why the build fails. Shouldn't this be reported to python?

**Comment by mati865** [comment]
It should be reported to binutils.

**Comment by lazka** [comment]
I've opened #6931 so we don't forget

**Pull request merged**
