### PR TITLE
Update Qt6 to 6.0.3

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Use submodule files.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
@Biswa96 @lazka
Can you guide how to build these dependent packages with the same pull-request.

**Comment by Biswa96** [comment]
Do we need to add `=${_qtver}` in depends?

**Comment by MehdiChinoune** [comment]
> Do we need to add `=${_qtver}` in depends?

Yes, to assure it doesn't build against the previous version.

**Comment by lazka** [comment]
> Do we need to add `=${_qtver}` in depends?

Removing that might fix it. We build them in the right order anyway.

**Comment by lazka** [comment]
Or I can look into fixing our CI script

**Pull request merged**
