### PR TITLE
gh: update to v1.9.2

### PR DESCRIPTION
**Pull request by dscho**

### CODE REVIEW

**Comment by dscho** [comment]
Hrmpf:

> GitHub Actions has encountered an internal error when running your job.

**Comment by dscho** [comment]
Force-push it is.

**Comment by naveen521kk** [comment]
>  GitHub Actions has encountered an internal error when running your job.

https://www.githubstatus.com/incidents/cj7gzzj30411

**Comment by dscho** [comment]
> [@lazka](/lazka) [lazka](/lazka) enabled auto-merge [44 seconds ago](/msys2/MINGW-packages/pull/8439#event-4623589236)

Yay!

**Comment by dscho** [comment]
Uh oh. Apparently this triggered a re-run. Oh well.

**Pull request merged**
