### PR TITLE
python-nidaqmx: new package

### PR DESCRIPTION
**Pull request by fsagbuya**
### Description

Added `python-nidaqmx` package.

Tested in `CLANG64` shell:
```
$ python
Python 3.11.9 (main, Apr 12 2024, 09:55:30)  [GCC Clang 18.1.3 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nidaqmx
>>> print(nidaqmx.__version__)
1.0.1
```

Need to package dependencies:
- [x] hightime
- [x] python-decouple
- [x] tzlocal

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you please follow the PKGBUILD template for all python packages from here https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-PKGBUILD-templates/PKGBUILD.python.sh ? Also, you can add all the dependencies in this same PR. CI will build them according to the dependency list.

**Comment by fsagbuya** [comment]
@Biswa96 CI still failing even though the missing dependencies have already been packaged

**Comment by ognevny** [comment]
please, wait until these packages are available in [staging](https://repo.msys2.org/staging/)

**Comment by fsagbuya** [comment]
@Biswa96 any updates?

**Comment by Biswa96** [comment]
PKGBUILDs of decouple and hightlight do not follow the PKGBUILD template. Also, nidaqmx do not have those dependencies.

**Comment by fsagbuya** [comment]
@Biswa96 any updates?

**Pull request merged**
