### PR TITLE
Provide install files for the new environments (ucrt64 and clang64/32)

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by Biswa96** [comment]
For the python packages, instead of install script, use the PKGBUILD.setup-py-python-pkg template to remove shebang.

**Comment by MehdiChinoune** [comment]
> For the python packages, instead of install script, use the PKGBUILD.setup-py-python-pkg template to remove shebang.

OK, I have removed the changes related to python packages

**Comment by MehdiChinoune** [comment]
Remoe ocaml as it fails to build with gcc11

**Comment by MehdiChinoune** [comment]
mingw32 build is hanging because of blender.

**Comment by lazka** [comment]
if blender fails we can try reverting the ninja change..

**Pull request merged**
