### PR TITLE
baobab: update to 42.0, remove upstreamed patch

### PR DESCRIPTION
**Pull request by rautesamtr**
Removed the upstreamed patch for windows icon in gtk3. Even though this
patch is upstreamed, the fix does not work anymore for gtk4 and the 42
release.

### CODE REVIEW

**Comment by rautesamtr** [comment]
"Open Folder" also does not work anymore even with the patch applied, it results in ```Failed to dup() in child process (Bad file descriptor)```

**Comment by lazka** [comment]
hm, it fails to start here with "gdk_gl_context_make_current() failed"

**Comment by rautesamtr** [comment]
Strange, i just did a clean 32bit & 64bit build in a new msys2 install and both just starts fine without any erros.
I also don't get the `gdk_gl_context_make_current() failed` with gtk4-widget-factory.

I am on Windows 11 21H2 22000.556 if that matters.

**Comment by lazka** [comment]
With all the GPU accel it might have to do with my setup (and Gtk not handling all cases or something).

I'm also on Win 11 with an AMD GPU.

**Comment by lazka** [comment]
thanks for re-testing, let's merge this then..

**Pull request merged**
