### PR TITLE
libssp: add clangarm64 to mingw_arch

### PR DESCRIPTION
**Pull request by jeremyd2019**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
@lazka apparently I can't push directly to master and can't merge unless the MINGW{32,64} checks pass

**Comment by Biswa96** [comment]
Just asking, does this need pkgrel++ ?

**Comment by jeremyd2019** [comment]
no, it hasn't been done for mingw_arch additions in the past.  This is really just advisory to autobuild at this point, since I'm manually building packages for arm I can build whatever I like.

**Comment by jeremyd2019** [comment]
thanks.

**Comment by lazka** [comment]
push to master should work again. I've disabled the check requirement (until we improve the CI..)

**Pull request merged**
