### PR TITLE
libwebp: define WEBP_EXTERN as __declspec(dllexport) in CPPFLAGS

### PR DESCRIPTION
**Pull request by sezero**
Otherwise, the dlls export everything.

### CODE REVIEW

**Comment by Alexpux** [comment]
@sezero i think it must be fixed in sources instead

**Comment by sezero** [comment]
I didn't want to patch it, but will do so now in a new PR.

**Comment by Alexpux** [comment]
@sezero passing this flags will broke static library

**Comment by sezero** [comment]
SDL uses the same method, but no one links static-SDL in a dll, so I see your point.
I can leave it as is if you want.

**Pull request closed without merging**
