### PR TITLE
libwebp: make sharpyuv a private dependency

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
Please explain the requirement. Is it discussed in upstream?

**Comment by Biswa96** [comment]
@1480c1 Would you like to review this change please?

**Comment by kmilos** [comment]
I also added my comment here: https://bugs.chromium.org/p/webp/issues/detail?id=590#c5

**Comment by 1480c1** [comment]
I don't recall why I didn't use .private, but lgtm

**Comment by 1480c1** [comment]
@kmilos would you like to try to submit the patch, you could add me to cc and tag me?

**Comment by kmilos** [comment]
Feel free to grab the patch from this PR @1480c1

**Pull request merged**
