### PR TITLE
hdf5: update to 1.13.1

### PR DESCRIPTION
**Pull request by MehdiChinoune**
I think the first patch should be dropped, It doesn't fix anything.
What's the purpose of adding `-0` to dll name?.
(Although, We have to rebuild all dependent packages!)

### CODE REVIEW

**Comment by lazka** [comment]
> I think the first patch should be dropped, It doesn't fix anything.
> What's the purpose of adding `-0` to dll name?.
> (Although, We have to rebuild all dependent packages!)

Feel free to drop it +  rebuilds.

Not sure why it's there.. non-cmake packages tend to communicate their ABI version that way, but cmake packages rarely bother.. Not worth patching it imo.

**Comment by MehdiChinoune** [comment]
@lazka Please revert this, since it is still in staging.
It turns out that releases with odd minor versions are experimental!
https://www.hdfgroup.org/2021/12/hdf5-1-13-0-introducing-experimental-releases/

**Comment by lazka** [comment]
oh, thanks, will do.

**Comment by MehdiChinoune** [comment]
Will you remove it from staging databases?

**Comment by lazka** [comment]
It will do that automatically, will take a few minutes..

**Pull request merged**
