### PR TITLE
enable some more clangarm64 packages

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
xerces-c:

```
2022-05-23T20:08:20.2218611Z In file included from C:/M/mingw-w64-xerces-c/src/xerces-c-3.2.3/src/xercesc/util/NetAccessors/WinSock/WinSockNetAccessor.cpp:30:
2022-05-23T20:08:20.2319143Z In file included from C:/M/mingw-w64-xerces-c/src/xerces-c-3.2.3/src/xercesc/util/NetAccessors/WinSock/BinHTTPURLInputStream.hpp:28:
2022-05-23T20:08:20.2320186Z   CXX      xercesc/util/FileManagers/WindowsFileMgr.lo
2022-05-23T20:08:20.2755779Z C:/msys64/clangarm64/include/winsock2.h:15:2: warning: Please include winsock2.h before windows.h [-W#warnings]
2022-05-23T20:08:20.2763863Z #warning Please include winsock2.h before windows.h
2022-05-23T20:08:20.2767272Z  ^
2022-05-23T20:08:20.5046470Z clang++: warning: argument unused during compilation: '-mthreads' [-Wunused-command-line-argument]
2022-05-23T20:08:20.6592561Z 1 warning generated.
2022-05-23T20:08:23.2323874Z clang++: warning: argument unused during compilation: '-mthreads' [-Wunused-command-line-argument]
2022-05-23T20:08:25.3588884Z clang++: warning: argument unused during compilation: '-mthreads' [-Wunused-command-line-argument]
2022-05-23T20:08:25.6137339Z clang++: warning: argument unused during compilation: '-mthreads' [-Wunused-command-line-argument]
2022-05-23T20:08:45.2513897Z   CXXLD    libxerces-c.la
2022-05-23T20:10:10.6226440Z ld.lld: error: undefined symbol: __cpuid
2022-05-23T20:10:10.6227966Z >>> referenced by xercesc\util\.libs\PlatformUtils.o:(xercesc_3_2::XMLPlatformUtils::Initialize(char const*, char const*, xercesc_3_2::PanicHandler*, xercesc_3_2::MemoryManager*))
2022-05-23T20:10:10.6420992Z clang++: error: linker command failed with exit code 1 (use -v to see invocation)
2022-05-23T20:10:10.6571647Z make[3]: *** [Makefile:3913: libxerces-c.la] Error 1
2022-05-23T20:10:10.6576723Z make[3]: Leaving directory '/c/M/mingw-w64-xerces-c/src/build-CLANGARM64/src'
2022-05-23T20:10:10.6607124Z make[2]: *** [Makefile:2836: all] Error 2
2022-05-23T20:10:10.6612011Z make[2]: Leaving directory '/c/M/mingw-w64-xerces-c/src/build-CLANGARM64/src'
2022-05-23T20:10:10.6705707Z make[1]: *** [Makefile:553: all-recursive] Error 1
2022-05-23T20:10:10.6713427Z make[1]: Leaving directory '/c/M/mingw-w64-xerces-c/src/build-CLANGARM64'
2022-05-23T20:10:10.6760306Z make: *** [Makefile:442: all] Error 2
2022-05-23T20:10:10.8996274Z ==> ERROR: A failure occurred in build().
```

freexl:

```
2022-05-23T19:31:03.3654516Z checking whether ln -s works... no, using cp -pR
2022-05-23T19:31:03.4985258Z checking whether make sets $(MAKE)... (cached) yes
2022-05-23T19:31:04.6454755Z Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized
2022-05-23T19:31:04.6502553Z configure: error: /bin/sh ../freexl-1.0.6/./config.sub aarch64-w64-mingw32 failed
2022-05-23T19:31:05.6107450Z ==> ERROR: A failure occurred in build().
```

**Comment by kmilos** [comment]
Thanks, I guess I well revert some of these then...

**Comment by Biswa96** [comment]
ArchLinuxARM has both [xerces-c](https://archlinuxarm.org/packages/aarch64/xerces-c/files/PKGBUILD) and [libfreexl](https://archlinuxarm.org/packages/aarch64/libfreexl/files/PKGBUILD) package. Let me test something.

**Comment by kmilos** [comment]
libfreexl might just miss an `autoreconf -ivf`?

Don't know about xerces-c, seems hard-coded...

**Pull request merged**
