### PR TITLE
qt5-base: rebuild

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
No Vulkan!

**Comment by MehdiChinoune** [comment]
I see now, vulkan-headers is missing in makedepends()
I remove dependency of vulkan-loader on vulkan-headers in https://github.com/msys2/MINGW-packages/commit/27d35e9e

**Comment by lazka** [comment]
ah, yeah, so related to https://github.com/KhronosGroup/Vulkan-Loader/issues/1463

**Comment by lazka** [comment]
fixed via c0e699eefafe97e337881a613999a54cd7e9d63c then.

**Pull request closed without merging**
