### PR TITLE
Update libiconv version to 1.17

### PR DESCRIPTION
**Pull request by sagilo**

### CODE REVIEW

**Comment by Biswa96** [comment]
Run `updpkgsums` command to update the checksums and amend the change to this commit.

**Comment by sagilo** [comment]
> Run `updpkgsums` command to update the checksums and amend the change to this commit.

The command fails on similar error
```
$ updpkgsums
==> Retrieving sources...
  -> Downloading libiconv-1.17.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz
    Aborting...
==> ERROR: Failed to generate new checksums
```

**Comment by umarcor** [comment]
@sagilo, `libiconv-1.17.tar.gz` does not exist in https://ftp.gnu.org/pub/gnu/libiconv/.

**Comment by sagilo** [comment]
> @sagilo, `libiconv-1.17.tar.gz` does not exist in https://ftp.gnu.org/pub/gnu/libiconv/.

I know, I want to create it by making the package get rebuilt through the pipeline

**Comment by umarcor** [comment]
You are trying to download a package from an external website, and that package does not exist. Upon further inspection, it seems that you are trying to build libiconv version 1.17, but that version was never developed, so it does not exist either.

If you want to rebuild the package without bumping the version, you need to bump `pkgrel`, not `pkgver`.

**Comment by sagilo** [comment]
> You are trying to download a package from an external website, and that package does not exist. Upon further inspection, it seems that you are trying to build libiconv version 1.17, but that version was never developed, so it does not exist either.
> 
> If you want to rebuild the package without bumping the version, you need to bump `pkgrel`, not `pkgver`.

Got it! I'll open another pr. thanks!

**Pull request closed without merging**
