### PR TITLE
groonga: Update to 10.1.1

### PR DESCRIPTION
**Pull request by komainu8**

### CODE REVIEW

**Comment by Biswa96** [comment]
Just FYI. There is a separate pull request to update arrow by @kou. groonga seems to depend on arrow. Can anyone of you move your change to other one? We may prevent any possible API breakage between them due to version update.

**Comment by kou** [comment]
OK. I'll merge this into #7807.

**Comment by Biswa96** [comment]
Make sure @komainu8 is agreed with that 😊

**Comment by komainu8** [comment]
OK. I agree with that.

**Pull request closed without merging**
