### PR TITLE
gtksourceview3: Fix compiling with clang

### PR DESCRIPTION
**Pull request by Biswa96**
* workaround warning: linker path does not have real file for library -luuid.
* workaround: glib-mkenums adds wrong comments in gtksourceview-enumtypes.c.
* disable gtk-doc due to wrong paths in build command.

Fixes https://github.com/msys2/MINGW-packages/issues/18588

### CODE REVIEW

**Comment by lazka** [comment]
fyi, we don't have any users left for gtksourceview3 with clang, so if that complicates things, consider dropping it and gtksourceviewmm3 for clang envs.

**Comment by Biswa96** [comment]
Please wait before removing this package. This reveals a bug in python. The `/clang64/lib/python3.11/distutils/cygwinccompiler.py` file has `-mdll` compiler option. It was not supported in clang for long time. clang 17 raises that to compiler error. We've to fix it first.

**Comment by Biswa96** [comment]
Could you fix it in python please?

**Comment by lazka** [comment]
sure

**Comment by hmartinez82** [comment]
@lazka So, I was trying to run quodlibet (know that project? 😉) in CLANGARM64. And these lines in textedit.py were being the issue:
```
try:
    import gi
    gi.require_version("GtkSource", "3.0")
    from gi.repository import GtkSource
except (ValueError, ImportError):
    TextView = Gtk.TextView
    TextBuffer = Gtk.TextBuffer
```
Interestingly if gtksourceview3 is not installed the exception path takes place (at least that's what I remember seeing while debugging) and it works, but if gtksourceview3 is installed then that gi import goes thru and the code crashes in the next line: `class TextBuffer(GtkSource.Buffer)` saying that GtkSource.Buffer is void.

in CLANGARM64 where gtksourceview4 does have the dll, I was able to change the require above to gi.require_version("GtkSource", "4") and it worked.

**Comment by lazka** [comment]
> @lazka So, I was trying to run quodlibet (know that project? 😉) in CLANGARM64. And these lines in textedit.py were being the issue:

I see. I took the opportunity to get rid of it there: https://github.com/quodlibet/quodlibet/pull/4377

**Comment by MehdiChinoune** [comment]
> Please wait before removing this package. This reveals a bug in python. The `/clang64/lib/python3.11/distutils/cygwinccompiler.py` file has `-mdll` compiler option. It was not supported in clang for long time. clang 17 raises that to compiler error. We've to fix it first.

I have encountered this issue with arrow package on CLANG* environments.

**Comment by lazka** [comment]
pkg-config segfaults after the last rebuild

**Comment by MehdiChinoune** [comment]
> pkg-config segfaults after the last rebuild, but works under a debugger, meh.

because of Hardening, Maybe!

**Comment by mmuetzel** [comment]
> pkg-config segfaults after the last rebuild, but works under a debugger, meh.

Sounds like it could be a threading issue.

**Pull request merged**
