### PR TITLE
poppler: update to 21.09.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
Needs rebuilds for:

```
mingw-w64-pdf2djvu
mingw-w64-poppler-qt6
mingw-w64-gdcm
mingw-w64-gdal
mingw-w64-inkscape
```

**Comment by lazka** [comment]
```diff
  --- /dev/fd/63	2021-09-24 06:31:37.000000000 +0000
  +++ /dev/fd/62	2021-09-24 06:31:37.000000000 +0000
  @@ -1,6 +1,6 @@
   /mingw64/
   /mingw64/bin/
  -/mingw64/bin/libpoppler-112.dll
  +/mingw64/bin/libpoppler-113.dll
   /mingw64/bin/libpoppler-cpp-0.dll
   /mingw64/bin/libpoppler-glib-8.dll
   /mingw64/bin/libpoppler-qt5-1.dll
```

**Comment by lazka** [comment]
> Speaking of poppler-qt6, you can also merge it with poppler PKGBUILD file like you did with other qt5/qt6 split packages.

Wouldn't it make more sense to split it like Arch to reduce pulling in qt5 etc?

**Comment by Biswa96** [comment]
Yup. The dependent packages may need the change also. Arch also separates glib one.

**Comment by lazka** [comment]
but that's for another PR...

**Pull request merged**
