### PR TITLE
libavif: update to 0.10.1, enable clangarm64

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
Just wondering if it is possible enable arm for libheif and libgd also.

**Comment by kmilos** [comment]
Yeah, might try...

**Comment by kmilos** [comment]
Turns out x265 is already available, but [libde265 requires quite a bit of patching to get to work on aarch64](https://github.com/strukturag/libde265/issues/308), so disabled it for now...

**Comment by kmilos** [comment]
At the same time, there seem to be aarch64 Linux packages around, so maybe it just works? https://archlinuxarm.org/packages/aarch64/libde265

**Comment by Biswa96** [comment]
Yeah, I've cross-compiled libde265 with llvm-mingw, not sure if it works.

**Comment by kmilos** [comment]
Ok, let's give https://github.com/msys2/MINGW-packages/pull/11599 a go separately

**Comment by kmilos** [comment]
I've seen these random 'Permission denied' failures locally as well...

**Pull request merged**
