### PR TITLE
ollama: Update to 0.1.42 and build in Release mode

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by ognevny** [comment]
it's better to push checksums for git source. it's useful when upstream change tag

**Comment by Biswa96** [comment]
> it's better to push checksums for git source. it's useful when upstream change tag

Done in 7d2d7bdb34684d93cdd306a860ae0dfd69d1aa37

**Comment by hmartinez82** [comment]
Oh. I never even heard about this concept. Learned a new thing today. Thank you.

**Comment by Biswa96** [comment]
> Oh. I never even heard about this concept.

It's a new thing in pacman 6.1.0 release. https://gitlab.archlinux.org/pacman/pacman/-/releases/v6.1.0

> Add checksum support for git/mercurial/bzr sources

**Pull request merged**
