### PR TITLE
aom: update to 3.0.0

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
Does this break ABI? https://aomedia.googlesource.com/aom/+/v3.0.0 isn't very clear .. hmm

**Comment by kmilos** [comment]
I can't be 100% sure either...

libavif change after they updated their external reference seems only API related? https://github.com/AOMediaCodec/libavif/commits/master

Happy to let this one sit until a new libavif release though...

**Comment by kmilos** [comment]
We can wait at least for the next libavif release that uses this new aom version and rebuild all then...

Do you think it's worth patching CMakeLists to [make the SOVERSION part of the DLL filename](https://gitlab.kitware.com/cmake/cmake/-/issues/21716)?

**Comment by lazka** [comment]
> We can wait at least for the next libavif release that uses this new aom version and rebuild all then...

sure

> Do you think it's worth patching CMakeLists to [make the SOVERSION part of the DLL filename](https://gitlab.kitware.com/cmake/cmake/-/issues/21716)?

Ideally upstream would decide that, so everyone uses the same DLL name (at least for the same type of toolchain). Do you think it's worth asking upstream?

**Comment by lazka** [comment]
rebuilds worked (except ucrt64, but that is WIP), so I'm merging this.

**Comment by lazka** [comment]
Thanks!

**Comment by kmilos** [comment]
Great, thanks!

**Pull request merged**
