### PR TITLE
mingw-w64: disable wildcard by default

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
Some docs: https://github.com/msys2/msys2.github.io/pull/347

**Comment by lazka** [comment]
news entry: https://github.com/msys2/msys2.github.io/pull/348

**Comment by mati865** [comment]
IIRC this will break Rust build or Rust testsuite on envs using Binutils.

**Comment by lazka** [comment]
Thanks. Did someone try this last year?

If all fails we can re-enable it on a per-package basis.

**Comment by mati865** [comment]
I was able to find the old error: `C:/a/rust/rust/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find C:\a\rust\rust\build\i686-pc-windows-gnu\stage2\lib\rustlib\i686-pc-windows-gnu\lib/liballoc-*.rlib: Invalid argument`.

It was previously called from Makefile: https://github.com/rust-lang/rust/pull/128407/files#diff-53c7f7d0d39446b7fbe61af298fbdbdcdfcd1a7f083095343edc545a8926c6f6L14
Since it's rewritten in Rust, this won't fail anymore, but there might be other places (also in different packages) where the toolchain is expected to handle globs, just like on Linux.

**Comment by lazka** [comment]
Thanks, from what I understand enabling wildcards in gcc would also fix this case? https://github.com/gcc-mirror/gcc/blob/7f67acf60c5429895d7c9e5df81796753e2913e0/gcc/configure.ac#L2263

**Comment by mati865** [comment]
Sounds likely but won't work for Binutils tools that don't go through GCC like when calling `ar`, but that might be an uncommon thing to do.

**Comment by lazka** [comment]
let's see :)

**Pull request merged**
