### PR TITLE
libopenmpt package was updated to 0.6.0 version.

### PR DESCRIPTION
**Pull request by volkanorhan**
This update depends on merge request https://github.com/msys2/MINGW-packages/pull/10604 . After then that package is merged, the tests can be run again.

### CODE REVIEW

**Comment by Biswa96** [comment]
It would be easier to to verify CI builds if these commits are added to the portaudio-cpp pull request. CI automatically builds the dependencies first.

**Comment by volkanorhan** [comment]
> It would be easier to to verify CI builds if these commits are added to the portaudio-cpp pull request. CI automatically builds the dependencies first.

Do you mean that I should add portaudio-cpp's commits to this branch (or merge portaudio-cpp branch to this branch)?

**Comment by Biswa96** [comment]
I meant to add these commits to #10604 PR. Because libopenmpt will be dependent on portaudiocpp.

**Comment by volkanorhan** [comment]
> I meant to add these commits to #10604 PR. Because libopenmpt will be dependent on portaudiocpp.

If I add these commits to portaudiocpp, that branch will contain changes for libopenmpt, but that branch is not related to libopenmpt.

**Pull request merged**
