### PR TITLE
Allow SFML PKGBUILD to build on clangarm64

### PR DESCRIPTION
**Pull request by ZachBacon**
Signed-off-by: Zach Bacon <zachbacon@vba-m.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
Enabling clangarm64 does not require pkgrel bump. Have you built this package in clangarm64?

**Comment by ZachBacon** [comment]
I have indeed, as a packager I tend to build before pushing changes. And yeah the habit of a bump in rel is a habit I have with solus. General rule of thumb there was if you touch it, then bump it.

**Comment by Biswa96** [comment]
Bumping pkgrel would not create any issue here but it results in additional update for users. pkgrel should be incremented only when fixes or addition features are added in PKGBUILD[^1]. Here adding clangarm64 does not add or change new features in packages of other MSYSTEMs.

[^1]: https://wiki.archlinux.org/title/PKGBUILD

**Comment by ZachBacon** [comment]
Yes I'm aware, I'm just saying it was a force of habit that made me do it without realizing it till much after the fact.

**Comment by Biswa96** [comment]
So, would you like to revert the last commit please?

**Comment by ZachBacon** [comment]
That's the thing, I am not well versed in reverting commits.

**Comment by Biswa96** [comment]
It's OK. I have added your commit in https://github.com/msys2/MINGW-packages/commit/131b9762af3fc6d4dd9c20df16795d622dca3be1. Thank you.

git commit can be reverted with `git reset --hard HEAD~1` command and then force push.

**Pull request closed without merging**
