### PR TITLE
flashrom: Fix version reporting with upstream source tarball

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/pull/10773

### CODE REVIEW

**Comment by Biswa96** [comment]
@obskyr Does this look good? The upstream source tarball already has versioninfo.inc. So, we don't have to generate it.

**Comment by obskyr** [comment]
This certainly fixes `versioninfo.inc`, yes! One question, however: should `makedepends` not include `"patch"`? When I attempted to build on a clean-ish MSYS2 installation, it complained that there was no such command as `patch`, and I had to install it manually with `pacman`.

**Comment by Biswa96** [comment]
> should makedepends not include "patch"?

It is not required to mention in PKGBUILD file. To build a package, one has to install base-devel package group which contains the patch program and others. It's similar as build-essentials in Debian like systems. More details can be found here https://www.msys2.org/wiki/Creating-Packages/#build-software

**Comment by obskyr** [comment]
Alright; very good to know – thank you for the information! This looks like a great fix, then!

**Pull request merged**
