### PR TITLE
gegl: Depend on libheif directly instead of transitively via vala,graphviz,libgd

### PR DESCRIPTION
**Pull request by hmartinez82**
See discussion in [#12607 ](https://github.com/msys2/MINGW-packages/pull/12607#issuecomment-1221391113)

### CODE REVIEW

**Comment by Biswa96** [comment]
I am not sure if it is correct to add libheif in gegl dependencies. libheif is not mentioned even a single time in gegl repository.

**Comment by hmartinez82** [comment]
@Biswa96 should we add the libheif dep to jasper then? https://github.com/jasper-software/jasper/search?q=heif

**Comment by Biswa96** [comment]
libheif is optional in jasper. I think I found the issue. jasper's pkgconfig file has libheif but libheif is not present at build time. We may need to fix the 002-pkg-config-static.patch.

**Comment by hmartinez82** [comment]
@Biswa96 can you tackle that change? :)

**Pull request closed without merging**
