### PR TITLE
WIP: rocksdb: build with jemalloc

### PR DESCRIPTION
**Pull request by EchterAgo**
This needs a fix for rocksdb which I have included as a patch.

See https://github.com/facebook/rocksdb/pull/7320

### CODE REVIEW

**Comment by Biswa96** [comment]
Please increase `pkgrel` variable by 1.

**Comment by EchterAgo** [comment]
@Biswa96 oops, sorry

**Comment by EchterAgo** [comment]
@Biswa96 fixed

**Comment by lazka** [comment]
Any info on why this change is needed/a good idea?

**Comment by EchterAgo** [comment]
Rocksdb benefits from an allocator that prevents heap fragmention. Arch linux enables it by default. That said I just realized that this needs to be improved because it might not work right with dynamic linking. I'll do more testing tomorrow.

**Comment by EchterAgo** [comment]
Ok, so this crashes in the shared build, but the reason is that in a shared build `-lrocksdb -ljemalloc` actually mixes a static `rocksdb` with a dynamic `jemalloc`. Everything works fine when I use `-lrocksdb-shared -ljemalloc`.

AFAICT there should always be 2 libraries, `libreadline.a` for static and `libreadline.dll.a` for shared. In `rocksdb` the static library is `librocksdb.a` and the dynamic library is `librocksdb-shared.dll.a`, causing the linker to see default to the static library. I think the `-shared` part should be removed. I'll open up a separate PR for this.

**Comment by lazka** [comment]
Yeah, looks weird given the shared lib on Linux doesn't have this suffix.

**Comment by lazka** [comment]
I've created #7155

**Comment by lazka** [comment]
@EchterAgo I've rebased this on top of master. Can you re-test for the crashes?

**Comment by Alexpux** [comment]
@EchterAgo @lazka rocksdb updated https://github.com/msys2/MINGW-packages/commit/63392dfe785248a04a217e33a76412b5a2740fa4

**Comment by lazka** [comment]
Someone will need to test this again (I don't know how), otherwise I'll close this.

**Comment by lazka** [comment]
Any plans to continue working on this?

**Pull request closed without merging**
