### PR TITLE
Build windows-default-manifest on CLANG64/32

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I'm curious, is there some particular reason you need this?

**Comment by MehdiChinoune** [comment]
> I'm curious, is there some particular reason you need this?

I want to build gfortran on clang*

**Comment by mati865** [comment]
Is there Thread Local Storage in Fortran? GCC doesn't support native TLS for Windows so libraries/executables produced by GCC wouldn't even link with ones made by Clang if TLS is used.

**Comment by MehdiChinoune** [comment]
> Is there Thread Local Storage in Fortran? GCC doesn't support native TLS for Windows so libraries/executables produced by GCC wouldn't even link with ones made by Clang if TLS is used.

I don't know!

**Pull request merged**
