### PR TITLE
lz4 - 1.9.0 Update to latest version, drop unneeded patch, and fix .l…

### PR DESCRIPTION
**Pull request by JPeterMugaas**
…ib file (it should be .dll.a)

### CODE REVIEW

**Comment by Alexpux** [comment]
@JPeterMugaas  seems your commit is wrong because CI generate empty package:
````
make: Nothing to be done for 'install'.
````

**Comment by Alexpux** [comment]
@JPeterMugaas return patch and adopt it to new version

**Comment by Alexpux** [comment]
@JPeterMugaas why you not first check yourself on your machine? Pakcage is broken. As I told you return patch and fix it for new version

**Comment by JPeterMugaas** [comment]
It seemed to work on my machine.

**Comment by Alexpux** [comment]
@JPeterMugaas both CI failing

**Comment by JPeterMugaas** [comment]
I know.  I'm working on this now.  I'm wondering if it might be better if we used cmake with "contrib/cmake_unofficial/CMakeLists.txt" instead of using the Makefile build system.  I think that the Makefiles could be doing something strange.

**Comment by Alexpux** [comment]
done by https://github.com/msys2/MINGW-packages/commit/430ca85108f43ebcc9b05a9c509cbafa66d3a1d9

**Pull request closed without merging**
