### PR TITLE
Revert "libuv: update to 1.44.2"

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Reverts msys2/MINGW-packages#13272

### CODE REVIEW

**Comment by lazka** [comment]
cmake crashes with current libuv in staging (1.44.2-1): https://github.com/msys2/msys2-tests/actions/runs/3167285211/jobs/5157661116

Is this related?

**Comment by MehdiChinoune** [comment]
> cmake crashes with current libuv in staging (1.44.2-1): https://github.com/msys2/msys2-tests/actions/runs/3167285211/jobs/5157661116
> 
> Downgrading fixes things
> 
> Is this related?

Automoc crashes in 32bit envs, see #13358 #13359 #13365

**Comment by lazka** [comment]
rebuilding cmake seems to fix things, so maybe libuv broke ABI?

**Comment by MehdiChinoune** [comment]
> rebuilding cmake seems to fix things here, so maybe libuv broke ABI?

I was relying on package-grokker on that, It didn't show nothing, but that was for MINGW64.

Maybe we should run package-grokker for other environments?

**Comment by lazka** [comment]
I don't see any missing symbols etc locally, so likely that wouldn't have caught it. I'll investigate some more.

**Comment by MehdiChinoune** [comment]
Rebuilding CMake fixes the crash with `automoc`.

**Comment by lazka** [comment]
Bisected:

```
8e67d8b364a3c44f4fd5a2df5914f13979de7c91 is the first bad commit
commit 8e67d8b364a3c44f4fd5a2df5914f13979de7c91
Author: roflcopter4 <15476346+roflcopter4@users.noreply.github.com>
Date:   Sat Mar 5 10:54:41 2022 -0700

    win,poll: add the MSAFD GUID for AF_UNIX (#3511)

    Enables the "fast poll" mechanism for the new(ish) Unix sockets in
    Windows 10.

 include/uv/win.h | 2 +-
 src/win/poll.c   | 4 +++-
 2 files changed, 4 insertions(+), 2 deletions(-)
```

**Comment by MehdiChinoune** [comment]
Just to clarify, It wasn't automoc that crashes It was CMake crashing at automoc step.
cmake is only package that depends on libuv.

**Comment by lazka** [comment]
I see, thanks.

**Comment by lazka** [comment]
triggered a cmake rebuild now: f5ec61ddc9aa2a7f

**Pull request closed without merging**
