### PR TITLE
gcc-git: Update to GCC 10

### PR DESCRIPTION
**Pull request by lhmouse**
Signed-off-by: Liu Hao <lh_mouse@126.com>

### CODE REVIEW

**Comment by Alexpux** [comment]
@lhmouse I have the same error trying to update to 10.1

**Comment by lhmouse** [comment]
The ` export ordinal too large: 65957` error? Sorry, I don't build Ada so was not aware of it. I will ask some other people how to overcome this.

**Comment by lhmouse** [comment]
AFAICT the error was caused by the limitation of ordinals. Each function that is exported from a **Windows** DLL is assigned an ordinal, which is an unsigned 16-bit integer, which limits the number of export functions to `65536` (or `65535`?). After looking at some random reports, I suppose that it is no longer possible to build an **Ada** DLL, only static libs can be built (see the 4th link attached below).

### References

1. <https://stackoverflow.com/questions/47135973/error-export-ordinal-too-large-104116>
2. <https://github.com/Z3Prover/z3/issues/2385>
3. <https://gitlab.haskell.org/ghc/ghc/issues/18030>
4. <https://gitlab.haskell.org/ghc/ghc/-/wikis/windows-dynamic-linking>

**Comment by Alexpux** [comment]
@lhmouse look at our error. It get error on creating cc1plus.exe.a

**Comment by lhmouse** [comment]
Which error? Didn't see such errors on Azure.

**Comment by Alexpux** [comment]
@lhmouse to see real issue probably need to build with -j1

**Comment by lhmouse** [comment]
I will take a look a couple of days later.

Building only C, C++ and LTO worked for me <https://gcc-mcf.lhmouse.com/>.

**Comment by Alexpux** [comment]
well if this is Ada build error then probably we need to think about dropping Ada again.

**Comment by lhmouse** [comment]
Try disabling `0011-Enable-shared-gnat-implib.patch`?

**Comment by Alexpux** [comment]
@lhmouse I don’t try, but it just create import library for already building DLL

**Comment by ArnaudCharlet** [comment]
Can someone post the full build log with the errors? FWIW I don't see why GCC 10 would make a difference here, so this is definitely unexpected but certainly fixable. BTW is that Windows 32bits or 64bits or both? I would guess 32bits only, if so you could at least keep Ada builds on 64bits.

**Comment by reznikmm** [comment]
@ArnaudCharlet Here it is:
- [i686 log](https://dev.azure.com/msys2/5ee43462-f2c2-45d5-8c1c-31fdb1fd15b4/_apis/build/builds/5101/logs/14)
- [x86_64 log](https://dev.azure.com/msys2/5ee43462-f2c2-45d5-8c1c-31fdb1fd15b4/_apis/build/builds/5101/logs/18)

**Comment by Alexpux** [comment]
It fail on linking both 32 and 64

**Comment by ArnaudCharlet** [comment]
Thanks. What's the point of generating gnat1.a in the first place?

--
-Wl,--out-implib=gnat1.exe.a
--

This issue will pop up with cc1plus.exe.a sooner or later, so I'd recommend removing this step before it hits other languages, there is really nothing Ada specific here.

**Comment by Alexpux** [comment]
@ArnaudCharlet well we suggested that this is for gcc plugins done.

**Comment by Alexpux** [comment]
@lhmouse  @ArnaudCharlet  yes this is go from gcc-plugin.m4

**Comment by ArnaudCharlet** [comment]
Do you know if people use the plug-ins capability with the mingw compilers from msys? If not one option would be to configure without plugin support.

**Comment by Alexpux** [comment]
disabling plugins solving issue

**Comment by lhmouse** [comment]
I see. I have no opinion on removal of plugins. It was @labba that requested them.

Personally I don't build Ada or ObjC so plugins work fine for me.

**Comment by Alexpux** [comment]
@lhmouse do you build GCC with zstd ? If no then try build with it

**Comment by lhmouse** [comment]
`--with-system-zstd`? do I have to remove `--with-system-zlib`?

**Comment by Alexpux** [comment]
@lhmouse if zstd installed GCC use it without options, zlib also used

**Comment by Alexpux** [comment]
I will upload GCC without plugins support but it need be fixed.

**Comment by Alexpux** [comment]
https://github.com/msys2/MINGW-packages/commit/9501ee2afc8d01dc7d85383e4b22e91c30d93ca7

**Comment by lhmouse** [comment]
ok will try tommorrow (~20 hrs later).

**Comment by jtanx** [comment]
This gcc is broken, it's reporting dependencies with mangled paths.

e.g. 

```
#include <stdio.h>
int main(){}
```

```
gcc -MD -MT t.o -MF t.d t.c
```

t.d contains

```
t.o: t.c C\:/msys64/mingw32/i686-w64-mingw32/include/stdio.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/corecrt_stdio_config.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/corecrt.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/_mingw.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/_mingw_mac.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/_mingw_secapi.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/vadefs.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/sdks/_mingw_ddk.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/_mingw_off_t.h \
 C\:/msys64/mingw32/i686-w64-mingw32/include/swprintf.inl \
 C\:/msys64/mingw32/i686-w64-mingw32/include/sec_api/stdio_s.h
```

Note the backwards slash C\ before the colon. This is causing issues with e.g. ninja (and probably make too):

```
ninja: error: FindFirstFileExA(c/:/msys64/mingw32/i686-w64-mingw32/include): The filename, directory name, or volume label syntax is incorrect.
```

**Comment by lhmouse** [comment]
@jtanx That's valid syntax for **GNU make**. I noticed the same `.Po` files when building the CRT and **GNU make** didn't complain.

**Comment by jtanx** [comment]
I just rolled back to gcc 9 and it was fine:

```
t.o: t.c C:/msys64/mingw32/i686-w64-mingw32/include/stdio.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/corecrt_stdio_config.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/corecrt.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/_mingw.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/_mingw_mac.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/_mingw_secapi.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/vadefs.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/sdks/_mingw_ddk.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/_mingw_off_t.h \
 C:/msys64/mingw32/i686-w64-mingw32/include/swprintf.inl \
 C:/msys64/mingw32/i686-w64-mingw32/include/sec_api/stdio_s.h
```

**Comment by 106062316** [comment]
@jtanx Someone proposed a fix to ninja already, see https://github.com/ninja-build/ninja/pull/1774

**Comment by Alexpux** [comment]
We could also try to fix this in GCC by adding backslash only if next char after colon is not directory separator

**Comment by Alexpux** [comment]
what about GCC patch like that:
````
--- gcc-10.1.0/libcpp/mkdeps.c.orig	2020-05-10 20:37:27.263933600 +0300
+++ gcc-10.1.0/libcpp/mkdeps.c	2020-05-10 20:42:00.700896900 +0300
@@ -156,10 +156,14 @@
 	      /* FALLTHROUGH  */
 
 	    case '#':
-	    case ':':
 	      buf[dst++] = '\\';
 	      /* FALLTHROUGH  */
 
+	    case ':':
+	      if (*(probe + 1) && !IS_DIR_SEPARATOR (*(probe + 1)))
+	        buf[dst++] = '\\';
+	      /* FALLTHROUGH  */
+
 	    default:
 	    def:
 	      slashes = 0;

````

**Comment by lhmouse** [comment]
@Alexpux  The first `/* FALLTHROUGH  */` is now incorrect, as it falls through the clause that you have added, which it didn't.

**Comment by Alexpux** [comment]
@lhmouse ah yes you are right. Maybe then:
````
--- gcc-10.1.0/libcpp/mkdeps.c.orig	2020-05-10 20:37:27.263933600 +0300
+++ gcc-10.1.0/libcpp/mkdeps.c	2020-05-10 20:42:00.700896900 +0300
@@ -156,6 +156,9 @@
 	      /* FALLTHROUGH  */
 
 	    case '#':
 	    case ':':
+#ifdef _WIN32
+	      if (!(c == ':' && IS_DIR_SEPARATOR (*(probe + 1))))
+#endif
 	      buf[dst++] = '\\';
 	      /* FALLTHROUGH  */
 
````

**Comment by lhmouse** [comment]
This patch could resolve this issue. But I think we could do more aggressively by prevent escaping of colons (that is to remove `case ':':`, as colons can't be part of a file name (unless created with MSYS2 or other drivers). Few people will use NTFS streams in Makefiles I believe.

Anyway this had better be fixed in Ninja.

**Comment by Alexpux** [comment]
@lhmouse are you sure that only ninja is broken by this?

**Comment by lhmouse** [comment]
No. The only two build systems that I know is **ninja** (broken) and **GNU make** (working well).

**Comment by Alexpux** [comment]
i will try rebuild gcc with my patch as workaround and try to see if we not break something else

**Comment by Alexpux** [comment]
As @lhmouse suggested completely remove escaping bachslash in deps https://github.com/msys2/MINGW-packages/commit/9b7f67c5f620d1ba7ce951cfee3ce2328fb751f6

**Comment by lhmouse** [comment]
@alexpux GCC bootstrapped OK with `mingw-w64-x86_64-zstd` installed. Only C, C++ and LTO were enabled. I haven't used it to build other libraries, though.

**Comment by Alexpux** [comment]
@lhmouse ok I get it

**Pull request merged**
