### PR TITLE
clang: stop using access time for file comparison

### LINKED ISSUE #15695: Clang: Sporadic linker errors happen when a sysroot is used
### Description / Steps to reproduce the issue

If you use clang as a cross compiler and give it a new sysroot via the --sysroot this error can occur sporadically. 

We have a very large CMake project. When we build the project in CI, we sometimes get build errors. However, this is highly sporadic and occurs in about 1% of linker actions.

Locally you can reproduce it if you update the sysroot folder access time during the build. (`while true; do touch -a <sysroot> ; done`) 

The comparison of access times was introduced with http://reviews.llvm.org/D18456. I think this happened by mistake.

### Expected behavior

lld should not have sporadic errors and should link independent of the access time.

### Actual behavior

lld sporadically fails to resolve GNU linker scripts.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?
https://github.com/msys2/MINGW-packages/pull/15694

### PR DESCRIPTION
**Pull request by rvogg**
To compare files on windows the access times is used.
This leads to the fact that the lld sets the variable isUnderSysroot to false by mistake with strongly
parallelized compiles. (Since the access time of the sysroot folder can be updated between two stats).
    
This prevents the ScriptParser from correctly resolving the path from a linker script if sysroot is set 
and sporadic linker errors occur.

Fixes #15695

### CODE REVIEW

**Comment by Biswa96** [comment]
Would you like to explain the problem in a new issue?

**Comment by rvogg** [comment]
I have created an issue:  https://github.com/msys2/MINGW-packages/issues/15695

**Comment by rvogg** [comment]
What info is still missing, is there anything else I can add? 
How can I help?

**Comment by mstorsjo** [comment]
The patch is on its way upstream in https://reviews.llvm.org/D144172.

**Pull request merged**
