### PR TITLE
libidn2: Update to 2.3.4

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by raedrizqie** [comment]
try removing libunistring from depends..

**Comment by lazka** [comment]
thanks, I'll give that a try tomorrow :)

**Comment by raedrizqie** [comment]
hmm.. the last time i built it CI.. it compiles fine.. without extra option..

```
Gnulib updated and now libunistring-optional is used.
This allows you to force libidn2 to use internal libunistring with the
following command: ./configure --with-included-libunistring
```

maybe we had to add `--with-included-libunistring` to force internal unistring..

**Comment by raedrizqie** [comment]
you forgot to add it for static build :)

**Comment by lazka** [comment]
no idea, there is an upstream bug: https://gitlab.com/libidn/libidn2/-/issues/113

**Pull request closed without merging**
