### PR TITLE
jsonschema: move attr, pyrsistent and setuptools from makedepends to depends

### PR DESCRIPTION
**Pull request by peterbud**
Interestingly the sha256sums was also wrong?

### CODE REVIEW

**Comment by lazka** [comment]
> Interestingly the sha256sums was also wrong?

github generated tarballs are not stable, afaik they are cached and regenerated on demand... so sometimes they change.

**Comment by peterbud** [comment]
I think it was my fault... I had a previously downloaded tarball, and the original checksum was the good. Now it looks better

**Comment by lazka** [comment]
(I think setuptools-scm in makedepends might help)

**Comment by peterbud** [comment]
Thanks @lazka ! Now it build nicely in CI as well.

**Pull request merged**
