### PR TITLE
python-pre-commit: Fix installation of python pre-commit hooks

### LINKED ISSUE #21161: [python-pre-commit]
### Description / Steps to reproduce the issue

Hello support team,

I am a pre-commit user on Linux and I'd like to use it on Windows with msys2/mingw64. I installed it using `pacman -S mingw-w64-x86_64-python-pre-commit`, which goes fine. But at run, it is not working:
```
$ pre-commit run
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/XYZ/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0

Check the log at C:/Users/XYZ/.cache/pre-commit/pre-commit.log
```

A guy answered that there is an issue in the package itself. The whole discussions is [here](https://stackoverflow.com/questions/78615923/pre-commit-version-did-not-match-created-version-on-msys2)

Any idea on the root cause / issue ?

### Expected behavior

It works directly after installation

### Actual behavior

the log shows:
**version information**
```
pre-commit version: 3.7.0
git --version: git version 2.45.1
sys.version:
    3.11.9 (main, Apr 12 2024, 09:55:31)  [GCC 13.2.0 64 bit (AMD64)]
sys.executable: C:/msys64/mingw64/bin/python.exe
os.name: nt
sys.platform: win32
```

**error information**
```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/robin.maubert.ch2/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0
```

```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/repository.py", line 99, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/XYZ/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by sdegrande**
Pre-commit uses python virtualenvs to install python hooks. On Windows, pre-commit uses the Windows's virtualenv directory structure, which install scripts in a 'Scripts' subdir. But, on msys, the standard unix virtualenv is used, which installs scripts in a 'bin' subdir.

Fixes #21161

### CODE REVIEW

**Comment by lazka** [comment]
Thanks.

In theory you could also do something like `python.exe -c "import sysconfig, os; print(os.path.basename(sysconfig.get_path('scripts')))"` but maybe we should try to provide a copy of everything under "Scripts" so things just work.

**Comment by lazka** [comment]
I've added a comment to a related issue for our python: https://github.com/msys2-contrib/cpython-mingw/issues/169#issuecomment-2269846086

**Comment by sdegrande** [comment]
Thanks for the merge, @lazka, and thanks for your amazing work !

**Comment by sdegrande** [comment]
> Thanks.
> 
> In theory you could also do something like `python.exe -c "import sysconfig, os; print(os.path.basename(sysconfig.get_path('scripts')))"` 

Eh, that would be a great 'universal' solution ! thanks for the tip, it could possibly be accepted by the pre-commit's dev. let's try...

**Pull request merged**
