### PR TITLE
goffice: Add package

### PR DESCRIPTION
**Pull request by stahta01**
I am trying to get gnumeric to build and it needs goffice.

Tim S.

### CODE REVIEW

**Comment by Biswa96** [comment]
A stable release would be preferred. Like this https://github.com/archlinux/svntogit-packages/blob/packages/goffice/trunk/PKGBUILD

**Comment by stahta01** [comment]
I consider a git tag to be more stable than a git commit; if you think differently please explain!

Tim S.

**Comment by Biswa96** [comment]
That's what I just said 😊 But this package uses git commit instead of tag, doesn't it?

**Comment by stahta01** [comment]
I edited the pkgver() to reduce the confusion.

**Comment by stahta01** [comment]
> That's what I just said  But this package uses git commit instead of tag, doesn't it?

To clarify for the other readers the Arch Linux package uses an plain git commit; while my package is using a git tag.

Tim S.

**Comment by Biswa96** [comment]
And why do we need those bunch of variables and if...else statement?

**Comment by stahta01** [comment]
I am guessing that some times that a git commit is needed to be used instead of a git tag.
I can get rid of some of them. But, it might be needed to add some of them back in the future.
I still do not under stand why the Arch Linux package uses a git commit instead of a git tag.

Tim S.

**Comment by stahta01** [comment]
Decided to work on this package in the [MINGW-packages-dev repo](https://github.com/msys2/MINGW-packages-dev)

**Pull request closed without merging**
