### PR TITLE
wasmer: Enable cranelift

### PR DESCRIPTION
**Pull request by ArchGuyWu**

### CODE REVIEW

**Comment by ognevny** [comment]
also enable cranelift

**Comment by ognevny** [comment]
why did you disable singlepass? it worked fine

**Comment by ArchGuyWu** [comment]
> singlepass

Ok, you mean we should enable all compilers?

**Comment by ognevny** [comment]
yes

**Comment by ArchGuyWu** [comment]
> yes

Ok.

**Comment by ognevny** [comment]
FYI, llvm-15's `llvm-config.exe` is located in `${MINGW_PREFIX}/opt/llvm-15/bin`

**Comment by ognevny** [comment]
in CLANG64 it still detects llvm 18, for UCRT64 it's not detected at all

**Comment by ArchGuyWu** [comment]
> in CLANG64 it still detects llvm 18, for UCRT64 it's not detected at all

OK, we maybe have to use clang-15 for clang64.

**Comment by ognevny** [comment]
> > in CLANG64 it still detects llvm 18, for UCRT64 it's not detected at all
> 
> OK, we maybe have to use clang-15 for clang64.

I'd prefer to not enable LLVM if it requires too many workarounds

**Comment by ArchGuyWu** [comment]
> > > in CLANG64 it still detects llvm 18, for UCRT64 it's not detected at all
> > 
> > 
> > OK, we maybe have to use clang-15 for clang64.
> 
> I'd prefer to not enable LLVM if it requires too many workarounds



> > > in CLANG64 it still detects llvm 18, for UCRT64 it's not detected at all
> > 
> > 
> > OK, we maybe have to use clang-15 for clang64.
> 
> I'd prefer to not enable LLVM if it requires too many workarounds

Ok.

**Comment by ArchGuyWu** [comment]
@ognevny Is it ok to merge?

**Comment by ognevny** [comment]
> @ognevny Is it ok to merge?

yes, but I wanted to squash tun-tap patch

**Comment by ArchGuyWu** [comment]
> > @ognevny Is it ok to merge?
> 
> yes, but I wanted to squash tun-tap patch

Ok.

**Comment by ArchGuyWu** [comment]
Why disabled lto?

**Comment by ognevny** [comment]
> Why disabled lto?

it's enabled in wasmer's Makefile. actually !lto is default value in makepkg.conf, it adds some lto-related CFLAGS, but for MinGW toolchain lto is broken. disabling it explicitly so unneeded lto flags won't be applied in future when everything will be fixed

**Comment by ArchGuyWu** [comment]
> > Why disabled lto?
> 
> it's enabled in wasmer's Makefile. actually !lto is default value in makepkg.conf, it adds some lto-related CFLAGS, but for MinGW toolchain lto is broken. disabling it explicitly so unneeded lto flags won't be applied in future when everything will be fixed

Ok.

**Pull request merged**
