### PR TITLE
Update arm-none-eabi-binutils to 2.35

### PR DESCRIPTION
**Pull request by fauxpark**
Technically a new package, as it's not actually in the pacman repo.

### CODE REVIEW

**Comment by Biswa96** [comment]
There should be separate build directory for x86_64 and i686. So, don't remove the commands with `build-${MINGW_CHOST}` directory name.

**Comment by fauxpark** [comment]
What for? `${srcdir}` gets nuked each time anyway.

**Comment by Biswa96** [comment]
It is not nuked with `makepkg-mingw` which is useful to create x86_64 and i686 package in one shot. Also separate build folder is useful to repackage (i.e. `makepkg-mingw -R`) if something went wrong.

**Comment by fauxpark** [comment]
> It is not nuked with makepkg-mingw which is useful to create x86_64 and i686 package in one shot.

I always use the command specified here: https://www.msys2.org/wiki/Creating-Packages/
`makepkg-mingw -sCLf` which cleans the srcdir before building. Fair point on repackaging, though.

**Pull request merged**
