### PR TITLE
python: Update to 3.9.6

### PR DESCRIPTION
**Pull request by lazka**
* [x] Figure out list of packages to rebuild
* [x] bump pkgrel for those packages

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I think @danyeaw had a script for that.

**Comment by danyeaw** [comment]
```
pacman -Fqx "/python3.8/" | grep 'mingw64/' | cut -f2- -d/ | \
	cut --complement -f3 -d- | while read -r dir; do
	if [ -d "$dir" ]; then
		echo "Updating pkgrel for $dir"
		cd "$dir"
		awk -F"=" 'BEGIN{OFS="="} { if ($1=="pkgrel") {print $1,$2=$2+1} else {print $0}}' \
		PKGBUILD > temp && mv temp PKGBUILD
		cd ..

	else 
		echo "$dir does not exist"
	fi
done
```

**Comment by jeremyd2019** [comment]
Hmm, and that's sufficient?  I would be trying to overengineer something, to try to get from package to %PKGBASE% to source dir.  https://gist.github.com/jeremyd2019/dbdabd1f91dd87d97f58ba25497ce851#file-clang32-py-L103-L113

**Comment by lazka** [comment]
Thanks, I went with `pacman -Fqx '/python3\.8/' '.*\.py.*' '.*-cpython-.*'` and did the pkgbase ones manually

**Comment by lazka** [comment]
let's go

**Pull request merged**
