### PR TITLE
Update mingw-w64

### PR DESCRIPTION
**Pull request by lazka**
https://github.com/mingw-w64/mingw-w64/compare/1b699a6db...5f566373f

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Building QGIS start failing after this update!

**Comment by Biswa96** [comment]
Could you provide the error message please?

**Comment by MehdiChinoune** [comment]
> Could you provide the error message please?

Paths start get stripped of slashes!
https://github.com/qgis/QGIS/actions/runs/4523070497/jobs/7965950041

**Comment by MehdiChinoune** [comment]
> > Paths start get stripped of slashes!
> 
> I am not sure if that kind of error is related to this minimal mingw-w64 changes. Wondering if the issue is in cmake or in other pacakages.

but It started right after mingw-w64 was updated (look at setup-msys2 log), cmake was updated in previous jobs with no failure.

**Comment by MehdiChinoune** [comment]
That wasn't the job where It started failing, It started failing here https://github.com/qgis/QGIS/actions/runs/4517306883/jobs/7959203173
The latest successful job was https://github.com/qgis/QGIS/actions/runs/4513850185/jobs/7949204376
cmake 3.26.0 vs 3.26.1!

**Comment by MehdiChinoune** [comment]
I think I have found it https://gitlab.kitware.com/cmake/cmake/-/commit/60132272302f106c996aa15a0c42cb3de9789a24

**Pull request merged**
