### PR TITLE
rust: update to 1.71.0

### PR DESCRIPTION
**Pull request by filnet**

### CODE REVIEW

**Comment by filnet** [comment]
Fails when packaging:

```
Build completed successfully in 2:21:25
==> Starting package_mingw-w64-clang-x86_64-rust()...
mv: cannot stat '/C/_/B/pkg/mingw-w64-clang-x86_64-rust/clang64/etc/bash_completion.d/cargo': No such file or directory
==> ERROR: A failure occurred in package_mingw-w64-clang-x86_64-rust().
    Aborting...
```

**Comment by filnet** [comment]
https://github.com/rust-lang/rust/commit/08ce68b6a6bad360e9c3611ad60cf6598401f878

**Comment by ognevnydemon** [comment]
ok to merge?

**Comment by filnet** [comment]
> ok to merge?

Some checks haven’t completed yet.

**Comment by filnet** [comment]
Should now be ok to merge.

**Comment by filnet** [comment]
@lazka @mati865 @Biswa96 @jeremyd2019, please merge whenever you can.

**Pull request merged**
