### PR TITLE
ruby: disable graphviz for clang.

### PR DESCRIPTION
**Pull request by jeremyd2019**
It's not available yet.  It's crashing on clang at this point, but want
to get more eyes on it.

/cc @Biswa96

### CODE REVIEW

**Comment by jeremyd2019** [comment]
This one didn't give a clang backtrace, just:
```
2021-05-01T19:16:33.2310581Z generating encdb.h
2021-05-01T19:16:33.7569784Z make: *** [uncommon.mk:1095: encdb.h] Segmentation fault
2021-05-01T19:16:33.7587914Z make: *** Waiting for unfinished jobs....
2021-05-01T19:16:33.7676300Z make: *** [uncommon.mk:1144: builtin_binary.inc] Segmentation fault
2021-05-01T19:16:33.8774642Z make: *** [uncommon.mk:820: .rbconfig.time] Error 139
```

**Comment by Biswa96** [comment]
I am solving the issues to compile graphviz (if possible) in clang. At least that gives me excuse to fixes packages in clang.

**Comment by jeremyd2019** [comment]
This is no longer relevant at all

**Comment by Biswa96** [comment]
Ruby does not build with clang, got segfault.

**Pull request closed without merging**
