### PR TITLE
[new package] gitui 0.24.3

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by ognevny** [comment]
clangarm64 fails with
```
thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.1.3+3.1.2\src\lib.rs:330:18:
    don't know how to configure OpenSSL for aarch64-pc-windows-gnullvm
```

**Comment by podsvirov** [comment]
> clangarm64 fails with...

be free to just disable   the broken subsystem

**Comment by ognevny** [comment]
> be free to just disable   the broken subsystem

you can commit it directly. do it, please, so there will be no need for extra PR

**Comment by ognevny** [comment]
> clangarm64 fails with
> ```
> thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.1.3+3.1.2\src\lib.rs:330:18:
>     don't know how to configure OpenSSL for aarch64-pc-windows-gnullvm
> ```

reported [here](https://github.com/alexcrichton/openssl-src-rs/issues/227)

**Pull request merged**
