### PR TITLE
soqt: Fix SoQt.pc

### PR DESCRIPTION
**Pull request by podsvirov**
The missing -lSoQt part will be added to Libs section.
The missing -DSOQT_DLL part will be added to Cflags section.

### CODE REVIEW

**Comment by Biswa96** [comment]
Shouldn't this be done from upstream or by patching the .pc.in file?

**Comment by podsvirov** [comment]
These issues have already been resolved in the master branch. I think that the fixes are superfluous - the additional configuration is enough. All this will not be needed in the new version.

**Comment by Biswa96** [comment]
Just asking. How about adding that upstream change as a patch file? It would make easy to track in future.

**Comment by podsvirov** [comment]
This is the correct thought. But in this case, I don't know where this patch is located. If you don't mind, I'll leave this question until the next release of SoQt.

**Comment by podsvirov** [comment]
In pair with #8029 we can build [test-code/components](https://github.com/coin3d/soqt/tree/master/test-code/components) by simple `Makefile`:
```make
TARGETS := $(filter-out coloreditor,$(patsubst %.cpp,%,$(wildcard *.cpp)))

CXXFLAGS := $(shell pkg-config SoQt --cflags)
LDFLAGS := $(shell pkg-config SoQt --libs)

.PHONY: all
all: ${TARGETS}

%: %.cpp
        ${CXX} ${CXXFLAGS} -o $@ $< ${LDFLAGS}

.PHONY: clean
clean:
        ${RM} ${TARGETS}
```

**Pull request merged**
