### PR TITLE
mdbook-pikchr: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
Anybody know why `CLANG32` (not in `mingw_arch`) was checked?

**Comment by MehdiChinoune** [comment]
> Anybody know why `CLANG32` (not in `mingw_arch`) was checked?

An issue in [ci-build.sh](https://github.com/msys2/MINGW-packages/blob/master/.ci/ci-build.sh#L41)
the initial list was `packages=("mingw-w64-mdbook" "mingw-w64-mdbook-pikchr")` and the skipped list is the same.
`${packages[@]/"mingw-w64-mdbook"}=(-pikchr)`

**Comment by podsvirov** [comment]
@MehdiChinoune thanks for quick fix!

**Comment by podsvirov** [comment]
Looks like access to mirrors too slow...

**Comment by podsvirov** [comment]
Anybody can build this tool himself via `cargo` (just invoke `cargo install mdbook-pikchr`), but what about to merge this PR for just installig via `pacman`?

**Pull request merged**
