### PR TITLE
Add various Ada libraries from AdaCore

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
And fix gprbuild for x86.

### CODE REVIEW

**Comment by Biswa96** [comment]
Some comments:

1. gnat_util package has unusual version. If possible try to use `_commit` (custom) and `pkgver` variables in commands.
2. `PROCESSORS=$(nproc)` options may be removed. The jobs count is already mentioned in `$MAKEFLAGS` in `/etc/makepkg*` files.
3. For license files, I would recommend to use `install` command instead of `cp`.

**Comment by Fabien-Chouteau** [comment]
Thank you @Biswa96 

> * gnat_util package has unusual version. If possible try to use `_commit` (custom) and `pkgver` variables in commands.

I think I see what you mean. I will submit a change.

> * `PROCESSORS=$(nproc)` options may be removed. The jobs count is already mentioned in `$MAKEFLAGS` in `/etc/makepkg*` files.

`PROCESSORS` is actually used when calling the Ada builder tool `gprbuild`. So this is different than `make`'s `-j` option.

> * For license files, I would recommend to use `install` command instead of `cp`.

Will do.

**Comment by Biswa96** [comment]
O, another thing. Try to use double quotes like `"${srcdir}"` and `"${pkgdir}"`.

**Comment by Fabien-Chouteau** [comment]
`actions/upload-artifact@v2` failed, can someone restart the workflow?

**Pull request merged**
