### PR TITLE
Update libconfini (1.12.0 -> 1.13.0)

### PR DESCRIPTION
**Pull request by madmurphy**

### CODE REVIEW

**Comment by lazka** [comment]
```
==> Extracting sources...
  -> Extracting libconfini-1.13.0.tar.gz with bsdtar
libconfini-1.13.0/dev/docs/baremetal.md: Can't create 'libconfini-1.13.0/dev/docs/baremetal.md'
bsdtar: Error exit delayed from previous errors.
==> ERROR: Failed to extract libconfini-1.13.0.tar.gz
    Aborting...
```

**Comment by madmurphy** [comment]
Hi lazka,

That is strange, it worked just fine on my laptop. Could it be possibly due to the fact that the file it fails to extract is a symbolic link?

**Comment by lazka** [comment]
yeah, that's likely the problem. See https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-grpc/PKGBUILD for example where we ignore extraction error.

**Comment by madmurphy** [comment]
Thank you, lazka. Now it should work.

**Pull request merged**
