### PR TITLE
New package: TileDB

### PR DESCRIPTION
**Pull request by jeroen**
@Biswa96 Here is a new package which also depends on aws-sdk-cpp, so we can test if #8070 actually works. You can merge this after or together with #8070. 
cc @ihnorton

### CODE REVIEW

**Comment by Biswa96** [comment]
The install step has gone in horrible way 😨 Also why are every AWS related package huge in size that it requires +4GB memory to build?

**Comment by Biswa96** [comment]
The binaries are installed in wrong path. Also this requires spdlog and catch package as dependency otherwise CMake download those externally.

**Comment by jeroen** [comment]
> The binaries are installed in wrong path.

Good catch. That should be fixed.

I have to go now, feel free to take it from here or make changes if you like.

**Comment by Biswa96** [comment]
OK, I'll add the dependencies tomorrow. Would you like to squash the commits into one?

**Pull request merged**
