### PR TITLE
python-wmi: new package

### PR DESCRIPTION
**Pull request by jeremyd2019**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I plan to try to test (run check) locally before marking ready for review.

**Comment by jeremyd2019** [comment]
check succeeded on clangarm64.

**Comment by Biswa96** [comment]
Just wondering. Is the project still maintained? In [pypi WMI](https://pypi.org/project/WMI/), the last release was in Apr 28, 2020.

**Comment by jeremyd2019** [comment]
I don't know, I suspect it just doesn't change much, since it is wrapping a Windows API that has been around for 20-some years.  I was actually surprised it was updated as recently as it was...

In any event, it is listed in the requirements.txt of the os-win project, and is installed when pip installing os-win with normal Windows python.

**Pull request merged**
