### PR TITLE
Remove hack from the kicad package

### PR DESCRIPTION
**Pull request by nickoe**
With the latest release of glm the cmake hack is not needed in the kicad package anymore.

### CODE REVIEW

**Comment by nickoe** [comment]
@ustsv why does this fail in the prepare step?

I think I will split this PR in two.

**Comment by nickoe** [comment]
I split this up with the glm bump in https://github.com/msys2/MINGW-packages/pull/5128

**Comment by Alexpux** [comment]
@nickoe fix conflicts

**Comment by nickoe** [comment]
@Alexpux ok, thank you. I rebased it, but I think the glm pkgbump needs to be pushed to the package repo before this will pass the CI.

**Pull request merged**
