### PR TITLE
wxWidgets3.1: Add package

### PR DESCRIPTION
**Pull request by stahta01**
wxWidgets version 3.1.1 is the latest development release of wxWidgets . I would not create a binary unless others request it.  I also have packages for wxWidgets3.0-git and wxWidgets-git; but, I am not sure you would want them. Tim S.

### CODE REVIEW

**Comment by Alexpux** [comment]
@stahta01 does it conflicts with current wxwidgets package?

**Comment by stahta01** [comment]
@Alexpux They just released 3.1.2 development release; I am working on changes to this package.

Likely be a few days to do all the testing; you might wish to wait or just use the 3.1.1 version of package.
Tim S.

**Comment by tomay3000** [comment]
Very good, it would be very helpful if it is included in the repo alongside with soci-git also.
Here is my All-In-One build commands for wxMSW port with Win32 MSys2 backend:
`cd /C/wxWidgets-3.1.2

mkdir build-msw-static
mkdir build-msw-shared
mkdir build-msw-shared-monolithic

cd build-msw-static && PKG_CONFIG='pkg-config --static' ../configure --with-msw --disable-shared --enable-cxx11 && make && cd ..
cd build-msw-shared && PKG_CONFIG='pkg-config' ../configure --with-msw --enable-cxx11 && make && cd ..
cd build-msw-shared-monolithic && PKG_CONFIG='pkg-config' ../configure --with-msw --enable-cxx11 --enable-monolithic && make && cd ..

cd build-msw-static/samples && make clean && make && cd ../..
cd build-msw-static/demos && make clean && make && cd ../..
cd build-msw-static/tests && make clean && make && cd ../..
cd build-msw-static/utils && make clean && make && cd ../..

cd build-msw-static/samples/minimal && ./minimal.exe && cd ../../..
cd build-msw-static/samples/typetest && ./typetest.exe && cd ../../..
cd build-msw-static/samples/drawing && ./drawing.exe && cd ../../..
cd build-msw-static/samples/splash && ./splash.exe && cd ../../..
cd build-msw-static/samples/widgets && ./widgets.exe && cd ../../..
`

**Comment by stahta01** [comment]
I am working on this package and hope to get it done in about a week. Spent the last 8 hours trying to get a patch to work.

Tim S.

**Comment by stahta01** [comment]
@Alexpux I think this package can now be added to your repo; I do not think it is worth making an binary package till someone other than me requests said package. Tim S.

**Comment by BrendanSimon-SEPL** [comment]
+1 request for wxWidgets 3.1.2 (or later).

I'm using `brew` on Mac which installs `wxWidgets 3.1.1`.  I have installed a downloaded font (`Repetition Scrolling`) and it works in a multiline TextCtrl perfectly on the Mac.

However this font is not working too well on MSYS2 wxWidgets 3.0.4.  The lines overlap !!

I have no idea whether wxWidgets 3.1.2 will fix it, but I would prefer to build my apps with the same genre of widgets (i.e. 3.1.x).

How can I download install your 3.1.x build of wxWidgets?

Thanks, Brendan.

**Comment by nickoe** [comment]
@stahta01 Why is this a seperate package and not just an update of the previous wxwidgets package?

**Comment by BrendanSimon-SEPL** [comment]
Any update on this.  I just installed msys2 on a fresh install of Win 10, updated the packages and still only see wxWidgets 3.0.4.

Is wxWidgets 3.1.2 available somewhere to install via pacman/pacboy ??

**Pull request merged**
