### PR TITLE
gdb does not load user init file

### PR DESCRIPTION
**Pull request by bustercopley**
GDB automatically loads (and treats as safe) the user init file in $HOME\.gdbinit, but HOME is not typically set on Windows, so no init file is loaded. The existing MSYS2 patch "gdb-8.3-cache-dir.patch" makes GDB fall back to USERPROFILE if HOME is not defined, in some cases but not others.

This commit makes GDB fall back to USERPROFILE if HOME is not defined, _everywhere_ it looks at HOME.

### CODE REVIEW

**Comment by Alexpux** [comment]
@bustercopley increase pkgrel

**Comment by bustercopley** [comment]
> @bustercopley <https://github.com/bustercopley> increase pkgrel
>
@Alexpux done, thanks.

**Comment by Alexpux** [comment]
@bustercopley CI tell that checksums are invalid. Seems you add wrong checksum for your patch

**Comment by bustercopley** [comment]
@Alexpux Forgive the newbie mistakes. Should I squash the commits into one?

**Pull request merged**
