### PR TITLE
nanobind: Remove redundant robin_map submodule download

### PR DESCRIPTION
**Pull request by Biswa96**
robin_map module is already included in nanobind tarball from pypi.

### CODE REVIEW

**Comment by Biswa96** [comment]
@marcelotduarte Would you like to review this PR please?

**Comment by marcelotduarte** [comment]
To write the PKGBUILD I read the aur version and conda feedstock recipe. I conda feedstock is write by the author of nanobind, so I follow him to include the robin_map_commit ;-)
https://github.com/conda-forge/nanobind-feedstock/blob/main/recipe/meta.yaml#L11C57-L11C73

**Comment by Biswa96** [comment]
> To write the PKGBUILD I read the aur version and conda feedstock recipe.

They are both using git repository and tarball from release page respectively. mingw package is using sdist from pypi.

**Comment by marcelotduarte** [comment]
You are correct.

**Pull request merged**
