### PR TITLE
clang: add coff fix section name encoding patch

### PR DESCRIPTION
**Pull request by filnet**
The patch fixes stripping of large static libraries.
The stripping issue was impacting LLVM itself.
LLVM had at least one invalid static library after stripping.

As the current LLVM is affected by the issue, we need to do two builds:
- a first build to produce a fixed LLVM
- and a second one to produce a properly stripped package (using the 1st build).

see https://github.com/msys2/MINGW-packages/pull/10555#issuecomment-1046088716

### CODE REVIEW

**Comment by mati865** [comment]
We have 2 options to proceed with this:
- temporarily disable stripping for CLANG* subsystems
- rebuild LLVM twice

**Comment by jeremyd2019** [comment]
Should we prefer backporting the full fix, now that that has 'landed'?

**Comment by filnet** [comment]
My tests show that even with the patch the rust build fails. So no urgency on my side unless we want to reproduce it in CI..

BTW, is it possible to download packages built by CI ?

**Comment by jeremyd2019** [comment]
> BTW, is it possible to download packages built by CI ?

Yes, go to the 'checks' tab and there should be an 'Artifacts' drop-down near the top right.

**Comment by filnet** [comment]
I tested the patched LLVM with rust and it looks good.

**Comment by filnet** [comment]
> Should we prefer backporting the full fix, now that that has 'landed'?

I had a quick look and the full fix is on top of major refactoring.

**Comment by jeremyd2019** [comment]
The backport to the 14.x branch applied cleanly (I pushed it here, but am continuing to test locally where it builds faster).

**Comment by jeremyd2019** [comment]
local build of 2x mingw-w64-clang and 1x mingw-w64-rust 1.58.1 succeeded with upstream patches from 14.x branch.

I also made a new split package on mingw-w64-clang that contains the gcc aliases (mingw-w64-clang-*-gcc-compat).  This inherits the '-toolchain' group from the top-level of the PKGBUILD so hopefully users who want to use tools that assume gcc will be able to continue to use them, and packages whose logic is tied to the name 'gcc' like perl can makedepend on it explicitly.

**Comment by jeremyd2019** [comment]
CI run from my fork (before the latest rebase): https://github.com/jeremyd2019/MINGW-packages/actions/runs/1890450317

**Comment by filnet** [comment]
Should I create a new PR for the 2nd build ?

**Comment by lazka** [comment]
(I don't need one at least)

**Comment by filnet** [comment]
> (I don't need one at least)

Sorry, I did not understand.

**Comment by lazka** [comment]
sry, I meant I don't need a PR to continue this.

**Pull request merged**
