### PR TITLE
[HOLD] otter-browser: New package

### PR DESCRIPTION
**Pull request by stahta01**
The browser works well enough to show me web pages; and, I logged into two web sites.
There does seem to be bugs; but, they match the ones I saw from the Windows download version.
I only have my name as Contributor because other than fixing build errors I can not fix run-time errors.
Is keeping the package able to be built enough to be a Maintainer?

See #6122

Tim S.

### CODE REVIEW

**Comment by stahta01** [comment]
I am thinking that the version added is not the newest version.
So, marked as WIP till I can confirm.

**Comment by stahta01** [comment]
I have decide to update the package to using the git master repo instead of the latest release.

Tim S.

**Comment by stahta01** [comment]
I have gotten the project to be as good as I can make it.
But, I would say keep it as a source only package with no binary build till the project is more stable.

Tim S.

**Comment by elieux** [comment]
Then maybe let's place it into mingw-packages-dev.

**Comment by stahta01** [comment]
Decided to add it to mingw-packages-dev repo, instead.

**Comment by lazka** [comment]
Closing in favor of https://github.com/msys2/MINGW-packages-dev/pull/10

**Pull request closed without merging**
