### PR TITLE
Add ffnvcodec-headers package

### PR DESCRIPTION
**Pull request by ImperatorS79**
Inspired from arch linux version. Needed to enable nvenc in ffmpeg.

### CODE REVIEW

**Comment by ZachBacon** [comment]
Your pr modified a crap ton of packages just to enable nvenc in ffmpeg that are unrelated to ffmpeg.

**Comment by ZachBacon** [comment]
scrap that, mobile didn't give me a proper view.

**Comment by jeremyd2019** [comment]
There's a merge commit on this branch that could be rebased out, that's probably the cause.

**Comment by ZachBacon** [comment]
@jeremyd2019 yeah, I saw that after logging into the desktop instead of my phone.

**Comment by Biswa96** [comment]
1. Add your name as maintainer and remove the ArchLinux one.
2. Add the pkgbase variable like other pkgbuild file.
3. As the package is being built from a specific tag, the source tarball can be used instead of git repository.
4.

**Comment by ImperatorS79** [comment]
No idea how to download a source tarball from here https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git;a=summary

**Comment by Biswa96** [comment]
It's ok, just asking.

**Comment by ImperatorS79** [comment]
I think this is ready to merge now.

**Pull request merged**
