### PR TITLE
Update freerdp to 3.3.0

### LINKED ISSUE #20182: [Freerdp] update to <3.3.0>
### Package name

freerdp

### New version number

3.3.0

### Other information that may be useful

It fails with:
```
gcc.exe -DFREERDP_EXPORTS -DNDEBUG -DUNICODE -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWITH_OPENSSL -DWITH_SMARTCARD_EMULATE -DWITH_VERBOSE_WINPR_ASSERT -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0601 -D_WINSOCK_DEPRECATED_NO_WARNINGS -Dwfreerdp_server_EXPORTS -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/winpr/include -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/build-UCRT64/winpr/include -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/build-UCRT64 -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/build-UCRT64/include -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/include -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/server/Windows/. -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -O3 -DNDEBUG -std=gnu11 -MD -MT server/Windows/CMakeFiles/wfreerdp-server.dir/wf_rdpsnd.c.obj -MF server\Windows\CMakeFiles\wfreerdp-server.dir\wf_rdpsnd.c.obj.d -o server/Windows/CMakeFiles/wfreerdp-server.dir/wf_rdpsnd.c.obj -c C:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/server/Windows/wf_rdpsnd.c
C:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/server/Windows/wf_rdpsnd.c: In function 'wf_peer_rdpsnd_activated':
C:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/server/Windows/wf_rdpsnd.c:78:40: error: 'i' undeclared (first use in this function)
   78 |         context->SelectFormat(context, i);
      |                                        ^
C:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-freerdp/src/FreeRDP-3.3.0/server/Windows/wf_rdpsnd.c:78:40: note: each undeclared identifier is reported only once for each function it appears in
[13/22] Linking C shared library server\shadow\libfreerdp-shadow3.dll
ninja: build stopped: subcommand failed.

```
maybe another patch on the headers?

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by Kreijstal**
fixes #20182

### CODE REVIEW

**Comment by Biswa96** [comment]
Did you try to upstream the patch file? It seems minor mistake.

Also, the kicad change should be in separate commit or pull request.

**Comment by Kreijstal** [comment]
> Did you try to upstream the patch file? It seems minor mistake.
> 
> Also, the kicad change should be in separate commit or pull request.

You were too fast! :<
I fixed it asap and you still noticed. 
we can create the issue if you want

**Comment by Biswa96** [comment]
I have asked about that issue in matrix now.

**Comment by MehdiChinoune** [comment]
I have already reported the issue in https://github.com/FreeRDP/FreeRDP/issues/9900 and It was fixed in https://github.com/FreeRDP/FreeRDP/pull/9901

**Pull request merged**
