### PR TITLE
cmake: no import lib for executable

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by lazka** [comment]
is there an upstream issue for this?

**Comment by raedrizqie** [comment]
not that i am aware of

**Comment by raedrizqie** [comment]
> Is there any package affected by this issue? Sometime import library is created from executable to create plugins.

on windows? can you please give an example?

**Comment by Biswa96** [comment]
> on windows? can you please give an example?

I can not recall any actual project but meson supports creating import library from executable https://mesonbuild.com/Reference-manual_functions.html#executable_implib

**Comment by MehdiChinoune** [comment]
postgresql link to posgresql.exe itself, you could check that by `ntldd -R`.

**Comment by raedrizqie** [comment]
both examples are not from cmake build system itself.. but yeah, they exist.. closing

**Pull request closed without merging**
