### PR TITLE
doxygen: enable for clangarm64

### PR DESCRIPTION
**Pull request by jeremyd2019**
Disable wizard, to avoid needing qt5 just yet.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
For Qt5/Qt6 there are few remaining packages:
- assimp
- double-conversion
- dbus
- md4c
- pcre2
- xmlstarlet
- libmariadbclient

**Comment by jeremyd2019** [comment]
my script comes up with mingw-w64-postgresql too (makedepends).

**Comment by MehdiChinoune** [comment]
> my script comes up with mingw-w64-postgresql too (makedepends).

It could be disabled. like we did before postgresql was available for clang*.

**Comment by driver1998** [comment]
> For Qt5/Qt6 there are few remaining packages:
>
> assimp
> minizip
> double-conversion
> dbus
> md4c
> pcre2
> xmlstarlet
> libmariadbclient

The following compiles for me locally:
- minizip-git
- double-conversion
- dbus (tests hang the build process, have to skip)
- md4c
- libmariadbclient

assimp seems to require D3DX9 which is not available for ARM, let's see what can do about it.

**Comment by MehdiChinoune** [comment]
> assimp seems to require D3DX9 which is not available for ARM, let's see what can do about it.

It requires it only for assimp_view tool which it could be disabled on aarch64.
https://github.com/assimp/assimp/blob/v5.2.2/tools/assimp_view/CMakeLists.txt#L42

**Comment by Biswa96** [comment]
It is possible to move the required import libraries to arm crt, like this https://github.com/mingw-w64/mingw-w64/commit/456b8d78be1e418d28d5c8ad26debecf92050a81

**Comment by driver1998** [comment]
It's not the import libraries, those D3DX dlls does not exist on ARM. For ARM32, there is some in the Windows 8 HLK for some reason, but nothing on ARM64.

**Pull request merged**
