### PR TITLE
Akira 0.0.14

### PR DESCRIPTION
**Pull request by albfan**
akira-0 0 14-windows

Packages needed to run Akira on windows 

https://github.com/akiraux/Akira

- Review needed: 
   - Is gtk-update-icon-cache needed? I see in other themes
   - xcursorgen is not available so some cursors are not generated. Should I include a tar with generated sources (they are png files)

### CODE REVIEW

**Comment by albfan** [comment]
@Alexpux some CI task failed due to order building, should I open separate PR?

**Comment by Biswa96** [comment]
It looks like you named the package "goocanvas3" but akira has "goocanvas" in dependencies. Also make sure the package name is similar with ArchLinux or AUR packages. It makes thing easier while comparing versions.

**Comment by Biswa96** [comment]
Also if available, use source tarball instead of git repository.

**Comment by albfan** [comment]
@Biswa96 on themers I need to use git repo as tarballs has symlinks and that do not extract correctly on windows.

goocanvas3 is due to change on release for goocanvas, not sure if we can update goocanvas to version 3 and break some packages depending on goocanvas (version 2.0.4)

**Comment by Biswa96** [comment]
No no, I mean make the package name as "goocanvas" but the version 3, like Arch does. 

Speaking of symbolic links, if the symlinks does not affect the source code or assets then the `noextract` trick can be use. May the grep be with you!

**Comment by albfan** [comment]
I can update that, I see only libgda depending on goocanvas. pkg-config changes to provide goocanvas-3 so probably it will break other packages.

In this case, symbolic links are needed, they are icons like cdrom.png symlinked to optical.png or similar, so symlinks are needed.

Will rework things and recheck again.

About elementary icon themes, I will add a tar of cursors to avoid build xcursorgen, because is an endless package dependency just to turn png into xcursor format

**Comment by Biswa96** [comment]
The `pkgname` and `pkgbase` variables does not interfere with pkg-config. You can use any `pkgname` you want, maybe name it like honolulu :)

**Comment by albfan** [comment]
pkg-config is different, hope this clarifies:

- https://gitlab.gnome.org/GNOME/libgda/-/blob/master/meson.build#L62
- https://github.com/akiraux/Akira/blob/master/meson.build#L21

goocanvas 2.0.4 is goocanvas-2.0 on pkg-config and goocanvas 3.0 and above is goocanvas-3.0 on pkg-config

If we are ok with breaking other packages dependencies great.

We plan some ABI breaks on goocanvas 3.0

**Comment by lazka** [comment]
I've split out the goocanvas update to #8528

**Comment by lazka** [comment]
You can depend on goocanvas v3 now

**Comment by lazka** [comment]
> * Is gtk-update-icon-cache needed? I see in other themes

Yeah, on the theme, and the app if it installs icons.

> * xcursorgen is not available so some cursors are not generated. Should I include a tar with generated sources (they are png files)

Afaik the cursor format is different on Windows anyway, so xcursorgen wouldn't help. (I think adwaita uses this: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/src/cursors/anicursorgen.py and ).

**Comment by albfan** [comment]
Anycursongen, cool! Will rework that and finish this

**Comment by lazka** [comment]
(I'm fine with skipping cursors for now..)

**Comment by albfan** [comment]
@lazka I agree this would be better fixed upstream: https://github.com/elementary/icons/issues/1026

We can merge this way by now

**Pull request merged**
