### PR TITLE
fmt: update to 11.0.1

### PR DESCRIPTION
**Pull request by bbolli**

### CODE REVIEW

**Comment by ognevny** [comment]
please, push a rebuild for reverse dependencies

**Comment by MehdiChinoune** [comment]
> please, push a rebuild for reverse dependencies

It will timeout.

**Comment by MehdiChinoune** [comment]
- spdlog: builds
- ccache: needs a backport
- vtk: fails to build

**Comment by bbolli** [comment]
Do I have to do something here to get this PR merged?

**Comment by MehdiChinoune** [comment]
> Do I have to do something here to get this PR merged?

Fix building each dependent ppackages (the ones metioned by package-grokker CI job) to build against fmt-11.

**Comment by ognevny** [comment]
ccache update is already in repo. please, rebase your branch

**Comment by Biswa96** [comment]
fmt has been updated to 11.0.2 version in 8623d9abfaf7a3dffe0a295caee2b0236486ccec commit.

**Pull request closed without merging**
