### PR TITLE
bmake: rel=6. Fix lookup paths issue

### PR DESCRIPTION
**Pull request by ofry**
Fix bmake package lookup files. Add fallback way - lookup through native Windows path.

### CODE REVIEW

**Comment by ofry** [comment]
I will seek why it's segfaulting on x86_64.

**Comment by lazka** [comment]
We've enabled ASLR, see #6925 for a workaround in case it makes problems.

**Comment by jeremyd2019** [comment]
@lazka called it, adding -Wl,--disable-high-entropy-va to LDFLAGS fixes this segfault.  Note that bmake, when run with no arguments, segfaults in strlen rather than printing some helpful message about how to use it, so that slowed me down a bit thinking that was the segfault in question.

**Comment by lazka** [comment]
@jeremyd2019 I wonder, what's the type of bugs ASLR exposes? Writing function pointers to long which then get truncated?

**Comment by mati865** [comment]
I think we have to admit that High Entropy VA for whatever reason generally doesn't work correctly. We should search for small example (probably package without dependencies) to debug it and in meantime remove `-Wl,--enable-high-entropy-va` from LDFLAGS.

**Comment by lazka** [comment]
So far all software that also supports building with MSVC works fine (glib,gtk3,pygobject for example) so I'm wondering if this isn't just exposes some latent bugs for things only built with mingw so far. Agreed on the example search..

**Comment by mati865** [comment]
MSVC uses UCRT though. I want to experiment with different mingw-w64 configurations and toolchains but I need small example for it.

**Comment by mati865** [comment]
Here is the bmake backtrace:
```
(lldb) r
Process 4012 launched: 'D:\Projekty\msys2\MINGW-packages\mingw-w64-bmake\src\mingw64_nt-10.0-190413-x86_64\bmake.exe' (x
86_64)
Process 4012 stopped
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x7ffcdfc4d2f1: Access violation reading location
 0x00000000
    frame #0: 0x00007ffcdfc4d2f1 msvcrt.dll`strlen + 49
msvcrt.dll`strlen:
->  0x7ffcdfc4d2f1 <+49>: movq   (%rax), %rdx
    0x7ffcdfc4d2f4 <+52>: movq   %r8, %r9
    0x7ffcdfc4d2f7 <+55>: addq   $0x8, %rax
    0x7ffcdfc4d2fb <+59>: addq   %rdx, %r9
(lldb) bt
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x7ffcdfc4d2f1: Access violation reading location
 0x00000000
  * frame #0: 0x00007ffcdfc4d2f1 msvcrt.dll`strlen + 49
    frame #1: 0x00007ff7dc96602c bmake.exe`str_concat + 28
    frame #2: 0x00007ff7dc951f15 bmake.exe`Cmd_Exec + 165
    frame #3: 0x00007ff7dc98f171 bmake.exe`main + 753
    frame #4: 0x00007ff7dc9513c1 bmake.exe`__tmainCRTStartup at crtexe.c:335:15
    frame #5: 0x00007ff7dc9514f6 bmake.exe`mainCRTStartup at crtexe.c:219:9
    frame #6: 0x00007ffcdf066fd4 kernel32.dll`BaseThreadInitThunk + 20
    frame #7: 0x00007ffcdfdbcec1 ntdll.dll`RtlUserThreadStart + 33
```
For me as a novice it seems possible this was pointer truncation issue somewhere is bmake and `strlen` was called with "wrong" pointer.

**Comment by jeremyd2019** [comment]
>Note that bmake, when run with no arguments, segfaults in strlen rather than printing some helpful message about how to use it, so that slowed me down a bit thinking that was the segfault in question.

@mati865 are you sure that's not the red herring I described?  Looks just like it.

**Comment by ofry** [comment]
There are source code of bmake Windows port: https://github.com/ofry/bmake/tree/port-20181221

If anyone can give me clue what's really happened and where are actual bug, I will have really happy :+1:

**Comment by ofry** [comment]
@mati865 Could you use something like `bt full` on GDB? Then it also will print some variable values too...

**Comment by jeremyd2019** [comment]
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x77069cc0 in strlen () from C:\WINDOWS\System32\msvcrt.dll
(gdb) bt
#0  0x77069cc0 in strlen () from C:\WINDOWS\System32\msvcrt.dll
#1  0x004157ff in str_concat (s1=s1@entry=0x0,
    s2=s2@entry=0x43d317 "usr\\bin\\bash.exe", flags=flags@entry=0)
    at /usr/src/debug/bmake/str.c:101
#2  0x00402392 in Cmd_Exec (
    cmd=0x2e933b8 "cygpath -u \"T:\\mingw-w64-bmake\\src\\mingw32_nt-10.0-183633-i686\\bmake.exe\"", errnum=errnum@entry=0x274fd6c)
    at /usr/src/debug/bmake/main.c:1731
#3  0x00403f82 in main (argc=1, argv=0x2e915d0)
    at /usr/src/debug/bmake/main.c:1220
```

**Comment by ofry** [comment]
@jeremyd2019 Could you do `bt full` instead of `bt`?

**Comment by mati865** [comment]
@ofry `bt full` in GDB gives me only:
```
(gdb) bt full
#0  0x00007ffbc6a1d2f1 in strlen () from C:\WINDOWS\System32\msvcrt.dll
No symbol table info available.
#1  0x00007ff72e02602c in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
LLDB which I pasted before doesn't seem to support `bt full`.

**Comment by jeremyd2019** [comment]
My backtrace was from my 'red herring' with dynamicbase disabled.
```
#0  0x77069cc0 in strlen () from C:\WINDOWS\System32\msvcrt.dll
No symbol table info available.
#1  0x004157ff in str_concat (s1=s1@entry=0x0,
    s2=s2@entry=0x43d317 "usr\\bin\\bash.exe", flags=flags@entry=0)
    at /usr/src/debug/bmake/str.c:101
        len1 = <optimized out>
        len2 = <optimized out>
        result = <optimized out>
#2  0x00402392 in Cmd_Exec (
    cmd=0x1e34b0 "cygpath -u \"D:\\t\\msys32\\home\\jeremyd\\MINGW-packages\\mingw-w64-bmake\\src\\mingw32_nt-10.0-183633-i686\\bmake.exe\"",
    errnum=errnum@entry=0x274fd6c) at /usr/src/debug/bmake/main.c:1731
        args = {0x441bc4 <__re_error_msgid+644> "cygpath -u",
          0x3040 <error: Cannot access memory at address 0x3040>, 0x0,
          0x4022f7 <Cmd_Exec+13> ")Ä<'$P0"}
        fds = <optimized out>
        cpid = <optimized out>
        pid = <optimized out>
        res = <optimized out>
        sysRootPath = 0x0
        status = <optimized out>
        command = '\000' <repeats 4095 times>
        escapedCmd = '\000' <repeats 4095 times>
        escapedCmdLaunchList = '\000' <repeats 4095 times>
        stdout_data = <error reading variable stdout_data (value requires 16777216 bytes, which is more than max-value-size)>
        stderr_data = <error reading variable stderr_data (value requires 16777216 bytes, which is more than max-value-size)>
        exit_code = 0
        cp = <optimized out>
        cc = <optimized out>
        savederr = <optimized out>
#3  0x00403f82 in main (argc=1, argv=0x1e15f8) at /usr/src/debug/bmake/main.c:1220
        outOfDate = <optimized out>
        sb = {st_dev = 4199647, st_ino = 49360, st_mode = 66, st_nlink = 6710, st_uid = 30629, st_gid = 0, st_rdev = 1, st_size = 98, st_atime = 1971740, st_mtime = 41221992, st_ctime = 4374848}
        sa = {st_dev = 0, st_ino = 49360, st_mode = 66, st_nlink = -404, st_uid = 628, st_gid = 0, st_rdev = 41222092, st_size = 1996737728, st_atime = 2129962820, st_mtime = -2, st_ctime = 41221992}
        p1 = 0x1e1638 "D:\\t\\msys32\\home\\jeremyd\\MINGW-packages\\mingw-w64-b
make\\src\\mingw32_nt-10.0-183633-i686\\bmake.exe"
        path = <optimized out>
        mdpath = "à'\036\000à'\036\000\000\000\036\000a\000\000P\000\000\036\000Oyt\002Oyt\002¢▌°wX\002\036\000y▌°wO>%Y\000\000\036\000à'\036\000à'\036\000\000\000\036\000a\000\000P\004\000\000\000\200\000\000\000ä'\036\001\230yt\002«A£w4_t\002psªw\210\000L"_ÿÿÿôyt\002P_«wà'\036\000\b\000\000\000à'\036\000è'\036\000'CRG\000\000\000\000D_t\002,q\002w\000\000\036\000\000\000\000\000à'\036\000(I\210\v\b\000\000\000à'\036\000è'\036\000è'\036\000(_t\002oo\004w\034C\tw\200\000\000\000\b_t\002ì'\036\000@_t\002"...
        error = 0x0
        machine = 0x274fb5c "i686"
        machine_arch = 0x43d862 "i686"
        syspath = 0x0
        sysMkPath = <optimized out>
        cp = 0x0
        start = <optimized out>
        defsyspath = "D:/t/msys32/mingw32/share/mk"
        found_path = '\000' <repeats 11 times>, "\b\000☼üt\002\063"°w\001\000\000\000\000\000\b\000\000\000\000\000\001\000\000\000\000\000\b\000\000\000\000\000\000\000\b\000\000\000\000\000\000yt\002">°wX\002\b\000}>°w\000>%Y\000\000\b\000\000\000\b\000b\000\000@.\000d\000l\000l\000p\000\000\000Iüt\002c\000\000P\000\000\b\000 z\b\000\001\000\000\000 z\b\000r\000d\000d\000i\001¬üt\002\000\000\000\000Äyt\002psªw8\000L"_ÿÿÿOyt\002~û☼w"z\b\000O>%Y z\b\000\000\000\b\000\200\000\000\000O'\036\000J,_w`(\036\000Üv¡w\b\000\000\000"...
        rightnow = {tv_sec = 1599415412, tv_usec = 267041}
        utsname = {nodename = "localhost\000\b\000\230B\b\000\220C\b\000\002\000\004\006\000\000\000\000\000\000\b\000\177▌☼w\004\000\000\000äot\002\000\000\b\000±F¥w B\b\000\000\000\000\000òJ¥wäz%Y\000\000\b\000à\000\000\000\210ùt\002\000\000\000\000qú☼w0^\b\000\000\000\b\000\002\000\004\006Fú☼w;\001\000\000p\002\b\000\000\000\b\000A\000\b\000\000\000\b\000°±\b\000\b¶\b\000\034\000\004\030\000\000\000\000\000\000\b\000\177▌☼w\177\000\000\000Tùt\002\000\000\b\000IF¥w,±\b\000@\004\000\000òJ¥wTY%Y\000\000\b\000@\004\000\000oùt\002\200ot\002\000\000\b\000"..., sysname = "MINGW32_NT-10.0\000\bY\b\000Dù\005\000\000¶\b\000\230B\b\000_ÿÿÿ\001\000\000\000\000\000\000\000\177\000\000\000T\001\000Y\000\000\b\000 \016\000\000\037\000\000\000\177\000\000\000A\000\b\000 B\b\000A\000\b\000Oot\002\020Iªw
\034ùt\002ü\000\005\000\000\000\005\000\002\000\000\000\t\000\000\000t\027\005\000èùt\002\220ùt\002l\000\000\000Pùt\002\271\001☼wDút\002\001\000\000\000\001\000\000\000\220ùt\002t\027\005\000\000\000\000\000e\002☼wOùt\002d\033\005\000\030\034\005\000\004\000\000\000\020º\n\022\002\000\000\000\001\000\000\000A\000\b\000\002\000\000\000'\004\000\000"..., release = "Windows 10.0\000ùt\002,ùt\002\024ût\002☼út\002\000\000\000\000IF¥wo\025\036\000\000\000\000\000t\027\005\000'\004\000\000\020º\n\022\001\000\000\000\000`-\000\000p-\000\030\000\000\000\003\000\000\000\000\000\000\000\002\000\000\000\003\000\000\000\002\000\000\000\006\000\000\000,út\002·ù£w\003\000\000\000\000\000\000\000\002\000\000\000Dút\002èùt\002,üt\002\000\000\000\000\024ú£w,±\b\000@", '\000' <repeats 63 times>..., version =
 "\000\000\000\000\000\000\002\000xút\002xút\002xút\002,üt\002÷\a☼w\024ût\002\000\000\000\000,\000\000\000\b\000\025A\024ût\002\024ût\002Äüt\002\020º\n\022\000\000\000\000\000\000\000\000)÷£w$\000&\000"z\b\000\000\000\000\000\000\000¥w", '\000' <repeats 12 times>, "\005\000\000\000c\001\000P\000\000\b\000\020º\n\022\230üt\002Äyt\002\000E²w\230üt\002\000\000\000\000\034ût\002\065\001\000A\034ût\002\026\016☼w'\016☼wÄyt\002\230üt\002 \000\000\000@ût\002 \000\000\000l\000\000\000\230üt\002\b\000\000\000p\002\b\000\000\000\b\000A\000\b\000\000\000"..., machine = "i686\000z\b\000\000\000\b\000|üt\002)\000\a.ê"°wX\002\b\000A"°wO\235%Y\000\000\b\000p\000\000\000b\000\000@\000\000\000\000\000\000\b\000\b\000\000\000\b\000\000\000\000\000\b\000 z\b\000c\001\000P\020\026\036\000\000\000\000\000Oz\b\000 z\b\000\000\000\000\000\001\000\000\000|ût\002\000\000\000\000\000\000\000\000psªw\000\000\000\000_ÿ\t\000,yt\002\215\064¥w&\000\000\000\t\000\004\r\000\000\b\000Lüt\002\000\000\000\000\001\000\001\000àz\b\000\000\000¡w\000\000\000\000\b", '\000' <repeats 15 times>, "düt\002psªwP)L"_ÿÿÿ"...}
```

**Comment by jeremyd2019** [comment]
Can I also comment on the oddness of a mingw package looking for usr\\bin\\bash.exe?

**Comment by ofry** [comment]
> 
> 
> Can I also comment on the oddness of a mingw package looking for usr\bin\bash.exe?

It looking

```
    const char *sysRootPath = getenv("SYSROOTWINDOWSPATH");
```

`usr\bin\bash.exe` in this directory. 

When this package installed, it exported:

```
export SYSROOTWINDOWSPATH=$(cygpath -w /);
```

**Comment by jeremyd2019** [comment]
Where's the prototype/header for getUnixPathCmd?  Is it relying on the default int return, resulting in a truncated pointer?

**Comment by jeremyd2019** [comment]
Yep, that seems to be the cause of the crash with high-entropy-va.  Note there are several more 'implicit declaration of function' warnings, and actually quite a few warnings, in this code.

**Comment by ofry** [comment]
@jeremyd2019 Thank you for finding this bug.

**Pull request merged**
