### PR TITLE
enable building as static library (untested)

### PR DESCRIPTION
**Pull request by fundies**
Hoping this setting will enable the static version to be built. I don't have windows so will need verified.

### CODE REVIEW

**Comment by mati865** [comment]
Error from CI:
`unrecognized arguments: --default_library ../libepoxy-1.5.3`

**Comment by fundies** [comment]
https://mesonbuild.com/Builtin-options.html according to the meson docs that's the option. Maybe someone more familiar with meson can help

**Comment by fundies** [comment]
seems to build. How can I conform the .a file is actually in the pkgbuild?

**Comment by mati865** [comment]
I don't know if CI uploads artifacts somewhere. If not you will have to build it locally.

**Comment by fundies** [comment]
Well I don't got windows or mingw so hopefully someone else can confirm all is well and merge it.

**Comment by RobertBColton** [comment]
Confirmed working here in #5059 on Windows after updating the package.

**Pull request merged**
