### PR TITLE
pango: update to 1.50.0

### PR DESCRIPTION
**Pull request by lb90**

### CODE REVIEW

**Comment by lb90** [comment]
I have tested the new Pango release and I couldn't find any regression, looks ok to me

**Comment by lazka** [comment]
clang build is failing:

```
/pango/pango-tabs.c
  ../pango-1.50.0/pango/pango-tabs.c:621:3: error: implicit declaration of function 'qsort' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    qsort (tab_array->tabs, tab_array->size, sizeof (PangoTab), compare_tabs);
    ^
  1 error generated.
```

maybe a missing include?

**Comment by lb90** [comment]
Yep, let me check that...

**Comment by Biswa96** [comment]
I have created a merge request in upstream here https://gitlab.gnome.org/GNOME/pango/-/merge_requests/532. Feel free to import the patch here.

**Comment by lb90** [comment]
Thanks, @Biswa96!!!

**Comment by lb90** [comment]
Opened https://github.com/msys2/MINGW-packages/pull/10308

**Pull request merged**
