### PR TITLE
qt6-base: Fix zombie processes due to qt dbus

### LINKED ISSUE #13198: Kate not completely quit
### Description

mingw-w64-i686-kate 22.08.1-1 on Windows 10 21H2 x64   
Kate not completely quit.   
I need end it manually in the task manager.   

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 x64 19044.1526

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Kate.exe is not in the processes list of task manager.  

### Actual behavior

Kate.exe is still in the processes list of task manager.  

### Repro steps

1. Run kate   
2. Close kate   

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by Biswa96**
Similar as f6eacbcdd74cc836294e8e7337c5d3cf772a3117

Fixes #13198 (but with qt6)

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
I have dropped the patch with 6.7.0 update as It no longer applies.
Maybe take a deeper look at the code and patch it accordingly.

**Comment by Biswa96** [comment]
The code was moved from qdbusconnection.cpp to qdbusconnectionmanager.cpp. I have tried to apply the same change but it did not fix the issue.

```diff
--- a/src/dbus/qdbusconnectionmanager.cpp
+++ a/src/dbus/qdbusconnectionmanager.cpp
@@ -103,6 +103,10 @@
 
     moveToThread(this);         // ugly, don't do this in other projects
 
+    qAddPostRoutine([]() {
+        QMetaObject::invokeMethod(QDBusConnectionManager::instance(), "quit");
+    });
+
 #ifdef Q_OS_WIN
     // prevent the library from being unloaded on Windows. See comments in the function.
     preventDllUnload();
```

We've to wait for KDE to update their patches.

**Comment by Biswa96** [comment]
The code was moved from qdbusconnection.cpp to qdbusconnectionmanager.cpp. I have tried to apply the same change but it did not fix the issue.

```diff
--- a/src/dbus/qdbusconnectionmanager.cpp
+++ a/src/dbus/qdbusconnectionmanager.cpp
@@ -103,6 +103,10 @@
 
     moveToThread(this);         // ugly, don't do this in other projects
 
+    qAddPostRoutine([]() {
+        QMetaObject::invokeMethod(QDBusConnectionManager::instance(), "quit");
+    });
+
 #ifdef Q_OS_WIN
     // prevent the library from being unloaded on Windows. See comments in the function.
     preventDllUnload();
```

We've to wait for KDE devs when they update qt6.

**Comment by hmartinez82** [comment]
@Biswa96 Does it mean that any code that links to the DBus module will see this issue again? :(

**Comment by Biswa96** [comment]
This patch has been removed and does not apply on current qt code. The kde apps are working fine in my setup without this patch.

**Comment by hmartinez82** [comment]
I had to do this https://github.com/msys2/MINGW-packages/pull/21111/files#diff-98cfc4f9df3381906043a2882dcad13797ef9d1cb58b0893884a1ab7a0618205R39 for the app to start closing in the end again :(

**Pull request merged**
