### PR TITLE
vapoursynth: update to R57

### PR DESCRIPTION
**Pull request by MehdiChinoune**
The plugins were moved to their own repos:
see: https://github.com/vapoursynth/vapoursynth/commit/67fa8c5

### CODE REVIEW

**Comment by lazka** [comment]
> The plugins were moved to their own repos:

does this mean we should package them?

**Comment by MehdiChinoune** [comment]
> > The plugins were moved to their own repos:
> 
> does this mean we should package them?

I don't know!. I don't use it.

**Comment by lazka** [comment]
:)

@ZachBacon any thoughts on this, since you added it initially

**Comment by ZachBacon** [comment]
> :)
> 
> @ZachBacon any thoughts on this, since you added it initially

I mean sure, though I don't remember adding it initially xD (poor memory is both a blessing and a curse)

**Comment by lazka** [comment]
ok, thanks, let's merge and see then

**Pull request merged**
