### PR TITLE
mold: enable lto support

### PR DESCRIPTION
**Pull request by yujincheng08**
Tested it works with `LLVMgold.dll`

### CODE REVIEW

**Comment by ognevny** [comment]
looks tricky. can you change it so it can be proposed upstream?

**Comment by yujincheng08** [comment]
yes, I asked upstream and they saied they would merge it.

**Comment by lazka** [comment]
got any links for that?

**Comment by yujincheng08** [comment]
https://github.com/rui314/mold/pull/1283#issuecomment-2179669335

**Comment by yujincheng08** [comment]
upstream merged https://github.com/rui314/mold/pull/1287

**Comment by ognevny** [comment]
> upstream merged https://github.com/rui314/mold/pull/1287

feel free to backport this change

**Pull request closed without merging**
