### PR TITLE
hexchat: Add packages

### PR DESCRIPTION
**Pull request by Biswa96**
Please review. @ZachBacon

### CODE REVIEW

**Comment by ZachBacon** [comment]
The next step is to FHS how it loads plugins, by default it will not load plugins from the level hexchat.exe is in, and then try to load it from %APPDATA%/hexchat. I think the relevant code for plugin loading is in cfgfiles.c  under src/common.

**Comment by Biswa96** [comment]
There are many things to be fixed. This is just beginning. Did you test any package from artifact? I'm little concerned about dependencies.

**Comment by ZachBacon** [comment]
> There are many things to be fixed. This is just beginning. Did you test any package from artifact? I'm little concerned about dependencies.

Not yet, I literally just woke up. Haven't made my way to the computer yet, that's just my first glance view.

**Comment by ZachBacon** [comment]
@Biswa96 you'll have to forgive me, how do I download the artifact?

**Comment by ZachBacon** [comment]
never mind, found out how.

**Comment by Biswa96** [comment]
No problem. From this link https://github.com/msys2/MINGW-packages/actions/runs/1674803415 download the ZIP file > extract .zst > install it with `pacman -U` command.

**Comment by ZachBacon** [comment]
> No problem. From this link https://github.com/msys2/MINGW-packages/actions/runs/1674803415 download the ZIP file > extract .zst > install it with `pacman -U` command.

as I stated, I found out how xD

**Comment by ZachBacon** [comment]
Anyways first glance, you disable dbus. But included dbus-glib as a dependency. Dbus-glib can be removed if dbus is disabled, and cfgfiles.c will need to be patched as well for the plugin location loading.

**Comment by ZachBacon** [comment]
actually I kinda think it's in plugin.c now. It's been a little bit since I looked at the plugin situation

**Comment by ZachBacon** [comment]
Also I the symbols aren't used in some of the plugins, like python No hexchat_plugin_init symbol; is this really a HexChat plugin?

**Pull request merged**
