### PR TITLE
CI: Move from deprecated set-output

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Review by naveen521kk — APPROVED** [review]
lgtm

**Comment by naveen521kk** [comment]
Actually, it would be better to write it directly to `$GITHUB_OUTPUT` inside that script but this should also work I think.

**Comment by MehdiChinoune** [comment]
> Actually, it would be better to write it directly to `$GITHUB_OUTPUT` inside that script but this should also work I think.

$GITHUB_OUTPUT is an environment file not an environment variable.

**Comment by naveen521kk** [comment]
> $GITHUB_OUTPUT is an environment file not an environment variable.

Hmm, wondering what an "environment file" is. I thought `$GITHUB_OUTPUT` is an environment variable containing a path to a file which we can write to for setting the output.

**Comment by naveen521kk** [comment]
By the way, `$GITHUB_OUTPUT` is an environment variable containing a path to a file, see https://github.com/msys2/MINGW-packages/pull/13710/.

**Comment by MehdiChinoune** [comment]
> By the way, `$GITHUB_OUTPUT` is an environment variable containing a path to a file, see #13710.

Yes, That what I meant. You couldn't set it as `GITHUB_OUTPUT=`.

**Pull request merged**
