### PR TITLE
libplacebo: update to 6.292.1

### PR DESCRIPTION
**Pull request by haasn**
Untested, but should be straightforward

### CODE REVIEW

**Comment by lazka** [comment]
looks like ffmpeg isn't compatible yet

```
C:/_/B/src/ffmpeg-6.0/libavfilter/vf_libplacebo.c:46:28: error: initializer element is not a compile-time constant
      [TONE_MAP_AUTO]      = &pl_tone_map_auto,

  C:/_/B/src/ffmpeg-6.0/libavfilter/vf_libplacebo.c:461:10: error: field designator 'force_icc_lut' does not refer to any field in type 'struct pl_render_params'
          .force_icc_lut = s->force_icc_lut,
```

**Comment by lazka** [comment]
Debian already has some backports we could copy: https://sources.debian.org/patches/ffmpeg/7:6.0-5/

**Comment by kasper93** [comment]
As a reminder this update is blocked by https://github.com/msys2/MINGW-packages/pull/16953 and that's why I didn't bother to do it.

**Comment by lazka** [comment]
vlc also doesn't build:

```
2023-08-06T23:22:49.7992401Z In file included from C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.c:44:
2023-08-06T23:22:49.8614303Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:133:5: error: 'PL_TONE_MAPPING_HABLE' undeclared here (not in a function)
2023-08-06T23:22:50.0020077Z   133 |     PL_TONE_MAPPING_HABLE,
2023-08-06T23:22:50.0645244Z       |     ^~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:50.1062687Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:134:5: error: 'PL_TONE_MAPPING_MOBIUS' undeclared here (not in a function)
2023-08-06T23:22:50.1310255Z   134 |     PL_TONE_MAPPING_MOBIUS,
2023-08-06T23:22:50.1448132Z       |     ^~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:50.1469043Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:135:5: error: 'PL_TONE_MAPPING_REINHARD' undeclared here (not in a function)
2023-08-06T23:22:50.1479861Z   135 |     PL_TONE_MAPPING_REINHARD,
2023-08-06T23:22:50.1610281Z       |     ^~~~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:50.1658329Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:136:5: error: 'PL_TONE_MAPPING_GAMMA' undeclared here (not in a function); did you mean 'PL_TONE_MAP_LUMA'?
2023-08-06T23:22:50.1702544Z   136 |     PL_TONE_MAPPING_GAMMA,
2023-08-06T23:22:50.1764528Z       |     ^~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:50.1790845Z       |     PL_TONE_MAP_LUMA
2023-08-06T23:22:50.2522313Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:137:5: error: 'PL_TONE_MAPPING_LINEAR' undeclared here (not in a function); did you mean 'PL_TONE_MAP_LUMA'?
2023-08-06T23:22:50.2527863Z   137 |     PL_TONE_MAPPING_LINEAR,
2023-08-06T23:22:50.2563288Z       |     ^~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:50.2592753Z       |     PL_TONE_MAP_LUMA
2023-08-06T23:22:50.2971095Z   CC       video_output/opengl/libgl_plugin_la-fragment_shaders.lo
2023-08-06T23:22:50.3818292Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:138:5: error: 'PL_TONE_MAPPING_CLIP' undeclared here (not in a function)
2023-08-06T23:22:50.3932379Z   138 |     PL_TONE_MAPPING_CLIP,
2023-08-06T23:22:50.3945256Z       |     ^~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:50.4842771Z make[4]: *** [Makefile:22447: video_output/opengl/libgl_plugin_la-vout_helper.lo] Error 1
2023-08-06T23:22:50.4877093Z make[4]: *** Waiting for unfinished jobs....
2023-08-06T23:22:51.7605440Z In file included from C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:36:
2023-08-06T23:22:51.7606775Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:133:5: error: 'PL_TONE_MAPPING_HABLE' undeclared here (not in a function)
2023-08-06T23:22:51.7607629Z   133 |     PL_TONE_MAPPING_HABLE,
2023-08-06T23:22:51.7608187Z       |     ^~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:51.8769619Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:134:5: error: 'PL_TONE_MAPPING_MOBIUS' undeclared here (not in a function)
2023-08-06T23:22:51.8770670Z   134 |     PL_TONE_MAPPING_MOBIUS,
2023-08-06T23:22:51.8771311Z       |     ^~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.0030082Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:135:5: error: 'PL_TONE_MAPPING_REINHARD' undeclared here (not in a function)
2023-08-06T23:22:52.0030910Z   135 |     PL_TONE_MAPPING_REINHARD,
2023-08-06T23:22:52.0031417Z       |     ^~~~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.1081805Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:136:5: error: 'PL_TONE_MAPPING_GAMMA' undeclared here (not in a function); did you mean 'PL_TONE_MAP_LUMA'?
2023-08-06T23:22:52.1082932Z   136 |     PL_TONE_MAPPING_GAMMA,
2023-08-06T23:22:52.1083532Z       |     ^~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.1084050Z       |     PL_TONE_MAP_LUMA
2023-08-06T23:22:52.2207205Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:137:5: error: 'PL_TONE_MAPPING_LINEAR' undeclared here (not in a function); did you mean 'PL_TONE_MAP_LUMA'?
2023-08-06T23:22:52.2208040Z   137 |     PL_TONE_MAPPING_LINEAR,
2023-08-06T23:22:52.2208539Z       |     ^~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.2209011Z       |     PL_TONE_MAP_LUMA
2023-08-06T23:22:52.3254835Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/vout_helper.h:138:5: error: 'PL_TONE_MAPPING_CLIP' undeclared here (not in a function)
2023-08-06T23:22:52.3255926Z   138 |     PL_TONE_MAPPING_CLIP,
2023-08-06T23:22:52.3256565Z       |     ^~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.4174578Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c: In function 'pl_color_space_from_video_format':
2023-08-06T23:22:52.4176879Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:534:45: error: 'PL_COLOR_REF_WHITE' undeclared (first use in this function); did you mean 'PL_COLOR_SDR_WHITE'?
2023-08-06T23:22:52.4177788Z   534 |     float sig_peak = fmt->lighting.MaxCLL / PL_COLOR_REF_WHITE;
2023-08-06T23:22:52.4178395Z       |                                             ^~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.4178864Z       |                                             PL_COLOR_SDR_WHITE
2023-08-06T23:22:52.4180362Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:534:45: note: each undeclared identifier is reported only once for each function it appears in
2023-08-06T23:22:52.4184113Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:550:10: error: 'struct pl_color_space' has no member named 'light'
2023-08-06T23:22:52.4184789Z   550 |         .light     = PL_COLOR_LIGHT_UNKNOWN,
2023-08-06T23:22:52.4185227Z       |          ^~~~~
2023-08-06T23:22:52.5216691Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:550:22: error: 'PL_COLOR_LIGHT_UNKNOWN' undeclared (first use in this function); did you mean 'PL_COLOR_TRC_UNKNOWN'?
2023-08-06T23:22:52.5217728Z   550 |         .light     = PL_COLOR_LIGHT_UNKNOWN,
2023-08-06T23:22:52.5218282Z       |                      ^~~~~~~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.5218791Z       |                      PL_COLOR_TRC_UNKNOWN
2023-08-06T23:22:52.5219908Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:551:10: error: 'struct pl_color_space' has no member named 'sig_peak'
2023-08-06T23:22:52.5221077Z   551 |         .sig_peak  = sig_peak,
2023-08-06T23:22:52.5221569Z       |          ^~~~~~~~
2023-08-06T23:22:52.5222450Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:552:10: error: 'struct pl_color_space' has no member named 'sig_avg'
2023-08-06T23:22:52.5223132Z   552 |         .sig_avg   = sig_avg,
2023-08-06T23:22:52.5223550Z       |          ^~~~~~~
2023-08-06T23:22:52.5235885Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c: In function 'opengl_fragment_shader_init_impl':
2023-08-06T23:22:52.5240759Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:617:22: error: 'struct pl_color_map_params' has no member named 'tone_mapping_algo'; did you mean 'tone_mapping_param'?
2023-08-06T23:22:52.5241927Z   617 |         color_params.tone_mapping_algo = var_InheritInteger(tc->gl, "tone-mapping");
2023-08-06T23:22:52.5242566Z       |                      ^~~~~~~~~~~~~~~~~
2023-08-06T23:22:52.5243067Z       |                      tone_mapping_param
2023-08-06T23:22:52.5245699Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:620:21: error: 'struct pl_color_map_params' has no member named 'desaturation_strength'
2023-08-06T23:22:52.5246720Z   620 |         color_params.desaturation_strength = var_InheritFloat(tc->gl, "desat-strength");
2023-08-06T23:22:52.5247328Z       |                     ^
2023-08-06T23:22:52.5249771Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:621:21: error: 'struct pl_color_map_params' has no member named 'desaturation_exponent'
2023-08-06T23:22:52.5250810Z   621 |         color_params.desaturation_exponent = var_InheritFloat(tc->gl, "desat-exponent");
2023-08-06T23:22:52.5251424Z       |                     ^
2023-08-06T23:22:52.5253805Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:622:21: error: 'struct pl_color_map_params' has no member named 'desaturation_base'
2023-08-06T23:22:52.5254839Z   622 |         color_params.desaturation_base = var_InheritFloat(tc->gl, "desat-base");
2023-08-06T23:22:52.5255436Z       |                     ^
2023-08-06T23:22:52.5257837Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:623:21: error: 'struct pl_color_map_params' has no member named 'max_boost'
2023-08-06T23:22:52.5258769Z   623 |         color_params.max_boost = var_InheritFloat(tc->gl, "max-boost");
2023-08-06T23:22:52.5259339Z       |                     ^
2023-08-06T23:22:52.5263247Z C:/_/B/src/vlc-3.0.18/modules/video_output/opengl/fragment_shaders.c:627:22: error: 'struct pl_color_map_params' has no member named 'gamut_warning'; did you mean 'gamut_mapping'?
2023-08-06T23:22:52.5264316Z   627 |         color_params.gamut_warning = var_InheritBool(tc->gl, "tone-mapping-warn");
2023-08-06T23:22:52.5264929Z       |                      ^~~~~~~~~~~~~
2023-08-06T23:22:52.5265408Z       |                      gamut_mapping
```

**Comment by haasn** [comment]
known limitation, vlc **3.0** needs to be built against libplacebo v5 (technically v4 but patches for v5 compatibility are common), vlc 4.0 is required for libplacebo 6+

**Comment by lazka** [comment]
Thanks for the info. 

Then I'm not quite sure how to proceed here.

**Comment by haasn** [comment]
In various other systems we achieved this by splitting libplacebo by major version, e.g. `libplacebo5` and `libplacebo6`. This is the usual convention for how to handle dependencies on old libraries by stale software.

**Comment by lazka** [comment]
ok, thanks, let's give that a try then.

**Comment by lazka** [comment]
some progress in #19148

**Comment by lazka** [comment]
Now with only VLC not being compatible, I wonder if we should just build vlc without libplacebo support. From what I see this only affects the opengl video output, which is not the default, and at least on my machine fails to produce output if I select it.

**Comment by lazka** [comment]
> Now with only VLC not being compatible, I wonder if we should just build vlc without libplacebo support. From what I see this only affects the opengl video output, which is not the default, and at least on my machine fails to produce output if I select it.

done in #19173

**Comment by lazka** [comment]
> In various other systems we achieved this by splitting libplacebo by major version, e.g. `libplacebo5` and `libplacebo6`. This is the usual convention for how to handle dependencies on old libraries by stale software.

That's not possible afaics since everything using libplacebo also uses ffmpeg, and vlc also uses ffmpeg. So the only thing left is statically linking it in VLC.

**Pull request closed without merging**
