### PR TITLE
[do not merge] Fix shiboken2 and pyside2 build issues

### PR DESCRIPTION
**Pull request by raccoonmonk**
There is at least one license issue though. PySide2 is built with Qt Data Visualization module which is not available under LGPL. https://doc.qt.io/qt-5/qtmodules.html#qt-add-ons
The question is should I exclude it from build or mark the Pyside2 package with more restrictive "GPL".

### CODE REVIEW

**Comment by raccoonmonk** [comment]
Do I need to break it into 2 separate pull requests? pyside2 has dependency on shiboken2

**Comment by Biswa96** [comment]
The `pkgrel` should be 1 as the `pkgver` is increased. Also I think the CI did not build the new dependency `mingw-w64-shiboken2-qt5` first and hence the build failed.

**Comment by Biswa96** [comment]
The `pkgrel` should be 1 as the `pkgver` is increased. Also I think the CI did not build the new dependency `mingw-w64-shiboken2-qt5` first and hence the build failed. Generally Ci automatically detects the dependency and build it first but not here. Handing over to CI experts here.

**Comment by mati865** [comment]
If you split both packages into own commits CI should follow that order.

**Comment by raccoonmonk** [comment]
@mati865 CI didn't follow the commit order.

**Comment by mati865** [comment]
Packages are not built on CI so it shouldn't matter. CI is used only to indicate if package is likely build but it's too fragile to depend on it.

**Comment by raccoonmonk** [comment]
I see. So even if shiboken2 will be checked first pyside2 will fail anyway since it depends on shiboken. CI will not install or even build it.
I checked both of them on my machine with both x86 and x64 arch. Tests pass.
What do we do now?

**Comment by mati865** [comment]
Wait for the reviewer I suppose.

**Comment by Alexpux** [comment]
@raccoonmonk is it building for you?

**Comment by raccoonmonk** [comment]
@Alexpux it was at the time. Both x86 and x64. Plus I had made a separate configuration with tests which I successfully ran. Also both Arch.
Are there any issues? When I'll have time I can build it again with recent llvm and Qt versions. If that's the problem.

**Pull request merged**
