### PR TITLE
fmt: update to 8.0.1

### PR DESCRIPTION
**Pull request by bbolli**

### CODE REVIEW

**Comment by lazka** [comment]
Should we try to rebuild the reverse dependencies with this?

**Comment by bbolli** [comment]
If you can find them out easily, then yes, please!

**Comment by Biswa96** [comment]
Here are the list https://packages.msys2.org/package/mingw-w64-x86_64-fmt?repo=mingw64

**Comment by lazka** [comment]
Blocking on https://github.com/gabime/spdlog/issues/1975

**Comment by bbolli** [comment]
There's already a fmt v8.0.1 out...

**Comment by lazka** [comment]
Maybe we should just backport https://github.com/gabime/spdlog/pull/1976 ?

**Comment by bbolli** [comment]
So spdlog uses the packaged fmt, not a bundled one?

**Comment by lazka** [comment]
> So spdlog uses the packaged fmt, not a bundled one?

Not sure tbh

> Anyway, that PR looks low-risk, so yeah, let's to this. Should I amend this PR then?

sure

**Comment by lazka** [comment]
thanks

**Pull request merged**
