### PR TITLE
Clang: Fix lld with g++

### PR DESCRIPTION
**Pull request by orgads**
and use symlinks instead of copies for all llvm tools.

### CODE REVIEW

**Comment by orgads** [comment]
Actually, since this is a single PR for 2 changes, maybe I should only change pkgrel once?

**Comment by Alexpux** [comment]
@orgads MSYS doesnt support symlinks by default, instead it do deep copy

**Comment by orgads** [comment]
I know, but this can be controlled by the MSYS env variable. This is better than telling cmake to unconditionally copy.

I'm currently building to see how makepkg behaves.

**Comment by Alexpux** [comment]
Sorry but I will not accept this

**Comment by orgads** [comment]
Ok, I'll separate the lld fix which is more important, and we'll discuss the links later.

Notice that the lld package contains 4 or 5 identical files of ~50 MB each because links are not used.

**Comment by orgads** [comment]
Ok, I see that cmake doesn't behave well when the user doesn't have symlink permissions.

So I abandoned also the upstream change https://reviews.llvm.org/D62891

Can we consider replacing the copies with hardlinks at least when packaging? tar can preserve hardlinks.

**Comment by Alexpux** [comment]
@orgads every user install MSYS2 and packages in defferent places, so we will have troubles with hardlinks

**Pull request closed without merging**
