### PR TITLE
Add libbacktrace.pc

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by Biswa96** [comment]
1. Increase `pkgrel` variable.
2. The `prefix` variable should not be hardcoded. Maybe try something with `sed` and `${MINGW_PREFIX}`.

**Comment by taozuhong** [comment]
@Biswa96 got it, thanks for your suggestion.

**Comment by Biswa96** [comment]
Wait! pkgconfig file is not changed. mingw64 is hardcoded.

**Comment by lazka** [comment]
pkg-config ignores prefix anyway

**Pull request merged**
