### PR TITLE
reduce SDL2_Image's dependency chain

### PR DESCRIPTION
**Pull request by fabiangreffrath**
For the same reasons as outlined in https://github.com/fabiangreffrath/MINGW-packages/commit/53ce00433d4f41f6fb09470fdf5e8ec9b1ee2c42, this commit reduces SDL2_Image's dependency chain to only one hard dependency on libpng.

While PNG support is absolutely expected from an image processing library, support for TIF, JPG and WEBP is demoted to soft dependencies which rely on the corresponding libraries being installed and available to get opened at run-time.

### CODE REVIEW

**Comment by Biswa96** [comment]
Why?

**Comment by fabiangreffrath** [comment]
> Why?

For the same reasons as outlined in fabiangreffrath@53ce004

**Comment by Biswa96** [comment]
That sounds like specific to your use case. Debian and ArchLinux both do the same as this package.

**Comment by lazka** [comment]
> Debian and ArchLinux both do the same as this package.

Our target audience is more focused on bundling our build results compared to Arch/Debian, so imo we should consider it at least.

**Comment by fabiangreffrath** [comment]
> You need to bump pkgrel

Done, thanks!

**Comment by lazka** [comment]
If anyone hits any problems because of this please let us know.

**Pull request merged**
