### PR TITLE
julia: remove libgcc_s_dw2-1.dll when packaging

### PR DESCRIPTION
**Pull request by smalltalkman**
@Alexpux Sorry, my final pkgbuild file was not submitted to pr.

### CODE REVIEW

**Comment by Alexpux** [comment]
@smalltalkman see previous pull request
https://github.com/msys2/MINGW-packages/pull/5668

**Comment by smalltalkman** [comment]
@Alexpux Ok, if the 32-bit compilation is successful, I next statically link julia's dependent library.

**Comment by Alexpux** [comment]
@smalltalkman why not use system provided shared libraries for 3rdparty dependencies?

**Comment by smalltalkman** [comment]
@Alexpux 
`julia` uses its own [libuv fork](https://github.com/JuliaLang/libuv) and patched [llvm](https://github.com/JuliaLang/julia/tree/master/deps/patches). 
In addition, the system provided PCRE, GMP, MPFR can not compile `julia` correctly, LIBM and UTF8PROC have not been tested. 
Msys2 does not provide DSFMT, so it can only be compiled with downloads.

**Pull request merged**
