### PR TITLE
avrdude: update to 6.4

### PR DESCRIPTION
**Pull request by fauxpark**

### CODE REVIEW

**Comment by fauxpark** [comment]
```
==> Verifying source file signatures with gpg...
    avrdude-6.4.tar.gz ... FAILED (unknown public key 7E9EADC3030D34EB)
```

Anything I can do to fix this? I swear I've encountered this before, but not sure if/how it was resolved.

**Comment by fauxpark** [comment]
I figured that, but it wasn't working for me locally. I assume that's because CI does the additional step of receiving the keys first.

Can/should the others be removed?

**Comment by jeremyd2019** [comment]
Usually a project will publish a list of keys that can be expected to sign their releases.  I'm not finding that anywhere for avrdude.

**Comment by fauxpark** [comment]
It seems they've moved from Savannah to GitHub recently, I've filed an issue there.

**Comment by lazka** [comment]
That key is used in Arch in multiple places, so I assume it's OK, https://github.com/search?q=56628323218C669FF578705C7E9EADC3030D34EB&type=code

**Comment by lazka** [comment]
(CI currently calls `../.ci/fetch-validpgpkeys.sh` in a package directory to fetch the referenced keys)

**Pull request merged**
