### PR TITLE
poppler: Update to 0.87.0

### PR DESCRIPTION
**Pull request by hiroakit**
## Overview

Merging this PR brings the package up to date.

## Note

Ref #6342

### CODE REVIEW

**Comment by lazka** [comment]
libpoppler-97.dll -> libpoppler-98.dll, so every dependency would need to be rebuild

**Comment by hiroakit** [comment]
@lazka

Thank you.
I'll try to check dependency.

**Comment by hiroakit** [comment]
@lazka

Would you to need to rebuild these?

https://packages.msys2.org/package/mingw-w64-x86_64-poppler?repo=mingw64

- mingw-w64-x86_64-OpenSceneGraph
- mingw-w64-x86_64-cairo (make)
- mingw-w64-x86_64-evince
- mingw-w64-x86_64-gdal
- mingw-w64-x86_64-gdcm
- mingw-w64-x86_64-gimp
- mingw-w64-x86_64-graphviz
- mingw-w64-x86_64-inkscape
- mingw-w64-x86_64-kfilemetadata-qt5
- mingw-w64-x86_64-libvips
- mingw-w64-x86_64-pdf2djvu
- mingw-w64-x86_64-pdf2svg

**Comment by Alexpux** [comment]
@hiroakit yes all these packages need to be rebuilded after poppler upgrade

**Comment by Alexpux** [comment]
graphviz and inkscape not buildable right now.

**Comment by hiroakit** [comment]
Sure. I'll rebuild it.

**Pull request merged**
