### PR TITLE
ncurses: Remove pthread dependency

### PR DESCRIPTION
**Pull request by raedrizqie**
Remove pthread dependency

### CODE REVIEW

**Comment by lazka** [comment]
can you add an inline comment explaining the reason for your change?

**Comment by raedrizqie** [comment]
nanosleep is only defined in pthread library.

Python modules such as _curses, _curses_panel and readline will pull libwinpthread-1.dll silently because of this.

**Comment by lazka** [comment]
sure, I meant add a comment in the PKBUILD above the change

**Comment by Biswa96** [comment]
Wondering if it is possible to move nanosleep to mingw-w64-crt? @lhmouse

**Comment by lhmouse** [comment]
We can't *move* it, otherwise existent applications that import it from winpthreads DLL will fail to start. If we want it to be available from the CRT anyhow, we must duplicate it.

**Comment by lazka** [comment]
ncurses has a windows specific fallback, so at least for this case I don't see the value.

**Pull request merged**
