### PR TITLE
gnome-calculator: Add patches

### LINKED ISSUE #11804: gnome-calculator crash when inputting a variable name
mingw-w64-i686-gnome-calculator 42.1-1 on Windows 10 x64 21H2

reproduce:
1. run gnome-calculator
2. change to 'Advanced' mode
3. click 'x' button on the bottom row (below the button x! and |x|)
4. click the entry which shows 'Variable name'
5. input 'a'

Now the gnome-calculator crash.

### LINKED ISSUE #11848: libxml2 crash
**How to reproduce**

1. Open `gnome-calculator`
2. Open the hamburger menu
3. Open Preferences

**Backtrace**

```
Thread 22 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 20608.0x5574]
0x00007fff06cb3416 in ntdll!RtlWaitOnAddress () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007fff06cb3416 in ntdll!RtlWaitOnAddress ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007fff06c7fcb4 in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007fff06c7fae2 in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffeb9352f87 in xmlGetGlobalState ()
    at ../libxml2-2.9.14/threads.c:713
#4  0x00007ffeb935263f in __xmlDefaultBufferSize ()
    at ../libxml2-2.9.14/globals.c:828
#5  0x00007ffeb93114b9 in xmlAllocParserInputBuffer (
    enc=enc@entry=XML_CHAR_ENCODING_NONE) at ../libxml2-2.9.14/xmlIO.c:2360
#6  0x00007ffeb9311c34 in xmlParserInputBufferCreateIO (
    ioread=0x7ffeb8a7ba00, ioclose=ioclose@entry=0x7ffeb8a7bb00,
    ioctx=ioctx@entry=0x20ef4b90e70, enc=enc@entry=XML_CHAR_ENCODING_NONE)
    at ../libxml2-2.9.14/xmlIO.c:3070
#7  0x00007ffeb92fc307 in xmlCreateIOParserCtxt (sax=0xf2ea3ee890,
    user_data=0x20ef838a490, ioread=<optimized out>, ioclose=0x7ffeb8a7bb00,
    ioctx=0x20ef4b90e70, enc=XML_CHAR_ENCODING_NONE)
    at ../libxml2-2.9.14/parser.c:12612
#8  0x00007ffeb8a7beb0 in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#9  0x00007ffeb8a2f621 in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#10 0x00007ffeb8a303c1 in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#11 0x00007ffeb8ae2bd6 in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#12 0x00007ffeb8b5362e in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#13 0x00007ffeb8a7eded in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#14 0x00007ffeb8a82001 in ?? () from D:\msys64\mingw64\bin\librsvg-2-2.dll
#15 0x00007ffef57b1566 in ?? ()
   from D:\msys64\mingw64\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll
#16 0x00007ffee28ea8c7 in ?? ()
   from D:\msys64\mingw64\bin\libgdk_pixbuf-2.0-0.dll
#17 0x00007ffee28e5a0b in ?? ()
   from D:\msys64\mingw64\bin\libgdk_pixbuf-2.0-0.dll
#18 0x00007ffee28e81bc in ?? ()
   from D:\msys64\mingw64\bin\libgdk_pixbuf-2.0-0.dll
#19 0x00007ffeb9b4890a in gtk_make_symbolic_pixbuf_from_data (
    file_data=0x20efdf524a0 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg height=\"16px\" viewBox=\"0 0 16 16\" width=\"16px\" xmlns=\"http://www.w3.org/2000/svg\">\n    <path d=\"m 6.5 0 c -3.578125 0 -6.5 2.921875 -6.5 6.5 s 2.921875 6.5 "..., file_len=590, width=128, height=128, scale=1,
    debug_output_basename=0x0, error=0xf2ea3ff9c8)
    at ../gtk4/gtk/gdkpixbufutils.c:339
#20 0x00007ffeb9b48cc7 in gtk_make_symbolic_pixbuf_from_path (
    path=0x20efdf4fee0 "D:\\msys64\\mingw64\\share\\icons\\Adwaita\\scalable/actions\\edit-find-symbolic.svg", width=128, height=128, scale=1,
    error=0xf2ea3ff9c8) at ../gtk4/gtk/gdkpixbufutils.c:459
#21 0x00007ffeb995a375 in icon_ensure_texture__locked (icon=0x20efdf1ae90,
    in_thread=1) at ../gtk4/gtk/gtkicontheme.c:3794
#22 0x00007ffeb99575a1 in load_icon_thread (task=0x20efde1a6c0,
    source_object=0x20efdf1ae90, task_data=0x0, cancellable=0x0)
    at ../gtk4/gtk/gtkicontheme.c:2424
#23 0x00007ffec67f22ce in ?? () from D:\msys64\mingw64\bin\libgio-2.0-0.dll
#24 0x00007ffec7679a8f in ?? () from D:\msys64\mingw64\bin\libglib-2.0-0.dll
#25 0x00007ffec76790a1 in ?? () from D:\msys64\mingw64\bin\libglib-2.0-0.dll
#26 0x00007ffec76a8897 in ?? () from D:\msys64\mingw64\bin\libglib-2.0-0.dll
#27 0x00007fff04d5af5a in msvcrt!_beginthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#28 0x00007fff04d5b02c in msvcrt!_endthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#29 0x00007fff06227034 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#30 0x00007fff06ca2651 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#31 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

### PR DESCRIPTION
**Pull request by lb90**
Fixes #11804
Fixes #11848

### CODE REVIEW

**Comment by lazka** [comment]
blocked on #11864 currently, sry

**Comment by lazka** [comment]
> blocked on #11864 currently, sry

oh, I guess it was not related after all

**Comment by Biswa96** [comment]
> oh, I guess it was not related after all, just a similar traceback

Nope, meson/python was not guilty. The CI output was `error: failed to load doclet` which was the bug from vala. I had the fix in my mind when I opened this issue https://gitlab.gnome.org/GNOME/vala/-/issues/1302. But it was _only_ in my mind. Justice served 👨‍⚖️

**Comment by lb90** [comment]
Forgot to bump the pkgrel number 😄

Thanks!

**Comment by Biswa96** [comment]
I have just noticed that some svg files in $prefix/share/devhelp/books/GCalc-2/ are missing in the package after this change. I assume it may be due to the vala change. Investigating 🕵️

**Comment by lb90** [comment]
Ok, if neede we can add a patch to https://github.com/msys2/MINGW-packages/pull/11983

**Comment by Biswa96** [comment]
The Config.PACKAGE_DATADIR and Config.PACKAGE_VALADOC_ICONDIR are two remaining paths in vala which I have tried to replace with the same logic as previous. But with those modification, vala can not be built.

Though some svg files in $prefix/share/devhelp/books/GCalc-2/ are missing in this PR, the actual gnome-calculator package has those files. It is because vala has hardcoded paths from msys2-autobuild directories.

**Pull request merged**
