### PR TITLE
ffmpeg: Enable frei0r-plugins

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Sorry @lazka, I just discovered that ffmpeg hardcodes the paths it looks for the frei0r plugins in. I am working on making that relocatable.

Do you think I should make the new search path relative to the calling DLL or the calling EXE (when it's been called by a DLL that is)?

**Comment by lazka** [comment]
hm, I guess DLL would be less fragile, but not sure.

We need some documentation or relocation...

**Comment by lazka** [comment]
Does it break ffmpeg, or does it just not find plugins?

**Comment by Biswa96** [comment]
> Do you think I should make the new search path relative to the calling DLL or the calling EXE

Don't we already have that thingy in openssl?

**Comment by mingwandroid** [comment]
No, it only breaks if you try to specify to use the plugins and it tells you what paths it looked in when it fails so the user can, for now, put them in one of those places.

**Comment by mingwandroid** [comment]
No need for reversion, just, on my part, better testing.

**Comment by lazka** [comment]
ok, thanks

**Comment by mingwandroid** [comment]
> We need some documentation or relocation...

Agreed.

**Pull request merged**
