### PR TITLE
[new package] c3c 0.6.3

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by ognevny** [comment]
lld is installed, but it's not found. looks like it requires manual setting...

**Comment by Biswa96** [comment]
Do we need this new toolchain for any program?

**Comment by ognevny** [comment]
> Do we need this new toolchain for any program?

I saw they have CI pipeline for build it with MSYS2, so I decided to provide as it should be supported. anyway, why not?

**Comment by Biswa96** [comment]
I was just curious. No objection.

**Pull request merged**
