### PR TITLE
zig: update to 0.13.0 (clang64 only)

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by ognevny** [comment]
why draft?

**Comment by raedrizqie** [comment]
i am trying to fix llvm toolchain to use compiler-rt on non clang system, so that zig could be built for mingw/ucrt.

zig can only be built on clang64 because it uses builtin compiler-rt,, even clang32 doesnt use builtin compiler-rt, thats why zig failed to compile on clang32..

**Comment by ognevny** [comment]
> i am trying to fix llvm toolchain to use compiler-rt on non clang system, so that zig could be built for mingw/ucrt.
> 
> zig can only be built on clang64 because it uses builtin compiler-rt,, even clang32 doesnt use builtin compiler-rt, thats why zig failed to compile on clang32..

IMO 32-bit can be dropped for zig, but I don't know about ucrt/mingw64

**Comment by MehdiChinoune** [comment]
I have pushed your changes, but for clang64 and clangarm64 only.
If you want to continue working on mingw64/ucrt64, please rebase your changes.

**Comment by raedrizqie** [comment]
ok thanks

**Comment by sskras** [comment]
@ognevny commented [2 weeks ago](https://github.com/msys2/MINGW-packages/pull/21159#issuecomment-2177600973):

> IMO 32-bit can be dropped for zig, but I don't know about ucrt/mingw64

Do you suggest that because of MSYS2 dropping the 32-bit packages or something else?

**Comment by ognevny** [comment]
> Do you suggest that because of MSYS2 dropping the 32-bit packages or something else?

yes, because we don't add new packages for 32-bit

**Comment by raedrizqie** [comment]
> @raedrizqie commented [2 weeks ago](https://github.com/msys2/MINGW-packages/pull/21159#issuecomment-2176824408):
> 
> > i am trying to fix llvm toolchain to use compiler-rt on non clang system, so that zig could be built for mingw/ucrt.
> > zig can only be built on clang64 because it uses builtin compiler-rt,, even clang32 doesnt use builtin compiler-rt, thats why zig failed to compile on clang32..
> 
> Zig [0.13.0](https://ziglang.org/download/#release-0.13.0) has the official build for 32-bit Windows:
> 
> OS	Arch	Filename	Signature	Size
> Windows	x86	[zig-windows-x86-0.13.0.zip](https://ziglang.org/download/0.13.0/zig-windows-x86-0.13.0.zip)	[minisig](https://ziglang.org/download/0.13.0/zig-windows-x86-0.13.0.zip.minisig)	79.4MiB
> If Ziglang developers can do the 32-bit build, do you know what stops doing the same on MinGW?

llvm must be rebuilt with builtin compiler-rt on all environments.. i am preparing a PR to update llvm to use builtin compiler-rt, making it a pure llvm on top of mingw toolchain. emutls should be disabled (same behaviour on current clang envs) for this to work. the pure llvm toolchain will not depends on any libgcc libraries.

**Pull request closed without merging**
