### PR TITLE
Capstone: workaround on #20581

### LINKED ISSUE #20581: capstone 5.0.1 pkgconfig version is wrong
### Description / Steps to reproduce the issue

Captured this error while using xmake (pkgconf search for capstone)
https://github.com/xmake-io/xmake/issues/4940

- Build capstone package/get capstone package from pacman
- Look for capstone.pc
- Capstone version is invalid.

CLANG64 example (Tested on all envs):
```
prefix=/clang64
exec_prefix=${prefix}
libdir=/clang64/lib
includedir=/clang64/include

Name: capstone
Description: Capstone disassembly engine
Version: 5.0.
URL: https://www.capstone-engine.org/
archive=${libdir}/libcapstone.a
Libs: -L${libdir} -lcapstone
Cflags: -I${includedir}/capstone
archs=
```

### Expected behavior

Shows `5.0.1` in version

### Actual behavior

Shows `5.0.` in version

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

Extra verification:
```
$ pacman -Suy
:: Synchronizing package databases...
 clangarm64 is up to date
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang32 is up to date
 clang64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [x] MINGW64
- [x] MINGW32
- [x] UCRT64
- [X] CLANG64
- [x] CLANG32
- [x] CLANGARM64

### Are you willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by PerikiyoXD**
## Context:
Capstone issue: https://github.com/capstone-engine/capstone/issues/2310
Fixes #20581

I recommend having a look at the Capstone issue first.

Fixes the pkgconfig bogus version, using a workaround until upstream fixes the root issue.

### CODE REVIEW

**Comment by PerikiyoXD** [comment]
The SHA256 for `fix_pkgconf_version_on_cmake.patch` is `f712940d351a30b80bf70578ac4d90e82e0a626b98c0913ddcf125201f594266` which matches the one defined in PKGBUILD.

????

**Comment by PerikiyoXD** [comment]
Local execution shows sha256 is right
```
$ makepkg -f
==> Making package: mingw-w64-capstone 5.0.1-2 (Sun Apr  7 03:01:30 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found capstone-5.0.1.tar.gz
  -> Found mingw_python.patch
  -> Found fix_pkgconf_version_on_cmake.patch
==> Validating source files with sha256sums...
    capstone-5.0.1.tar.gz ... Passed
    mingw_python.patch ... Passed
    fix_pkgconf_version_on_cmake.patch ... Passed
```

**Comment by PerikiyoXD** [comment]
CRLF => LF

**Comment by PerikiyoXD** [comment]
https://github.com/msys2/MINGW-packages/actions/runs/8585054229/job/23526119178?pr=20582#step:8:19

This was failing before?

**Comment by PerikiyoXD** [comment]
https://github.com/msys2/MINGW-packages/actions/runs/8206626042/job/22446178826

Was skipped.

Seems good to me. Waiting for a review!

**Comment by PerikiyoXD** [comment]
We got a merge on upstream. Hopefully all works now?

**Comment by Biswa96** [comment]
Thank you for the contribution.

**Pull request merged**
