### PR TITLE
tiledb: fix compilation with clang

### PR DESCRIPTION
**Pull request by neheb**
Just needs -Werror disabled.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
```
  ==> Starting prepare()...
  TileDB-2.2.4/test/inputs/test_certs/2ec8ef2c.0: Can't create '\\\\?\\C:\\_\\mingw-w64-tiledb\\src\\TileDB-2.2.4\\test\\inputs\\test_certs\\2ec8ef2c.0'
```

CI failed while extracting files. It looks like we need the `noextract` workaround. Or ZIP file can also be used as source.

**Comment by neheb** [comment]
No idea what noextract is.

**Comment by jeremyd2019** [comment]
https://wiki.archlinux.org/title/PKGBUILD#noextract

**Comment by neheb** [comment]
hrm OK. Not sure how it would be done here though. Add noextract and run gnutar?

**Comment by jeremyd2019** [comment]
> hrm OK. Not sure how it would be done here though. Add noextract and run gnutar?

Exactly.  Sometimes with an `|| true` if it's a particularly pernicious one.

**Pull request closed without merging**
