### PR TITLE
angleproject: update to 2.1.r21358

### PR DESCRIPTION
**Pull request by raedrizqie**
- enable vulkan backend
- linked with internal vulkan statically

### CODE REVIEW

**Comment by raedrizqie** [comment]
@lazka @Biswa96 can we merge this?

**Comment by Biswa96** [comment]
> linked with internal vulkan statically

Isn't it possible to use the mingw vulkan packages?

**Comment by raedrizqie** [comment]
maybe, but needs to patch vulkan deps' build.gn

**Comment by lazka** [comment]
arm64 failed with:

```
2023-07-13T06:51:06.1366400Z ../../third_party/SwiftShader/src/System/Timer.cpp:63:24: error: use of undeclared identifier 'ARM64_PMCCNTR_EL0'
2023-07-13T06:51:06.1366936Z 
2023-07-13T06:51:06.1367243Z         return _ReadStatusReg(ARM64_PMCCNTR_EL0);
```

**Comment by lazka** [comment]
swiftshader is 1.7GB and makes the source package 2.5GB, which is too large for github

**Comment by lazka** [comment]
I moved it to a .zip from git, maybe that helps

**Comment by lazka** [comment]
now arm64 fails with:

```
ld.lld: error: undefined symbol: llvm::sys::CompareAndSwap(unsigned int volatile*, unsigned int, unsigned int)
ld.lld: error: undefined symbol: llvm::sys::MemoryFence()
```

also in SwiftShader

**Comment by raedrizqie** [comment]
..or maybe you could try using the latest swiftshader?

**Pull request merged**
