### PR TITLE
clucene: fix compilation with clang

### PR DESCRIPTION
**Pull request by neheb**
Changed CXX_STANDARD to 98 as 11 requires stricter list initialization.

Switch to build with Ninja. Faster.

Added pthread patch for UCRT.

Added clang32 where this was tested.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
What a weird error.

**Comment by raedrizqie** [comment]
you can fix it by something like this:

```
--- clucene-core-2.3.3.4-orig/src/shared/cmake/MacroCheckGccVisibility.cmake
+++ clucene-core-2.3.3.4/src/shared/cmake/MacroCheckGccVisibility.cmake
@@ -26,7 +26,7 @@
    
       # gcc on mac just reports: "gcc (GCC) 3.3 20030304 ..." without the patch level, handle this here:
       if (NOT _gcc_version)
-        string (REGEX REPLACE ".*\\(GCC\\).* ([34]\\.[0-9]) .*" "\\1.0" _gcc_version "${_gcc_version_info}")
+        string (REGEX REPLACE ".*\\(Rev[0-9], Built by MSYS2 project\\).* ([0-9]+\\.[0-9]\\.[0-9]) .*" "\\1.0" _gcc_version "${_gcc_version_info}")
       endif (NOT _gcc_version)
    endif (NOT _gcc_version)
    
```

**Comment by Biswa96** [comment]
Or, disable the check entirely.

**Comment by neheb** [comment]
added patch. builds with mingw now.

**Comment by neheb** [comment]
ping

**Pull request merged**
