### PR TITLE
new package bat and dust

### PR DESCRIPTION
**Pull request by naveen521kk**
https://github.com/sharkdp/bat

### CODE REVIEW

**Comment by Biswa96** [comment]
Another Rust clone 😩

**Comment by naveen521kk** [comment]
> Another Rust clone

hmm, what do you mean by that?

**Comment by Biswa96** [comment]
So, here are the clones we've
* ripgrep -- grep
* sccahce -- ccache
* rav1e -- dav1d
* bat -- cat
* dust -- du

**Comment by naveen521kk** [comment]
what's the problem with that?

**Comment by mati865** [comment]
Some of them aren't exactly clones:
- sccache - cloud based storage is rather big feature
- rav1e - it's the encoder, dav1d is the decoder

**Pull request merged**
