### PR TITLE
qt6-imageformats: update to 6.3.2

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Fails!
Reverting #12598 makes it succeed.

### CODE REVIEW

**Comment by lazka** [comment]
@kmilos any ideas?

**Comment by Biswa96** [comment]
We can workaround the issue by disabling first webp check. Here is the diff

```diff
--- a/cmake/FindWrapWebP.cmake
+++ b/cmake/FindWrapWebP.cmake
@@ -12,7 +12,7 @@
     return()
 endif()
 
-find_package(WebP QUIET)
+#find_package(WebP QUIET)
 if(TARGET WebP::webp AND TARGET WebP::webpdemux AND TARGET WebP::libwebpmux)
     set(WrapWebP_FOUND ON)
     add_library(WrapWebP::WrapWebP INTERFACE IMPORTED)
```

**Comment by kmilos** [comment]
Good way to do it. No idea why the libwebp config scripts would affect the Qt build ones... @1480c1

**Comment by MehdiChinoune** [comment]
I am going to merge it with this (ugly) workaround!

**Pull request merged**
