### PR TITLE
Add mingw-w64-c-toolchain package

### PR DESCRIPTION
**Pull request by lazka**
This meta package depends on all packages that are needed to build a executable
with $CC during packaging.

Packages can makedepend on this to get a C compiler.

### CODE REVIEW

**Comment by Biswa96** [comment]
Is it required to add this meta package in every packages as makedepends?

**Comment by lazka** [comment]
> Is it required to add this meta package in every packages as makedepends?

That's the idea. Then we could remove the requirement for installing "mingw-w64-x86_64-toolchain".

**Comment by Biswa96** [comment]
That will be a huge change 😟 toolchain and base-devel are used in many docs and CI scripts.

**Comment by lazka** [comment]
They can stay around, it's only for our CI and autobuild.. and only once enough packages have it.

**Comment by lazka** [comment]
c-toolchain is

```
Total Download Size:    46.85 MiB
Total Installed Size:  393.42 MiB
```

vs the current toolchain group:

```
Total Download Size:    151.34 MiB
Total Installed Size:  1000.17 MiB
```

**Comment by lazka** [comment]
handled via b845c4cc40a43c60 instead now.. similar result.

**Pull request closed without merging**
