### PR TITLE
openscad-git: add depends & MCAD.git

### PR DESCRIPTION
**Pull request by ustsv**

### CODE REVIEW

**Comment by ustsv** [comment]
Opps Boost 1.69 I have patched
--- C:/temp/system_category_win32.hpp	Wed Feb 13 19:28:51 2019
+++ C:/temp/system_category_win32.original.hpp	Wed Feb 13 20:00:32 2019
@@ -51,3 +51,3 @@
 {
-    snprintf( buffer, len, "Unknown error (%d)", ev );
+    std::snprintf( buffer, len, "Unknown error (%d)", ev );
     return buffer;

**Comment by ustsv** [comment]
#5097, It includes #5102 
w/o lib3mf now

**Comment by podsvirov** [comment]
@ustsv, you right - looks like we need add `lib3mf` package for new `OpenSCAD` features.

**Comment by podsvirov** [comment]
@ustsv look at #5135 and #5136.

**Pull request closed without merging**
