### PR TITLE
Fix insecure hashes, prefer HTTPS (or HTTP even) over FTP

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by lazka** [comment]
Please try to be more specific with your commit messages.

**Comment by vszakats** [comment]
It really is just an assortment of fixing sloppy practices: MD5, SHA1, missing checksum, FTP protocol. I'm not even sure how some of these are still allowed in new commits.

Do you have a suggestion for a better title?

**Comment by lazka** [comment]
> Do you have a suggestion for a better title?

Anything that somewhat describes what you are trying to do, like:

> It really is just an assortment of fixing sloppy practices: MD5, SHA1, missing checksum, FTP protocol. I'm not even sure how some of these are still allowed in new commits.

**Comment by lazka** [comment]
thanks!

**Comment by vszakats** [comment]
You're welcome and thanks for the merge.

(The 'missing checksum' case was in an orphan (old) file, so it didn't make it into the patch.)

**Pull request merged**
