### PR TITLE
starship: optdepend on nerd fonts

### PR DESCRIPTION
**Pull request by ognevnydemon**
needed for theme prompts

important question: can we use package group as dependency? (edit: for the answer read comments below https://github.com/msys2/MINGW-packages/pull/18196#issuecomment-1680036783)

### CODE REVIEW

**Comment by Biswa96** [comment]
> can we use package group as dependency?

optdepends just show a message at the time of installing a package. One can write anything in optdepends. User has to decide what to install.

**Comment by lazka** [comment]
> important question: can we use package group as dependency?

no

**Comment by ognevnydemon** [comment]
> > important question: can we use package group as dependency?
> 
> no

I meant optdepend

**Comment by lazka** [comment]
> I meant optdepend

not sure, it should also point to real packages, but I don't know if pacman will fail if it isn't.

**Comment by ognevnydemon** [comment]
can you test it in staging?

**Comment by lazka** [comment]
I think the "proper" fix would be to remove the group from nerd-fonts, add an additional package to nerd-fonts, which is just named "<...>-nerd-fonts" and depends on all the other packages (so like a meta package).

**Comment by ognevnydemon** [comment]
> I think the "proper" fix would be to remove the group from nerd-fonts, add an additional package to nerd-fonts, which is just named "<...>-nerd-fonts" and depends on all the other packages (so like a meta package).

ok. I hope I'll try it in Sunday

**Comment by ognevnydemon** [comment]
won't this conflict?

**Comment by lazka** [comment]
> won't this conflict?

With what?

I see that Arch solves this via a provides: https://archlinux.org/packages/extra/any/ttf-profont-nerd/

**Comment by ognevnydemon** [comment]
> With what?

sorry, at first I didn't understand you right. now I'm sure that it won't conflict

**Comment by ognevnydemon** [comment]
> I see that Arch solves this via a provides (ttf-font-nerd), which is also an option: https://archlinux.org/packages/extra/any/ttf-profont-nerd/

in that case we can left package group as is, and just use this provides, right?

**Comment by lazka** [comment]
> in that case we can left package group as is, and just use this provides, right?

if it's named the same then the group will be ignored by pacman, otherwise sure. Though we have made the experience that groups just confuse users at installation time, so at least I kinda avoid them.

**Comment by ognevnydemon** [comment]
oops, there are some merge conflicts... I'm not pro in git, how can I resolve it without `merge branch...` commit?

**Comment by ognevnydemon** [comment]
> I see that Arch solves this via a provides (ttf-font-nerd), which is also an option: https://archlinux.org/packages/extra/any/ttf-profont-nerd/

done in #18228

**Comment by ognevnydemon** [comment]
should be mergable now

**Pull request merged**
