### PR TITLE
nsis: enable clang

### PR DESCRIPTION
**Pull request by raedrizqie**
Fixes: #21000 

I cannot test for clangarm64 though..

### CODE REVIEW

**Comment by lazka** [comment]
great!

**Comment by lazka** [comment]
Just curious, did mingw32 got dropped because it caused issues?

**Comment by lazka** [comment]
```
scons: *** [build/urelease/System/unicode/Source/Call-arm64CPP.o] Source `Contrib/System/Source/Call-arm64CPP.S' not found, needed by target `build/urelease/System/unicode/Source/Call-arm64CPP.o'.
```

should we disable arm64 again?

**Comment by raedrizqie** [comment]
> Just curious, did mingw32 got dropped because it caused issues?

I drop mingw32 because now we are not using msys2 scons, and there is no mingw32 scons.

**Comment by raedrizqie** [comment]
> ```
> scons: *** [build/urelease/System/unicode/Source/Call-arm64CPP.o] Source `Contrib/System/Source/Call-arm64CPP.S' not found, needed by target `build/urelease/System/unicode/Source/Call-arm64CPP.o'.
> ```
> 
> should we disable arm64 again?

yee, i guess. hoping somebody else could help with arm64.

**Comment by lazka** [comment]
> yee, i guess. hoping somebody else could help with arm64.

OK, thanks, I'll disable it later

**Comment by hmartinez82** [comment]
Oh wow, sorry 😅. That ASM file is way out of my league. It's not like I know ARM64 assembly anyway.

**Pull request merged**
