### PR TITLE
Add gst-plugin-gtk4

### PR DESCRIPTION
**Pull request by realmazharhussain**
Adds GTK4 plugin for GStreamer.

### CODE REVIEW

**Comment by lazka** [comment]
Can we still name it gst-plugins-rs? So we can try to fix it in the future to include more stuff.

**Comment by realmazharhussain** [comment]
Sorry, there were a few things I forgot.

- [ ] ` (mingw-w64)` postfix in pkgdesc
- [ ] license in the format `spdx:<license-id>`
- [ ] install license file

**Comment by realmazharhussain** [comment]
> Can we still name it gst-plugins-rs? So we can try to fix it in the future to include more stuff.

I think there has been some miscommunication here. When I asked if I should try and bundle all plugins with cargo-c in PR #16941, I meant I could most probably reopen and fix #16941.

I didn't realize it before but I think gst-plugins-rs does not currently support meson completely. It seems like they are still figuring some things out.

**Comment by realmazharhussain** [comment]
#16941 is ready. If it is preferred that all plugins be bundled together, #16941 can be reviewed and merged. If the GTK4 plugin is preferred to be bundled alone, this MR can be reviewed and merged instead.

**Comment by lazka** [comment]
thanks, closing since I merged #16941

**Pull request closed without merging**
