### PR TITLE
gedit: finish the meson port

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
Needs some more work, I'll have a look later.

**Comment by lazka** [comment]
@Alexpux should be ready

**Comment by Alexpux** [comment]
@lazka what patch help-no-media do?

**Comment by lazka** [comment]
> @lazka what patch help-no-media do?

I just skips the images in yelp, because otherwise I get this:

```
WARNING: Symlinking not supported, falling back to copying
Installing C:/msys64/mingw64/share/help/C/gedit/figures/gedit-html-snippet.png to C:/msys64/home/xy/M/mingw-w64-gedit/pkg/mingw-w64-x86_64-gedit/mingw64/share/help/ar/gedit/figures/gedit-html-snippet.png
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\meson-script.py", line 11, in <module>
    load_entry_point('meson==0.50.1', 'console_scripts', 'meson')()
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\mesonmain.py", line 219, in main
    return run(sys.argv[1:], launcher)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\mesonmain.py", line 208, in run
    return run_script_command(args[1], args[2:])
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\mesonmain.py", line 156, in run_script_command
    return module.run(script_args)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\scripts\yelphelper.py", line 131, in run
    destdir, options.project_id, options.symlinks)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\scripts\yelphelper.py", line 101, in install_help
    shutil.copyfile(infile, outfile)
  File "C:/msys64/mingw64/lib/python3.7\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/msys64/mingw64/share/help/C/gedit/figures/gedit-html-snippet.png'
FAILED: meson-install
"C:/msys64/mingw64/bin/meson" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
```

**Comment by Alexpux** [comment]
@lazka I fixed this bug in meson already, you seems not install latest packages

**Comment by Alexpux** [comment]
@lazka see https://github.com/msys2/MINGW-packages/commit/2b9491754ffffc8a736ecb5ee786c6cb724027d1

**Comment by lazka** [comment]
The above error happens with the latest meson package here.

**Comment by lazka** [comment]
I've removed the patch and fixed the meson patch.

**Comment by lazka** [comment]
I've opened https://github.com/mesonbuild/meson/pull/5450

**Comment by JPeterMugaas** [comment]
Should gedit use 'yelp-tools' or mingw-w64-yelp-tools?  I ask because I did check in a mingw-w64-yelp-tools that includes support for mallard-ducktype.

**Comment by lazka** [comment]
Not sure. yelp-tools is written in bash so there shouldn't be much difference. As for mallard-ducktype, I can't seem to find any reference in yelp where it is actually used... weird. Any ideas?

**Comment by JPeterMugaas** [comment]
What I'm refering to is "mallard-ducktype" which is a package I made available (see: https://github.com/msys2/MINGW-packages/pull/5485).  The yelp-check script refers to it as "Mallard".    I i DO KNOW THAT "yelp-xsl" calls the "ducktype" command from "python3-mallard-ducktype".

It is probably true that "yelp-tools" is a bunch of shell scripts at one level but these shell scripts refer to things like "/mingw64/bin/xsltproc" instead of the "/usr/bin/xsltproc".

**Comment by lazka** [comment]
ah, ok, thanks. I'll try porting some things to it and see how it works.

**Comment by JPeterMugaas** [comment]
I did fix an issue at: https://github.com/msys2/MINGW-packages/pull/5486 .  That was some invalid paths the scripts.  Let me know how this works.  

Right now, I'm trying to see if I can port gnome-doc-utils to mingw.  Keep your fingers crossed.

**Pull request merged**
