### PR TITLE
Fix compilation if gcc is installed in a path with spaces

### LINKED ISSUE #4744: GCC 8 regression
It seems that gcc 8 introduced a regression comparing to gcc 7.
With gcc 7, it was and is still possible to install msys64 in a folder that contains spaces and still be able to compile a `hello_world.c` file, which was working nicely, but it seems it is broken with gcc 8 (note the space between `msys` and `64`):

```bash
$ pwd
/D/msys 64/home/Olivier

$ ls -l
total 9
-rw-r--r-- 1 Olivier None     96 Dec  4 18:01 hello_world.c


$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 8.2.1 20181123
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc hello_world.c
D:/msys 64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w6 4-mingw32/bin/ld.exe: cannot find D:/msys: No such file or directory
D:/msys 64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w6 4-mingw32/bin/ld.exe: cannot find 64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8 .2.1/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file  or directory
collect2.exe: error: ld returned 1 exit status

$ PATH=/usr/bin gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ PATH=/usr/bin gcc hello_world.c

$ ls -l
total 153
-rwxr-xr-x 1 Olivier None 144279 Dec  4 18:01 a.exe
-rw-r--r-- 1 Olivier None     96 Dec  4 18:01 hello_world.c
```

It seems the problem is a wrong path to `default-manifest.o`, probably missing double quotes, which should be fairly easy to fix.

*Note*: I am aware that it is not recommended to install MSYS2 in a path containing spaces, but it used to work nicely until gcc 8 came 😒...

### PR DESCRIPTION
**Pull request by omichel**
Fixes #4744.

### CODE REVIEW

**Comment by omichel** [comment]
I am not sure why did the AppVeyor test failed. Could someone look into this?

**Comment by mati865** [comment]
It's irrelevant.

**Comment by omichel** [comment]
👍

**Comment by Alexpux** [comment]
@omichel increase ````pkgrel````

**Comment by omichel** [comment]
@Alexpux: done.

**Pull request merged**
