### PR TITLE
OpenCV: update to 4.5.5

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
package-grokker shows only these packages need to be rebuilt:
```
mingw-w64-gst-plugins-bad
mingw-w64-gmic
mingw-w64-openimageio
mingw-w64-itk
```
https://github.com/MehdiChinoune/package-grokker/runs/5633776681?check_suite_focus=true

**Comment by MehdiChinoune** [comment]
I am waiting for #11058 to enable vtk dependency on clang environments.

**Comment by lazka** [comment]
> package-grokker shows only these packages need to be rebuilt:

btw, package-grokker now has a mode where you just have to pass a PR number: https://github.com/lazka/package-grokker/runs/5667298516?check_suite_focus=true

**Comment by MehdiChinoune** [comment]
`gmic` failed to build, but the failure is not related to OpenCV.

**Comment by MehdiChinoune** [comment]
It should be ready now.

**Pull request merged**
