### PR TITLE
zlib: Update to 1.3.1

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
It fails to build with gcc (mingw64 and ucrt64)

**Comment by lazka** [comment]
oh, I only tested with clang this time :(

**Comment by MehdiChinoune** [comment]
Oh, Something wrong with the one https://zlib.net/zlib-1.3.1.tar.xz the I used to build.

**Comment by lazka** [comment]
weird, let's check

**Comment by lazka** [comment]
They have the same content, so maybe something different

**Comment by lazka** [comment]
looks like it's flaky:

```
2024-01-23T08:03:40.5681054Z gcc -march=pentium4 -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -D_LARGEFILE64_SOURCE=1 -L. -pipe -Wl,--no-seh -Wl,--large-address-aware -o example64.exe example64.o -L. libz.a
2024-01-23T08:03:40.5762225Z gcc -march=pentium4 -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -D_LARGEFILE64_SOURCE=1 -L. -pipe -Wl,--no-seh -Wl,--large-address-aware -o minigzip64.exe minigzip64.o -L. libz.a
2024-01-23T08:03:40.6678308Z collect2.exe: error: ld returned 32 exit status
2024-01-23T08:03:40.6752323Z make: *** [Makefile:298: example64.exe] Error 1
```

**Pull request merged**
