### PR TITLE
pywin32: Update 001-compile-and-setup-fixes.patch

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by lazka** [comment]
Why do we need this?

We already have #5615 open for updating pywin32. Please coordinate with the people working there, thanks.

**Comment by raedrizqie** [comment]
Hi Chris,

I just want to test the patch, hence the draft status. This patch has already been submitted to Mark here: [1584](https://github.com/mhammond/pywin32/pull/1584)

Sorry for all the trouble.

**Comment by Biswa96** [comment]
> I just want to test the patch

TIP: If you want to test a patch you can do it in your own fork of this repository. Enable GitHub Actions in repository Settings > Actions > Allow all actions.

**Comment by raedrizqie** [comment]
> 
> 
> > I just want to test the patch
> 
> TIP: If you want to test a patch you can do it in your own fork of this repository. Enable GitHub Actions in repository Settings > Actions > Allow all actions.

Ok.. thanks for the tip.

**Pull request closed without merging**
