### PR TITLE
Add cppgc include directory to instalation

### PR DESCRIPTION
**Pull request by Kwizatz**
Missed a new include directory from the installation.

### CODE REVIEW

**Comment by Kwizatz** [comment]
Moving to live review since failures do not seem related to build.

**Comment by Biswa96** [comment]
Can the `install -d` commands be removed? Doesn't `install -D` create the destination directory automatically?

**Comment by Kwizatz** [comment]
@Biswa96 Looks like we do need those:
https://github.com/msys2/MINGW-packages/runs/1108785185

**Comment by Biswa96** [comment]
OK, as wish. I was just asking.

**Comment by Kwizatz** [comment]
> OK, as wish. I was just asking.

No problem 😁 it would had been nice if it did worked.

**Pull request merged**
