### PR TITLE
mcfgthread: update to v1.8.1

### PR DESCRIPTION
**Pull request by lhmouse**
https://github.com/lhmouse/mcfgthread/releases/tag/v1.8-ga

### CODE REVIEW

**Comment by ognevny** [comment]
there are lots of warnings thrown by a compiler :)

**Comment by lhmouse** [comment]
> there are lots of warnings thrown by a compiler :)

For example?
https://github.com/lhmouse/mcfgthread/actions/runs/9147367241/job/25148819693#step:5:39

**Comment by ognevny** [comment]
> > there are lots of warnings thrown by a compiler :)
> 
> For example? https://github.com/lhmouse/mcfgthread/actions/runs/9147367241/job/25148819693#step:5:39

look at CI in this repository

**Comment by lhmouse** [comment]
I just read it over. I think those warnings are safe (and kinda expected), as there are things that GCC supports but Clang doesn't.

**Pull request merged**
