### PR TITLE
update ghc to 9.8.2

### PR DESCRIPTION
**Pull request by oltolm**

### CODE REVIEW

**Comment by ognevny** [comment]
I pushed some small fixes

**Comment by oltolm** [comment]
> I pushed some small fixes

Thank you, but I only tested in clang64. I don't think it will work in another environment.

**Comment by ognevny** [comment]
> Thank you, but I only tested in clang64. I don't think it will work in another environment.

is there any upstream test suite? which test suite did you run? I can download and test for ucrt64

**Comment by oltolm** [comment]
> > Thank you, but I only tested in clang64. I don't think it will work in another environment.
> 
> is there any upstream test suite? which test suite did you run? I can download and test for ucrt64

I didn't run any test suite, I just compiled some Haskell apps. There is a test suite, but I don't know how to run it.

**Comment by ognevny** [comment]
patches can't be applied. maybe you used git master as source? it's better to checkout to the tag and make changes on it

**Comment by ognevny** [comment]
> I didn't run any test suite, I just compiled some Haskell apps. There is a test suite, but I don't know how to run it.

which projects? I'll test it for ucrt64

**Comment by oltolm** [comment]
I build git-annex, but some patches were necessary. I haven't yet contributed them.

**Comment by ognevny** [comment]
the build failure
```
Resolving dependencies...
Error: cabal.exe: Could not resolve dependencies:
[__0] trying: hadrian-0.1.0.0 (user goal)
[__1] trying: hadrian:+selftest
[__2] unknown package: QuickCheck (dependency of hadrian +selftest)
[__2] fail (backjumping, conflict set: QuickCheck, hadrian, hadrian:selftest)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: hadrian, hadrian:selftest, QuickCheck
```
the same for ucrt64

**Comment by Kreijstal** [comment]
pandoc here we come

**Comment by oltolm** [comment]
Is there any interest in this PR or should I close it?

**Comment by Kreijstal** [comment]
> Is there any interest in this PR or should I close it?

I'm interested

**Comment by oltolm** [comment]
> > Is there any interest in this PR or should I close it?
> 
> I'm interested, have you tried it for mingw as well?

No I have not.

**Comment by Kreijstal** [comment]
what happens if you add it?

> > > Is there any interest in this PR or should I close it?
> > 
> > 
> > I'm interested, have you tried it for mingw as well?
> 
> No I have not.

**Comment by Kreijstal** [comment]
rip :(

**Pull request closed without merging**
