### PR TITLE
aws-sdk-cpp: Update to 1.8.149, separate dependencies.

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by kou** [comment]
Could you also bump `arrow`'s `pkgrel` to rebuild `arrow`?

**Comment by jeroen** [comment]
lgtm

**Comment by jeroen** [comment]
I opened a PR #8085 with another package that uses aws-sdk, so we can better test this.

**Comment by Biswa96** [comment]
> with another package that uses aws-sdk, so we can better test this.

Yeah, more lab rats. But that PR will not use this aws-sdk-cpp package until this one is merged and built by msys2-autobuild. Thought you can build TileDB in your own machine using CI artifacts from here.

**Comment by Biswa96** [comment]
> with another package that uses aws-sdk, so we can better test this.

Yeah, more lab rats. But that PR will not use this aws-sdk-cpp package until this one is merged and built by msys2-autobuild. But you can build TileDB in your own machine using CI artifacts from here.

**Comment by jeroen** [comment]
> Yeah, more lab rats. But that PR will not use this aws-sdk-cpp package until this one is merged and built by msys2-autobuild. But you can build TileDB in your own machine using CI artifacts from here.

You could merge that commit into this branch if you like.

**Comment by Biswa96** [comment]
TileDB compiles using this aws-sdk-cpp without any issue, just need little changes. If this change itself ok I can ask _msys2 Project Manager_ to merge 😄

**Comment by Biswa96** [comment]
@lazka ready.

**Pull request merged**
