### PR TITLE
libva: add package

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/14856

### CODE REVIEW

**Comment by Biswa96** [comment]
@pal1000 Would you like to review this pull request please?
* Are the DLL and import libraries name correct? Should those be prefixed with 'lib' ? Should those have so version?
* Should I also add another commit to add `-Dgallium-va=enabled` with mesa?

**Comment by pal1000** [comment]
> Are the DLL and import libraries name correct?

Yes, but it might not matter as Mesaa3D only uses libva headers according to [source](https://gitlab.freedesktop.org/search?search=_dep_va_name&nav_source=navbar&project_id=176&group_id=1155&search_code=true&repository_ref=main).

> Should I also add another commit to add -Dgallium-va=enabled

Why not.

**Comment by Biswa96** [comment]
I have added the mesa changes. Looks good?

**Comment by pal1000** [comment]
Yes.

**Pull request merged**
