### PR TITLE
libgit2: update to 1.8.4

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by Biswa96** [comment]
Reverse dependencies need pkgrel bump.

**Comment by podsvirov** [comment]
Of course you're right.  I'll try to do this soon.  But I don't mind if someone does it while I'm a little busy with other things.

**Comment by podsvirov** [comment]
> Reverse dependencies need pkgrel bump.

I've done a little analysis and it seems the world is not ready for this update yet :-).
We need to wait a bit for the dependent packages to support this version.

**Comment by ognevny** [comment]
IMO it's ok to push an update to 1.8.1 and rebuilds for reverse dependencies. Arch already did this

**Comment by podsvirov** [comment]
Updated to `1.8.1`.

```
$ pacboy  -Sii libgit2:u
...
Required By     : mingw-w64-ucrt-x86_64-bat  mingw-w64-ucrt-x86_64-cargo-c  mingw-w64-ucrt-x86_64-cargo-generate  mingw-w64-ucrt-x86_64-delta
                  mingw-w64-ucrt-x86_64-fritzing  mingw-w64-ucrt-x86_64-geany-plugins  mingw-w64-ucrt-x86_64-gitui  mingw-w64-ucrt-x86_64-jj
                  mingw-w64-ucrt-x86_64-kicad  mingw-w64-ucrt-x86_64-ktexteditor-qt5  mingw-w64-ucrt-x86_64-libgit2-glib  mingw-w64-ucrt-x86_64-lsd
                  mingw-w64-ucrt-x86_64-python-pygit2  mingw-w64-ucrt-x86_64-zed
...
```

Should we rebuild all these packages or something else?

**Comment by ognevny** [comment]
> Updated to `1.8.1`.
> 
> ```
> $ pacboy  -Sii libgit2:u
> ...
> Required By     : mingw-w64-ucrt-x86_64-bat  mingw-w64-ucrt-x86_64-cargo-c  mingw-w64-ucrt-x86_64-cargo-generate  mingw-w64-ucrt-x86_64-delta
>                   mingw-w64-ucrt-x86_64-fritzing  mingw-w64-ucrt-x86_64-geany-plugins  mingw-w64-ucrt-x86_64-gitui  mingw-w64-ucrt-x86_64-jj
>                   mingw-w64-ucrt-x86_64-kicad  mingw-w64-ucrt-x86_64-ktexteditor-qt5  mingw-w64-ucrt-x86_64-libgit2-glib  mingw-w64-ucrt-x86_64-lsd
>                   mingw-w64-ucrt-x86_64-python-pygit2  mingw-w64-ucrt-x86_64-zed
> ...
> ```
> 
> Should we rebuild all these packages or something else?

look at package-grokker output first. at least don't rebuild zed, as there is a update PR for it: #21254

**Comment by ognevny** [comment]
`cargo update -p git2 --precise 0.19.0` doesn't work? I think there is no need for a patch

**Comment by podsvirov** [comment]
> `cargo update -p git2 --precise 0.19.0` doesn't work? I think there is no need for a patch

```
    Updating crates.io index
error: failed to select a version for the requirement `git2 = "^0.18"`
candidate versions found which didn't match: 0.19.0
```

**Comment by podsvirov** [comment]
Hm,  `clang64`  (but not for others)  failed for `lsd:`:
```
  ==> Validating source files with sha256sums...
      lsd-1.1.2.tar.gz ... Passed
      1021.patch ... FAILED
      0001-lsd-1.1.2-update-git2.patch ... Passed
```

**Comment by ognevny** [comment]
> Hm,  `clang64`  (but not for others)  failed for `lsd:`:
> ```
>   ==> Validating source files with sha256sums...
>       lsd-1.1.2.tar.gz ... Passed
>       1021.patch ... FAILED
>       0001-lsd-1.1.2-update-git2.patch ... Passed
> ```

change it to upstream commit: https://github.com/lsd-rs/lsd/commit/575f505dc2067da154902b9ea4d80fa1315fb280

**Comment by podsvirov** [comment]
@lazka, thanks for done (or start...) this work! :-)

**Pull request merged**
