### PR TITLE
wezterm: add missing libssh2 dep

### LINKED ISSUE #22890: mingw-w64-ucrt-x86_64-wezterm depends on libssh but links to libssh2
### Description / Steps to reproduce the issue

```
$ ldd $(which wezterm-gui) |grep libssh
        libssh2-1.dll => /ucrt64/bin/libssh2-1.dll (0x7ffe2f850000)
$ LANG=en_US.UTF-8 pacman -Qo /ucrt64/bin/libssh2-1.dll
/ucrt64/bin/libssh2-1.dll is owned by mingw-w64-ucrt-x86_64-libssh2 1.11.1-1
$ LANG=en_US.UTF-8 pacman -Qi mingw-w64-ucrt-x86_64-wezterm |grep Depends
Depends On      : mingw-w64-ucrt-x86_64-openssl  mingw-w64-ucrt-x86_64-libssh
```

### Expected behavior

The linked dll should be found in its dependent packages

### Actual behavior

But it is not

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26100

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by lazka**
Fixes #22890

### CODE REVIEW

**Comment by lazka** [comment]
hmm, no idea

**Comment by MehdiChinoune** [comment]
@ognevny @mati865 could you fix the issue.

**Comment by ognevny** [comment]
> hmm, no idea

bump cc crate in prepare()

`cargo update -p cc`

**Comment by ognevny** [comment]
> @ognevny @mati865 could you fix the issue.

FYI, there was a bug in cc crate, which was fixed in 1.1.10 version (rust-lang/cc-rs#1176)

**Comment by ognevny** [comment]
thanks

**Pull request merged**
