### PR TITLE
rust: update psm dependency

### PR DESCRIPTION
**Pull request by ognevny**
I don't know whether this work, patch doesn't create checksum file... I'll go sleep now, feel free to fix if needed
@jeremyd2019

### CODE REVIEW

**Comment by jeremyd2019** [comment]
we shall see: https://github.com/msys2-arm/MINGW-packages/actions/runs/12074687359/job/33673128814 though I bet if the patch is bad it'd fail in one of the other CI runs too.

**Comment by jeremyd2019** [comment]
I wasn't sure if it'd be easier to update psm like this, or just apply the patch from https://github.com/rust-lang/stacker/commit/c94a424e1dc1c1d7f0e7cdb5150d1c0fe4e0489b, either would require messing with the checksum files, which suck.

**Comment by jeremyd2019** [comment]
https://github.com/msys2-arm/MINGW-packages/actions/runs/12075324149/job/33674915084 🤞

**Comment by lazka** [comment]
merge?

**Comment by ognevny** [comment]
good morning, thank you :)

**Pull request merged**
