### PR TITLE
qemu: Update to 8.1.0

### PR DESCRIPTION
**Pull request by heljkon**
see https://wiki.qemu.org/Planning/8.1 for further information

### CODE REVIEW

**Comment by heljkon** [comment]
I've expected failures because of major changes qemu applied to the build system, see https://wiki.qemu.org/ChangeLog/8.1#Build_Information

I'll go for it later.

**Comment by heljkon** [comment]
I've created an issue for the clang build failures: https://gitlab.com/qemu-project/qemu/-/issues/1782
Currently the build for clang succeeds, if dbus is disabled: 
`./configure --disable-dbus-display`

**Comment by heljkon** [comment]
@lazka @Biswa96 @jeremyd2019 
Please have a look!

**Comment by Biswa96** [comment]
qemu install libftd related files which are provided by dtc package also. Should those be removed from qemu package?

**Comment by lazka** [comment]
> Library fdt found: NO

maybe it's just missing a dependency on https://packages.msys2.org/base/mingw-w64-dtc ?

**Comment by lazka** [comment]
In case it helps, I've updated dtc to the newest version in #18274

**Comment by heljkon** [comment]
Adding the already existing package dtc as dependency solved the duplicate problems.

**Comment by Biswa96** [comment]
Thank you.

**Pull request merged**
