### PR TITLE
verilator: update to 4.204

### PR DESCRIPTION
**Pull request by umarcor**
See verilator/verilator-announce#47.

### CODE REVIEW

**Comment by lazka** [comment]
Is 32bit no longer supported?

**Comment by umarcor** [comment]
I'm dealing with it: https://github.com/verilator/verilator/pull/2681#issuecomment-864005456 and https://github.com/verilator/verilator/pull/2681#issuecomment-864007683. I'll convert this to a draft. Sorry about not being clear about that.

**Comment by lazka** [comment]
no problem, thanks

**Comment by umarcor** [comment]
@lazka, I think this is good now.

**Pull request merged**
