### PR TITLE
Add nerd fonts, take 2

### LINKED ISSUE #18178: Add nerd-fonts
### Package name

nerd-fonts

### Brief description of package

See https://github.com/msys2/MINGW-packages/pull/17833

The Arch variant as split package is here: https://gitlab.archlinux.org/archlinux/packaging/packages/nerd-fonts/-/blob/main/PKGBUILD

### URL for package's homepage

https://github.com/ryanoasis/nerd-fonts

### Provide a basic test case to validate the package's functionality.

not sure

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

not now

### PR DESCRIPTION
**Pull request by ognevnydemon**
Fixes #18178

### CODE REVIEW

**Comment by ognevnydemon** [comment]
oops! I found that pkgdesk of nerd-fonts in website is broken

**Comment by lazka** [comment]
> oops! I found that pkgdesk of nerd-fonts in website is broken. can we fix it?

the website has the pacman DB as source, and that only knows about packages, so there is no common description for a split package and we just show a description of one of the packages.

We could match up the PKGINFO and take the description from there maybe. Let's see...

**Comment by lazka** [comment]
see https://github.com/msys2/msys2-web/commit/f1459923ca805f4222f9d06f62265c64e3dae6a9

**Comment by ognevnydemon** [comment]
thanks

**Pull request merged**
