### PR TITLE
rust: rebuild 1.69.0 to work around clang issue with 1.70.0

### PR DESCRIPTION
**Pull request by filnet**
see https://github.com/msys2/MINGW-packages/pull/17406

### CODE REVIEW

**Comment by filnet** [comment]
Looks like the MINGW32 build timed out or something.

**Comment by filnet** [comment]
CI is having a hard time building for CLANG32... looks like it is stuck.

**Comment by filnet** [comment]
Timed out again ? I think is got stuck in the same spot last time too.

```
   Building stage1 library artifacts (i686-pc-windows-gnu) 
     Compiling cc v1.0.77
     Compiling core v0.0.0 (C:\_\B\src\rustc-1.69.0-src\library\core)
     Compiling compiler_builtins v0.1.87
     Compiling libc v0.2.139
     Compiling unwind v0.0.0 (C:\_\B\src\rustc-1.69.0-src\library\unwind)
     Compiling memchr v2.5.0
     Compiling std v0.0.0 (C:\_\B\src\rustc-1.69.0-src\library\std)
  Terminate batch job (Y/N)? 
  ^C
```

**Comment by jeremyd2019** [comment]
Might have to try it locally, see if there's, ie, an error message box or something.  Or try to get a backtrace of where it's hung

**Comment by filnet** [comment]
It's currently stuck compiling std v0.0.0.

**Comment by filnet** [comment]
Local build:

```console
   Compiling std v0.0.0 (C:\M\mingw-w64-rust\src\rustc-1.69.0-src\library\std)
error: could not compile `core`

Caused by:
  process didn't exit successfully: `C:\M\mingw-w64-rust\src\MINGW32\build\bootstrap\debug\rustc --crate-name core --edit
ion=2021 'library\core\src\lib.rs' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagno
stic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Zunstabl
e-options --check-cfg 'names()' --check-cfg 'values()' -C metadata=76d63240a4356319 -C extra-filename=-76d63240a4356319 -
-out-dir 'C:\M\mingw-w64-rust\src\MINGW32\build\i686-pc-windows-gnu\stage1-std\i686-pc-windows-gnu\release\deps' --target
 i686-pc-windows-gnu -C linker=gcc -L 'dependency=C:\M\mingw-w64-rust\src\MINGW32\build\i686-pc-windows-gnu\stage1-std\i6
86-pc-windows-gnu\release\deps' -L 'dependency=C:\M\mingw-w64-rust\src\MINGW32\build\i686-pc-windows-gnu\stage1-std\relea
se\deps' -Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options '--check-cfg=values(bootstrap)' '--check-
cfg=values(stdarch_intel_sde)' '--check-cfg=values(no_fp_fmt_parse)' '--check-cfg=values(no_global_oom_handling)' '--chec
k-cfg=values(no_rc)' '--check-cfg=values(no_sync)' '--check-cfg=values(freebsd12)' '--check-cfg=values(backtrace_in_libst
d)' '--check-cfg=values(target_env,"libnx")' '--check-cfg=values(target_arch,"asmjs","spirv","nvptx","xtensa")' -Zmacro-b
acktrace -Zunstable-options -Csplit-debuginfo=packed -Cprefer-dynamic -Cembed-bitcode=yes '-Zcrate-attr=doc(html_root_url
="https://doc.rust-lang.org/1.69.0/")' -Z binary-dep-depinfo` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:08:46
==> ERROR: A failure occurred in build().
```

**Comment by jeremyd2019** [comment]
```
---------------------------
rustc.exe - Entry Point Not Found
---------------------------
The procedure entry point __divmoddi4 could not be located in the dynamic link library C:\msys64\mingw32\bin\libstdc++-6.dll. 
---------------------------
OK   
---------------------------
```

**Comment by jeremyd2019** [comment]
> Edit:: it failed fast. Why does it timeout on CI ?

https://github.com/msys2/MINGW-packages/blob/51d3109d30d86e71c4c4a877d4e603f92c48838c/.github/workflows/main.yml#L28

causes Windows to show error message boxes for things like missing exports.  So CI is sitting waiting for somebody to answer the message box.

**Comment by filnet** [comment]
> ```
> ---------------------------
> rustc.exe - Entry Point Not Found
> ---------------------------
> The procedure entry point __divmoddi4 could not be located in the dynamic link library C:\msys64\mingw32\bin\libstdc++-6.dll. 
> ---------------------------
> OK   
> ---------------------------
> ```

How did you get that ?

**Comment by jeremyd2019** [comment]
> How did you get that ?

I tried to build the package locally for MINGW32, with `MSYS=winjitdebug` environment variable set (on my local machine, I have this set globally and gdb registered as Windows JIT debugger).  This caused the error mode to be reset to default in new processes, which means Windows will produce message boxes for errors such as this.  I then pressed <kbd>Ctrl</kbd>-<kbd>C</kbd> on the message box to copy. (not sure which part you were asking about, so I provided info on both getting the message box and copying it in that format).

**Comment by filnet** [comment]
Do you know which rustc is asking for the missing the entry point ?
Is it the official bootstrap compiler ? Because if it is then it depends C:\msys64\mingw32\bin\libstdc++-6.dll which is not good.

**Comment by filnet** [comment]
I was able to build MINGW32 with _bootstrapping=no ! Got lucky...

**Comment by jeremyd2019** [comment]
> Do you know which rustc is asking for the missing entry point ? Is it the official bootstrap compiler ? Because if it is then it depends on `C:\msys64\mingw32\bin\libstdc++-6.dll` which is not good.

Two rustc.exe's are running: `$srcdir\MINGW32\build\bootstrap\debug` and `$srcdir\MINGW32\build\i686-pc-windows-gnu\stage1\bin`

**Comment by mati865** [comment]
This is concerning, `__divmoddi4` must have been found in libstdc++ previously since this is just a rebuild and now it's gone?


> Two rustc.exe's are running while the message box is open: `$srcdir\MINGW32\build\bootstrap\debug` and `$srcdir\MINGW32\build\i686-pc-windows-gnu\stage1\bin`

Yeah that is expected, `build/bootstrap` is build tool made for Rustc. It and stage1 compiler are built with stage0 compiler downloaded from Rust (`_bootstrapping=yes`) or system one (`_bootstrapping=no`).
Linking [libstdc++ statically](https://github.com/rust-lang/rust/blob/7452822843cf461b56742f0fc648af35889a3070/config.example.toml#L80) should help as well but I have no idea what happened there. maybe `ld.bfd` has linked libstdc++ DLL provided in Rust tarball and the one from MINGW32 has broke ABI?

**Comment by filnet** [comment]
@mati865 should we investigate more or proceed with the current 1.69.0-2 rebuild (which is successful after disabling bootstrap for ming32) ? 

This would allow us to move on with 1.70.0 which is waiting on this rebuild.

**Comment by filnet** [comment]
Googling `__divmoddi4 ` does not yield much (nothing recent) but shows that others have had issues with it on 32 bit systems.

**Comment by mati865** [comment]
I wouldn't block on that, since it appears to be some GCC bug.

**Comment by jeremyd2019** [comment]
I think `__divmoddi4` is supposed to come from libgcc.  I don't know why it would have been exported from libstdc++, other than some gcc bug (or something like `--export-all-symbols` re-exporting it if libstdc++ statically linked libgcc and pulled it in).

**Comment by filnet** [comment]
> I wouldn't block on that, since it appears to be some GCC bug.

Good to hear.

Note that if we proceed with the actual plan we will end up having all systems, but MING64, with boostrap=no.
This will open up a new can of worms :) Future will tell...

**Comment by filnet** [comment]
May the powers in place please kindly merge this PR.

**Pull request merged**
