### PR TITLE
openexr: update to 3.2.0

### PR DESCRIPTION
**Pull request by kmilos**
Deps need rebuilding because of soname change (sorry, but can't get around to it myself).

~~Tools are still not enabled for Clang builds, now also [reported upstream](https://github.com/AcademySoftwareFoundation/openexr/issues/1538).~~ Edit: enabled using upstream proposed workaround patch.

### CODE REVIEW

**Comment by kmilos** [comment]
Could be combined w/ https://github.com/msys2/MINGW-packages/pull/18286 as draktable and kimageformats are already rebuilt there...

**Comment by MehdiChinoune** [comment]
> Could be combined w/ #18286 as darktable and kimageformats are already rebuilt there...

There is no guarantee that they will be rebuilt successfully, there is no harm on bumping pkgrel twice (before deployment).

**Comment by kmilos** [comment]
Thanks for bumping all the deps @lazka 

It seems opencolorio no longer builds:
```
2023-09-14T11:24:36.5222502Z CMake Error at share/cmake/modules/Findyaml-cpp.cmake:46 (get_target_property):
2023-09-14T11:24:36.5223369Z   get_target_property() called with non-existent target "yaml-cpp".
2023-09-14T11:24:36.5223838Z Call Stack (most recent call first):
2023-09-14T11:24:36.5224315Z   share/cmake/modules/FindExtPackages.cmake:44 (find_package)
2023-09-14T11:24:36.5224755Z   CMakeLists.txt:270 (include)
2023-09-14T11:24:36.5225009Z 
2023-09-14T11:24:36.5225076Z 
2023-09-14T11:24:36.5245934Z -- Could NOT find yaml-cpp (missing: yaml-cpp_LIBRARY) (found suitable version "0.8.0", minimum required is "0.7.0")
2023-09-14T11:24:36.6883893Z -- Installing yaml-cpp: C:/_/B/src/build-MINGW64/ext/dist/lib/libyaml-cpp.a (version "0.7.0")
2023-09-14T11:24:36.6925162Z -- Found pystring: D:/M/msys64/mingw64/include (Required is at least version "1.1.3") 
2023-09-14T11:24:36.7015765Z -- Found Imath: D:/M/msys64/mingw64/bin/libImath-3_1.dll (found suitable version "3.1.9", minimum required is "3.0") 
2023-09-14T11:24:36.7515850Z -- Found ZLIB: D:/M/msys64/mingw64/lib/libz.dll.a (found suitable version "1.3", minimum required is "1.2.13")  
2023-09-14T11:24:36.9801423Z -- Found minizip-ng: D:/M/msys64/mingw64/lib/libminizip-ng.dll.a (found suitable version "4.0.1", minimum required is "3.0.7") 
2023-09-14T11:24:37.1418847Z -- Found lcms2: D:/M/msys64/mingw64/include (found suitable version "2.15", minimum required is "2.2") 
2023-09-14T11:24:37.6352011Z -- Found Python: D:/M/msys64/mingw64/bin/python.exe (found version "3.11.5") found components: Interpreter Development.Module 
2023-09-14T11:24:37.7132797Z -- pybind11::lto disabled (problems with undefined symbols for MinGW for now)
2023-09-14T11:24:37.7133774Z -- pybind11::thin_lto disabled (problems with undefined symbols for MinGW for now)
2023-09-14T11:24:37.7134652Z -- Found pybind11: D:/M/msys64/mingw64/include (found suitable version "2.11.1", minimum required is "2.9.2") 
2023-09-14T11:24:38.0764399Z -- Found OpenEXR: D:/M/msys64/mingw64/bin/libOpenEXR-3_2.dll (found suitable version "3.2.0", minimum required is "3.0") 
2023-09-14T11:24:38.0765493Z -- Using OpenEXR to build ociolutimage, ocioconvert and ociodisplay.
2023-09-14T11:24:38.3522822Z CMake Warning at tests/CMakeLists.txt:24 (message):
2023-09-14T11:24:38.3523616Z   Skipping the library unit tests.
2023-09-14T11:24:38.3524010Z 
2023-09-14T11:24:38.3524149Z 
2023-09-14T11:24:38.3781635Z CMake Warning at src/bindings/python/CMakeLists.txt:44 (message):
2023-09-14T11:24:38.3782563Z   Building PyOpenColorIO with OCIO_BUILD_DOCS disabled will result in
2023-09-14T11:24:38.3783233Z   incomplete Python docstrings.
2023-09-14T11:24:38.3783629Z 
2023-09-14T11:24:38.3783767Z 
2023-09-14T11:24:38.6283782Z -- Configuring incomplete, errors occurred!
2023-09-14T11:24:38.7246871Z ==> ERROR: A failure occurred in build().
2023-09-14T11:24:38.7524377Z     Aborting...
```

**Comment by MehdiChinoune** [comment]
I have encountered a similar issue with qt-creator.

**Comment by kmilos** [comment]
Could be related to this: https://github.com/jbeder/yaml-cpp/pull/1212/files#r1310028784

It looks like the imported target name changed in 0.8.0

**Comment by kmilos** [comment]
Something now changed in the meantime that causes somewhat random failures due to missing headers (UCRT64 on blender, CLANG32 on freeimage)...

**Comment by lazka** [comment]
Maybe we should try to rebuild (and maybe update) them in separate PRs first?

**Comment by mmuetzel** [comment]
The error on UCRT64 is the one that shows up intermittently and disappears when rebuilding without any other change:
```
2023-09-15T10:17:33.3711904Z In file included from D:/M/msys64/ucrt64/include/c++/13.2.0/ext/string_conversions.h:43,
2023-09-15T10:17:33.3712606Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/bits/basic_string.h:4097,
2023-09-15T10:17:33.3713136Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/string:54,
2023-09-15T10:17:33.3713662Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/bits/locale_classes.h:40,
2023-09-15T10:17:33.3714146Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/bits/ios_base.h:41,
2023-09-15T10:17:33.3714651Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/ios:44,
2023-09-15T10:17:33.3715141Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/ostream:40,
2023-09-15T10:17:34.6089432Z                  from D:/M/msys64/ucrt64/include/c++/13.2.0/iostream:41,
2023-09-15T10:17:34.6090719Z                  from C:/_/B/src/blender-3.6.2/intern/ghost/intern/GHOST_Debug.hh:18,
2023-09-15T10:17:34.6091599Z                  from C:/_/B/src/blender-3.6.2/intern/ghost/intern/GHOST_CallbackEventConsumer.cc:14:
2023-09-15T10:17:34.6092293Z D:/M/msys64/ucrt64/include/c++/13.2.0/cstdlib:79:15: fatal error: stdlib.h: No such file or directory
2023-09-15T10:17:34.6092827Z    79 | #include_next <stdlib.h>
2023-09-15T10:17:34.6093244Z       |               ^~~~~~~~~~
2023-09-15T10:17:34.6093660Z compilation terminated.
2023-09-15T10:17:34.6093973Z 
```
The one for CLANG32 is about a missing declaration of `std::auto_ptr`:
```
2023-09-15T10:04:28.2339501Z Source/FreeImage/MultiPage.cpp:274:10: error: no member named 'auto_ptr' in namespace 'std'
2023-09-15T10:04:28.2340604Z                                 std::auto_ptr<FIMULTIBITMAP> bitmap (new FIMULTIBITMAP);
2023-09-15T10:04:28.2352933Z                                 ~~~~~^
2023-09-15T10:04:28.2353985Z Source/FreeImage/MultiPage.cpp:274:19: error: 'FIMULTIBITMAP' does not refer to a value
2023-09-15T10:04:28.2354603Z                                 std::auto_ptr<FIMULTIBITMAP> bitmap (new FIMULTIBITMAP);
2023-09-15T10:04:28.2355059Z                                               ^
2023-09-15T10:04:28.2355464Z Source/FreeImage.h:123:12: note: declared here
2023-09-15T10:04:28.2355900Z FI_STRUCT (FIMULTIBITMAP) { void *data; };
2023-09-15T10:04:28.2356258Z            ^
```

Haven't checked. But maybe that file needs to `#include <memory>`?

**Comment by kmilos** [comment]
> Haven't checked. But maybe that file needs to `#include <memory>`?

Ah, [it didn't get as far as blendr/freeimage 19h ago](https://github.com/msys2/MINGW-packages/actions/runs/6187946768), so possibly there are more gcc/clang related patches needed since the last builds ;)

In any case, I give up here 🤷 

Please feel free to slice this up any way you find fit.

**Comment by mmuetzel** [comment]
For the build error of FreeImage: #18488

**Comment by mmuetzel** [comment]
The PR FreeImage is merged.
Could you please rebase your changes on a current head of master? (Don't forget to bump the pkgrel of FreeImage again.)

**Comment by kmilos** [comment]
@mmuetzel Thanks, giving it one more go then.

**Comment by mmuetzel** [comment]
The runners for the 64-bit environments timed out (apart from the infamous `include_next` error for UCRT64 - which doesn't count).
The runners for the 32-bit environments completed without errors.
I'll take that as a win.

Staging is pretty crowded currently. But we could probably attempt to have this be built for staging and try to fix potential build errors if they occur.

**Pull request merged**
