### PR TITLE
svt-av1: update to 2.3.0

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
The total file size went double with the version update https://github.com/msys2/MINGW-packages/actions/runs/11614724193/job/32343561041?pr=22362#step:11:1281. Could you know the reason for that change?

**Comment by lazka** [comment]
Is the LTO with the static build actually usable? Maybe we could disable it there?

**Comment by lazka** [comment]
ok, we this becomes more common we might have to rethink static packaging.

**Comment by lazka** [comment]
There is fallout reported in #22439

**Pull request merged**
