### PR TITLE
gettext: update to 0.21

### PR DESCRIPTION
**Pull request by MehdiChinoune**
- patches from https://github.com/mlocati/gettext-iconv-windows/tree/master/patches/gettext-0.21-configure
- backport a recent fix for interference with boost headers.

### CODE REVIEW

**Comment by lazka** [comment]
oh, I was about to look into that. nice :)

**Comment by lazka** [comment]
I think all the ltmain/configure changes can be dropped. We replace them via autogen anyway.

**Comment by lazka** [comment]
xgettext relocation support sees to work fine. I'm not quite sure about the libintl one.. and how to test it.

@MehdiChinoune can I continue from your branch?

**Comment by MehdiChinoune** [comment]
> xgettext relocation support seems to work fine. I'm not quite sure about the libintl one.. and how to test it.
> 
> @MehdiChinoune can I continue from your branch?

yes

**Pull request closed without merging**
