### PR TITLE
imagemagick: enable JPEG XL

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by kmilos** [comment]
Looks like GM requires (unreleased) libjxl 0.7.0...

**Comment by Biswa96** [comment]
Should not libjxl mentioned as optional dependencies? The new DLL file in the package seems to be a plugin.

**Comment by kmilos** [comment]
You're probably right - but that goes for most of the other delegates as well then?

Anyway, let's hold off on this until #13204 is done...

**Comment by kmilos** [comment]
Dropped in favour of #13206

**Pull request closed without merging**
