### PR TITLE
llvm: update to 18.1.1

### PR DESCRIPTION
**Pull request by MehdiChinoune**
All components build successfully.

~I have added a patch to libc++ to fix a build failure with qt-creator https://bugreports.qt.io/projects/QTCREATORBUG/issues/QTCREATORBUG-30302
I don't know what to do with this issue!~

Rebuilds:
- [x] mingw-w64-arrow backport https://github.com/apache/arrow/commit/ed78986a
- [x] mingw-w64-creduce
- [x] mingw-w64-include-what-you-use update 0.22
- [x] mingw-w64-mesa fix meson https://github.com/msys2/MINGW-packages/commit/82bb0959
- [x] mingw-w64-openshadinglanguage (build against LLVM-15 d0b1952734) AcademySoftwareFoundation/OpenShadingLanguage/issues/1769
- [x] mingw-w64-qt6-tools
- [x] mingw-w64-qt-creator
- [x] mingw-w64-qt6-static
- [x] mingw-w64-spirv-llvm-translator update to 18.1.0
- [x] mingw-w64-triton-git (build against LLVM-15 305dded65) fails https://github.com/JonathanSalwan/Triton/issues/1306

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
everything is ready except mesa https://gitlab.freedesktop.org/mesa/mesa/-/issues/10783

**Comment by mati865** [comment]
18.1.1 is available.

**Comment by oltolm** [comment]
I tried built it locally and I get errors when installing

```
$ pacman -U mingw*.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (9) mingw-w64-clang-x86_64-clang-18.1.0-1  mingw-w64-clang-x86_64-clang-analyzer-18.1.0-1
             mingw-w64-clang-x86_64-clang-libs-18.1.0-1
             mingw-w64-clang-x86_64-clang-tools-extra-18.1.0-1
             mingw-w64-clang-x86_64-compiler-rt-18.1.0-1  mingw-w64-clang-x86_64-gcc-compat-18.1.0-1
             mingw-w64-clang-x86_64-lld-18.1.0-1  mingw-w64-clang-x86_64-llvm-18.1.0-1
             mingw-w64-clang-x86_64-llvm-libs-18.1.0-1

Total Installed Size:  1890.11 MiB
Net Upgrade Size:       772.20 MiB

:: Proceed with installation? [Y/n]
(9/9) checking keys in keyring                                 [#################################] 100%
(9/9) checking package integrity                               [#################################] 100%
(9/9) loading package files                                    [#################################] 100%
(9/9) checking for file conflicts                              [#################################] 100%
error: failed to commit transaction (conflicting files)
/clang64/bin/libclang-18.1.dll exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-clang-libs'
/clang64/bin/libclang-cpp-18.1.dll exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-clang-libs'
/clang64/lib/clang/18/include/fuzzer/FuzzedDataProvider.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/orc/c_api.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/profile/instr_prof_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/profile/InstrProfData.inc exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/allocator_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/asan_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/common_interface_defs.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/coverage_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/dfsan_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/hwasan_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/linux_syscall_hooks.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/lsan_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
/clang64/lib/clang/18/include/sanitizer/memprof_interface.h exists in both 'mingw-w64-clang-x86_64-llvm' and 'mingw-w64-clang-x86_64-compiler-rt'
```

It continues for thousands of lines. It seems that the LLVM package contains everything and not just the LLVM.

**Comment by MehdiChinoune** [comment]
@oltolm something wrong with your build.

**Comment by oltolm** [comment]
Yes, it worked with `--nocheck`, thank you.

**Comment by oltolm** [comment]
I also got this warning:
```
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
C:/src/MINGW-packages/mingw-w64-clang/pkg/mingw-w64-clang-x86_64-llvm/clang64/lib/clang/18/lib/windows/libclang_rt.ubsan_standalone_cxx-x86_64.a
```

**Comment by pal1000** [comment]
Try disabling miicrosoft-clc and https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27640.

**Pull request merged**
