### PR TITLE
cotire: update for CMake 3.20

### PR DESCRIPTION
**Pull request by Optiligence**

### CODE REVIEW

**Comment by Biswa96** [comment]
Please increment `pkgrel` variable for this rebuild.

**Comment by Optiligence** [comment]
there is no need since the CMake version that gets bumped is part of the version
(`1.8.1_3.19-1` → `1.8.1_3.20-1`)

**Comment by Biswa96** [comment]
Just asking. Should the package version append another package version number?

**Comment by Optiligence** [comment]
Other packages sync their versioning or have it in their name. (which wasn’t done here, i’m not the author of `cotire`)
I don’t think there is a »should«. I think it fits the way it is. It’s the primary and only dependency and wont work if the minor version doesn’t match.

**Comment by Biswa96** [comment]
All right. Thanks for sharing.

**Pull request merged**
