### PR TITLE
bat: redesign recipe

### PR DESCRIPTION
**Pull request by ognevny**
- make it to match template
- add changes for dynamic linking
- set `GIT_DIR=/dev/null` to resolve

<details>

```
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\logs/HEAD: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\index: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\logs/HEAD: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\index: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
```

</details>

- removed cargo install as it's always recompiled (I didn't find a solution for it)

### CODE REVIEW

**Comment by ognevny** [comment]
excitement: enforce dynamic linking for system libs

**Comment by lazka** [comment]
fyi, git issues can usually be worked around by `export GIT_DIR=/dev/null`

**Comment by ognevny** [comment]
> fyi, git issues can usually be worked around by `export GIT_DIR=/dev/null`

I'll try it. thanks

**Comment by lazka** [comment]
(unless the build really needs git, but usually it will bail out if git reports there is no repo)

**Review by ognevny — COMMENTED** [review]
> (unless the build really needs git, but usually it will bail out if git reports there is no repo) 

I didn't find any mention about it in build scripts. with GIT_DIR=/dev/null it builds without any error

**Comment by ognevny** [comment]
currently I'm slowly working on enforcing dynamic linking for some rust-based packages. let's try this one first

**Pull request merged**
