### PR TITLE
poppler-qt6: Add package

### PR DESCRIPTION
**Pull request by Biswa96**
Just an experiment for this issue https://github.com/msys2/MINGW-packages/issues/9126

### CODE REVIEW

**Comment by Biswa96** [comment]
@sunderme Would you like to try the packages from the GitHub Actions artifacts?

**Comment by sunderme** [comment]
I can try. Is there a comfortable way, to get them on a CD machine ?

**Comment by sunderme** [comment]
I think it is much easier to have this PR merged.
As a new package, it does not break anything else and I can set-up the txs CD build against this easily then.

**Comment by Biswa96** [comment]
I'd like to wait if someone comments or approves this change. Meanwhile you could test the package in your macine.

**Comment by Biswa96** [comment]
OK, no comment so far, merging...

**Comment by sunderme** [comment]
thanks

**Comment by sunderme** [comment]
Now that the package is build, the pkgconfig file is missing.
in poppler it is (among others): e.g.  /mingw64/lib/pkgconfig/poppler-cpp.pc

**Comment by Biswa96** [comment]
I was expecting this reply. The pkgconfig file is added in new version of poppler. For that, we'll need to update poppler. But it also needs a rebuild of plethora of packages.

**Comment by sunderme** [comment]
okay, thanks for the quick reply

**Pull request merged**
