### PR TITLE
gcc: add conflicts for objc and ada

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
Our pacman is patched to default to "yes" for conflicts, so I hope that this makes things work with "--noconfirm"

**Comment by lazka** [comment]
@Alexpux any thoughts on this?

**Comment by Alexpux** [comment]
@lazka I dont have time for gcc rebuild, so i will leave it open for some time

**Comment by lazka** [comment]
ok :+1:

**Comment by lazka** [comment]
objc and ada are back ->closing

**Pull request closed without merging**
