### PR TITLE
Update luarocks to 3.7.0 and fix installed files

### LINKED ISSUE #9037: [mingw-w64-(i686|x86_64)-lua-luarocks] 3.5.0-1 seems to be borked
I have previously used (and still have on a non-updated PC) the **2.4.4-2** versions of these packages and have been using those with the corresponding 5.1 **[mingw-w64-(i686|x86_64)-lua]** interpreters (**5.1.5-5**) version on that machine after fixing an issue with the 32-bit version (#5928, #6580). On a fresh machine (new install of Windows 10 Pro) this *new*, *improved* set of packages - which is supposed to support multiple Lua versions but which looks to come preset for Lua 5.1 and 5.4 - can't even find their own configuration files for any version. Using the `luarocks` command all on its own defaults to **5.4** (by default one has to also include a `--lua-version 5.x` option for a different version) - on the x86_64 side of things reports the following at the end of the output: 
```sh
   ...
   Configuration:
   Lua:
      Version    : 5.4
      Interpreter: C:\msys64\mingw64\bin/lua.exe (ok)
      LUA_DIR    : C:\msys64\mingw64 (ok)
      LUA_BINDIR : C:\msys64\mingw64\bin (ok)
      LUA_INCDIR : C:\msys64\mingw64/include (ok)
      LUA_LIBDIR : C:\msys64\mingw64/bin (ok)

   Configuration files:
      System  : /mingw64/etc/luarocks/config-5.4.lua (not found)
      User    : C:/msys64/home/stephen/.luarocks/config-5.4.lua (not found)

   Rocks trees in use:
      C:\msys64\home\stephen/.luarocks ("user")


stephen@Hunt MINGW64 ~
$
```

correspondingly for 5.1:
```sh
   ...
   Configuration:
   Lua:
      Version    : 5.1
      Interpreter: C:\msys64\mingw64\bin/lua5.1.exe (ok)
      LUA_DIR    : C:\msys64\mingw64 (ok)
      LUA_BINDIR : C:\msys64\mingw64\bin (ok)
      LUA_INCDIR : C:\msys64\mingw64/include/lua5.1 (ok)
      LUA_LIBDIR : C:\msys64\mingw64/bin (ok)

   Configuration files:
      System  : /mingw64/etc/luarocks/config-5.1.lua (not found)
      User    : C:/msys64/home/stephen/.luarocks/config-5.1.lua (not found)

   Rocks trees in use:
      C:\msys64\home\stephen/.luarocks ("user")
```

Note the file suggested by the output for the *system* "Configuration files:" **`/mingw64/etc/luarocks/config-5.4.lua (not found)`** and **`/mingw64/etc/luarocks/config-5.4.lua (not found)`** - yet strangely ***both files do exist and have content***:
```sh
stephen@Hunt MINGW64 ~
$ more /mingw64/etc/luarocks/config-5.?.lua
::::::::::::::
/mingw64/etc/luarocks/config-5.1.lua
::::::::::::::
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/mingw64" };
}
lua_interpreter = "lua5.1.exe";
variables = {
   LUA_DIR = "/mingw64";
   LUA_INCDIR = "/mingw64/include/lua5.1";
   LUA_BINDIR = "/mingw64/bin";
}
::::::::::::::
/mingw64/etc/luarocks/config-5.4.lua
::::::::::::::
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/mingw64" };
}
lua_interpreter = "lua.exe";
variables = {
   LUA_DIR = "/mingw64";
   LUA_BINDIR = "/mingw64/bin";
}
```

With this as a starting point it is not surprising that trying to install a rock fails miserably:
```sh
stephen@Hunt MINGW64 ~
$ luarocks --lua-version 5.1 install utf8
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/utf8-1.2-0.src.rock
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting C:\msys64\home\stephen/.cache/luarocks/https___luarocks.org/manifest-5.1.zip

Error: Failed unpacking rock file: C:\msys64\tmp/luarocks_luarocks-rock-utf8-1.2-0-8831/utf8-1.2-0.src.rock: failed extracting C:\msys64\tmp/luarocks_luarocks-rock-utf8-1.2-0-8831/utf8-1.2-0.src.rock
```

The output from running the above again with an additional `--verbose` argument is this: [luarocks_install_ut8_rock_failure_log.txt](https://github.com/msys2/MINGW-packages/files/6744442/luarocks_install_ut8_rock_failure_log.txt) - superficially it *seems* that handling of Windows `\` path delimiters seems to be messed up... 😜 

Looking more closely at what upstream has been doing to Luarock since 3.x versions have been worked on it looks like the MSYS2/Mingw-w64 package build instructions are way out of date - since @kou 's actions in https://github.com/msys2/MINGW-packages/pull/7431#issuecomment-743451407 points out - the patch in https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-lua-luarocks (in https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua-luarocks/mingw32-msys2.patch ) must be re-examined to see if it is still relevant. Also in https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua-luarocks/luarocks-x86_64.install and https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua-luarocks/luarocks-i686.install both try to `sed` some paths in the corresponding `${MINGW_PREFIX}/etc/luarocks/config-5.1.lua` files (but it is not clear that that works now as there may be other files for other Lua versions (currently 5.4 by default) and similarly for `${MINGW_PREFIX}/share/lua/5.1/luarocks/site_config.lua` - and those files do not exist any more! {I tried to create one for Lua 5.1 to see if it would fix things - but it doesn't seem to...!}

### PR DESCRIPTION
**Pull request by ImperatorS79**
Fix #9037 I hope.

@SlySven It works for me, If you have time could you test this ?

### CODE REVIEW

**Comment by ImperatorS79** [comment]
I do not really understand the failure: this is the right sha256sum 🤔.

**Comment by lazka** [comment]
Could be line ending conversion changing it

**Comment by ImperatorS79** [comment]
Thanks ^^.

**Comment by lazka** [comment]
ok to merge

**Comment by ImperatorS79** [comment]
@lazka If you could try to install a package, for example:
```
 luarocks --lua-version=5.1 install utf8 
```
and it works, then it is ok to merge (you should install lua51 for this package).

**Pull request merged**
