### PR TITLE
gcc: build libgccjit

### PR DESCRIPTION
**Pull request by lazka**
ported from #6572

### CODE REVIEW

**Comment by lazka** [comment]
> enable-host-shared typically slows the rest of the compiler down by
a few %, so you must explicitly enable it.
>
 >If you want to build both the jit and the regular compiler, it is often
best to do this via two separate configure/builds, in separate
directories, to avoid imposing the performance cost of
--enable-host-shared on the regular compiler.

I guess we should create a separate package..

**Comment by kirill-gerasimenko** [comment]
Wow, that would be awesome when merged! Will allow to build native comp branch of Emacs

**Comment by WolfgangRamos** [comment]
Hi @lazka, thank you for your effort to bringing `libgccjit` to `mingw`. I am looking forward to this being available in order to build emacs native-comp branch for windows.

I tried building gcc with the `PKGBUILD` file from your `libgccjit` branch. I also added the `--enable-host-shared` option to `configure` in order to circumvent the error message 
````
Enabling language "jit" requires --enable-host-shared. [...]
````

However I ended up with this error message:
````
config.status: executing depdir commands
mkdir -p -- .deps
config.status: executing gccdepdir commands
mkdir -p -- build/.deps
mkdir -p -- ada/.deps
mkdir -p -- brig/.deps
mkdir -p -- c/.deps
mkdir -p -- cp/.deps
mkdir -p -- d/.deps
mkdir -p -- fortran/.deps
mkdir -p -- go/.deps
mkdir -p -- jit/.deps
mkdir -p -- lto/.deps
mkdir -p -- objc/.deps
mkdir -p -- objcp/.deps
mkdir -p -- c-family/.deps
mkdir -p -- common/.deps
mkdir -p -- analyzer/.deps
config.status: executing default commands
make[3]: Entering directory '/c/Users/wr/dev/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32/gcc'
TARGET_CPU_DEFAULT="" \
HEADERS="auto-host.h ansidecl.h config/i386/xm-mingw32.h" DEFINES="" \
/bin/sh ../../gcc-10.2.0/gcc/mkconfig.sh config.h
TARGET_CPU_DEFAULT="" \
HEADERS="options.h insn-constants.h config/vxworks-dummy.h config/i386/biarch64.h config/i386/i386.h config/i386/unix.h config/i386/bsd.h config/i386/gas.h config/dbxcoff.h config/i386/cygming.h config/i386/mingw-pthread.h config/i386/mingw32.h config/i386/mingw-w64.h config/i386/mingw-stdint.h config/initfini-array.h defaults.h" DEFINES="LIBC_GLIBC=1 LIBC_UCLIBC=2 LIBC_BIONIC=3 LIBC_MUSL=4" \
/bin/sh ../../gcc-10.2.0/gcc/mkconfig.sh tm.h
TARGET_CPU_DEFAULT="" \
HEADERS="config/i386/i386-protos.h tm-preds.h" DEFINES="" \
/bin/sh ../../gcc-10.2.0/gcc/mkconfig.sh tm_p.h
TARGET_CPU_DEFAULT="" \
HEADERS="auto-host.h ansidecl.h config/i386/xm-mingw32.h" DEFINES="" \
/bin/sh ../../gcc-10.2.0/gcc/mkconfig.sh bconfig.h
make[3]: *** No rule to make target '../build-x86_64-w64-mingw32/libiberty/pic/libiberty.a', needed by 'build/genmodes.exe'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/c/Users/wr/dev/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32/gcc'
make[2]: *** [Makefile:4752: all-stage1-gcc] Error 2
make[2]: Leaving directory '/c/Users/wr/dev/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32'
make[1]: *** [Makefile:24494: stage1-bubble] Error 2
make[1]: Leaving directory '/c/Users/wr/dev/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32'
make: *** [Makefile:1009: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
````

Did you encounter this error as well? Do you have any ideas how it could be solved? I searched for this error, but did not find anything helpful :(

**Comment by WolfgangRamos** [comment]
I think I found the answer to my own question :)
The patch that brings `libgccjit` to windows (via `mingw`) will be part of gcc 11.0 (see [here](https://gcc.gnu.org/pipermail/gcc-patches/2020-May/546384.html) for the mailing list discussion and [here](https://github.com/gcc-mirror/gcc/commit/c83027f32d9cca84959c7d6a1e519a0129731501) for the commit in the gcc master branch) which is planned for early 2021. The patch seems to the remove the 
````
Enabling language "jit" requires --enable-host-shared. [...]
````
error for mingw-platform builds as well as the error I observed with the missing `libiberty.a`. We should then be able to build without `--enable-host-shared`.

So there is nothing we can do atm. We will simply have to wait for gcc 11.0 to be released.

**Comment by lazka** [comment]
We can also backport if it is self contained.

**Comment by WolfgangRamos** [comment]
Yes we could. I am however not that much of a c developer, so presumably I won't be of much help :( All I could do is try to apply the patch to gcc 10.2.0 source and hope for it to apply cleanly. Maybe I will try that...

But for me it would also be totally OK to wait until gcc 11.0 is released. I waited for a faster emacs for years now...I think I could spare another few months :D

**Comment by WolfgangRamos** [comment]
Awesome, thank you for backporting 👍

**Comment by lazka** [comment]
https://gcc.gnu.org/onlinedocs/jit/intro/tutorial01.html works fine here, so I think this is ready.

**Comment by nicber** [comment]
Thanks you for backporting.

It would be nice to backport this commit too https://github.com/gcc-mirror/gcc/commit/f8d6596c791562442c5bdb9656b6ba7c830c3e62.

I've created a branch including that commit in https://github.com/nicber/MINGW-packages/tree/libgccjit

**Comment by lazka** [comment]
Thanks, pulled from your branch.

**Comment by kirill-gerasimenko** [comment]
Thanks for this!

Do I get it correctly that I can now issue the following command to get the package?:
```
pacman -S mingw-w64-x86_64-libgccjit
```

**Comment by lazka** [comment]
> Do I get it correctly that I can now issue the following command to get the package?:

Once it is in the repo, yes. (might take some days)

**Comment by deb75** [comment]
Hi,

[There](https://gitlab.com/debry/mingw-packages) if you cannot wait.

I will try to build gccemacs (emacs feature/native-comp branch) and propose a package, based on MINGW-packages-dev/emacs, as it was my original purpose.

Regards

**Comment by lazka** [comment]
its now in the repo

**Pull request merged**
