### PR TITLE
nlopt: add c++ libs

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by jeroen** [comment]
Hmm this still doesn't seem to include the c++ lib :/

**Comment by Biswa96** [comment]
NLOPT_CXX option is enabled by default. Is there any way we can help?

**Comment by jeroen** [comment]
Maybe they just renamed the static library? In an older version I had `libnlopt.a` and `libnlopt_cxx.a` but maybe they merged them or something.... I'll try to figure out what is going on.

**Comment by Biswa96** [comment]
> I had libnlopt.a and libnlopt_cxx.a but maybe they merged them or something....

Seems right https://github.com/stevengj/nlopt/commit/8da50d516fe0a0da42c06b66329b02cf6e44236e

**Pull request closed without merging**
