### PR TITLE
enable some more clangarm64 packages

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by jeremyd2019** [comment]
First package failed:
```
  ==> Starting build()...
  configure: loading site script /etc/config.site
  Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized
  configure: error: /bin/sh ../SDL-1.2.15/build-scripts/config.sub aarch64-w64-mingw32 failed
  ==> ERROR: A failure occurred in build().
```
https://github.com/msys2-arm/MINGW-packages/runs/5491295637?check_suite_focus=true#step:9:241

**Comment by Biswa96** [comment]
SDL can be compiled for clangarm64 using latest git repo.

**Comment by kmilos** [comment]
Thanks, I guess it might be ageneral issue with older autotools packages, I'll pay more attention.

**Comment by kmilos** [comment]
SDL package update to git will wait for another day, let's try a smaller batch without it and deps...

**Pull request merged**
