### PR TITLE
portmidi: upgrade to 2.0.3

### PR DESCRIPTION
**Pull request by kmilos**
Switching to new repository and codebase: https://github.com/PortMidi/portmidi

### CODE REVIEW

**Comment by Biswa96** [comment]
Should those test executables be installed? If yes, can the patch file be upstreamed?

**Comment by kmilos** [comment]
They were in the previous package (directly done inside `package()`), so I thought I'd keep them... Indeed, not installed by default by upstream, but e.g. OpenSUSE distributes them as well (w/ `portmidi-` prefix though)...

I'm ok with skipping them as well...

**Comment by lazka** [comment]
I think it's fine to drop them.

**Comment by kmilos** [comment]
Done, vanilla it is.

**Pull request merged**
