### PR TITLE
helics: update to 3.1.1

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by Biswa96** [comment]
Instead of sed commands, a patch file may be better option.

**Comment by neheb** [comment]
how strange that alligned_alloc is not supported. It's part of C++17.

**Comment by raedrizqie** [comment]
> how strange that alligned_alloc is not supported. It's part of C++17.

it is guarded with ``_LIBCPP_USING_IF_EXISTS``
>D:/M/msys64/clang64/include/c++/v1/cstdlib:158:1: note: using declaration annotated with 'using_if_exists' here
  using ::aligned_alloc _LIBCPP_USING_IF_EXISTS;

is there any way to come around this?

**Comment by jeremyd2019** [comment]
https://github.com/chriskohlhoff/asio/issues/922

**Pull request closed without merging**
