### PR TITLE
exiv2: update to 0.28.1

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
cmake files are now installed in /share instead of /lib. Is that ok? IIRC, /share is used for header only packages.

**Comment by kmilos** [comment]
Good catch, I wasn't aware of that change. I think it should be in /lib/cmake as well, will work on a patch...

**Comment by MehdiChinoune** [comment]
cmake search in both lib and share folders for config and module files.

**Comment by kmilos** [comment]
> cmake search in both lib and share folders for config and module files

Indeed, but might still be worth keeping some consistency across one platform...

**Pull request merged**
