### PR TITLE
minizip-ng: rename minzip2 to minizip-ng and update to 3.0.7

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by kmilos** [comment]
Thanks!

**Comment by Neustradamus** [comment]
Thanks @MehdiChinoune!

It is possible to replace https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip-git by https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip with official minizip from zlib (source: https://github.com/madler/zlib/tree/master/contrib/minizip)?

cc: @gvollant, @madler.

And to add https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-zlib-ng with https://github.com/zlib-ng/zlib-ng?

cc: @zlib-ng, @nmoinvaz.

**Comment by MehdiChinoune** [comment]
see #14046

**Comment by Neustradamus** [comment]
@MehdiChinoune: Not good...

**Comment by MehdiChinoune** [comment]
What't not good?

**Pull request merged**
