### PR TITLE
New package: bscan-spi-bitstreams

### PR DESCRIPTION
**Pull request by wlph17**
JTAG-SPI proxy bitstreams to be used with the OpenOCD jtagspi flash driver

### CODE REVIEW

**Comment by Biswa96** [comment]
Please follow the PKGBUILD templates here https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-PKGBUILD-templates before creating a package. Also see the guidelines here https://www.msys2.org/dev/new-package/

If possible create a proper package in your fork then do the pull request. Multiple git pushes will flood the notification for those who are watching this repository.

**Comment by wlph17** [comment]
oh sorry about that

**Comment by wlph17** [comment]
I think this is ready to merge

**Comment by wlph17** [comment]
The binary blobs for Xilinx and Lattice chips  was generated by python script in https://github.com/quartiq/bscan_spi_bitstreams.

**Comment by lazka** [comment]
Ah, I see, thanks. I'll give that a try.

**Comment by wlph17** [comment]
you're welcome.

**Pull request merged**
