### PR TITLE
python-pybase64: Update to 1.3.2

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
There is an issue with this one https://github.com/mayeut/pybase64/issues/674
It doesn't build c-module.

**Comment by lazka** [comment]
I see, thanks. Not a regression at least.

**Comment by mayeut** [comment]
If you want a hard failure if the extension is not built, please define `CIBUILDWHEEL=1` environment variable.

**Comment by MehdiChinoune** [comment]
Could I push my changes? with 32-bit disabled

**Comment by lazka** [comment]
Which changes?

**Comment by MehdiChinoune** [comment]
> Which changes?

https://github.com/MehdiChinoune/MINGW-packages/commit/b10f8bcd4de0a6fbc6abd6eab783605ec6b150fd

**Comment by lazka** [comment]
That's not much different than my changes here, but sure, if you want.

**Pull request closed without merging**
