### PR TITLE
lcms2: update to 2.16

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
Should we pass `-Dutils=true` to keep the executables?

**Comment by kmilos** [comment]
> Should we pass `-Dutils=true` to keep the executables?

Definitely, sorry for missing the new option...

**Comment by kmilos** [comment]
@lazka P.S. Thanks for the vote of confidence and the invite, but can't really commit to the project more in earnest at this time, sorry.

**Comment by lazka** [comment]
No problem. There are no extra obligations, just more permissions, in case you reconsider.

**Pull request merged**
