### PR TITLE
Enable sctp (data channel) and windows plugins

### PR DESCRIPTION
**Pull request by BFamzz**
WebRTC Data Channel requires sctp plugin. MediaFoundation and Wasapi2 are improved windows specific plugins.

### CODE REVIEW

**Comment by Biswa96** [comment]
mediafoundation can not be build right now. mingw-w64 headers need some additions. I am working on that. And I assume wasapi2 is for WinRT or UWP environment, not for desktop apps.

**Comment by BFamzz** [comment]
Alright. I'll restrict this PR to enabling only sctp. Thanks.

**Comment by Biswa96** [comment]
I think sctp is enabled automatically. See the file list of gst-plugins-lib package. For example, here is the output:

```
$ pacman -Fl mingw-w64-x86_64-gst-plugins-bad-libs | grep -i sctp
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/bin/libgstsctp-1.0-0.dll
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/include/gstreamer-1.0/gst/sctp/
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/include/gstreamer-1.0/gst/sctp/sctp-prelude.h
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/include/gstreamer-1.0/gst/sctp/sctpreceivemeta.h
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/include/gstreamer-1.0/gst/sctp/sctpsendmeta.h
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/include/gstreamer-1.0/gst/webrtc/sctptransport.h
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/lib/libgstsctp-1.0.dll.a
mingw-w64-x86_64-gst-plugins-bad-libs mingw64/lib/pkgconfig/gstreamer-sctp-1.0.pc
```

For sctp, meson.build file checks for libnice package which is already present in depends list.

**Comment by BFamzz** [comment]
My thoughts initially, but running 

`gst-inspect-1.0 sctp`

resulted in

`No such element or plugin 'sctp'`

**Comment by Biswa96** [comment]
Did you install gst-plugins-bad and gst-plugins-bad-libs package both? Those are two different packages.

**Comment by BFamzz** [comment]
Yes, they are both installed.

image

**Comment by lazka** [comment]
looks like there is a library and a plugin, and this enables the plugin.

lgtm

**Comment by Biswa96** [comment]
FI, I have sent a patch to upstream mingw-w64 for the mediafoundation plugin https://sourceforge.net/p/mingw-w64/mailman/message/37605807/.

**Comment by BFamzz** [comment]
Thanks and well done.

**Comment by BFamzz** [comment]
> FI, I have sent a patch to upstream mingw-w64 for the mediafoundation plugin https://sourceforge.net/p/mingw-w64/mailman/message/37605807/.

@Biswa96 please any update on this? Thanks.

**Comment by BFamzz** [comment]
> FI, I have sent a patch to upstream mingw-w64 for the mediafoundation plugin https://sourceforge.net/p/mingw-w64/mailman/message/37605807/.

Hello @Biswa96 please has this patch been merged upstream and can mediafoundation be enabled in gstreamer going-forward?

Thanks.

**Comment by Biswa96** [comment]
Thank you for the reminder. I have re-enabled the media foundation plugin here https://github.com/msys2/MINGW-packages/commit/8c5e6b6d8fe9df69fcc9e2fb8a9cc862a20e1238

**Comment by BFamzz** [comment]
Thanks!

**Pull request merged**
