### PR TITLE
enter-tex: add package, renamed from gnome-latex

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
I can not figure out the meson error.

**Comment by Biswa96** [comment]
@eli-schwartz could you provide any hint to troubleshoot this meson issue?

**Comment by eli-schwartz** [comment]
It's not precisely a meson issue (maybe not a meson issue at all). Meson successfully configured.

When compiling `src/gtex/Gtex-1.gir` using gnome's g-ir-scanner, it appears to be instructed to parse libgtex-static.a instead of libgtex-shared.dll, and the gnome introspection tooling emits an error that it cannot find a shared DLL at that location (the .a file).

**Comment by eli-schwartz** [comment]
https://gitlab.gnome.org/swilmet/enter-tex/-/blob/main/src/gtex/meson.build#L129

```meson.build
GNOME.generate_gir(
  GTEX_STATIC_LIB,
  header: 'gtex.h',
```

Interesting.

**Comment by Biswa96** [comment]
> the gnome introspection tooling emits an error that it cannot find a shared DLL at that location (the .a file).

Do you mean that should be changed to shared library target gtex_shared_lib?

**Comment by eli-schwartz** [comment]
It sounds like it, yes. At the very least, ask upstream whether they think it might make sense to do so. :p

**Comment by Biswa96** [comment]
I have reported the issue in upstream https://gitlab.gnome.org/swilmet/enter-tex/-/issues/21

**Pull request closed without merging**
