### PR TITLE
ruby: update to 3.3.4

### PR DESCRIPTION
**Pull request by raedrizqie**
- fix building on clang32
- drop obsolete patches
- drop redundant meta packages

### CODE REVIEW

**Comment by ognevny** [comment]
> ucrt32

😨

**Comment by lazka** [comment]
Can you explain why those changes are needed?

**Comment by raedrizqie** [comment]
1. All the removed patches are not needed anymore in 3.3.4
2. `0009-ucrt-platform-arch.patch` is needed to fix building gems on clang32, because of mismatch between ruby arch and ruby platform
3. The removed meta packages are just clones of ruby package. We always put ruby as depends anyway, not those meta package

**Comment by raedrizqie** [comment]
these changes has been accepted upstream:
https://github.com/ruby/ruby/commit/00176cd40fe9f385231e9c20b956fc4a84d240b9
https://github.com/ruby/ruby/commit/f1224e55fda658a7395bd3512c6aaa92cbf4a25c

its up to you guys to wait for next update or not.. closing this

**Pull request closed without merging**
