### PR TITLE
tklib: rebuild

### PR DESCRIPTION
**Pull request by oscarfv**
Hope this is the right procedure for requesting a rebuild of a -git package.

Thanks.

### CODE REVIEW

**Comment by lazka** [comment]
OK with my changes?

**Comment by oscarfv** [comment]
@lazka : that's good.

**Comment by oscarfv** [comment]
With those changes, sucessive `pacman -Suy` switches one package for another:

```
$ pacman -Suy
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
:: Replace mingw-w64-i686-tklib with mingw32/mingw-w64-i686-tklib-git? [Y/n]
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-i686-tklib-0.7.r1974.57e720fd-1 [removal]
             mingw-w64-i686-tklib-git-r1737.65490b01-1

Total Installed Size:  3.36 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(2/2) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) removing mingw-w64-i686-tklib                [#####################] 100%
(1/1) installing mingw-w64-i686-tklib-git          [#####################] 100%

Oscar@win7-32-vm MSYS /etc
$ pacman -Suy
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
:: Replace mingw-w64-i686-tklib-git with mingw32/mingw-w64-i686-tklib? [Y/n]
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-i686-tklib-0.7.r1974.57e720fd-1
             mingw-w64-i686-tklib-git-r1737.65490b01-1 [removal]

Total Installed Size:  3.36 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(2/2) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) removing mingw-w64-i686-tklib-git            [#####################] 100%
(1/1) installing mingw-w64-i686-tklib              [#####################] 100%

```

**Comment by lazka** [comment]
yeah, the old package needs to be removed. @elieux can you clean up https://packages.msys2.org/removals ?

**Comment by oscarfv** [comment]
I think the problem is related to the way pacman handles version numbers and it is likely to happen with similar changes to other packages.

For this specific case this should fix the issue:

```
--- /home/oscar/dev/other/MINGW-packages/mingw-w64-tklib/PKGBUILD
+++ #<buffer mingw-w64-tklib/PKGBUILD>
@@ -3,7 +3,6 @@
 _realname=tklib
 pkgbase=mingw-w64-${_realname}
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
-pkgver=0.7.r1974.57e720fd
 pkgrel=1
 pkgdesc="A companion to Tcllib, for Tk related packages (mingw-w64)"
 arch=('any')
@@ -19,7 +18,7 @@
 
 pkgver() {
   cd "${_realname}"
-  printf '0.7.r%s.%s' "$(git rev-list --count "${_commit}")" "$(git rev-parse --short "${_commit}")"
+  printf 'r%s.%s' "$(git rev-list --count "${_commit}")" "$(git rev-parse --short "${_commit}")"
 }
 
 build() {
```

**Comment by lazka** [comment]
This is about both packages having the other under "replaces". The version number doesn't matter as they have different package names.

**Comment by lazka** [comment]
should be fixed now

**Comment by oscarfv** [comment]
Thank you.

**Pull request merged**
