### PR TITLE
scrcpy: new package

### PR DESCRIPTION
**Pull request by Freed-Wu**
Refer <https://github.com/Genymobile/scrcpy/blob/master/BUILD.md>

### CODE REVIEW

**Comment by Freed-Wu** [comment]
chanage b2sums to sha256sums

**Comment by Biswa96** [comment]
I'm not sure if this is right way to provide a package. Two signifact parts are/can not provided as mingw package. The adb client program and scrcpy server written in Java.

**Comment by Freed-Wu** [comment]
I refer the arch's PKGBUILD, maybe they use a pre-built scrcpy-server not build it because of convenience. About `adb`, prehaps it can be built by mingw, although I have not tried.

**Comment by MehdiChinoune** [comment]
It couldn't be used without adb!

**Comment by Biswa96** [comment]
I have compiled adb with mingw gcc and clang partially. See this project here https://github.com/Biswa96/android-tools-win. The only catch is that DLLs require atlmfc library which can be only compiled with msvc. Also the library is license restricted. So, one has to reimplement it in mingw-w64 without looking at the actual code.

**Comment by MehdiChinoune** [comment]
A package that's not usable at all shouldn't be added at first place!
I still wondering why was it merged?

**Comment by driver1998** [comment]
> I have compiled adb with mingw gcc and clang partially. See this project here https://github.com/Biswa96/android-tools-win. The only catch is that DLLs require atlmfc library which can be only compiled with msvc. Also the library is license restricted. So, one has to reimplement it in mingw-w64 without looking at the actual code.

I would rather update adb to not use ATL at this point... Not sure what it is used for, cppwinrt and wil are sutiable alternatives if you just need some COM wrappers.

**Pull request merged**
