### PR TITLE
qt5-static: update to 5.15.10

### PR DESCRIPTION
**Pull request by MehdiChinoune**
It fails to build on i686 (both mingw32 and clang32), Anyone interested in it is welcome to fix it.

### CODE REVIEW

**Comment by lazka** [comment]
For future reference, do you remember what the error/issue was for i686?

**Comment by MehdiChinoune** [comment]
I will post later, but IIRC It was qtsensors and exactly Bluetooth submodules that failed to build because of some missing definitions. Most probably a MinGW-w64 issue.

**Comment by MehdiChinoune** [comment]
CLANG32:
```
...
clang++ -c -mfpmath=sse -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wextra -Wno-ignored-attributes -Wdate-time -Winconsistent-missing-override -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_SENSORS_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_CORE_LIB -DJAS_DLL=0 -I. -I../../include -I../../include/QtSensors -I../../include/QtSensors/5.15.10 -I../../include/QtSensors/5.15.10/QtSensors -Itmp -IC:/_/B/src/CLANG32/qtbase/include/QtCore/5.15.10 -IC:/_/B/src/CLANG32/qtbase/include/QtCore/5.15.10/QtCore -IC:/_/B/src/CLANG32/qtbase/include -IC:/_/B/src/CLANG32/qtbase/include/QtCore -I.moc/release -IC:/_/B/src/CLANG32/qtbase/mkspecs/win32-clang-g++  -o .obj/release/qsensor.o qsensor.cpp
2023-09-09T06:43:36.8051870Z ../../../3rdparty/assimp/src/include/assimp/vector3.h:72:5: warning: definition of implicit copy assignment operator for 'aiVector3t<float>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
2023-09-09T06:43:36.8099388Z     aiVector3t( const aiVector3t& o ) = default;
2023-09-09T06:43:36.8103018Z clang++ -c -mfpmath=sse -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wextra -Wno-ignored-attributes -Wdate-time -Winconsistent-missing-override -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_WIN_BLUETOOTH -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_BLUETOOTH_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DJAS_DLL=0 -I. -I../../include -I../../include/QtBluetooth -I../../include/QtBluetooth/5.15.10 -I../../include/QtBluetooth/5.15.10/QtBluetooth -Itmp -IC:/_/B/src/CLANG32/qtbase/include/QtCore/5.15.10 -IC:/_/B/src/CLANG32/qtbase/include/QtCore/5.15.10/QtCore -IC:/_/B/src/CLANG32/qtbase/include -IC:/_/B/src/CLANG32/qtbase/include/QtCore -IC:/_/B/src/CLANG32/qtbase/include/QtConcurrent -I.moc/release -IC:/_/B/src/CLANG32/qtbase/mkspecs/win32-clang-g++  -o .obj/release/qbluetoothservicediscoveryagent_win.o qbluetoothservicediscoveryagent_win.cpp
...
qbluetoothservicediscoveryagent_win.cpp:276:43: error: cannot initialize a parameter of type 'PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK' (aka 'int (*)(unsigned long, unsigned char *, unsigned long, void *) __attribute__((stdcall))') with an lvalue of type 'BOOL (ULONG, LPBYTE, ULONG, LPVOID)' (aka 'int (unsigned long, unsigned char *, unsigned long, void *)')
...
                                           bluetoothSdpCallback,
                                           ^~~~~~~~~~~~~~~~~~~~
D:/M/msys64/clang32/include/bluetoothapis.h:307:44: note: passing argument to parameter 'pfnCallback' here
     PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK pfnCallback,
                                            ^
 1 error generated.
```
MINGW32:
```
...
g++ -c -fno-keep-inline-dllexport -march=pentium4 -mtune=generic -Wa,-mbig-obj -mfpmath=sse -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_WIN_BLUETOOTH -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_BLUETOOTH_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DJAS_DLL=0 -I. -I../../include -I../../include/QtBluetooth -I../../include/QtBluetooth/5.15.10 -I../../include/QtBluetooth/5.15.10/QtBluetooth -Itmp -IC:/_/B/src/MINGW32/qtbase/include/QtCore/5.15.10 -IC:/_/B/src/MINGW32/qtbase/include/QtCore/5.15.10/QtCore -IC:/_/B/src/MINGW32/qtbase/include -IC:/_/B/src/MINGW32/qtbase/include/QtCore -IC:/_/B/src/MINGW32/qtbase/include/QtConcurrent -I.moc/release -IC:/_/B/src/MINGW32/qtbase/mkspecs/win32-g++  -o .obj/release/qbluetoothservicediscoveryagent_win.o qbluetoothservicediscoveryagent_win.cpp
...
qbluetoothservicediscoveryagent_win.cpp: In function 'FindServiceResult findNextService(HANDLE)':
 qbluetoothservicediscoveryagent_win.cpp:276:43: error: invalid conversion from 'BOOL (*)(ULONG, LPBYTE, ULONG, LPVOID)' {aka 'int (*)(long unsigned int, unsigned char*, long unsigned int, void*)'} to 'PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK' {aka 'int (__attribute__((stdcall)) *)(long unsigned int, unsigned char*, long unsigned int, void*)'} [-fpermissive]
   276 |                                           bluetoothSdpCallback,
       |                                           ^~~~~~~~~~~~~~~~~~~~
       |                                           |
       |                                           BOOL (*)(ULONG, LPBYTE, ULONG, LPVOID) {aka int (*)(long unsigned int, unsigned char*, long unsigned int, void*)}
 In file included from qbluetoothservicediscoveryagent_win.cpp:56:
 D:/M/msys64/mingw32/include/bluetoothapis.h:307:44: note:   initializing argument 3 of 'WINBOOL BluetoothSdpEnumAttributes(LPBYTE, ULONG, PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK, LPVOID)'
   307 |     PFN_BLUETOOTH_ENUM_ATTRIBUTES_CALLBACK pfnCallback,
```

**Comment by Biswa96** [comment]
Could you provide a link to that file?

**Comment by MehdiChinoune** [comment]
> Could you provide a link to that file?

https://github.com/MehdiChinoune/MINGW-packages/actions/runs/6129159984

**Comment by Biswa96** [comment]
qtconnectivity has that same build failure. I shall add a pull request to fix that. The same patch can be copied to qt5-static.

**Pull request merged**
