### PR TITLE
Drop qt5 meta-package

### PR DESCRIPTION
**Pull request by MehdiChinoune**
It has no user now.

### CODE REVIEW

**Comment by lazka** [comment]
There might be some fallout of users installing it in CI etc... but I can write a NEWS entry about it.

**Comment by MehdiChinoune** [comment]
`pacman -S ${MINGW_PACKAGE_PREFIX}-qt5` will install qt5 group for them which contains all the Qt5 packages. the same as `toolchain`.

**Comment by lazka** [comment]
ah, I see, thanks

**Comment by MehdiChinoune** [comment]
https://github.com/search?q=mingw-w64-x86_64-qt5&type=code

**Pull request merged**
