### PR TITLE
gcc: try latest available snapshot (NOT TO BE MERGED)

### PR DESCRIPTION
**Pull request by oscarfv**
... to see if it contains a fix for #8320

### CODE REVIEW

**Comment by oscarfv** [comment]
This build fails with a configure error on libgomp (on stage 2, if I'm correct). Now trying gcc-11 + EH patch on #9035.

```
2021-07-03T02:17:29.6847319Z mkdir -p -- i686-w64-mingw32/libgomp
2021-07-03T02:17:29.7431682Z Checking multilib configuration for libgomp...
2021-07-03T02:17:29.8665757Z Configuring stage 1 in i686-w64-mingw32/libgomp
2021-07-03T02:17:34.9920382Z configure: loading site script /etc/config.site
2021-07-03T02:17:35.0190664Z configure: creating cache ./config.cache
2021-07-03T02:17:35.0206347Z checking for --enable-version-specific-runtime-libs... no
2021-07-03T02:17:35.0207899Z checking for --enable-generated-files-in-srcdir... no
2021-07-03T02:17:35.1581938Z checking build system type... i686-w64-mingw32
2021-07-03T02:17:35.2260715Z checking host system type... i686-w64-mingw32
2021-07-03T02:17:35.2979055Z checking target system type... i686-w64-mingw32
2021-07-03T02:17:35.2980274Z checking for a BSD-compatible install... /usr/bin/install -c
2021-07-03T02:17:35.3475058Z checking whether build environment is sane... yes
2021-07-03T02:17:35.4943821Z checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
2021-07-03T02:17:35.4948666Z checking for gawk... gawk
2021-07-03T02:17:35.6139459Z checking whether make sets $(MAKE)... yes
2021-07-03T02:17:35.7099141Z checking whether make supports nested variables... yes
2021-07-03T02:17:35.8748898Z checking for i686-w64-mingw32-gcc... /C/_/mingw-w64-gcc/src/build-i686-w64-mingw32/./gcc/xgcc -B/C/_/mingw-w64-gcc/src/build-i686-w64-mingw32/./gcc/ -L/mingw32/i686-w64-mingw32/lib -L/mingw32/lib -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/include -B/mingw32/i686-w64-mingw32/bin/ -B/mingw32/i686-w64-mingw32/lib/ -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/i686-w64-mingw32/sys-include   -fno-checking
2021-07-03T02:17:36.5474489Z checking whether the C compiler works... yes
2021-07-03T02:17:36.5483808Z checking for C compiler default output file name... a.exe
2021-07-03T02:17:36.8272433Z checking for suffix of executables... .exe
2021-07-03T02:17:37.1259476Z configure: error: in `/C/_/mingw-w64-gcc/src/build-i686-w64-mingw32/i686-w64-mingw32/libgomp':
2021-07-03T02:17:37.1261103Z configure: error: cannot run C compiled programs.
2021-07-03T02:17:37.1262007Z If you meant to cross compile, use `--host'.
2021-07-03T02:17:37.1262718Z See `config.log' for more details
2021-07-03T02:17:37.3458989Z make[2]: *** [Makefile:24035: configure-stage1-target-libgomp] Error 1
```

**Comment by Biswa96** [comment]
You can test any changes in your own forked repository. CI will run same thing.

**Comment by oscarfv** [comment]
> You can test any changes in your own forked repository. CI will run same thing.

That's news to me, thank you.

(What a waste of electricity!)

**Comment by jeremyd2019** [comment]
only if you enable it, you have to go to the "Actions" tab of your fork and allow it

**Pull request closed without merging**
