### PR TITLE
libraw: Update to 0.20.2

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
Is the rebuild of darktabel on purpose?

re the error: you need to add `validpgpkeys=('F10F9686652B0E949FCD94C318DCA123F949BD3B ')` to the package.

**Comment by Biswa96** [comment]
^ Also increate pkgrel in PKGBUILD file of mingw-w64-python-tifffile?

**Comment by Biswa96** [comment]
^ Also increase pkgrel in PKGBUILD file of mingw-w64-python-tifffile?

**Comment by kmilos** [comment]
Sorry, committed some WIP to this branch by mistake...

**Comment by kmilos** [comment]
I guess I need to squash these together for a successful build? Even with the revert and gpg keys, darktable won't build anyway because of lensfun...

**Comment by lazka** [comment]
> I guess I need to squash these together for a successful build?

I guess so

**Pull request merged**
