### PR TITLE
gimp3: Use git commit instead of tarball when building

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by Biswa96** [comment]
May I ask why this is required?

**Comment by hmartinez82** [comment]
@Biswa96 Because the last version that has a tarball is from last year. Since this is heavily under development still I thought that devs would be more interested in having a close to 2.99.15 as possible build

**Comment by Biswa96** [comment]
> I thought that devs would be more interested in having a close to 2.99.15 as possible build

msys2 is not that much bleeding edge, is it? 🤔 According to [the download page](https://download.gimp.org/pub/gimp/v2.99/), version 2.99.14 is just 2 months old.

**Comment by mmuetzel** [comment]
Afaict, builds from release tarballs are preferred over bleeding-edge repository checkouts. That is, unless there are good reasons for not using the latest release...

**Pull request closed without merging**
