### PR TITLE
Add libopenmpt-modplug

### PR DESCRIPTION
**Pull request by drfiemost**
A wrapper around libopenmpt that replaces libmodplug, as requested in #8435
As noted by upstream:

> CAUTION: The emulation of the libmodplug interface is not complete as libmodplug exposes lots of internal implementation details. If any of those is used by an application, the emulation via libopenmpt will fail and/or crash

### CODE REVIEW

**Comment by drfiemost** [comment]
Should libmodplug be marked as conflicting with this one?

**Comment by lazka** [comment]
> Should libmodplug be marked as conflicting with this one?

yes, "conflicts" and "provides"

**Comment by Biswa96** [comment]
The provides and conflicts should also contain `${MINGW_PACKAGE_PREFIX}-` string in package name. Also increase the `pkgrel` of libmodplug.

**Comment by Biswa96** [comment]
With double quote please 😁

**Comment by lazka** [comment]
not sure if conflicts in both directions add much, but can't hurt I guess. Thanks!

**Pull request merged**
