### PR TITLE
feat: add serust

### PR DESCRIPTION
**Pull request by thewh1teagle**
Add `serust` 
Serial monitor CLI tool
used for debug microcontrollers over USB with serial connection,
or with arduino / raspberry pi, etc...
from https://github.com/thewh1teagle/serust

### CODE REVIEW

**Comment by ognevnydemon** [comment]
no need to vendor deps if you don't patch them. just use `cargo fetch --locked`

**Comment by thewh1teagle** [comment]
Fixed

**Comment by ognevnydemon** [comment]
> Fixed

sorry for late answer. also you need to remove `mingw32` and `clang32`

**Comment by thewh1teagle** [comment]
@ognevnydemon 
removed `mingw32` and `clang32`, and added `email` on top.

**Comment by ognevnydemon** [comment]
> added `email` on top.

it's not needed, also this one is incorrect because it's automatically created by github

**Comment by lazka** [comment]
So this seems to be a small personal project that's not packages anywhere. I'm wondering if we should add it.

**Comment by thewh1teagle** [comment]
It's already packaged into `Winget`. If you think you will add it, just reopen / merge.

**Comment by lazka** [comment]
I was just curious what others were thinking about it, since I haven't worked with serial connections in a while, and can't judge how useful it would be for our users.

**Pull request closed without merging**
