### PR TITLE
zed: update to 0.143.7

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by Suburbanno** [comment]
how to fix?

image
@ognevny

**Comment by ognevny** [comment]
> how to fix?
> 
> image
> @ognevny 

this is already reported upstream: https://github.com/zed-industries/zed/issues/13575. does the package work at the moment?

**Comment by Suburbanno** [comment]
> > how to fix?
> > image
> > @ognevny
> 
> this is already reported upstream: [zed-industries/zed#13575](https://github.com/zed-industries/zed/issues/13575). does the package work at the moment?

I hadn't seen this issue, sorry.

But at the moment it doesn't work and I haven't found the solution yet

**Comment by ognevny** [comment]
I guess I should revert that update, right?

**Comment by Suburbanno** [comment]
> I guess I should revert that update, right?

let's wait for the next update

**Comment by ognevny** [comment]
> > I guess I should revert that update, right?
> 
> let's wait for the next update

there was a report that the issue didn't fix on git master. anyway I'll try to rebuild today locally

**Comment by ognevny** [comment]
> there was a report that the issue didn't fix on git master. anyway I'll try to rebuild today locally

with Zed from pacman I don't get any errors, but when I build it from git master (in debu mode) I get the same errors as above

**Comment by Suburbanno** [comment]
> > there was a report that the issue didn't fix on git master. anyway I'll try to rebuild today locally
> 
> with Zed from pacman I don't get any errors, but when I build it from git master (in debu mode) I get the same errors as above

I tried to redo the entire process from scratch, but the error remains

**Comment by Polygons1** [comment]
@Suburbanno, just update your graphics driver and it should work

**Pull request merged**
