### PR TITLE
liblo: fix compilation with lld

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
Another thing in the list of GCC can but LLVM can't.

**Comment by neheb** [comment]
lld is a linker. gcc is a compiler. You're thinking of GOLD.

**Comment by jeremyd2019** [comment]
BFD if you want to be pedantic :wink:

**Comment by neheb** [comment]
:)

**Comment by mati865** [comment]
> Another thing in the list of GCC can but LLVM can't.

Opened https://github.com/msys2/CLANG-packages/issues/45

**Pull request merged**
