### PR TITLE
grpc: Update PKGBUILD

### PR DESCRIPTION
**Pull request by fundies**
Because #6324

### CODE REVIEW

**Comment by lazka** [comment]
I've reverted this since grpc and all other deps affected by the c-ares .so bump got rebuilt yesterday.

**Comment by fundies** [comment]
> I've reverted this since grpc and all other deps affected by the c-ares .so bump got rebuilt yesterday.

grpc was not rebuilt after c-ares

**Comment by Alexpux** [comment]
@fundies grocery was updated yesterday to 1.27.3 after c-ares update

**Comment by fundies** [comment]
it was upgraded *before* cares commits

**Comment by Alexpux** [comment]
@fundies you are wrong. See what is changed in commit that you point me. There was rebuild of packages that depends on grpc

**Comment by Alexpux** [comment]
I reverted changes

**Comment by fundies** [comment]
well either your servers hadn't updated the package or whatever before you merged my commit because I was having runtime errors in my build just last night 
https://dev.azure.com/enigma-dev/ENIGMA/_build/results?buildId=852&view=logs&j=faa49efd-b80d-59ec-f116-4ddab3c93356&t=f9c47ca7-7422-52b4-f0d1-0ba1ba4299de&l=664

however, it seems to be working now and I don't really care when/how it was fixed as long as it was fixed

**Comment by lazka** [comment]
You can see the order in which packages were rebuild here: https://packages.msys2.org/updates

Note that this doesn't have to match the order in which changes landed it git.

Glad it's working now, thanks for the report.

**Pull request merged**
