### PR TITLE
python-pygame: update to v2.1.3

### PR DESCRIPTION
**Pull request by wszqkzqk**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
There is one problem!
```
$ vercmp.exe 2.1.3 2.1.3.dev8
-1
```

**Comment by Biswa96** [comment]
Is it allowed to fake pkgver? `2.1.3.0` worked though.

```
$ vercmp.exe 2.1.3.0 2.1.3.dev8
1
```

**Comment by wszqkzqk** [comment]
> Is it allowed to fake pkgver? `2.1.3.0` worked though.
> 
> ```
> $ vercmp.exe 2.1.3.0 2.1.3.dev8
> 1
> ```

What about `1:2.1.3`

**Comment by wszqkzqk** [comment]
> > Is it allowed to fake pkgver? `2.1.3.0` worked though.
> > ```
> > $ vercmp.exe 2.1.3.0 2.1.3.dev8
> > 1
> > ```
> 
> What about `1:2.1.3`

According to arch wiki's advice, maybe `2.1.3.0` is better.

**Pull request merged**
