### PR TITLE
Add mingw-w64-fox-dev

### PR DESCRIPTION
**Pull request by iahung2**

### CODE REVIEW

**Comment by iahung2** [comment]
> There is already a mingw fox package, see https://packages.msys2.org/base/mingw-w64-fox. I am not sure if both versions should exist in different package.

This is FOX 1.7. I don't know how to put it in the same mingw fox package.

**Comment by lazka** [comment]
Are fox 1.6 and 1.7 not compatible? i.e. is there a need to provide both versions?

**Comment by iahung2** [comment]
> Are fox 1.6 and 1.7 not compatible? i.e. is there a need to provide both versions?

Yes. They are not compatible.

**Comment by Biswa96** [comment]
ArchLinux has 1.6.xx version but Gentoo has 1.7.xx. There are two ways I can think of.
1. update the fox package as usual from 1.6 to 1.7.
2. create separate package with 1.7 version, similar as pangomm, cairomm etc.

**Comment by lazka** [comment]
According to http://fox-toolkit.org/download.html 1.7 is a development version and 1.6 is the stable version.

If there is a good reason why we should package a development version we can think about it, otherwise I'd close this.

**Comment by iahung2** [comment]
> According to http://fox-toolkit.org/download.html 1.7 is a development version and 1.6 is the stable version.
> 
> If there is a good reason why we should package a development version we can think about it, otherwise I'd close this.

Explained in detail here: https://github.com/msys2/MINGW-packages/issues/19718#issuecomment-1888729049

**Comment by iahung2** [comment]
Btw, building from source is easy and fast enough with franko's Meson based build system. I will drop this PR. I created it as my first attempt to contribute to the MSYS2 project. I will try something different.

**Comment by lazka** [comment]
I see thanks. Given this situation I can understand the need for a separate package, so I'm not against adding one.

**Pull request closed without merging**
