### PR TITLE
[new-package] Qt6 6.0.2

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by Biswa96** [comment]
Just FYI, by modular packages, it means to use tarballs from submodules folder in download.qt.io link.
1. ArchLinux: https://archlinux.org/packages/?q=qt6
2. AUR: https://aur.archlinux.org/packages/?O=0&K=mingw-w64-qt6

**Comment by Biswa96** [comment]
Just FYI, by modular packages, it means to use tarballs from submodules folder in download.qt.io link. Then build the packages with separate PKGBUIILD files. This reduces the build time and make the packages easier to debug.

1. ArchLinux: https://archlinux.org/packages/?q=qt6
2. AUR: https://aur.archlinux.org/packages/?O=0&K=mingw-w64-qt6

**Comment by MehdiChinoune** [comment]
> Just FYI, by modular packages, it means to use tarballs from submodules folder in download.qt.io link. Then build the packages with separate PKGBUIILD files. This reduces the build time and make the packages easier to debug.
> 
> 1. ArchLinux: https://archlinux.org/packages/?q=qt6
> 2. AUR: https://aur.archlinux.org/packages/?O=0&K=mingw-w64-qt6

I followed the same way [Clang-packages](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-clang/PKGBUILD) are built.
Build them from tarballs make upgrading them very difficult. for example if someone wants to upgrade Qt6 to 6.1.0 he should upgrade qt6-base first, push it to the repo and waits until it merges then push qt6-svg, qt6-declarative ... (qt6-base direct dependants) and then qt6-quick3d...

**Comment by Biswa96** [comment]
> waits until it merges then push qt6-svg, qt6-declarative

FYI, that thing was past. In this GitHub Actions, stating repository is added automatically. First an updated base package will be installed then the dependent packages will be built.

**Comment by MehdiChinoune** [comment]
> > waits until it merges then push qt6-svg, qt6-declarative
> 
> FYI, that thing was past. In this GitHub Actions, stating repository is added automatically. First an updated base package will be installed then the dependent packages will be built. More details here https://packages.msys2.org/queue

Still you have to make separate pull-requests for them, you can't upgrade them with the same pull-request.

**Comment by lazka** [comment]
> Still you have to make separate pull-requests for them, you can't upgrade them with the same pull-request.

That should still work in one PR.

But anyway, this is a good start, so merging.

Thanks!

**Pull request merged**
