### PR TITLE
libavif: Build static library

### LINKED ISSUE #19510: [libavif] static library missing
### Description / Steps to reproduce the issue

in  our CI environment we build static windows builds. Since the last update pf sdl2 image  libavif is required but does not provide a static library.

### Expected behavior

Please add a static library of avif to the package

### Actual behavior

no static library provided

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

uname

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #19510

### CODE REVIEW

**Comment by kmilos** [comment]
How about patching `libavif.pc` w/ `Cflags.private: -UAVIF_DLL` as well for good measure?

**Comment by Biswa96** [comment]
> How about patching `libavif.pc` w/ `Cflags.private: -UAVIF_DLL` as well for good measure?

That would also be an solution. I am not sure if that would cause any issue in other packages. Please feel free to create a pull request with that change after this pull request.

**Comment by kmilos** [comment]
> That would also be an solution. I am not sure if that would cause any issue in other packages.

Don't think so because we never had a static lib?

> Please feel free to create a pull request with that change after this one.

That'll have to wait until 2024...

**Comment by Biswa96** [comment]
> That'll have to wait until 2024...

OK, I shall try to add that flag in this pull request.

**Comment by Biswa96** [comment]
I have tried to add `Cflags.private: -UAVIF_DLL` in libavif.pc but got compiler errors like following while compiling tests in libavif.

```
ld.exe: libavif.dll.a(libavif_16_dll_d000096.o):(.text+0x0): multiple definition of `avifVersion'; libavif_internal.a(avif.c.obj):avif.c:(.text+0x0): first defined here
```

**Comment by hessenfarmer** [comment]
ok I tried the new packages. after adding a lot of static dependencies i finally failed with this dependency

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib/librav1e.a(rav1e.std-195b9aabdc2e76b7.std.b6d1d6f02fc704f8-cgu.04.rcgu.o.rcg
u.o):(.text+0x11d5): undefined reference to `NtWriteFile'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib/librav1e.a(rav1e.std-195b9aabdc2e76b7.std.b6d1d6f02fc704f8-cgu.04.rcgu.o.rcg
u.o):(.text+0x120c): undefined reference to `RtlNtStatusToDosError'

**Comment by hessenfarmer** [comment]
so if sdl2image package intend on enabling the avif dependency it will break our (and any other) static build

**Comment by Biswa96** [comment]
ntdll is required for `RtlNtStatusToDosError`.

**Comment by kmilos** [comment]
> I have tried to add `Cflags.private: -UAVIF_DLL` in libavif.pc but got compiler errors

🤷

**Comment by Biswa96** [comment]
> I have tried to add `Cflags.private: -UAVIF_DLL` in libavif.pc but got compiler errors like following while compiling tests in libavif.
> 
> ```
> ld.exe: libavif.dll.a(libavif_16_dll_d000096.o):(.text+0x0): multiple definition of `avifVersion'; libavif_internal.a(avif.c.obj):avif.c:(.text+0x0): first defined here
> ```

That issue was probably fixed in https://github.com/AOMediaCodec/libavif/commit/7b9a07243834dfc3d7b6518008e3426ee9a12ed3 commit. I can not reproduce the compiler error in libavif repository.

**Pull request merged**
