### PR TITLE
Try to fix rust for Vista

### PR DESCRIPTION
**Pull request by jeroen**
Hi, just testing this on the CI, if it will work!

### CODE REVIEW

**Comment by lazka** [comment]
Note that we don't support Vista any more.

**Comment by jeroen** [comment]
Yeah I know :( I just want to test and then maybe use it locally.

**Comment by jeroen** [comment]
I just need to build a version of librsvg that can run on Windows 2008. It can be a one-off thing.

**Comment by lazka** [comment]
We have lots of older versions (also pre-rustification) here: http://repo.msys2.org/mingw/x86_64/

**Comment by jeroen** [comment]
@lazka I know, but those didn't always work well, for example: https://github.com/ropensci/magick/issues/240

I tested it a bit and the rendering is much bettter with the latest rsvg. The only thing that prevents me from pushing this to our users is this stupid `SetThreadErrorMode` call...

**Comment by jeroen** [comment]
Actually someone else just pointed out my diagnosis was wrong. The call to `SetThreadErrorMode` is not in librsvg but in `libgmodule-2.0.a`

**Comment by jeroen** [comment]
So this is not actually needed, as it turns out rustc requries Windows 7 but the resulting binaries still work on Windows Vista. The problem I have is actually in glib2.

By the way, why doesn't the rust build succeed? I was getting the same build error locally. I don't think it's related to the patch.

**Comment by mati865** [comment]
> By the way, why doesn't the rust build succeed?

Hard to tell without closer look but could be another GCC 10 victim.

**Pull request closed without merging**
