### PR TITLE
Update GTK to 3.99.4; Update pango to 1.48.0

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by lazka** [comment]
it depends on an unreleased pango

**Comment by taozuhong** [comment]
> It depends on an unreleased pango. We'll have to wait for a pango release first I think.

right exactly

**Comment by lazka** [comment]
I've read on IRC that a new pango release will be out soon.

**Comment by lazka** [comment]
(another thing, gtk4 no longer depends on atk)

**Pull request merged**
