### PR TITLE
qt5: backport assimp fix

### LINKED ISSUE #7360: Qt5 strange build error
`make[3]: Entering directory '/E/mingw-w64-qt5/src/x86_64/qtremoteobjects/mkspecs/features'
make -f Makefile.Release
Project ERROR: Library 'assimp' is not defined.`

At first i decided to check assimp for errors and as it turned out there is atleast one as the pkgconfig file has wrong include paths.
But even after fixing that the build error is the same ?!?

### PR DESCRIPTION
**Pull request by lazka**
This came up in CI, see if it helps

See https://bugreports.qt.io/browse/QTBUG-84037

Fixes #7360

### CODE REVIEW

**Comment by lazka** [comment]
looks better, I'll wait with merging until there are more qt5 changes (since this didn't finish in time and requires a manual build)

**Comment by Biswa96** [comment]
If you have time would you like to check if ` 0304-qtdeclarative-disable-dx12.patch` file can be removed? I think dxd12 things were added in mingw-w64 since last discussion about it with Alexpux.

**Comment by lazka** [comment]
@Biswa96 

```
make[6]: Entering directory '/C/_/mingw-w64-qt5/src/x86_64/qtdeclarative/src/plugins/scenegraph/d3d12'
fxc.exe /nologo /E VS_VertexColor /T vs_5_0 /Fh vs_vertexcolor.hlslh shaders/vertexcolor.hlsl
make[6]: fxc.exe: No such file or directory
make[6]: *** [Makefile.Release:234: vs_vertexcolor.hlslh] Error 127
```

**Comment by Biswa96** [comment]
> fxc.exe /nologo /E VS_VertexColor /T vs_5_0 /Fh vs_vertexcolor.hlslh shaders/vertexcolor.hlsl

Some use this https://github.com/mozilla/fxc2. Wish I had million cores in my CPU to build Qt5! Thank you for testing ❤️

**Comment by lazka** [comment]
> Some use this https://github.com/mozilla/fxc2. Wish I had million cores in my CPU to build Qt5! Thank you for testing ❤️

Any idea where d3dcompiler_47.dll in the git repo is coming from?

**Comment by Biswa96** [comment]
> Any idea where d3dcompiler_47.dll in the git repo is coming from?

"C:\Windows\System32\D3DCompiler_47.dll"

**Comment by lazka** [comment]
ah, so maybe just in the repo for wine where this doesn't exist?

**Comment by Alexpux** [comment]
Here how I test locally before. Try to build it again
https://github.com/msys2/MINGW-packages/commit/8eb921674f100e82a6c429bcecbfe1b9b7bc0f6b

**Comment by jeremyd2019** [comment]
>  I think dxd12 things were added in mingw-w64 since last discussion about it with Alexpux.

I'm not sure this CI would show what you want to see, though, as the changes from #7538 wouldn't be available to it yet.

**Comment by lazka** [comment]
I've pushed this to master directly.

**Pull request closed without merging**
