### PR TITLE
taglib: Update to 2.0

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Why not dropping 32-bit from taglib?

**Comment by lazka** [comment]
there is also mingw-w64-gst-plugins-good as a reverse dep and I didn't want to deal with that right now.

**Comment by MehdiChinoune** [comment]
OK

**Comment by MehdiChinoune** [comment]
I have pushed a commit to drop 32-bit from taglib and its reverse-dependencies.

**Pull request merged**
