### PR TITLE
pkgconf: update to 1.9.4

### PR DESCRIPTION
**Pull request by MehdiChinoune**
@1480c1 Could you try this one.
I have tested the example from #13390 .

### CODE REVIEW

**Comment by 1480c1** [comment]
Seems 1.9.4 still has issues for me

```bash
cddeg@ccom-laptop UCRT64 /d/mabs
$ cat <<'EOF' > temp.c
#include <stdint.h>
#include <opus/opusfile.h>
int main() { return (intptr_t)opus_server_info_init; }
EOF

cddeg@ccom-laptop UCRT64 /d/mabs
$ echo gcc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl)
gcc -static -IC:/msys64/ucrt64/include/opus temp.c -lopusurl -lopusfile -logg -lopus -lm -lssl -lws2_32 -lgdi32 -lcrypt32 -lcrypto -lws2_32 -lgdi32 -lcrypt32

cddeg@ccom-laptop UCRT64 /d/mabs
$ pacman -U mingw-w64-ucrt-x86_64-pkgconf-1~1.9.4-1-any.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-ucrt-x86_64-pkgconf-1~1.9.4-1

Total Installed Size:  0.50 MiB
Net Upgrade Size:      0.02 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [#######################################] 100%
(1/1) checking package integrity                                         [#######################################] 100%
(1/1) loading package files                                              [#######################################] 100%
(1/1) checking for file conflicts                                        [#######################################] 100%
(1/1) checking available disk space                                      [#######################################] 100%
:: Processing package changes...
(1/1) upgrading mingw-w64-ucrt-x86_64-pkgconf                            [#######################################] 100%

cddeg@ccom-laptop UCRT64 /d/mabs
$ gcc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl)
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x3f27): undefined reference to `op_fopen'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x5a3b): undefined reference to `op_open_callbacks'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x5bbb): undefined reference to `op_test_callbacks'
collect2.exe: error: ld returned 1 exit status

cddeg@ccom-laptop UCRT64 /d/mabs
$ echo gcc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl)
gcc -static -IC:/msys64/ucrt64/include/opus temp.c -lopusfile -lopusurl -lssl -lws2_32 -lgdi32 -lcrypt32 -lopus -lm -logg -lcrypto -lws2_32 -lgdi32 -lcrypt32
```

Seems, at least in this specific case, opusurl and opusfile is swapped?

**Comment by MehdiChinoune** [comment]
I have tested only on CLANG64.

**Comment by 1480c1** [comment]
Does clang give proper output? I will try some other environments to see if it's potentially an env issue

**Comment by MehdiChinoune** [comment]
```
$ pkgconf --static --libs opusurl
-lopusfile -lopusurl -lssl -lws2_32 -lgdi32 -lcrypt32 -lopus -lm -logg -lcrypto -lws2_32 -lgdi32 -lcrypt32
```

**Comment by 1480c1** [comment]
Seems it also gives you the incorrect output, opusurl is supposed to be first before opusfile

**Comment by MehdiChinoune** [comment]
I think clang/lld doesn't have an issue with static libraries order

**Comment by 1480c1** [comment]
With clang64, I instead get
```bash
$ cc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl)
ld.lld: error: undefined symbol: clock_gettime
>>> referenced by libopusurl.a(libopusurl_la-http.o):(op_http_conn_read_rate_update)
>>> referenced by libopusurl.a(libopusurl_la-http.o):(op_http_conn_read_rate_update)
>>> referenced by libopusurl.a(libopusurl_la-http.o):(op_http_connect)
>>> referenced 9 more times
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

and if I run
```bash
cc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl) -pthread
```
it passes

**Comment by MehdiChinoune** [comment]
I can't reproduce that!
are you executing those commands from CLANG64 or from elsewhere.

**Comment by MehdiChinoune** [comment]
I can reproduce the failure on UCRT64:
```
$ cc -static $(pkgconf --static --cflags opusurl) main.c $(pkgconf --static --libs opusurl)
D:/Programs/msys64_test/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Programs/msys64_t
est/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x3f27): undefined refere
nce to `op_fopen'
D:/Programs/msys64_test/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Programs/msys64_t
est/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x5a3b): undefined refere
nce to `op_open_callbacks'
D:/Programs/msys64_test/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Programs/msys64_t
est/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libopusurl.a(libopusurl_la-http.o):(.text+0x5bbb): undefined refere
nce to `op_test_callbacks'
collect2.exe: error: ld returned 1 exit status
```

**Comment by 1480c1** [comment]
> I can't reproduce that! are you executing those commands from CLANG64 or from elsewhere.

I did
```bash
$ . shell clang64
$ cat <<'EOF' > temp.c
#include <stdint.h>
#include <opus/opusfile.h>
int main() { return (intptr_t)opus_server_info_init; }
EOF
$ pacboy -S --needed --noconfirm cc:p opusfile:p
$ cc -static $(pkgconf --static --cflags opusurl) temp.c $(pkgconf --static --libs opusurl)

**Comment by MehdiChinoune** [comment]
your output of `pkgconf --static --libs opusurl` seems different.
```
$ pkgconf --static --libs opusurl
-lopusfile -lopusurl -lssl -lws2_32 -lgdi32 -lcrypt32 -lopus -lm -logg -lcrypto -lws2_32 -lgdi32 -lcrypt32
```

**Comment by 1480c1** [comment]
```bash
cddeg@ccom-laptop UCRT64 /c/Users/cddeg
$ pkgconf --static --libs opusurl
-lopusfile -lopusurl -lssl -lws2_32 -lgdi32 -lcrypt32 -lopus -lm -logg -lcrypto -lws2_32 -lgdi32 -lcrypt32
```
mine seems to be exactly the same as yours?

**Comment by MehdiChinoune** [comment]
never

**Pull request closed without merging**
