### PR TITLE
qemu: Update to 9.2.0

### PR DESCRIPTION
**Pull request by heljkon**
see https://wiki.qemu.org/ChangeLog/9.2

### CODE REVIEW

**Comment by heljkon** [comment]
@lazka @jeremyd2019 @Biswa96 @MehdiChinoune 
Please review and merge

**Comment by jeremyd2019** [comment]
I think @pbo-linaro was going to suggest some patches to re-enable clang64/clangarm64, but there's probably no rush to do that in this version.

**Comment by pbo-linaro** [comment]
Indeed. I'm waiting for the [related series](https://lore.kernel.org/qemu-devel/20241128201510.869974-1-pierrick.bouvier@linaro.org/) to be merged, so we can conveniently cherry-pick the related commits on 9.2.0 that was released today.

You can proceed now if you prefer, we can always update the patches later if some nits are reported.

**Comment by pbo-linaro** [comment]
The patches related to clang support have been merged upstream.
I created this [PR](https://github.com/msys2/MINGW-packages/pull/23135) to backport it to msys2 QEMU package.

**Pull request merged**
