### PR TITLE
slim-simulator: Update to version 3.7.1

### PR DESCRIPTION
**Pull request by rdinnager**
This just updates `slim-simulator` to the newest version. Didn't require any changes except for the sha256sums of course.

### CODE REVIEW

**Comment by neheb** [comment]
```
  C:/_/mingw-w64-slim-simulator/src/SLiM_pacman/eidos/eidos_globals.cpp:87:30: error: static assertion failed: SLiM must be built for 64-bit, not 32-bit.
     87 | static_assert(sizeof(char *) == 8, "SLiM must be built for 64-bit, not 32-bit.");
        |               ~~~~~~~~~~~~~~~^~~~
```

looks like a CI bug.

**Comment by Biswa96** [comment]
> looks like a CI bug.

Nope. mingw32 is not present mingw_arch. So, the package is not built for 32 bit. CI just runs anyway. LGTM.

**Comment by neheb** [comment]
> > looks like a CI bug.
> 
> Nope. mingw32 is not present mingw_arch. So, the package is not built for 32 bit. CI just runs anyway. LGTM.

that's exactly what I meant.

**Comment by Biswa96** [comment]
Understand. That can be ignored for this case.

**Pull request merged**
