### PR TITLE
llvm: update to 18.1.8

### PR DESCRIPTION
**Pull request by oscarfv**

### CODE REVIEW

**Comment by oscarfv** [comment]
CLANG64 timed out :(

**Comment by ognevny** [comment]
> CLANG64 timed out :(

all-in-one updates will take long to compile anyway

**Comment by luau-project** [comment]
I already built some llvm-related packages on my own with different compilers. The most annoying is LLVM flang, which is memory hungry and takes a lot of time to compile. Checking the logs, it was exactly on flang compilation that timed out your build.

**Comment by MehdiChinoune** [comment]
> I already built some llvm-related packages on my own with different compilers. The most annoying is LLVM flang, which is memory hungry and takes a lot of time to compile. Checking the logs, it was exactly on flang compilation that timed out your build.

It doesn't time-out because of flang. It times out because clang is built with PGO on CLANG* environments.

**Pull request merged**
