### PR TITLE
rust: update to 1.82.0

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by ognevny** [comment]
for a future reference, docs fail to generate with
```
   Documenting std v0.0.0 (C:\_\B\src\rustc-1.82.0-src\library\std)
  warning: dropping unsupported crate type `dylib` for target `wasm32-wasip1`
  
  error[E0432]: unresolved import `crate::sys::cvt`
   --> std\src\os\unix\net\addr.rs:7:5
    |
  7 | use crate::sys::cvt;
    |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`
  
  error[E0432]: unresolved import `crate::sys::cvt`
    --> std\src\os\unix\net\datagram.rs:24:5
     |
  24 | use crate::sys::cvt;
     |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`
  
  error[E0432]: unresolved import `crate::sys::cvt`
   --> std\src\os\unix\net\listener.rs:4:5
    |
  4 | use crate::sys::cvt;
    |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`
  
  error[E0432]: unresolved import `crate::sys::cvt`
    --> std\src\os\unix\net\stream.rs:21:5
     |
  21 | use crate::sys::cvt;
     |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`
  
  error[E0432]: unresolved import `crate::sys::cvt`
   --> std\src\os\windows\io\handle.rs:8:5
    |
  8 | use crate::sys::cvt;
    |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`
  
  error[E0432]: unresolved import `crate::sys::cvt`
   --> std\src\os\windows\io\socket.rs:9:5
    |
  9 | use crate::sys::cvt;
    |     ^^^^^^^^^^^^^^^ no `cvt` in `sys`
  
  error[E0425]: cannot find value `SOMAXCONN` in crate `libc`
     --> std\src\os\unix\net\listener.rs:104:48
      |
  104 |             const backlog: libc::c_int = libc::SOMAXCONN;
      |                                                ^^^^^^^^^ not found in `libc`
  
  error[E0433]: failed to resolve: could not resolve path `libc::SOMAXCONN`
     --> std\src\os\unix\net\listener.rs:104:42
      |
  104 |             const backlog: libc::c_int = libc::SOMAXCONN;
      |                                          ^^^^^^^^^^^^^^^ could not resolve path `libc::SOMAXCONN`
      |
      = note: this error was originally ignored because you are running `rustdoc`
      = note: try running again with `rustc` or `cargo check` and you may get a more detailed error
  
  Some errors have detailed explanations: E0425, E0432, E0433.
  For more information about an error, try `rustc --explain E0425`.
  error: could not document `std`
```
If someone wants, I can try to make a separate package for rust-docs in future

**Comment by ognevny** [comment]
CLANG32 now fails with `STATUS_STACK_BUFFER_OVERRUN`. looks like it's common for i686, but I didn't find actual way to fix this...

**Comment by ognevny** [comment]
> CLANG32 now fails with `STATUS_STACK_BUFFER_OVERRUN`. looks like it's common for i686, but I didn't find actual way to fix this...

@mati865 any thoughts?

**Comment by mati865** [comment]
Before `STATUS_STACK_BUFFER_OVERRUN` you can see errors:
- `memory allocation of 8650768 bytes failed`
- `memory allocation of 5505040 bytes failed`
- `rustc-LLVM ERROR: out of memory`

I believe they are all coming from LLVM and are probably related to mmap, similarly to https://github.com/mstorsjo/llvm-mingw/issues/151
I doubt a solution exists, and the only workaround is to drop platforms that have no real point these days (32bit in other words) https://github.com/msys2/MINGW-packages/pull/21998

**Comment by ognevny** [comment]
ok, supporting CLANG32 dropping, now with Rust toolchain being out! actually sad, I wanted to keep it at least to 1.83.0 where all backports will be finally dropped

**Comment by mati865** [comment]
I don't know what is wrong with docs but I think applying this diff will make it work for wasi:
```
❯ git diff
diff --git a/library/std/src/sys/pal/wasi/mod.rs b/library/std/src/sys/pal/wasi/mod.rs
index 8051021a588..dc5d561bdd7 100644
--- a/library/std/src/sys/pal/wasi/mod.rs
+++ b/library/std/src/sys/pal/wasi/mod.rs
@@ -48,3 +48,7 @@

 use helpers::err2io;
 pub use helpers::{abort_internal, decode_error_kind, hashmap_random_keys, is_interrupted};
+
+pub fn cvt<T: IsMinusOne>(t: T) -> io::Result<T> {
+    if t.is_minus_one() { Err(io::Error::last_os_error()) } else { Ok(t) }
+}
```

**Comment by ognevny** [comment]
thanks, will try tomorrow. also opened rust-lang/rust#131786 for CLANG32 fail

**Comment by ognevny** [comment]
> I don't know what is wrong with docs but I think applying this diff will make it work for wasi:
> ```
> ❯ git diff
> diff --git a/library/std/src/sys/pal/wasi/mod.rs b/library/std/src/sys/pal/wasi/mod.rs
> index 8051021a588..dc5d561bdd7 100644
> --- a/library/std/src/sys/pal/wasi/mod.rs
> +++ b/library/std/src/sys/pal/wasi/mod.rs
> @@ -48,3 +48,7 @@
> 
>  use helpers::err2io;
>  pub use helpers::{abort_internal, decode_error_kind, hashmap_random_keys, is_interrupted};
> +
> +pub fn cvt<T: IsMinusOne>(t: T) -> io::Result<T> {
> +    if t.is_minus_one() { Err(io::Error::last_os_error()) } else { Ok(t) }
> +}
> ```

it still fails
```
error[E0405]: cannot find trait `IsMinusOne` in this scope
    --> std\src\sys\pal\wasi\mod.rs:52:15
     |
  52 | pub fn cvt<T: IsMinusOne>(t: T) -> io::Result<T> {
     |               ^^^^^^^^^^ not found in this scope
     |
  help: consider importing this trait
     |
  41 + use crate::sys::os::IsMinusOne;
     |
  
  error[E0412]: cannot find type `Result` in module `io`
    --> std\src\sys\pal\wasi\mod.rs:52:40
     |
  52 | pub fn cvt<T: IsMinusOne>(t: T) -> io::Result<T> {
     |                                        ^^^^^^ not found in `io`
     |
  help: consider importing one of these items
     |
  41 + use crate::fmt::Result;
     |
  41 + use crate::io::Result;
     |
  41 + use crate::prelude::rust_2024::Result;
     |
  41 + use crate::thread::Result;
     |
       and 4 other candidates
  help: if you import `Result`, refer to it directly
     |
  52 - pub fn cvt<T: IsMinusOne>(t: T) -> io::Result<T> {
  52 + pub fn cvt<T: IsMinusOne>(t: T) -> Result<T> {
     |
  
  error[E0433]: failed to resolve: could not find `Error` in `io`
    --> std\src\sys\pal\wasi\mod.rs:53:35
     |
  53 |     if t.is_minus_one() { Err(io::Error::last_os_error()) } else { Ok(t) }
     |                                   ^^^^^ could not find `Error` in `io`
     |
  help: consider importing one of these items
     |
  41 + use crate::error::Error;
     |
  41 + use crate::fmt::Error;
     |
  41 + use crate::io::Error;
     |
  41 + use core::error::Error;
     |
       and 3 other candidates
  help: if you import `Error`, refer to it directly
     |
  53 -     if t.is_minus_one() { Err(io::Error::last_os_error()) } else { Ok(t) }
  53 +     if t.is_minus_one() { Err(Error::last_os_error()) } else { Ok(t) }
     |
  
  error[E0425]: cannot find value `SOMAXCONN` in crate `libc`
     --> std\src\os\unix\net\listener.rs:104:48
      |
  104 |             const backlog: libc::c_int = libc::SOMAXCONN;
      |                                                ^^^^^^^^^ not found in `libc`
  
  Some errors have detailed explanations: E0405, E0412, E0433.
  For more information about an error, try `rustc --explain E0405`.
  warning: `std` (lib) generated 1 warning
  error: could not compile `std` (lib) due to 3 previous errors; 1 warning emitted
  warning: build failed, waiting for other jobs to finish...
  error[E0433]: failed to resolve: could not resolve path `libc::SOMAXCONN`
     --> std\src\os\unix\net\listener.rs:104:42
      |
  104 |             const backlog: libc::c_int = libc::SOMAXCONN;
      |                                          ^^^^^^^^^^^^^^^ could not resolve path `libc::SOMAXCONN`
      |
      = note: this error was originally ignored because you are running `rustdoc`
      = note: try running again with `rustc` or `cargo check` and you may get a more detailed error
  
  Some errors have detailed explanations: E0405, E0412, E0425, E0433.
  error: could not document `std`
```
and CLANG32 fails to build even with -j1

**Comment by mati865** [comment]
> it still fails

RIght, forgot about imports and libc. This is an upstream bug and should be reported there.

**Pull request merged**
