### PR TITLE
spirv-cross: Add package

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
Do not merge now. Wait for the current mpv update. Otherwise this will be linked with older libplacebo. Also it is not required to increas pkgrel in libplace just for this.

**Comment by lazka** [comment]
> Do not merge now. Wait for the current mpv update. Otherwise this will be linked with older libplacebo.

autobuild has a newer placebo, so It should work imo

**Comment by Biswa96** [comment]
If I use `ntldd` command on the artifact here mpv.exe shows ` libplacebo-72.dll => not found`.

**Comment by lazka** [comment]
yes, the CI builds against the pacman repo, autobuild is smarter and builds against all packages in the queue + the pacman repo.

**Comment by Biswa96** [comment]
OK, feel free to whatever you want.

**Comment by Biswa96** [comment]
Nope, it linked with previous libplacebo.

**Comment by lazka** [comment]
mpv hasn't been built yet. Why do you think so?

**Comment by Biswa96** [comment]
O! It's different than GHA builds?

**Comment by lazka** [comment]
It gets build here: https://github.com/msys2/msys2-autobuild/actions/runs/521027269

The build status is here: https://packages.msys2.org/queue

**Pull request merged**
