### PR TITLE
arrow: Update to 0.13.0

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by jeroen** [comment]
Note that we have thrift now, so you could enable parquet: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-thrift/PKGBUILD

**Comment by kou** [comment]
Did you try it? It causes a build error:

```text
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libthrift.a(TBufferTransports.cpp.obj):(.text+0x36c): undefined reference to `__imp_htonl'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libthrift.a(TBufferTransports.cpp.obj):(.text+0x4d6): undefined reference to `__imp_ntohl'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/parquet/CMakeFiles/parquet_shared.dir/build.make:119: release/libparquet.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:1305: src/parquet/CMakeFiles/parquet_shared.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

We need to improve Apache Arrow to enable Parquet. It's out of scope of this pull request. First we should improve Apache Arrow.

**Comment by jeroen** [comment]
@kou it works for me: https://ci.appveyor.com/project/jeroen/rtools-packages/builds/23509064

That linking error usually just means you are missing `-lws2_32` somewhere. Not sure why it doesn't pop up in my build.

**Comment by kou** [comment]
Is https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-arrow/PKGBUILD your configuration?
It doesn't build shared library: https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-arrow/PKGBUILD#L65
This build error is occurred to build a shared library for Parquet.

Do you want to make "enabling Parquet" as a blocker of this "updating to 0.13.0" pull request? I don't think that "enabling Parquet" is a blocker of this pull request.

**Comment by jeroen** [comment]
No it's not a blocker.

**Pull request merged**
