### PR TITLE
opus: Enable detection of NEON and other aarch64 features

### PR DESCRIPTION
**Pull request by hmartinez82**
```
ninja: Entering directory `C:/M_P/mingw-w64-opus/src/build-CLANGARM64'
ninja: no work to do.
 1/15 test_unit_types              OK               0.12s
 2/15 test_unit_mathops            OK               0.11s
 3/15 test_unit_laplace            OK               0.08s
 4/15 test_unit_dft                OK               0.06s
 5/15 test_unit_rotation           OK               0.05s
 6/15 test_unit_mdct               OK               0.20s
 7/15 test_opus_padding            OK               0.09s
 8/15 test_opus_projection         OK               0.06s
 9/15 test_unit_cwrs32             OK               1.00s
10/15 test_unit_cwrs32             OK               1.08s
11/15 test_unit_entropy            OK               2.17s
12/15 test_opus_api                OK               4.07s
13/15 test_opus_extensions         OK              18.23s
14/15 test_opus_decode             OK              26.36s
15/15 test_opus_encode             OK              54.61s

Ok:                 15
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0
```

### CODE REVIEW

**Comment by Biswa96** [comment]
Is the patch in upstream repository?

**Comment by hmartinez82** [comment]
@Biswa96 not yet. And I'm still processing. I don't know if they want a more generic solution. But since this #if block is for MINGW64 we can assume that we are definitely targeting Windows only there? Then my assumptions hold.

I'll post the patch upstream. Let's see what they have to say :)

**Comment by Biswa96** [comment]
There is already a `#if defined(_MSC_VER)` condition in celt/arm/armcpu.c file. So, I think better condition would be adding this change into the `#else` part of that condition.

**Comment by marcosfrm** [comment]
> I'll post the patch upstream. Let's see what they have to say :)

Please do. Thanks.

**Pull request merged**
