### PR TITLE
graphicsmagick: update to 1.3.41

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by mmuetzel** [comment]
With the MINGW64 build artifact from this PR, the test suite of Octave starts to fail:
```
>>>>> processing C:\msys64\mingw64\share\octave\8.2.0\m\image\imwrite.m
***** testif HAVE_MAGICK
 gray  = randi (255, 10, 10, 1, "uint8");
 alpha = randi (255, 10, 10, 1, "uint8");
 [r, ~, a] = write_and_read (".tif", gray, "Alpha", alpha);
 assert (r, gray);
 assert (a, alpha);
!!!!! test failed
ASSERT errors for:  assert (a,alpha)

  Location  |  Observed  |  Expected  |  Reason
     .          O(0x0)      E(10x10)     Dimensions don't match
***** testif HAVE_MAGICK
 gray  = randi (255, 10, 10, 3, 5, "uint8");
 alpha = randi (255, 10, 10, 1, 5, "uint8");
 [r, ~, a] = write_and_read (".tif", gray, "Alpha", alpha);
 assert (r, gray);
 assert (a, alpha);
!!!!! test failed
ASSERT errors for:  assert (a,alpha)

  Location  |  Observed  |  Expected  |  Reason
     .          O(0x0)    E(10x10x1x5)   Dimensions don't match
***** testif HAVE_MAGICK
 rgb   = randi (255, 10, 10, 3, "uint8");
 alpha = randi (255, 10, 10, 1, "uint8");
 [r, ~, a] = write_and_read (".tif", rgb, "Alpha", alpha);
 assert (r, rgb);
 assert (a, alpha);
!!!!! test failed
ASSERT errors for:  assert (a,alpha)

  Location  |  Observed  |  Expected  |  Reason
     .          O(0x0)      E(10x10)     Dimensions don't match
***** testif HAVE_MAGICK
 rgb   = randi (255, 10, 10, 3, 5, "uint8");
 alpha = randi (255, 10, 10, 1, 5, "uint8");
 [r, ~, a] = write_and_read (".tif", rgb, "Alpha", alpha);
 assert (r, rgb);
 assert (a, alpha);
!!!!! test failed
ASSERT errors for:  assert (a,alpha)

  Location  |  Observed  |  Expected  |  Reason
     .          O(0x0)    E(10x10x1x5)   Dimensions don't match
```
Afaict, these tests are about .tif images with transparency.

We've seen the same with GraphicsMagick from Homebrew since they updated to 1.3.41:
https://github.com/Homebrew/homebrew-core/pull/139411

Could we please hold this update until we can verify whether this is an issue with Octave or with GraphicsMagick?

**Comment by mmuetzel** [comment]
Hmm... Guess my comment came 10 minutes too late...

**Comment by ognevnydemon** [comment]
> Hmm... Guess my comment came 10 minutes too late...

I think you can revert it

**Comment by kmilos** [comment]
I guess tis is related to this upstream change:
```
TIFF: Require that TIFFTAG_EXTRASAMPLES be used appropriately to indicate the intention of extra channels.
```
Are Octave test files "invalid" in this respect, i.e. missing the [ExtraSamples](https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html) tag? Or tags not matching up in some other aspect?

**Comment by mmuetzel** [comment]
Octave uses GraphicsMagick to write those files. It sets the image type to, e.g., `Magick::GrayscaleMatteType`. According to its documentation that means "Grayscale image with opacity". I guess, it should be setting all necessary tags automatically.

I tried to write a small sample image using with ImageMagick 1.3.40 and ImageMagick 1.3.41. They seem to be byte-identical (apart from a version number). So, it's probably the reading part that changed.

**Comment by mmuetzel** [comment]
I opened #18183 with a potential fix.

**Pull request merged**
