### PR TITLE
Update x264

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by omichel** [comment]
That broke `ffmpeg.exe` which depends on `avcodec-58.dll` which depends on `libx264-159.dll`, however, this update replaced `libx264-159.dll` with `libx264-161.dll`. I guess we need a new `ffmpeg` package with fixed dependencies.

**Comment by Biswa96** [comment]
But ffmpwg was rebuilt here.

**Comment by omichel** [comment]
Yes, but the current MSYS2 is broken: my system is up-to-date and when I type `ffmpeg.exe`, I get this:
```bash
$ ffmpeg.exe
D:/msys64/mingw64/bin/ffmpeg.exe: error while loading shared libraries: swscale-5.dll: cannot open shared object file: No such file or directory
$ pacman -Qi mingw-w64-x86_64-ffmpeg
Name            : mingw-w64-x86_64-ffmpeg
Version         : 4.4-3
Description     : Complete and free Internet live audio and video broadcasting
                  solution (mingw-w64)
Architecture    : any
URL             : https://ffmpeg.org/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : mingw-w64-x86_64-aom  mingw-w64-x86_64-bzip2
                  mingw-w64-x86_64-celt  mingw-w64-x86_64-frei0r-plugins
                  mingw-w64-x86_64-fontconfig  mingw-w64-x86_64-dav1d
                  mingw-w64-x86_64-gnutls  mingw-w64-x86_64-gsm
                  mingw-w64-x86_64-lame  mingw-w64-x86_64-libass
                  mingw-w64-x86_64-libbluray  mingw-w64-x86_64-libcaca
                  mingw-w64-x86_64-libexif  mingw-w64-x86_64-libmfx
                  mingw-w64-x86_64-libmodplug  mingw-w64-x86_64-libsoxr
                  mingw-w64-x86_64-libtheora  mingw-w64-x86_64-libvorbis
                  mingw-w64-x86_64-libvpx  mingw-w64-x86_64-libwebp
                  mingw-w64-x86_64-libxml2  mingw-w64-x86_64-openal
                  mingw-w64-x86_64-opencore-amr  mingw-w64-x86_64-openjpeg2
                  mingw-w64-x86_64-opus  mingw-w64-x86_64-rtmpdump
                  mingw-w64-x86_64-SDL2  mingw-w64-x86_64-speex
                  mingw-w64-x86_64-srt  mingw-w64-x86_64-vulkan
                  mingw-w64-x86_64-x264  mingw-w64-x86_64-x265
                  mingw-w64-x86_64-xvidcore  mingw-w64-x86_64-zlib
Optional Deps   : None
Required By     : mingw-w64-x86_64-ffms2
Optional For    : mingw-w64-x86_64-libde265  mingw-w64-x86_64-opencv
Conflicts With  : None
Replaces        : None
Installed Size  : 51.84 MiB
Packager        : CI (msys2-autobuild/16f20bf2/894056292)
Build Date      : Tue, Jun 1, 2021 0:26:37
Install Date    : Wed, Jun 2, 2021 9:54:14
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by lazka** [comment]
hm, yeah, the rebuild order didn't work

**Pull request merged**
