### PR TITLE
Fix launcher for manim

### PR DESCRIPTION
**Pull request by naveen521kk**

### CODE REVIEW

**Comment by Biswa96** [comment]
FYI, if the `${MINGW_PREFIX}` is removed the result may also be same.

**Comment by naveen521kk** [comment]
> FYI, if the ${MINGW_PREFIX} is removed in the sed command then the result may also be same.

Can you give the exact sed command?

**Comment by Biswa96** [comment]
> Can you give the exact sed command?

Here:

```sh
  local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
  # fix python command in files
  for _f in "${pkgdir}${MINGW_PREFIX}"/bin/*.py; do
    sed -e "s|/usr/bin/env ||g" \
        -e "s|${PREFIX_WIN}/bin||g" -i ${_f}
  done
```

**Comment by naveen521kk** [comment]
@Biswa96 it creates a shebang like `#!/python.exe`. My aim was to not have any shebang.

**Comment by naveen521kk** [comment]
please squash while merging

**Pull request merged**
