### PR TITLE
feat: add picotool

### PR DESCRIPTION
**Pull request by thewh1teagle**
Add picotool package from
https://github.com/raspberrypi/picotool
Inspired by picotool arch Linux package.

Statically linked libraries so users can use it outside msys too.
Final binary size is ~1.32MB

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
> Statically linked libraries so users can use it outside msys too. Final binary size is ~1.32MB

MSYS2 is like any other packaging system, it relies on Dynamic linking.
If you want static libraries, you could build both. You could find some examples in other PKGBUILDs like https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-aws-c-common/PKGBUILD

**Comment by MehdiChinoune** [comment]
Also, please follow PKGBUILD-template https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-tarball.sh

**Comment by thewh1teagle** [comment]
@MehdiChinoune 
I havn't found example for PKGBUILD which build static + shared binary (not library) 
where should I place both?
should I build 2 and one binary name will be `picotool` and the second will be `picotool_static`?

Also, about the template format, I'm not sure where is the mistakes.

**Comment by ognevnydemon** [comment]
> I havn't found example for PKGBUILD which build static + shared binary (not library) 
> where should I place both?
> should I build 2 and one binary name will be `picotool` and the second will be `picotool_static`?

a good example https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-sfml%2FPKGBUILD

**Comment by MehdiChinoune** [comment]
I have fixed the PKGBUILD and merged the changes.

**Pull request merged**
