### PR TITLE
ngspice: update to 35

### PR DESCRIPTION
**Pull request by umarcor**
A new release was published.

/cc @holvo

### CODE REVIEW

**Comment by Biswa96** [comment]
Is the pkgconfig file installation procedure in upstream?

**Comment by umarcor** [comment]
@Biswa96, I don't think so: https://github.com/umarcor/MINGW-packages/runs/3394394537?check_suite_focus=true#step:9:6620

**Comment by Biswa96** [comment]
The pkgconfig file is installed when `--with-ngshared` option present. How about writing the `package()` step like this?

```sh
package() {
  cd "${srcdir}/build-shared-${CARCH}"
  make DESTDIR="${pkgdir}" install

  cd "${srcdir}/build-static-${CARCH}"
  make DESTDIR="${pkgdir}" install

  install -Dm644 "${srcdir}/${_realname}-${pkgver}/COPYING" "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
}
```

**Comment by umarcor** [comment]
Please, go ahead and give it a try!

**Pull request merged**
