### PR TITLE
mesa: disable llvm

### PR DESCRIPTION
**Pull request by MehdiChinoune**
for llvm-18
@pal1000

### CODE REVIEW

**Comment by mmuetzel** [comment]
The main reason for me to use mesa on Windows is llvmpipe. Without it, it's pretty useless to me.

**Comment by MehdiChinoune** [comment]
You are welcome to fix it to build against llvm-18.

**Comment by mmuetzel** [comment]
Did you report it upstream?

**Comment by MehdiChinoune** [comment]
> Did you report it upstream?

yes, https://gitlab.freedesktop.org/mesa/mesa/-/issues/10783

**Comment by lazka** [comment]
Could this be a general meson problem? Meson usually needs adjustmets for every llvm release

**Comment by MehdiChinoune** [comment]
> Could this be a general meson problem? Meson usually needs adjustmets for every llvm release

I think so, I should try cmake before using llvm-config. It looks like It couldn't use the new LLVM cmake files.
I tried it with LLVM-17, using llvm-config fails.

**Comment by thesamesam** [comment]
This ended up being reported as https://github.com/mesonbuild/meson/issues/12961.

**Pull request closed without merging**
