### PR TITLE
Update v8 PKGBUILD to version 8.3.110.13

### PR DESCRIPTION
**Pull request by Kwizatz**

### CODE REVIEW

**Comment by jeroen** [comment]
@Kwizatz I think this formula unintentionally depends on Visual Studio being available? When I try to build this locally I get:

```
Traceback (most recent call last):
  File "C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 561, in <module>
    sys.exit(main())
  File "C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 557, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 534, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 93, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 175, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 164, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/out/Release-x86_64/
Command: C:/msys64/mingw64/bin/python.exe C:/Users/jeroen/Desktop/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:913:1: which caused the file to be included.
action("postmortem-metadata") {

```

Probably VS is installed on the CI servers, but not on my machine. Is there a way to fix this?

**Comment by Kwizatz** [comment]
Hi @jeroen, to avoid having to duplicate a lot of the build environment, the mingw tool chain sets is_win to true and uses build/config/win/Build.gn.

As part of the build process that file copies over some dlls v8 requires from VS and the WinSDK.

I don't think the mingw build needs them, but it never complained either, so it slipped my mind looking into what to omit to avoid the copy. 

Anyway, you can look into the BUILD.gn file and remove any lines executing that vs_toolchain.py file which is the one making the copies.

**Comment by Kwizatz** [comment]
I'll have a proper fix in the 8.4 update.

**Comment by Kwizatz** [comment]
Hi @jeroen, try replacing the build.patch file with the one attached, make sure you get its sha256 into the PKGBUILD.
You can add it to your fork but please don't submit a PR to update it at MINGW-packages, there is no need, the resulting dlls and pc files would not be affected.

Also I've created a repo with scripts to make working with the v8 code easier at [https://github.com/AeonGames/v8-builder](https://github.com/AeonGames/v8-builder)

It's work in progress but you should be able to clone it and get some builds done.

```bash
source tools
fetch
build-mingw-static x64 false
```

should get static build going, if you make changes to build or v8 you can use write-build-patch or write-v8-patch to get fresh patches.
[build.zip](https://github.com/msys2/MINGW-packages/files/5146418/build.zip)

**Pull request merged**
