### PR TITLE
qt6: update to 6.2.3 - Part1

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
thanks!

**Comment by MehdiChinoune** [comment]
qt6-tools failed on MINGW64 to build with msys2-autobuild because of network issue.
qt6-shadertools failed on UCRT64 with a mysterious error about missing `stdlib.h`!

@lazka could you trigger msys2-autobuild to rebuild them

**Comment by jeremyd2019** [comment]
> qt6-shadertools failed on UCRT64 with a mysterious error about missing `stdlib.h`!

#10761

**Comment by Biswa96** [comment]
I built qt6-shadertools 6.2.3 in ucrt64 without any issue.

```
x@y UCRT64 ~/MINGW-packages/mingw-w64-qt6-shadertools/src/build-UCRT64
$ ./bin/qsb.exe --version
qsb 6.2.3
```

**Pull request merged**
