### PR TITLE
Add a pip check

### PR DESCRIPTION
**Pull request by naveen521kk**
lately, there have been many issues with broken deps for py packages. add a check for that.

I have rebuild isort as a test.

### CODE REVIEW

**Comment by naveen521kk** [comment]
This works, but something is broken when installing isort.

**Comment by naveen521kk** [comment]
ready for review

**Comment by lazka** [comment]
https://github.com/msys2/MINGW-packages/pull/8712/checks?check_run_id=2613560448

**Comment by naveen521kk** [comment]
That log is missing?

**Pull request merged**
