### PR TITLE
Python updates

### PR DESCRIPTION
**Pull request by Schala**
- python-boto3 1.17.73
- python-botocore 1.20.73
- python-click 8
- python-flask 2
- python-gsutil 4.62
- python-itsdangerous 2
- python-werkzeug 2

### CODE REVIEW

**Comment by lazka** [comment]
the jinja update is missing

**Comment by naveen521kk** [comment]
> the jinja update is missing

irrc, I updated it and it caused the sphinx problem :facepalm:

**Comment by lazka** [comment]
ah, right, missed that.

**Comment by naveen521kk** [comment]
now, https://github.com/msys2/MINGW-packages/pull/8690/commits/174a45b050b6efaf31434224f5ca498e4a53cc0a broke [manim](https://packages.msys2.org/package/mingw-w64-x86_64-manim?repo=mingw64), again :facepalm:

**Comment by lazka** [comment]
the downsides of having a proper dependency resolver in pip, people start to depend on it and use it :)

**Comment by naveen521kk** [comment]
I think getting in https://github.com/msys2/MINGW-packages/pull/8689 should at least inform us which are broken.

**Comment by jeremyd2019** [comment]
It's frustrating when people use it to pin exact versions or set maximum versions without any actual known breakage with the other versions they're blocking though.

**Comment by naveen521kk** [comment]
it's always an expectation that a major version would cause breakage(and IMO it is good practice) and quite some time it does(for example jinja did).

**Pull request merged**
