### PR TITLE
ttf-cm-unicode: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
What are they needed for?

**Comment by podsvirov** [comment]
For text rendering, of course.

**Comment by fabiangreffrath** [comment]
I mean these specific fonts. There are gazilion of free fonts available out there, but why these?

**Comment by podsvirov** [comment]
Short answer: I just ported this package from [aur](https://aur.archlinux.org/packages/ttf-cm-unicode).

**Comment by podsvirov** [comment]
@lazka thanks!

**Pull request merged**
