### PR TITLE
Assimp: fix wrong version in .pc file

### PR DESCRIPTION
**Pull request by ImperatorS79**
I don't know why, but the .pc file says version 5.2.4.

### CODE REVIEW

**Comment by Biswa96** [comment]
I think this should be fixed in the code instead of using sed command.

**Comment by ImperatorS79** [comment]
> I think this should be fixed in the code instead of using sed command.

Yes, this is a quick fix. But I did not have time to check where is the problem in the code.

**Comment by ImperatorS79** [comment]
> The project version was fixed in this upstream commit [assimp/assimp@8ce6f5a](https://github.com/assimp/assimp/commit/8ce6f5ad272cb42118a70d19668e15c1dd1615e7)
> 
> Is it possible to import that patch in PKGBUILD ?

I am doing the patch manually, as I don't know how to import it. It will be the same results at the end.

**Comment by Biswa96** [comment]
Thank you for the fix. I have verified this fixes the version number in pkgconfig file.

**Pull request merged**
