### PR TITLE
upstream CMake 3.18.5

### PR DESCRIPTION
**Pull request by scivision**

### CODE REVIEW

**Comment by orgads** [comment]
Please close. You didn't update the checksum, and 3.19.0 is already released anyway. Superseded by #7316.

**Comment by lazka** [comment]
Closing in favor of #7316

**Comment by scivision** [comment]
OK thanks 3.19.0 was the ultimate goal; I wasn't familiar with the MSYS2 package internal update process but now I see-thanks!

**Comment by Biswa96** [comment]
> I wasn't familiar with the MSYS2 package internal update process

There is no internal update process. Just 3.19.0 > 3.18.5.

**Comment by Biswa96** [comment]
> I wasn't familiar with the MSYS2 package internal update process

There is no internal update process. Just 3.19.0 > 3.18.5 🤓

**Pull request closed without merging**
