### PR TITLE
Fix libbluray.a link against libxml2.dll.a

### PR DESCRIPTION
**Pull request by shithappens2016**
Fix libbluray.a link against libxml2.dll.a

### CODE REVIEW

**Comment by lazka** [comment]
Sorry, I don't know much about static builds sadly. Is there any way I can verify what this changes/fixes?

**Comment by shithappens2016** [comment]
@lazka
<table>
<tr>
<td>
before
</td>
<td>
fixed
</td>
</tr>
<tr>
<td>
<pre>
nm libbluray.a |grep xml
                 U __imp_xmlFree            ❌
                 U xmlCleanupParser
                 U xmlDocGetRootElement
                 U xmlFreeDoc
                 U xmlGetProp
                 U xmlNodeGetContent
                 U xmlReadMemory
                 U xmlStrEqual

</pre>
</td>
<td>
<pre>
nm libbluray.a |grep xml
                 U xmlFree            ✔
                 U xmlCleanupParser
                 U xmlDocGetRootElement
                 U xmlFreeDoc
                 U xmlGetProp
                 U xmlNodeGetContent
                 U xmlReadMemory
                 U xmlStrEqual

</pre>
</td>
</tr>
</table>

**Comment by ImperatorS79** [comment]
I think this can be merged.

**Comment by lazka** [comment]
since the branch was deleted, re-created here: #10971

**Pull request closed without merging**
