### PR TITLE
poppler: update to 22.01.0

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/10487

### CODE REVIEW

**Comment by lazka** [comment]
Rebuilds:

```
mingw-w64-emacs-pdf-tools-server
mingw-w64-pdf2djvu
mingw-w64-poppler-qt6
mingw-w64-gdcm
mingw-w64-poppler
mingw-w64-gdal
mingw-w64-inkscape
```

**Comment by Biswa96** [comment]
> you delay/revert the update part...

My apology, I didn't understand that.

**Comment by lazka** [comment]
Oh, the relocation is only in the new version, never mind then. Rebuilds are needed.

**Comment by lazka** [comment]
There is some fallout for clang builds:

```
2022-01-07T13:25:45.6529314Z D:/a/msys64/clang32/include/poppler/Form.h:320:10: error: no template named 'optional' in namespace 'std'
2022-01-07T13:25:45.6530403Z     std::optional<GooString> getCheckedSignature(Goffset *checkedFileSize);
2022-01-07T13:25:45.6531143Z     ~~~~~^
2022-01-07T13:25:45.6682481Z D:/a/msys64/clang32/include/poppler/Form.h:611:10: error: no template named 'optional' in namespace 'std'
2022-01-07T13:25:45.6684003Z     std::optional<GooString> getCheckedSignature(Goffset *checkedFileSize);
2022-01-07T13:25:45.6684763Z     ~~~~~^
```

**Comment by Biswa96** [comment]
Hmm... Looks like that. g++ defaults to c++17 but clang++ defaults to c++14. Should it be bumped in every packages or for poppler only?

**Comment by Biswa96** [comment]
Hmm... Looks like that. g++ defaults to c++17 but clang++ defaults to c++14. Would there be any issue if I do it one by one with patches from upstream pull request?

**Pull request merged**
