### PR TITLE
zed: update to 0.145.1

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by Suburbanno** [comment]
I'm having problems with this update, it just won't open
@ognevny 
image

**Comment by ognevny** [comment]
that was merged too fast, that should be tested too... @lazka maybe revert it for now?

**Comment by lazka** [comment]
It works/opens fine here. But I can revert if wanted.

**Comment by ognevny** [comment]
> It works/opens fine here. But I can revert if wanted.

@Suburbanno what's your opinion here?

**Comment by Suburbanno** [comment]
> > It works/opens fine here. But I can revert if wanted.
> 
> @Suburbanno what's your opinion here?

let's wait, I'll do some more tests, redo a clean install and I'll come back and say something

**Comment by Suburbanno** [comment]
1. Clean install of msys2
2. I uninstalled the drivers and reinstalled
3. I installed Zed as shown in the docs

The error remains

image

**Comment by lazka** [comment]
Can you confirm that a downgrade fixes things? `pacman -U "https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-zed-0.144.4-1-any.pkg.tar.zst"`

**Comment by Suburbanno** [comment]
> Can you confirm that a downgrade fixes things? `pacman -U "https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-zed-0.144.4-1-any.pkg.tar.zst"`

image

**Comment by Suburbanno** [comment]
for some reason the new update works...

I don't understand, sometimes it works, sometimes it doesn't, either way, everything is ok at the moment

image

**Pull request merged**
