### PR TITLE
zed: update to 0.144.4

### PR DESCRIPTION
**Pull request by ognevny**
draft for now as https://github.com/zed-industries/zed/issues/13575 is still here

### CODE REVIEW

**Comment by ognevny** [comment]
I've downloaded artifacts and Zed works fine! I've tested before and after nvidia drivers update
@Suburbanno can you test this build, please?

**Comment by Suburbanno** [comment]
> I've downloaded artifacts and Zed works fine! I've tested before and after nvidia drivers update @Suburbanno can you test this build, please?

Can you explain to me how I can be test using this draft? I'm a bit of a layman, I tried the conventional ways but the old version is downloaded

**Comment by ognevny** [comment]
download an artifact from CI: https://github.com/msys2/MINGW-packages/actions/runs/9979472545/artifacts/1712202054, unpack it, then run `pacman -U *.pkg.*` in the same directory where artifact unpacked

**Comment by Suburbanno** [comment]
> download an artifact from CI: https://github.com/msys2/MINGW-packages/actions/runs/9979472545/artifacts/1712202054, unpack it, then run `pacman -U *.pkg.*` in the same directory where artifact unpacked

work but with some error

image

**Comment by ognevny** [comment]
did you try to update GPU driver?

**Comment by Suburbanno** [comment]
> did you try to update GPU driver?

yep

**Comment by ognevny** [comment]
> > did you try to update GPU driver?
> 
> yep

can you share your which hardware do you use?

**Comment by Polygons1** [comment]
also can you share the current driver version and the name of the display adapter that you are using right now?

**Comment by ognevny** [comment]
me using RTX 3050Ti for laptops, driver version 560.70

**Comment by Polygons1** [comment]
for you it’s all good because the minimum version is 510.47.03​

**Comment by Suburbanno** [comment]
> > > did you try to update GPU driver?
> > 
> > 
> > yep
> 
> can you share your which hardware do you use?

Windows 11 (10.0.26241) x64
Intel Core i5 8Gen
12GB RAM
1TB SSD
Intel® UHD Graphics 620
Nvidia GeForce MX110 2GB

**Comment by Polygons1** [comment]
@Suburbanno and what about the driver version?

**Comment by Suburbanno** [comment]
> @Suburbanno and what about the driver version?

INTEL UHD 620: 31.0.101.2128
Nvidia GeForce MX110: 32.0.15.6070

**Comment by Polygons1** [comment]
can you send a screenshot of the errors, maybe they are different

**Comment by Suburbanno** [comment]
> can you send a screenshot of the errors, maybe they are different

image

**Comment by Polygons1** [comment]
what is the exit code? (echo $?)

**Comment by Suburbanno** [comment]
> what is the exit code? (echo $?)

image

**Comment by Polygons1** [comment]
what s the number?

**Comment by Suburbanno** [comment]
> what is the number?

Could you explain it to me better? The only errors I have are those in the console, Zed starts to open, but the errors remain

image

**Comment by Polygons1** [comment]
as long that Zed opens the console errors don’t matter

**Comment by Polygons1** [comment]
also to view the exit code just run echo $? (with the question mark at the end)

**Comment by Suburbanno** [comment]
> also to view the exit code just run echo $? (with the question mark at the end)

image

**Comment by ognevny** [comment]
I think that bug is not so critical atm, pushing an update

**Pull request merged**
