### PR TITLE
Add nerd fonts

### LINKED ISSUE #17796: [package request] alacritty
### Package name

alacritty

### Brief description of package

alacritty is the terminal emulator that uses OpenGL for GPU acceleration.

### URL for package's homepage

https://alacritty.org/

### Provide a basic test case to validate the package's functionality.

alacritty: open the executable file

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [x] CLANGARM64

### Are you willing to submit a PR?

Alacritty currently submitted

progress:
- [x] #17827 add alacritty

- [ ] #17833 add ttf-* and otf-* nerd fonts [for starship]

### PR DESCRIPTION
**Pull request by ognevnydemon**
provides a package group containing each font

after this PR merge I add optdepend to starship

closes #17796

### CODE REVIEW

**Comment by ognevnydemon** [comment]
I really don't understand, what's wrong?

**Comment by ognevnydemon** [comment]
Ii have idea to split all fonts into separate PKGBUILDs. any thoughts?

**Comment by ognevnydemon** [comment]
i686 starship is broken even there

**Comment by ognevnydemon** [comment]
fonts build successfully, so now remove draft

**Comment by ognevnydemon** [comment]
@lazka can we merge it?

**Comment by ognevnydemon** [comment]
added 2 missing fonts

**Comment by jeremyd2019** [comment]
This seems like rather an excessive number of PKGBUILDs

**Comment by ognevnydemon** [comment]
> This seems like rather an excessive number of PKGBUILDs

when I tried to push into one recipe It failed

**Pull request closed without merging**
