### PR TITLE
v8: try fixing build

### PR DESCRIPTION
**Pull request by naveen521kk**
try fixing https://github.com/msys2/MINGW-packages/issues/12568

### CODE REVIEW

**Comment by naveen521kk** [comment]
Now the msvs checks are patched out, but something related to pkg-config is failing...

**Comment by naveen521kk** [comment]
ok https://github.com/msys2/MINGW-packages/pull/12587/commits/39bcc3f210b9cf1d70f9d182e773f9ed0542e413 fixed it

**Comment by mmuetzel** [comment]
I seems to be building with `-Werror`. Should that flag just be patched out?

**Comment by naveen521kk** [comment]
> I seems to be building with `-Werror`. Should that flag just be patched out?

Yeah. I'll do that...

**Comment by naveen521kk** [comment]
Now this fails with
```py
  FAILED: gen/src/inspector/protocol/Forward.h gen/src/inspector/protocol/Protocol.cpp gen/src/inspector/protocol/Protocol.h gen/src/inspector/protocol/Console.cpp gen/src/inspector/protocol/Console.h gen/src/inspector/protocol/Debugger.cpp gen/src/inspector/protocol/Debugger.h gen/src/inspector/protocol/HeapProfiler.cpp gen/src/inspector/protocol/HeapProfiler.h gen/src/inspector/protocol/Profiler.cpp gen/src/inspector/protocol/Profiler.h gen/src/inspector/protocol/Runtime.cpp gen/src/inspector/protocol/Runtime.h gen/src/inspector/protocol/Schema.cpp gen/src/inspector/protocol/Schema.h gen/include/inspector/Debugger.h gen/include/inspector/Runtime.h gen/include/inspector/Schema.h 
  D:/M/msys64/mingw64/bin/python.exe ../../third_party/inspector_protocol/code_generator.py --jinja_dir ../../third_party/ --output_base gen/src/inspector --config ../../src/inspector/inspector_protocol_config.json --inspector_protocol_dir ///third_party/inspector_protocol
  Traceback (most recent call last):
    File "C:\_\mingw-w64-v8\src\v8-9.1.269.39\third_party\inspector_protocol\code_generator.py", line 702, in <module>
      main()
    File "C:\_\mingw-w64-v8\src\v8-9.1.269.39\third_party\inspector_protocol\code_generator.py", line 584, in main
      jinja_env = initialize_jinja_env(jinja_dir, config.protocol.output, config)
    File "C:\_\mingw-w64-v8\src\v8-9.1.269.39\third_party\inspector_protocol\code_generator.py", line 190, in initialize_jinja_env
      import jinja2
    File "C:/_/mingw-w64-v8/src/v8-9.1.269.39/third_party/jinja2/__init__.py", line 33, in <module>
      from jinja2.environment import Environment, Template
    File "C:/_/mingw-w64-v8/src/v8-9.1.269.39/third_party/jinja2/environment.py", line 16, in <module>
      from jinja2.defaults import BLOCK_START_STRING, \
    File "C:/_/mingw-w64-v8/src/v8-9.1.269.39/third_party/jinja2/defaults.py", line 32, in <module>
      from jinja2.tests import TESTS as DEFAULT_TESTS
  
    File "C:/_/mingw-w64-v8/src/v8-9.1.269.39/third_party/jinja2/tests.py", line 13, in <module>
  
      from collections import Mapping
  
  ImportError: cannot import name 'Mapping' from 'collections' (D:/M/msys64/mingw64/lib/python3.10/collections/__init__.py)
  
```
See https://docs.python.org/3.10/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code, should I patch that? Fixing this build is getting really complicated...

**Comment by mmuetzel** [comment]
The packaged version is already pretty old. Maybe updating to a newer version would avoid dealing with compatibility issues because of Python versions.
On the other hand, that might open a whole new can of worms...
Up to you, I guess.
(And the last option of just abandoning this package is also still on the table iiuc.)

**Comment by naveen521kk** [comment]
> The packaged version is already pretty old. Maybe updating to a newer version would avoid dealing with compatibility issues because of Python versions.
On the other hand, that might open a whole new can of worms...

I think I'll patch it for now, updating seems like a lot of work...

>  (And the last option of just abandoning this package is also still on the table iiuc.)

That also exists, but I think people from r-tool are using this package for something they support and it can make their life difficult. I'll try to fix the build but if it requires a lot of work then I'll probably abandon it.

**Comment by naveen521kk** [comment]
Ok this is done ig.

**Comment by lazka** [comment]
thanks!

**Pull request merged**
