### PR TITLE
cvise: colordiff is an MSYS2 package

### PR DESCRIPTION
**Pull request by oltolm**

### CODE REVIEW

**Comment by lazka** [comment]
What makes you think that?

**Comment by oltolm** [comment]
```
$ pacboy find colordiff
msys/colordiff 1.0.21-1 [installed]
    Diff wrapper with pretty syntax highlighting
```

BTW I just discovered that `cvise` does not work because it contains wrong paths like `D:/a/msys64/clang64/bin/clang-format.exe`. If I replace `D:/a` with `C:` it works.

**Comment by lazka** [comment]
Ah, right, I mixed it up, thanks. Needs a pkgrel bump

**Comment by oltolm** [comment]
I bumped the `pkgrel`. The paths are now correct for some reason.

**Pull request merged**
