### PR TITLE
gss: add missing make dependency

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by lazka** [comment]
bump pkgrel

**Comment by neheb** [comment]
why? this is just a make dependency?

**Comment by lazka** [comment]
What does adding this makedep change in regards to the final package?

no pkgrel bump, means no rebuild. If you don't need a rebuild then I wonder what this does.

**Comment by neheb** [comment]
added.

**Pull request merged**
