### PR TITLE
emacs: depend on texinfo for proper info directory update upon install

### PR DESCRIPTION
**Pull request by oscarfv**
This completes the fix for issue #631

### CODE REVIEW

**Comment by oscarfv** [comment]
Looks like the ucrt64 build timed out. Forcing a new check run...

**Comment by oscarfv** [comment]
@cyrilarnould : do you plan to submit a PR for the workaround mentioned on https://debbugs.gnu.org/cgi/bugreport.cgi?bug=70889#25 ?

Otherwise I will.

Thanks to you and @lazka for analyzing the faulty gcc 14.1 build.

**Comment by cyrilarnould** [comment]
I'm currently checking whether the `PKGBUILD` recipe works on my machine with the workaround :)

But feel free to integrate it into your PR, my suggestion would have been

```
diff --git a/mingw-w64-emacs/PKGBUILD b/mingw-w64-emacs/PKGBUILD
index 469d137ca..7c088c6bc 100644
--- a/mingw-w64-emacs/PKGBUILD
+++ b/mingw-w64-emacs/PKGBUILD
@@ -83,6 +83,9 @@ build() {
   CFLAGS=${CFLAGS//"-Wp,-D_FORTIFY_SOURCE=2"}
   # -foptimize-sibling-calls breaks native compilation (GCC 13.1)
   CFLAGS+=" -fno-optimize-sibling-calls"
+  # configure script can not deal with the warnings that were turned
+  # into errors in GCC 14
+  CFLAGS+=" -Wno-error=implicit-function-declaration"

   ../${_realname}-${pkgver}/configure \
     --prefix="${MINGW_PREFIX}" \

```

**Comment by oscarfv** [comment]
Okay, PR updated, thanks @cyrilarnould .

The occasional CI build failure seems to be a timing issue either on emacs' build system or in the nativecomp machinery.

**Comment by cyrilarnould** [comment]
Upstream has fixed the issue `-Wno-error=implicit-function-declaration` with a different patch: 

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=5216903ae6c3f91ebefb1152af40753f723cbc39

Maybe using this might be more appropriate?

In the meantime, they've also integrated the `-fno-optimize-sibling-calls`

**Comment by lazka** [comment]
thanks, I've referenced the commits in 0d77e7c68b6698f40c45f88399eed1caaf59baf3, so we can drop the workarounds maybe on the next upstream release.

**Pull request merged**
