### PR TITLE
gnustep-gui: Add patches for msys2 fixes

### PR DESCRIPTION
**Pull request by johnathan-becker**
This MR adds some of the latest patches to fix issues with gnustep-gui on MSYS2 platforms.

### CODE REVIEW

**Comment by johnathan-becker** [comment]
I am not sure what is happening here. I have tried clean isolated environments locally and everything works fine. I cannot reproduce these pipeline failures. Is there some sort of security hardening in these pipelines that I wouldn't have locally?

**Comment by qmfrederik** [comment]
@johnathan-becker I can reproduce this by enabling the staging repository.  My guess it that something changed in staging (perhaps libxml2?) which breaks plutil.  Perhaps a simple rebuild of libs-base is enough.  You can try bumping the revision number of libs-base in this pull request and see if that fixes CI.

**Comment by qmfrederik** [comment]
Here are the steps to enable staging if that's what you want to do:

https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml#L73-L82

**Comment by johnathan-becker** [comment]
@qmfrederik that did seem to fix the issue. I will fix the MR for final review.

**Comment by johnathan-becker** [comment]
Ready for final review

**Pull request merged**
