### PR TITLE
qtwebkit: update dependencies

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
It fails on MinGW64 with messages like
`D:/a/_temp/msys/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find *a library*: Too many open files`
and on MinGW32 with a message indicating a mlformed archive
`D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../lib/libWTF.a: error adding symbols: malformed archive`
Any Idea?

**Comment by MehdiChinoune** [comment]
It looks like It is a binutils related problem, as It happened before #4317

**Comment by lazka** [comment]
We should try backporting https://sourceware.org/pipermail/binutils/2021-July/117264.html

**Comment by lazka** [comment]
I've added a comment here: https://sourceware.org/bugzilla/show_bug.cgi?id=24723

**Pull request merged**
