### PR TITLE
fd: new package

### PR DESCRIPTION
**Pull request by Freed-Wu**
Refer archlinux's PKGBUILD.

### CODE REVIEW

**Comment by Biswa96** [comment]
Please follow this [template PKGBUILD][1] file and remove those unnecessary variables and comments.

[1]: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-PKGBUILD-templates/PKGBUILD.cargo-tarball.sh

**Comment by Biswa96** [comment]
Did you test the package with lto enabled? I am not sure if lto should be enabled in mingw packages.

**Comment by Freed-Wu** [comment]
<https://github.com/sharkdp/fd/blob/master/Cargo.toml#L78>

```
[profile.release]
lto = true
```

Did you mean it?

**Comment by Biswa96** [comment]
I mean adding this command `export CFLAGS+=" -ffat-lto-objects"`.

**Comment by Freed-Wu** [comment]
Now lto has been removed

**Comment by Freed-Wu** [comment]
Now it can work.

**Comment by Freed-Wu** [comment]
Are there any problem about this package?

**Pull request merged**
