### PR TITLE
ncurses 6.3 - update to l newer version, update PGP key, and use sepa…

### PR DESCRIPTION
**Pull request by JPeterMugaas**
…rate paths for all builds.

### CODE REVIEW

**Comment by lazka** [comment]
The clang builds lost their pkg-config files with this.

**Comment by JPeterMugaas** [comment]
I don't see the problem here because those *.pc files are built when I do "MINGW_ARCH=CLANG64 makepkg-mingw -f" here.  Am I missing something?

**Comment by Biswa96** [comment]
Try to add `--enable-pc-files` option with configure command.

**Comment by lazka** [comment]
That somehow seems to have fixed the problem. Thanks!

**Comment by naveen521kk** [comment]
Hmm, I think this made our python fail to build the `curses` module https://github.com/msys2-contrib/cpython-mingw/runs/4492454357?check_suite_focus=true#step:5:1428.

**Pull request merged**
