### PR TITLE
spdlog: Update to 1.8.5

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
Hm, in my case, the `CI-Build` step is frozen on state:

``` txt
  ==> Extracting sources...
    -> Extracting spdlog-1.8.5.tar.gz with bsdtar
  ==> Starting build()...
  -- The CXX compiler identification is GNU 10.2.0
  -- Detecting CXX compiler ABI info
```

But it only takes a few minutes to build the package on my local machine.

**Comment by lazka** [comment]
maybe the cygwin update in staging..

**Comment by lazka** [comment]
We need to fix https://github.com/msys2/MINGW-packages/issues/7890

**Comment by podsvirov** [comment]
@lazka, thanks for fixing.

**Pull request merged**
