### PR TITLE
CI: read mingw_arch array to decide which builds the PKGBUILD supports

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
Blocked on #8081

**Comment by Biswa96** [comment]
The new keyword should be in template pkgbuild and/or in docs. Though I have some mixed feeling about not using [standard pkgbuild keywords][1].

[1]: https://wiki.archlinux.org/index.php/Arch_package_guidelines

**Comment by lazka** [comment]
yeah, once it works. Related: https://github.com/msys2/MSYS2-packages/pull/2363

**Comment by Biswa96** [comment]
Will `arch=('x86_64')` work instead of `arch=('any')`?

**Comment by lazka** [comment]
It would limit the package to 64bit msys envs, but that doesn't change anything since that's all we have anyway right now.

**Pull request merged**
