### PR TITLE
angleproject: version bump

### PR DESCRIPTION
**Pull request by raedrizqie**
- update the version to trigger CI rebuild
- rebase some patches

### CODE REVIEW

**Comment by Biswa96** [comment]
The last digit in pkgver may not increment with newer commit. We need some kind of integer which is incremented with every commit. For example, see `git rev-list --count HEAD` part in mingw-w64-headers-git package.

**Comment by Biswa96** [comment]
Now according to vercmp, this is a downgrade, right?

```
$ vercmp "2.1.2c60b86e" "2.1.r20194.6c41793f"
1
```

**Comment by raedrizqie** [comment]
hmm.. so it's better without rev-list then?

**Comment by Biswa96** [comment]
The `.2c60b86e` and `.6c41793f` parts are coming from git commit hash which can be random. It's just coincident that here .6 > .2 but it may not be true all the time.

**Comment by jeremyd2019** [comment]
also version components that start with letters sort less than numbers, so the fact that it's `.r999` is less than `.2xxx`.

**Comment by raedrizqie** [comment]
so how do fix this? remove the package and add it back?

**Comment by jeremyd2019** [comment]
epoch, or just live with it being a downgrade

**Comment by raedrizqie** [comment]
ok.. so it will be downgrade for this version only.. and its ok.. but will CI rebuild the package?

**Comment by jeremyd2019** [comment]
I think so.  @lazka?

**Comment by lazka** [comment]
I wont build older versions, but I can remove the package temporarily if wanted. I don't have anything against epoch.

**Comment by raedrizqie** [comment]
ok.. please remove this temporarily.. thank you.. sorry for the mess

**Pull request merged**
