### PR TITLE
xmake: 2.5.7

### PR DESCRIPTION
**Pull request by waruqi**

### CODE REVIEW

**Comment by Biswa96** [comment]
If you see the [diff] section in CI log here you can see some files are removed after new version. Is that alright?

**Comment by waruqi** [comment]
> If you see the [diff] section in CI log here you can see some files are removed after new version. Is that alright?

what diif? I do not found it.

**Comment by Biswa96** [comment]
See this https://github.com/msys2/MINGW-packages/pull/9491/checks#step:9:660

**Comment by waruqi** [comment]
> See this https://github.com/msys2/MINGW-packages/pull/9491/checks#step:9:660

yeah, I removed them.

**Pull request merged**
