### PR TITLE
Update path.py to version 12.5.0

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by Biswa96** [comment]
upgrade or downgrade? 13.2.0 -> 12.5.0 ??

**Comment by danyeaw** [comment]
@Biswa96 Whoops, you found a hole in my automation! I'm trying to get all of these Python packages up to date 👍

**Comment by Biswa96** [comment]
You could just force push a commit with new version. Also https://xkcd.com/1319/

**Comment by danyeaw** [comment]
@Biswa96 Yup, that is a good xkcd 😄. In this case creating the script took about 1 hour and I have created 50 PRs using it, so I think the time was well spent. Manually determining which Python packages need to be updated for the 300+ packages is not something I like to spend my time doing.

https://github.com/danyeaw/mingw-package-updater

**Pull request closed without merging**
