### PR TITLE
Fix libass.a link against  libfribidi.dll.a

### PR DESCRIPTION
**Pull request by shithappens2016**
#8817
build static & shared separately should fix it.
just like #8804

### CODE REVIEW

**Comment by Biswa96** [comment]
Bump the pkgrel.

**Comment by Biswa96** [comment]
If you see the CI build log there is no file change.

**Comment by shithappens2016** [comment]
@Biswa96 

clang32 missing dependencies.
i don't know what to do.
should i avoid clang32 from buiding libass.
still, i don't how to do that.
please help

```Shell
  ==> Checking runtime dependencies...
  ==> Installing missing dependencies...
  error: target not found: mingw-w64-clang-i686-fribidi
  error: target not found: mingw-w64-clang-i686-fontconfig
  error: target not found: mingw-w64-clang-i686-freetype
  error: target not found: mingw-w64-clang-i686-harfbuzz
  ==> ERROR: 'pacman' failed to install missing dependencies.
  ==> Missing dependencies:
    -> mingw-w64-clang-i686-fribidi
    -> mingw-w64-clang-i686-fontconfig
    -> mingw-w64-clang-i686-freetype
    -> mingw-w64-clang-i686-harfbuzz
  ==> Checking buildtime dependencies...
  ==> Installing missing dependencies...
  error: target not found: mingw-w64-clang-i686-nasm
  ==> ERROR: 'pacman' failed to install missing dependencies.
  ==> Missing dependencies:
    -> mingw-w64-clang-i686-nasm
  ==> ERROR: Could not resolve all dependencies.
  
  [MSYS2 CI] FAILURE: mingw-w64-libass: Building binary failed.
  
  Error: Process completed with exit code 1.
```

**Comment by Biswa96** [comment]
clang32 is not required anywhere. It's just for someone with some weird but valid cause 😏

**Comment by shithappens2016** [comment]
yes your are right
nothing changed
```Shell
nm libass.a |grep fri
                 U __imp_fribidi_get_bidi_types
                 U __imp_fribidi_get_bracket_types
                 U __imp_fribidi_get_joining_types
                 U __imp_fribidi_get_par_embedding_levels_ex
                 U __imp_fribidi_join_arabic
                 U __imp_fribidi_reorder_line
                 U __imp_fribidi_shape
```

**Comment by shithappens2016** [comment]
@Biswa96
fixed
```shelll
 nm libass.a |grep fri
                 U fribidi_get_bidi_types
                 U fribidi_get_bracket_types
                 U fribidi_get_joining_types
                 U fribidi_get_par_embedding_levels_ex
                 U fribidi_join_arabic
                 U fribidi_reorder_line
                 U fribidi_shape
```

**Pull request closed without merging**
