### PR TITLE
FLAC: update to 1.3.4

### PR DESCRIPTION
**Pull request by drfiemost**

### CODE REVIEW

**Comment by lazka** [comment]
I already tried, and the static build is broken somehow.

**Comment by Biswa96** [comment]
Do you mean at runtime or the build is broken? I've tried with cmake and it builds fine. But need to rebuild all the depenencies sue to DLL change.

**Comment by lazka** [comment]
The build was broken (shared worked, static complained about libssp things)

Maybe I missed something. cmake + name change is fine too.

**Comment by drfiemost** [comment]
I don't see any useful error message in the log...
The fun thing is that the changelog says "build system: Fixes for MinGW and MSVC"
So, would it be better to switch to cmake?

**Comment by Biswa96** [comment]
> So, would it be better to switch to cmake?

Yes, cmake is preferred over autotools because cmake is faster in mingw environment. Also cmake is easier to use and tinker with but opinion may vary 😊 If you want I can try to send the change in a pull request.

**Pull request closed without merging**
