### PR TITLE
libinih: fix version mismatch

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by mmuetzel** [comment]
Is it really necessary to cherry-pick this change? Afaict, all compilers distributed by MSYS2 already default to C++11 or newer.

**Comment by Biswa96** [comment]
This fixes the version number of the library.

**Comment by kmilos** [comment]
> This fixes the version number of the library.

This - the pkg-cofig file currently has `Version: 56`.

**Comment by mmuetzel** [comment]
Ah, I see. I missed that part. 👍

**Comment by kmilos** [comment]
Btw, let me add the ref to the Cygwin package as well in a sec...

**Comment by kmilos** [comment]
> Please add the archlinux also https://archlinux.org/packages/core/x86_64/libinih/

No need? The package name is the same for Arch and MSYS2 (on purpose), so they're already linked, no?

**Comment by Biswa96** [comment]
According to the _developer_, if it is absent "msys2-web will try to guess based on the naming". So, we could help poor msys2-web from that guesswork.

**Pull request merged**
