### PR TITLE
python-pytest-datafiles: add new package

### PR DESCRIPTION
**Pull request by marcelotduarte**
I will use it to implement check() in python-cx-freeze.

### CODE REVIEW

**Comment by Biswa96** [comment]
Are 32 bit packages required?

**Comment by marcelotduarte** [comment]
I copied mingw_arch from other pytest plugins. But I think only mingw32 will be needed because I saw that cedk will need it for now in cx_Freeze. So if you want, I can remove clang32.

**Comment by marcelotduarte** [comment]
By the way, I was planning to update pytest and its plugins, so I can disable clang32 for everyone too?

**Comment by Biswa96** [comment]
> so I can disable clang32 for everyone too?

If there is not reverse dependencies, yes absolutely.

**Comment by marcelotduarte** [comment]
Updated. Can you merge?

**Pull request merged**
