### PR TITLE
med: fix DLL install locations, depend on libgfortran

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
@3rav

**Comment by Biswa96** [comment]
Maybe?

```
ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
```

**Comment by lazka** [comment]
Where are they defined?

**Comment by Biswa96** [comment]
Doc: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by lazka** [comment]
med doesn't use this module, and I don't feel confident enough changing more :/

**Pull request merged**
