### PR TITLE
[new-package] Qt6 6.0.2

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by Biswa96** [comment]
Wasn't there a discussion about making modular Qt packages?

**Comment by MehdiChinoune** [comment]
> Wasn't there a discussion about making modular Qt packages?

Yes There was.
I didn't any efficient way to build all packages within the same PKGBUILD file.

I tried two ways:

1st - Build each package from its own archive (submodule files). but the problem is that each package depend on other so build qt-svg for example qt-base must be available through pacman. because it needs some files from qt-base only available after installation.

2nd - Build all packages from the single file, then package each component separately.
It builds, packages but fails to install them because there is a conflict between them which I can't figure out how to resolve.

I am open to any suggestion to resolve these issues.

**Comment by Biswa96** [comment]
Using submodules tarball is a superior choice. There are some mingw-w64-Qt6 packages in AUR. I would like to test those.

**Comment by MehdiChinoune** [comment]
> Using submodules tarball is a superior choice. There are some mingw-w64-Qt6 packages in AUR. I would like to test those.

Well, I hope that's not a blocker to this pr. You push your changex when you succeed.

**Comment by Biswa96** [comment]
Can this option be added `-DFEATURE_system_harfbuzz=ON`? Otherwise the build uses bundled harfbuzz.

**Comment by MehdiChinoune** [comment]
> Can this option be added `-DFEATURE_system_harfbuzz=ON`? Otherwise the build uses bundled harfbuzz.

No, cmake can't find it.

It's "-DQT_FEATURE_system_harfbuzz".

**Comment by MehdiChinoune** [comment]
superseded by #8199

**Pull request closed without merging**
