### PR TITLE
rust: fix build on clang32

### PR DESCRIPTION
**Pull request by jeremyd2019**
For #9091.  The patch to psm was accepted upstream and released as 0.1.14.

This doesn't actually fix it, but it gets much further, to stage0 rustbook.
```
Building stage0 tool rustbook (i686-pc-windows-gnu)
  running: "\\\\?\\C:\\_\\mingw-w64-rust\\src\\i686\\build\\i686-pc-windows-gnu\\stage0\\bin\\cargo.exe" "build" "--target" "i686-pc-windows-gnu" "-Zbinary-dep-depinfo" "-j" "2" "--release" "--frozen" "--color" "always" "--manifest-path" "C:\\_\\mingw-w64-rust\\src\\rustc-1.53.0-src\\src/tools/rustbook\\Cargo.toml" "--message-format" "json-render-diagnostics"
```
...
```
  error: failed to run custom build command for `html5ever v0.25.1`
  
  Caused by:
    process didn't exit successfully: `C:\_\mingw-w64-rust\src\i686\build\i686-pc-windows-gnu\stage0-bootstrap-tools\release\build\html5ever-7b859b6107fbb733\build-script-build` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
    --- stdout
    cargo:rerun-if-changed=C:\_\mingw-w64-rust\src\rustc-1.53.0-src\vendor\html5ever\src/tree_builder/rules.rs
  
    --- stderr
    fatal runtime error: failed to initiate panic, error 5
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  command did not execute successfully: "\\\\?\\C:\\_\\mingw-w64-rust\\src\\i686\\build\\i686-pc-windows-gnu\\stage0\\bin\\cargo.exe" "build" "--target" "i686-pc-windows-gnu" "-Zbinary-dep-depinfo" "-j" "2" "--release" "--frozen" "--color" "always" "--manifest-path" "C:\\_\\mingw-w64-rust\\src\\rustc-1.53.0-src\\src/tools/rustbook\\Cargo.toml" "--message-format" "json-render-diagnostics"
  expected success, got: exit code: 101
  Traceback (most recent call last):
    File "../rustc-1.53.0-src/x.py", line 27, in <module>
      bootstrap.main()
    File "C:/_/mingw-w64-rust/src/rustc-1.53.0-src/src/bootstrap/bootstrap.py", line 1189, in main
      bootstrap(help_triggered)
    File "C:/_/mingw-w64-rust/src/rustc-1.53.0-src/src/bootstrap/bootstrap.py", line 1175, in bootstrap
      run(args, env=env, verbose=build.verbose)
    File "C:/_/mingw-w64-rust/src/rustc-1.53.0-src/src/bootstrap/bootstrap.py", line 145, in run
      raise RuntimeError(err)
  RuntimeError: failed to run: C:/_/mingw-w64-rust/src/i686/build/bootstrap/debug/bootstrap install --stage 2 --verbose
```

### CODE REVIEW

**Comment by revelator** [comment]
seeing the same error here.

**Comment by jeremyd2019** [comment]
@mati865 any ideas?

**Comment by mati865** [comment]
My hack breaks unwinding but I have no clue why it would panic. Try replacing libs in the hack directory with ones from mingw32 subsystem.

**Comment by jeremyd2019** [comment]
This seems to have failed sooner with `STATUS_DLL_NOT_FOUND` (as opposed to `STATUS_STACK_BUFFER_OVERRUN`)

**Comment by mati865** [comment]
Ah, that would also require having `/mingw32/bin/libgcc_s_dw2-1.dll` somewhere in the path.

**Comment by jeremyd2019** [comment]
gets even further, but still gets a `STATUS_STACK_BUFFER_OVERRUN`:
```
   Compiling cargo-miri v0.1.0 (T:\mingw-w64-rust\src\rustc-1.53.0-src\src\tools\miri\cargo-miri)
error: failed to run custom build command for `cargo-miri v0.1.0 (T:\mingw-w64-rust\src\rustc-1.53.0-src\src\tools\miri\cargo-miri)`

Caused by:
  process didn't exit successfully: `T:\mingw-w64-rust\src\i686\build\i686-pc-windows-gnu\stage2-tools\release\build\cargo-miri-ccf7610928535c96\build-script-build` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'Unable to generate vergen keys!: could not find repository from 'T:\mingw-w64-rust\src\rustc-1.53.0-src\src\tools\miri\cargo-miri'; class=Repository (6); code=NotFound (-3)', src\tools\miri\cargo-miri\build.rs:10:24
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  fatal runtime error: failed to initiate panic, error 5
command did not execute successfully: "\\\\?\\C:\\msys64\\home\\adminuser\\MINGW-packages\\mingw-w64-rust\\src\\i686\\build\\i686-pc-windows-gnu\\stage0\\bin\\cargo.exe" "build" "--target" "i686-pc-windows-gnu" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--frozen" "--manifest-path" "T:\\mingw-w64-rust\\src\\rustc-1.53.0-src\\src/tools/miri/cargo-miri\\Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
```

**Comment by jeremyd2019** [comment]
Starting a build with copying files from mingw32, including having a copy of libgcc*.dll in /clang32/bin/, will see what that does.

**Comment by jeremyd2019** [comment]
Pretty much the same error:
```
error: failed to run custom build command for `html5ever v0.25.1`

Caused by:
  process didn't exit successfully: `T:\mingw-w64-rust\src\i686\build\i686-pc-windows-gnu\stage0-bootstrap-tools\release\build\html5ever-7b859b6107fbb733\build-script-build` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
  --- stdout
  cargo:rerun-if-changed=T:\mingw-w64-rust\src\rustc-1.53.0-src\vendor\html5ever\src/tree_builder/rules.rs
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "\\\\?\\C:\\msys64\\home\\adminuser\\MINGW-packages\\mingw-w64-rust\\src\\i686\\build\\i686-pc-windows-gnu\\stage0\\bin\\cargo.exe" "build" "--target" "i686-pc-windows-gnu" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--frozen" "--manifest-path" "T:\\mingw-w64-rust\\src\\rustc-1.53.0-src\\src/tools/rustbook\\Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
```

**Comment by jeremyd2019** [comment]
This appears to actually be a `__fastfail` (https://docs.microsoft.com/en-us/cpp/intrinsics/fastfail?view=msvc-160), in `build-script-build.exe`.  I'm going to try to trap this in gdb, as windbg was less than helpful (no symbols).  But windbg did say something along the lines of "fast fail zeroed stack" if that's any hint.

**Comment by mati865** [comment]
Yup, it's fastfail which means panic somewhere. Missing any sort of backtrace is the problem.
Maybe it'd be easier to cross compile bootstrap compiler from clang64.

**Comment by jeremyd2019** [comment]
A backtrace I can get, it's symbols that were the issue 😉

**Comment by jeremyd2019** [comment]
Incoming!

<details>
<summary>GDB backtrace</summary>

```
#0  0x009aa33f in std::sys::windows::abort_internal () at library\std\src\sys\windows/mod.rs:261
#1  std::sys_common::util::abort () at library\std\src\sys_common/util.rs:19
#2  0x009abf98 in std::panicking::rust_panic () at library\std\src/panicking.rs:642
#3  0x009abe0f in std::panicking::rust_panic_with_hook () at library\std\src/panicking.rs:610
#4  0x0093cbb4 in std::panicking::begin_panic::{{closure}}<&str> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\std\src/panicking.rs:520
#5  0x0093c94d in std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\std\src\sys_common/backtrace.rs:141
#6  0x0093cb88 in std::panicking::begin_panic<&str> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\std\src/panicking.rs:519
#7  0x0095a91e in proc_macro::bridge::client::{{impl}}::with::{{closure}}<proc_macro::bridge::client::Span,closure-0>
    () at library\proc_macro\src\bridge/client.rs:331
#8  proc_macro::bridge::client::{{impl}}::with::{{closure}}::{{closure}}<proc_macro::bridge::client::Span,closure-0>
    () at library\proc_macro\src\bridge/client.rs:293
#9  proc_macro::bridge::scoped_cell::ScopedCell::replace<proc_macro::bridge::client::BridgeStateL,proc_macro::bridge::client::Span,closure-0> () at library\proc_macro\src\bridge/scoped_cell.rs:75
#10 proc_macro::bridge::client::{{impl}}::with::{{closure}}<proc_macro::bridge::client::Span,closure-0> ()
    at library\proc_macro\src\bridge/client.rs:291
#11 std::thread::local::LocalKey::try_with<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>,closure-0,proc_macro::bridge::client::Span> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\std\src\thread/local.rs:272
#12 std::thread::local::LocalKey::with<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>,closure-0,proc_macro::bridge::client::Span> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\std\src\thread/local.rs:248
#13 proc_macro::bridge::client::BridgeState::with<proc_macro::bridge::client::Span,closure-0> ()
    at library\proc_macro\src\bridge/client.rs:290
#14 proc_macro::bridge::Bridge::with<proc_macro::bridge::client::Span,closure-0> ()
    at library\proc_macro\src\bridge/client.rs:329
#15 proc_macro::bridge::client::Span::call_site () at library\proc_macro\src\bridge/client.rs:237
#16 proc_macro::Span::call_site () at library\proc_macro\src\lib.rs:311
#17 0x0092b35b in core::ops::function::FnOnce::call_once ()
#18 0x00938b99 in std::panicking::try::do_call ()
#19 0x00939e6d in __rust_try ()
#20 0x00938a4e in std::panicking::try ()
#21 0x00929df6 in std::panic::catch_unwind ()
#22 0x0092813b in proc_macro2::detection::initialize ()
#23 0x0092b379 in core::ops::function::FnOnce::call_once ()
#24 0x00929dd4 in std::sync::once::Once::call_once::{{closure}} ()
#25 0x009a7955 in std::sync::once::Once::call_inner () at library\std\src\sync/once.rs:418
#26 0x00929d5f in std::sync::once::Once::call_once ()
#27 0x00928045 in proc_macro2::detection::inside_proc_macro ()
#28 0x00922cba in <proc_macro2::imp::TokenStream as core::str::traits::FromStr>::from_str ()
#29 0x00921fd4 in core::str::<impl str>::parse ()
#30 0x00930ab6 in <proc_macro2::TokenStream as core::str::traits::FromStr>::from_str ()
#31 0x00891574 in syn::parse::Parser::parse_str ()
#32 0x0090ab14 in syn::parse_str ()
#33 0x0090aee3 in syn::parse_file ()
#34 0x006c6b52 in build_script_build::match_token::expand ()
#35 0x006cfbe9 in build_script_build::main::{{closure}} ()
#36 0x0075c4ab in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#37 0x0075d2cb in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} ()
#38 0x0075c3db in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once ()
#39 0x006bd4bd in std::panicking::try::do_call ()
#40 0x006bf2ad in __rust_try ()
#41 0x006bd430 in std::panicking::try ()
#42 0x0075c89b in std::panic::catch_unwind ()
#43 0x0075d16e in std::thread::Builder::spawn_unchecked::{{closure}} ()
#44 0x0075da01 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#45 0x009b8495 in alloc::boxed::{{impl}}::call_once<(),FnOnce<()>,alloc::alloc::Global> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\alloc\src/boxed.rs:1546
#46 alloc::boxed::{{impl}}::call_once<(),alloc::boxed::Box<FnOnce<()>, alloc::alloc::Global>,alloc::alloc::Global> ()
    at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\library\alloc\src/boxed.rs:1546
#47 std::sys::windows::thread::{{impl}}::new::thread_start () at library\std\src\sys\windows/thread.rs:56
#48 0x7742fa29 in KERNEL32!BaseThreadInitThunk () from C:\Windows\SysWOW64\kernel32.dll
#49 0x77807a7e in ntdll!RtlGetAppContainerNamedObjectPath () from C:\Windows\SysWOW64\ntdll.dll
#50 0x77807a4e in ntdll!RtlGetAppContainerNamedObjectPath () from C:\Windows\SysWOW64\ntdll.dll
#51 0x00000000 in ?? ()
```
</details>

**Comment by jeremyd2019** [comment]
I actually got 2 gdb's pop up, one for markup5ever build-script-build.exe, and both have that same line in their backtraces.

**Comment by jeremyd2019** [comment]
@mati865 does that backtrace give you any ideas?

**Comment by mati865** [comment]
Unfortunately no, I have no experience debugging proc macros and don't have any clue what could be wrong here.

**Comment by jeremyd2019** [comment]
Hah, my only experience with rust is cursing it when I have to build it, so... Should I try to find proc_macros upstream and ask there?

**Comment by mati865** [comment]
proc_macros are part of the Rust itself, they are special libraries that allow altering code just before it's built. You can see very simple example here: https://blog.turbo.fish/proc-macro-simple-derive/
I'll try to play with the build on my own but it could even be a miscomppilation.

**Comment by raedrizqie** [comment]
> Hah, my only experience with rust is cursing it when I have to build it, so... Should I try to find proc_macros upstream and ask there?

hi @jeremyd2019 , what is the status of this fix?

**Comment by mati865** [comment]
Unwinding is broken so the compiler cannot bootstrap itself.

**Comment by raedrizqie** [comment]
> Unwinding is broken so the compiler cannot bootstrap itself.

ah.. ok thx

**Comment by jeremyd2019** [comment]
The fix from this PR (updating psm) seems to be upstream now (at least the last update of rust failed on clang32 the same way it's failing here, rather than earlier on psm as it was before).

**Comment by jeremyd2019** [comment]
@raedrizqie see #9091 - that has more debugging details

**Comment by raedrizqie** [comment]
> @raedrizqie see #9091 - that has more debugging details

ok

**Pull request closed without merging**
