### PR TITLE
ideviceinstaller: new package

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
ucrt build is failing with missing dependencies. I don't know what needs to be done for this.

  ==> Missing dependencies:
    -> mingw-w64-ucrt-x86_64-libplist
    -> mingw-w64-ucrt-x86_64-libimobiledevice
    -> mingw-w64-ucrt-x86_64-libzip

**Comment by Biswa96** [comment]
Would you like to to wait some time for those to be built? Stare at this https://packages.msys2.org/queue 👀

**Comment by nisargjhaveri** [comment]
That's a long list! 😮
But sure, we can wait. 

Also, side topic, I am planning to add -git versions of libplist, libusbmuxd, libimobiledevice, which depends on each other in that order. Do I have to create separate PRs and wait for each one to get merged beforehand, or is there a way I can prepare the entire chain together?

**Comment by Biswa96** [comment]
> That's a long list

Actually not so long. Hover upon your packages you can see the hints.

> add -git versions of libplist, libusbmuxd, libimobiledevice

Git packages go in this repository https://github.com/msys2/MINGW-packages-dev and those will not be built/served to users, just for testing.

**Comment by lazka** [comment]
ucrt failing is OK for now.

**Comment by Biswa96** [comment]
Interesting! But the dependencies are built with UCRT in previous pull requests.

**Comment by lazka** [comment]
ah, I missed that! I assumed they aren't built with ucrt. oops

**Comment by lazka** [comment]
re-ran CI now that the other packages are in staging, and it worked luckily.

**Pull request merged**
