### PR TITLE
libvips: Update to 8.9.2

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by kmilos** [comment]
No idea what was changed since 8.9.1 to make introspect fail again...

**Comment by lazka** [comment]
> No idea what was changed since 8.9.1 to make introspect fail again...

I'll have a look when I find some time

**Comment by lazka** [comment]
mingw-w64-matio needs a rebuild because mingw-w64-hdf5 had an ABI break (some symbols got removed).

@kmilos Try increasing pkgrel of mingw-w64-matio in this PR.

**Comment by Alexpux** [comment]
Everything already done and will be in repo some later

**Pull request closed without merging**
