### PR TITLE
clang: package function tweaks

### PR DESCRIPTION
**Pull request by jeremyd2019**
Fix depends is not an array in libc++/libc++abi

Fix name libcxx -> libc++.

Use for loop to generate package function wrappers, suggested in https://github.com/msys2/MSYS2-packages/pull/2304#issuecomment-765891946

### CODE REVIEW

**Comment by Biswa96** [comment]
Don't they need some `conflicts` and `replaces` variable?

**Comment by jeremyd2019** [comment]
The packages themselves are the same names, the only names that changed are the internal function names that are then wrapped, either by the explicit wrapper functions or now by functions created by eval in the for loop.

**Comment by lazka** [comment]
uh, good point. "MINGW_INSTALLS=mingw64 makepkg-mingw --printsrcinfo" fails to pick up depends on both cases

**Comment by lazka** [comment]
ok, even more hacky, but seems to handle all cases:

```bash
for _name in "${pkgname[@]}"; do
  _short="package_${_name#${MINGW_PACKAGE_PREFIX}-}"
  _func="$(declare -f $_short)"
  eval "${_func/$_short/package_$_name}"
done
```

**Comment by lazka** [comment]
lgtm

**Comment by jeremyd2019** [comment]
Superseded by #7878

**Pull request closed without merging**
