### PR TITLE
proj: update to 8.1.1

### PR DESCRIPTION
**Pull request by Adsun701**
This updates proj to 8.1.1.

### CODE REVIEW

**Comment by Biswa96** [comment]
The DLL name has changed. Dependent packages need to be rebuild/updated.

**Comment by lazka** [comment]
```
mingw-w64-libspatialite
mingw-w64-libgeotiff
mingw-w64-postgis
mingw-w64-spatialite-gui
mingw-w64-gdal
```

**Comment by Adsun701** [comment]
Is there a problem with this pull request that prevents it from being merged? Would you please let me know so I could fix this? Thanks.

**Comment by lazka** [comment]
postgis failed to build. We need to figure out why

**Pull request merged**
