### PR TITLE
python-pygit2: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
Hm... I have some troubles with `libgit2` from `staging` repo. Installed the version while `CI-build` is `1.2.0` but should be `1.3.0`. For other `MSYSTEM`s all good...

Cc: @lazka

**Comment by podsvirov** [comment]
Again the same...

**Comment by lazka** [comment]
weird

**Comment by lazka** [comment]
fixed in master

**Comment by podsvirov** [comment]
Thanks! But `python-cached-property` missing for `UCRT64` and `CLANG64` currently.

**Comment by Biswa96** [comment]
It's already there https://packages.msys2.org/base/mingw-w64-python-cached-property

**Comment by podsvirov** [comment]
I see, but `CI` not. Perhaps we need to wait until all the mirrors are updated and restart the check.

**Comment by podsvirov** [comment]
Hm... Something wrong with `UCRT64` only...

**Comment by podsvirov** [comment]
After a short wait, the next check was has passed! Looks like we ready to merge.

**Pull request merged**
