### PR TITLE
starship: update to 1.16.0

### PR DESCRIPTION
**Pull request by ognevnydemon**
don't know why, but it fails on i686. should we disable it?

upd.: i686 is disabled, but it will be fixed soon. see further conversation for details

### CODE REVIEW

**Comment by ognevnydemon** [comment]
> don't know why, but it fails on i686. should we disable it?

@jeremyd2019 any ideas?

**Comment by jeremyd2019** [comment]
Guess: sha1-asm crate isn't properly mangling asm names for x86 windows? https://github.com/RustCrypto/asm-hashes/blob/master/sha1/src/x86.S  should have leading underscore like the apple case I think.  I might find some time to hack at it tomorrow.

**Comment by jeremyd2019** [comment]
@mati865 are you familiar with sha1-asm crate?  I get the impression it isn't really expected to be used on Windows, as I see no signs of MSVC support.  While it looks like it should be possible for it to work for -windows-gnu, maybe there's something else going on that is causing it to be used here on Windows instead of something more Windows-specific.

**Comment by mati865** [comment]
I have never used it myself but looks like they could figure out i686 CI so they only support amd64 https://github.com/RustCrypto/asm-hashes/pull/19 ...
The only immediate solution I can think of is building with `--no-default-features` on i686 which will likely render git support as not working because of Cygwin paths.
For future releases I think we need to make gitoxide buildable on i686, it avoids `sha1` on msvc and should do the same for i686-windows-gnu: https://github.com/Byron/gitoxide/blob/146c1498c7de4c8c00b2d1df52795b8338635697/gix-features/Cargo.toml#L155

**Comment by ognevnydemon** [comment]
so our task for now is build gitoxide package?

**Comment by jeremyd2019** [comment]
> @mati865 are you familiar with sha1-asm crate? I get the impression it isn't really expected to be used on Windows, as I see no signs of MSVC support. While it looks like it should be possible for it to work for -windows-gnu, maybe there's something else going on that is causing it to be used here on Windows instead of something more Windows-specific.

```toml
# Assembly doesn't yet compile on MSVC on windows, but does on GNU, see https://github.com/RustCrypto/asm-hashes/issues/17
# At this time, only aarch64, x86 and x86_64 are supported.
[target.'cfg(all(any(target_arch = "aarch64", target_arch = "x86", target_arch = "x86_64"), not(target_env = "msvc")))'.dependencies]
sha1 = { version = "0.10.0", optional = true, features = ["asm"] }
```

**Comment by jeremyd2019** [comment]
I will try to fix build on i686-pc-windows-gnu and open a PR against RustCrypto/asm-hashes, but for now probably the best option is to figure out how to disable the `gix/fast-sha1` feature for i686.  I'm not that familiar with cargo, but there doesn't seem to be an option to turn *off* a feature, so you may need `--no-default-features` and enable all the other features that should be enabled.  Or just drop i686 packages for starship for now.

**Comment by ognevnydemon** [comment]
I decided to disable i686 for now

**Comment by jeremyd2019** [comment]
I still need to test on clangarm64 too.  It looks like at least windows-targets needs to be updated to 0.48.1 (which is at least cleaner than hacking up 0.48.0 with sed)

**Comment by mati865** [comment]
Minimal patch for `gitoxide` that makes it build on i686:
```diff
$ git diff -- gix-features
diff --git a/gix-features/Cargo.toml b/gix-features/Cargo.toml
index e1cd1cdea..b03d44e00 100644
--- a/gix-features/Cargo.toml
+++ b/gix-features/Cargo.toml
@@ -150,9 +150,9 @@ libc = { version = "0.2.119" }
 bstr = { version = "1.3.0", default-features = false }


-# Assembly doesn't yet compile on MSVC on windows, but does on GNU, see https://github.com/RustCrypto/asm-hashes/issues/17
+# Assembly doesn't yet compile on MSVC and x86 GNU on windows, but does on x86_64 GNU, see https://github.com/RustCrypto/asm-hashes/issues/17
 # At this time, only aarch64, x86 and x86_64 are supported.
-[target.'cfg(all(any(target_arch = "aarch64", target_arch = "x86", target_arch = "x86_64"), not(target_env = "msvc")))'.dependencies]
+[target.'cfg(all(any(target_arch = "aarch64", target_arch = "x86", target_arch = "x86_64"), not(any(target_env = "msvc", all(target_arch = "x86", target_env = "gnu")))))'.dependencies]
 sha1 = { version = "0.10.0", optional = true, features = ["asm"] }

 [package.metadata.docs.rs]
```
> I will try to fix build on i686-pc-windows-gnu and open a PR against RustCrypto/asm-hashes

I don't know if they will accept any PR: https://github.com/RustCrypto/asm-hashes/pull/58

**Comment by jeremyd2019** [comment]
CLANGARM64 builds now.  Probably don't want to merge this yet, until python rebuilds are done.

**Comment by ognevnydemon** [comment]
> CLANGARM64 builds now.  Probably don't want to merge this yet, until python rebuilds are done.

python rebuilds are done. can we merge it now?

**Comment by ognevnydemon** [comment]
updated package to 1.16.0 and removed windows-targets workaround

**Comment by jeremyd2019** [comment]
Ugh, 1.16.0 failed on clangarm64 due to not finding `-lwindows`.  It seems now it only uses windows 0.39.0 and 0.48.x.  0.39.0 is too old to have gnullvm in its Cargo.toml, and 0.48.0 now uses a version number in its "windows" lib.  Does this need messing with 0.39.0's Cargo.toml to pull in the MSVC variant for aarch64, like back when aarch64 rust was first built @mati865 ?  ☹️

**Pull request merged**
