### PR TITLE
pelican: New package

### PR DESCRIPTION
**Pull request by podsvirov**
[Pelican](https://github.com/getpelican/pelican) is a useful static site generator.

Depend on:
- [x] #6497
- [ ] #6569
- [x] #6571

### CODE REVIEW

**Comment by podsvirov** [comment]
Ping.

Cc: @Alexpux

**Comment by Alexpux** [comment]
@podsvirov I'm getting off from MSYS2 so lets decide who will support packages building. Growing package database eat all my time so I dontr want to work on packages anymore

**Comment by podsvirov** [comment]
Hello, @lazka, what you think about this?
I also have no many free time...
The CI can do many work after people actions and checking...

**Comment by lazka** [comment]
See https://github.com/msys2/MSYS2-packages/issues/2014

Once we have things figured out we'll focus more on adding new packages I guess.

**Comment by podsvirov** [comment]
Hello @lazka , any news about adding new packages?

**Comment by lazka** [comment]
Many of the optdepends packages don't seem to exist. Can you maybe clean that up? I've merged the other things for starters.

**Comment by Biswa96** [comment]
^ Or comment those optdepends packages which does not exist here. Others may find those useful, if needed.

**Comment by podsvirov** [comment]
@Biswa96, I have commented out the unavailable optional dependencies.

@lazka, what about to merging #6569?

**Comment by podsvirov** [comment]
Great. Now we are waiting for the package `python-blinker` to be added to the repository, then this package should be built successfully.

**Pull request merged**
