### PR TITLE
ffmpeg: enable libjxl

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
Should this also be enabled for ffmpeg4.4?

**Comment by kmilos** [comment]
> Should this also be enabled for ffmpeg4.4?

I didn't check if it was actually supported there, sorry... Maybe leave it out if 4.4 is being phased out anyway?

**Comment by lazka** [comment]
We only have 4.4 because some packages aren't compatible with anything newer, so I think it's fine to just leave it as is, until we can delete it.

**Comment by lazka** [comment]
I've created #20151 for tracking the 4.4 removal

**Pull request merged**
