### PR TITLE
mlt: Update to 7.22.0

### PR DESCRIPTION
**Pull request by hmartinez82**
image

### CODE REVIEW

**Comment by Biswa96** [comment]
Did you check if this update does not crash shotcut in all MSYSTEMs?

**Comment by hmartinez82** [comment]
I ran the unit tests in UCRT64 and CLANG64 . There's one unit test failing: `QtTest:properties`
Were there previous attempts to update `mlt` that led to crashes?

**Comment by Biswa96** [comment]
I have tried to update mlt and shotcut. The very recent attempt crashes shotcut.

**Comment by hmartinez82** [comment]
Ahh ok. I certainly did not check shotcut. I'll close this.

**Comment by Biswa96** [comment]
I did not mean to discourage this attempt. There may be some issue in my system also. Feel free to try.

**Comment by hmartinez82** [comment]
Understood. I'll look into it. 
To be fair shotcut is already not working even before this update in both UCRT64 and MINGW64, only CLANG64 and CLANGARM64 

- In UCRT64 and MINGW64 shotcut shows the splash screen for a second and exits with error code 1. I see no crash
- In the CLANG builds the app loads, but the timeline in the bottom is just a blank white:

**Comment by hmartinez82** [comment]
I wonder if this is all happening due to Qt 6.6

**Comment by hmartinez82** [comment]
@Biswa96 What should we do?
This while updating shotcut to 24.02 😓:
```
-- Checking for module 'mlt++-7>=7.22.0'
--   Package dependency requirement 'mlt++-7 >= 7.22.0' could not be satisfied.
Package 'mlt++-7' has version '7.18.0', required version is '>= 7.22.0'
CMake Error at C:/msys64/ucrt64/share/cmake/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - mlt++-7>=7.22.0

Call Stack (most recent call first):
  C:/msys64/ucrt64/share/cmake/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  CMakeLists.txt:47 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...
```

Then I built mlt 7.22.0 locally and shotcut 24.02 crashes at startup 😑

**Comment by hmartinez82** [comment]
@Biswa96 Finally! Tracked this down. Now Shotcut works on CLANGARM64, CLANG64, MINGW64 and UCRT64

**Comment by Biswa96** [comment]
Would it be possible to upstream the change?

**Comment by hmartinez82** [comment]
@Biswa96 Already done :)  https://github.com/mltframework/mlt/pull/974

**Pull request merged**
