### PR TITLE
rpi-imager: add package

### PR DESCRIPTION
**Pull request by Biswa96**
I have used the package with Raspberry Pi 4B to write bootloader and Raspberry Pi OS.

<details><summary>Click here to see the screenshot of rpi-imager</summary>

image

</summary>

### CODE REVIEW

**Comment by ArchGuyWu** [comment]
It won't start even with administrator permission.

**Comment by Biswa96** [comment]
> It won't start even with administrator permission.

rpi-imager requires admin permission. Probably, Windows Defender or other antivirus blocks programs which is not signed.

**Comment by ArchGuyWu** [comment]
> > It won't start even with administrator permission.
> 
> rpi-imager requires admin permission. Probably, Windows Defender or other antivirus blocks programs which is not signed.

I disabled WD, and rufus works well.

**Comment by ArchGuyWu** [comment]
> How did you execute rufus or rpi-imager?

Just click it.

**Comment by ArchGuyWu** [comment]
I created a shortcut for it.

**Pull request merged**
