### PR TITLE
Update GTK to 4.1.2

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Appropriate for https://github.com/msys2/MINGW-packages-dev perhaps?

**Comment by Biswa96** [comment]
Which lunatic decides the version of GTK? The version 4.1.2 literally just belongs to gtk4.

**Comment by lazka** [comment]
odd minor releases are unstable for all GNOME libraries

**Comment by mingwandroid** [comment]
odd-sem-ver I like to call it.

**Comment by taozuhong** [comment]
GTK 4 is a big change version and needs more testing, release these packages for testing.

**Comment by mingwandroid** [comment]
If we release packages that need testing the we risk breaking a lot of people though, we'd probably love some testing repos? but we are not there yet.

**Comment by taozuhong** [comment]
I  respect your thoughts, 

but I should point out: there is no app that supports GTK 4 now, just for testing only.

**Comment by lazka** [comment]
OK, fair enough. Let's allow it for 4.1.x only to get more testing.

**Pull request merged**
