### PR TITLE
python-astroid: update to 2.8.4

### PR DESCRIPTION
**Pull request by raedrizqie**
reverse dep failure (pylint)

### CODE REVIEW

**Comment by lazka** [comment]
> reverse dep failure (pylint)

that seems relevant in this case, no?

**Comment by raedrizqie** [comment]
> > reverse dep failure (pylint)
> 
> that seems relevant in this case, no?

i will update pylint afterwards

**Comment by lazka** [comment]
Please update it in this PR so we can see if all dependencies are correct

**Comment by raedrizqie** [comment]
> Please update it in this PR so we can see if all dependencies are correct

will do.. thx

**Comment by lazka** [comment]
ok, fair enough

**Pull request merged**
