### PR TITLE
wxWidgets update to 3.0.5 and use builtin libraries in Static library build

### PR DESCRIPTION
**Pull request by stahta01**
See [wxSVG: Cannot Link Statically](https://github.com/msys2/MINGW-packages/issues/5601) for reason for using builtin library. This does not fix that issue; but, should help with that issue.

Tim S.

### CODE REVIEW

**Comment by stahta01** [comment]
Changing this PR because wxWidgets 3.0.5 was just released today

**Comment by Alexpux** [comment]
@stahta01 we prefer shared linking and do static linking if it not breal shared linking only.

**Comment by stahta01** [comment]
So, you prefer the wxWidgets static libraries use DLLs instead of using the builtin static support libraries? Tim S.

**Comment by stahta01** [comment]
@Alexpux Do you really prefer Static Libraries to use MSys2 MinGW DLLs?
This seems very wrong to me.

I do understand that Shared Libraries should use MSys2 MinGW DLLs!

Tim S.

**Comment by Alexpux** [comment]
@stahta1 sorry I’m wrong. I don’t look at PKGBUILD that it build wxwidget twice. Changes is ok

**Pull request merged**
