### PR TITLE
openexr: update to 3.3.2

### PR DESCRIPTION
**Pull request by kmilos**
Edit: I just noticed duplication of https://github.com/msys2/MINGW-packages/pull/22491 (which I guess doesn't build with recent Clang 19 swicth...) @lazka

### CODE REVIEW

**Comment by Biswa96** [comment]
Does openexr update break ABI/API in this case?

**Comment by lazka** [comment]
> Edit: I just noticed duplication of #22491 (which I guess doesn't build with recent Clang 19 swicth...) @lazka

That was with v18 still, I haven't looked into it yet.

**Comment by mmuetzel** [comment]
> MINGW32 failure in gimp: last time built was before GCC 14, which became more strict
> 
> CLANG64 failure in OSG: I guess also due to Clang 19 switch...
> 
> Unfortunately, I don't have the bandwidth to dive into this pit 😞

The build errors for GIMP and OSG should be fixed now. It's not clear (yet) if all packages that would have been built later in the queue build correctly. It might be worth rebasing on a current head if you come around to it.
(Don't forget to bump the pkgrel of updated packages when you rebase.)

**Comment by mmuetzel** [comment]
It still builds for me locally after updating with `pacman -Syu`. Maybe, just an intermittent fluke? I'll try to restart the MINGW32 job once the other jobs have finished. (GitHub doesn't allow to restart a job while others are still running...)

**Comment by mmuetzel** [comment]
> As the build takes hours, is there a better strategy to bumping this?

You could open a separate PR to fix the issue with rebuilding darktable if you prefer.

**Comment by mmuetzel** [comment]
@lazka: Could you hold moving packages from staging to the main repositories if we merge this in several steps?

**Comment by lazka** [comment]
sure

**Comment by mmuetzel** [comment]
`mingw-w64-gst-plugins-bad` failed to rebuild on CLANGARM64 with errors like the following:
```
  [669/1237] Compiling C++ object sys/d3d11/libgstd3d11.dll.p/gstd3d11window_swapchainpanel.cpp.obj
  FAILED: sys/d3d11/libgstd3d11.dll.p/gstd3d11window_swapchainpanel.cpp.obj 
  "clang++" "-Isys/d3d11/libgstd3d11.dll.p" "-Isys/d3d11" "-I../gst-plugins-bad-1.24.9/sys/d3d11" "-I." "-I../gst-plugins-bad-1.24.9" "-Igst-libs" "-I../gst-plugins-bad-1.24.9/gst-libs" "-Igst-libs/gst/codecs" "-Igst-libs/gst/d3d11" "-Igst-libs/gst/dxva" "-IC:/msys64/clangarm64/include/gstreamer-1.0" "-IC:/msys64/clangarm64/include/glib-2.0" "-IC:/msys64/clangarm64/lib/glib-2.0/include" "-IC:/msys64/clangarm64/include/orc-0.4" "-IC:/msys64/clangarm64/include/directxmath" "-fdiagnostics-color=always" "-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wno-non-virtual-dtor" "-fvisibility=hidden" "-fno-strict-aliasing" "-Wformat-nonliteral" "-Wmissing-declarations" "-Wredundant-decls" "-Wwrite-strings" "-Wformat" "-Wformat-security" "-Winit-self" "-Wmissing-include-dirs" "-Waddress" "-Wno-multichar" "-Wvla" "-Wpointer-arith" "-O2" "-pipe" "-Wp,-D_FORTIFY_SOURCE=2" "-fstack-protector-strong" "-Wp,-D__USE_MINGW_ANSI_STDIO=1" "-DHAVE_CONFIG_H" "-DGST_USE_UNSTABLE_API" "-DHAVE_WINMM" "-Wno-redundant-decls" -MD -MQ sys/d3d11/libgstd3d11.dll.p/gstd3d11window_swapchainpanel.cpp.obj -MF "sys/d3d11/libgstd3d11.dll.p/gstd3d11window_swapchainpanel.cpp.obj.d" -o sys/d3d11/libgstd3d11.dll.p/gstd3d11window_swapchainpanel.cpp.obj "-c" ../gst-plugins-bad-1.24.9/sys/d3d11/gstd3d11window_swapchainpanel.cpp

[trimmed loads of missing-braces warnings from Clang]

 ../gst-plugins-bad-1.24.9/sys/d3d11/gstd3d11window_swapchainpanel.cpp:32:10: fatal error: 'windows.ui.xaml.media.dxinterop.h' file not found
     32 | #include <windows.ui.xaml.media.dxinterop.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  62 warnings and 1 error generated.
```

Afaict, no package that is distributed by MSYS2 provides that header.
The package built without issues for the other environments.

**Comment by mmuetzel** [comment]
I opened #22602 with a potential fix.

**Pull request merged**
