### PR TITLE
calculix-ccx: Fix numeric output format on UCRT64.

### LINKED ISSUE #22630: calculix-ccx ucrt error (comma instead of dot)
### Description / Steps to reproduce the issue

Run this input, and see input.frd

$ ccx -i input

input.inp:
```
***********************************************************************
*NODE, NSET=Nall
       1,5.000000000000e+01,5.000000000000e+01,0.000000000000e+00
       2,5.000000000000e+01,0.000000000000e+00,0.000000000000e+00
       3,5.000000000000e+01,0.000000000000e+00,5.000000000000e+01
       4,5.000000000000e+01,5.000000000000e+01,5.000000000000e+01
       5,0.000000000000e+00,5.000000000000e+01,0.000000000000e+00
       6,0.000000000000e+00,0.000000000000e+00,0.000000000000e+00
       7,0.000000000000e+00,0.000000000000e+00,5.000000000000e+01
       8,0.000000000000e+00,5.000000000000e+01,5.000000000000e+01
*ELEMENT, TYPE=C3D8, ELSET=Eall
     1,     1,     2,     3,     4,     5,     6,     7,     8
***********************************************************************
*NSET,NSET=Nfix 
1, 2, 5, 6, 
***********************************************************************
*NSET,NSET=Nload 
3, 4, 7, 8, 
***********************************************************************
*BOUNDARY
Nfix, 1,3,,
***********************************************************************
*MATERIAL, NAME=17-4PH_H1025
*ELASTIC
210.e+3, 0.3
*EXPANSION,TYPE=ISO,ZERO=20.
1.2e-5
*SOLID SECTION, ELSET=Eall, MATERIAL=17-4PH_H1025
***********************************************************************
*STEP,NLGEOM=YES
*STATIC,SOLVER=SPOOLES
0.1, 1., 1e-05, 0.1
***********************************************************************
*BOUNDARY
Nload, 3,3,-.8,
***********************************************************************
*NODE FILE
U, NT
*NODE PRINT, NSET=Nfix, TOTALS=ONLY
U
***********************************************************************
*EL FILE
S, E, PEEQ
*END STEP
```

### Expected behavior

Good results (mingw64 and clang 64) from ccx:

```
    1C
    1UUSER                                                              
    1UDATE              23.november.2024                                
    1UTIME              15:53:33                                        
    1UHOST                                                              
    1UPGM               CalculiX                                        
    1UVERSION           Version 2.22                             
    1UCOMPILETIME       Mon Aug  5 19:15:25 CEST 2024                    
    1UDIR                                                               
    1UDBN                                                               
    1UMAT    117-4PH_H1025                                              
    2C                         29791                                     1
 -1         1 5.00000E+01 5.00000E+01 0.00000E+00
 -1         2 5.00000E+01 4.83333E+01 0.00000E+00
 -1         3 5.00000E+01 4.83333E+01 1.66667E+00
 -1         4 5.00000E+01 5.00000E+01 1.66667E+00
```

mingw64

### Actual behavior

Results (ucrt64) from ccx:

```
    1C
    1UUSER                                                              
    1UDATE              23.november.2024                                
    1UTIME              15:59:24                                        
    1UHOST                                                              
    1UPGM               CalculiX                                        
    1UVERSION           Version 2.22                             
    1UCOMPILETIME       Mon Aug  5 19:15:25 CEST 2024                    
    1UDIR                                                               
    1UDBN                                                               
    1UMAT    117-4PH_H1025                                              
    2C                         29791                                     1
 -1         1 5,00000E+01 5,00000E+01 0,00000E+00
 -1         2 5,00000E+01 4,83333E+01 0,00000E+00
 -1         3 5,00000E+01 4,83333E+01 1,66667E+00
 -1         4 5,00000E+01 5,00000E+01 1,66667E+00
 -1         5 4,83333E+01 5,00000E+01 0,00000E+00
```

ucrt64

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26100

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

### Are you willing to submit a PR?

no

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Fixes #22630 
@3rav could you test artifacts for UCRT64, after It finishes building.

### CODE REVIEW

**Comment by 3rav** [comment]
There are problems,some of the results are with `.` and some are with `,` ucrt64 + fix:

cgx menu:
menu_ucrt

output from ccx:
output_ucrt

frd file:
frd_ucrt

**Comment by MehdiChinoune** [comment]
Could you try again, now.

**Comment by 3rav** [comment]
New fix, after some tests (~10 different types of calculations):
- .frd, .dat output files are OK (only `.`)
- ccx output, sometimes `,` and later `.`

```
 increment 1 attempt 1 
 increment size= 1,000000e-01
 sum of previous increments=0,000000e+00
 actual step time=1,000000e-01
 actual total time=1,000000e-01

 iteration 1

 Using up to 1 cpu(s) for the stress calculation.

 Using up to 1 cpu(s) for the symmetric stiffness/mass contributions.

 Factoring the system of equations using the symmetric spooles solver
 Using up to 4 cpu(s) for spooles.

 Using up to 1 cpu(s) for the stress calculation.

 average force= 99791,040553
 time avg. forc= 99791,040553
 largest residual force= 113,168214 in node 8 and dof 1
 largest increment of disp= 1,714286e-02
 largest correction to disp= 1,714286e-02 in node 8 and dof 1

 no convergence

 iteration 2

 Using up to 1 cpu(s) for the symmetric stiffness/mass contributions.

 Factoring the system of equations using the symmetric spooles solver
 Using up to 4 cpu(s) for spooles.

 Using up to 1 cpu(s) for the stress calculation.

 average force= 99785,622227
 time avg. forc= 99785,622227
 largest residual force= 0,000090 in node 8 and dof 2
 largest increment of disp= 1,714286e-02
 largest correction to disp= 1,599705e-05 in node 8 and dof 1

 convergence

 Using up to 1 cpu(s) for the stress calculation.

 increment 2 attempt 1 
 increment size= 1.000000e-01
 sum of previous increments=1.000000e-01
 actual step time=2.000000e-01
 actual total time=2.000000e-01
```

**Comment by 3rav** [comment]
As without the patch file, everywhere `,`

**Comment by MehdiChinoune** [comment]
What about now?

**Comment by 3rav** [comment]
Looks good!

**Pull request merged**
