### PR TITLE
wslay: build with cmake and ninja

### PR DESCRIPTION
**Pull request by neheb**
Faster and more reliable.

Added check() section.

Added patch to fix compilation with cmake.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by lazka** [comment]
It's missing:

* the shared lib
* the pkg-config file
* the man pages

```diff
  --- /dev/fd/63	2021-12-18 00:22:20.000000000 +0000
  +++ /dev/fd/62	2021-12-18 00:22:20.000000000 +0000
  @@ -1,39 +1,13 @@
   /mingw64/
  -/mingw64/bin/
  -/mingw64/bin/libwslay-0.dll
   /mingw64/include/
   /mingw64/include/wslay/
   /mingw64/include/wslay/wslay.h
   /mingw64/include/wslay/wslayver.h
   /mingw64/lib/
  +/mingw64/lib/cmake/
  +/mingw64/lib/cmake/wslay/
  +/mingw64/lib/cmake/wslay/wslay.cmake
  +/mingw64/lib/cmake/wslay/wslay-config.cmake
  +/mingw64/lib/cmake/wslay/wslay-release.cmake
   /mingw64/lib/libwslay.a
  -/mingw64/lib/libwslay.dll.a
  -/mingw64/lib/pkgconfig/
  -/mingw64/lib/pkgconfig/libwslay.pc
  -/mingw64/share/
  -/mingw64/share/man/
  -/mingw64/share/man/man3/
  -/mingw64/share/man/man3/wslay_event_config_set_callbacks.3.gz
  -/mingw64/share/man/man3/wslay_event_config_set_max_recv_msg_length.3.gz
  -/mingw64/share/man/man3/wslay_event_config_set_no_buffering.3.gz
  -/mingw64/share/man/man3/wslay_event_context_client_init.3.gz
  -/mingw64/share/man/man3/wslay_event_context_free.3.gz
  -/mingw64/share/man/man3/wslay_event_context_server_init.3.gz
  -/mingw64/share/man/man3/wslay_event_get_close_received.3.gz
  -/mingw64/share/man/man3/wslay_event_get_close_sent.3.gz
  -/mingw64/share/man/man3/wslay_event_get_queued_msg_count.3.gz
  -/mingw64/share/man/man3/wslay_event_get_queued_msg_length.3.gz
  -/mingw64/share/man/man3/wslay_event_get_read_enabled.3.gz
  -/mingw64/share/man/man3/wslay_event_get_status_code_received.3.gz
  -/mingw64/share/man/man3/wslay_event_get_status_code_sent.3.gz
  -/mingw64/share/man/man3/wslay_event_get_write_enabled.3.gz
  -/mingw64/share/man/man3/wslay_event_queue_close.3.gz
  -/mingw64/share/man/man3/wslay_event_queue_fragmented_msg.3.gz
  -/mingw64/share/man/man3/wslay_event_queue_msg.3.gz
  -/mingw64/share/man/man3/wslay_event_recv.3.gz
  -/mingw64/share/man/man3/wslay_event_send.3.gz
  -/mingw64/share/man/man3/wslay_event_set_error.3.gz
  -/mingw64/share/man/man3/wslay_event_shutdown_read.3.gz
  -/mingw64/share/man/man3/wslay_event_shutdown_write.3.gz
  -/mingw64/share/man/man3/wslay_event_want_read.3.gz
  -/mingw64/share/man/man3/wslay_event_want_write.3.gz
  +/mingw64/lib/libwslay_shared.dll.a
```

**Comment by lazka** [comment]
hm?

**Comment by neheb** [comment]
Cmake build looks incomplete.

**Comment by lazka** [comment]
ok :)

**Pull request closed without merging**
