### PR TITLE
flang: update to 15.0.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
```
  LLVM ERROR: out of memory
  Allocation failed
```
https://github.com/llvm/llvm-project/issues/49403

**Comment by lazka** [comment]
Would `-DLLVM_PARALLEL_LINK_JOBS=1` help maybe? https://github.com/llvm/llvm-project/issues/49403#issuecomment-998709042

I guess 32 bit fails because it expects "long double" to be 64bits

**Comment by MehdiChinoune** [comment]
> Would `-DLLVM_PARALLEL_LINK_JOBS=1` help maybe? [llvm/llvm-project#49403 (comment)](https://github.com/llvm/llvm-project/issues/49403#issuecomment-998709042)
> 
> I guess 32 bit fails because it expects "long double" to be 64bits. Annoying that mingw has a different ABI there...

We already restricting build jobs to one. what else we could do?

**Comment by lazka** [comment]
> We already restricting build jobs to one. what else we could do?

yeah, I see.. true..

**Comment by lazka** [comment]
> I guess 32 bit fails because it expects "long double" to be 64bits. Annoying that mingw has a different ABI there...

I think this error should also occur on 32 bit Linux (where long double is also 96 bits), so maybe upstream doesn't test with that?

**Comment by mati865** [comment]
That would make sense given the fact it won't build with 32-bit address space anyway (one does need to cross compile it from 64-bit) and https://github.com/llvm/llvm-project/issues/57621#issuecomment-1242925642

**Comment by lazka** [comment]
aarch64 ENOMEMed also, so disabling that too:

```
2022-09-13T19:58:57.1674115Z [51/286] Building CXX object lib/Lower/CMakeFiles/obj.FortranLower.dir/ConvertExpr.cpp.obj
2022-09-13T19:58:57.1674750Z FAILED: lib/Lower/CMakeFiles/obj.FortranLower.dir/ConvertExpr.cpp.obj 
2022-09-13T19:58:57.2219435Z C:\msys64\clangarm64\bin\clang++.exe -DFLANG_LITTLE_ENDIAN=1 -DGTEST_HAS_RTTI=0 -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IC:/M/mingw-w64-flang/src/flang-15.0.0.src/include -IC:/M/mingw-w64-flang/src/build-CLANGARM64/include -O2 -pipe -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -Wno-deprecated-copy -Wno-string-conversion -Wno-unused-command-line-argument -Wstring-conversion           -Wcovered-switch-default -Wno-nested-anon-types -O3 -DNDEBUG  -fno-exceptions -fno-rtti -std=c++17 -MD -MT lib/Lower/CMakeFiles/obj.FortranLower.dir/ConvertExpr.cpp.obj -MF lib\Lower\CMakeFiles\obj.FortranLower.dir\ConvertExpr.cpp.obj.d -o lib/Lower/CMakeFiles/obj.FortranLower.dir/ConvertExpr.cpp.obj -c C:/M/mingw-w64-flang/src/flang-15.0.0.src/lib/Lower/ConvertExpr.cpp
2022-09-13T19:58:57.2315788Z LLVM ERROR: out of memory
2022-09-13T19:58:57.2316505Z Allocation failed
```

**Comment by jeremyd2019** [comment]
The build of flang 15.0.0 failed on the QC710 (which has 4GB RAM), but I just did a test on a VM on a Raspberry Pi 4 8GB (VM with 6.2GB RAM, the most I could do without the host swapping badly) and that succeeded, slowly.  This was also a test of Win11 22H2 and the new official pre-release arm64 runner build.

https://github.com/msys2-arm/MINGW-packages/actions/runs/3131180157/jobs/5082250794

**Pull request merged**
