### PR TITLE
pyqt3d: new package

### PR DESCRIPTION
**Pull request by melven**
New package for mingw-w64-pyqt3d very much copied from mingw-w64-python-pyqt5.

Tested and worked fine for me...<br>

Locally, I had to remove the --confirm-licence for sip-build though.
In this pull request, the flags are identical to those in the python-qt5 package.

### CODE REVIEW

**Comment by melven** [comment]
Ok, the CI also does not like the `--confirm-license` flag. Should I remove it?

**Comment by lazka** [comment]
hm, thanks. It would be nice if only those things were copied which are actually needed for this package.

I can try to help if you want though.

**Comment by melven** [comment]
What should a change / remove? I just assumed that most things for building PyQt3d are very similar to PyQt5.

**Comment by lazka** [comment]
ok, I'll have a look tomorrow

**Pull request merged**
