### PR TITLE
Add cmake-bootstrap

### PR DESCRIPTION
**Pull request by lazka**
A cmake variant that doesn't depend on any external dependencies and can be used for bootstrapping an env, and building a full cmake.

### CODE REVIEW

**Comment by Biswa96** [comment]
Identity crisis - if standalone cmake-bootstrap is present why do we need the system dependent cmake?

**Comment by lazka** [comment]
> Identity crisis - if standalone cmake-bootstrap is present why do we need the system dependent cmake?

It statically links everything, which isn't ideal I guess. But yeah, I'm not sure what the best approach is.. this is more of an experiment.

**Comment by Biswa96** [comment]
Alpine Linux links cmake selectively https://git.alpinelinux.org/aports/tree/main/cmake/APKBUILD

```
# jsoncpp/cppdap/curl/nghttp2 needs cmake to build so to avoid recursive build
# dependency, we use the bundled version.
# Do NOT remove --no-system-*
```

**Comment by lazka** [comment]
oh, and the qt-gui stuff would be missing, since that can't be vendored in.

**Comment by lazka** [comment]
One difference to Linux distributions is that they are usually fine with using autotools in the cmake dependencies to avoid cycles. But in our case I'd prefer if we would switch to cmake for packages that support it, like libarchive and libuv.

**Comment by lazka** [comment]
I expanded the commit message a bit and changed cmake to build with cmake-bootstrap.

**Pull request merged**
