### PR TITLE
libipt update

### PR DESCRIPTION
**Pull request by GitMensch**
* version bump
* changed to use tags instead of commit id
* adjustment to current version by disabling C11 threads

### CODE REVIEW

**Comment by ognevnydemon** [comment]
as it was discussed in #18556, source tarballs are prefered more, than versioned tag

**Comment by GitMensch** [comment]
We should have a general issue about that, just search for `#tag` (it "obviously" was so common in here that I've changed to that - will revert).

**Comment by Biswa96** [comment]
`#tag` is ok here. The source repository is small. We use it for other small packages also.

ArchLinux prefers `#tag` instead of source tarball (most of the time) because it helps to verify the source using git.

**Comment by GitMensch** [comment]
... ok, then getting back to `#tag` with the next commit...

**Comment by Biswa96** [comment]
It is not an requirement. You are welcome to use either `#commit` or `#tag` as per your preference for this package.

**Comment by lazka** [comment]
Note that tags can change, commits can't.

**Comment by GitMensch** [comment]
If you tell me that you want to part from Arch and want to replace all `#tag` by `#commit` "over time", then I'm totally adjusting this one. Otherwise I'd leave it as is and consider this PR finished.

**Pull request merged**
