### PR TITLE
gmp - 6.2.0 - added patch from Cygwin.

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by Biswa96** [comment]
Just curious, is the patch reported to upstream?

**Comment by lazka** [comment]
Why do we need it?

**Comment by JPeterMugaas** [comment]
I think it adds support for some types of chip architectures.  I found it when looking at the CygWin package for gmp.

**Comment by lazka** [comment]
looking at the upstream repo it looks like the CPU detection is more up to date for x86_64 and this tries to also add it for x86. I wonder if anyone cares about x86 that much still if performance is an issue and if we should apply this if none of us understand the change.

**Comment by lazka** [comment]
Also we don't build with "--enable-fat", so I'm wondering if this changes anything at all.

**Comment by lazka** [comment]
I tried asking on the gmp mailing list since they don't have a bug tracker, but it blocks my messages, so I'm giving up...

**Comment by JPeterMugaas** [comment]
I think we actually with "--enable-fat".  That's what I see in the script.

**Comment by lazka** [comment]
> I think we actually with "--enable-fat". That's what I see in the script.

missing word? Which script?

**Comment by JPeterMugaas** [comment]
Alright, I was looking at the wrong script.  It was the one for MSYS2.  But ideally, I would like to see the fat capability in MINGW.

**Comment by lazka** [comment]
What about adding it to this PR?

**Comment by lazka** [comment]
No response, closing.

**Pull request closed without merging**
