### PR TITLE
Remove redundant dependency

### PR DESCRIPTION
**Pull request by jeroen**
See comment here: https://github.com/msys2/MINGW-packages/pull/18000#issuecomment-1694662796

### CODE REVIEW

**Comment by raedrizqie** [comment]
you forgot to bump the pkgrel

**Comment by jeroen** [comment]
I don't think that is needed? Nothing will change really, the dependency was not used right?

**Comment by sskras** [comment]
Having two different configuration of the package under the same version would confuse users who report the bug / does QA testing.

**Comment by lazka** [comment]
> Having two different configurations of a package published under the same version would confuse users who report bugs / does QA testing, IMO.

without pkgrel bump nothing will reach the user

**Pull request merged**
