### PR TITLE
gegl: Update to 0.4.18; Port to meson

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by Alexpux** [comment]
@lazka what problem with getting release archive? I see it present on ftp

**Comment by lazka** [comment]
```
gegl-0.4.18/bin/lua/gegl_crop.lua: Can't create 'gegl-0.4.18/bin/lua/gegl_crop.lua'
gegl-0.4.18/bin/lua/gegl_fill-path.lua: Can't create 'gegl-0.4.18/bin/lua/gegl_fill-path.lua'
bsdtar: Error exit delayed from previous errors.
```

**Comment by Alexpux** [comment]
@lazka well we solve such issue for many packages adding noextract to header and unpack in prepare

**Comment by lazka** [comment]
ok, I'll give that a try

**Comment by lazka** [comment]
done

**Comment by Alexpux** [comment]
@ i see error in builds:
````
[775/776] Generating docs_commandline_txt_html with a custom command.
D:/a/1/s/mingw-w64-gegl/src/build-i686-w64-mingw32/bin/gegl.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
asciidoc: WARNING: commandline.txt: line 22: sys::[bash -c './bin/gegl -h 2>&1']: non-zero exit status

[776/776] Generating gallery-stamp with a meson_exe.py custom command.
````

so probably we miss some dependencies

**Comment by lazka** [comment]
good catch, I'll have a look

**Comment by Alexpux** [comment]
@lazka something linked with old libspiro

**Comment by Alexpux** [comment]
i will look

**Pull request merged**
