### PR TITLE
cargo-create-tauri-app: update to 4.5.0

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
`CLANG64`:
```
error: failed to download `windows_x86_64_gnullvm v0.48.5`
```

**Comment by ognevny** [comment]
change prepare() to fit it like in template

**Comment by ognevny** [comment]
`cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"`

**Comment by ognevny** [comment]
I can push a commit to change all old-style fetch so no help will be required

**Comment by podsvirov** [comment]
@ognevny, thanks!

**Pull request merged**
