### PR TITLE
libghdl: Fix generation of .link and .lst files in UCRT64

### LINKED ISSUE #16034: lib/libghdl.link has a wrong hardcoded path in UCRT64
### Description / Steps to reproduce the issue

The link input file provided by libghdl has a hardcoded path in UCRT64
This error is not present in MINGW64

### Expected behavior

`/ucrt64/lib/gcc/x86_64-w64-mingw32/12.2.0/adalib/libgnat.a`

### Actual behavior

`D:/a/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/12.2.0/adalib/libgnat.a` 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by hmartinez82**
Fixes #16034

### CODE REVIEW

**Comment by Biswa96** [comment]
Isn't it possible to use typical sed command to remove full path of MINGW_PREFIX? For example, the following command is used most of the time

```sh
sed -s "s|${PREFIX_DEPS}|${MINGW_PREFIX}|g" -i libghdl.link
```

**Comment by hmartinez82** [comment]
Open to improvements, but I'm by no means a sed wizard so I went the least churn possible route

**Comment by Biswa96** [comment]
There is no wizardry or witchcraft 🪄 Just copy paste from other PKGBUILD. The command can be found with

```
grep -r "cygpath" MINGW-packages --include PKGBUILD
```

**Comment by Biswa96** [comment]
++pkgrel;

**Comment by hmartinez82** [comment]
> ++pkgrel;

Done :)

**Pull request merged**
