### PR TITLE
openssl: Update to 1.1.1s

### PR DESCRIPTION
**Pull request by lazka**
Add new singing key
remove patch which is included in the new release

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
> Add new singing key remove patch which is included in the new release

Who is singing?

**Comment by lazka** [comment]
> Who is singing?

see https://www.openssl.org/community/otc.html linked above, Tomas Mraz

**Comment by MehdiChinoune** [comment]
> > Who is singing?
> 
> see https://www.openssl.org/source/ and linked https://www.openssl.org/community/otc.html linked above, Tomas Mraz
> 
> Should we make it more clear somehow?

You don't get the joke, `singing` vs `signing`.

**Comment by lazka** [comment]
😂

**Pull request merged**
