### PR TITLE
vulkan: Update to 1.2.179

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
Iff the version numbering is correct I will push the others.

**Comment by Biswa96** [comment]
Is the version number correct? @lazka

**Comment by lazka** [comment]
yes

**Comment by Biswa96** [comment]
CI out of memory 🤦

**Comment by jeremyd2019** [comment]
On gcc even

**Comment by lazka** [comment]
maybe https://www.mail-archive.com/devel@lists.fedoraproject.org/msg167371.html ?

**Comment by Biswa96** [comment]
I can't do anything to fix the mingw32 out of memory issue. Tried with `-j1` but failed.

**Comment by Biswa96** [comment]
I can't do anything to fix the mingw32 out of memory issue. Tried with `-j1` but failed.

**Comment by Biswa96** [comment]
Wouldn't the cflags variable ended up with "-O2 -O1"?

**Comment by lazka** [comment]
oh, it forces ` -O3`, so needs patching

**Comment by Biswa96** [comment]
Where are these come from `CMAKE_CXX_FLAGS_RELEASE` and `CMAKE_C_FLAGS_RELEASE`?

**Comment by Biswa96** [comment]
Where are these come from `CMAKE_CXX_FLAGS_RELEASE` and `CMAKE_C_FLAGS_RELEASE`? Those are set to `-O3` in spirv-headers build folder.

```
$ grep -ir o3
src/build-i686-w64-mingw32/CMakeCache.txt:CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
src/build-i686-w64-mingw32/CMakeCache.txt:CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
```

**Comment by Biswa96** [comment]
It looks like CMake automatically add `-O3` to cflags and cxxflags when package is built with release build type.

* Here is the output in spirv-headers build folder:

```
$ grep -r "\-O3"
src/build-i686-w64-mingw32/CMakeCache.txt:CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
src/build-i686-w64-mingw32/CMakeCache.txt:CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
```

* Here is one of the output in spirv-tools build folder:

```
$ grep -r "\-O3"
src/build-i686-static/build.ninja:  FLAGS = -march=i686 -mtune=generic -O2 -pipe -O3 -DNDEBUG
src/build-i686-static/CMakeCache.txt:CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
src/build-i686-static/CMakeCache.txt:CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
```

**Comment by jeremyd2019** [comment]
I wonder why CLANG32 got a `dlltool` "no target machine specified" error on vulkan-loader, while CLANG64 was fine.

**Comment by lazka** [comment]
Looks like this broke the ABI for 32bit maybe?

```
2021-06-02T10:06:00.2842393Z D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: gst-libs/gst/vulkan/libgstvulkan-1.0-0.dll.p/gstvkbuffermemory.c.obj:gstvkbuffermemory.c:(.text+0x2b2): undefined reference to `vkDestroyBuffer@16'
2021-06-02T10:06:00.2924980Z D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: gst-libs/gst/vulkan/libgstvulkan-1.0-0.dll.p/gstvkbuffermemory.c.obj:gstvkbuffermemory.c:(.text+0x4bd): undefined reference to `vkCreateBuffer@16'
2021-06-02T10:06:00.2928194Z D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: gst-libs/gst/vulkan/libgstvulkan-1.0-0.dll.p/gstvkbuffermemory.c.obj:gstvkbuffermemory.c:(.text+0x510): undefined reference to `vkGetBufferMemoryRequirements@16'
2021-06-02T10:06:00.2931171Z D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: gst-libs/gst/vulkan/libgstvulkan-1.0-0.dll.p/gstvkbuffermemory.c.obj:gstvkbuffermemory.c:(.text+0x6aa): undefined reference to `vkBindBufferMemory@28'
2021-06-02T10:06:00.3012815Z D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: gst-libs/gst/vulkan/libgstvulkan-1.0-0.dll.p/gstvkbuffermemory.c.obj:gstvkbuffermemory.c:(.text+0x7c3): undefined reference to `vkGetBufferMemoryRequirements@16'
2021-06-02T10:06:00.3024937Z D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: gst-libs/gst/vulkan/libgstvulkan-1.0-0.dll.p/gstvkcommandpool.c.obj:gstvkcommandpool.c:(.text+0x449): undefined reference to `vkDestroyCommandPool@16'
```

**Comment by Biswa96** [comment]
Yes, I have fixed it in mpv pull request.

**Comment by lazka** [comment]
Perfect, thanks

**Comment by Biswa96** [comment]
Just realized that I didn't have to do the heavy patching here for `__declspec(dllexport)` attribute because I have already added a DEF file for 32bit DLLs.

**Pull request merged**
