### PR TITLE
qt-creator: Update to 5.0.1

### LINKED ISSUE #9664: qt-creator: Missing Devel component for plugins development

### PR DESCRIPTION
**Pull request by podsvirov**
Install `Devel` component.

Closes #9664.

~~NOTES~~: The files `*.dll.a` are installed next to the files `*.dll`. Maybe we need to fix this. (Fixed in 7e0f027)

### CODE REVIEW

**Comment by Biswa96** [comment]
> The files `*.dll.a` are installed next to the files `*.dll`. Maybe we need to fix this.

Generally, it can be fixed by adding `ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}` in cmake file at `install()` step.

**Comment by podsvirov** [comment]
LGTM. What about to merge?

**Comment by Biswa96** [comment]
The include directory change seems weird. It's like everything is dumped in there. See the CI log.

**Comment by podsvirov** [comment]
This is life :man_shrugging:. And so it was conceived. But everything is neatly placed in one subfolder. I'm not going to fix this now.

**Pull request closed without merging**
