### PR TITLE
baobab: Open directory in explorer patch

### LINKED ISSUE #9343: baobab cannot open directories
Context menu -> Open Folder raises "Failed to open file" "No application is registered as handling this file" on directories.

### PR DESCRIPTION
**Pull request by mugiseyebrows**
Fixes #9343

### CODE REVIEW

**Comment by Biswa96** [comment]
1. Increase `pkgrel` variable.
2. If this patch is from upstream put a link of that commit or merge request as a comment.

**Comment by mugiseyebrows** [comment]
No, it's not from upstream, it's windows-specific, I think it wont be merged.

**Comment by Biswa96** [comment]
BTW, I am not familiar with GNOME environment but does it have some equivalent of LOAD_LIBRARY_SEARCH_SYSTEM32 flag? I mean instead of using "explorer" string can it be more specific like System32 folder only?

**Comment by lazka** [comment]
It's not ideal that we carry functional patches that wont make it upstream... but this is small enough I guess.

**Pull request merged**
