### PR TITLE
libusb-win32: fix compilation with lld

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
ping @fauxpark

**Comment by fauxpark** [comment]
https://github.com/msys2/MINGW-packages/pull/6679

**Comment by lazka** [comment]
@fauxpark do you agree?

**Comment by fauxpark** [comment]
No, this will break things. See the description on the PR above where I added this package.

**Comment by lazka** [comment]
Could you go into a bit more detail re what it would break? I'm not familiar with either package sadly.

**Comment by fauxpark** [comment]
Anyone who is used to the official release of dfu-programmer will be expecting to need the libusb-win32 driver installed on any device they wish to communicate with. If this change goes through, they will need to switch the driver to WinUSB, and would no longer be able to use the official release and the MSYS2 version interchangeably as the two driver APIs are incompatible. libusb-win32 is a windows port of libusb 0.1, while WinUSB is compatible with libusb 1.0.

It would certainly be a good idea to drop libusb-win32, but personally I feel that just isn't possible without breaking users' expectations, until dfu-programmer itself switches to building for libusb 1.0.

**Comment by neheb** [comment]
OTOH dfu-programmer seems quite dead upstream. There's also libusb-compat as well. Does that not work?

**Comment by fauxpark** [comment]
`libusb-compat` is just an interface for libusb 0.1 applications to work with libusb 1.0 - you still need the WinUSB driver installed on the device.

**Comment by neheb** [comment]
Decided to fix compilation with lld instead. Simple enough change.

**Pull request merged**
