### PR TITLE
OpenAI dependencies tier 1

### PR DESCRIPTION
**Pull request by Schala**
I'm splitting my OpenAI pull request into tiers because otherwise Travis/CI errors out. I'll be doing one tier at a time to ensure that it is checked successfully.

Tier 1 are the base dependencies that don't require any other packages I'm introduced that have yet to be built. It consists of:

- m2r
- python-astor
- python-astunparse
- python-async-timeout
- python-audioread
- python-biscuits
- python-cachetools
- python-click
- python-gast
- python-googleapis-common-protos
- python-google-resumable-media
- python-gsutil
- python-imageio
- python-imgviz
- python-itsdangerous
- python-llvmlite
- python-multidict
- python-opt_einsum
- python-profanityfilter
- python-pytest-mock
- python-pytest-timeout
- python-qtpy
- python-rsa
- python-soundfile
- python-termcolor
- python-tifffile
- python-toposort
- python-tqdm
- python-tracery
- python-trimesh
- python-typing_extensions
- python-werkzeug

### CODE REVIEW

**Comment by lazka** [comment]
So, that's quite a lot of packages, and maintaining them isn't free, so

1) Why do you/we need them all for?
2) Will you be helping out with the packages in the future?

**Comment by Schala** [comment]
Well, I've had an interest in OpenAI for a while, but they require a truckload of Python dependencies. Although, without the ability to use Tensorflow or PyTorch, all I can do is keep the other dependencies updated while I wait. As for maintaining them not being free, do you mean hosting the binaries, or keeping the PKGBUILDs up to date? Because if it's the latter, I'm not asking for any money from this.

**Comment by lazka** [comment]
> Well, I've had an interest in OpenAI for a while, but they require a truckload of Python dependencies

I was hoping you would explain what OpenAI is (or link to it) and why we'd want it :D

> As for maintaining them not being free, do you mean hosting the binaries, or keeping the PKGBUILDs up to date? Because if it's the latter, I'm not asking for any money from this.

The later. We usually ping the maintainer if something non-trivial in the package is broken.

but, anyway, let's merge this and see. Thanks!

**Comment by kmilos** [comment]
Please be aware that `imageio` will currently fail to find the freeimage lib, so it'll either have to be patched, or wait for a new [upstream](https://github.com/imageio/imageio/issues/554) release...

**Comment by mingwandroid** [comment]
This is more or less, the Python Data Science stack ported to MSYS2/mingw-w64-python.

For me it is great to see MSYS2 expanding its reach in this area.

**Comment by Schala** [comment]
Perhaps I'll remove the optional dependency. I only included it as per the Arch native PKGBUILD.

**Comment by kmilos** [comment]
It's quite useful actually. I'd also add tifffile in optdeps as well once it gets in the repo.

**Pull request merged**
