### PR TITLE
New packages: pastix4calculix

### PR DESCRIPTION
**Pull request by 3rav**

### CODE REVIEW

**Comment by Biswa96** [comment]
Python2? There are discussions about getting rid of it! The `provides` should have `MINGW_PACKAGE_PREFIX` also.

**Comment by 3rav** [comment]
With the another version (I mean 3) I have a bug preventing compilation.

**Comment by lazka** [comment]
yeah, no more python2 please.

**Comment by 3rav** [comment]
I have this error with python3:

```
-- Generating done
  CMake Error:
    Running
  
     'D:/a/_temp/msys/msys64/mingw64/bin/ninja.exe' '-C' 'C:/_/mingw-w64-pastix4calculix/src/build-x86_64-w64-mingw32-static' '-t' 'recompact'
  
    failed with:
  
     ninja: error: build.ninja:1842: expected '=', got lexing error
  
    common/z_integer.c" -p s -P common && chmod a-w common/s_integer.c"
  
  
          ^ near here
  
  
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  ==> ERROR: A failure occurred in build().
      Aborting...
```

**Comment by Biswa96** [comment]
In the patch file, what is wrong with all those memset?

**Comment by 3rav** [comment]
Previously, instead of memset was bzero, I made "pull requests" for this (https://github.com/Kabbone/PaStiX4CalculiX/pull/1) but now I decided that maybe it is better to unify the syntax of the main official version 6.1.0 Pastix: https://gitlab.inria.fr/solverstack/pastix/-/blob/master/order/order_find_supernodes.c

**Comment by Biswa96** [comment]
Just curious. Why is a forked repository (Kabbone/PaStiX4CalculiX) used instead of actual one (Dhondtguido/PaStiX4CalculiX)?

**Comment by 3rav** [comment]
Dhondtguido/PaStiX4CalculiX requires CUDA but this version does not (Kabbone/PaStiX4CalculiX).

**Comment by 3rav** [comment]
> Python2? There are discussions about getting rid of it! The `provides` should have `MINGW_PACKAGE_PREFIX` also.

Where can I find this discussion?

**Pull request closed without merging**
