### PR TITLE
[new package] supertuxkart 1.4

### PR DESCRIPTION
**Pull request by ognevny**

### CODE REVIEW

**Comment by ognevny** [comment]
what's wrong with GCC envs? it failseven with clang!

**Comment by Biswa96** [comment]
Include stdio.h for snprintf.

**Comment by ognevny** [comment]
> Include stdio.h for snprintf.

had the same thought. but why it's not failing for CLANG64?

**Comment by Biswa96** [comment]
> had the same thought. but why it's not failing for CLANG64?

clang and gcc both have their own standards.

**Comment by ognevny** [comment]
> clang and gcc both have their own standards.

but I set `CMAKE_C_COMPILER=clang` and `CMAKE_CXX_COMPILER=clang++`

**Comment by ognevny** [comment]
actually the headers weren't included in 1.4 tarball, but it's fixed after the release

**Comment by ognevny** [comment]
and now it fails on UCRT64
```
[804/804] Linking CXX executable bin\supertuxkart.exe
  FAILED: bin/supertuxkart.exe 
  C:\Windows\system32\cmd.exe /C "cd . && D:\M\msys64\ucrt64\bin\clang++.exe -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -std=gnu++0x -Wall -Wno-unused-function -O3 -DNDEBUG -pipe -Wl,--subsystem,windows @CMakeFiles\supertuxkart.rsp -o bin\supertuxkart.exe -Wl,--out-implib,libsupertuxkart.dll.a -Wl,--major-image-version,0,--minor-image-version,0 && cd ."
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.obj:irr_driver.cpp:(.text+0x632): undefined reference to `__imp_createDeviceEx'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.obj:irr_driver.cpp:(.text+0x1e4a): undefined reference to `__imp_createDeviceEx'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.obj:irr_driver.cpp:(.text+0x1f86): undefined reference to `__imp_createDevice'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.obj:irr_driver.cpp:(.text+0x21a2): undefined reference to `__imp_createDeviceEx'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/light.cpp.obj:light.cpp:(.text$_ZN3irr5scene10ISceneNode11getMaterialEj[_ZN3irr5scene10ISceneNode11getMaterialEj]+0x3): undefined reference to `__imp__ZN3irr5video16IdentityMaterialE'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/referee.cpp.obj:referee.cpp:(.text+0x1218): undefined reference to `__imp__ZN3irr4core14IdentityMatrixE'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/referee.cpp.obj:referee.cpp:(.text+0x1224): undefined reference to `__imp__ZN3irr4core14IdentityMatrixE'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/slip_stream.cpp.obj:slip_stream.cpp:(.text+0x66d): undefined reference to `__imp__ZN3irr4core14IdentityMatrixE'
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/slip_stream.cpp.obj:slip_stream.cpp:(.text+0x679): undefined reference to `__imp__ZN3irr4core14IdentityMatrixE'
  
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/slip_stream.cpp.obj:slip_stream.cpp:(.text+0xb32): undefined reference to `__imp__ZN3irr4core14IdentityMatrixE'
  
  D:/M/msys64/ucrt64/bin/ld: CMakeFiles/supertuxkart.dir/src/graphics/slip_stream.cpp.obj:slip_stream.cpp:(.text+0xb3e): more undefined references to `__imp__ZN3irr4core14IdentityMatrixE' follow
  
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ognevny** [comment]
how to deal with https://github.com/msys2/MINGW-packages/actions/runs/8590745303/job/23538667024#step:11:1545 ? looks like that's because of lots of vendored deps there

**Comment by Biswa96** [comment]
Why are you using clang in makedepends?

**Comment by ognevny** [comment]
> Why are you using clang in makedepends? 

it failed woth gcc+ld (mainly because of ld errors)

**Comment by ognevny** [comment]
I also tried to push a change to use a system bullet, but upstream maintainers don't recommend to do this: https://github.com/supertuxkart/stk-code/issues/5035#issuecomment-2005581607

**Comment by ognevny** [comment]
UCRT64 fails to run 'story mode'. I'll try to rebuild it with clang

**Comment by ognevny** [comment]
> UCRT64 fails to run 'story mode'. I'll try to rebuild it with clang

now it works

I'm not sure if it works on CLANGARM64, so let's try it

**Pull request merged**
