### PR TITLE
wasm-bindgen: update lock file

### PR DESCRIPTION
**Pull request by lazka**
link upstream issue re missing lock file

because github complains that it contains outdated dependencies, but the relevant packages can't be updated, so this wont help.

But update anyway while I'm already at it.

### CODE REVIEW

**Comment by lazka** [comment]
@ognevny ok?

**Comment by ognevny** [comment]
> because github complains that it contains outdated dependencies, but the relevant packages can't be updated, so this wont help.

where I can see such logs?

**Comment by ognevny** [comment]
> @ognevny ok?

ok anyway

**Comment by lazka** [comment]
image

**Pull request merged**
