### PR TITLE
python-lazy-loader: new package, update scikit-image

### PR DESCRIPTION
**Pull request by kmilos**
Required for updating scikit-image and other "scientific Python" libraries: https://scientific-python.org/specs/

See also https://aur.archlinux.org/packages/python-lazy-loader

### CODE REVIEW

**Comment by kmilos** [comment]
Need to remove the .dll.a implibs somehow, or patch meson commands somewhere to build modules rather than shared libs... Any suggestions are welcome.

**Comment by kmilos** [comment]
@lazka Still need to remove all the .dll.a implibs from the scikit-image package!

**Comment by lazka** [comment]
But they don't hurt, right?

**Comment by kmilos** [comment]
> Should we report it upstream?

No side-effects, no, just wasteful/ugly.

> Should we report it upstream?

Don't know who's to blame here for shared_library() vs shared_module() - meson-python, or the scikit-image package itself, or a somewhere else?

**Comment by lazka** [comment]
In pycairo I use this https://github.com/pygobject/pycairo/blob/64058391b37957f719246c2e8c51997ca10f73ac/cairo/meson.build#L75 which doesn't seem to create it.

**Comment by kmilos** [comment]
This is from scikit-image:

https://github.com/scikit-image/scikit-image/blob/441fe68b95a86d4ae2a351311a0c39a4232b6521/skimage/_shared/meson.build

Can't really tell what's different...

**Comment by lazka** [comment]
Oops, I was wrong, we delete it here too: https://github.com/msys2/MINGW-packages/blob/1c6698776a7c9bc984c564afe90adb4d3f24b2b2/mingw-w64-pycairo/PKGBUILD#L51

**Comment by kmilos** [comment]
Will you add this than as well please before it hits staging?

**Comment by kmilos** [comment]
And I guess this should now be reported as a meson bug on https://mesonbuild.com/Python-module.html#extension_module ?

**Comment by lazka** [comment]
Yeah

**Comment by lazka** [comment]
> Will you add this than as well please before it hits staging?

ok d76c50eb43c06663

**Comment by kmilos** [comment]
> Yeah

Done.

**Pull request merged**
