### PR TITLE
xerces-c: fix pc file

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by Biswa96** [comment]
IMO, a patch file would be better instead of sed.

**Comment by lazka** [comment]
What does this fix for example?

**Comment by raedrizqie** [comment]
> What does this fix for example?

preparing for gdal & maybe cegui.. gdal only assume xerces libs as `-lxerces -lpthread` but it actually depends on `icu` too.

**Comment by lazka** [comment]
hm, weird that this only happens with clang and only on Windows...

**Comment by raedrizqie** [comment]
> hm, weird that this only happens with clang and only on Windows...

i will test linking gdal with xerces-c without icu.. if it compiles, then this PR can be closed

**Comment by MehdiChinoune** [comment]
The issue with xerces on clang is in #9804

**Pull request closed without merging**
