### PR TITLE
mingw-w64-directxmath - Fix for cpuid.h being used instead of intrin.h.

### PR DESCRIPTION
**Pull request by JPeterMugaas**
This could effect things besides DirectxTex.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
I think clang will start support cpuid.h with 18.x

**Comment by MehdiChinoune** [comment]
It looks like It was supported before GCC-11 https://github.com/mingw-w64/mingw-w64/commit/d2374f898457b0f4ea8bd4084a94f2dafc87a99a

**Comment by lazka** [comment]
What does this fix and should it be reported upstream?

**Comment by MehdiChinoune** [comment]
> What does this fix and should it be reported upstream?

Fix #19609

**Comment by JPeterMugaas** [comment]
I have reported the issue upstream.  See: https://github.com/microsoft/DirectXMath/pull/176 .

**Pull request merged**
