### PR TITLE
ccache: Update to 4.2.1

### PR DESCRIPTION
**Pull request by lazka**
@peterbud do you know what `01-directory-separator.patch` fixed? See https://github.com/msys2/MINGW-packages/pull/3477 It doesn't apply and it's not straight forward to rebase without understanding the issue.

I tried your steps in #3039 but they "fail" before and after this change: fail, in that if you set CCACHE_BASEDIR you get a miss, but also get a hit if you do it again.

(if anyone wonders: build with ninja is broken)

### CODE REVIEW

**Comment by peterbud** [comment]
Hi @lazka - I'm not following closely ccache development anymore, but I have seen that version 4 is a major re-write, and also I have seen a more active Windows development on the project. In the past the windows version failed in many test cases due to the way it handled or not handled directory separators (like backward and forward slashes), and the patch meant to fix those shortcomings. Honestly, my best advice would be to go without the patch, and see where the tests are failing.

**Comment by lazka** [comment]
Sounds good, thanks!

**Comment by lazka** [comment]
unittests are passing, but the new test system seems linux specific and doesn't really work.. :/

**Comment by lazka** [comment]
hm, this broke ccache on 32bit.. Not output, just doesn't do anything and returns "3"

**Pull request merged**
