### PR TITLE
gstreamer: Update to 1.18.0

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by Biswa96** [comment]
What is the error? Any pkgbuild sample?

**Comment by lazka** [comment]
fixed it :)

like still dependencies missing..

**Comment by Biswa96** [comment]
`glslc` program is provided by `shaderc` package in ArchLinux, see https://www.archlinux.org/packages/extra/x86_64/shaderc/

**Comment by lazka** [comment]
I've created #6961

**Pull request merged**
