### PR TITLE
virglrenderer: update to 0.10.4

### PR DESCRIPTION
**Pull request by heljkon**
Download updated patch.
Adjust script.

### CODE REVIEW

**Comment by heljkon** [comment]
**I'm unsure, if this PR should be merged, but I don't see a way to turn it into a draft!**

To succeed with MINGW32 I had to remove a rather sensible Flag from meson.build: -Werror=incompatible-pointer-types

I found no way to succeed with CLANG32, so I disabled this architecture. CI failed with:
```
2023-08-17T06:25:13.1895923Z FAILED: src/libvirgl.a.p/vrend_renderer.c.obj 
2023-08-17T06:25:13.2674763Z "clang" "-Isrc/libvirgl.a.p" "-Isrc" "-I../src" "-I../src/gallium/include" "-I../src/gallium/auxiliary" "-I../src/gallium/auxiliary/util" "-I." "-I.." "-I../src/venus" "-I../src/drm" "-I../src/dr
m/drm-uapi" "-Isrc/mesa" "-I../src/mesa" "-I../src/mesa/compat" "-I../src/mesa/pipe" "-I../src/mesa/util" "-fcolor-diagnostics" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wextra" "-Wpedantic" "-std=gnu11" 
"-O3" "-Werror=implicit-function-declaration" "-Werror=missing-prototypes" "-Wmissing-prototypes" "-Werror=incompatible-pointer-types" "-Werror=int-to-pointer-cast" "-Wno-unused-parameter" "-Wno-overlength-strings" "-fvisibi
lity=hidden" "-imacros" "C:/_/B/src/virglrenderer-0.10.4/build/config.h" "-DHAVE_CONFIG_H=1" "-march=pentium4" "-mtune=generic" "-O2" "-pipe" "-Wp,-D_FORTIFY_SOURCE=2" "-fstack-protector-strong" "-D__USE_MINGW_ANSI_STDIO=1" 
"-pthread" -MD -MQ src/libvirgl.a.p/vrend_renderer.c.obj -MF "src/libvirgl.a.p/vrend_renderer.c.obj.d" -o src/libvirgl.a.p/vrend_renderer.c.obj "-c" ../sr
c/vrend_renderer.c
2023-08-17T06:25:13.2834857Z In file included from ../src/vrend_renderer.c:40:
2023-08-17T06:25:13.2840962Z In file included from ../src/mesa/util/u_thread.h:35:
2023-08-17T06:25:13.2896196Z In file included from ../src/mesa/compat/c11/threads.h:64:
2023-08-17T06:25:13.2897414Z ../src/mesa/compat/c11/threads_win32.h:176:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
2023-08-17T06:25:13.2898141Z static void impl_tss_dtor_invoke()
2023-08-17T06:25:13.2898650Z                                 ^
2023-08-17T06:25:13.2899121Z                                  void
2023-08-17T06:25:13.2900665Z ../src/vrend_renderer.c:7149:30: error: incompatible function pointer types passing 'void (GLenum, GLenum, GLuint, GLenum, GLsizei, const GLchar *, const void *)' (aka 'void (unsigned int, unsigned int, unsigned int, unsigned int, int, const char *, const void *)') to parameter of type 'GLDEBUGPROC' (aka 'void (*)(unsigned int, unsigned int, unsigned int, unsigned int, int, const char *, const void *) __attribute__((stdcall))') [-Wincompatible-function-pointer-types]
2023-08-17T06:25:13.2901827Z       glDebugMessageCallback(vrend_debug_cb, NULL);
2023-08-17T06:25:13.2902370Z                              ^~~~~~~~~~~~~~
2023-08-17T06:25:13.2903947Z ../src/vrend_renderer.c:12084:30: error: incompatible function pointer types passing 'void (GLenum, GLenum, GLuint, GLenum, GLsizei, const GLchar *, const void *)' (aka 'void (unsigned int, unsigned int, unsigned int, unsigned int, int, const char *, const void *)') to parameter of type 'GLDEBUGPROC' (aka 'void (*)(unsigned int, unsigned int, unsigned int, unsigned int, int, const char *, const void *) __attribute__((stdcall))') [-Wincompatible-function-pointer-types]
2023-08-17T06:25:13.2904891Z 
2023-08-17T06:25:13.2905276Z       glDebugMessageCallback(vrend_debug_cb, NULL);
2023-08-17T06:25:13.2905672Z 
2023-08-17T06:25:13.2905987Z                              ^~~~~~~~~~~~~~
2023-08-17T06:25:13.2906338Z 
2023-08-17T06:25:13.2906662Z 1 warning and 2 errors generated.
2023-08-17T06:25:13.2907017Z 
2023-08-17T06:25:13.2907395Z [41/45] Compiling C object src/libvirgl.a.p/vrend_winsys.c.obj
2023-08-17T06:25:14.6010972Z [42/45] Compiling C object src/libvirgl.a.p/vrend_shader.c.obj
2023-08-17T06:25:14.6011668Z ninja: build stopped: subcommand failed.
2023-08-17T06:25:14.6635185Z ==> ERROR: A failure occurred in build().
2023-08-17T06:25:14.6920576Z     Aborting...
```

**Comment by raedrizqie** [comment]
just add `-Wno-incompatible-function-pointer-types` for clang?

**Comment by mmuetzel** [comment]
`vrend_debug_cb` is probably missing the `stdcall` attribute for 32-bit Windows. Just ignoring the warning/error is probably not the best solution.

**Comment by heljkon** [comment]
I skipped modifying the compiler flags.

The errors occured on activating the debug callback for 32bit archs. After removal of these code blocks, the builds succeed.

**Comment by raedrizqie** [comment]
instead of explicitly disable the code, maybe we can guard those with:
```
if (VREND_DEBUG_ENABLED && vrend_debug(...
```

**Comment by Biswa96** [comment]
> `vrend_debug_cb` is probably missing the `stdcall` attribute for 32-bit Windows. Just ignoring the warning/error is probably not the best solution.

Please try this patch.

```diff
--- src/vrend_renderer.c.
+++ src/vrend_renderer.c
@@ -6985,7 +6985,7 @@
    }
 }
 
-static void vrend_debug_cb(UNUSED GLenum source, GLenum type, UNUSED GLuint id,
+static void APIENTRY vrend_debug_cb(UNUSED GLenum source, GLenum type, UNUSED GLuint id,
                            UNUSED GLenum severity, UNUSED GLsizei length,
                            UNUSED const GLchar* message, UNUSED const void* userParam)
 {
```

**Comment by heljkon** [comment]
@Biswa96 Nice one!

**Pull request merged**
