### PR TITLE
Add mingw-w64-julia package

### PR DESCRIPTION
**Pull request by smalltalkman**
Try to compile julia under msys2.

### CODE REVIEW

**Comment by smalltalkman** [comment]
After recompiling `mingw-w64-lapack`, `julia` can be successfully compiled under `msys2`. Contains `32-bit` and `64-bit`.

**Comment by Alexpux** [comment]
@smalltalkman probably you need add libutf8proc to dependencies?

**Comment by smalltalkman** [comment]
@Alexpux Currently `julia` downloads and compiles `utf8proc` and `openlibm`, and later considers `utf8proc` and `openlibm` provided by `msys2`.

**Comment by Alexpux** [comment]
@smalltalkman in current state I dont want to publish julia language because it install many libraries that similar to our own:

````
$ ls -l /scripts/mingw-w64-julia/pkg/mingw-w64-x86_64-julia/mingw64/bin
-rwxr-xr-x 1 Alexx None    25668 авг  5 09:21 BugpointPasses.dll
-rwxr-xr-x 1 Alexx None   253661 авг  5 09:21 julia.exe
-rwxr-xr-x 1 Alexx None    59147 авг  5 09:21 libccalltest.dll
-rwxr-xr-x 1 Alexx None    49208 авг  5 09:21 libdSFMT.dll
-rwxr-xr-x 1 Alexx None   485419 авг  5 09:21 libgmp.dll
-rwxr-xr-x 1 Alexx None  2618414 авг  5 09:21 libjulia.dll
-rwxr-xr-x 1 Alexx None    21141 авг  5 09:21 libllvmcalltest.dll
-rwxr-xr-x 1 Alexx None   448751 авг  5 09:21 libmpfr.dll
-rwxr-xr-x 1 Alexx None   199998 авг  5 09:21 libopenlibm.dll
-rwxr-xr-x 1 Alexx None   590757 авг  5 09:21 libpcre2-8.dll
-rwxr-xr-x 1 Alexx None    42916 авг  5 09:21 libpcre2-posix.dll
-rwxr-xr-x 1 Alexx None    17509 авг  5 09:21 libsuitesparse_wrapper.dll
-rwxr-xr-x 1 Alexx None   271030 авг  5 09:21 libuv-2.dll
-rwxr-xr-x 1 Alexx None 41689348 авг  5 09:21 LLVM.dll
-rwxr-xr-x 1 Alexx None    21851 авг  5 09:21 LLVMHello.dll
-rwxr-xr-x 1 Alexx None   113525 авг  5 09:21 LTO.dll
````

Julia must use out own gmp, pcre2, mpfr, llvm or link it statically to not install them

**Comment by vchuravy** [comment]
I would also recommend submitting these patches upstream.

**Pull request merged**
