### PR TITLE
mpv: Build with MINGW python, perl and winpty

### PR DESCRIPTION
**Pull request by MehdiChinoune**
@stahta01 your turn #11961

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
@stahta01 Please show where msys python is used here.

**Comment by stahta01** [comment]
> @stahta01 Please show where msys python is used here.

Please read the first line of the waf file

**Comment by MehdiChinoune** [comment]
> > @stahta01 Please show where msys python is used here.
> 
> Please read the first line of the waf file

msys2 python is not installed!

**Comment by stahta01** [comment]
> > > @stahta01 Please show where msys python is used here.
> > 
> > 
> > Please read the first line of the waf file
> 
> which waf file are you talking about? msys2 python is not installed!

Please delete the waflib so you can do a real comparison

**Comment by MehdiChinoune** [comment]
> > > > @stahta01 Please show where msys python is used here.
> > > 
> > > 
> > > Please read the first line of the waf file
> > 
> > 
> > which waf file are you talking about? msys2 python is not installed!
> 
> Please delete the waflib so you can do a real comparison

No, show me first where myss2 python is used.
msys2 python is not installed, do you understand that!
waf is using mingw python to build.

**Comment by stahta01** [comment]
> > > > > @stahta01 Please show where msys python is used here.
> > > > 
> > > > 
> > > > Please read the first line of the waf file
> > > 
> > > 
> > > which waf file are you talking about? msys2 python is not installed!
> > 
> > 
> > Please delete the waflib so you can do a real comparison
> 
> what waflib?
> 
> No, show me first where myss2 python is used. msys2 python is not installed, do you understand that! waf is using mingw python to build.

source=("${_realname}-${pkgver}.tar.gz"::"https://github.com/mpv-player/${_realname}/archive/v${pkgver}.tar.gz")

**Pull request closed without merging**
