### PR TITLE
codelite: rebuild against new wxw packages

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by stahta01** [comment]
I saw this package failure and I am working to fix it by adding an wxWidgets 3.0 STL build; the error was likely triggered by the GCC compiler version upgrade. But, the error can likely be fixed by patching CodeLite to use an STL version of wxWidgets 3.0 like it does with 3.1. Likely be a lot of codelite patches needed.

**Comment by lazka** [comment]
There is an upstream fix: https://github.com/eranif/codelite/commit/1d57763c8a19b3 but it doesn't apply cleanly, so I gave up for now.

**Comment by stahta01** [comment]
I will try to manually apply the fix and see if it works by itself.

**Comment by stahta01** [comment]
See PR #12459

**Pull request closed without merging**
