### PR TITLE
ag: fix compilation with clang

### PR DESCRIPTION
**Pull request by neheb**
getpagesize() is needed.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by lazka** [comment]
Any idea why that is only a problem with clang?

**Comment by Biswa96** [comment]
In mingw and ucrt, the function is replaced with something like this `long long getpagesize() { return 0x1000 }`. Not sure where it comes from.

**Comment by neheb** [comment]
Wonder if that's a bug or if pagesise really doesn't differ between platforms.

**Comment by neheb** [comment]
anything else misisng here?

**Comment by lazka** [comment]
seems like GCC somehow injects it (??)

fine I guess

**Pull request merged**
