### PR TITLE
libirecovery + libidevicerestore: fix with clang64

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Still have no idea why libirecovery didn't fail compilation before this PR.

**Comment by jeremyd2019** [comment]
Probably libtool... it likes to not fail to build, but instead degrade to just building static libraries because Windows doesn't allow undefined symbols in DLLs

**Comment by Biswa96** [comment]
Is this patch in upstream?

**Comment by neheb** [comment]
No. Upstream's not that active.

**Pull request merged**
