### PR TITLE
rust: update to 1.67.0

### PR DESCRIPTION
**Pull request by filnet**
fixed upstream:
- `0009-build-gnullvm-targets-natively.patch`
- `0010-gnullvm-debuginfo-fix.patch`
- `0012-disable-miri.patch`

### CODE REVIEW

**Comment by filnet** [comment]
0009-build-gnullvm-targets-natively.patch fails to apply (on `*-clang-aarch64` only)

**Comment by MehdiChinoune** [comment]
@mati865 @jeremyd2019 Could you update the clang-aarch64 patch.

**Comment by jeremyd2019** [comment]
I think @mati865 said the cargo packages that were being patched would be updated in the next version, so hopefully that part of the patch will go away? 🤞

**Comment by mati865** [comment]
Yeah, they will indeed go away but I haven't had time yet to check if that day is today.

**Comment by jeremyd2019** [comment]
> fixed upstream:
> 
> * 0011-disable-uac-for-installer.patch

I think you meant 0010-gnullvm-debuginfo-fix.patch

<details>
<summary>Patch errors</summary>

```
-> Applying 0009-build-gnullvm-targets-natively.patch
  patching file compiler/rustc_llvm/build.rs
  patching file compiler/rustc_llvm/src/lib.rs
  Hunk #1 succeeded at 95 (offset 2 lines).
  patching file library/std/src/personality/gcc.rs
  Reversed (or previously applied) patch detected!  Skipping patch.
  1 out of 1 hunk ignored -- saving rejects to file library/std/src/personality/gcc.rs.rej
  patching file library/unwind/src/libunwind.rs
  Hunk #1 FAILED at 37.
  Hunk #2 FAILED at 90.
  Hunk #3 FAILED at 269.
  3 out of 3 hunks FAILED -- saving rejects to file library/unwind/src/libunwind.rs.rej
  patching file src/bootstrap/compile.rs
  Reversed (or previously applied) patch detected!  Skipping patch.
  1 out of 1 hunk ignored -- saving rejects to file src/bootstrap/compile.rs.rej
  patching file src/stage0.json
  Hunk #1 FAILED at 18.
  1 out of 1 hunk FAILED -- saving rejects to file src/stage0.json.rej
  patching file src/test/run-make-fulldeps/reproducible-build/Makefile
  Hunk #1 succeeded at 1 with fuzz 1.
  patching file src/test/run-make-fulldeps/use-extern-for-plugins/Makefile
  patching file vendor/psm/.cargo-checksum.json
  Hunk #1 FAILED at 1.
  1 out of 1 hunk FAILED -- saving rejects to file vendor/psm/.cargo-checksum.json.rej
  patching file vendor/psm/build.rs
  Reversed (or previously applied) patch detected!  Skipping patch.
  2 out of 2 hunks ignored -- saving rejects to file vendor/psm/build.rs.rej
  patching file vendor/psm/src/arch/aarch_aapcs64.s
  Reversed (or previously applied) patch detected!  Skipping patch.
  1 out of 1 hunk ignored -- saving rejects to file vendor/psm/src/arch/aarch_aapcs64.s.rej
  patching file vendor/windows-sys/.cargo-checksum.json
  Hunk #1 FAILED at 1.
  1 out of 1 hunk FAILED -- saving rejects to file vendor/windows-sys/.cargo-checksum.json.rej
  patching file vendor/windows-sys/Cargo.toml
  Hunk #1 succeeded at 352 with fuzz 2 (offset -369 lines).
  Hunk #2 succeeded at 379 with fuzz 2 (offset -366 lines).
  can't find file to patch at input line 223
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -urN rustc-1.64.0-src.orig/vendor/windows-sys-0.28.0/.cargo-checksum.json rustc-1.64.0-src/vendor/windows-sys-0.28.0/.cargo-checksum.json
  |--- rustc-1.64.0-src.orig/vendor/windows-sys-0.28.0/.cargo-checksum.json	2022-10-08 13:19:49.007689300 +0200
  |+++ rustc-1.64.0-src/vendor/windows-sys-0.28.0/.cargo-checksum.json	2022-10-09 15:51:25.665633900 +0200
  --------------------------
  File to patch: 
  Skip this patch? [y] 
  Skipping patch.
  1 out of 1 hunk ignored
  can't find file to patch at input line 229
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -urN rustc-1.64.0-src.orig/vendor/windows-sys-0.28.0/Cargo.toml rustc-1.64.0-src/vendor/windows-sys-0.28.0/Cargo.toml
  |--- rustc-1.64.0-src.orig/vendor/windows-sys-0.28.0/Cargo.toml	2022-10-08 13:19:49.008687500 +0200
  |+++ rustc-1.64.0-src/vendor/windows-sys-0.28.0/Cargo.toml	2022-10-09 13:25:29.112289200 +0200
  --------------------------
  File to patch: 
  Skip this patch? [y] 
  Skipping patch.
  2 out of 2 hunks ignored
  patching file vendor/windows_aarch64_msvc/.cargo-checksum.json
  Hunk #1 FAILED at 1.
  1 out of 1 hunk FAILED -- saving rejects to file vendor/windows_aarch64_msvc/.cargo-checksum.json.rej
  patching file vendor/windows_aarch64_msvc/build.rs
  can't find file to patch at input line 266
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -urN rustc-1.64.0-src.orig/vendor/windows_aarch64_msvc-0.28.0/.cargo-checksum.json rustc-1.64.0-src/vendor/windows_aarch64_msvc-0.28.0/.cargo-checksum.json
  |--- rustc-1.64.0-src.orig/vendor/windows_aarch64_msvc-0.28.0/.cargo-checksum.json	2022-10-08 13:19:47.237857800 +0200
  |+++ rustc-1.64.0-src/vendor/windows_aarch64_msvc-0.28.0/.cargo-checksum.json	2022-10-09 15:52:26.402594300 +0200
  --------------------------
  File to patch: 
  Skip this patch? [y] 
  Skipping patch.
  1 out of 1 hunk ignored
  can't find file to patch at input line 272
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -urN rustc-1.64.0-src.orig/vendor/windows_aarch64_msvc-0.28.0/build.rs rustc-1.64.0-src/vendor/windows_aarch64_msvc-0.28.0/build.rs
  |--- rustc-1.64.0-src.orig/vendor/windows_aarch64_msvc-0.28.0/build.rs	2022-10-08 13:19:47.238857200 +0200
  |+++ rustc-1.64.0-src/vendor/windows_aarch64_msvc-0.28.0/build.rs	2022-10-09 13:21:26.785[420](https://github.com/msys2-arm/MINGW-packages/actions/runs/4033261400/jobs/6933663400#step:11:421)900 +0200
  --------------------------
  File to patch: 
  Skip this patch? [y] 
  Skipping patch.
  1 out of 1 hunk ignored
  patching file vendor/windows_x86_64_msvc/.cargo-checksum.json
  Hunk #1 FAILED at 1.
  1 out of 1 hunk FAILED -- saving rejects to file vendor/windows_x86_64_msvc/.cargo-checksum.json.rej
  patching file vendor/windows_x86_64_msvc/build.rs
  can't find file to patch at input line 299
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -urN rustc-1.64.0-src.orig/vendor/windows_x86_64_msvc-0.28.0/.cargo-checksum.json rustc-1.64.0-src/vendor/windows_x86_64_msvc-0.28.0/.cargo-checksum.json
  |--- rustc-1.64.0-src.orig/vendor/windows_x86_64_msvc-0.28.0/.cargo-checksum.json	2022-10-08 13:19:57.891556700 +0200
  |+++ rustc-1.64.0-src/vendor/windows_x86_64_msvc-0.28.0/.cargo-checksum.json	2022-10-09 16:22:38.503675300 +0200
  --------------------------
  File to patch: 
  Skip this patch? [y] 
  Skipping patch.
  1 out of 1 hunk ignored
  can't find file to patch at input line 305
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -urN rustc-1.64.0-src.orig/vendor/windows_x86_64_msvc-0.28.0/build.rs rustc-1.64.0-src/vendor/windows_x86_64_msvc-0.28.0/build.rs
  |--- rustc-1.64.0-src.orig/vendor/windows_x86_64_msvc-0.28.0/build.rs	2022-10-08 13:19:57.893563300 +0200
  |+++ rustc-1.64.0-src/vendor/windows_x86_64_msvc-0.28.0/build.rs	2022-10-09 16:22:14.366[449](https://github.com/msys2-arm/MINGW-packages/actions/runs/4033261400/jobs/6933663400#step:11:450)000 +0200
  --------------------------
  File to patch: 
  Skip this patch? [y] 
  Skipping patch.
  1 out of 1 hunk ignored
```
</details>

**Comment by jeremyd2019** [comment]
Everything seems to be accounted for except for the removal of m68k, though some of that windows msvc stuff was confusing (there are now windows gnullvm directories there, so I assume it's taken care of).  I'm going to try building without that patch altogether.

**Comment by jeremyd2019** [comment]
https://github.com/msys2-arm/MINGW-packages/actions/runs/4033513581/jobs/6934091625 succeeded building rust on clangarm64 without that patch.  I never did understand why disabling m68k should have had any effect, maybe @mati865 does, but it did build without disabling, so it may have been a cross-compilation thing?

**Comment by filnet** [comment]
I'll remove the patch then and fix the commit log to mention the correct removed patch.

**Comment by mati865** [comment]
> [msys2-arm/MINGW-packages/actions/runs/4033513581/jobs/6934091625](https://github.com/msys2-arm/MINGW-packages/actions/runs/4033513581/jobs/6934091625) succeeded building rust on clangarm64 without that patch. I never did understand why disabling m68k should have had any effect, maybe @mati865 does, but it did build without disabling, so it may have been a cross-compilation thing?
> 
> Anyway, I think that patch can just be removed now.

There used to be an error when linking LLVM (only when building with Clang+LLD) where m68k symbols were conflicting with some other target. It's fixed now so the patch is unnecessary.

> though some of that windows msvc stuff was confusing (there are now windows gnullvm directories there, so I assume it's taken care of)

Yeah, that was a hack to use msvc libs during absence of gnullvm libs.

**Review by jeremyd2019 — APPROVED** [review]
LGTM

**Pull request merged**
