### PR TITLE
Add ffmpeg4.4

### PR DESCRIPTION
**Pull request by lazka**
The goal of this package is to provide ffmpeg 4.4.x and not conflict with ffmpeg 5.x etc.

Compared to the current 4.4 package this removes the frei0r-plugins dependency, since there is a dep cycle via frei0r-plugins -> opencv

edit:

```
# for packages switching to this:
depends=("${MINGW_PACKAGE_PREFIX}-ffmpeg4.4")
export PKG_CONFIG_PATH="${MINGW_PREFIX}/lib/ffmpeg4.4/pkgconfig:$PKG_CONFIG_PATH"
```

### CODE REVIEW

**Comment by wszqkzqk** [comment]
May we make a list of the packages depend on ffmpeg4.4? Thus others can use ffmpeg5.

**Comment by lazka** [comment]
I was planning to follow https://github.com/msys2/MINGW-packages/issues/10725#issuecomment-1363351829, but the 4.4 packages there take very long to build, so I'm going to test with vlc first. Not today though.

**Comment by wszqkzqk** [comment]
> I was planning to follow [#10725 (comment)](https://github.com/msys2/MINGW-packages/issues/10725#issuecomment-1363351829), but the 4.4 packages there take very long to build, so I'm going to test with vlc first. Not today though.

Can we refer to archlinux?
[ffmpeg4.4](https://archlinux.org/packages/extra/x86_64/ffmpeg4.4/)
[ffmpeg5](https://archlinux.org/packages/extra/x86_64/ffmpeg/)

[The note of archlinux's vlc package](https://github.com/archlinux/svntogit-packages/blob/packages/vlc/trunk/PKGBUILD#L16)

**Comment by wszqkzqk** [comment]
> > I was planning to follow [#10725 (comment)](https://github.com/msys2/MINGW-packages/issues/10725#issuecomment-1363351829), but the 4.4 packages there take very long to build, so I'm going to test with vlc first. Not today though.
> 
> Can we refer to archlinux? [ffmpeg4.4](https://archlinux.org/packages/extra/x86_64/ffmpeg4.4/) [ffmpeg5](https://archlinux.org/packages/extra/x86_64/ffmpeg/)
> 
> [The note of archlinux's vlc package](https://github.com/archlinux/svntogit-packages/blob/packages/vlc/trunk/PKGBUILD#L16)

Arch Linux's VLC denpend on `ffmpeg4.4` duo to vaapi, which is unavailable in windows, so we may have a try.

**Comment by lazka** [comment]
I did a bit of cleanup in #15760 and synced that in here.

> Arch Linux's VLC denpend on `ffmpeg4.4` duo to vaapi, which is unavailable in windows, so we may have a try.

It is supported in theory, see https://packages.msys2.org/base/mingw-w64-libva and https://devblogs.microsoft.com/directx/video-acceleration-api-va-api-now-available-on-windows/, but we don't used it in ffmpeg, yeah. I'm just using VLC as a test to see if linking works and there are no cycles.

**Comment by lazka** [comment]
pkgconf relocation is broken with the .pc files being in a subdirectory

**Comment by lazka** [comment]
Yay.. It worked

**Pull request merged**
