### PR TITLE
libimagequant: update to 4.0.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Since It builds with rust => No clang32 or clangarm64.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I wish projects would have a little consideration for those of us who can't manage to get rust to work properly, rather than pulling the rug out from under us and the other packages that already took them as a dependency when they could be built.

Are we going to have to go the librsvg route and package an old version for the rust-free prefixes?

**Comment by MehdiChinoune** [comment]
python-pyopenssl 22.0.0, It requires python-cryptography>=36.0 which requires rust to build.
Many other Python packages depend on one of them

**Comment by jeremyd2019** [comment]
Luckily it looks like @mati865 has been busy and might be making progress with rust upstream ❤️

**Comment by lazka** [comment]
Should we wait a bit with this then?

**Pull request closed without merging**
