### PR TITLE
mesa: Update to 22.3.3

### PR DESCRIPTION
**Pull request by pal1000**

### CODE REVIEW

**Comment by pal1000** [comment]
I don't know what's wrong. I didn't have problems with MSYS2 MinGW-W64 build [here](https://github.com/pal1000/mesa-dist-win/releases/tag/22.3.3).

**Comment by driver1998** [comment]
The dzn build failure on clang is fixed on https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20676, you can apply the patch if you want.

Not sure about what happened on autobuild right now though.

**Comment by pal1000** [comment]
These build issues look like some flaking problem.

**Comment by lazka** [comment]
Likely because https://github.com/actions/toolkit/issues/1311 unsets the MSYS env var we set in CI

**Pull request merged**
