### PR TITLE
gcc-git: Fix 0016-Ensure-lmsvcrt-precede-lkernel32.patch

### PR DESCRIPTION
**Pull request by lhmouse**
Signed-off-by: Liu Hao <lh_mouse@126.com>

### CODE REVIEW

**Comment by Alexpux** [comment]
@lhmouse after rebuilding GCC 32-bit libstdc++ dont export anymore smbols
````
__emutls_v._ZSt11__once_call
__emutls_v._ZSt15__once_callable
````
So it lead to mostly not working many 32 bit packages. Do you know why it happen?

**Comment by Alexpux** [comment]
64-bit libstdc++ still provide this symbols

**Comment by mati865** [comment]
@Alexpux probably `_GLIBCXX_HAVE_TLS` is no longer defined to `1`?
```
$ grep _GLIBCXX_HAVE_TLS /mingw32/include/c++/10.1.0/i686-w64-mingw32/bits/c++config.h
#define _GLIBCXX_HAVE_TLS 1
```

**Comment by Alexpux** [comment]
But for what reason and only for 32 bit?

**Comment by mati865** [comment]
GCC build system is a mess, maybe one of checks started failing somehow.

**Comment by lhmouse** [comment]
@mati865  I get this instead, without this patch:

```
lh_mouse@lhmouse-pc ~ $ grep _GLIBCXX_HAVE_TLS /mingw32/include/c++/10.1.1/i686-w64-mingw32/bits/c++config.h
/* #undef _GLIBCXX_HAVE_TLS */
lh_mouse@lhmouse-pc ~ $ grep _GLIBCXX_HAVE_TLS /mingw64/include/c++/10.1.1/x86_64-w64-mingw32/bits/c++config.h
/* #undef _GLIBCXX_HAVE_TLS */
```
what's the difference?

**Comment by mati865** [comment]
@lhmosue I haven't updated GCC for few days.
AFAIK `_GLIBCXX_HAVE_TLS` should be defined when using pthreads and not defined when using win32 threads (since GCC doesn't have full support for C++ then).

**Comment by Alexpux** [comment]
@lhmouse @mati865  probably here is failed test for TLS:
````
D:\msys64\mingw32\i686-w64-mingw32\bin\ld.exe: D:/msys64/mingw32/i686-w64-mingw32/lib\libmingwex.a(lib32_libmingwex_a-mingw_pformat.o): in function `_pformat_int':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_pformat.c:797: undefined reference to `__umoddi3'
collect2.exe: error: ld returned 1 exit status
````

**Comment by Alexpux** [comment]
64-bit libstdc++ have some more checks passed. Compare to 32-bit there are few other defines present in 64-bit:
````
#define _GLIBCXX_USE_INT128 1
#define HAVE__ISNANF 1
#define HAVE__FINITEF 1
#define HAVE_TLS 1
````

**Comment by lhmouse** [comment]
Probably this can be resolved by building a new **winpthreads** with `-D__USE_MINGW_ANSI_STDIO=0` so it uses MS `printf()` without referencing these routines.

**Comment by Alexpux** [comment]
@lhmouse why this fail only for 32 bit then?

**Comment by lhmouse** [comment]
@Alexpux x64 has hardware instruction for 128bit -> 64bit division (the `di` in `__umoddi3` suggests DI mode, which means **d**ouble-precision **i**nteger - 64 bits). It might be the mingw-w64 `printf` that uses 64-bit division. I haven't checked the source though.

**Comment by lhmouse** [comment]
This had better be done in winpthreads, but we had better test it first.

```diff
diff --git a/mingw-w64-libraries/winpthreads/Makefile.am b/mingw-w64-libraries/winpthreads/Makefile.am
index e674a35e..8a3b758c 100644
--- a/mingw-w64-libraries/winpthreads/Makefile.am
+++ b/mingw-w64-libraries/winpthreads/Makefile.am
@@ -7,7 +7,7 @@ ACLOCAL_AMFLAGS = -I m4
 lib_LTLIBRARIES = libwinpthread.la
 
 include_HEADERS = include/pthread.h include/sched.h include/semaphore.h include/pthread_unistd.h include/pthread_time.h include/pthread_compat.h include/pthread_signal.h
-libwinpthread_la_CPPFLAGS = -I$(srcdir)/include -DIN_WINPTHREAD -DWINPTHREAD_DBG=1
+libwinpthread_la_CPPFLAGS = -I$(srcdir)/include -DIN_WINPTHREAD -DWINPTHREAD_DBG=1 -D__USE_MINGW_ANSI_STDIO=0
 libwinpthread_la_LDFLAGS = -no-undefined -version-info 1:0:0 -L$(builddir)/fakelib -Wc,-no-pthread
 EXTRA_libwinpthread_la_DEPENDENCIES = fakelib/libgcc.a  fakelib/libgcc_eh.a  fakelib/libgcc_s.a
 libwinpthread_la_SOURCES = \
```

**Comment by Alexpux** [comment]
I will test

**Comment by Alexpux** [comment]
@lhmouse patch for wipthreads solve issue with GCC build

**Comment by lhmouse** [comment]
> @lhmouse patch for winpthreads solve issue with GCC build

Thanks. I will forward it to mingw-w64.

**Pull request merged**
