### PR TITLE
ccache: fix compilation with clang

### PR DESCRIPTION
**Pull request by neheb**
Disable testing as it has some linking problem.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
```
undefined reference to `__imp___imp__environ'
```

strange.

**Comment by jeremyd2019** [comment]
ccache: C:/_/M/mingw-w64-ccache/src/ccache-4.2.1/src/system.hpp:190:25: error: '__p__environ' redeclared without 'dllimport' attribute: previous 'dllimport' ignored [-Werror,-Winconsistent-dllimport]

I would check that file/line, I think it's doing something stupid there

**Comment by neheb** [comment]
That warning the patch fixes.

**Comment by jeremyd2019** [comment]
https://github.com/ccache/ccache/blob/master/src/system.hpp#L193
`DLLIMPORT extern char** environ;`

But, that shows that `environ` is actually a macro, so it expands into something unexpected

**Comment by jeremyd2019** [comment]
like `#define _environ (* __MINGW_IMP_SYMBOL(_environ))` and then `#define environ _environ`

**Comment by neheb** [comment]
??? seriously?

https://github.com/msys2/MINGW-packages/blob/f15a21c517454c8713ded54e7fc950d4b5cf8d2c/mingw-w64-ccache/010-clang.patch

this macro does not expand into anything as Visual C++ is not being used.

**Comment by jeremyd2019** [comment]
I'm talking about `environ` in mingw-w64... that's a macro, and may or may not expand into something that can be successfully used as a variable name.
such as
https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/stdlib.h#L323
and
https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/stdlib.h#L704

**Comment by neheb** [comment]
sounds like a bug.

Anyway, is there a macro to match against UCRT?

**Comment by jeremyd2019** [comment]
`_UCRT`  but in either (UCRT or MSVCRT) case environ doesn't need to be explicitly declared extern, just include stdlib.h

**Comment by jeremyd2019** [comment]
this patch works for me:
```diff
--- ccache-4.2.1/src/system.hpp.orig    2021-05-07 21:56:05.544685900 -0700
+++ ccache-4.2.1/src/system.hpp 2021-05-07 21:56:19.060320500 -0700
@@ -187,7 +187,9 @@
 #  define PATH_DELIM ":"
 #endif

+#ifndef environ
 DLLIMPORT extern char** environ;
+#endif

 // Work with silly DOS binary open.
 #ifndef O_BINARY
```

**Comment by neheb** [comment]
Builds now.

**Comment by lazka** [comment]
ccache 4 was broken under mingw32 so I had to revert it. rebase accordingly.

**Pull request merged**
