### PR TITLE
Adding openbabel

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by Alexpux** [comment]
We build shared versions in first place

**Comment by jeroen** [comment]
I couldn't get the shared build to work :/ The cmake script is not very good.

**Comment by Alexpux** [comment]
well then i leave this pull request open/ maybe will look on it later

**Comment by jeroen** [comment]
What about building both a shared and static version for some other cmake packages?

**Comment by Alexpux** [comment]
i dont want to build only static package. Our prefer method is shared linking. Static libs we provide if possible

**Comment by jeroen** [comment]
OK I'll have another try later, thank you.

**Comment by jeroen** [comment]
Hmm haven't seen this before, it now fails with:

```
CMake Error at cmake/modules/MacroEnsureVersion.cmake:76 (MATH):
  MATH cannot parse the expression: "gcc.exe (Rev2, Built by MSYS27*10000 +
  gcc.exe (Rev2, Built by MSYS23*100 + gcc.exe (Rev2, Built by MSYS20":
  syntax error, unexpected exp_NUMBER, expecting exp_CLOSEPARENT or exp_OR
  (31)
Call Stack (most recent call first):
  cmake/modules/MacroEnsureVersion.cmake:95 (NORMALIZE_VERSION)
  CMakeLists.txt:248 (macro_ensure_version)
```

**Comment by lazka** [comment]
Any news?

**Comment by lazka** [comment]
Feel free to create a new PR when you find some time. Closing for now.

**Pull request closed without merging**
