### PR TITLE
qt6-tools: Fix windeployqt searching for qmake instead of qmake6

### LINKED ISSUE #10018: [mingw-w64-qt6-tools] qmake missing
Some tools included in this package (like windeployqt) still require qmake at runtime for some reasons. I've reported the need to drop this requirement upstream :
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-97998.

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Fixes #10018

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
@Amphaal Could you verify if windeployqt is fixed, by installing the artifacts from https://github.com/msys2/MINGW-packages/actions/runs/1429342932

**Comment by Amphaal** [comment]
Will do asap ;)

**Comment by MehdiChinoune** [comment]
@Amphaal Any news?

**Comment by Amphaal** [comment]
Just got home, sorry for the delay.

`windeployqt-qt6.exe` now fetches all required dependencies, but fails at the end. Here is an example log with a project of mine :

```
$ windeployqt-qt6.exe build/out/SoundBuddy.exe 
E:\DEV\REPOS\feedtnz\build\out\SoundBuddy.exe 64 bit, release executable
Updating qicns.dll.
Updating qico.dll.
Updating qjp2.dll.
Updating qjpeg.dll.
Updating qmng.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/platforms.
Updating qwindows.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/styles.
Updating qwindowsvistastyle.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/tls.
Updating qcertonlybackend.dll.
Updating qopensslbackend.dll.
Direct dependencies: Qt6Core Qt6Gui Qt6Network Qt6WebSockets Qt6Widgets
All dependencies   : Qt6Core Qt6Gui Qt6Network Qt6WebSockets Qt6Widgets
To be deployed     : Qt6Core Qt6Gui Qt6Network Qt6Svg Qt6WebSockets Qt6Widgets
Updating Qt6Core.dll.
Updating Qt6Gui.dll.
Updating Qt6Network.dll.
Updating Qt6Svg.dll.
Updating Qt6WebSockets.dll.
Updating Qt6Widgets.dll.
Updating D3Dcompiler_47.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/iconengines.
Updating qsvgicon.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/imageformats.
Updating qgif.dll.
Updating qicns.dll.
Updating qico.dll.
Updating qjp2.dll.
Updating qjpeg.dll.
Updating qmng.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/platforms.
Updating qwindows.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/styles.
Updating qwindowsvistastyle.dll.
Creating directory E:/DEV/REPOS/feedtnz/build/out/tls.
Updating qcertonlybackend.dll.
Updating qopensslbackend.dll.
Updating qschannelbackend.dll.
Creating E:\DEV\REPOS\feedtnz\build\out\translations...
Creating qt_ar.qm...
CreateProcessW failed: Le fichier spÚcifiÚ est introuvable.
```

All dependencies are well copied, and the executable is portable and functionnal. 

image

**Comment by MehdiChinoune** [comment]
> Creating E:\DEV\REPOS\feedtnz\build\out\translations...
> Creating qt_ar.qm...
> CreateProcessW failed: Le fichier spÚcifiÚ est introuvable.
> ```
> 
> All dependencies are well copied, and the executable is portable and functionnal.
> 

You need to install qt6-translations.

**Comment by Amphaal** [comment]
`qt6-translations` is indeed well installed :(

image

**Comment by MehdiChinoune** [comment]
@Amphaal I have pushed new changes, consider testing the packages from https://github.com/msys2/MINGW-packages/actions/runs/1435945664 after the building complete.

**Comment by Amphaal** [comment]
I've had suspected some kind of additional fix needed regarding `lupdate `/ `lrelease `/ `lconvert` invocation, but did not manage to find it... well done ! Testing this as soon as the artifacts are available ;)

**Pull request merged**
