### PR TITLE
libraw: enable support for more formats

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
Do you really need this? upstream suggests to not enable it for security reasons.

**Comment by kmilos** [comment]
The additional code paths are less tested indeed... There is no burning issue, i.e. no report that a user is missing support for a Sigma camera etc., so we could leave it as is until such moment.

**Comment by lazka** [comment]
ok, I'd rather not then. OK with my change?

**Comment by kmilos** [comment]
Sure

**Pull request merged**
