### PR TITLE
Unicorn: Build new v2 RC versions

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
This may be used as a template whenever version 2 will get finally released. Meanwhile I would like to gather feedback from the msys2 project on how should I improve my contribution for it to get accepted :)

Thanks!

### CODE REVIEW

**Comment by Biswa96** [comment]
Thank you for the contribution. Please follow this [template PKGBUILD][1] to build packages using cmake and ninja build system.

[1]: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-tarball.sh

**Comment by antoniovazquezblanco** [comment]
I hope it looks a little bit better now.

**Comment by lazka** [comment]
looks good in general.

clang build fails (rebase to get a better error, we changed things recently):

```
ld.lld: error: undefined symbol: getpagesize
```

We had a similar issue in be5da1615761efb614589762a156 recently.

**Comment by antoniovazquezblanco** [comment]
Patch provided. Thanks!

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Pull request merged**
