### PR TITLE
Link LLVM dynamically

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/msys2/MINGW-packages/issues/4006

There is a problem however:
```
$ llvm-config --link-shared --cxxflags
-ID:\msys64\mingw64/include -std=c++14 -stdlib=libc++  -fno-exceptions -fno-rtti -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```
GCC doesn't understand `-stdlib=libc++` and will throw an error. So to link LLVM (and all related tools) dynamically at the very least we have to make GCC ignore `-stdlib`.

### CODE REVIEW

**Comment by Biswa96** [comment]
Shouldn't we have to wait for next release or so? Patches count is going up.

**Comment by mati865** [comment]
> Shouldn't we have to wait for next release or so? Patches count is going up.

That's true, 3 out of 5 patches added by this PR won't be necessary with LLVM 11.

**Comment by lazka** [comment]
Because I was wondering and looked it up: LLVM 11 will be out Aug 26, so in one month.

**Comment by mati865** [comment]
> LLVM 11 will be out Aug 26, so in one month

They have tendency to delay the release (it's not a bad thing though) so I'd expect it somewhere mid September.

**Comment by mati865** [comment]
LLVM 11 rc3 was released recently and is expected to be promoted as final without changes.
I'll work on LLVM 11 PR instead.

**Pull request closed without merging**
