### PR TITLE
openssl: update to 3.2.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
package-grokker shows nothing.

### CODE REVIEW

**Comment by r4sas** [comment]
I'm proposing to revert that update, because it has broken EdDSA: https://github.com/openssl/openssl/issues/23075

**Comment by Biswa96** [comment]
> I'm proposing to revert that update, because it has broken EdDSA

Would it be possible to wait for a fix in upstream?

**Comment by r4sas** [comment]
Today we release new version of i2pd, so msys2 repository build will be broken.

**Comment by MehdiChinoune** [comment]
If the current i2pd works, then there is no hurry to update.

**Comment by r4sas** [comment]
Okay, in that case do not merge PR's with i2pd updates with using this PR as blocker till further updates.

**Comment by orignal** [comment]
Use own EdDSA implementation with 3.2.0
https://github.com/PurpleI2P/i2pd/commit/0e98dd5c7049d79bdcdba341357c504e562eb61f

**Pull request merged**
