### PR TITLE
add mingw32 and mingw64 to mingw_arch in pkgbuild of mingw-w64-msgpac…

### PR DESCRIPTION
**Pull request by sgachoud**
add mingw32 and mingw64 to mingw_arch in pkgbuild of mingw-w64-msgpack-cxx

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you explain why those are needed?

**Comment by Biswa96** [comment]
> Uniformity, all my packages are installed with mingw64.

Please switch to ucrt64.

**Comment by sgachoud** [comment]
> > Uniformity, all my packages are installed with mingw64.
> 
> Please switch to ucrt64.

Why?

**Comment by Biswa96** [comment]
Default environment is switch from mingw64 to ucrt64 2 years ago https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt64

32 bit packages are being dropped https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages

There are many advantages in ucrt64 environment https://www.msys2.org/docs/environments/#msvcrt-vs-ucrt

**Comment by sgachoud** [comment]
Thank you!

**Pull request closed without merging**
