### PR TITLE
qemu: update to 5.1.0

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
@ZachBacon Would you like to test the whpx accel? It does not work with my old machine.

**Comment by Biswa96** [comment]
@ZachBacon Would you like to test the whpx accel? whpx does not work with my old machine. Overall qemu 5.1 is OK.

**Comment by ZachBacon** [comment]
@Biswa96 yeah, I'll test it this weekend.

**Comment by lazka** [comment]
Should we wait, or merge now?

**Comment by Biswa96** [comment]
Wait please 🥺

**Comment by ZachBacon** [comment]
@Biswa96 qemu-system-i386.exe -cpu Skylake-Client -hda ./ubuntu.img -cdrom ./MX-19.2_386.iso -accel whpx
Windows Hypervisor Platform accelerator is operational

I got a vm going on my end.

**Comment by Biswa96** [comment]
Can be merged now.

**Pull request merged**
