### PR TITLE
swi-prolog: update to 9.2.4

### PR DESCRIPTION
**Pull request by mgondan**
now includes the test suite, run with ?- test_installation.

### CODE REVIEW

**Comment by Biswa96** [comment]
Are those tests require for normal usage?

**Comment by lazka** [comment]
Looks like they are just installed tests: https://github.com/SWI-Prolog/swipl-devel/blob/c60103a2df235d6c52221576a6b531df67bbcbd6/doc/Testing.md?plain=1#L57

**Comment by mgondan** [comment]
Sorry for not responding earlier, but you found it out anyway. The tests are not strictly required---on the other hand, professional users will probably appreciate them.

**Comment by Biswa96** [comment]
> The tests are not strictly required---on the other hand, professional users will probably appreciate them.

I was wondering if tests should be in a separate package e.g. swi-prolog-tests or swi-prolog-data. As tests are not strictly required, not all users need them.

**Comment by mgondan** [comment]
Good point. I'll put them into a separate package (in the next release, if that is ok).

**Pull request merged**
