### PR TITLE
Add missing makedepend on libc++

### PR DESCRIPTION
**Pull request by mati865**

### CODE REVIEW

**Comment by mati865** [comment]
At least it reproduces....

**Comment by Biswa96** [comment]
pkgrel++

**Comment by mati865** [comment]
No idea how it happened but previously there was `/c  /Fo` and now there is one space less: `/c /Fo`.

> pkgrel++

Is is necessary? The build failed for both architectures.

**Comment by lazka** [comment]
> Is is necessary? The build failed for both architectures.

If this fixes things, yes, otherwise it wont rebuild.

**Comment by lazka** [comment]
unrelated question: has anyone tried building this with ninja?

**Comment by mati865** [comment]
> 
> 
> unrelated question: has anyone tried building this with ninja?

I often use Ninja for developing LLVM, it's way faster but as I said in https://github.com/msys2/MINGW-packages/pull/7116#issuecomment-711387675 we cannot use Ninja with monolithic package.

This comment still applies: https://github.com/msys2/MINGW-packages/pull/7157/files#diff-125e46f56c15d81bb2f9210bdcc4959baf788e9db4c0acfbff0148bf4416815dR251

**Comment by lazka** [comment]
Ah, I missed that comment, thanks.

**Comment by mati865** [comment]
> Ah, I missed that comment, thanks.

Not your fault, the comments are over the place here.

**Pull request merged**
