### PR TITLE
Remove lib3mf-1

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by Biswa96** [comment]
Why is this package being removed?

**Comment by MehdiChinoune** [comment]
> Why is this package being removed?

Because It's no longer needed (an orphan)

**Comment by Biswa96** [comment]
That does not mean it is not used anywhere.

The upstream project is in still in development. Some branches have new commits in https://github.com/3MFConsortium/lib3mf

ArchLinux mentioned is as a dependency of openscad, see https://archlinux.org/packages/community/x86_64/lib3mf-1/

**Comment by MehdiChinoune** [comment]
> That does not mean it is not used anywhere.
> 
> The upstream project is in still in development. Some branches have new commits in https://github.com/3MFConsortium/lib3mf
> 
> ArchLinux mentioned is as a dependency of openscad, see https://archlinux.org/packages/community/x86_64/lib3mf-1/

We have another package `lib3mf`.

**Comment by Biswa96** [comment]
I am not sure if lib3mf-1 and lib3mf can be used interchangeably. Maybe it's like openssl v1 vs v3.

**Comment by MehdiChinoune** [comment]
> I am not sure if lib3mf-1 and lib3mf can be used interchangeably. Maybe it's like openssl v1 vs v3.

We don't have any package requiring lib3mf-1, Isn't that enough to remove it?

**Comment by MehdiChinoune** [comment]
> The author of the PR #7430 mentioned that lib3mf-1 is required by openscad.

Ours doesn't

**Comment by Biswa96** [comment]
I would suggest to wait for other opinions. @lazka

**Comment by lazka** [comment]
openscad supports lib3mf 2.0 in the release we have: https://github.com/openscad/openscad/blob/master/RELEASE_NOTES.md

In Ubuntu 22.04 openscad is also the only reverse dependency, so that suggests there not many other users of the old library, so I think it is fine to drop it.

**Comment by Biswa96** [comment]
OK, thanks.

**Pull request merged**
