### PR TITLE
suitesparse: update to 6.0.2

### PR DESCRIPTION
**Pull request by MehdiChinoune**
- A Fortran Compiler is now required to build suitesparse (No CLANG32)
- Something wrong with either mpfr or gmp on GCC based envs, I tried to force linking to static gmp but still getting the same linking errors. Maybe #14146 could fix this issue!

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Buidling against #14146 succeeds.

**Comment by mmuetzel** [comment]
Regarding the new dependency on a Fortran compiler, it might help to revert this changeset:
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/70369da8d4aca602770331cd8f70f2147ee01f4a

IIUC, it only adds demos that aren't actually needed for the libraries.

**Comment by MehdiChinoune** [comment]
> Regarding the new dependency on a Fortran compiler, it might help to revert this changeset: [DrTimothyAldenDavis/SuiteSparse@70369da](https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/70369da8d4aca602770331cd8f70f2147ee01f4a)
> 
> IIUC, it only adds demos that aren't actually needed for the libraries.

Fortran listed in other components not just AMD.

**Comment by MehdiChinoune** [comment]
Building SPEX still fails with GCC based envs.

**Comment by mmuetzel** [comment]
> Building SPEX still fails with GCC based envs because of static mpfr.

Could that be an issue with the `.pc` files?

**Pull request merged**
