### PR TITLE
live-media: Update to 2021.02.11

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by Biswa96** [comment]
So many patches 🤯

**Comment by mingwandroid** [comment]
They all come from the VLC project. I can look into upstreaming them, but I assume the VLC project would do so if it were easy.

These patches are important. They add e.g. pkg-config support which VLC relies on to find livemedia555. With this done, we can support RTSP streams on MSYS2 (at least in VLC).

**Comment by lazka** [comment]
This installs lots of files to `/usr/local/` (see the CI output under [diff])

**Comment by mingwandroid** [comment]
> This installs lots of files to /usr/local/ (see the CI output under [diff])

Could this be made into a failure condition?

**Comment by mingwandroid** [comment]
@lazka I think that's fixed now. Thanks.

**Comment by mingwandroid** [comment]
Thanks!

**Pull request merged**
