### PR TITLE
libhandy: moved dll in MINGW_PREFIX/bin and upgrade to 0.0.8

### PR DESCRIPTION
**Pull request by tallero**
DLL now in ${MINGW_PREFIX}/lib

### CODE REVIEW

**Comment by lazka** [comment]
```
2018-12-31T19:52:54.2076990Z mv: cannot move '/d/a/1/s/mingw-w64-libhandy/pkg/mingw-w64-i686-libhandy/mingw32/lib/libhandy-0.0-0.dll' to '/d/a/1/s/mingw-w64-libhandy/pkg/mingw-w64-i686-libhandy/mingw32/bin/libhandy-0.0-0.dll': No such file or directory
```

you also need to increase pkgrel

**Comment by Alexpux** [comment]
@tallero it better to fix buil;d system to install dll in right folder instead doing it manually

**Comment by tallero** [comment]
@Alexpux @lazka pushed a fix upstream

https://source.puri.sm/Librem5/libhandy/merge_requests/196

waiting for merge

**Comment by Alexpux** [comment]
@tallero is the fix in 0.0.7 version?

**Comment by tallero** [comment]
@Alexpux the fix has been integrated after the 0.0.7 release. I did not know if it would be fine targeting a specific commit so I was waiting for 0.0.8.
Here is the [commit](b6ed4a7373ab436931c804596c2997680714b88d).

**Comment by tallero** [comment]
@Alexpux now everything should be alright and ready for merging.

**Pull request merged**
