### PR TITLE
lis: update sha256sums and enable complex

### PR DESCRIPTION
**Pull request by MehdiChinoune**
They reuploaded the same file on 18/11!

### CODE REVIEW

**Comment by Biswa96** [comment]
Just asking. Do you change SHA checksums manually instead of using `updpkgsums` command?

**Comment by MehdiChinoune** [comment]
> Just asking. Do you change SHA checksums manually instead of using `updpkgsums` command?

Yes, I never use `updpkgsums`

**Comment by lazka** [comment]
> They reuploaded the same file on 18/11!

They are doing this all the time :/ https://github.com/anishida/lis/issues/29

**Comment by lazka** [comment]
> Yes, I never use `updpkgsums`

You should give it a try :)

**Pull request merged**
