### PR TITLE
blender: update to 2.93.9

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Need some testing, It does not work for me.
It doesn't respond when I try to do anything with, It does show `tools`.
when launched from shell it shows hundreds of messages about not loading elements.

**Comment by Biswa96** [comment]
I have tested the mingw64 package. It's working in my Windows 10 system. I am not familiar with Blender. If you need anything specific to test I can try.

**Comment by MehdiChinoune** [comment]
I got these messages:
```
$ blender
Bundled Python not found and is expected on this platform (the 'install' target may have not been built)
Traceback (most recent call last):
  File "D:/Programs\msys64_test\clang64\share\blender\2.93\scripts\modules/bpy/__init__.py", line 79, in <module>
    main()
  File "D:/Programs\msys64_test\clang64\share\blender\2.93\scripts\modules/bpy/__init__.py", line 62, in main
    join(utils.user_resource('SCRIPTS'), "addons", "modules"),
  File "D:/Programs\msys64_test\clang64\share\blender\2.93\scripts\modules/bpy/utils/__init__.py", line 730, in user_resource
    target_path = _user_resource(resource_type, path)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 29: invalid continuation byte
Error: dropbox with unknown operator: WM_OT_drop_blend_file
Python: Traceback (most recent call last):
  File "D:/Programs\msys64_test\clang64\share\blender\2.93\scripts\modules/bpy/__init__.py", line 79, in <module>
    main()
  File "D:/Programs\msys64_test\clang64\share\blender\2.93\scripts\modules/bpy/__init__.py", line 62, in main
    join(utils.user_resource('SCRIPTS'), "addons", "modules"),
  File "D:/Programs\msys64_test\clang64\share\blender\2.93\scripts\modules/bpy/utils/__init__.py", line 730, in user_resource
    target_path = _user_resource(resource_type, path)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 29: invalid continuation byte

location: <unknown location>:-1
WARN (wm.keymap): D:/dev/MINGW-packages/mingw-w64-blender/src/blender-2.93.9/source/blender/windowmanager/intern/wm_keymap.c:464 WM_keymap_poll: empty keymap 'Grease Pencil'
WARN (wm.keymap): D:/dev/MINGW-packages/mingw-w64-blender/src/blender-2.93.9/source/blender/windowmanager/intern/wm_keymap.c:464 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Curve Edit Mode'
WARN (wm.keymap): D:/dev/MINGW-packages/mingw-w64-blender/src/blender-2.93.9/source/blender/windowmanager/intern/wm_keymap.c:464 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Edit Mode'
...
```

**Comment by MehdiChinoune** [comment]
Now I get this:
```
A graphics card and driver with support for OpenGL 3.3 or higher is required.
Installing the latest driver for your graphics card may resolve the issue

The program will now close.
Blender - Unsupported Graphics Card or Driver
```

**Comment by Biswa96** [comment]
I do not have any dedicated GPU. So, Blender shows this warning:

image

But other than that, everything seems to be fine.

**Comment by MehdiChinoune** [comment]
I have two GPUs (Intel+Nvidia) in my laptop, but It fails to detect any them.
Maybe something should be fixed on MINGW.

**Comment by MehdiChinoune** [comment]
The Graphics Driver message now disappeared (without doing anything)
When I switch to another PC account with ASCII name, It works.
So I assume that blender has an issue when account names aren't ASCII. Need to confirm through testing.

**Comment by MehdiChinoune** [comment]
I will merge this PR as it is and I will investigate non-ASCII username issue later.

**Pull request merged**
