### PR TITLE
armadillo: Use LAPACK from f2cblaslapack for clang builds.

### LINKED ISSUE #10556: mingw-w64-clang-x86_64-armadillo  ld.lld: error: undefined symbol: wrapper2_* error
I use  mingw-w64-clang-x86_64-armadillo to there's a lot of errors when link
refrence link: https://packages.msys2.org/package/mingw-w64-clang-x86_64-armadillo?repo=clang64

ld.lld: error: undefined symbol: wrapper2_dgeev_
ld.lld: error: undefined symbol: wrapper2_dgeqrf_
ld.lld: error: undefined symbol: wrapper2_dorgqr_
ld.lld: error: undefined symbol: wrapper2_dgesdd_
ld.lld: error: undefined symbol: wrapper2_dgesvd_
ld.lld: error: undefined symbol: wrapper2_dlansy_
ld.lld: error: undefined symbol: wrapper2_dpotrf_
ld.lld: error: undefined symbol: wrapper2_dpotri_
ld.lld: error: undefined symbol: wrapper2_dpocon_
ld.lld: error: undefined symbol: wrapper2_ilaenv_
ld.lld: error: undefined symbol: wrapper2_dgelsd_
ld.lld: error: undefined symbol: wrapper2_dtrtrs_
ld.lld: error: undefined symbol: wrapper2_dgesv_
ld.lld: error: undefined symbol: wrapper2_dgbsvx_
ld.lld: error: undefined symbol: wrapper2_dposvx_
ld.lld: error: undefined symbol: wrapper2_dgesvx_
ld.lld: error: undefined symbol: wrapper2_dpotrs_
ld.lld: error: undefined symbol: wrapper2_dlange_
ld.lld: error: undefined symbol: wrapper2_dgetrf_
ld.lld: error: undefined symbol: wrapper2_dgetrs_

it seems there indeed no such symbols in  libarmadillo.dll.a, only below symbols
wrapper2_cgemm_
wrapper2_cgemv_
wrapper2_cherk_
wrapper2_dasum_
wrapper2_ddot_
wrapper2_dgemm_
wrapper2_dgemv_
wrapper2_dnrm2_
wrapper2_dsyrk_
wrapper2_sasum_
wrapper2_sdot_
wrapper2_sgemm_
wrapper2_sgemv_
wrapper2_snrm2_
wrapper2_ssyrk_
wrapper2_zgemm_
wrapper2_zgemv_
wrapper2_zherk_
wrapper_cgemm_
wrapper_cgemv_
wrapper_cherk_
wrapper_dasum_
wrapper_ddot_
wrapper_dgemm_
wrapper_dgemv_
wrapper_dnrm2_
wrapper_dsyrk_
wrapper_sasum_
wrapper_sdot_
wrapper_sgemm_
wrapper_sgemv_
wrapper_snrm2_
wrapper_ssyrk_
wrapper_zgemm_
wrapper_zgemv_

### PR DESCRIPTION
**Pull request by mmuetzel**
Fixes #10556.

### CODE REVIEW

**Comment by raedrizqie** [comment]
maybe numpy could also use something like this?

**Comment by mmuetzel** [comment]
@raedrizqie: I haven't looked at it in any detail. But judging from the log of the failed build, the issue is a missing Fortran compiler in the clang environment:
https://github.com/msys2/msys2-autobuild/runs/4364425071?check_suite_focus=true?check_suite_focus=true#step:12:21873

I'd guess the approach here wouldn't help for that case.

**Comment by mmuetzel** [comment]
The symbols that where listed as missing in #10556 seem to be exported in the updated library. So, I assume that issue would be fixed by this change.

**Comment by raedrizqie** [comment]
> Oops: Mis-read `scipy` for `numpy`. 😳
> What is the issue with `numpy`?

IIRC.. openblas' lapack implementation is incomplete on clang..

**Comment by raedrizqie** [comment]
> So, numpy compiles but misses features? Do you know how to test that?
> 
> (Maybe, we should move that to a different issue?)

before you open a new topic, let me reconfirm it first.. :)

**Comment by mmuetzel** [comment]
Updated the PR following suggestions from upstream. It should be ready now.

**Comment by raedrizqie** [comment]
> Updated the PR following suggestions from upstream. It should be ready now.

nice.. if you have the time.. can you please try building openblas with lapack from f2cblaslapack, so that we dont have to include this lapack on every clang package that requires it? just a suggestion.. thank you

**Comment by mmuetzel** [comment]
> can you please try building openblas with lapack from f2cblaslapack

I tried tricking OpenBLAS into exporting all symbols from f2c LAPACK. See: https://github.com/mmuetzel/MINGW-packages/commit/f4f3a7f7a7ff67b11f1f4237f74c72a9b911f372

But linking fails with:
```
[9083/9083] Linking C shared library lib\libopenblas.dll
FAILED: lib/libopenblas.dll lib/libopenblas.dll.a
cmd.exe /C "cd . && C:\msys64\clang64\bin\cc.exe -DHAVE_C11 -DMS_ABI -Wall -m64 -DSMALL_MATRIX_OPT -DDYNAMIC_ARCH -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DMAX_CPU_NUMBER=64 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.19\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 -O3 -DNDEBUG   -shared -o lib\libopenblas.dll -Wl,--out-implib,lib\libopenblas.dll.a -Wl,--major-image-version,0,--minor-image-version,3 @CMakeFiles\openblas_shared.rsp  && cd ."
ld.lld: error: duplicate symbol: cspmv_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/cspmv.c.obj
>>> defined at liblapack.a(cspmv.o)

ld.lld: error: duplicate symbol: cspr_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/cspr.c.obj
>>> defined at liblapack.a(cspr.o)

ld.lld: error: duplicate symbol: csymv_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/csymv.c.obj
>>> defined at liblapack.a(csymv.o)

ld.lld: error: duplicate symbol: csyr_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/csyr.c.obj
>>> defined at liblapack.a(csyr.o)

ld.lld: error: duplicate symbol: zspmv_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zspmv.c.obj
>>> defined at liblapack.a(zspmv.o)

ld.lld: error: duplicate symbol: zspr_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zspr.c.obj
>>> defined at liblapack.a(zspr.o)

ld.lld: error: duplicate symbol: zsymv_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zsymv.c.obj
>>> defined at liblapack.a(zsymv.o)

ld.lld: error: duplicate symbol: zsyr_
>>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zsyr.c.obj
>>> defined at liblapack.a(zsyr.o)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
Not sure how to fix that...

**Comment by raedrizqie** [comment]
does f2cblaslapack have any extra define for its static lib, like maybe -DSTATIC_LAPACK or something?

**Comment by mmuetzel** [comment]
> does f2cblaslapack have any extra define for its static lib, like maybe -DSTATIC_LAPACK or something?

What should that flag do? Could you please elaborate?

To clarify: Those symbols do correspond to LAPACK functions. And f2c LAPACK is right to export those imho. E.g.: http://www.netlib.org/lapack/explore-html/d4/db0/group__complex_o_t_h_e_rauxiliary_gafc01629cdde2db1e97d122a55cda415c.html
Maybe, OpenBLAS shouldn't export those symbols if it is built with `NO_LAPACK` (which is implicitly set when no Fortran compiler is found)...

**Comment by MehdiChinoune** [comment]
> > can you please try building openblas with lapack from f2cblaslapack
> 
> I tried tricking OpenBLAS into exporting all symbols from f2c LAPACK. See: [mmuetzel@f4f3a7f](https://github.com/mmuetzel/MINGW-packages/commit/f4f3a7f7a7ff67b11f1f4237f74c72a9b911f372)
> 
> But linking fails with:
> 
> ```
> [9083/9083] Linking C shared library lib\libopenblas.dll
> FAILED: lib/libopenblas.dll lib/libopenblas.dll.a
> cmd.exe /C "cd . && C:\msys64\clang64\bin\cc.exe -DHAVE_C11 -DMS_ABI -Wall -m64 -DSMALL_MATRIX_OPT -DDYNAMIC_ARCH -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DMAX_CPU_NUMBER=64 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.19\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 -O3 -DNDEBUG   -shared -o lib\libopenblas.dll -Wl,--out-implib,lib\libopenblas.dll.a -Wl,--major-image-version,0,--minor-image-version,3 @CMakeFiles\openblas_shared.rsp  && cd ."
> ld.lld: error: duplicate symbol: cspmv_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/cspmv.c.obj
> >>> defined at liblapack.a(cspmv.o)
> 
> ld.lld: error: duplicate symbol: cspr_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/cspr.c.obj
> >>> defined at liblapack.a(cspr.o)
> 
> ld.lld: error: duplicate symbol: csymv_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/csymv.c.obj
> >>> defined at liblapack.a(csymv.o)
> 
> ld.lld: error: duplicate symbol: csyr_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/csyr.c.obj
> >>> defined at liblapack.a(csyr.o)
> 
> ld.lld: error: duplicate symbol: zspmv_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zspmv.c.obj
> >>> defined at liblapack.a(zspmv.o)
> 
> ld.lld: error: duplicate symbol: zspr_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zspr.c.obj
> >>> defined at liblapack.a(zspr.o)
> 
> ld.lld: error: duplicate symbol: zsymv_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zsymv.c.obj
> >>> defined at liblapack.a(zsymv.o)
> 
> ld.lld: error: duplicate symbol: zsyr_
> >>> defined at interface/CMakeFiles/interface.dir/CMakeFiles/zsyr.c.obj
> >>> defined at liblapack.a(zsyr.o)
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> ```
> 
> Not sure how to fix that...

Not all LAPACK source files are written in Fortran, some are optimized (written in C/assembly).
You should disable LAPACK entirely to net get symbols duplicates by passing `-DBUILD_WITHOUT_LAPACK=ON` to cmake.

**Comment by MehdiChinoune** [comment]
> OpenBLAS shouldn't export those symbols if it is built with `NO_LAPACK` (which is implicitly set when no Fortran compiler is found)...

Reference?

**Comment by mmuetzel** [comment]
> Reference?

https://github.com/xianyi/OpenBLAS/blob/develop/cmake/f_check.cmake#L31

```
if (NOT NO_LAPACK)
  include(CheckLanguage)
  check_language(Fortran)
  if(CMAKE_Fortran_COMPILER)
    enable_language(Fortran)
  else()
  message(STATUS "No Fortran compiler found, can build only BLAS but not LAPACK")
  set (NOFORTRAN 1)
  set (NO_LAPACK 1)
  endif()
else()
  include(CMakeForceCompiler)
  CMAKE_FORCE_Fortran_COMPILER(gfortran GNU)
endif()
```

**Comment by mmuetzel** [comment]
> You should disable LAPACK entirely to not get symbols duplicates by passing `-DBUILD_WITHOUT_LAPACK=ON` to cmake.

That causes the build to fail early on:
```
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at test/CMakeLists.txt:4 (enable_language):
  The CMAKE_Fortran_COMPILER:

    gfortran

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

**Comment by MehdiChinoune** [comment]
> > You should disable LAPACK entirely to not get symbols duplicates by passing `-DBUILD_WITHOUT_LAPACK=ON` to cmake.
> 
> That causes the build to fail early on:
> 
> ```
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> CMake Error at test/CMakeLists.txt:4 (enable_language):
>   The CMAKE_Fortran_COMPILER:
> 
>     gfortran
> 
>   is not a full path and was not found in the PATH.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
>   path to the compiler, or to the compiler name if it is in the PATH.
> 
> 
> -- Configuring incomplete, errors occurred!
> ```

```diff
-enable_language(Fortran)
+include(CheckLanguage)
+check_language(Fortran)
+if(CMAKE_Fortran_COMPILER)
+  enable_language(Fortran)
+endif()
```

**Comment by mmuetzel** [comment]
> ```diff
> -enable_language(Fortran)
> +include(CheckLanguage)
> +check_language(Fortran)
> +if(CMAKE_Fortran_COMPILER)
> +  enable_language(Fortran)
> +endif()
> ```

That doesn't work. Probably because of this chunk in `f_check.cmake`:
```
  include(CMakeForceCompiler)
  CMAKE_FORCE_Fortran_COMPILER(gfortran GNU)
```

**Comment by MehdiChinoune** [comment]
I think you should pass `-DNOFORTRAN=ON` to cmake

**Comment by mmuetzel** [comment]
I used this change instead:
```
Check for Fortran compiler before using it.

$ diff -urN cmake/f_check.cmake.orig cmake/f_check.cmake
--- a/cmake/f_check.cmake.orig	2021-12-19 20:55:57.000000000 +0100
+++ b/cmake/f_check.cmake	2022-01-21 11:16:45.591484400 +0100
@@ -20,19 +20,18 @@
 # NEEDBUNDERSCORE
 # NEED2UNDERSCORES
 
-if (NOT NO_LAPACK)
-  include(CheckLanguage)
-  check_language(Fortran)
-  if(CMAKE_Fortran_COMPILER)
-    enable_language(Fortran)
-  else()
-  message(STATUS "No Fortran compiler found, can build only BLAS but not LAPACK")
-  set (NOFORTRAN 1)
-  set (NO_LAPACK 1)
-  endif()
-else()
+include(CheckLanguage)
+check_language(Fortran)
+if(CMAKE_Fortran_COMPILER)
+  enable_language(Fortran)
   include(CMakeForceCompiler)
   CMAKE_FORCE_Fortran_COMPILER(gfortran GNU)
+else()
+  if (NOT NO_LAPACK)
+    message(STATUS "No Fortran compiler found, can build only BLAS but not LAPACK")
+  endif()
+  set (NOFORTRAN 1)
+  set (NO_LAPACK 1)
 endif()
 
 if (NOT ONLY_CBLAS)
```

Configuration finished. I'm waiting for the build process to finish now (which could take some time).

**Comment by mmuetzel** [comment]
Fails with the same "duplicate symbol" errors. It looks like OpenBLAS exports those LAPACK symbols no matter what...

**Comment by raedrizqie** [comment]
hmm.. it doesnt have option to link with external lapack?

**Comment by mmuetzel** [comment]
> hmm.. it doesnt have option to link with external lapack?

Not afaict...

**Comment by mmuetzel** [comment]
I opened a PR for the issue with no Fortran compiler if `-DBUILD_WITHOUT_LAPACK=ON` is set:
https://github.com/xianyi/OpenBLAS/pull/3516

**Comment by mmuetzel** [comment]
Asked about the LAPACK symbols upstream:
https://github.com/xianyi/OpenBLAS/issues/3517

**Comment by mmuetzel** [comment]
After sitting on this for a while, I no longer think this is the correct approach. Instead, we should probably provide shared libraries for the `f2c` BLAS and LAPACK. See #10601.

**Pull request closed without merging**
