### PR TITLE
mkvtoolnix: Update to 80.0 and enable aarch64 builds

### PR DESCRIPTION
**Pull request by hmartinez82**

### CODE REVIEW

**Comment by lazka** [comment]
this is https://github.com/fmtlib/fmt/issues/3654

**Comment by lazka** [comment]
(I think this is ready)

**Comment by hmartinez82** [comment]
Marked as ready

**Comment by lazka** [comment]
Things crash in CI sadly:

```
2023-11-26T10:56:17.3917373Z C:/msys64/tmp/mkvtoolnix-rake-run20231126-9724-xa57f9: line 1:  5824 Segmentation fault      /clangarm64/bin/xsltproc --nonet --maxdepth 10000 -o doc/man/mkvtoolnix-gui.1 /clangarm64/share/xml/docbook/xsl-stylesheets-1.79.2/manpages/docbook.xsl doc/man/mkvtoolnix-gui.xml > C:/msys64/tmp/mkvtoolnix-rake-output20231126-9724-sdaxbh 2>&1
```

**Pull request merged**
