### PR TITLE
leptonica: update to 1.82.0

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by Biswa96** [comment]
Potential candidate for clangarm64.

```
$ file src/bin/src/.libs/liblept-5.dll
src/bin/src/.libs/liblept-5.dll: PE32+ executable (DLL) (GUI) Aarch64, for MS Windows
````

**Comment by kmilos** [comment]
I thought so, but then don't know how to handle the checkdepends which is not available for clangarm64...

**Comment by MehdiChinoune** [comment]
Isn't possible to build with cmake?

**Comment by Biswa96** [comment]
Need some changes for cmake build.

**Comment by kmilos** [comment]
Yeah, I already saw a bunch of CMake related changes upstream, best to leave it until they release the next version...

**Pull request merged**
