### PR TITLE
ci-check: don't fail if pacman install failed

### PR DESCRIPTION
**Pull request by naveen521kk**
Fixes https://github.com/msys2/MINGW-packages/issues/8749

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Wouldn't the rest of the check then potentially be invalid?  If it's going to punt, it might make more sense to skip the rest of the check if an install fails.

**Comment by naveen521kk** [comment]
maybe how about running Pacman twice? That should work. At first, it will install all the things it could and then in round 2 it will install things it failed at first.

Also, btw did you PR had python modules? If not it should have ideally skipped them.

**Comment by jeremyd2019** [comment]
> Also, btw did you PR had python modules? If not it should have ideally skipped them.

Yes

**Comment by jeremyd2019** [comment]
> maybe how about running Pacman twice? That should work. At first, it will install all the things it could and then in round 2 it will install things it failed at first.

Maybe.  It seems like in degenerate cases it may need more rounds, or may even never resolve (such as the mutually-conflicting packages from #8469).  For clang/llvm, running pacman to install all packages at once would work, but that would fail for those new curl split packages (though luckily I don't think they have any python).  I don't know of any approach that would work in all cases

**Comment by naveen521kk** [comment]
> I don't know of any approach that would work in all cases

Or how about passing all the packages to Pacman together? Finally, calculate rdeps for each package and not failing if failed to install?

**Comment by jeremyd2019** [comment]
> Or how about passing all the packages to Pacman together?

That would work for pinned deps, or circular deps, but if there are conflicting packages in the group that would fail.
 
> Finally, calculate rdeps for each package and not failing if failed to install?

would you skip the check on install failure?  I think you'd have to if installing all packages in one pacman call, as that would probably mean none had been installed so the check would be meaningless.

**Comment by naveen521kk** [comment]
@lazka I could see https://github.com/msys2/MINGW-packages/commit/e1a97686b4d5c636e42e36d0a726f6421da01989, FYI, `-Qi` only prints the reverse dependency of packages installed, but we need from the whole database, so `-Sii` should be used. I made it so that it doesn't fail on new packages. https://github.com/msys2/MINGW-packages/pull/8750/commits/ac4cfa61ece71fc1b9a03b730daf827bb2613881

**Comment by lazka** [comment]
ah, ok, sry.

**Comment by lazka** [comment]
one possible fix, if I'm not mistaken, is put all packages in a local repo, install/uninstall one by one.

**Comment by naveen521kk** [comment]
I think it still can't fix conflicts and it works the same as passing everything to pacman.

**Comment by jeremyd2019** [comment]
I think it wouldn't "fix" conflicts, but it would "succeed" by automatically uninstalling the package it conflicts with before installing the package.  So you'd wind up with the "last" package of mutually-conflicting packages, rather than a failure to install.  Don't know what's preferable here (with the failure you know something funny's going on and can skip the rest of the check)

**Comment by naveen521kk** [comment]
I think it's simply fine to skip the tests if the installation failed(*usually* python packages we care about don't have that problem).

**Comment by naveen521kk** [comment]
I will try to create a temp repo and working and that seems like an effective idea.

**Pull request merged**
