### PR TITLE
pupnp: update to 1.4.12

### PR DESCRIPTION
**Pull request by neheb**
Switch to CMake compilation. Faster and less buggy.

Added testing support.

Remove outdated patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
pupnp installs DLLs in lib folder instead of bin folder.

**Comment by lazka** [comment]
the static libs have a s suffix still.. not sure if that is a problem

**Comment by Biswa96** [comment]
There was a similar situation with brotli's static libs. Alexey added a workaround by renaming it 💡

**Comment by neheb** [comment]
At this point it's probably better to replace the patch with a sed script...

**Comment by neheb** [comment]
Updated.

**Comment by lazka** [comment]
thx

**Comment by Biswa96** [comment]
The 010-msvc.patch and 020-fix-install-dir.patch are in upstream now with two mingw64 and mingw32 builds in CI.

**Pull request merged**
