### PR TITLE
krpc-cpp: Rebuild with upstream asio and protobuf

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by Biswa96** [comment]
Would you like to explain the reason for this change?

**Comment by podsvirov** [comment]
There is a namespace conflict: the global namespace pb is already declared in the updated protobuf headers.

**Comment by Biswa96** [comment]
Thanks for the info. Did you report it to upstream?

**Comment by MehdiChinoune** [comment]
> Thanks for the info. Did you report it to upstream?

https://github.com/krpc/krpc/issues/766

**Pull request merged**
