### PR TITLE
Add rav1e and cargo-c

### PR DESCRIPTION
**Pull request by lazka**
"An AV1 encoder focused on speed and safety"

### CODE REVIEW

**Comment by lazka** [comment]
This only builds the executables, the shared library build is blocked by https://github.com/alexcrichton/ssh2-rs/issues/187 atm

**Comment by mati865** [comment]
ssh2-rs issue has been fixed.

**Comment by lazka** [comment]
This is ready now

**Comment by lazka** [comment]
Now with some cargo-c Windows fixes

**Pull request merged**
