### PR TITLE
Add intel-tbb-debug package

### PR DESCRIPTION
**Pull request by ImperatorS79**
I do not know what is the "policy" about debug librairies here, so I created another package, but I can merge it into one if necessary.

### CODE REVIEW

**Comment by lazka** [comment]
extra package seems fine, but there are ucrt64 errors. likely some unrelated issue, but this blocks things.

**Comment by ImperatorS79** [comment]
Seems related to https://github.com/msys2/MINGW-packages/issues/9617. I wonder how it builded before on ucrt64 (even the release build does not work).

**Comment by lazka** [comment]
it was fixed in #9786, so a rebase should fix it

**Comment by lazka** [comment]
This now contains unrelated changes, if I'm not mistaken (?)

**Comment by ImperatorS79** [comment]
Yes but I do not know why, the rebase went wrong somehow🤔.

**Comment by lazka** [comment]
ok, I'll have a look when I have some time.

**Comment by ImperatorS79** [comment]
@lazka I think I fixed it.

**Comment by ImperatorS79** [comment]
@lazka Small reminder that this PR exists ^^.

**Comment by lazka** [comment]
I'm slightly confused tbh. What does this add? It doesn't add a package and doesn't add any new files.

**Comment by ImperatorS79** [comment]
It should add an intel-tbb-debug package.

**Comment by ImperatorS79** [comment]
Ok I forgot to modify pkgname variable -_-'. My bad.

**Comment by MehdiChinoune** [comment]
There is no intel-tbb anymore.

**Pull request closed without merging**
