### PR TITLE
starpu: fix 32bit build with clang v16

### PR DESCRIPTION
**Pull request by lazka**
it rightfully complains the the callback calling convention doesn't match

### CODE REVIEW

**Comment by lazka** [comment]
@3rav fyi

upstream git isn't public, so not sure if we can upstream this.

or maybe we should drop 32bit?

**Comment by 3rav** [comment]
> @3rav fyi
> 
> upstream git isn't public, so not sure if we can upstream this.
> 
> or maybe we should drop 32bit?
> 
> or just leave it as is for now...

For me drop 32bit

**Comment by lazka** [comment]
> Isn't this one the official repository https://gitlab.inria.fr/starpu/starpu ? Also there is an official mirror https://github.com/starpu-runtime/starpu/

Ah, I missed the mirror, thanks (the former requires you to send an email to someone to request an account)

**Comment by Biswa96** [comment]
Would you like to upstream the changes? Or can I?

**Comment by lazka** [comment]
https://github.com/starpu-runtime/starpu/pull/13

**Pull request merged**
