### PR TITLE
libmysofa: Update to 1.2, use ninja

### PR DESCRIPTION
**Pull request by Biswa96**
The idea is shamelessly copied/stolen from https://github.com/msys2/MINGW-packages/pull/8606

Pinging some bots @jeremyd2019 @neheb @ZachBacon

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I believe this just needs some pkgconf magic to define `MYSOFA_STATIC_DEFINE` for static builds, and it'd be good for both static and dynamic builds (assuming whoever is doing static builds uses pkgconf).

**Comment by Biswa96** [comment]
Why? There is already a static library built with shared library. And dependent packages are linked with dlls. Aren't they?

**Comment by jeremyd2019** [comment]
If somebody wanted to *use* the static library, they'd need to define `MYSOFA_STATIC_DEFINE` otherwise they'd get the API's with dllimport attributes, and the linker would be sad.  If you add the line `Cflags.private: -DMYSOFA_STATIC_DEFINE=1` to the .pc file, users of pkgconf who ask for `pkg-config --cflags --static` will get that.

**Comment by Biswa96** [comment]
And where did you get the `MYSOFA_STATIC_DEFINE` name from?

**Comment by jeremyd2019** [comment]
From the generated mysofa_export.h.  https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html 
> If the same sources are used to create both a shared and a static library, the uppercased symbol ${BASE_NAME}_STATIC_DEFINE should be used when building the static library
This will cause the export macros to expand to nothing when building the static library.

**Comment by neheb** [comment]
I hold no opinion.

**Pull request merged**
