### PR TITLE
python-nuitka: Update to 0.6.16.5

### PR DESCRIPTION
**Pull request by podsvirov**
*UPDATE*: from 0.6.16.4 to 0.6.16.5

### CODE REVIEW

**Comment by Biswa96** [comment]
This is in a previous pull request.

**Comment by podsvirov** [comment]
> This is in a previous pull request.

You mean #9543?

**Comment by Biswa96** [comment]
Yes.

**Comment by podsvirov** [comment]
> This is in a previous pull request.

And now?

**Pull request merged**
