### PR TITLE
mingw-w64-python-pyproject2setuppy -

### PR DESCRIPTION
**Pull request by JPeterMugaas**
new package
mingw-w64-python-tomli
  rewrote to use pyproject2setuppy
mingw-w64-python-tomli-w
  new package

### CODE REVIEW

**Comment by Biswa96** [comment]
The `mingw_arch` array is required to select $MSYSTEM before building packages.

**Comment by jeremyd2019** [comment]
Where was this yesterday when I was fighting the circular dependency between python-build and python-tomli? :wink:

**Comment by naveen521kk** [comment]
Thanks, can you make a corresponding [PKGBUILD.template](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-PKGBUILD-templates), so that one can refer to it in the future.

**Review by naveen521kk — APPROVED** [review]
Looks good thanks

**Pull request merged**
