### PR TITLE
python-streamlink: add package and add/update dependencies

### PR DESCRIPTION
**Pull request by JasonQiu1**
(add package) python-streamlink: A CLI utility that extracts streams from various services and pipes them into a video player of choice. It wasn't working with pip install but worked after adding/updating the below packages.
(add package dependency) python-charset_normalizer: A library that helps you read text from an unknown charset encoding
(add package dependency) python-isodate: An ISO 8601 date/time/duration parser and formatter
(add package dependency) python-pycountry: ISO country, subdivision, language, currency and script definitions and their translations
(update package dependency) python-requests: 2.25.1 => 2.27.1

I'm new to package repos and PRs, so if I need to separate these into separate pull requests or need to do anything special, please let me know.

### CODE REVIEW

**Comment by JasonQiu1** [comment]
```
Installing Package.
Installing: ['mingw-w64-x86_64-manim', 'mingw-w64-x86_64-python-cachecontrol', 'mingw-w64-x86_64-python-cookiecutter', 'mingw-w64-x86_64-python-dephell-changelogs', 'mingw-w64-x86_64-python-dephell-licenses', 'mingw-w64-x86_64-python-flit', 'mingw-w64-x86_64-python-google-api-core', 'mingw-w64-x86_64-python-google-cloud-core', 'mingw-w64-x86_64-python-oslosphinx', 'mingw-w64-x86_64-python-pooch', 'mingw-w64-x86_64-python-pygithub', 'mingw-w64-x86_64-python-requests-mock', 'mingw-w64-x86_64-python-requests-oauthlib', 'mingw-w64-x86_64-python-requests-unixsocket', 'mingw-w64-x86_64-python-responses', 'mingw-w64-x86_64-python-sphinx', 'mingw-w64-x86_64-python-streamlink']

Pip Output: mingw-w64-x86_64-python-requests-2.27.1-1-any.pkg.tar.zst
Here is what it failed.
oslosphinx 4.18.0 requires pbr, which is not installed.
```

I'm not sure what went wrong in the check job. None of the packages I added or updated depend on sphinx or oslosphinx.

**Comment by lazka** [comment]
> I'm not sure what went wrong in the check job. None of the packages I added or updated depend on sphinx or oslosphinx.

yes, please ignore

**Comment by Biswa96** [comment]
oslosphinx project had been archived in upstream. It should be removed.

**Comment by naveen521kk** [comment]
This caused an error when running `manim`
```py
pkg_resources.DistributionNotFound: The 'charset_normalizer~=2.0.0' distribution was not found and is required by requests
```
and in turn `pip check`
```
❯ pip check
requests 2.27.1 requires charset-normalizer, which is not installed.
```
I think the ci-check should error out only when all the packages are checked and the error should be printed all together so that this issue can be found.

**Pull request merged**
