### PR TITLE
cmake: Update to 3.20.0

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
There was a missing dependency in `sphinx` (`packaging`), that is used by cmake, so I rebased it on top of the sphinx upgrade.

**Comment by orgads** [comment]
Thanks, rebased.

**Comment by orgads** [comment]
Damn. Should have waited until the package is published.. 🙄

**Comment by lazka** [comment]
No problem, I'll restart it later once the packages are done.

**Comment by jtanx** [comment]
The Intl::Intl imported target doesn't work in this version, haven't yet determined if that's an msys2 problem or a cmake problem.

**Pull request merged**
