### PR TITLE
python-watchfiles: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by lazka** [comment]
The python package version is "0.0.0", which suggests that there is some dynamic version detection going which failed. Not sure what though.

**Comment by podsvirov** [comment]
> edit: from what I see maturin should pull the version from cargo.toml.. weird.

Good catch. In Cargo.toml currently `0.0.0`. Should I add patch?

**Comment by lazka** [comment]
Indeed. Yeah, I think patching is needed there.

**Comment by lazka** [comment]
Ah, the tarball from https://pypi.org/project/watchfiles/ contains a proper version. Maybe use that instead?

**Comment by podsvirov** [comment]
Okay!

**Pull request merged**
