### PR TITLE
qwt: Enable generating pkgconfig file.

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Is it OK to rename qwt to qwt-qt5?

**Comment by MehdiChinoune** [comment]
The CI fails because of conflicting between qwt (qt5) and qwt (qt6-base) dependencies.

**Comment by Biswa96** [comment]
You can separate any one of the packages here in different pull request.

**Comment by MehdiChinoune** [comment]
> You can separate any one of the packages here in different pull request.

Done.

**Comment by lazka** [comment]
Isn't this the same as #9225 now?

**Comment by MehdiChinoune** [comment]
> Isn't this the same as #9225 now?

It's the same, but for qwt-qt5

**Comment by lazka** [comment]
> Is it OK to rename qwt to qwt-qt5?

It was named that before (see the replaces/conflict/provides). I'd have to coordinate removing the old package after the rename to avoid a rename loop, but sure.

**Comment by lazka** [comment]
> It's the same, but for qwt-qt5

I only see qt6 changes here.

**Comment by MehdiChinoune** [comment]
> > It's the same, but for qwt-qt5
> 
> I only see qt6 changes here.

Are you sure!

**Comment by lazka** [comment]
yes

**Pull request closed without merging**
