### PR TITLE
python-colour-science: update to 0.4.0

### PR DESCRIPTION
**Pull request by kmilos**
Also sync w/ latest template

### CODE REVIEW

**Comment by lazka** [comment]
https://github.com/colour-science/colour/issues/945 thanks

We can update setuptools if needed, just needs some patching.

**Comment by kmilos** [comment]
Looks like there is a patch upstream already, will wait for that...

**Comment by kmilos** [comment]
Or I could also try switching to `python-build` [like Arch did](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-colour-science&id=e39f2987a27d78a5a3cf19e7101d3bb743021f59)...

**Comment by naveen521kk** [comment]
Slightly editing the pyproject.toml should do the trick without poetry being installed (instead using poetry-core) as mentioned in https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

**Comment by kmilos** [comment]
@naveen521kk Indeed, thanks!

**Comment by naveen521kk** [comment]
Also, I think you can make that change upstream.

**Comment by kmilos** [comment]
Yeah, it seems it recommended anyway, I let upstream know.

**Pull request merged**
