### PR TITLE
python-sphinx_rtd_theme: update to 1.0.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
I could do nothing about `docutils` dependency that has been already updated to 0.18.1

### CODE REVIEW

**Comment by Biswa96** [comment]
> about docutils dependency that has been already updated to 0.18.1

Try to add the `sed -i 's/<0.18/<0.19/' setup.py` command in sphinx-rtd-theme PKGBUILD.

**Comment by MehdiChinoune** [comment]
Could I ask, How did you merge this?

**Comment by jeremyd2019** [comment]
Looks like a 'Squash and merge'

**Comment by MehdiChinoune** [comment]
> Looks like a 'Squash and merge'

No, They were committed separately.
The strange thing is that I am seeing his name beside mine as authors!

**Comment by naveen521kk** [comment]
> The strange thing is that I am seeing his name next mine as authors!

I guess it's rebase and merge then.

**Comment by Biswa96** [comment]
Yup, I did 'Rebase and merge'. It retains each separate commits without creating a merge commit.

**Comment by MehdiChinoune** [comment]
> Yup, I did 'Rebase and merge'. It retains each separate commits without creating a merge commit.
> 
> > The strange thing is that I am seeing his name next mine as authors!
> 
> No, the author and committer are two different users. It is common in many repositories like
> 
> * mingw-w64: https://github.com/mingw-w64/mingw-w64/commits/master
> * wine: https://github.com/wine-mirror/wine/commits/master

I know about it, It's common.
I just didn't see in "GitHub Desktop", but I could see it in Web.

**Comment by jeremyd2019** [comment]
Oops, ignore the 'revert' branch i just inadvertently created... I just wanted to see if the 'revert' button on that line knew there was more than one commit (it did), I didn't know it would actually create the branch, let alone in this repo rather than on my fork!

**Comment by MehdiChinoune** [comment]
Well, forgot to say.
This didn't happen with previous commits (, It only shows me!

**Comment by jeremyd2019** [comment]
Normally PRs tend to be merged with a merge commit around here.  In that case, your original commits exist as-is (with you as author and committer), and the person who merges is author and committer of the merge commit.

**Pull request merged**
