### PR TITLE
julia: set `USE_LLVM_SHLIB = 0` and fix install dir

### PR DESCRIPTION
**Pull request by smalltalkman**
Continue from https://github.com/msys2/MINGW-packages/pull/5679

### CODE REVIEW

**Comment by smalltalkman** [comment]
@Alexpux Why did AppVeyor build failed? The downloaded log is incomplete.

**Comment by mati865** [comment]
1,5 hour time limit.

**Comment by smalltalkman** [comment]
@mati865 Thanks.

**Comment by vchuravy** [comment]
`USE_LLVM_SHLIB=0` is not an encouraged build configuration since it will break packages depending on LLVM.jl (https://github.com/maleadt/LLVM.jl), which uses the C-API of LLVM and is used to add support for GPU computing. 

Just FYI.

**Pull request merged**
