### PR TITLE
openvdb: rebuild

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
@Alexpux openvdb doesn't build

**Comment by Alexpux** [comment]
@lazka because cmake find wrong Python, see
````
Found Python: C:/hostedtoolcache/windows/Python/3.9.1/x64/include) (found suitable version "3.9.1", minimum required is "2.7")
````

**Comment by Alexpux** [comment]
@lazka try add to options:
````
-DPython_EXECUTABLE=${MINGW_PREFIX}/bin/python
````

**Comment by Alexpux** [comment]
Well try then add:
````
-DPython_ROOT_DIR=${MINGW_PREFIX}
-DPython_FIND_REGISTRY=NEVER
````

**Comment by lazka** [comment]
thanks! we are getting further

**Pull request merged**
