### PR TITLE
ninja: use $TERM to decide when to use fancy output

### PR DESCRIPTION
**Pull request by oscarfv**
... such as one-line progress messages, color, etc.

### CODE REVIEW

**Comment by oscarfv** [comment]
What's preventing the merge of this PR?

**Comment by lazka** [comment]
We'll enable conpty in the near future, which makes this obsolete, but can't hurt I guess.

**Comment by lazka** [comment]
This breaks ninja, I have to revert it.

```
# CMakeLists.txt
project(foo)
message(STATUS ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
```

`CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES` is empty with the patched ninja version.

**Comment by oscarfv** [comment]
> We'll enable conpty in the near future, which makes this obsolete, but can't hurt I guess.

This benefits any application that launches ninja and has terminal emulation capabilities.

> This breaks ninja, I have to revert it.
> 
> ```
> # CMakeLists.txt
> project(foo)
> message(STATUS ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
> # cmake .
> ```
> 
> `CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES` is empty with the patched ninja version.
> 
> cmake logs indicate that cmakes somehow gets ninja debug output and tries to parse it as gcc output, which fails.

Thanks for the analysis. Under mintty $TERM is set to `xterm`. This is what ninja sees when it is invoked by cmake.

I'm afraid that it would be necessary to implement an explicit option to enable ninja's fancy output on Windows, because there is no general mechanism to decide if the output is going to a terminal (real or emulated) or not.

Sorry for the inconvenience.

**Pull request merged**
