### PR TITLE
coin: New package

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by Alexpux** [comment]
@podsvirov for what reason you add it back? In the past I have mostly full subset of packages from coin but it mostly die, so I don’t see a reason to add them back

**Comment by podsvirov** [comment]
In my opinion, the project is undergoing a second wind. They switched to more modern tools and development tools. Almost ten years later, new tags and releases appeared. Also, as far as I know, the project is actively used in the `FreeCAD` project. Similar packages were added in the `vcpkg` package manager.

**Comment by Alexpux** [comment]
@podsvirov why you then add SoQt instead Quarter?

**Comment by podsvirov** [comment]
I think we need to support both, for various reasons. Of course we need to add the `Quarter` and other packages as well later.

**Comment by Alexpux** [comment]
@podsvirov look at https://github.com/msys2/MINGW-packages-dev you will find there packages that I do years ago for coin

**Comment by podsvirov** [comment]
Well, I will explore your experience. Can I hope that we will see these packages again here?

**Comment by Alexpux** [comment]
@podsvirov in my previous coin3d package I have next deps:
````
depends=("${MINGW_PACKAGE_PREFIX}-simage"
         "${MINGW_PACKAGE_PREFIX}-bzip2"
         "${MINGW_PACKAGE_PREFIX}-expat"
         "${MINGW_PACKAGE_PREFIX}-openal"
         "${MINGW_PACKAGE_PREFIX}-superglu"
         "${MINGW_PACKAGE_PREFIX}-freetype"
         "${MINGW_PACKAGE_PREFIX}-fontconfig"
         "${MINGW_PACKAGE_PREFIX}-zlib")
````
Is simage and superglu dont need anymore?

**Comment by podsvirov** [comment]
Sorry for the long answer. Both are still relevant and can be added.  But we can run SoQt examples without them.

**Pull request merged**
