### PR TITLE
Update mingw-w64

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
@mmuetzel includes https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/20231026111557.3507876-1-martin%40martin.st/#msg48497812 might be interesting you

**Comment by mmuetzel** [comment]
@lazka: Thanks for the pointer. I occasionally peruse that mailing list and I'm very much looking forward to that change since I came across it. Happy you adopted it for MSYS2 so timely. 🎉

Maybe, that's the final step that was needed to definitely move from MINGW64 to UCRT64 as my primarily used environment.

(I haven't tested anything so far though...)

**Comment by MehdiChinoune** [comment]
> @mmuetzel includes https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/20231026111557.3507876-1-martin%40martin.st/#msg48497812 might be interesting you

r345 means that they are included I guess, I have just checked this morning.

**Comment by mmuetzel** [comment]
Ran the test suite of Octave in the MINGW64 and UCRT64 environments. There aren't any new errors afaict. 👍
I haven't run any performance tests yet. IIUC, some basic math operations with single precision floating point numbers should be faster after that change. Is that correct?

**Comment by lazka** [comment]
> Ran the test suite of Octave in the MINGW64 and UCRT64 environments. There aren't any new errors afaict. 👍

Nice, thanks.

> I haven't run any performance tests yet. IIUC, some basic math operations with single precision floating point numbers should be faster after that change. Is that correct?

No idea. I only saw that CPython math tests now pass with it, we had these errors before:

```
 ======================================================================
FAIL: test_mtestfile (test.test_math.MathTests.test_mtestfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython-mingw\cpython-mingw\Lib\test\test_math.py", line 1798, in test_mtestfile
    self.fail('Failures in test_mtestfile:\n  ' +
AssertionError: Failures in test_mtestfile:
  erfc0050: erfc(-40.0): expected 2.0, got 'OverflowError' (not equal)
  erfc0052: erfc(-1e+150): expected 2.0, got 'OverflowError' (not equal)

======================================================================
FAIL: test_testfile (test.test_math.MathTests.test_testfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython-mingw\cpython-mingw\Lib\test\test_math.py", line 1731, in test_testfile
    self.fail('Failures in test_testfile:\n  ' +
AssertionError: Failures in test_testfile:
  acosh0062: acosh(1.0000000000000002): expected 2.1073424255447014e-08, got 2.1073424338879928e-08 (error = 8.34e-17 (25216051 ulps); permitted error = 0 or 5 ulps)
  acosh0063: acosh(1.0000000000000002): expected 2.1073424255447014e-08, got 2.1073424338879928e-08 (error = 8.34e-17 (25216051 ulps); permitted error = 0 or 5 ulps)
  acosh0064: acosh(1.001): expected 0.04471763360830685, got 0.04471763360830678 (error = 6.94e-17 (10 ulps); permitted error = 0 or 5 ulps)
  acosh0065: acosh(1.001): expected 0.04471763360830685, got 0.04471763360830678 (error = 6.94e-17 (10 ulps); permitted error = 0 or 5 ulps)
```

**Comment by mmuetzel** [comment]
Interesting that it fixed a test of the error function for you. I ran Octave's CI on GitHub with UCRT64 and it shows an error in a test for that function that I don't recognize from before:
https://github.com/mmuetzel/octave/actions/runs/6676760096/job/18146138911#step:15:86401
```
***** assert (erfcinv (erfc (single ([-3 -1 -0.4 0.7 1.3 2.8]))),
        single ([-3 -1 -0.4 0.7 1.3 2.8]), -1e-4)
!!!!! test failed
ASSERT errors for:  assert (erfcinv (erfc (single ([-3, -1, -0.4, 0.7, 1.3, 2.8]))),single ([-3, -1, -0.4, 0.7, 1.3, 2.8]),-1e-4)

  Location  |  Observed  |  Expected  |  Reason
    (1)        -2.9994         -3        Rel err 0.00019693 exceeds tol 0.0001 by 0.0001
shared variables 
    rt2 = 1.4142
    rt3 = 1.7321
```

I don't see that test error locally. Could any of that depend on the used hardware?

**Pull request merged**
