### PR TITLE
CMake tests

### PR DESCRIPTION
**Pull request by Optiligence**
not sure if this is wanted (therefore separately from #2513)
also not sure if this works to merge one after the other, but i’d be curious to find out

### CODE REVIEW

**Comment by Optiligence** [comment]
I’m currently still running these, and apparently some fail, so far: 
#61: ExportImport
#118: CPackWiXGenerator (and some more related to the WiX toolset that i have installed, so removed that for a second run)

so it’s probably not so wise to enforce the tests yet

**Comment by Alexpux** [comment]
Rebase changes

**Comment by Optiligence** [comment]
test output https://pastebin.com/spN9F1xk
i couldn’t fix any of the failing tests yet
some are related to path handling, others to import libraries

**Comment by peterbud** [comment]
I'm happy to see such PRs. I have found also packages which were failing some of the test cases, and those errors were undetected for a longer time simply due to lack of `make check`. I think it's OK to have some test cases fail, but at least they are known and people can work on those.

**Comment by Optiligence** [comment]
I thought failing tests would prevent packages from successfully building. If that isn’t the case then this can be merged right away. Although i’m not sure where the discussion about failing cases should continue then.

**Comment by mati865** [comment]
@Optiligence you can always use `make check | true`

**Comment by lazka** [comment]
Needs a rebase again. Failing tests are fine imo, better then before at least..

**Pull request merged**
