### PR TITLE
binutils: add upstream patches changing PE defaults.

### PR DESCRIPTION
**Pull request by jeremyd2019**
I don't know that this is desired, but I wanted to get this out there in draft form because there seems to be some desire to test with ASLR on by default in binutils in #6674.

### CODE REVIEW

**Comment by lazka** [comment]
* There has been one more commit upstream: https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=6194b866b7a89969d8c66f8a97d40acc028373b1
* If we'd add a commit reverting the default changes we could get the --disable flags which we could start using (does `LDFLAGS=--high-entropy-va; LDFLAGS+=--disable-high-entropy-va` work as I think it does?). I'd still like to see more packages getting build first before enabling this for everyone.

**Comment by 1480c1** [comment]
> * If we'd add a commit reverting the default changes we could get the --disable flags which we could start using (does `LDFLAGS=--high-entropy-va; LDFLAGS+=--disable-high-entropy-va` work as I think it does?). I'd still like to see more packages getting build first before enabling this for everyone.

I'm not sure this would work since it would result in 
```bash
LDFLAGS=--high-entropy-va--disable-high-entropy-va
```

would probably instead need
```bash
LDFLAGS=--high-entropy-va; LDFLAGS+=" --disable-high-entropy-va"
```

**Comment by jeremyd2019** [comment]
> * There has been one more commit upstream: https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=6194b866b7a89969d8c66f8a97d40acc028373b1 Not sure if relevant
That should be 1003-Fixes-for-testsuite-failures-introduced-by-the-chang.patch

> * If we'd add a commit reverting the default changes we could get the --disable flags which we could start using (does `LDFLAGS=--high-entropy-va; LDFLAGS+=--disable-high-entropy-va` work as I think it does?).

It should be that the last one wins.

>  I'd still like to see more packages getting build first before enabling this for everyone.

Me too, which is why this is a draft, and why I had originally made 2 patches on the upstream bug, one adding the disable flags and one changing the defaults.

**Comment by jeremyd2019** [comment]
I had made this branch for my own use testing, but after seeing someone going back to the old patches, I thought it'd be a good idea to make it more accessible (and as a side benefit, can grab binaries from the CI artifacts)

**Comment by lazka** [comment]
> > * There has been one more commit upstream: https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=6194b866b7a89969d8c66f8a97d40acc028373b1 Not sure if relevant
> 
> That should be 1003-Fixes-for-testsuite-failures-introduced-by-the-chang.patch

ah, I missed that.

> > * If we'd add a commit reverting the default changes we could get the --disable flags which we could start using (does `LDFLAGS=--high-entropy-va; LDFLAGS+=--disable-high-entropy-va` work as I think it does?).
> 
> It should be that the last one wins.

ok

> > I'd still like to see more packages getting build first before enabling this for everyone.
> 
> Me too, which is why this is a draft, and why I had originally made 2 patches on the upstream bug, one adding the disable flags and one changing the defaults.

I'd be happy to merge this now if DEFAULT_DLL_CHARACTERISTICS was set to 0x0

**Pull request merged**
