### PR TITLE
libavif: update to 1.0.1

### PR DESCRIPTION
**Pull request by kmilos**
Deps need patching/update because of API change and/or `SameMajor` CMake version matching policy.

### CODE REVIEW

**Comment by lazka** [comment]
Arch completed the rebuild here: https://archlinux.org/todo/libavif-10/ see the packages for related patches they apply.

**Comment by kmilos** [comment]
IMHO there are some gd and sdl2 patches missing.

darktable and kimageformats are patched upstream.

**Comment by kmilos** [comment]
> Should we switch to `CMAKE_SHARED_LIBRARY_NAME_WITH_VERSION=ON` while at it?

Good idea, done.

**Comment by MehdiChinoune** [comment]
The recommended way to add SOVERSION to library name is using [CMAKE_DLL_NAME_WITH_SOVERSION](https://cmake.org/cmake/help/latest/variable/CMAKE_DLL_NAME_WITH_SOVERSION.html)

**Pull request merged**
