### PR TITLE
flac: update to 1.3.4, port to cmake

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/pull/10853

Review please @drfiemost

### CODE REVIEW

**Comment by lazka** [comment]
lgtm

**Comment by lazka** [comment]
we need rebuilds though :) Should I do that?

**Comment by Biswa96** [comment]
The previous build of this PR failed with `-isystem` in UCRT. I would like to wait for green in autobuild. Also have the PTSD from those "Revert.. Revert..." commits 😰

**Comment by lazka** [comment]
ok, no problem.

**Comment by lazka** [comment]
The following packages need a rebuild:

```
mingw-w64-libsndfile
mingw-w64-sox
mingw-w64-opus-tools
mingw-w64-SDL2_mixer
mingw-w64-sfml
mingw-w64-gst-plugins-good
mingw-w64-allegro
mingw-w64-vlc
mingw-w64-scummvm
```

**Comment by lazka** [comment]
I added it in 6d696174d98fdb. I'll handle the "revert revert..." if needed ;)

**Pull request merged**
