### PR TITLE
go: Include temporary fix for default environment variables

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/18166

### CODE REVIEW

**Comment by Biswa96** [comment]
This is copied from ArchLinux https://gitlab.archlinux.org/archlinux/packaging/packages/go/-/commit/97e19acbc78f2b2a19f6ed25aee510669d70fc65

**Comment by ognevnydemon** [comment]
it fixes a bit more issues regarding GOROOT variable

**Comment by lazka** [comment]
> it fixes a bit more issues regarding GOROOT variable. or not?

I don't know much about golang, but `go env GOROOT` returns the same thing before and after this change.

**Comment by ognevnydemon** [comment]
> > it fixes a bit more issues regarding GOROOT variable. or not?
> 
> I don't know much about golang, but `go env GOROOT` returns the same thing before and after this change.

anyway I can set it in this file, can't I?

**Comment by Biswa96** [comment]
> it fixes a bit more issues regarding GOROOT variable. or not?

This is not related to GOROOT variable. go.env sets only GOPROXY, GOSUMDB and GOTOOLCHAIN variables. 

Though, we could add GOROOT in that go.env file. I am not sure about that. shell's rc file is another option.

**Pull request merged**
