### PR TITLE
mingw-w64-x265: fix static library linking.

### LINKED ISSUE #8824: static FFmpeg (again)
I asked it years ago #4234 ...

Now it is formally supported, but of course it is broken.

To start with: it links to `-l:libx264.dll.a` and `-l:libxml2.dll.a`, instead of `-lx264` and `-lxml2`
```
ld: libavformat.a(dashdec.o):(.text+0x10bc): undefined reference to `_imp__xmlGetProp'
...
ld: libavcodec.a(libx264.o):libx264.c:(.text+0x30): undefined reference to `_imp__x264_picture_init'
...
```

libx265 is broken in exotic way:
```
ld: libx265.a(api.cpp.obj):(.text+0x3c30): undefined reference to `x265_12bit::x265_api_get_192(int)'
ld: libx265.a(api.cpp.obj):(.text+0x3c49): undefined reference to `x265_10bit::x265_api_get_192(int)'
ld: libx265.a(api.cpp.obj):(.text+0x3cc1): undefined reference to `x265_10bit::x265_api_query(int, int, int*)'
ld: libx265.a(api.cpp.obj):(.text+0x3cd9): undefined reference to `x265_12bit::x265_api_query(int, int, int*)'
```
There was fix for this in vcpkg https://github.com/microsoft/vcpkg/pull/18145 but I just don't indestand what it does.

### PR DESCRIPTION
**Pull request by nitroxis**
See https://github.com/msys2/MINGW-packages/issues/8824#issuecomment-1086783808

### CODE REVIEW

**Comment by msink** [comment]
This will fix only small subset of #8824

**Comment by nitroxis** [comment]
I guess. It only fixes the x265 linking errors.

**Comment by msink** [comment]
But if merged as-is - it will autoclose #8824, no?

**Comment by nitroxis** [comment]
Oh, in that case let me change the commit message

**Pull request merged**
