### PR TITLE
fix patch file - remove -std=c++11 -pedantic for windows

### PR DESCRIPTION
**Pull request by phweyland**
EDIT: gmic package update. The previous version failed with darktable.

I've tried commit --amend but this was bringing some of your previous changes sig ...
I've created a new commit. I hope that's ok.

### CODE REVIEW

**Comment by Alexpux** [comment]
@phweyland increase ````pkgrel````

**Comment by phweyland** [comment]
> increase `pkgrel`

done

**Comment by Alexpux** [comment]
> 
> 
> > increase `pkgrel`
> 
> done

I dont see

**Comment by phweyland** [comment]
Sorry, I've forgotten to add it. :(
Should be there now.

**Pull request merged**
