### PR TITLE
mingw-w64-headers-git: add patch for av1 with dxva

### PR DESCRIPTION
**Pull request by 1480c1**
Adds a patch that is currently not in mingw-w64 nor wine for adding av1
decoding support via dxva. This is useful for FFmpeg to decode using
their hwaccel.

From https://www.winehq.org/pipermail/wine-devel/2020-September/173175.html and used in https://github.com/BtbN/FFmpeg-Builds/commit/0df2644223a5d3f775b4e25d027a3dc4446caefe

### CODE REVIEW

**Comment by Biswa96** [comment]
mingw-w64-crt need a bump. The GUIDs have to go into libuuid.a.

**Comment by Biswa96** [comment]
crt does not need the patch as the patch is applied in mingw-w64-headers folder. By bump, I mean pkgrel++ Apology for confusion.

**Comment by 1480c1** [comment]
Oh, I just applied it since it seems the other patches that were the same were also applied

**Comment by Biswa96** [comment]
It's OK to apply for both package.

**Comment by 1480c1** [comment]
found out that pkgver does indeed run after prepare, so the git patch being there will properly change the pkgver

**Comment by Biswa96** [comment]
A new version of Windows SDK has been released and it has these definitions. I'd like to wait for some days before poking in wine mailing list.

**Pull request merged**
