### PR TITLE
libuv: update to 1.44.2

### PR DESCRIPTION
**Pull request by MehdiChinoune**
The commit couldn't be reversed anymore.

~Moving to CMake buildsystem requires a bootstrap pf CMake as libuv is one of its dependencies.~ (Fixed)

### CODE REVIEW

**Comment by Biswa96** [comment]
Is it required to use cmake to build this package? The bootstrap conflicts can be skipped with autotools, right?

**Comment by MehdiChinoune** [comment]
> Is it required to use cmake to build this package?

No, It could be built by both CMake and autotools.
> The bootstrap conflicts can be skipped with autotools, right?

autotools with CMake or libuv?
I have fixed the library name to avoid rebuilding CMake.

**Comment by Biswa96** [comment]
I mean, let build libuv with autotools. In that way, we can avoid the dependency cycle.

**Comment by MehdiChinoune** [comment]
> I mean, let build libuv with autotools. In that way, we can avoid the dependency cycle.

The CMake build is faster and provide cmake-config files.

**Comment by Biswa96** [comment]
OK, understood.

**Comment by MehdiChinoune** [comment]
Is there any objection?

**Pull request merged**
