### PR TITLE
Libuhd bugfixes

### PR DESCRIPTION
**Pull request by chrisjohgorman**
- There was a small section of code commented out because I couldn't get it to build. A
  simple cast fixes this. Now we can use pthread_setname_np to set thread names.

- Use cygpath.exe to set a proper path for the _DEFAULT_INSTALL_PATH for uhd_images_downloader

- Move uhd_images_downlader.py and usrp2_card_burner.py to ${MINGW_PREFIX}/bin and change
  their names to uhd_images_downloader and usrp_card_burner respectively. The reflects the
  contents of /usr/bin in the arch package.

- Re enable @ognevny 's fix to -DUHD_PYTHON_DIR that was deleted in error by my first push.

### CODE REVIEW

**Comment by ognevny** [comment]
it's better to rebase your branch and squash the PR into one commit

**Comment by chrisjohgorman** [comment]
@ognevny I'm sorry to say my git skills are not the greatest.  I have made a mistake with the rebase and squash, that seemed so simple.  I ran rebase -i $HEAD~2 for the two commits, but then couldn't get it pushed.  I will delete the branch and start over.

**Comment by ognevny** [comment]
first, you ran `git rebase master`. you should have master branch up-to-date with upstream's master. then you should resolve conflicts, run `git add .` and `git rebase --continue`. after all you can commit it, then run `git push --force-with-lease`. squashing is easier, run `git reset --soft HEAD@n, where n is number of commits, then `git add .` and commit. pushing also with `git push --force-with-lease`

**Comment by chrisjohgorman** [comment]
Thank you Maksim, I will follow your instructions.

**Comment by chrisjohgorman** [comment]
@ognevny, I have created a state with git that I can't figure my way out of.  So I will delete my branch and start over.  Thank you for your attempted assistance.

**Comment by ognevny** [comment]
rustc dev guide has a section about rebases: https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts

**Comment by chrisjohgorman** [comment]
Thank you Maksim.  I'll check it out.

**Pull request closed without merging**
