### PR TITLE
Update llama.cpp

### PR DESCRIPTION
**Pull request by Kreijstal**
also adding mingw64 as target

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Please, remove mingw64 and update pkgver properly.

**Comment by Kreijstal** [comment]
> Please, remove mingw64, update pkgver properly and use a better commit message.

It compiles using mingw64, and it runs, what's the problem?

**Comment by MehdiChinoune** [comment]
> > Please, remove mingw64, update pkgver properly and use a better commit message.
> 
> It compiles using mingw64, and it runs, what's the problem?

We are pushing people to use UCRT64, because at certain time MINGW64 will be dropped (in the far future).

**Comment by Kreijstal** [comment]
> > > Please, remove mingw64, update pkgver properly and use a better commit message.
> > 
> > 
> > It compiles using mingw64, and it runs, what's the problem?
> 
> We are pushing people to use UCRT64, because at certain time MINGW64 will be dropped (in the far future).

Yeah, but why wouldn't you support mingw64 if you can, makes no sense to me, like https://github.com/lazka/MINGW-packages/commit/2dc9224e431e18359efa4e7b63cc8c65e602112b , anyway, the commit message is based on the tag on the github repository, what would be the right version, anyway?

**Comment by MehdiChinoune** [comment]
Please, Fix pkgver.
Just change the commit and makepkg-mingw will fix it for you.

**Comment by Kreijstal** [comment]
> Please, Fix pkgver. Just change the commit and makepkg-mingw will fix it for you.

I will, just tell me what should pkgver should be...? I am getting it from the github repo...

**Comment by MehdiChinoune** [comment]
> > Please, Fix pkgver. Just change the commit and makepkg-mingw will fix it for you.
> 
> I will, just tell me what should pkgver should be...? I am getting it from the github repo...

I said, just run makepkg-mingw and it will update it for you.

**Pull request merged**
