### PR TITLE
hub 2.14.2

### PR DESCRIPTION
**Pull request by tschoonj**
Long time user, first time contributor... 

Please let me know if I screwed up!

### CODE REVIEW

**Comment by Biswa96** [comment]
Mistake! pkgrel should be 1.

**Comment by tschoonj** [comment]
Ah sorry! Do I open a PR to fix this?

**Comment by lazka** [comment]
oops, thanks, fixed in master

**Comment by Biswa96** [comment]
Also some files installed in `/usr` folder instead of `/mingw` one.

**Comment by tschoonj** [comment]
That was already the case with the previous version.

**Comment by lazka** [comment]
We should really show a file tree of the package content in CI

**Pull request merged**
