### PR TITLE
meson: Update to 1.2.2

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by ognevnydemon** [comment]
forgot to delete patches

**Comment by lazka** [comment]
thanks

**Comment by MehdiChinoune** [comment]
I think there is a regression, gexiv2 was building fine before this update now it fails:
```
ninja: error: 'D:/M/msys64/mingw32/bin/glib-mkenums', needed by 'gexiv2/gexiv2-enums.h', missing and no known rule to make it
```
but glib-mkenums.exe already exists

**Comment by Biswa96** [comment]
It is related to this upstream issue https://github.com/mesonbuild/meson/issues/12271

**Comment by MehdiChinoune** [comment]
But It started failing only with this update.

**Comment by lazka** [comment]
#18659 should fix it

**Pull request merged**
