### PR TITLE
pupnp: Update to version 1.12.1

### PR DESCRIPTION
**Pull request by stahta01**
I was able to install both 32 and 64 bit versions of package. I have no idea of how to test if they work.

See #6090

Tim S.

### CODE REVIEW

**Comment by Biswa96** [comment]
Any plan to upstream the patches?

**Comment by stahta01** [comment]
> Any plan to upstream the patches?

The patches are all from the upstream repo.

Tim S.

**Comment by lazka** [comment]
@emptyVoid since you did some upstream work, does this look OK to you?

**Comment by emptyVoid** [comment]
LGTM.

Though I haven't tried linking `libupnp` built with MinGW using `pkg-config` thus it might still need the following part from original patches:
https://github.com/msys2/MINGW-packages/blob/29a90e7702fe3056f4d389ad7a4e5d3b5d8e321f/mingw-w64-pupnp/002-libupnp-win32.patch#L1-L9

**Comment by stahta01** [comment]
I will update "002-libupnp-win32.patch". Tim S.

**Comment by stahta01** [comment]
I have done the change suggested by emptyVoid. Tim S.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
