### PR TITLE
Update

### PR DESCRIPTION
**Pull request by naveen521kk**
https://github.com/naveen521kk/msys2-updator

### CODE REVIEW

**Comment by lazka** [comment]
ok :)

but who checks for dependency changes?

**Comment by naveen521kk** [comment]
> but who checks for dependency changes? I guess me

That looks worse though, checking through some 200 packages isn't that simple. Maybe enable checks so we can run their test suite and check it? Or let's make it work with that `updator`? Got any idea's on how to? AFAIK, PyPI API provides some info about this, like [`this`](https://pypi.org/pypi/Sphinx/json) and it can be used for checking dependency. And for now, this is only PyPi things are here.

**Comment by naveen521kk** [comment]
Also, this would be the case for the first time, if it runs daily, then things would be easy :)

**Comment by mati865** [comment]
For Python you can use https://github.com/wimglenn/johnnydep, I had link to similar tool for library dependencies but cannot find it right now.

**Comment by naveen521kk** [comment]
This PR is only for python package, thanks :)

**Comment by naveen521kk** [comment]
Ok, I think it would better to do things smaller in number and also I would try implementing a dependency handler inside it, so things don't be like this, instead would be more organized.

**Pull request closed without merging**
