### PR TITLE
Fix clang builds

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
@lazka Is there any issue building dbus-glib in CI? I can build it in my setup but CI shows

```
Compilation failed: Failed to execute child process (Permission denied)
```

**Comment by Biswa96** [comment]
@lazka Is there any issue building dbus-glib in CI? I can build it in my setup but CI shows

```
Compilation failed: Failed to execute child process (Permission denied)
```

**Comment by jeremyd2019** [comment]
Yeah, https://github.com/msys2/MINGW-packages/pull/8581

**Comment by Biswa96** [comment]
Well then, I have removed the dbus-glib commit. The dbus-glib can be manually updated by members.

**Pull request merged**
