### PR TITLE
gtk3: update to 3.24.9

### PR DESCRIPTION
**Pull request by Adsun701**
This updates gtk3 to 3.24.9.

### CODE REVIEW

**Comment by lazka** [comment]
@Adsun701 fyi, I'm currently looking into moving it to meson.

**Comment by Adsun701** [comment]
@lazka Thanks for letting me know. Should I close or keep this pull request?

**Comment by lazka** [comment]
You can keep it open. I just wanted to avoid us doing duplicated work re meson.

**Comment by Adsun701** [comment]
@lazka OK. Thanks.

**Pull request merged**
