### PR TITLE
Adjust PKGBUILDs for CPPFLAGS removal from makepkg

### PR DESCRIPTION
**Pull request by lazka**
See https://github.com/msys2/MSYS2-packages/issues/4860 It was moved from CPPFLAGS to CFLAGS/CXXFLAGS.

### CODE REVIEW

**Comment by ognevny** [comment]
for rufus remove `unset CPPFLAGS`. instead remove `-D__USE_MINGW_ANSI_STDIO=1` from it, as upstream redefines it to 0

**Comment by lazka** [comment]
> for rufus remove `unset CPPFLAGS`. instead remove `-D__USE_MINGW_ANSI_STDIO=1` from CFLAGS, as upstream redefines it to 0

thanks, I hadn't looked for "unset". rufus ignores CFLAGS (should we fix that?), and even if it would it would override our default, so I think it is fine. The unset could be removed though.

**Comment by ognevny** [comment]
> > for rufus remove `unset CPPFLAGS`. instead remove `-D__USE_MINGW_ANSI_STDIO=1` from CFLAGS, as upstream redefines it to 0
> 
> thanks, I hadn't looked for "unset". rufus ignores CFLAGS (should we fix that?), and even if it would it would override our default, so I think it is fine. The unset could be removed though.

oh I didn't see it. understood

**Comment by lazka** [comment]
the check thing is a false positive, so merging

**Pull request merged**
