### PR TITLE
rebuild packages for Qt 6.8

### PR DESCRIPTION
**Pull request by mmuetzel**
Rebuild the packages for which the package grokker reported an ABI incompatibility with Qt 6.8.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Oops. `pyside6` actually needs an update. See #22300.

**Comment by Biswa96** [comment]
Thanks, I was actually planning to do this after pyside.

**Comment by mmuetzel** [comment]
Oops. Sorry if I messed with your plans.

I have the necessary patches for mkvtoolnik ready and could push them here if you don't prefer to do the update yourself.

**Comment by lazka** [comment]
oh, I missed that again, sorry

**Comment by mmuetzel** [comment]
I should have waited after I had built everything locally. But "what could go wrong on some simple rebuilds"? 😉

Building `qt-creator` on MINGW64 fails with this error for me locally:
```
In file included from D:/repo/MSYS2/MINGW-packages/mingw-w64-qt-creator/src/qt-creator-opensource-src-14.0.1/src/plugins/appstatisticsmonitor/idataprovider.cpp:20:
C:/msys64/mingw64/include/psapi.h: At global scope:
C:/msys64/mingw64/include/psapi.h:166:28: error: expected ')' before '*' token
  166 |   typedef WINBOOL (CALLBACK *PENUM_PAGE_FILE_CALLBACKW) (LPVOID pContext,PENUM_PAGE_FILE_INFORMATION pPageFileInfo,LPCWSTR lpFilename);
      |                   ~        ^~
      |                            )
C:/msys64/mingw64/include/psapi.h:167:28: error: expected ')' before '*' token
  167 |   typedef WINBOOL (CALLBACK *PENUM_PAGE_FILE_CALLBACKA) (LPVOID pContext,PENUM_PAGE_FILE_INFORMATION pPageFileInfo,LPCSTR lpFilename);
      |                   ~        ^~
      |                            )
C:/msys64/mingw64/include/psapi.h:169:34: error: 'PENUM_PAGE_FILE_CALLBACKW' was not declared in this scope; did you mean 'PENUM_PAGE_FILE_CALLBACK'?
  169 |   WINBOOL WINAPI EnumPageFilesW (PENUM_PAGE_FILE_CALLBACKW pCallBackRoutine,LPVOID pContext);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  PENUM_PAGE_FILE_CALLBACK
C:/msys64/mingw64/include/psapi.h:169:84: error: expected primary-expression before 'pContext'
  169 |   WINBOOL WINAPI EnumPageFilesW (PENUM_PAGE_FILE_CALLBACKW pCallBackRoutine,LPVOID pContext);
      |                                                                                    ^~~~~~~~
C:/msys64/mingw64/include/psapi.h:169:92: error: expression list treated as compound expression in initializer [-fpermissive]
  169 |   WINBOOL WINAPI EnumPageFilesW (PENUM_PAGE_FILE_CALLBACKW pCallBackRoutine,LPVOID pContext);
      |                                                                                            ^
C:/msys64/mingw64/include/psapi.h:170:34: error: 'PENUM_PAGE_FILE_CALLBACKA' was not declared in this scope; did you mean 'PENUM_PAGE_FILE_CALLBACK'?
  170 |   WINBOOL WINAPI EnumPageFilesA (PENUM_PAGE_FILE_CALLBACKA pCallBackRoutine,LPVOID pContext);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  PENUM_PAGE_FILE_CALLBACK
C:/msys64/mingw64/include/psapi.h:170:84: error: expected primary-expression before 'pContext'
  170 |   WINBOOL WINAPI EnumPageFilesA (PENUM_PAGE_FILE_CALLBACKA pCallBackRoutine,LPVOID pContext);
      |                                                                                    ^~~~~~~~
C:/msys64/mingw64/include/psapi.h:170:92: error: expression list treated as compound expression in initializer [-fpermissive]
  170 |   WINBOOL WINAPI EnumPageFilesA (PENUM_PAGE_FILE_CALLBACKA pCallBackRoutine,LPVOID pContext);
      |                                                                                            ^
```

Is that an issue with the MinGW headers? Or is it more likely that there is something wrong when they are including `psapi.h`? (It looks like `CALLBACK` is undefined.)

**Comment by Biswa96** [comment]
Either `CALLBACK` is being undefined or redefined or used as an variable etc.

**Comment by mmuetzel** [comment]
If I copy the following (which I found in `minwindef.h`) close to the top of `psapi.h`, building succeeds:
```
#ifndef CALLBACK
#if defined(_ARM_)
#define CALLBACK
#else
#define CALLBACK __stdcall
#endif
#endif
```

**Comment by Biswa96** [comment]
llvm had a similar issue https://github.com/llvm/llvm-project/commit/54bff1522fc863329894d875d54c2fe4cd1b4f3f

**Comment by mmuetzel** [comment]
Found the following in a header that is included in almost each of their compilation units (in `qtcreator_pch.h`):
```
// LLVM 12 comes with CALLBACK as a template argument
#undef CALLBACK
```

(That's probably to work around the issue that was fixed in LLVM with the patch you pointed out.)

I'll try if it builds correctly without that.

**Comment by mmuetzel** [comment]
But shouldn't `psapi.h` still be includable without other prior headers? I.e., shouldn't it get the definition of `CALLBACK` from somewhere?
I can't find how it would do that...

**Pull request merged**
