### PR TITLE
Add package for Enlightenment Foundation Libraries

### PR DESCRIPTION
**Pull request by rggammon**
Add package for Enlightenment Foundation Libraries

### CODE REVIEW

**Comment by lazka** [comment]
I've pushed some fixes to make the packaging work, but untested.

**Comment by rggammon** [comment]
Thank you for the help! If I try to compile based on -
https://docs.enlightenment.org/api/evas/doc/html/

> gcc `pkg-config --libs evas ecore-evas` evas-text.o -o evas-text

... I have some issues linking to figure out:

> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: evas-text.o:evas-text.c:(.text+0xfee): undefined reference to `__imp_ecore_evas_shutdown'

> nm /mingw64/lib/libecore_evas.dll.a | grep __imp_ecore_evas_shutdown
> 0000000000000000 I __imp_ecore_evas_shutdown

**Comment by lazka** [comment]
wrong link order

```
gcc  evas-text.o `pkg-config --libs evas ecore-evas` -o evas-text
```

**Comment by rggammon** [comment]
evas-text and some of the other examples are working for me, after removing install.patch

**Pull request merged**
