### PR TITLE
python-pywavelets: update to 1.5.0

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by lazka** [comment]
https://github.com/mesonbuild/meson/issues/12547

**Comment by kmilos** [comment]
Hm... It builds fine on my (up to date) machine?!

**Comment by lazka** [comment]
ah, wrong pkg-config, needs mingw one

**Comment by kmilos** [comment]
Any reason why pkgconf isn't a dependency of meson-python then (or meson for that matter)? It's not listed as a dependency in the project docs...

**Comment by lazka** [comment]
I guess in theory it should also work without it, assuming the meson project doesn't need it for other deps. But that's broken right now.

**Comment by lazka** [comment]
But yeah, one could say it's such a common dependency that we might as well make it a default.

**Comment by kmilos** [comment]
> But yeah, one could say it's such a common dependency that we might as well make it a default.

Seems to be the case when it comes to cmake...

**Comment by lazka** [comment]
#19204

**Pull request merged**
