### PR TITLE
gst-editing-services: Update to 1.18.3

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
There is a workaround to set correct installation directory of python files. Without the workaround, meson chooses `Python38` instead of `python3.8`.. Please check it.

**Comment by lazka** [comment]
hm, what about

```diff
diff --git a/meson.build b/meson.build
index 9d574c6e..fe837acf 100644
--- a/meson.build
+++ b/meson.build
@@ -268,6 +268,7 @@ subdir('docs')
 override_detector = '''
 import sys
 import os
+from distutils.sysconfig import get_python_lib
 
 prefix = sys.argv[1]
 version = sys.version_info
@@ -283,14 +284,7 @@ if os.path.commonprefix([overrides_path, prefix]) == prefix:
 
 # Otherwise follow python's way of install site packages inside
 # the provided prefix
-if os.name == 'posix':
-    print(os.path.join(
-        prefix, 'lib', 'python%d.%d' % (version.major, version.minor),
-        'site-packages', 'gi', 'overrides'))
-else:
-    print(os.path.join(
-        prefix, 'Lib', 'Python%d%d' % (version.major, version.minor),
-        'site-packages', 'gi', 'overrides'))
+print(os.path.join(get_python_lib(prefix=prefix), 'gi', 'overrides'))
 '''
 pygi_override_dir = get_option('pygi-overrides-dir')
 if pygi_override_dir == ''
```

**Comment by Biswa96** [comment]
Zero idea. I think that should be in upstream.

**Comment by lazka** [comment]
ok

**Comment by Biswa96** [comment]
BTW, also try to enable the `python` option in pkgbuild. You'll get a surprise.

**Comment by lazka** [comment]
ok :) not on windows right now.. I'll have a look later

**Comment by lazka** [comment]
I don't get what python is supposed to do.. lots of hardcoded broken things..

**Pull request merged**
