### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by TwentyOneSolutions**
Resolves issues #6 and #7

### CODE REVIEW

**Comment by Alexpux** [comment]
Please use repo from https://github.com/Alexpux/MINGW-packages
Here is not synced version of it.

**Comment by TwentyOneSolutions** [comment]
I didn't realize that I was looking at the wrong repository.  The one that you linked to has newer code and does not have some of these issues so I will look there.  

I think that the readme.MD file in this repository should point to the repository that you pointed to.

Thank you.

**Comment by mingwandroid** [comment]
.. Or we should remove these ones?

**Comment by TwentyOneSolutions** [comment]
it will be much less confusing if you close these ones and post a link to the correct ones.

**Pull request closed without merging**
