### PR TITLE
add package: simple-mail

### PR DESCRIPTION
**Pull request by zgyarmati**

### CODE REVIEW

**Comment by Biswa96** [comment]
* Append `(mingw-w64)` in `pkgdesc`. 
* `patch` in `makedepends`, Why?

**Comment by Biswa96** [comment]
* Append `(mingw-w64)` in `pkgdesc`. 
* `patch` in `makedepends` maybe removed.

**Comment by Biswa96** [comment]
* Append `(mingw-w64)` in `pkgdesc`. 
* `patch` in `makedepends` may be removed.

**Comment by zgyarmati** [comment]
Thanks for the review, both of the mentioned issues are fixed.
Please feel free to squash these commits when merging.

**Pull request merged**
