### PR TITLE
dbus-glib: update to 0.112

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by jeremyd2019** [comment]
well, at least the error I saw with clang is showing up everywhere, so it's not some obscure clang-specific thing 😉

**Comment by neheb** [comment]
```
 Compilation failed: Failed to execute child process (Permission denied)
```

Locally this compiles under MinGW64

**Comment by jeremyd2019** [comment]
oh, I guess the error I was seeing was only UCRT64 and CLANG64.

**Comment by neheb** [comment]
added random autoreconf.

**Comment by Biswa96** [comment]
@lazka Would you like to manually build/update this package fix? It can be built without any issue, at least in my setup.

**Pull request merged**
