### PR TITLE
gdk-pixbuf 2.42.4

### PR DESCRIPTION
**Pull request by lovetox**

### CODE REVIEW

**Comment by lazka** [comment]
feel free to disable the docs for now

**Comment by lovetox** [comment]
But they work on my machine if we install the correct deps

where do i have to add them?

to makedepends or depends in PKGBUILD?

**Comment by lazka** [comment]
you can try makedepend on `${MINGW_PACKAGE_PREFIX}-gi-docgen`

**Comment by Biswa96** [comment]
Reset `pkgrel` to 1.

**Comment by lazka** [comment]
I guess the gtk-doc dependency can be removed as well now

**Comment by lovetox** [comment]
Ok will do

**Comment by lazka** [comment]
thanks!

**Pull request merged**
