### PR TITLE
New package: deno

### PR DESCRIPTION
**Pull request by ArchGuyWu**

### CODE REVIEW

**Comment by ognevny** [comment]
MSVC flags is somehow set for MinGW compilers. it's totally wrong

**Comment by ArchGuyWu** [comment]
> MSVC flags is somehow set for MinGW compilers. it's totally wrong

Yes, and it seems to need many patches.

**Comment by ognevny** [comment]
it's better to remove this build flag

**Comment by ArchGuyWu** [comment]
> it's better to remove this build flag

Ok, I'll remove it if it makes the build fail.

**Comment by raedrizqie** [comment]
this package uses v8.. can it link with system v8 so that you dont have to patch the internal v8?

**Comment by ArchGuyWu** [comment]
> this package uses v8.. can it link with system v8 so that you dont have to patch the internal v8?

No, I've searched its repo.

**Comment by ognevny** [comment]
```
  D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
```

why it uses `lld-link`?

**Comment by ArchGuyWu** [comment]
> ```
>   D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
> ```
> 
> why it uses `lld-link`?

Don't know, I'll try to set [RUSTY_V8_ARCHIVE](https://github.com/denoland/rusty_v8?tab=readme-ov-file#the-rusty_v8_archive-environment-variable) .

**Comment by raedrizqie** [comment]
> ```
>   D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
> ```
> 
> why it uses `lld-link`?

because v8's BUILD.gn assumes we are compiling with MSVC.. this wont work without patching

**Comment by ognevny** [comment]
> > ```
> >   D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
> > ```
> > 
> > why it uses `lld-link`?
> 
> Don't know, I'll try to set [RUSTY_V8_ARCHIVE](https://github.com/denoland/rusty_v8?tab=readme-ov-file#the-rusty_v8_archive-environment-variable) .

we don't have V8 static library

**Comment by ArchGuyWu** [comment]
> > > ```
> > >   D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > why it uses `lld-link`?
> > 
> > 
> > Don't know, I'll try to set [RUSTY_V8_ARCHIVE](https://github.com/denoland/rusty_v8?tab=readme-ov-file#the-rusty_v8_archive-environment-variable) .
> 
> we don't have V8 static library

Ok, how can I add static library for package v8 ?

**Comment by raedrizqie** [comment]
> > > ```
> > >   D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > why it uses `lld-link`?
> > 
> > 
> > because v8's BUILD.gn assumes we are compiling with MSVC.. this wont work without patching
> 
> Can we enable both shared and static library for package v8?

it should be possible i think

**Comment by ArchGuyWu** [comment]
> > > > ```
> > > >   D:\M\msys64\ucrt64\bin\lld-link.exe /lib /OUT:obj/v8/v8_libbase.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/v8/v8_libbase.lib.rsp
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > why it uses `lld-link`?
> > > 
> > > 
> > > because v8's BUILD.gn assumes we are compiling with MSVC.. this wont work without patching
> > 
> > 
> > Can we enable both shared and static library for package v8?
> 
> it should be possible i think

I'll add another package mingw-w64-v8-static later.

**Comment by ArchGuyWu** [comment]
The extra gn args for static library:
`v8_static_library=true v8_monolithic=true`

The extra ninja arg for static library:
`v8_monolithic`

**Comment by ArchGuyWu** [comment]
It needs extra config and build step, how can I simplify the build script?

**Comment by raedrizqie** [comment]
i think you need to build them separately..
1. build in `${_buildtype}-${MSYSTEM`
2. build in `${_buildtype}-${MSYSTEM-static`

then, just copy only the static libs into the pkgdir

**Comment by ArchGuyWu** [comment]
> i think you need to build them separately..
> 
> 1. build in `${_buildtype}-${MSYSTEM}`
> 2. build in `${_buildtype}-${MSYSTEM}-static`
> 
> then, just copy only the static libs into the pkgdir

I searched msys2 repo, and found that some packages have both shared and static library, too.

**Comment by raedrizqie** [comment]
yes.. you dont need to create a separate package

**Comment by raedrizqie** [comment]
why dont you make a separate PR for v8? dont forget to bump pkgrel

**Comment by ArchGuyWu** [comment]
> why dont you make a separate PR for v8? dont forget to bump pkgrel

Because I need to test whether deno can build with msys2 prebuilt v8 static library first.

**Comment by ArchGuyWu** [comment]
Can you review these changes for v8? @raedrizqie 
I can't create v8 static library contains "v8_libbase v8_libplatform v8".

**Comment by raedrizqie** [comment]
i could try updating v8 if you want?

for static build, i think you dont have to add this: `_v8_static_library=true`

just `is_component_build=false` and `_v8_monolithic=true` will do..

**Comment by ArchGuyWu** [comment]
> i could try updating v8 if you want?
> 
> for static build, i think you dont have to add this: `_v8_static_library=true`
> 
> just `is_component_build=false` and `_v8_monolithic=true` will do..



> i could try updating v8 if you want?
> 
> for static build, i think you dont have to add this: `_v8_static_library=true`
> 
> just `is_component_build=false` and `_v8_monolithic=true` will do..

Ok, I'll try to get static library first, and if failing when building deno, I'll ping you.

**Comment by raedrizqie** [comment]
libv8_monolith.a is in /obj -> `install -Dm755 out/${_buildtype}-${MSYSTEM}-static/obj/libv8_monolith.a ..`

**Comment by ArchGuyWu** [comment]
What's wrong with this?

```
  [1807/1807] AR obj/libv8_monolith.a
  ==> Starting package()...
  install: cannot stat 'out/Release-CLANG64-static/*.a': No such file or directory
```

```
  # generate build files for static library
  ${MINGW_PREFIX}/bin/gn gen out/${_buildtype}-${MSYSTEM}-static --args="${_gn_args} is_component_build=false v8_monolithic=true v8_use_external_startup_data=false"

  ${MINGW_PREFIX}/bin/ninja -C out/${_buildtype}-${MSYSTEM}-static v8_monolith
```

**Comment by ArchGuyWu** [comment]
> libv8_monolith.a is in /obj -> `install -Dm755 out/${_buildtype}-${MSYSTEM}-static/obj/libv8_monolith.a ..`

Thanks.

**Comment by ArchGuyWu** [comment]
> libv8_monolith.a is in /obj -> `install -Dm755 out/${_buildtype}-${MSYSTEM}-static/obj/libv8_monolith.a ..`

Just providing a prebuilt v8 static library to rusty_v8 seems not helpful, it also needs prebuilt rust binding.

**Comment by ArchGuyWu** [comment]
I'll cancel this pull request, and add another package called [bun](https://bun.sh/).

**Pull request closed without merging**
