### PR TITLE
gr: Update to 0.54.0

### PR DESCRIPTION
**Pull request by kojix2**
Hi!
I will send you a libgr update. 
Thank you for maintaining Mingw.

### CODE REVIEW

**Comment by Biswa96** [comment]
Reset `pkgrel` variable to 1.

**Comment by kojix2** [comment]
Thank you for pointing this out. I've fixed it.

**Comment by kojix2** [comment]
'Some checks were not successful'
Well, how can I fix it?

**Comment by Biswa96** [comment]
I have restarted the CI. The checks are now successful. Sometimes (1 in 100) CI can not download packages from mirrors. Just a side effect of using mirrors. Hope GitHub allows pull request's author to restart CI like GitLab does.

**Comment by kojix2** [comment]
Thanks!

**Pull request merged**
