### PR TITLE
Add sdl12-compat

### PR DESCRIPTION
**Pull request by lazka**
try to build it as a normal library without -nostdlib -static-libgcc stuff, which breaks for example stack protector. I might be missing something though.

Also no "replaces" for now, until we are sure it can replace sdl1

### CODE REVIEW

**Comment by Biswa96** [comment]
Some related discussion https://discord.com/channels/792780131906617355/1059806620353318993/1100325471410978846

**Comment by lazka** [comment]
thanks. any objections to this hackery then?

**Comment by Biswa96** [comment]
No idea.

**Comment by lazka** [comment]
Let's give it a try then. At least the examples run fine here.

**Pull request merged**
