### PR TITLE
meson: add optdepends on sccache and ccache

### PR DESCRIPTION
**Pull request by ognevny**
see https://mesonbuild.com/Feature-autodetection.html#ccache and https://mesonbuild.com/Release-notes-for-0-61-0.html#added-support-for-sccache

### CODE REVIEW

**Comment by ognevny** [comment]
any objections?

**Comment by Biswa96** [comment]
This not required in my opinion. One can install sccache/ccache and choose to use it without meson. Or, meson does not need sccache/ccache for general use cases.

**Comment by ognevny** [comment]
> This not required in my opinion. One can install sccache/ccache and choose to use it without meson. Or, meson does not need sccache/ccache for general use cases.

that's why I added them to `optdepends`. I accidentally found, that meson supports `sccache` without any extra options to be passed

**Comment by lazka** [comment]
fair enough I guess. It's just one of many things meson can use, but a very useful and easy to miss one. I've never used sccache though, only ccache.

**Pull request merged**
