### PR TITLE
Update Vala to 0.54.1

### PR DESCRIPTION
**Pull request by taozuhong**
Update Vala to 0.54.1

### CODE REVIEW

**Comment by lazka** [comment]
vala-language-server needs a rebuild

**Comment by taozuhong** [comment]
submit it with the Vala package?

**Comment by lazka** [comment]
yes, this PR

**Comment by taozuhong** [comment]
Done as your suggestion, but I don't know why.

**Comment by lazka** [comment]
```
$ ntldd /mingw64/bin/vala-language-server.exe
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x000002204a4c0000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x000002204a4c0000)
        libgee-0.8-2.dll => C:\msys64\mingw64\bin\libgee-0.8-2.dll (0x000002204a660000)
        libgio-2.0-0.dll => C:\msys64\mingw64\bin\libgio-2.0-0.dll (0x000002204a720000)
        libglib-2.0-0.dll => C:\msys64\mingw64\bin\libglib-2.0-0.dll (0x000002204a8d0000)
        libgobject-2.0-0.dll => C:\msys64\mingw64\bin\libgobject-2.0-0.dll (0x000002204a4c0000)
        libjson-glib-1.0-0.dll => C:\msys64\mingw64\bin\libjson-glib-1.0-0.dll (0x000002204a2d0000)
        libjsonrpc-glib-1.0-1.dll => C:\msys64\mingw64\bin\libjsonrpc-glib-1.0-1.dll (0x000002204a2d0000)
        libvala-0.52-0.dll => C:\msys64\mingw64\bin\libvala-0.52-0.dll (0x000002204a660000)
```

Because vala-language-server.exe links against libvala-0.52-0.dll which your update removes

**Comment by taozuhong** [comment]
Got it, thanks. 

Anything else I could do?

**Comment by lazka** [comment]
> Anything else I could do?

no, all good, thanks (assuming this builds fine)

**Pull request merged**
