### PR TITLE
Update Packages

### PR DESCRIPTION
**Pull request by naveen521kk**

### CODE REVIEW

**Comment by lazka** [comment]
since the error is hard to find in the log:

```
2021-11-17T06:54:44.2798118Z ==> Making package: mingw-w64-python-virtualenv 20.10.0-1 (Wed, Nov 17, 2021  6:54:44 AM)
2021-11-17T06:54:45.1794934Z ==> Checking runtime dependencies...
2021-11-17T06:54:46.1870151Z ==> Installing missing dependencies...
2021-11-17T06:54:47.3752640Z error: target not found: mingw-w64-x86_64-python-backports.entry-points-selectable
```

**Comment by naveen521kk** [comment]
> tox 3.21.2 requires colorama, which is not installed.

https://github.com/msys2/MINGW-packages/pull/10162 has fixed it

**Comment by naveen521kk** [comment]
> spyder 5.1.5 has requirement python-lsp-server[all]<1.3.0,>=1.2.2, but you have python-lsp-server 1.3.1.

Not sure what to do. @lazka can we merge this PR?

**Comment by naveen521kk** [comment]
Thanks :)

**Pull request merged**
