### PR TITLE
Godot (some limitations)

### PR DESCRIPTION
**Pull request by Schala**
So with Christoph's mingw-w64-scons package available, I was able to build Godot with some success, but there are some unfortunate limitations:

- 32-bit build is failing with 'multiple definition' errors. 64-bit build seems alright, on the other hand
- Mono support will not build successfully
- Despite attempting to explicitly tell SCons not to use built-in third party sources, it utterly ignores them when passed. The resulting EXE is about 75 MB

### CODE REVIEW

**Comment by lazka** [comment]
Passing

```
builtin_freetype=no \
builtin_libpng=no \
builtin_zlib=no
```

changed something, but then it can't find ft2build.h.

**Comment by Schala** [comment]
I know. It has Bullet's header path incorrect too.

**Comment by lazka** [comment]
I'd be OK to merge this (with the changes I pushed). Any objections?

**Comment by Schala** [comment]
There is one issue I attempted to address. in godot_headers, `find .` was interpreting `.` literally.

**Comment by lazka** [comment]
I already fixed that by adding a trailing "/"

**Comment by Schala** [comment]
Alright, go ahead. I have godot-cpp coming soon, too.

**Comment by lazka** [comment]
ok

**Comment by lazka** [comment]
Thanks!

**Comment by mingwandroid** [comment]
How far off is mono support?

**Pull request merged**
