### PR TITLE
Bump wxWidgets 3.1 package to tagged release 3.1.5.

### PR DESCRIPTION
**Pull request by stambaughw**
* Minor housekeeping to clean up unused and/or unnecessary patches for
  wxWidgets 3.1.5.
* Remove custom compiler settings and use the defaults supplied by
  makepkg-mingw.  There doesn't appear to be any reason to do this any
  more.
* Don't create bin folder or move DLLs into it.  The 3.1.5 wxWidgets
  configuration appears to do this correctly already.

### CODE REVIEW

**Comment by stambaughw** [comment]
Please let me know if I need to do anything else to get this merged.  There are a bunch of fixes in wxWidgets 3.1.5 compared to 3.1.3 which the KiCad project needs for the upcoming version 6 stable release.

**Comment by lazka** [comment]
looks good, thanks

**Comment by stambaughw** [comment]
Thanks for the quick response.  Maybe at some point wxPhoenix can get packaged but that's proving to be a much tougher nut to crack.

**Comment by Biswa96** [comment]
Where is it?

**Comment by stambaughw** [comment]
@Biswa96 I'm assuming you mean where is the wxPhoenix project.  The wxPhoenix project (was wxPython) can be found [here](https://github.com/wxWidgets/Phoenix).  Another developer [took a swipe at it]( https://bitbucket.org/ustsv/testpkg_msys2) but it seems to be completely broken.

**Pull request merged**
