### PR TITLE
libwebp: define WEBP_EXTERN as __declspec(dllexport)

### PR DESCRIPTION
**Pull request by sezero**
Otherwise, the dlls export everything.

### CODE REVIEW

**Comment by Alexpux** [comment]
@sezero need more work because it will break static library

**Comment by sezero** [comment]
More work will further complicate things. Will leave it as is.  Closing.

**Comment by Alexpux** [comment]
@sezero see how it done in most other libraries. It not very complicated

**Comment by sezero** [comment]
> @sezero see how it done in most other libraries. It not very complicated.

I know how it's done (I maintain a couple of such libraries mysel),
but I'm not motivated to do it for this one :)  Maybe one day the
mainstream handles it properly. Until that day I'm withdrawing this PR.

**Pull request closed without merging**
