### PR TITLE
pango: backport font fallback list fix

### PR DESCRIPTION
**Pull request by lazka**
This restores the support of optional font fallbacks.

### CODE REVIEW

**Comment by lazka** [comment]
This also adds a warning to no upgrade to 1.44 because of https://gitlab.gnome.org/GNOME/pango/issues/385

@lillolollo

**Comment by lillolollo** [comment]
@lazka Thanks!

**Comment by Alexpux** [comment]
@lazka is it ready for merge?

**Comment by lazka** [comment]
@Alexpux yes! (I've heard that the next gimp release needs it)

**Pull request merged**
