### PR TITLE
qtbinpatcher: remove

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Qt is now relocatable.

### CODE REVIEW

**Comment by lazka** [comment]
qtbinpatcher is used in some install files if I'm not mistaken

**Comment by MehdiChinoune** [comment]
> qtbinpatcher is used in some install files if I'm not mistaken

It was used to relocate qt5 binaries/files https://github.com/Fsu0413/QQtPatcher#for-users-of-qt-514-or-later

**Comment by lazka** [comment]
I mean https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt5-static/qt5-MINGW32.install

should that be removed?

**Comment by MehdiChinoune** [comment]
I forgot to remove those.
an update to 5.15.9 is ready, but it requires a manual build for at least 3 envs!

**Pull request merged**
