### PR TITLE
totem-pl-parser: fix clang build

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by Biswa96** [comment]
Though the workaround works, it has to be modified in meson.build. If you can wait I would like to propose the change in upstream.

**Comment by raedrizqie** [comment]
ok.. no problem

**Comment by Biswa96** [comment]
Would you like to add a patch file from this merge request https://gitlab.gnome.org/GNOME/totem-pl-parser/-/merge_requests/46 ? It may solve the clang build.

**Comment by raedrizqie** [comment]
> Would you like to add a patch file from this merge request https://gitlab.gnome.org/GNOME/totem-pl-parser/-/merge_requests/46 ? It may solve the clang build.

its ok.. you can generate the patch and submit. thank you

**Pull request closed without merging**
