### PR TITLE
assimp: update to 5.1.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
maybe this has broken qt5?

```
2021-11-14T07:55:13.4996735Z assimpimporter.cpp: In member function 'void AssimpImporter::generateMaterial(aiMaterial*, QTextStream&, int)':
2021-11-14T07:55:13.5564897Z assimpimporter.cpp:956:36: error: 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_FACTOR' was not declared in this scope; did you mean 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE'?
2021-11-14T07:55:13.6935215Z   956 |             result = material->Get(AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_FACTOR, baseColorFactor);
2021-11-14T07:55:13.7511062Z       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-11-14T07:55:13.8846340Z       |                                    AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE
2021-11-14T07:55:13.9056724Z assimpimporter.cpp:964:62: error: 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_TEXTURE' was not declared in this scope; did you mean 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE'?
2021-11-14T07:55:13.9208509Z   964 |             QString baseColorImage = generateImage(material, AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_BASE_COLOR_TEXTURE, tabLevel + 1);
2021-11-14T07:55:14.0783906Z       |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-11-14T07:55:14.1181213Z       |                                                              AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE
2021-11-14T07:55:14.2077933Z assimpimporter.cpp:982:36: error: 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLIC_FACTOR' was not declared in this scope; did you mean 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE'?
2021-11-14T07:55:14.2345623Z   982 |             result = material->Get(AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLIC_FACTOR, metallicFactor);
2021-11-14T07:55:14.2352441Z       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-11-14T07:55:14.3132095Z       |                                    AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE
2021-11-14T07:55:14.3147848Z assimpimporter.cpp:992:36: error: 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_ROUGHNESS_FACTOR' was not declared in this scope; did you mean 'AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE'?
2021-11-14T07:55:14.3162250Z   992 |             result = material->Get(AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_ROUGHNESS_FACTOR, roughnessFactor);
2021-11-14T07:55:14.3174396Z       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-11-14T07:55:14.3213737Z       |                                    AI_MATKEY_GLTF_PBRMETALLICROUGHNESS_METALLICROUGHNESS_TEXTURE
2021-11-14T07:55:14.3215532Z make[6]: Leaving directory '/c/M/mingw-w64-qt5-pkgs/src/MINGW32/qtquick3d/src/plugins/assetimporters/assimp'
2021-11-14T07:55:14.3230118Z assimpimporter.cpp:1079:36: error: 'AI_MATKEY_GLTF_UNLIT' was not declared in this scope; did you mean 'AI_MATKEY_GLTF_MAPPINGID'?
2021-11-14T07:55:14.3239223Z make[5]: Leaving directory '/c/M/mingw-w64-qt5-pkgs/src/MINGW32/qtquick3d/src/plugins/assetimporters/assimp'
2021-11-14T07:55:14.3250008Z  1079 |             result = material->Get(AI_MATKEY_GLTF_UNLIT, isUnlit);
2021-11-14T07:55:14.3272661Z make[4]: Leaving directory '/c/M/mingw-w64-qt5-pkgs/src/MINGW32/qtquick3d/src/plugins/assetimporters'
2021-11-14T07:55:14.3297329Z       |                                    ^~~~~~~~~~~~~~~~~~~~
```

**Comment by lazka** [comment]
looks like things got renamed: https://github.com/assimp/assimp/pull/3952

**Comment by lazka** [comment]
we might need to revert that, or port qt5 to the new API

**Comment by MehdiChinoune** [comment]
It seems like reverting this PR is the only solution.

**Comment by lazka** [comment]
ok, thanks for trying

**Pull request merged**
