### PR TITLE
rust: rebuild for newer LLVM

### PR DESCRIPTION
**Pull request by ognevnydemon**
it will give some performance boost

### CODE REVIEW

**Comment by lazka** [comment]
> it will give some performance boost

just wondering, why is that?

**Comment by ognevnydemon** [comment]
> just wondering, why is that?

https://perf.rust-lang.org/compare.html?start=03a119b0b0e310d22d94399b24ed030056050f13&end=443c3161dd04f4c1b656a626f9079921bee9c326&stat=instructions:u

**Comment by Biswa96** [comment]
The title says `Comparing instructions:u between #114344 and #114048`. How is that related to llvm version?

**Comment by ognevnydemon** [comment]
> The title says `Comparing instructions:u between #114344 and #114048`. How is that related to llvm version?

because #114048 was about upgrade to 17.0.0

**Comment by ognevnydemon** [comment]
forgot that we need to backport some things. so I can leave this until 1.73.0 update

**Pull request closed without merging**
