### PR TITLE
clang: update 12.0.0-8

### LINKED ISSUE #8963: lld-12.0.0-6 LTO segfault on gcc prefixes
It seems lld-12.0.0-6 is also broken, see https://github.com/zufuliu/notepad2/actions/runs/951639414 for ucrt, x86_64 and i686 builds.
https://github.com/zufuliu/notepad2/runs/2863091346?check_suite_focus=true#step:7:203
> #0 0x00007ff7b65bef8c (C:\msys64\ucrt64\bin\ld.lld.exe+0x5ef8c)
> #1 0x00007ff7b658e915 (C:\msys64\ucrt64\bin\ld.lld.exe+0x2e915)
> #2 0x00007ff7b658fe5d (C:\msys64\ucrt64\bin\ld.lld.exe+0x2fe5d)
> #3 0x00007ff7b65921b6 (C:\msys64\ucrt64\bin\ld.lld.exe+0x321b6)
> #4 0x00007ff7b65928d6 (C:\msys64\ucrt64\bin\ld.lld.exe+0x328d6)
> #5 0x00007ff7b659d097 (C:\msys64\ucrt64\bin\ld.lld.exe+0x3d097)
> #6 0x00007ff7b656e79d (C:\msys64\ucrt64\bin\ld.lld.exe+0xe79d)
> #7 0x00007ff7b656eb04 (C:\msys64\ucrt64\bin\ld.lld.exe+0xeb04)
> #8 0x00007ff7b6569dfe (C:\msys64\ucrt64\bin\ld.lld.exe+0x9dfe)
> #9 0x00007ff7b657438f (C:\msys64\ucrt64\bin\ld.lld.exe+0x1438f)
>#10 0x00007ff7b657a2b8 (C:\msys64\ucrt64\bin\ld.lld.exe+0x1a2b8)
>#11 0x00007ff7b6729510 (C:\msys64\ucrt64\bin\ld.lld.exe+0x1c9510)
>#12 0x00007ff7b656237d (C:\msys64\ucrt64\bin\ld.lld.exe+0x237d)
>#13 0x00007ff7b691862e (C:\msys64\ucrt64\bin\ld.lld.exe+0x3b862e)
>#14 0x00007ff7b65613c1 (C:\msys64\ucrt64\bin\ld.lld.exe+0x13c1)
>#15 0x00007ff7b65614f6 (C:\msys64\ucrt64\bin\ld.lld.exe+0x14f6)
>#16 0x00007ffceac17974 (C:\Windows\System32\KERNEL32.DLL+0x17974)
>#17 0x00007ffcec04a2f1 (C:\Windows\SYSTEM32\ntdll.dll+0x5a2f1)
>clang++: error: linker command failed due to signal (use -v to see invocation)

While the 5 days ago lld-12.0.0-5 is working, see https://github.com/zufuliu/notepad2/actions/runs/934479857

_Originally posted by @zufuliu in https://github.com/msys2/MINGW-packages/issues/8868#issuecomment-864345963_

### LINKED ISSUE #9048: i686 lld crashes linking, mostly on Github runners
I have been building packages for clang32/i686 for several months now, and have not seen this until I started trying to build them in a Github actions workflow/hosted runner.  It seems to happen intermittently on different packages, but seems to be consistently happening when linking python, which uses LTO and PGO (this is the profile-instr-generate phase).

```
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Exec format error
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: D:/a/_temp/msys/msys64/clang32/bin/ld.lld -m i386pe --shared -Bdynamic -e _DllMainCRTStartup@12 --enable-auto-image-base -o libpython3.8.dll D:/a/_temp/msys/msys64/clang32/i686-w64-mingw32/lib/dllcrt2.o D:/a/_temp/msys/msys64/clang32/i686-w64-mingw32/lib/crtbegin.o -LD:/a/_temp/msys/msys64/clang32/i686-w64-mingw32/lib -LD:/a/_temp/msys/msys64/clang32/lib -LD:/a/_temp/msys/msys64/clang32/i686-w64-mingw32/sys-root/mingw/lib -LD:/a/_temp/msys/msys64/clang32/lib/clang/11.0.0/lib/windows --enable-auto-image-base --dynamicbase --no-seh --dynamicbase --no-seh --out-implib=libpython3.8.dll.a Modules/getbuildinfo.o Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/token.o Parser/myreadline.o Parser/parsetok.o Parser/tokenizer.o Objects/abstract.o Objects/accu.o Objects/boolobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/bytesobject.o Objects/call.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/codeobject.o Objects/c...
 #0 0x6df45608 HandleAbort (D:\a\_temp\msys\msys64\clang32\bin\libLLVM.dll+0x125608)
 msys2/CLANG-packages#1 0x754a5b22 (C:\Windows\System32\ucrtbase.dll+0xa5b22)
 msys2/CLANG-packages#2 0x6dd97a98 abort_message (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x77a98)
 msys2/MINGW-packages#9044 0x6dd7a616 __cxa_throw_bad_array_new_length (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x5a616)
 msys2/CLANG-packages#4 0x6ddabf20 (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x8bf20)
 msys2/CLANG-packages#5 0x6ddabfa8 (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x8bfa8)
 msys2/CLANG-packages#6 0x0250e1a4 
 msys2/CLANG-packages#7 0x0003fda4 
 msys2/CLANG-packages#8 0x6dd022ac _ZN9libunwind12UnwindCursorINS_17LocalAddressSpaceENS_13Registers_x86EE4stepEv (D:\a\_temp\msys\msys64\clang32\bin\libunwind.dll+0x22ac)
 msys2/CLANG-packages#9 0x6dd05db6 _Unwind_RaiseException (D:\a\_temp\msys\msys64\clang32\bin\libunwind.dll+0x5db6)
msys2/CLANG-packages#10 0x75443dfc (C:\Windows\System32\ucrtbase.dll+0x43dfc)
msys2/CLANG-packages#11 0x011cdcfc _ZN3lld4coff12LinkerDriver11enqueuePathEN4llvm9StringRefEbb (D:\a\_temp\msys\msys64\clang32\bin\ld.lld.exe+0xdcfc)
msys2/CLANG-packages#12 0x6dd782cb _ZNSt3__120__throw_system_errorEiPKc (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x582cb)
msys2/CLANG-packages#13 0x75642b66 (C:\Windows\System32\KERNELBASE.dll+0x112b66)
msys2/CLANG-packages#14 0x778ee697 (C:\Windows\SYSTEM32\ntdll.dll+0x3e697)
msys2/CLANG-packages#15 0x7564b627 (C:\Windows\System32\KERNELBASE.dll+0x11b627)
msys2/CLANG-packages#16 0x6dd7a315 _ZNSt3__121__libcpp_execute_onceEPPvPFvvE (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x5a315)
msys2/CLANG-packages#17 0x6dd7a49a _ZNSt3__116__libcpp_tls_getEl (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x5a49a)
msys2/CLANG-packages#18 0x6dd96b42 __cxa_get_globals (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x76b42)
msys2/CLANG-packages#19 0x6dd96e85 _ZSt11__terminatePFvvE (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x76e85)
msys2/CLANG-packages#20 0x6dd997d7 __cxa_throw (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x797d7)
msys2/CLANG-packages#21 0x6dd99762 __cxa_throw (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x79762)
msys2/CLANG-packages#22 0x6dd782ba _ZNSt3__120__throw_system_errorEiPKc (D:\a\_temp\msys\msys64\clang32\bin\libc++.dll+0x582ba)
msys2/CLANG-packages#23 0x011cdcfc _ZN3lld4coff12LinkerDriver11enqueuePathEN4llvm9StringRefEbb (D:\a\_temp\msys\msys64\clang32\bin\ld.lld.exe+0xdcfc)
msys2/CLANG-packages#24 0x011cd994 _ZN3lld4coff12LinkerDriver11enqueuePathEN4llvm9StringRefEbb (D:\a\_temp\msys\msys64\clang32\bin\ld.lld.exe+0xd994)
msys2/CLANG-packages#25 0x6df393d0 _ZN4llvm3sys2fs11getUniqueIDENS_5TwineERNS1_8UniqueIDE (D:\a\_temp\msys\msys64\clang32\bin\libLLVM.dll+0x1193d0)
msys2/MINGW-packages#9045 0x011c8025 _ZN3lld4coff12LinkerDriver4linkEN4llvm8ArrayRefIPKcEE (D:\a\_temp\msys\msys64\clang32\bin\ld.lld.exe+0x8025)
msys2/CLANG-packages#27 0x77908450 (C:\Windows\SYSTEM32\ntdll.dll+0x58450)
msys2/MINGW-packages#9046 0x77908450 (C:\Windows\SYSTEM32\ntdll.dll+0x58450)
msys2/MINGW-packages#9047 0x778ed925 (C:\Windows\SYSTEM32\ntdll.dll+0x3d925)
msys2/CLANG-packages#30 0x778ed49e (C:\Windows\SYSTEM32\ntdll.dll+0x3d49e)
msys2/CLANG-packages#31 0x778ed1e2 (C:\Windows\SYSTEM32\ntdll.dll+0x3d1e2)
msys2/CLANG-packages#32 0x7564081e (C:\Windows\System32\KERNELBASE.dll+0x11081e)
msys2/CLANG-packages#33 0x0002ed3a 
```

### PR DESCRIPTION
**Pull request by jeremyd2019**
A couple of patches were pushed, so it seems like a good time to start a 12.0.0-8.

- Fix handling of LTO comdats with nontrivial selection types.  Fixes #8963.
- Updated llvm-rc default triple patch to pushed version.
- Disable using `std::launch::async` on 32-bit Windows.  It seems there are issues spawning a ton of threads there.  Fixes #9048
- Use upstream fix for deadlocking lld on non-clean shutdown by using TerminateProcess.

Still outstanding:
- #9050.  There is a patch which seems to work, but so far just in a bug comment, and has been 'rescinded' as not the correct fix.
- #8868 which seems to be a truncated call offset/relocation generated from GCC emutls

### CODE REVIEW

**Comment by mati865** [comment]
We might need to enable `0305-use-TerminateProcess-instead-of-exit.patch` for clang subsystems as well or even better replace it with https://reviews.llvm.org/D102944. I've experienced deadlocks when building Rust on 32 thread machine 😢

**Comment by jeremyd2019** [comment]
> even better replace it with https://reviews.llvm.org/D102944

🎉 Too bad about rust, but great to have a less-hacky upstream alternative!

**Comment by mati865** [comment]
Are https://gist.github.com/jeremyd2019/c445a5312bfe49fb8b0192b10bd5710d#stdcall and https://gist.github.com/jeremyd2019/c445a5312bfe49fb8b0192b10bd5710d#cannot-link-dll still big problems?
Martin just fixed them on the main but I don't know if we should consider backporting them.

**Comment by jeremyd2019** [comment]
I don't really consider them a big issue, most of the packages with those issues have been patched now.

**Comment by jeremyd2019** [comment]
Is this "ready" now?  I was waiting on a fix for the X87 stackifier issue, but now not sure that one is forthcoming.  Also, no evidence of further movement on the lldb crash.  There are a couple of crash fixes in here though, that would be nice to release

**Comment by mati865** [comment]
I don't have anything more to include either.

**Pull request merged**
