### PR TITLE
New packages: (pt)scotch

### PR DESCRIPTION
**Pull request by okhlybov**

### CODE REVIEW

**Comment by lazka** [comment]
Why does it need to be split into two packages?

**Comment by okhlybov** [comment]
scotch is a sequential code, ptscotch is a MPI parallel extension to it

**Comment by lazka** [comment]
Is there a reason these can't be put into one package, like in Arch Linux?

**Comment by okhlybov** [comment]
The joint package will be carrying the msmpi dependency even for those who don't parallel version.

**Comment by lazka** [comment]
msmpi is just 3MB, so that's not a problem

**Comment by okhlybov** [comment]
Modified to build joint package.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
