### PR TITLE
groonga: update to Groonga 9.0.8

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by Alexpux** [comment]
@kenhys it already updated

**Comment by kenhys** [comment]
@Alexpux It seems that it still points to 9.0.6. What am I wrong?

**Comment by Alexpux** [comment]
@kenhys what you mean?
````
$ pacman -Ss groonga
mingw32/mingw-w64-i686-groonga 9.0.8-1
    An opensource fulltext search engine (mingw-w64)
mingw64/mingw-w64-x86_64-groonga 9.0.8-1
    An opensource fulltext search engine (mingw-w64)
````

**Comment by kenhys** [comment]
Ah, It seems that PKGBUILD itself is a bit old, so I've sent a PR, as it was already updated, so It's ok.

**Pull request closed without merging**
