### PR TITLE
winpthreads: Update to latest git

### LINKED ISSUE #6678: winpthreads build fails over "patch does not apply"
Building for mingw-64:
```
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sLf
```
Error:
```
Applying: Define __{de,}register_frame_info in fake libgcc_s
error: patch failed: mingw-w64-libraries/winpthreads/Makefile.am:7
error: mingw-w64-libraries/winpthreads/Makefile.am: patch does not apply
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Applying: Build winpthreads without __USE_MINGW_ANSI_STDIO
Patch failed at 0001 Build winpthreads without __USE_MINGW_ANSI_STDIO
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
==> ERROR: A failure occurred in prepare().
    Aborting...
```

### PR DESCRIPTION
**Pull request by lazka**
Drop a patch which is now upstream:
https://github.com/mirror/mingw-w64/commit/e82b4f5681c1e4a81f2ac22

Fixes #6678

### CODE REVIEW

**Comment by Biswa96** [comment]
I am not sure if winpthreads update also requires latest headers and crt. But there is an issue about dxva2 header file in mingw-w64 which needed to be fixed first.

**Comment by lazka** [comment]
There have only been three commits since then: https://github.com/mirror/mingw-w64/commits/master/mingw-w64-libraries/winpthreads Do you think it's ok?

**Comment by Biswa96** [comment]
Asking in IRC.

**Comment by mati865** [comment]
Crt and headers each other often depend on exactly the same commit. Winpthreads is less demanding, it's fine in this case.

**Pull request merged**
