### PR TITLE
pkgconf: update to 1.9.5 and add patch to disable sorting

### PR DESCRIPTION
**Pull request by 1480c1**
Based on work done by @MehdiChinoune, should fix https://github.com/msys2/MINGW-packages/issues/13390.

Tested by compiling FFmpeg and a bunch of other dependencies, and seems to work.

### CODE REVIEW

**Comment by lazka** [comment]
I guess there is no explanation as to why this fixes things?

**Comment by 1480c1** [comment]
Not really. I guess because qsort is unstable is the only real explanation? Not sure why it doesn't break on Linux, unless they don't test pure static compilation?

**Comment by MehdiChinoune** [comment]
Could this PR merged.

**Comment by lazka** [comment]
if you both feel reasonably confident, sure.

I was planning to write some pkgconf tests, but I can always do that later.

**Comment by 1480c1** [comment]
This PR could wait if you feel like you can get tests written soon, but would of course prefer to be merged sooner than later. As far as I know, nothing that I know of requires 1.9.5 vs our current version, as it seems 1.9+ is mainly performance and dependency resolving.

**Comment by lazka** [comment]
I'm busy over the weekend, so likely not too soon. Let's see :)

**Pull request merged**
