### PR TITLE
libepoxy: enable angle backend

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by lazka** [comment]
Just wondering, do you have any project in mind that would use this?

**Comment by raedrizqie** [comment]
Just trying to add EGL support in qemu, as @ZachBacon said on discord..

**Comment by Biswa96** [comment]
Should angleproject be mentioned as optional dependency with libepoxy? It seems that libepoxy detects EGL or GLESv2 at runtime.

**Comment by raedrizqie** [comment]
> Should angleproject be mentioned as optional dependency with libepoxy? It seems that libepoxy detects EGL or GLESv2 at runtime.

although it just do dynamic load of libEGL, gtk expect this entrypoint at runtime: `epoxy_eglBindApi` from libepoxy-0.dll

so, either add support to egl for epoxy or don't..

**Comment by Biswa96** [comment]
> gtk expect this entrypoint at runtime

Can you provide the reference of that in gtk code?

**Comment by raedrizqie** [comment]
replace libepoxy-0.dll with the old one (or one that compiled without egl enabled).. you will get that runtime error

**Comment by lazka** [comment]
There is some fallout from this, in case anyone wants to chime in: https://github.com/msys2/MINGW-packages/pull/16357

**Pull request merged**
