### PR TITLE
jack2: Add package

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/issues/6117

### CODE REVIEW

**Comment by Be-ing** [comment]
I'm confused. This doesn't build JackWeakAPI, this builds libjack which we discussed shouldn't be done in #6117.

**Comment by Biswa96** [comment]
> I'm confused. 

Me too 😄 Shouldn't weakjack be a different package? Don't weakjack require libjack? Don't libjack use JackWeakAPI.c?

**Comment by Biswa96** [comment]
In weakjack project, the README says "add weak_libjack.c to the build-source of your project". So, should weakjack be served as a package?

**Comment by Biswa96** [comment]
Any comment on the new packages. I have added qjackctl also.

**Pull request merged**
