### PR TITLE
python-jupyter* updates

### PR DESCRIPTION
**Pull request by raedrizqie**
depends on #18288

### CODE REVIEW

**Comment by raedrizqie** [comment]
rdeps check failed at
```
Pip Output (without reverse dependencies): mingw-w64-ucrt-x86_64-python-poetry-1.6.1-2-any.pkg.tar.zst
  Pip Check Failed for mingw-w64-ucrt-x86_64-python-poetry
  Running `pip check` didn't suceed. Maybe missing dependencies?
Here is what it failed.
build 0.10.0 requires colorama, which is not installed.
```

colorama is actually an optdepend in python-build, but it is listed under dependencies here:
https://github.com/pypa/build/blob/1fff01ed7440d5b5626fec31422026a4920b7764/pyproject.toml#L38

**Comment by Biswa96** [comment]
Would you like to force push the changes in a clean branch? Some commits like jupyter-events and jupyter-nbconvert updates are shown twice.

**Comment by raedrizqie** [comment]
ok, will do later when im home

**Comment by raedrizqie** [comment]
@Biswa96 rdeps check failed on spyder.. should i also update spyder?

**Pull request closed without merging**
