### PR TITLE
More OpenAI deps

### PR DESCRIPTION
**Pull request by Schala**
New:

- python-aiohttp-cors
- python-google-cloud-storage
- python-pytest-flake8
- python-ruamel-yaml
- python-trustme

Updated:

- python-aiohttp 3.7.2
- python-google-auth 1.23
- python-gsutil 4.55
- python-imgviz 1.2.3
- python-labelme (removal of unneeded .desktop file)
- python-multidict 5.0.2
- python-pathspec 0.8.1
- python-responses 0.12.1
- python-tifffile 2020.11.26
- python-tqdm 4.52
- python-trimesh 3.8.14
- python-yarl 1.6.3

### CODE REVIEW

**Comment by lazka** [comment]
puh.. this reverts various unrelated things..

**Comment by Schala** [comment]
What do you mean? I don't know of it changing anything other than what I specified.

**Comment by lazka** [comment]
Not sure, the diff seemed to include unrelated things, but I already linearized the git history in this PR, so no way to look at it now..

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
