### PR TITLE
portaudio: Build C++ binding with CMake

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/msys2/MINGW-packages/pull/10604

### CODE REVIEW

**Comment by Biswa96** [comment]
@volkanorhan Here is my idea. Please review. I would like to sent this in upstream first.

**Review by volkanorhan — APPROVED** [review]

**Comment by volkanorhan** [comment]
I approved this but maintenance of the previous one is much better.

**Comment by volkanorhan** [comment]
I reviewed this again. It seems OK. Thanks @Biswa96

**Comment by volkanorhan** [comment]
After then you merge this branch to master branch, I will update my https://github.com/msys2/MINGW-packages/pull/10605 pull request's branch, so libopenmtp's tests will be run again.

**Comment by Biswa96** [comment]
It seems that upstream has an open issue about building C++ bindings https://github.com/PortAudio/portaudio/issues/539. Developers are planning to separate the C++ bindings as different repository and the work is in progress but slow. We may have to carry the patches for long time 😩

**Comment by volkanorhan** [comment]
> It seems that upstream has an open issue about building C++ bindings [PortAudio/portaudio#539](https://github.com/PortAudio/portaudio/issues/539). Developers are planning to separate the C++ bindings as different repository and the work is in progress but slow. We may have to carry the patches for long time 😩

Yes, I took Be-ing's fork of portaudio and added some commits on his branch to support standalone build. I also made pull request on Be-ing's fork of portaudio.

I think that it is much easier to maintain my pull request (as a different package for portaudio C++ bindings).

**Comment by volkanorhan** [comment]
> > as a different package for portaudio C++ bindings
> 
> The source repository is same as of now. So, entirely separate package don't seem rational, IMO. Also have to change dependencies in other dependent packages. Whereas with one package is just a rebuild.

So, can you please merge this branch to master, @Biswa96?

**Comment by Biswa96** [comment]
Waiting for others opinions too...

**Comment by volkanorhan** [comment]
> Waiting for others opinions too...

Thanks for the information

**Pull request merged**
