### PR TITLE
python-jupyterlab/notebook: update to 4.1.1/7.1.0

### PR DESCRIPTION
**Pull request by podsvirov**
Looks like we should wait for the next release of the `notebook`...

### CODE REVIEW

**Comment by podsvirov** [comment]
The `check` is broken:
```
notebook 7.0.8 has requirement jupyterlab<4.1,>=4.0.2, but you have jupyterlab 4.1.0
```
but `jupyter notebook` (7.0.80) work for me with `jupyterlab` (4.1.0).

What about to merge this `PR` now?

**Comment by lazka** [comment]
> The `check` is broken:

Does `pip check` not fail for you?

**Comment by lazka** [comment]
Upstream added the version check in https://github.com/jupyter/notebook/issues/7248

**Comment by podsvirov** [comment]
> Does `pip check` not fail for you?

Yes. All work. I can launch `jupyter lab` or `jupyter notebook` and then in browser select `Open in Notebook` or `Open in JupyterLab` to switch environment.

**Comment by lazka** [comment]
You didn't answer my question.

Anyway, we can

* Wait for notebook 7.1.0 which would solve this
* Merge this as is, and get pip check errors until notebook gets updated

**Comment by podsvirov** [comment]
LGTM. Ready to merge. Please review.
Cc: @lazka, @Biswa96.

**Review by MehdiChinoune — APPROVED** [review]

**Pull request merged**
