### PR TITLE
clang: update 12.0.1-1

### LINKED ISSUE #9106: windres (clang) fails to build windows-default-manifest.
```
windres -F pe-x86-64 default-manifest.rc -o default-manifest.o
  llvm-rc: Error parsing file: expected ',', got "<assembly xmlns=""urn:schemas-microsoft-com:asm.v1"" manifestVersion=""1.0"">\n"
  make: *** [Makefile:28: default-manifest.o] Error 1
  ==> ERROR: A failure occurred in build().
      Aborting...
```

### PR DESCRIPTION
**Pull request by jeremyd2019**
backport several patches from upstream

* Update 32-bit std::async fix to committed patch. (llvm/llvm-project@7a7da69)
* Support for linking DLLs directly (llvm/llvm-project@a9ff1ce)
* `--enable-stdcall-fixup` (llvm/llvm-project@ce211c505b82e5bbb68b936968d9b54608285416)
* rc files containing multiple strings without commas (llvm/llvm-project@beb0e7e) (Fixes #9106).

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Why not Clang 12.0.1 ?

**Comment by jeremyd2019** [comment]
I don't know.  I guess it might get rid of some of the upstream patches at least, if we're lucky.

**Comment by jeremyd2019** [comment]
Nope, all the patches still applied.

**Comment by jeremyd2019** [comment]
I'll let CI chew on it, but would probably make sense to close this PR and open a fresh one with a less misleading branch name (I don't think I can change that).

**Comment by lazka** [comment]
>  less misleading branch name

they are not part of the history anyway

**Comment by jeremyd2019** [comment]
I believe they are by default in the commit message of the merge commit, but it asks when merging a pull request, so can be changed there.

**Comment by jeremyd2019** [comment]
Oops, I guess renaming the branch in github website closed the pull request.

**Pull request closed without merging**
