### PR TITLE
Upgrade ncurses to 6.3

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by JPeterMugaas** [comment]
I think the failures are due to transient network problems.

**Comment by Biswa96** [comment]
The defined pgp key is wrong in the PKGBUILD file. See the change here https://github.com/archlinux/svntogit-packages/commit/3795c6d8064d5199c3a7b08d142c78e6fbdf605a

**Comment by JPeterMugaas** [comment]
Something on my system got out of whack and I do not comfortable or skilled enough to rebase so I'm closing this.  I will resubmit it.

**Comment by Biswa96** [comment]
Alright. In this type of case, I delete my local branch, create a new one from master with same branch name, add my modifications and force push it.

**Pull request closed without merging**
