### PR TITLE
lerc: update to 4.0.0

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by kmilos** [comment]
Argh, libjxl is not yet available for clangarm64, will have to patch this up...

**Comment by Biswa96** [comment]
It's OK, many packages disable some dependency for clangarm64. e.g. ffmpeg, spice-gtk etc.

**Comment by kmilos** [comment]
I know it's ok, it's just extra work I wasn't prepared for and can't do this instant - it's not just having the conditional in the deps list, have to patch the imagecodecs source as well as it doesn't to automatic detection...

**Comment by Biswa96** [comment]
It may be better to update imagecodecs in a separate pull request.

**Comment by kmilos** [comment]
This version depends on the Lerc version being bumped, so kinda have to merge them together...

**Comment by kmilos** [comment]
Let's just wait for the next libjxl release, we haven't had that feature enabled yet anyway...

**Pull request merged**
