### PR TITLE
paraview: 5.11.0

### PR DESCRIPTION
**Pull request by MehdiChinoune**
@hmartinez82 Could you please test building it on clangarm64.

Fixes #15964

### CODE REVIEW

**Comment by hmartinez82** [comment]
Sure thing. I'll do it today after lunch

**Comment by MehdiChinoune** [comment]
@hbadi Could you test the built package (download from CI artifacts and install with `pacman -U`)

**Comment by hbadi** [comment]
Hi @MehdiChinoune,
Not sure to understand, where can I find the built package from CI artifacts ?
Can you explicit the steps ?
Thanks.

**Comment by hmartinez82** [comment]
@hbadi , the checks below create the packages . You can find them here https://github.com/msys2/MINGW-packages/actions/runs/4316041546

**Comment by hbadi** [comment]
Great !
Does the packages was compiled using vtk external packages ? Cause paraview cmake uses it's own vtk sources (it can be very long to compile). I posted a message on paraview discourse [post](https://discourse.paraview.org/t/paraview-with-mingw64/11543/2) and guys asked cmake was not write to use external vtk binaries.

**Comment by MehdiChinoune** [comment]
It was built using its internal vtk.

**Pull request merged**
