### PR TITLE
[WIP] shotcut

### PR DESCRIPTION
**Pull request by mingwandroid**
Hi friends.

I cannot figure how to get the exe into the right place here. Any help greatly appreciated. I'm too long out of practice here I fear and on too many meds. Pinging @elieux, @naveen521kk and @lazka.

It seems to nearly be working other than that!

### CODE REVIEW

**Comment by mingwandroid** [comment]
Wow, this seems to work to an extent now and looks nice!

**Comment by mingwandroid** [comment]
Frei0r plugins arent being found and ui elements are amiss but its good progress none the less.

**Comment by lazka** [comment]
Moved to https://github.com/msys2/MINGW-packages-dev/commit/fbfcd94491772d7e0

**Comment by Biswa96** [comment]
Can I move that to main repository? I have built this recently.

**Comment by lazka** [comment]
Sure.

**Comment by lazka** [comment]
Added in 23b21bf9fa4cbed

**Pull request closed without merging**
