### PR TITLE
make[critical]: Fix bad timestamps on mingw32

### PR DESCRIPTION
**Pull request by orgads**
Fixes a critical regression between 4.3 and 4.4.

### CODE REVIEW

**Comment by Biswa96** [comment]
Did you asked upstream about this patch? If yes, can you add a comment with url of that upstream commit or thread? It'd help to track the patch in future.

**Comment by lazka** [comment]
lgtm

**Comment by orgads** [comment]
https://lists.gnu.org/archive/html/bug-make/2022-11/msg00017.html

**Comment by orgads** [comment]
I'll add it as a comment in PKGBUILD.

**Comment by orgads** [comment]
Done

**Comment by lazka** [comment]
in the repo now, thanks

**Pull request merged**
